### ISSUE TITLE
Interop Marshalling moved

### ISSUE THREAD

**Issue by AaronRobinsonMSFT** [dotnet/docs#6629]
The `Interop Marshalling` topic should be moved to the more general .NET Guide. See dotnet/coreclr#19090 and dotnet/coreclr#19082.

This topic is relevant to both .NET Framework _and_ .NET Core. There are some minor differences on .NET Core when on Non-Windows platforms, but largely the same when either runtime is on Windows.

cc @jkotas

**Comment by rpetrusha** [comment]
An interop section has been created in dotnet/docs/docs/standard (see #13402), but the difference in exception handling remains to be noted.
