### ISSUE TITLE
Problem with the statement 'The ?? operator defines a default value that is returned when a nullable type is assigned to a non-nullable type.'

### ISSUE THREAD

**Issue by matthewkrieger** [dotnet/docs#6630]
The statement 'The ?? operator defines a default value that is returned when a nullable type is assigned to a non-nullable type.' may be misleading or inaccurate.  The ?? operator doesn't care what type of assignment is being made.  I think a better description would be to indicate that ?? is the null coalescing operator which per https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/null-coalescing-operator, simply "...returns the left-hand operand if the operand is not null; otherwise it returns the right hand operand."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2552ed95-c11d-4657-0dad-9e0cccba9ca4
* Version Independent ID: 326dd492-3549-0312-3d46-a179d3fe76c6
* Content: [Using Nullable Types (C# Programming Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/nullable-types/using-nullable-types)
* Content Source: [docs/csharp/programming-guide/nullable-types/using-nullable-types.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/nullable-types/using-nullable-types.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by pkulikov** [comment]
@matthewkrieger that's a good observation, thank you for reporting. I'll update the topic this week.

**Comment by BillWagner** [comment]
Thanks @pkulikov  I've assigned this to you.
