### ISSUE TITLE
Outdated serialization information

### ISSUE THREAD

**Issue by kappa7194** [dotnet/docs#6637]
The paragraph

> In fact, none of the fields that contain private key information can be serialized. If you try to serialize an RSAParameters structure with a remoting call or by using one of the serializers, you will receive only public key information. If you want to pass private key information, you will have to manually send that data. In all cases, if anyone can derive the parameters, the key that you transmit becomes useless.

is outdated. The `[NonSerialized]` attribute has been removed with pull request [22862](https://github.com/dotnet/corefx/pull/22862), merged back in corefx with commit [7eed79f](https://github.com/dotnet/corefx/commit/7eed79faf47e8e8dbe1645fb002e52c306867347) on 2017-08-02, as of today the attribute [is missing](https://github.com/dotnet/corefx/blob/7eed79faf47e8e8dbe1645fb002e52c306867347/src/System.Security.Cryptography.Algorithms/src/System/Security/Cryptography/RSAParameters.cs). The paragraph should be removed.

**N.b.** This change applies only to .NET Core ≥ 2.1.0.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cec592a3-82b8-f4d5-ddfa-9e113209f113
* Version Independent ID: 8cb9de04-a0fb-f27a-a848-68bbd52f0396
* Content: [RSAParameters Struct (System.Security.Cryptography)](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.rsaparameters?view=netcore-2.1)
* Content Source: [xml/System.Security.Cryptography/RSAParameters.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Security.Cryptography/RSAParameters.xml)
* Product: **.net**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by taspeotis** [comment]
When will the information be outdated for the full framework? The attributes [are present](https://referencesource.microsoft.com/#mscorlib/system/security/cryptography/rsa.cs,dfd6cfff509b13df) for .NET Framework 4.7.2.

**Comment by kappa7194** [comment]
> The attributes are present for .NET Framework 4.7.2.

Right, I forgot to specify that the change applies only to .NET Core ≥ 2.1.0.
