### ISSUE TITLE
Buffering contradiction

### ISSUE THREAD

**Issue by breyed** [dotnet/docs#6638]
The remarks make two statements, which seem contradictory:
1. The returned `Task<Result>` object will complete after the whole response body is read.
2. This method does not buffer the stream.

Based on statement 1, the application can't start using the stream until the whole body is read, because it won't have access to the `Stream` object via `Task<Stream>.Result` until the task completes. But if the stream isn't accessible until the whole body is read, that body has to be buffered; otherwise, it would be lost. So statement 2 can't also be true.

Statement 1 seems likely to be a copy and paste error:
1. Waiting until the whole response body is read would largely defeat the purpose of using a stream. If all HTTP clients worked that way, we wouldn't have web pages that display as the load, progressive images, videos that play as the load, etc.
2. Statement 1 refers to `Task<TResult>` even though the return type is always the more specific `Task<Stream>`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d631c3d1-c266-5828-015f-ab08ce377542
* Version Independent ID: a6438168-4ae4-33b3-bb89-b17f0e987d2e
* Content: [HttpClient.GetStreamAsync Method (System.Net.Http)](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.getstreamasync?view=netframework-4.7.2#System_Net_Http_HttpClient_GetStreamAsync_System_String_)
* Content Source: [xml/System.Net.Http/HttpClient.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Http/HttpClient.xml)
* Product: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks @breyed for your feedback.

@stephentoub @davidsh can you confirm that we should change the docs for issue 1?

For issue 2, we could change the link to display the more specific type. By default, our API links will use the generic signature.

**Comment by davidsh** [comment]
This sentence is wrong:

*"This operation will not block. The returned Task<TResult> object will complete after the whole response body is read. This method does not buffer the stream."*

HttpClient.GetStreamAsync() does not read the response body.  So, it should say something like this:

*"This operation will not block. The returned Task<TResult> object will complete after the response headers are read. This method does not read nor buffer the response body."*
