### ISSUE TITLE
Where is the callback definitions? 

### ISSUE THREAD

**Issue by krestenks** [dotnet/docs#6643]
How do you set callbacks for mouse clicks on the MenuItems? This is not described. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe3d5478-8556-d72d-8ab1-81bfd8139aaf
* Version Independent ID: 7ed38399-5313-776e-9886-475dc5e3e61d
* Content: [ContextMenu Overview](https://docs.microsoft.com/en-us/dotnet/framework/wpf/controls/contextmenu-overview)
* Content Source: [docs/framework/wpf/controls/contextmenu-overview.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/controls/contextmenu-overview.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by JRAlexander** [comment]
Thanks for your feedback, @krestenks! This has been added to the backlog.
