### ISSUE TITLE
async await and TPL

### ISSUE THREAD

**Issue by atiq-cs** [dotnet/docs#6644]
where is the updated version of this to look at for TPL and async and await?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a04219c-aacc-199c-66b9-d3a394f5fac0
* Version Independent ID: 289ca45c-cdd4-94c6-56ec-922a587108b3
* Content: [The Managed Thread Pool](https://docs.microsoft.com/en-us/dotnet/standard/threading/the-managed-thread-pool)
* Content Source: [docs/standard/threading/the-managed-thread-pool.md](https://github.com/dotnet/docs/blob/master/docs/standard/threading/the-managed-thread-pool.md)
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by pkulikov** [comment]
@atiq-cs 
For TPL, please check 
https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/task-parallel-library-tpl

For async/await, you can start with (the **See Also** section contains more links):
https://docs.microsoft.com/en-us/dotnet/standard/async-in-depth

**Comment by atiq-cs** [comment]
Hi, Thank you very much. Where is updated documentation for thread pools such as worker threads and IOCP ?
