### ISSUE TITLE
CS0177 and array

### ISSUE THREAD

**Issue by ChuckDev922** [dotnet/docs#6647]
You might want to mention the case when the parameter is an array:
static void MyMethod(out int[] arr)
{
arr = new int[10];   // definite assignment of arr
...
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3a74f91-8081-cb02-b990-f8809e148415
* Version Independent ID: 2a3e3a63-9d32-3d60-16b4-400557119c77
* Content: [Compiler Error CS0177](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs0177)
* Content Source: [docs/csharp/misc/cs0177.md](https://github.com/dotnet/docs/blob/master/docs/csharp/misc/cs0177.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by svick** [comment]
Why do you think this should be mentioned here? What makes arrays different than any other type?

**Comment by rpetrusha** [comment]
Thanks for your feedback, @ChuckDev922, although I agree with @svick.  An array type is not a special case, nor does it require any special handling in a method with the `out` keyword. I'm going to close this issue. If you disagree, however, feel free to respond.
