### ISSUE TITLE
Out of scope and bad conventions

### ISSUE THREAD

**Issue by berkarslan-cs** [dotnet/docs#6658]
This article contains lots of examples that are out of the scope of this documentation. The excessive length of the documentation makes the document require too much time.

Another point is that the author's coding style is annoying. Using single lines for if else foreach conditions, not using any code comments, bad naming conventions (appending m_ for variables? really?? not a good practice..) should be fixed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cabcc3ba-9033-c65f-8969-482a436d510b
* Version Independent ID: a74714e2-d059-e33f-a8c6-591d988ef2a4
* Content: [Consuming the Task-based Asynchronous Pattern](https://docs.microsoft.com/en-us/dotnet/standard/asynchronous-programming-patterns/consuming-the-task-based-asynchronous-pattern#configuring-suspension-and-resumption-with-yield-and-configureawait)
* Content Source: [docs/standard/asynchronous-programming-patterns/consuming-the-task-based-asynchronous-pattern.md](https://github.com/dotnet/docs/blob/master/docs/standard/asynchronous-programming-patterns/consuming-the-task-based-asynchronous-pattern.md)
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by JRAlexander** [comment]
Thank you for your feedback, @berkarslan-cs.  This has been added to the backlog.

**Comment by MarkCBB** [comment]
I've found the content of this article really interesting, complete and helpful to learn the Task-based Asynchronous Pattern (in my case studying for the C# certification). I wouldn't vote to remove any content, everything written here makes sense, is handy and is good for learning (from my point of view) but is true that some code examples can be written clearer.
