### ISSUE TITLE
missing content

### ISSUE THREAD

**Issue by BenWestbrook** [dotnet/docs#6659]
"...See Also
IPV6 Socket Sample..."

bad link

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffd48e88-8264-f6cb-3ac6-bcbe7fbed373
* Version Independent ID: 27c955c6-1790-599d-d604-f87446d3ca3c
* Content: [Internet Protocol Version 6](https://docs.microsoft.com/en-us/dotnet/framework/network-programming/internet-protocol-version-6)
* Content Source: [docs/framework/network-programming/internet-protocol-version-6.md](https://github.com/dotnet/docs/blob/master/docs/framework/network-programming/internet-protocol-version-6.md)
* Product: **dotnet-framework**
* GitHub Login: @mcleblanc
* Microsoft Alias: **markl**

**Comment by rpetrusha** [comment]
Thank you for reporting another broken link, @BenWestbrook. The intended URL is https://msdn.microsoft.com/en-us/library/ms180981(v=vs.85).aspx. We'll open a PR to correct the broken link shortly.
