### ISSUE TITLE
Runtime difference between .net and .netcore

### ISSUE THREAD

**Issue by jackbond** [dotnet/docs#6664]
On .netcore after creating a new instance of ECDsaCng from a CngKey, you must manually set the HashAlgorithm property. When running on full framework it is automatically populated. Is this a bug or a feature?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec4a500f-7745-5009-c93e-dc873b621b78
* Version Independent ID: b04ed007-af05-2806-b19b-82f0cfafef6f
* Content: [ECDsaCng Class (System.Security.Cryptography)](https://docs.microsoft.com/en-gb/dotnet/api/system.security.cryptography.ecdsacng?view=netcore-2.0)
* Content Source: [xml/System.Security.Cryptography/ECDsaCng.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Security.Cryptography/ECDsaCng.xml)
* Product: **.net**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by rpetrusha** [comment]
@bartonjs, can you answer the question from @jackbond?

**Comment by bartonjs** [comment]
Looks like a bug. opened https://github.com/dotnet/corefx/issues/31376 for it.

@jackbond The best workaround is to not depend on the property.  That is, switch to using `ECDsa.SignData` or `ECDsa.VerifyData` overloads which take a `HashAlgorithmName` parameter.  The property (and the method overloads which rely on it) is not available on ECDsa implementations for Linux or macOS.

**Comment by jackbond** [comment]
Just to clarify, we're using the System.Security.Cryptography.Cng Nuget library, which I thought was Windows only (unfortunately) We're using version 4.5.0 (currently the latest) and it does not include the overloads you mentioned.

**Comment by jackbond** [comment]
It's in core, but I'm referencing the Nuget package in a .netstandard library, so that overload is not available.

**Comment by bartonjs** [comment]
There must be something wrong with tooling, because those methods on ECDsa were added in .NET Standard 1.4, the same version that the ECDsa type was added to .NET Standard.  You shouldn't be able to talk about ECDsa without seeing them, except for targeting .NET Framework directly (in which case the type came in 3.5 and I fixed the base class for 4.6.1).

**Comment by JRAlexander** [comment]
@bartonjs, has this been resolved? Thanks!

**Comment by bartonjs** [comment]
It's resolved in master, but not in the wild.

**Comment by JRAlexander** [comment]
Ok, I'll leave this open, then. Thanks!

**Comment by bartonjs** [comment]
@JRAlexander  Oh, I interpreted the question wrong :).  I don't know that we want a docs change, since it's tracked as a product bug.

**Comment by JRAlexander** [comment]
Ah, ok. I'll close this, then. Thanks!
