### ISSUE TITLE
Doesn't have the same capabilities as msbuild

### ISSUE THREAD

**Issue by SidShetye** [dotnet/docs#6666]
> The command has the exact same capabilities as existing MSBuild command-line client. 

This is wrong. If you try invoking msbuild on a SSDT `.sqlproj` project `msbuild.exe` actually works while `dotnet msbuild` fails with error shown below. 

```
error MSB4019: The imported project "C:\Program Files\dotnet\sdk\2.1.300\Microsoft\VisualStudio\v10.0\SSDT\Microsoft.Data.Tools.Schema.SqlTasks.targets" was not found. Confirm that the path in the &lt;Import&gt; declaration is correct, and that the file exists on disk.
```

The desired behavior is that if dotnet cannot support a specific project type it should defer to msbuild instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9083568-6c58-1c1b-0062-10632e61a88d
* Version Independent ID: a1d47471-9482-9f69-f11e-3424e62383f6
* Content: [dotnet msbuild command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-msbuild)
* Content Source: [docs/core/tools/dotnet-msbuild.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-msbuild.md)
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
@KathleenDollard @dsplaisted @livarcocc can one of you please comment on this feedback? Does dotnet msbuild support building .sqlproj projects? 
I'm wondering if I should clarify in the topic that "The command has the exact same capabilities as existing MSBuild command-line client" for supported .NET Core project types?

**Comment by dsplaisted** [comment]
It doesn't support .sqlproj or a bunch of other project types.

I think the intent of the doc is that all of the same command-line options are supported by `dotnet msbuild` that `msbuild` supports.

**Comment by DavidChennells** [comment]
It would be awesome if documentation for the dotnet cli could be more explicit about which project types are supported.  (And even more awesome if all build engines/options/clis used by VS to build VS-supported project types could be exposed via dotnet cli passthrough commands.)

Here is the use case:  I am migrating a large ASP NET Core solution from full framework to NET Core.  A migration path for getting there is migrating suitable dependent, subsidiary projects to .NET Standard, while a few other projects and the main web project temporarily remain full framework pending partial re-writes.  NET Standard project types are well supported by the CLI, and that's led me to extensive use of the dotnet CLI in my rebuild/migration scripts.  It would be simpler if a single CLI tool (and documentation repository) could support both the mixed, full framework phase and the final all-NET Core phase.

**Comment by mairaw** [comment]
@KathleenDollard @dsplaisted do we have the list of all support project types supported by the CLI somewhere? This would probably be good information to add to the main tools topic at https://docs.microsoft.com/en-us/dotnet/core/tools/

**Comment by KathleenDollard** [comment]
+ @cartermp

**Comment by cartermp** [comment]
Thanks, I agree that this is a good thing to have, but not in this doc specifically. Beyond a project that uses a .NET SDK-style SDK moniker, I'm not fully aware of everything `dotnet msbuild` can handle.

**Comment by atrauzzi** [comment]
Hmm, I'm not seeing a full list of supported project types anywhere. @mairaw - Did it end up at a different page?

Moreover, I'd love to see a master list somewhere of all extant *proj formats in the Microsoft ecosystem and their levels of support and deprecation.
