### ISSUE TITLE
Description for resourceExtension is missing content.

### ISSUE THREAD

**Issue by AppFzx** [dotnet/docs#6668]
The definition for "XAML Values &gt; resourceExtension" is "One of the following: or . This usage is used..." but it appears there's an air gap on both sides of the "or" where two possible values for resourceExtension should go.  e.g. it should read "One of the following: _______possibility_1________ or _________possibility_2_________. This usage is used"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d33ed34a-3b73-2b51-914f-230226acc07a
* Version Independent ID: a18f223c-79b0-c73a-5f0e-3d343b88c519
* Content: [FrameworkElement.DataContext Property (System.Windows)](https://docs.microsoft.com/en-us/dotnet/api/system.windows.frameworkelement.datacontext?view=netframework-4.7.2)
* Content Source: [xml/System.Windows/FrameworkElement.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Windows/FrameworkElement.xml)
* Product: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
Thanks for pointing out that text had dropped out of the documentation, @AppFzx. The lost text is [StaticResource](https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/staticresource-markup-extension) or [`DynamicResource`](https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/dynamicresource-markup-extension). I'll open a PR to restore the lost text shortly.
