### ISSUE TITLE
Using a what?

### ISSUE THREAD

**Issue by amp64** [dotnet/docs#6669]
"Setting a visual property will only have an effect if that property is both present in MenuItem control's default template and is set by using a . You can find" - set by using a WHAT exactly?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1bd77fb-e845-d8f2-cce7-eab07f0ebe91
* Version Independent ID: 14d31d7d-f925-bbcb-1b86-3202cce19132
* Content: [MenuItem Class (System.Windows.Controls)](https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.menuitem?view=netframework-4.7.1)
* Content Source: [xml/System.Windows.Controls/MenuItem.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Windows.Controls/MenuItem.xml)
* Product: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
Thanks for noticing the missing text, @amp64. It should be "set by using a [TemplateBinding](https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/templatebinding-markup-extension). I'll open a PR to restore the text shortly.
