### ISSUE TITLE
Example incomplete

### ISSUE THREAD

**Issue by amp64** [dotnet/docs#6670]
The example shows how to define a style, but doesn't show how to use it, and that isn't obvious to me anyway.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f92fcdc-57c9-a8ce-4e4b-cf7fd96cf1f4
* Version Independent ID: ae7c367e-8a3c-81a4-7dcb-5652d72a7dc7
* Content: [MenuItem.SeparatorStyleKey Property (System.Windows.Controls)](https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.menuitem.separatorstylekey?view=netframework-4.7.1#System_Windows_Controls_MenuItem_SeparatorStyleKey)
* Content Source: [xml/System.Windows.Controls/MenuItem.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Windows.Controls/MenuItem.xml)
* Product: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by amp64** [comment]
User error, never mind.

**Comment by JRAlexander** [comment]
No worries, @amp64! Thanks for closing. Keep at it and have a great day!
