### ISSUE TITLE
Missing documentation on DefaultExpression.

### ISSUE THREAD

**Issue by rcsteiner** [dotnet/docs#6686]
No example, when used with default value on parameter, it comes back null, so it doesn't appear to useful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 556b4527-96e6-e733-9a12-58af0eca6ac4
* Version Independent ID: 95c64b5f-2e19-16b5-1cf3-2f1f04f076b0
* Content: [VCCodeParameter.DefaultExpression Property (Microsoft.VisualStudio.VCCodeModel)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.vccodemodel.vccodeparameter.defaultexpression?view=netframework-1.1)
* Content Source: [xml/Microsoft.VisualStudio.VCCodeModel/VCCodeParameter.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.VisualStudio.VCCodeModel/VCCodeParameter.xml)
* Product: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks @rcsteiner for your feedback. I need to investigate some issues related to API docs that might be causing this.

**Comment by mairaw** [comment]
PR https://github.com/dotnet/dotnet-api-docs/pull/411 fixed this as there were some 1.1 assemblies that were causing conflicts with the VS SDK ones.
