### ISSUE TITLE
More on Docker and .NET Core

### ISSUE THREAD

**Issue by mindems** [dotnet/docs#6687]
For those of you who want to explore further, feel free to check out my tutorials at https://github.com/mindems/Docker.NET.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 849478c4-6c54-f01e-aa8e-f3a5baea1cb1
* Version Independent ID: e11a4a6b-ecaa-8a6a-75e6-543e40716b19
* Content: [Docker and .NET Core](https://docs.microsoft.com/en-us/dotnet/core/docker/)
* Content Source: [docs/core/docker/index.md](https://github.com/dotnet/docs/blob/master/docs/core/docker/index.md)
* Product: **dotnet-core**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by rpetrusha** [comment]
Thanks for the comment, @mindems. This issue isn't actionable, so I'm going to close it. However, feel free to add a link to your tutorials in  [.NET Open Source Developer Projects](https://github.com/Microsoft/dotnet/blob/master/dotnet-developer-projects.md). In your PR, you can add a new section, **Tutorials**, and provide the link, link text, and description.
