### ISSUE TITLE
Persistence Location of key container

### ISSUE THREAD

**Issue by JamesMBristow2** [dotnet/docs#6688]
The storage location behavior is opposite of the ASP.NET tool aspnet_regiis.exe; the key container is saved in the user's profile by default. Set the CspParameters.Flags to specify the machine container.
Example: 
csp.Flags = CspProviderFlags.UseMachineKeyStore. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf319632-8038-7d57-38ee-c6423c02c1d2
* Version Independent ID: b7f7eb2d-0422-0699-ff0d-143cce350731
* Content: [How to: Store Asymmetric Keys in a Key Container](https://docs.microsoft.com/en-us/dotnet/standard/security/how-to-store-asymmetric-keys-in-a-key-container)
* Content Source: [docs/standard/security/how-to-store-asymmetric-keys-in-a-key-container.md](https://github.com/dotnet/docs/blob/master/docs/standard/security/how-to-store-asymmetric-keys-in-a-key-container.md)
* Product: **dotnet**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment]
It would be nice to at least mention in this article how to set the store. We don't need to mention **aspnet_regiis**.
