### ISSUE TITLE
All of documentation for WPF attached events has disappeared

### ISSUE THREAD

**Issue by sayurin** [dotnet/docs#6690]
[DragDrop.DragOver Attachedevent (System.Windows)](https://docs.microsoft.com/en-us/dotnet/api/system.windows.dragdrop.dragover?view=netframework-4.7.1) has no document. But [previus verion](https://msdn.microsoft.com/en-us/library/system.windows.dragdrop.dragover(v=vs.110).aspx) are well documented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f2fa756-4cb1-fd2a-b192-d14d5324a293
* Version Independent ID: 0fb2f7de-4494-d59c-d01d-cd1c8591c477
* Content: [DragDrop.DragOver Attachedevent (System.Windows)](https://docs.microsoft.com/en-us/dotnet/api/system.windows.dragdrop.dragover?view=netframework-4.7.1#feedback)
* Content Source: [xml/System.Windows/DragDrop.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Windows/DragDrop.xml)
* Product: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
Thanks for your feedback, @sayurin. The documentation for attached properties and attached events was lost when we migrated from our previous authoring system to GitHub. We are aware of the issue and expect that the documentation will be available on docs.microsoft.com in the near future.
