### ISSUE TITLE
The "XML Markup Compatibility Specification" link is dead

### ISSUE THREAD

**Issue by BillHally** [dotnet/docs#6695]
The "XML Markup Compatibility Specification" link is dead

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 535bc2da-9b3d-8aac-04ba-2c998820c706
* Version Independent ID: b06edade-3a83-5d42-d0c7-846c9e784ebd
* Content: [mc:Ignorable Attribute](https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/mc-ignorable-attribute)
* Content Source: [docs/framework/wpf/advanced/mc-ignorable-attribute.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/advanced/mc-ignorable-attribute.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
This issue should look for the same link throughout our repos. A quick workaround is to fix the Fwlink internally.

**Comment by mairaw** [comment]
And thanks for reporting this @BillHally!
