### ISSUE TITLE
Thank you very much for sharing

### ISSUE THREAD

**Issue by lutayashafiq** [dotnet/docs#6697]
Thank you very much for sharing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ff2f7d2-0adc-6471-f126-47bd6760d61c
* Version Independent ID: 396c0154-32c1-3d9c-5fc8-885604c22f71
* Content: [How to: Use the Try-Catch Block to Catch Exceptions](https://docs.microsoft.com/en-us/dotnet/standard/exceptions/how-to-use-the-try-catch-block-to-catch-exceptions)
* Content Source: [docs/standard/exceptions/how-to-use-the-try-catch-block-to-catch-exceptions.md](https://github.com/dotnet/docs/blob/master/docs/standard/exceptions/how-to-use-the-try-catch-block-to-catch-exceptions.md)
* Product: **dotnet**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by JRAlexander** [comment]
You are welcome!
