### ISSUE TITLE
Request to add the description about the risk of calling Thread.Abort

### ISSUE THREAD

**Issue by tomoshi-public** [dotnet/docs#6700]
I'd like to add the following description in order to prevent the developers from the risk of calling Thread.Abort. I'd appreciate if you consider my proposal text for Remarks section.

"When Abort is called, the thread on which it is invoked may be terminated before executing the code you expected. It will be a cause of an unexpected problem like a resouce leak that was used in unmanaged code."

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 9ad07e0b-045f-1883-6bbd-5f98dba08fcd
* Version Independent ID: 3764f95f-640e-b437-215a-b61cae9ec11e
* Content: [Thread.Abort Method (System.Threading)](https://docs.microsoft.com/ja-jp/dotnet/api/system.threading.thread.abort?view=netframework-4.7.2)
* Content Source: [xml/System.Threading/Thread.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Threading/Thread.xml)
* Product: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks for the feedback @tomoshi-public. We'll look into your suggestion.
