### ISSUE TITLE
Duplicate examples

### ISSUE THREAD

**Issue by sfilipi** [dotnet/docs#6705]
There are two examples displaying in this page, and in the source xml:
https://github.com/dotnet/ml-api-docs/blob/smoke-test-preview/dotnet/xml/Microsoft.ML.Trainers/LightGbmBinaryClassifier.xml

The xml on the dll, contains only one example section:
      &lt;seealso cref="T:Microsoft.ML.Trainers.NaiveBayesClassifier" /&gt;
      &lt;example&gt;
        &lt;code language="csharp"&gt;
          pipeline.Add(OneVersusAll.With(new StochasticDualCoordinateAscentBinaryClassifier()));
        &lt;/code&gt;
      &lt;/example&gt;
    &lt;/member&gt;

 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22dc2bd3-0a8c-5353-8a3c-fceb390601f1
* Version Independent ID: aa246821-aa5c-977b-49a0-d0eca632a5ab
* Content: [LightGbmBinaryClassifier Class (Microsoft.ML.Trainers)](https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.ml.trainers.lightgbmbinaryclassifier?view=ml-dotnet&branch=smoke-test-preview)
* Content Source: [dotnet/xml/Microsoft.ML.Trainers/LightGbmBinaryClassifier.xml](https://github.com/dotnet/ml-api-docs/blob/smoke-test-preview/dotnet/xml/Microsoft.ML.Trainers/LightGbmBinaryClassifier.xml)
* GitHub Login: @dotnet-bot

**Comment by JRAlexander** [comment]
@sfilipi - I'm going to close this as I think it's been resolved. Please reopen if that's not the case.
