### ISSUE TITLE
Any way to install one tool located in my machine ?

### ISSUE THREAD

**Issue by ucavalcante** [dotnet/docs#6706]
im develop one console app and want know if i can install without publish with nuget for testing purpuse.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0c5b03c-2854-8462-57dc-b0239388096e
* Version Independent ID: 13b38200-ed54-7bfe-f7cf-099cf1b010f4
* Content: [.NET Core Global Tools](https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools)
* Content Source: [docs/core/tools/global-tools.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/global-tools.md)
* Product: **dotnet-core**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **mairaw**

**Comment by KathleenDollard** [comment]
@ucavalcante 

I assume you are creating a global tool with dotnet pack with PackAsTool == true in the project. 

1) You tool is a normal console application. You can test it's functionality by calling it directly or by using unit tests. When that is done...

2) `dotnet pack` and use the `--output` switch to put your package on your local drive
This creates a local NuGet package in the location you specify.

To test the installation of your tool use the `--add-source` switch on `dotnet tool install` to find your package. You may also specify a `--tool-path` if you'd prefer to keep the tool you're testing separated from your other install tools. 

Let me know if that isn't enough to get you started.

**Comment by JRAlexander** [comment]
Going to go ahead and close this as it appears resolved. @ucavalcante, if that isn't the case, please reopen. Thanks!

**Comment by johnkors** [comment]
@KathleenDollard / @JRAlexander , I came here for the same thing. Might be useful to addition to the docs. Currently the `--tool-path` is documented, but it would be even clearer if you had a specific "How to test your tools locally" section.

**Comment by JohnTortugo** [comment]
What's the default list of feeds the `dotnet tool` search the package on?

**Comment by KathleenDollard** [comment]
@JohnTortugo 

Internally, this uses standard NuGet restore. It uses the normal NuGet.config (or it's default)

@wli3 for more nuance if needed.
