### ISSUE TITLE
What are the advantages of auto implemented properties?

### ISSUE THREAD

**Issue by jbstcyr** [dotnet/docs#6707]
What are the advantages of auto implemented properties and why does the VS2017 ide suggest using them in Visual Basic?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5eef8ea6-7067-a274-6b6c-84ea894941ad
* Version Independent ID: f6820eb1-15a6-2988-bf98-82355c68d81a
* Content: [Auto-Implemented Properties (Visual Basic)](https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/language-features/procedures/auto-implemented-properties)
* Content Source: [docs/visual-basic/programming-guide/language-features/procedures/auto-implemented-properties.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/programming-guide/language-features/procedures/auto-implemented-properties.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by zyx-zyx-zyx** [comment]
1. It saves time. 
2. It is less error-prone.

They are functionally equivalent, except the compiler will create and manage the backing field for you, saving the developer from having to declare a private backing field.

If you are going to have any functionality to your getter/setter, you must implement this yourself.

For quick properties with no special functionality, this is the way to go.

**Comment by tbradner1** [comment]
Why not make the private backing field protected so you can use inheritance?

**Comment by BillWagner** [comment]
> Why not make the private backing field protected so you can use inheritance?

Usually the data is private, for better protection.

**Comment by BillWagner** [comment]
These questions have been answered. Closing this.
