### ISSUE TITLE
ShowDialog may crash

### ISSUE THREAD

**Issue by schmidhorst** [dotnet/docs#6708]
My VB.net application was during debugging with VS2015 terminating at ShowDialog() (Exit code 0x4000001f). Not possible to catch it with try catch. [See also](https://social.msdn.microsoft.com/Forums/de-DE/694862ac-b0c2-4a92-8980-deaf94c42ef5/vs2015-openfiledialog-erzeugt-vshostexe-wurde-mit-code-1073741855-0x4000001f?forum=visual_studiode) and [here](https://stackoverflow.com/questions/4532457/program-and-debugger-quit-without-indication-of-problem).
It was caused by shndlers.dll, which belongs to the "1&1 Upload Manager", which maps a WebDAV item to the namespace. 

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 7d98b3a2-313d-eb55-faef-c19ad74c7442
* Version Independent ID: 105d9f6d-997d-04d4-dd1e-4c99e96c01fe
* Content: [OpenFileDialog Class (System.Windows.Forms)](https://docs.microsoft.com/de-de/dotnet/api/system.windows.forms.openfiledialog?view=netframework-4.7.2)
* Content Source: [xml/System.Windows.Forms/OpenFileDialog.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Windows.Forms/OpenFileDialog.xml)
* Product: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks for your feedback @schmidhorst. Given that this issue might happen in other circumstances as well,  we don't think this should be documented on this API page. 
But please let us know if you disagree.
