### ISSUE TITLE
Default Values

### ISSUE THREAD

**Issue by Blackglade** [dotnet/docs#6715]
Could you please include an area indicating the default value of the property/field/variable/etc... when it isn't specifically set or altered?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a5a6157-0af8-5b76-5c0e-ae08d9dc0edf
* Version Independent ID: fa64606c-d998-92c4-ca7f-c861aa90c2ab
* Content: [ScrollViewer.VerticalScrollBarVisibility Property (System.Windows.Controls)](https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.scrollviewer.verticalscrollbarvisibility?view=netframework-4.7.2)
* Content Source: [xml/System.Windows.Controls/ScrollViewer.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Windows.Controls/ScrollViewer.xml)
* Product: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
@Blackglade thanks for sending your feedback. We try to include that information in the text and I see this API already has that information, so I'll be closing this bug. 

![image](https://user-images.githubusercontent.com/12971179/43479930-967032aa-94b6-11e8-9ef3-d1188725db60.png)

If you'd like the layout to change for all property pages to include a new section, I'd suggest that you file a feature request at https://github.com/microsoftdocs/feedback to be reviewed and considered by the engineering team.
