### ISSUE TITLE
Syntax of the filter expression

### ISSUE THREAD

**Issue by vrapp** [dotnet/docs#6719]
It would right step to mention that the syntax of the filter is described in the article "DataColumn.Expression Property".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 364b6a9b-8cd5-b8aa-d59c-350575e9c42b
* Version Independent ID: b70fee57-6424-5bbf-9e12-d851b4c7e1ab
* Content: [BindingSource.Filter Property (System.Windows.Forms)](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.bindingsource.filter?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(System.Windows.Forms.BindingSource.Filter);k(TargetFrameworkMoniker-.NETFramework,Version%3Dv4.6.2);k(DevLang-VB)%26rd%3Dtrue&view=netframework-4.7.2)
* Content Source: [xml/System.Windows.Forms/BindingSource.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Windows.Forms/BindingSource.xml)
* Product: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks for your feedback @vrapp. The remarks say "If the underlying data source is a DataSet, DataTable, or DataView, you can specify Boolean expressions using the syntax documented for the DataColumn.Expression property." 

We believe this is already documented then, so we'll be closing this issue. Let us know if we missed anything.
