### ISSUE TITLE
Download PDF

### ISSUE THREAD

**Issue by BelarminoVicenzo** [dotnet/docs#6721]
You should do something with the formatting when downloaded to PDF.
When I download, all text comes normal, without the colors. Something that is very important.
It makes more difficult to read the code.
See for yourselves https://prnt.sc/kccpgm 

So I had to manually copy-paste all docs, literally all them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc2fe8f7-b023-5aa7-52c2-b9c1c5c13ded
* Version Independent ID: 18c373d4-02f9-4cc6-656d-9cf4d11f6498
* Content: [C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/index#feedback)
* Content Source: [docs/csharp/programming-guide/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/index.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by JRAlexander** [comment]
Thanks for your feedback, @BelarminoVicenzo. @dend - Can you comment on this?

**Comment by mairaw** [comment]
Given this is a general issue with docs.microsoft.com, I've moved it to https://github.com/MicrosoftDocs/feedback/issues/565, so it can get properly routed. 

@dastaffo FYI
