### ISSUE TITLE
ManualResetEvent API: no Set/Reset methods

### ISSUE THREAD

**Issue by pkulikov** [dotnet/docs#6722]
The [ManualResetEvent](https://docs.microsoft.com/en-us/dotnet/api/system.threading.manualresetevent?view=netframework-4.7.2) inherits [EventWaitHandle](https://docs.microsoft.com/en-us/dotnet/api/system.threading.eventwaithandle?view=netframework-4.7.2). Thus, it's expected to have [Set](https://docs.microsoft.com/en-us/dotnet/api/system.threading.eventwaithandle.set?view=netframework-4.7.2) and [Reset](https://docs.microsoft.com/en-us/dotnet/api/system.threading.eventwaithandle.reset?view=netframework-4.7.2) methods. However, [the class overview page in the API browser](https://docs.microsoft.com/en-us/dotnet/api/system.threading.manualresetevent?view=netframework-4.7.2#methods) lists neither `Set` nor `Reset` methods:

![image](https://user-images.githubusercontent.com/15279990/43365541-ac1aa402-932e-11e8-85d9-236a378a1c02.png)

Note, it lists inherited [SetAccessControl method](https://docs.microsoft.com/en-us/dotnet/api/system.threading.eventwaithandle.setaccesscontrol?view=netframework-4.7.2)

Where have `Set` and `Reset` methods disappeared? 

You find two if you check the TOC:
![image](https://user-images.githubusercontent.com/15279990/43365560-ff101e12-932e-11e8-8ea7-4b8b36e79ea7.png)

Selecting one of them brings to the method version for .NET Framework 1.1 (that's why those two are not in the table for the .NET Framework 4.7.2):
![image](https://user-images.githubusercontent.com/15279990/43365587-5d0a09d8-932f-11e8-879b-fcc481063f83.png)

The related XML (is it the case that the member belonged to `ManualResetEvent` class in .NET Framework 1.1, but later was moved to `EventWaitHandle`? Because of that the below XML doesn't contain later assembly versions?):
```xml
    <Member MemberName="Reset">
      <MemberSignature Language="C#" Value="public bool Reset ();" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig instance bool Reset() cil managed" />
      <MemberSignature Language="DocId" Value="M:System.Threading.ManualResetEvent.Reset" />
      <MemberSignature Language="VB.NET" Value="Public Function Reset () As Boolean" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; bool Reset();" />
      <MemberSignature Language="F#" Value="member this.Reset : unit -&gt; bool" Usage="manualResetEvent.Reset " />
      <MemberType>Method</MemberType>
      <AssemblyInfo>
        <AssemblyName>mscorlib</AssemblyName>
        <AssemblyVersion>1.0.5000.0</AssemblyVersion>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>System.Boolean</ReturnType>
      </ReturnValue>
      <Parameters />
      <Docs>
        <summary>To be added.</summary>
        <returns>To be added.</returns>
        <remarks>To be added.</remarks>
      </Docs>
    </Member>
```

That's not expected. Expected behavior is to see inherited `Set` and `Reset` methods.

/cc: @mairaw  @dend

**Comment by mairaw** [comment]
Thanks @pkulikov. This seems the same issue as https://github.com/MicrosoftDocs/feedback/issues/616, so I'm closing this one as duplicate.
