### ISSUE TITLE
Wrote 5 Blog Posts for ML.net inspired from theses documentation.

### ISSUE THREAD

**Issue by abhiongithub** [dotnet/docs#6723]
*********This is not a Issue ******** 
This is a comment on ML Documentation Page, somehow it is registered as Issue , Someone please close it.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e855e630-1a30-d138-4ac6-bfeefebf9aae
* Version Independent ID: afc0a7d1-d3c2-acf2-d4ea-d2565e22b237
* Content: [ML.NET tutorials](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/)
* Content Source: [docs/machine-learning/tutorials/index.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/index.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by JRAlexander** [comment]
Great to hear! Closing per your request.
