### ISSUE TITLE
config-file option

### ISSUE THREAD

**Issue by ianwalkeruk** [dotnet/docs#6729]
In documented examples, --config-file is provided as a way to specify a custom config file. However, this switch is not part of the synopsis, and gives an error if used

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b363ab07-ea19-574f-e0db-25fd5702255d
* Version Independent ID: 6fa9479a-85db-5498-6b7e-2418fc7bac32
* Content: [dotnet nuget push command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-nuget-push?tabs=netcore21)
* Content Source: [docs/core/tools/dotnet-nuget-push.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-nuget-push.md)
* Product: **dotnet-core**
* GitHub Login: @karann-msft
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Thanks for reporting this @ianwalkeruk. I'll investigate this.

**Comment by mairaw** [comment]
@karann-msft should I just remove that last example?

**Comment by karann-msft** [comment]
@mairaw - yes I guess for now we could do that.
