### ISSUE TITLE
Inner-loop development workflow for Kubernetes-based applications

### ISSUE THREAD

**Issue by spacecat** [dotnet/docs#6732]
Hi,

Could you post an exact same (in-detail) article on INNER-loop development workflow for Kubernetes-based (AKS) applications (how to setup Visual Studio, what extensions/tools to install, inner-loop development workflows, build and run, debug and testing etc - basically the same type of content in this article but for Kubernetes)?

Also, it would be good to put a note at the top to let people know.

Oh, and by the way, where can I find good resources on this topic (Visual Studio, ASP.NET Core, AKS)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b69a4b5-2003-e7a5-97a3-59e3737ea1ef
* Version Independent ID: 0df5f0d7-a2b4-e9b3-9f34-d66cedf418a3
* Content: [Development workflow for Docker apps](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/docker-application-development-process/docker-app-development-workflow)
* Content Source: [docs/standard/microservices-architecture/docker-application-development-process/docker-app-development-workflow.md](https://github.com/dotnet/docs/blob/master/docs/standard/microservices-architecture/docker-application-development-process/docker-app-development-workflow.md)
* Product: **dotnet**
* GitHub Login: @CESARDELATORRE
* Microsoft Alias: **wiwagn**

**Comment by spacecat** [comment]
Maybe this is the resource I was looking for?

https://docs.microsoft.com/en-us/visualstudio/deployment/tutorial-kubernetes-tools

**Comment by JRAlexander** [comment]
@spacecat, it looks like this has been resolved, so I'm going to close this issue. If this isn't correct, please reopen. Thanks!
