### ISSUE TITLE
Dispose

### ISSUE THREAD

**Issue by ofer987** [dotnet/docs#6733]
Hi, 

I believe that you meant to write `try/finally` instead of `try/catch` in the Remarks section (https://docs.microsoft.com/en-ca/dotnet/api/system.diagnostics.process?view=netcore-2.1#remarks).

This text:

This type implements the IDisposable interface. When you have finished using the type, you should dispose of it either directly or indirectly. To dispose of the type directly, call its Dispose method in a try/catch block. To dispose of it indirectly, use a language construct such as using (in C#) or Using (in Visual Basic). For more information, see the "Using an Object that Implements IDisposable" section in the IDisposable interface topic.

Should be

To dispose of the type directly, call its Dispose method in a try/finally block.

Instead of

To dispose of the type directly, call its Dispose method in a try/catch block.

As of https://docs.microsoft.com/en-ca/dotnet/api/system.idisposable?view=netcore-2.1#the-tryfinally-block.

Thanks,
-Dan

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84993cb7-37e6-01ef-9b25-8cea57f5a125
* Version Independent ID: 723dcba4-f26d-7567-77af-4e93f41a0df9
* Content: [Process Class (System.Diagnostics)](https://docs.microsoft.com/en-ca/dotnet/api/system.diagnostics.process?view=netcore-2.1#remarks)
* Content Source: [xml/System.Diagnostics/Process.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Diagnostics/Process.xml)
* Product: **.net**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by JRAlexander** [comment]
Thanks for your feedback, @ofer987! It's been added to the backlog.
