### ISSUE TITLE
How to setup a repo to build and test .NET Framework and .NET Core applications

### ISSUE THREAD

**Issue by richlander** [dotnet/docs#674]
We need a tutorial on this.

**Comment by BillWagner** [comment]
I agree.

Comments / questions:

I assume you mean a CI build on GitHub on the main repo, on PRs. Bonus points for displaying the badges on the homepage of the repo.

Do you mean build the framework, or build your application *built* on the framework or Core?

I think this could become a meta-issue on multiple paths, if you mean applications build on the framework:

- Platform independent libraries
- Libraries with Native dependencies (you'll need to configure the build environment for the different environments.
- Mobile apps (does Hockey App apply here?)
- Cordova / Taco?
- Xamarin builds (for both Android and iOS)?

Let's discuss the scope you want here.

**Comment by mairaw** [comment]
@richlander can you clarify here what you want to see? Is this about building your own version of .NET Core/.NET Framework?

**Comment by richlander** [comment]
Ah ... I _think_ I meant this:

- "Hey, you just setup a new repo on GH/VSTS".
- "You probably want more than just idle C# files in source control."
- "You probably want builds and unit test results and maybe even Docker images. Either on every commit or nightly or both."
- "Email notifications saying something is happening would be good, too."
- "You might think you are asking too much. I've got you covered."
- "You know, it's Valentine's day."

**Comment by BillWagner** [comment]
[This page](https://docs.microsoft.com/en-us/vsts/release-notes/2017/nov-28-vsts) should provide ample source material. cc

**Comment by mairaw** [comment]
Would this be part of our repo or Azure DevOps content @richlander?
