### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by tstedel** [dotnet/docs#6740]
All instances of "Run This Sample" are broken links

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6638825c-e251-07c2-db62-711e677b8ed2
* Version Independent ID: 68488b20-6c17-1a8d-1618-b87aeaac78fe
* Content: [Easing Functions](https://docs.microsoft.com/en-us/dotnet/framework/wpf/graphics-multimedia/easing-functions#feedback)
* Content Source: [docs/framework/wpf/graphics-multimedia/easing-functions.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/graphics-multimedia/easing-functions.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks for reporting this issue @tstedel. We no longer have that functionality working so we should remove this link from the topics that are using it.
