### ISSUE TITLE
Update for Windows 10 look-and-feel?

### ISSUE THREAD

**Issue by wjk** [dotnet/docs#6743]
The documentation for this class includes specific instructions for how to work with the now outdated and obsolete Aero Glass UI in Windows Vista and Windows 7. The look-and-feel has changed significantly in Windows 8, and again in Windows 10. This API is still supported as far as I can tell, but I do not know how to make it work, and make it look good, under the Windows 10 theme with the existing information. Thanks for looking into this!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51b688a4-ceb5-6e73-78c1-45e7a4c37ab8
* Version Independent ID: 56918f97-3d7a-eac5-7141-3064ca392b98
* Content: [WindowChrome Class (System.Windows.Shell)](https://docs.microsoft.com/en-us/dotnet/api/system.windows.shell.windowchrome?view=netframework-4.7.2)
* Content Source: [xml/System.Windows.Shell/WindowChrome.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Windows.Shell/WindowChrome.xml)
* Product: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by JRAlexander** [comment]
Thanks for your feedback, @wjk! It's been added to the backlog.

**Comment by mairaw** [comment]
@sambent can you help with this feedback?

**Comment by SamBent** [comment]
This is a feature request.  I've shared it with management for awareness.

**Comment by mairaw** [comment]
Ok, thanks for the prompt reply. Is there a better place to move this feedback to?
