### ISSUE TITLE
Offline Installation

### ISSUE THREAD

**Issue by kevo970** [dotnet/docs#6747]
I need to update as computer that is not permitted to have an internet connection by my company's IT department.  Is there an option for offline installation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea654e23-2ec5-637e-99c3-8870b895030c
* Version Independent ID: 9c054590-c5e3-199c-b852-e1a856b4aae7
* Content: [Install the .NET Framework 3.5 on Windows 10, Windows 8.1, and Windows 8](https://docs.microsoft.com/en-us/dotnet/framework/install/dotnet-35-windows-10)
* Content Source: [docs/framework/install/dotnet-35-windows-10.md](https://github.com/dotnet/docs/blob/master/docs/framework/install/dotnet-35-windows-10.md)
* Product: **dotnet-framework**
* GitHub Login: @rlander
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
You need to use the DISM command-line tool for that @kevo970. You can check the instructions for no Internet connectivity at https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/deploy-net-framework-35-by-using-deployment-image-servicing-and-management--dism connectivity. 

I hope this helps.

**Comment by Reza-Ka** [comment]
It is easy
first you need DVD or any other media which you have installed windows 10 and connect to computer 
you should run gpedit in run of windows and then follow steps
1- select  administrative  on computer configuration
2- select system
3-double click on specify  setting for optional component installation and component repair 
4- click Enable and then write "x:\sources\sxs" in alternative source path box.
     x is name of drive of your source windows media instalation
5- open turn windows features on or off in control panel 
6- active box of .net framework 3.5 and click OK and waiting to finish.
then ENJOY it

**Comment by Pgierlach** [comment]
The ISO we have received from IT doesn't have x:\sources\sxs directory. When we try to install .Net 3.5 from Win10 iso from microsoft website it says that there is a version mismatch.

**Comment by g0pinath** [comment]
How about Azure VM, can you please add instructions on how to mount the DVD on Azure VM.
