### ISSUE TITLE
A small typo

### ISSUE THREAD

**Issue by akemimadoka** [dotnet/docs#6750]
In C, function parameter list should be (void) to declare a function which does not receive any argument.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 678eaef3-eec4-dc52-1234-37e220f84682
* Version Independent ID: 38b09163-65d8-4d6c-1394-401e080ed6f0
* Content: [Marshaling Data with Platform Invoke](https://docs.microsoft.com/en-us/dotnet/framework/interop/marshaling-data-with-platform-invoke)
* Content Source: [docs/framework/interop/marshaling-data-with-platform-invoke.md](https://github.com/dotnet/docs/blob/master/docs/framework/interop/marshaling-data-with-platform-invoke.md)
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by rpetrusha** [comment]
Thanks for pointing out the absence of the `void` type, @akemimadoka. I've opened PR #6754 to address the issue, as well as to correct the formatting of pointers.
