### ISSUE TITLE
Typo in the description of this page

### ISSUE THREAD

**Issue by alirizvi2008** [dotnet/docs#6751]
Occurs when s static resource reference is resolved.

should be 
Occurs when a static resource reference is resolved.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6adc8ee-0e84-16ec-4946-8968eb886a48
* Version Independent ID: 4bf284ab-a5df-f0f1-8a2b-45b487102b1e
* Content: [ResourceDictionaryDiagnostics.StaticResourceResolved Event (System.Windows.Diagnostics)](https://docs.microsoft.com/en-us/dotnet/api/system.windows.diagnostics.resourcedictionarydiagnostics.staticresourceresolved?view=netframework-4.7.2#feedback)
* Content Source: [xml/System.Windows.Diagnostics/ResourceDictionaryDiagnostics.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Windows.Diagnostics/ResourceDictionaryDiagnostics.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by JRAlexander** [comment]
Thanks for reporting this, @alirizvi2008! I'll make the change now and you should see it live in a few days.
