### ISSUE TITLE
Hierarchy of topics in the documentations.

### ISSUE THREAD

**Issue by sunilmhta** [dotnet/docs#6753]
I think the documentation is good in itself but I find hard to find my topics in the documentation without googling it.  So  the documentation should be arranged in a hierarchical way so that we can find it easily and it will help us to understand the hierarchy of the classes and other objects.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc2fe8f7-b023-5aa7-52c2-b9c1c5c13ded
* Version Independent ID: 18c373d4-02f9-4cc6-656d-9cf4d11f6498
* Content: [C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/index)
* Content Source: [docs/csharp/programming-guide/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/index.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by JRAlexander** [comment]
Thank you for your feedback, @sunilmhta. What topics are you having difficulty finding?

**Comment by sunilmhta** [comment]
I was at C# programming guide page (https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/index). I wanted to explore all the headers ( I am from C++ background, so sorry if I use wrong terminologies) but I couldn't find them. Then I went to Collections from this page under the language section, there also  I felt that the language section should be in the left side (just beneath the C# programming guide. I am sorry if it is still not making much sense but I think cpprefernce (https://en.cppreference.com/w/cpp) is very well organized in this manner and I think any documentation should be organized like this. I am sorry if I am biased.

**Comment by BillWagner** [comment]
I added this to our backlog. 

This is valuable feedback, and addressing it will be a project in its own. When we pull this from the backlog, we'll define a set of tasks to address it.

**Comment by BillWagner** [comment]
I'm closing this based on [this gist](https://gist.github.com/BillWagner/047cb97f6c0fe542d3a1299e994b2acd) proposing a new TOC. We're working toward that organization.
