### ISSUE TITLE
Format Error?

### ISSUE THREAD

**Issue by wschin** [dotnet/docs#6755]
I saw "xref data-throw-if-not-resolved="true"" in the document, is it supposed to happen? I also saw some words are cut in that line.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7716b5cd-1280-3d9d-bc82-48b88ef57467
* Version Independent ID: 346173f4-dc4a-b8cc-7284-5a7a4343d1e0
* Content: [OnnxConverter.Convert(PredictionModel) Method (Microsoft.ML.Models)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.models.onnxconverter.convert?view=ml-dotnet)
* Content Source: [dotnet/xml/Microsoft.ML.Models/OnnxConverter.xml](https://github.com/dotnet/ml-api-docs/blob/live/dotnet/xml/Microsoft.ML.Models/OnnxConverter.xml)
* GitHub Login: @dotnet-bot

**Comment by JRAlexander** [comment]
Thanks for your feedback, @wschin! Nope, not supposed to happen. I've added it to the backlog.
