### ISSUE TITLE
GetCallingAssembly example is not informative

### ISSUE THREAD

**Issue by lambdageek** [dotnet/docs#6758]
The example for `System.Reflection.Assembly.GetCallingAssembly()` is not informative: it consists of a single `Main` function directly calling `GetCallingAssembly` with a comment illustrating that the expected output is the name of that very assembly.  (There is also some dead code that creates an integer and gets its type and assembly - none of which are used again and don't contribute to the clarity of the example.)

A better example would be something like this:

```csharp
// Assembly FirstAssembly
using System;
using System.Reflection;
using System.Runtime.CompilerServices;
namespace FirstAssembly {
public class InFirstAssembly {
  public static void Main () {
     FistMethod ();
     SecondAssembly.InSecondAssembly.OtherMethod ();
  }

  [MethodImpl(MethodImplOptions.NoInlining)]
  public static void FirstMethod () {
    Console.WriteLine ("FirstMethod called from: " + Assembly.GetCallingAssembly ().FullName);
  }
}
}

// Assembly SecondAssembly
using System;
using System.Reflection;
using System.Runtime.CompilerServices;

namespace SecondAssembly {
class InSecondAssembly () {
  [MethodImpl (MethodImplOptions.NoInlining)]
  public static void OtherMethod () {
    Console.WriteLine ("OtherMehod executing assembly: " + Assembly.GetExecutingAssembly ().FullName);
    Console.WriteLine ("OtherMethod called from: " + Assembly.GetCallingAssembly ().FullName);
  }
}
// Expected output:
//  "FirstMethod called from: FirstAssembly, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null"
// "OtherMethod executing assembly: SecondAssembly, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null"
// "OtherMethod called from: FirstAssembly, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null"
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 589f27b3-22a8-1c87-46d6-25c13ec450de
* Version Independent ID: 56d1e4a7-b852-44fa-5fed-be6c60c6e2c7
* Content: [Assembly.GetCallingAssembly Method (System.Reflection)](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.assembly.getcallingassembly?view=netframework-4.7.2#System_Reflection_Assembly_GetCallingAssembly)
* Content Source: [xml/System.Reflection/Assembly.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Reflection/Assembly.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
Thank you for an excellent suggestion, @lambdageek. Would you like to update the documentation with the your example by opening PRs in the dotnet/samples and dotnet/dotnet-api-docs repos?

**Comment by lambdageek** [comment]
@rpetrusha Sure, I can give it a try.  Couple of questions:

1. In dotnet-api-docs I see the following:
https://github.com/dotnet/dotnet-api-docs/blob/d66fd6b485a6051f371e0a22ee8820cc15d44636/xml/System.Reflection/Assembly.xml#L986-L988

which means that that's where the corresponding snippet lives.  So I would open a PR on the dotnet/samples repo and edit the snippet file?

2. I don't speak C++/CLI or VB, is it alright if I just PR the C# example?
