### ISSUE TITLE
Need Visual Studio release details

### ISSUE THREAD

**Issue by davkean** [dotnet/docs#6772]
Visual Basic 15.3 and Visual Basic 15.5 do not document the release of Visual Studio that they come out in.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 272fdffd-2201-990f-387b-d37467e976cf
* Version Independent ID: 06703ef5-e10a-3fdd-da13-0ce99903a5e6
* Content: [What's new for Visual Basic](https://docs.microsoft.com/en-us/dotnet/visual-basic/getting-started/whats-new#visual-basic-153)
* Content Source: [docs/visual-basic/getting-started/whats-new.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/getting-started/whats-new.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by davkean** [comment]
It looks like Visual Basic 15.5 came with Visual Studio 15.6, and maybe 15.3 with Visual Studio 15.5 but do not quote me on this. @jcouv would know details.

**Comment by jcouv** [comment]
VB and VS versions match: VB 15.5 came with VS 15.5, etc
https://github.com/dotnet/vblang/blob/master/Language-Version-History.md

**Comment by BillWagner** [comment]
@rpetrusha Is this something you are addressing in #6765 ?

**Comment by rpetrusha** [comment]
I hadn't planned to, @BillWagner, but since the PR is open and the change affects the what's new topic, I will address it in #6765.
