### ISSUE TITLE
Review/update documentation of the 'debug' C# compiler option

### ISSUE THREAD

**Issue by cremor** [dotnet/docs#6773]
Could you please review this page and make sure that it is actually correct? Because there are a few posts that claim that parts of that documentation is wrong or outdated.

A good starting point is [this question on StackOverflow](https://stackoverflow.com/questions/7713514/should-i-compile-release-builds-with-debug-info-as-full-or-pdb-only). The two highest voted answers both say that this documentation is outdated and they also provide links to further information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3029908f-c2ff-3620-7d51-b9f6a3b768dc
* Version Independent ID: 0f310c2a-3dc6-54a4-5014-264d7f727f2f
* Content: [-debug (C# Compiler Options)](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/debug-compiler-option)
* Content Source: [docs/csharp/language-reference/compiler-options/debug-compiler-option.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/debug-compiler-option.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by rpetrusha** [comment]
Thanks, @cremor, for your feedback. We'll have to investigate before we can revise the documentation.

**Comment by tmat** [comment]
https://github.com/dotnet/roslyn/blob/master/docs/compilers/CSharp/CommandLine.md has up to date documentation of the switch.

**Comment by BillWagner** [comment]
The current doc is missing `/debug:portable` and `/debug:embedded` descriptions.

The other key change i that `/debug:pdbonly` should be called out as a Windows only debug format. The `/debug:portable` would be preferred.

**Comment by tmat** [comment]
Also `/debug:pdbonly` is exactly the same as `/debug:full`. It's not really a Windows-only switch. 
It will produce Portable PDB on Linux and Windows PDB on Windows.

**Comment by tmat** [comment]
You can link https://github.com/dotnet/designs/blob/master/accepted/diagnostics/debugging-with-symbols-and-sources.md#pdb-formats that discusses the PDB formats.

**Comment by EsaHeikkiPoutanen** [comment]
Azure function c# Visual studio 2017, debugging locally, fine, remote debugging: 'no symbols have been loaded...' crap when I try to set up break, point ! Have tried various debug options with no results..
enfuriating !!!

**Comment by EsaHeikkiPoutanen** [comment]
Oh, and this only happens when using V2 fuctions and .net code, V1 functions, remote debugging works fine

**Comment by srikcgaa2** [comment]
This documentation is still out of sync because the newly added options such as embedded, portable are not updated while there are external documentation that describes this.  It will be good to capture the same information in this page as well

**Comment by ericsampson** [comment]
@IEvangelist this page is massively out of date and wrong.

**Comment by ericsampson** [comment]
@dotnet/docs this is still valid and important to update. Should be not hard.

**Comment by ericsampson** [comment]
@BillWagner I don't seem to be able to reopen this as the bot message suggests, I must not have the rights.

**Comment by akoeplinger** [comment]
Yeah only repo collaborators can reopen issues, that is a longstanding issue with GitHub: https://github.com/isaacs/github/issues/583

I also think this is still needed so reopening.

**Comment by BillWagner** [comment]
@dotnet/docs  should be sufficient to tag the team.

**Comment by sharwell** [comment]
@BillWagner The markdown to tag the team is `@dotnet/docs`. Only members of the org can use it.

**Comment by ericsampson** [comment]
yeah unfortunately I already tried to tag the group. Really unfortunate that externals like regular devs can't tag as described in the bot note.

**Comment by BillWagner** [comment]
@ericsampson 

> Really unfortunate that externals like regular devs can't tag as described in the bot note.

Yeah, that's annoying. I've sent email to my team and we're watching closely for comments.

**Comment by akoeplinger** [comment]
#22797 didn't fully fix the original issue since https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/code-generation#debugtype still only mentions `pdbonly`/`full` and misses the `portable` and `embedded` options, even though `portable` is the default and recommended option for new .NET projects now.

Reopening, @BillWagner not sure if this will put it in the correct GitHub tracking state so please fix if it's wrong :)
