### ISSUE TITLE
Correcting gamma for PathGradientBrush

### ISSUE THREAD

**Issue by Bilge** [dotnet/docs#6774]
This article only covers `LinearGradientBrush`, but the same section covers both linear gradients and path gradients. How do you apply gamma correction to a `PathGradientBrush`? If this is not possible, it appears to be a glaring hole in the API. Regardless, it should be mentioned in this article - whether it's possible or not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 295c10c9-d902-b818-2060-9f5541cf893a
* Version Independent ID: f71b13be-4506-174b-7087-68499bd3ea93
* Content: [How to: Apply Gamma Correction to a Gradient](https://docs.microsoft.com/en-us/dotnet/framework/winforms/advanced/how-to-apply-gamma-correction-to-a-gradient)
* Content Source: [docs/framework/winforms/advanced/how-to-apply-gamma-correction-to-a-gradient.md](https://github.com/dotnet/docs/blob/master/docs/framework/winforms/advanced/how-to-apply-gamma-correction-to-a-gradient.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by JRAlexander** [comment]
Thanks for the feedback, @Bilge. This has been added to the backlog.
