### ISSUE TITLE
The format of the encoding table is broken.

### ISSUE THREAD

**Issue by moyanming** [dotnet/docs#6776]
Please see the following picture.

BTW, I have test the Encoding.GetEncodings method ant only got 8 codepages within the Windows 10 IoT core OS. How to convert the ANSI (e.g. chinese ANSI) txt file to the UNICODE?
CodePage(WindowsCodePage) BodyName
1200(1200) utf-16
1201(1200) utf-16BE
12000(1200) utf-32
12001(1200) utf-32BE
20127(1252) us-ascii
28591(1252) iso-8859-1
65000(1200) utf-7
65001(1200) utf-8

Best regards.

![qq 20180801212128](https://user-images.githubusercontent.com/13234209/43524583-3c088c14-95d2-11e8-8b31-5b52a8456df1.jpg)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e108a631-9747-7d6e-dc36-280b0591cd68
* Version Independent ID: f630aa07-55fd-5352-f0c3-bd2e263cd70b
* Content: [Encoding Class (System.Text)](https://docs.microsoft.com/en-us/dotnet/api/system.text.encoding?view=netcore-2.1)
* Content Source: [xml/System.Text/Encoding.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Text/Encoding.xml)
* Product: **dotnet-api**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by rpetrusha** [comment]
Thanks for pointing this out, @moyanming. I've opened PR dotnet/dotnet-api-docs#406 to correct the table formatting.
