### ISSUE TITLE
Can you provide more details on the runtimes folder?

### ISSUE THREAD

**Issue by rschiefer** [dotnet/docs#6779]
I'm looking for more details about the runtimes folder inside the publish folder.  Is there a way to exclude runtimes you don't need?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 211afdc7-c796-202d-239d-823f2a499dff
* Version Independent ID: 9439897e-dcb3-bc2e-5cae-35c1ca2e0681
* Content: [dotnet publish command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-publish?tabs=netcore21)
* Content Source: [docs/core/tools/dotnet-publish.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-publish.md)
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by rpetrusha** [comment]
@rschiefer, thanks for your feedback. Have you taken a look at [.NET Core Application Deployment](https://docs.microsoft.com/en-us/dotnet/core/deploying/)?

**Comment by mairaw** [comment]
Closing due to the lack of response.
