### ISSUE TITLE
Doc: How to know that a NuGet library supports .NET Core

### ISSUE THREAD

**Issue by richlander** [dotnet/docs#678]
We need a doc on this.

There already is some content that talks about it, but not a single topic dedicated to it.

This should be both:
- I have the NuGet package.
- I am browsing a NuGet feed (NuGet.org, VS Online, ...)

**Comment by mairaw** [comment]
@kraigb would this be something that would be covered in the NuGet docs instead?

**Comment by kraigb** [comment]
Yes, I think this would be appropriate under Finding and Choosing Packages, http://docs.nuget.org/ndocs/consume-packages/finding-and-choosing-packages. I'll create an issue in the NuGet repo for that.

**Comment by BillWagner** [comment]
Closed, as this will be handled in the NuGet Repo. See https://github.com/NuGet/Home/issues/4109
