### ISSUE TITLE
incomplete xaml

### ISSUE THREAD

**Issue by gojanpaolo** [dotnet/docs#6789]
Sample for `textBoxInError` and `data`?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a0b0539-04a6-b652-ef55-b288545f897b
* Version Independent ID: 5b75a31b-3a21-02d0-6ffe-a57f567b037e
* Content: [How to: Implement Validation Logic on Custom Objects](https://docs.microsoft.com/en-us/dotnet/framework/wpf/data/how-to-implement-validation-logic-on-custom-objects)
* Content Source: [docs/framework/wpf/data/how-to-implement-validation-logic-on-custom-objects.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/data/how-to-implement-validation-logic-on-custom-objects.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
Thanks for letting us know that the sample code is incomplete, @gojanpaolo. We've created two PRs, dotnet/docs#6806 and dotnet/samples#217, to display all of the Window1.xaml file with the relevant code highlighted.

**Comment by gojanpaolo** [comment]
@rpetrusha Thanks for addressing this issue.

I'm currently looking at the [page](https://docs.microsoft.com/en-us/dotnet/framework/wpf/data/how-to-implement-validation-logic-on-custom-objects) and it seems nothing changed yet? Will it take time before the page updates? I assumed the page is fixed since the issue is closed. :)

**Comment by mairaw** [comment]
Yes @gojanpaolo. The update will be live later today.

**Comment by gojanpaolo** [comment]
@mairaw Alright! Thanks you :)
