### ISSUE TITLE
Clearing the concept

### ISSUE THREAD

**Issue by aby191** [dotnet/docs#6791]
Hi,

Nyc article with good understanding on the new and virtual keyword.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4702e20f-4482-e0ce-bf61-784d436b64d5
* Version Independent ID: c88cfd2b-fdee-64eb-c26c-4d808e82e8b6
* Content: [Knowing When to Use Override and New Keywords (C# Programming Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/knowing-when-to-use-override-and-new-keywords)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/knowing-when-to-use-override-and-new-keywords.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/knowing-when-to-use-override-and-new-keywords.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thank you for compliment.  Closing as kudos.
