### ISSUE TITLE
Missing link

### ISSUE THREAD

**Issue by ygoe** [dotnet/docs#6793]
"Windows Sockets version 2 API error code documentation in MSDN" should point to the information. Now I'll have to google it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84ff3356-3553-0460-3866-9a23dbea8d74
* Version Independent ID: 4369f846-6ba0-ed79-2696-9e8420b1d6b2
* Content: [SocketException.ErrorCode Property (System.Net.Sockets)](https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.socketexception.errorcode?view=netframework-4.7.2)
* Content Source: [xml/System.Net.Sockets/SocketException.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Sockets/SocketException.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by ygoe** [comment]
Here it is, the text is wrong. It's not in MSDN.

https://docs.microsoft.com/en-us/windows/desktop/winsock/windows-sockets-error-codes-2

**Comment by ChrisMaddock** [comment]
A note for whoever fixes this: the same phrase is used in 4/5 different API doc files. That's more than I can fix in the browser, I'm afraid! 😄

**Comment by mairaw** [comment]
Thanks @ChrisMaddock. I'll take care of this.
