### ISSUE TITLE
The code example in Docs was wrong

### ISSUE THREAD

**Issue by heaip** [dotnet/docs#6795]
On this page : https://docs.microsoft.com/en-us/dotnet/standard/collections/thread-safe/how-to-add-and-remove-items
TryUpdate method example :
     cities.TryUpdate(searchKey, retrievedValue, newValue)
should be:
     cities.TryUpdate(searchKey, newValue, retrievedValue)

newValue is the second parameter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39d05753-640a-9bb9-d548-77bc9e82616d
* Version Independent ID: 72d44346-2d65-2e97-75a5-7d6f7f5012e6
* Content: [How to: Add and Remove Items from a ConcurrentDictionary](https://docs.microsoft.com/en-us/dotnet/standard/collections/thread-safe/how-to-add-and-remove-items)
* Content Source: [docs/standard/collections/thread-safe/how-to-add-and-remove-items.md](https://github.com/dotnet/docs/blob/master/docs/standard/collections/thread-safe/how-to-add-and-remove-items.md)
* Product: **dotnet**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by jpreese** [comment]
Thanks for pointing this out @heaip! There are a couple open pull requests that should resolve this.
