### ISSUE TITLE
Remarks section missing word

### ISSUE THREAD

**Issue by nnpcYvIVl** [dotnet/docs#6797]
The Remarks section contains:
> You can also add the  to your application's configuration file.

It seems to be missing a word between the and to.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53e48129-8ce2-dc3c-9f92-ba5e11260eac
* Version Independent ID: e602e52c-23ce-fc33-e2d9-fc8b113fc95b
* Content: [HandleProcessCorruptedStateExceptionsAttribute Class (System.Runtime.ExceptionServices)](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.exceptionservices.handleprocesscorruptedstateexceptionsattribute?view=netframework-4.7.1)
* Content Source: [xml/System.Runtime.ExceptionServices/HandleProcessCorruptedStateExceptionsAttribute.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Runtime.ExceptionServices/HandleProcessCorruptedStateExceptionsAttribute.xml)
* Product: **dotnet-api**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by jpreese** [comment]
Thanks for finding this @nnpcYvIVl! There is now an open pull request to resolve this issue.
