### ISSUE TITLE
C# tutorials - threading

### ISSUE THREAD

**Issue by stevehoag** [dotnet/docs#68]
Show how to do multi-threading in C#.

Tutorials should include one or more code examples, each example should also show expected output and should include an explanation of the code where it isn't obvious. Examples shouldn't be dependent on a specific IDE or target platform.

**Comment by cartermp** [comment]
Should this be generalized to concurrency and parallelism?  Generally people don't new up `Thread` objects anymore, and the TPL is broad enough to warrant a general tutorial on concurrency and parallelism.

**Comment by rpetrusha** [comment]
Closing. There is already duplicated C# and Visual Basic threading content, but threading itself is a framework rather than a language feature.
