### ISSUE TITLE
Faulty PNG in link?

### ISSUE THREAD

**Issue by ironfey** [dotnet/docs#6803]
When trying to use the linked watermark.png I get file type not supported error. Does not happen with other (random) png.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0dc39f7-b153-a46c-3b88-07c8ed2c71bc
* Version Independent ID: 78a14535-9703-e2af-4451-783a7c4c10be
* Content: [Create a WPF application in Visual Studio](https://docs.microsoft.com/en-us/dotnet/framework/wpf/getting-started/walkthrough-my-first-wpf-desktop-application)
* Content Source: [docs/framework/wpf/getting-started/walkthrough-my-first-wpf-desktop-application.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/getting-started/walkthrough-my-first-wpf-desktop-application.md)
* Product: **dotnet-framework**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by ironfey** [comment]
PS: Windows 7 64 bit, Visual Studio 2017

**Comment by rpetrusha** [comment]
Thanks for pointing this out, @ironfey. We'll have to investigate and update your issue with our findings.,

**Comment by svick** [comment]
It works fine for me on Windows 10. Are you sure you downloaded the file correctly? Where exactly do you get that error?

**Comment by dhowes** [comment]
The instructions say "You can create your own image, copy the file from the sample code, or get it here." If you follow the "here" link you get to 

https://github.com/Microsoft/WPF-Samples/tree/master/Getting%20Started/WalkthroughFirstWPFApp

If you enter the csharp folder and save the file from the page (by right-clicking), the file you get is invalid. The link is

https://github.com/microsoft/WPF-Samples/blob/master/Getting%20Started/WalkthroughFirstWPFApp/csharp/watermark.png

You can download the source code by going to

https://github.com/microsoft/WPF-Samples

Download the repository and unzip it and get the image file from the csharp folder:

"\WPF-Samples-master\Getting Started\WalkthroughFirstWPFApp\csharp\watermark.png"

**Comment by svick** [comment]
@dhowes The watermark.png link at https://github.com/microsoft/WPF-Samples/tree/master/Getting%20Started/WalkthroughFirstWPFApp/csharp leads to a HTML page that shows the image and its git metadata. If you want to actually get the image, you have to go to that page and click the Download link.

I have created a PR (https://github.com/dotnet/docs/pull/13804) that bypasses all this and links directly to that image instead (using the same URL as the Download link). Do you think that that's better?
