### ISSUE TITLE
Switch examples to SHA256/512

### ISSUE THREAD

**Issue by joshbw** [dotnet/docs#6809]
Given that MD5 and RIPEMD160 are broken/weak hashing algorithms unsuitable for most applications, this example would be more useful if it referenced SHA256 or SHA512

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 410b53de-93ba-46c6-1fef-a8d66047a78c
* Version Independent ID: 32cc7592-abcd-5af9-4650-bdee2e30a40b
* Content: [HashAlgorithm.ComputeHash Method (System.Security.Cryptography)](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.hashalgorithm.computehash?view=netframework-4.7.1#feedback)
* Content Source: [xml/System.Security.Cryptography/HashAlgorithm.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Security.Cryptography/HashAlgorithm.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
Thanks, @joshbw, for pointing this out. We'll revise the examples in the near future.
