### ISSUE TITLE
Why use new() constraint in the Enumeration class?

### ISSUE THREAD

**Issue by stg609** [dotnet/docs#6812]
The implementaion is a little weird:

1、There's no public paramterless constructor, so how does the new() constraint work?
2、I don't see any necessary to new T() if just to get a static value. Why not use info.GetValue(null) directly?
3、The List method of the CarType doesn’t scale well, what if we need to add a new option?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d118f070-8743-e905-2d08-dc725a4e8b5f
* Version Independent ID: 4a95bf3d-1028-7c9e-5b7c-0733fc6addaa
* Content: [Using Enumeration classes instead of enum types](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/microservice-ddd-cqrs-patterns/enumeration-classes-over-enum-types)
* Content Source: [docs/standard/microservices-architecture/microservice-ddd-cqrs-patterns/enumeration-classes-over-enum-types.md](https://github.com/dotnet/docs/blob/master/docs/standard/microservices-architecture/microservice-ddd-cqrs-patterns/enumeration-classes-over-enum-types.md)
* Product: **dotnet**
* GitHub Login: @CESARDELATORRE
* Microsoft Alias: **wiwagn**

**Comment by svick** [comment]
@stg609 I agree with you on points 1 and 2, so I created Pull Requests https://github.com/dotnet/docs/pull/6967 and https://github.com/dotnet-architecture/eShopOnContainers/pull/704 to fix that.

I'm not sure about point 3, so I'll let someone else answer that.

**Comment by mvelosop** [comment]
Hi @stg609 

The book has been updated to current codebase.

You will not see it published until the PR #8201 goes through, though.

We'll keep discussion on https://github.com/dotnet-architecture/eShopOnContainers/pull/704.
