### ISSUE TITLE
>? description misspelling

### ISSUE THREAD

**Issue by fourst4r** [dotnet/docs#6815]
In the description for the &gt;? operator, the word "greater" is spelled "greather".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eda0064b-feb6-ccf5-b77c-92e59be17b0c
* Version Independent ID: 7f789b6e-4f55-5740-2c2f-2dec4e2129fc
* Content: [Symbol and Operator Reference (F#)](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/symbol-and-operator-reference/)
* Content Source: [docs/fsharp/language-reference/symbol-and-operator-reference/index.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/language-reference/symbol-and-operator-reference/index.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by rpetrusha** [comment]
Closing, Since #6821 merged.

@cartermp, for an issue to be auto-closed by a PR merge, the PR has to include "Fixes#".
