### ISSUE TITLE
Filtering of members

### ISSUE THREAD

**Issue by nvmkpk** [dotnet/docs#6818]
Please let us filter listed members like hiding inherited members like MSDN website had.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb8f7ce9-5aa7-5d81-7e38-87895240399c
* Version Independent ID: 868c1749-34cc-7de8-765b-411db7f1dd19
* Content: [ToolTaskExtension Class (Microsoft.Build.Tasks)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.build.tasks.tooltaskextension?view=netframework-4.7.2)
* Content Source: [xml/Microsoft.Build.Tasks/ToolTaskExtension.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Build.Tasks/ToolTaskExtension.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by JRAlexander** [comment]
Thank you for your feedback, @nvmkpk! I'll forward this on.

**Comment by JRAlexander** [comment]
I created [MicrosoftDocs/feedback/issues/581](https://github.com/MicrosoftDocs/feedback/issues/581), as it is a general Docs issue, and for proper routing.  Closing this issue. 

cc: @dastaffo FYI
