### ISSUE TITLE
Great article

### ISSUE THREAD

**Issue by zerple** [dotnet/docs#6819]
Hi, thanks for this really excellently written article which was easy to follow and I easily understood how to proceed with my testing cases. Thanks and again great work much appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e39c2f1b-f41a-bdf9-2646-09379941453d
* Version Independent ID: 422811cb-6287-03af-ba8d-1daebee9744d
* Content: [Unit testing C# code in .NET Core using dotnet test and xUnit](https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-with-dotnet-test)
* Content Source: [docs/core/testing/unit-testing-with-dotnet-test.md](https://github.com/dotnet/docs/blob/master/docs/core/testing/unit-testing-with-dotnet-test.md)
* Product: **dotnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **wiwagn**

**Comment by rpetrusha** [comment]
Thank you for the positive feedback, @zerple. We're happy that you're finding our documentation useful for your testing.
