### ISSUE TITLE
Observed significant execution time difference between "for" loop and "Parallel.For" loop

### ISSUE THREAD

**Issue by dilv0055** [dotnet/docs#6826]
I've tested pushing 1000 messages to Azure Service Bus queue with help of "for" loop  and "parallel.for" loop and calculated time using StopWatch class methods. 
=&gt; With help of "for" loop:  ** 1000 messages sending completed in "117.4382276" seconds.  
=&gt; With help of "Parallel.For" loop:  ** 1000 messages sending completed in "2.4045131" seconds.

Thank you contributors

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 629911c2-f9cc-7deb-df8e-3012d3e6afd0
* Version Independent ID: 1603adc7-b23f-ff8f-4c18-7c3f84fbcba8
* Content: [How to: Write a Simple Parallel.For Loop](https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/how-to-write-a-simple-parallel-for-loop#feedback)
* Content Source: [docs/standard/parallel-programming/how-to-write-a-simple-parallel-for-loop.md](https://github.com/dotnet/docs/blob/master/docs/standard/parallel-programming/how-to-write-a-simple-parallel-for-loop.md)
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by BillWagner** [comment]
Thank you @dilv0055 I'm glad this is useful.

Closing as kudos.
