### ISSUE TITLE
Create tutorials for how to build F# form apps (and F# apps in general) in Monodevelop for Linux users

### ISSUE THREAD

**Issue by jacqueline-homan** [dotnet/docs#683]
Since F# has been updated to 4.0, some things have been deprecated. While trying to get through Kit Eason's F# tutorial on Pluralsight, I found that **.nth** was deprecated and **.item** is now used instead. However, simply replacing .nth with .item did not work for me when trying to do that tutorial and I could not find any F# programming examples where .item was used in code. There are no tutorials at all for F# on Monodevelop, either -- which makes it nearly impossible for beginners trying to learn the language who don't have Windows and/or VS.

**Comment by mairaw** [comment]
@cartermp should we add this to Getting Started improvements project?

**Comment by cartermp** [comment]
Yep, we could so something like this.  I think the issue is that this represents new content entirely and we'll have to think about where it can best exist.  Right now we have getting started material for VS, VS ode, and the .NET CLI, but not MonoDevelop or VS for Mac.

**Comment by cartermp** [comment]
We now have content for VS for Mac and VSCode, which is sufficient for getting started in a supported environment with non-Windows OSes.
