### ISSUE TITLE
Update references to specific versions of Visual Studio, such as Visual Studio 2012

### ISSUE THREAD

**Issue by natejgardner** [dotnet/docs#6832]
This page refers to Visual Studio 2012. Shouldn't it be referring to a current version of Visual Studio?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c62caa2-710a-39c5-c016-28d74c877181
* Version Independent ID: 0d921e75-c19f-b01a-a5e0-d7795f4f443e
* Content: [How to: Host a WCF Service in a Managed Application](https://docs.microsoft.com/en-us/dotnet/framework/wcf/how-to-host-a-wcf-service-in-a-managed-application)
* Content Source: [docs/framework/wcf/how-to-host-a-wcf-service-in-a-managed-application.md](https://github.com/dotnet/docs/blob/master/docs/framework/wcf/how-to-host-a-wcf-service-in-a-managed-application.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
Thanks for your feedback, @natejgardner. Yes, it should be updated to reflect the current version of Visual Studio, @natejgardner. I've added it to the backlog, as well as to the community contributors' project.
