### ISSUE TITLE
Online 

### ISSUE THREAD

**Issue by U5Alekseevich** [dotnet/docs#6837]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ef7201b-e3d3-484c-c46f-0f2f257ddae3
* Version Independent ID: bc2b573a-40ac-a9fd-daa8-b5a5884b11c7
* Content: [Collections tutorial - C# local quickstarts](https://docs.microsoft.com/en-us/dotnet/csharp/quick-starts/arrays-and-collections)
* Content Source: [docs/csharp/quick-starts/arrays-and-collections.md](https://github.com/dotnet/docs/blob/master/docs/csharp/quick-starts/arrays-and-collections.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by rpetrusha** [comment]
I assume this was a test, @U5Alekseevich, so I'm closing this issue.
