### ISSUE TITLE
ReadAsync(Memory<byte> memory, CancellationToken cancellationToken) doesn't exist

### ISSUE THREAD

**Issue by ryzngard** [dotnet/docs#6846]
I was looking at using this method and can't find where it comes from. Clicking the documentation shows no override with this signature. Looking at the definition from netstandard.dll version 2.0.0.0 on my machine also doesn't have this method. 

My csproj: 

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.IO" Version="4.3.0" />
    <PackageReference Include="System.IO.Pipelines" Version="4.5.0" />
    <PackageReference Include="System.Memory" Version="4.5.1" />
  </ItemGroup>

</Project>

```

> &gt;dotnet --info
> .NET Core SDK (reflecting any global.json):
>  Version:   2.1.302
>  Commit:    9048955601
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.17134
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\2.1.302\
> 
> Host (useful for support):
>   Version: 2.1.2
>   Commit:  811c3ce6c0
> 
> .NET Core SDKs installed:
>   2.1.202 [C:\Program Files\dotnet\sdk]
>   2.1.302 [C:\Program Files\dotnet\sdk]
> 
> .NET Core runtimes installed:
>   Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
> 
> To install additional .NET Core runtimes or SDKs:
>   https://aka.ms/dotnet-download

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 968f92e0-aae5-7107-de5e-cdbbfe2f5daa
* Version Independent ID: ccf9cf00-2d05-3483-9530-470e18ae8e33
* Content: [FileStream Class (System.IO)](https://docs.microsoft.com/en-us/dotnet/api/system.io.filestream?view=netframework-4.7.2)
* Content Source: [xml/System.IO/FileStream.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.IO/FileStream.xml)
* Product: **dotnet-api**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by svick** [comment]
As far as I can tell, that overload is only available in .Net Core 2.1. I think the fact that it shows in the list of methods for `FileStream` for .Net Framework 4.7.2 is a bug.

![](https://user-images.githubusercontent.com/287848/43710755-ce2821f8-9970-11e8-90e3-283303b6a1b6.png)

**Comment by ryzngard** [comment]
That seems right, since I'm targeting .Net Standard 2.0. The documentation for `Stream` is correctly hiding that method for .Net Framework 4.7.2 and .Net Standard 2.0

**Comment by Thraka** [comment]
Right now there is nothing we can do about this type of problem. These main type pages (and the TOC itself) sort of pulls everything in for all frameworks. I've previously opened an internal bug about this and I will update it with reference to this issue.

Thanks for alerting us!

**Comment by ryzngard** [comment]
For my undestanding, is this due to it being an inherited method? The base stream page handles this correctly [https://docs.microsoft.com/en-us/dotnet/api/system.io.stream?view=netcore-2.0](https://docs.microsoft.com/en-us/dotnet/api/system.io.stream?view=netcore-2.0 )

Thanks for looking into this

**Comment by Thraka** [comment]
@rynowak Right now the web team has been alerted to this issue (which they sort of already knew about it) Not sure when a fix would be made but I know the whole experience is under constant evolution 😄 

I'm going to close this. Cheers!
