### ISSUE TITLE
Missing text in Remarks section 

### ISSUE THREAD

**Issue by malcolms** [dotnet/docs#6847]
Quick one - looks like some automated process has converted all references to "Keyboard" to "oard" in the remarks section:

"... through the static methods on the oard class, such as oard.IsKeyUp(System.Windows.Input.Key) and oard.GetKeyStates(System.Windows.Input.Key). The oard class reports the current state of the keyboard."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca14cb52-ed72-8c7c-c997-48327212880b
* Version Independent ID: 65284877-5147-eeca-4630-942b5a5a1899
* Content: [Key Enum (System.Windows.Input)](https://docs.microsoft.com/en-us/dotnet/api/system.windows.input.key?view=netframework-4.7.2#System_Windows_Input_Key_System)
* Content Source: [xml/System.Windows.Input/Key.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Windows.Input/Key.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
Thanks for reporting this content dropout, @malcolms. I've opened dotnet/dotnet-api-docs#423 to restore the dropped text.
