### ISSUE TITLE
Definition of POCO

### ISSUE THREAD

**Issue by mattfrear** [dotnet/docs#6851]
One thing that confused me here is the definition of POCO classes. I always thought a POCO class was one that had no methods, and just a bunch of properties with getters and setters. So I was wondering where the domain logic would be.
You eventually clarify it by saying 
&gt; It is important to note that this is a domain entity implemented as a POCO class. It does not have any direct dependency on Entity Framework Core or any other infrastructure framework.

But I think it would be improved if you define what you mean by a POCO class earlier in the book.

Thanks for a great book though, it solidified a lot of the DDD concepts for me.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49c9fdb0-f078-2030-204d-67d016b22c8d
* Version Independent ID: c37e4177-f0bd-de19-f53b-f597fbadcef0
* Content: [Implementing a microservice domain model with .NET Core](https://docs.microsoft.com/en-gb/dotnet/standard/microservices-architecture/microservice-ddd-cqrs-patterns/net-core-microservice-domain-model)
* Content Source: [docs/standard/microservices-architecture/microservice-ddd-cqrs-patterns/net-core-microservice-domain-model.md](https://github.com/dotnet/docs/blob/master/docs/standard/microservices-architecture/microservice-ddd-cqrs-patterns/net-core-microservice-domain-model.md)
* Product: **dotnet**
* GitHub Login: @CESARDELATORRE
* Microsoft Alias: **wiwagn**

**Comment by JRAlexander** [comment]
Thanks for your feedback, @mattfrear! Really glad you liked the book and we are taking the suggestion under consideration.
