### ISSUE TITLE
This returns a conversion error

### ISSUE THREAD

**Issue by crtjr64** [dotnet/docs#6852]
I'm using a process exactly like the example except the return types are different. Cannot convert lambda expression to intended delegate type because some of the return types in the block are not implicitly convertible to the delegate return type. My only difference is that var results and return results is replaced with a method that returns the return type. That's all this does is run that 1 method and I get this error. before trying to use Task in this instance, the method was working an returning the data type fine, but its an atomic database operation that's repeated. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68b95913-4dea-8160-0184-9aaf6c2c363e
* Version Independent ID: b779abdd-e97e-2fa5-87a9-76b859c38c7c
* Content: [How to: Return a Value from a Task](https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/how-to-return-a-value-from-a-task)
* Content Source: [docs/standard/parallel-programming/how-to-return-a-value-from-a-task.md](https://github.com/dotnet/docs/blob/master/docs/standard/parallel-programming/how-to-return-a-value-from-a-task.md)
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by BillWagner** [comment]
Thanks for writing this @crtjr64 

It's hard to know without seeing the code, but that error is generated when your lambda expression could return different types. Check the code carefully to make sure all return statements return the same type of object.

**Comment by mairaw** [comment]
Closing since we'd need to see the code to be able to help more.
