### ISSUE TITLE
Documention for the new "x is null" syntax.

### ISSUE THREAD

**Issue by verelpode** [dotnet/docs#6855]
Please document the lovely new "x is null" syntax that was added to C# 7.  I'm talking about this:  Open VS 2017 then click menubar -&gt; Tools -&gt; Options -&gt; Text Editor -&gt; C# -&gt; Code Style -&gt; General -&gt; "Prefer 'is null' over 'object.ReferenceEquals(..., null)'".

C# now allows us to write:
    if (x is null) {...}
instead of:
    if (object.ReferenceEquals(x, null)) {...}

Please document the difference between "x is null" versus "x == null", meaning the difference when the class contains an operator-overload for the "==" operator.  Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3126aaa9-8f5f-04f3-2d75-96477b6273cd
* Version Independent ID: 3f4b3eac-11eb-2dd6-4f27-b24537367288
* Content: [is (C# Reference)](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/is)
* Content Source: [docs/csharp/language-reference/keywords/is.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/is.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @verelpode you are correct. the `myVar is null` should be added.  I've added this to an upcoming milestone. 

I'm going to close #6856 as a duplicate. However, this syntax should be added in many places:

- [ ] docs/csharp/language-reference/keywords/is.md
- [ ] docs/csharp/language-reference/keywords/swiitch.md
- [ ] docs/csharp/pattern-matching.md (See #6856)
- [ ] docs/csharp/whats-new/csharp-7.md

**Comment by WayneGoosen** [comment]
@BillWagner I would like to help out. Could I please tackle this issue and submit a PR?

**Comment by BillWagner** [comment]
Thanks @WayneGoosen 

We'd be happy to have a PR on this. @- mention me if you have any questions. 

I'll suggest opening a WIP (Work in Progress) PR when you start an outline. I'll look for it.
