### ISSUE TITLE
Did it change since?

### ISSUE THREAD

**Issue by StingyJack** [dotnet/docs#6868]
&gt; In the .NET Framework version 2.0,
&gt; In version 1.0 of the .NET Framework,
&gt; In version 1.1 of the .NET Framework

These preambles imply the sentence topics that follow them only apply to that version and not versions before and not versions after.  Are some of them actually "Starting with version X.X of ..." ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed9b2a1c-66c1-5054-bff1-67d0ebc12089
* Version Independent ID: d1ffa572-246c-e85c-1491-2e08f34f4c52
* Content: [Making an Image Easier to Debug](https://docs.microsoft.com/en-us/dotnet/framework/debug-trace-profile/making-an-image-easier-to-debug)
* Content Source: [docs/framework/debug-trace-profile/making-an-image-easier-to-debug.md](https://github.com/dotnet/docs/blob/master/docs/framework/debug-trace-profile/making-an-image-easier-to-debug.md)
* Product: **dotnet-framework**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Thanks for your comment @StingyJack. We try to make future-proof content, when we know the changes are introduced at a certain version but this article probably hasn't been reviewed in a long time. So the most typical case will be "Starting with version X.X of ..."

@karelz can you point someone who could help us understand what has changed since with that area?

**Comment by StingyJack** [comment]
I think you are saying the sentences should begin as "Starting with..." rather than "In...", right?

**Comment by mairaw** [comment]
Yes, except when we really wanna call out something from a particular version. But I don't know in the case of this particular topic, if the correct thing would be in or starting with. This might have changed a lot since 2.0.

**Comment by rpetrusha** [comment]
The exception to "starting with" is 1.0 -- since it was the first version, any explicit mention of 1.0 typically means the behavior is limited to 1.0 and was changed in 1.1.

**Comment by karelz** [comment]
I am fairly confident, that all comments are meant as "X.Y+", so all can be replaced with "Starting with ..." (except the 1.0 call out from @rpetrusha).
@noahfalk can you (or someone on debugger team) please double check? See [this](https://docs.microsoft.com/en-us/dotnet/framework/debug-trace-profile/making-an-image-easier-to-debug) page.

**Comment by noahfalk** [comment]
yeah that seems accurate to me
