### ISSUE TITLE
Appraisal

### ISSUE THREAD

**Issue by vinrok** [dotnet/docs#6870]
Hats off team. Really amazing tutorials. Done with all QuickStart.
Are there more such interactive tutorials to learn C# from basic to advanced.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d9e98de-9df3-d63f-f6a6-aa079eb5095f
* Version Independent ID: a057574c-020f-a9f0-9dfc-f8936a1132fe
* Content: [Collections interactive tutorial - C# quickstarts](https://docs.microsoft.com/en-us/dotnet/csharp/quick-starts/list-collection?tutorial-step=7)
* Content Source: [docs/csharp/quick-starts/list-collection.yml](https://github.com/dotnet/docs/blob/live/docs/csharp/quick-starts/list-collection.yml)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thank you for the kind words @vinrok We're glad these are helping.

We don't have more yet, but there will be new topics coming soon.
