### ISSUE TITLE
Exception calling "DownloadString" with "1" argument(s): "The underlying connection was closed: An unexpected error occurred on a send."

### ISSUE THREAD

**Issue by achrjulien** [dotnet/docs#6873]
Hi,
Since yesterday, at least, we are getting this error when running `(New-Object System.Net.WebClient).DownloadString("https://dot.net/v1/dotnet-install.ps1") &gt; dotnet-install.ps1` or `wget https://dot.net/v1/dotnet-install.ps1` from a docker container under `microsoft/dotnet-framework:4.7.2-sdk`, this has also been reproduced under a current Windows 10 Desktop install.
```
Exception calling "DownloadString" with "1" argument(s): "The underlying connection was closed: An unexpected error occurred on a send."
At line:1 char:1
+ (New-Object System.Net.WebClient).DownloadString("https://dot.net/v1/ ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException
```
Accessing from a browser works as expected.
Will this be fixed. What can we do in the meantime?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2e484a9-5e0c-eb3e-1413-7b507c4fa07d
* Version Independent ID: 5bc7caa5-f1c2-d7d5-fe02-80c65cca9672
* Content: [dotnet-install scripts](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script)
* Content Source: [docs/core/tools/dotnet-install-script.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-install-script.md)
* Product: **dotnet-core**
* GitHub Login: @blackdwarf
* Microsoft Alias: **mairaw**

**Comment by MikkelHegn** [comment]
In my experience this is because of the combination of TLS 1.2 requirement on the website and PowerShell. This explains: https://www.codyhosterman.com/2016/06/force-the-invoke-restmethod-powershell-cmdlet-to-use-tls-1-2/ And this sample above shows how to do this from PowerShell: `@powershell -NoProfile -ExecutionPolicy unrestricted -Command "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; &([scriptblock]::Create((Invoke-WebRequest -useb 'https://dot.net/v1/dotnet-install.ps1'))) <additional install-script args>" `

**Comment by MikkelHegn** [comment]
Just noticed this: https://github.com/dotnet/docs/issues/5153

**Comment by achrjulien** [comment]
I see, thank you. We have used a compiled curl in the meantime. Do you think Powershell will upgrade to 1.2 as default in the following months?

**Comment by KathleenDollard** [comment]
@johnbeisner Will this continue to be a problem going forward?

**Comment by mairaw** [comment]
Met with @johnbeisner today about this. There's not much we can do since this is a constraint from the environment you run the script. Hopefully the workaround to force PS to use TLS 1.2 provided by @MikkelHegn can help in this scenario.

**Comment by RajaPriyan** [comment]
> In my experience this is because of the combination of TLS 1.2 requirement on the website and PowerShell. This explains: https://www.codyhosterman.com/2016/06/force-the-invoke-restmethod-powershell-cmdlet-to-use-tls-1-2/ And this sample above shows how to do this from PowerShell: `@powershell -NoProfile -ExecutionPolicy unrestricted -Command "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; &([scriptblock]::Create((Invoke-WebRequest -useb 'https://dot.net/v1/dotnet-install.ps1'))) <additional install-script args>" `

Thanks ,it's working

**Comment by yehgdotnet** [comment]
Even without TLS using https,  I get this error.  Anyone faced the same?

**Comment by Saif5017** [comment]
@yehgdotnet me too the problem i am facing is 
```
The splatting operator '@' cannot be used to reference variables in an expression. '@powershell' can be used only as an
 argument to a command. To reference variables in an expression use '$powershell'.
At line:1 char:12
+ @powershell <<<<  -NoProfile -ExecutionPolicy unrestricted -Command "[Net.ServicePointManager]::SecurityProtocol = [N
et.SecurityProtocolType]::Tls12; &([scriptblock]::Create((Invoke-WebRequest -useb 'https://dot.net/v1/dotnet-install.ps
1'))) <additional install-script args>"@powershell -NoProfile -ExecutionPolicy unrestricted -Command "[Net.ServicePoint
Manager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; &([scriptblock]::Create((Invoke-WebRequest -useb 'https
://dot.net/v1/dotnet-install.ps1'))) <additional install-script args>"
    + CategoryInfo          : ParserError: (powershell:String) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : SplattingNotPermitted
```

**Comment by juanlamberti** [comment]
> @yehgdotnet me too the problem i am facing is
> 
> ```
> The splatting operator '@' cannot be used to reference variables in an expression. '@powershell' can be used only as an
>  argument to a command. To reference variables in an expression use '$powershell'.
> At line:1 char:12
> + @powershell <<<<  -NoProfile -ExecutionPolicy unrestricted -Command "[Net.ServicePointManager]::SecurityProtocol = [N
> et.SecurityProtocolType]::Tls12; &([scriptblock]::Create((Invoke-WebRequest -useb 'https://dot.net/v1/dotnet-install.ps
> 1'))) <additional install-script args>"@powershell -NoProfile -ExecutionPolicy unrestricted -Command "[Net.ServicePoint
> Manager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; &([scriptblock]::Create((Invoke-WebRequest -useb 'https
> ://dot.net/v1/dotnet-install.ps1'))) <additional install-script args>"
>     + CategoryInfo          : ParserError: (powershell:String) [], ParentContainsErrorRecordException
>     + FullyQualifiedErrorId : SplattingNotPermitted
> ```

As I see you copy the sentence two times copy only: @powershell -NoProfile -ExecutionPolicy unrestricted -Command "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; &([scriptblock]::Create((Invoke-WebRequest -useb 'https://dot.net/v1/dotnet-install.ps1')))" **without "< additional install-script args >"**

**Comment by ahmedlecheheb1974-maker** [comment]
hi 
this command in powershell not work just now i need help please
iex ((New-Object Net.WebClient).DownloadString('https://get.activated.win'))
is this not work please i need help
