### ISSUE TITLE
Throwing an 'Exception' is not a best practice.

### ISSUE THREAD

**Issue by shatl** [dotnet/docs#6881]
from.RollbackTransaction(withdrawalTrxID);
    throw new Exception("Withdrawal failed", ex);

Throwing an 'Exception' is not a best practice.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1ea31f6-516f-100d-046e-1a0445d92824
* Version Independent ID: a713e8c9-8210-761d-9ae7-238793825ff3
* Content: [Best Practices for Exceptions](https://docs.microsoft.com/en-us/dotnet/standard/exceptions/best-practices-for-exceptions)
* Content Source: [docs/standard/exceptions/best-practices-for-exceptions.md](https://github.com/dotnet/docs/blob/master/docs/standard/exceptions/best-practices-for-exceptions.md)
* Product: **dotnet**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by crtjr64** [comment]
Who wrote that rule? You? How do you expect that inner exceptions are created in the first place? What if you have an exception handler in the attribute in your controller that logs errors or would you just create exception logging throughout the application and think that's best practice? Good luck with the next programmer not cursing you out when the exception logger is upgraded.

**Comment by shatl** [comment]
@crtjr64  please read carefully https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/exceptions/creating-and-throwing-exceptions#things-to-avoid-when-throwing-exceptions :)

**Comment by BillWagner** [comment]
I read @shatl 's original issue as recommending against throwing `System.Exception`. Is that what you meant?  

@crtjr64 did you think he was recommending against throwing *any* exception?

**Comment by shatl** [comment]
@billwagner exactly
