### ISSUE TITLE
MS Test in VS code

### ISSUE THREAD

**Issue by vinaysimharaju** [dotnet/docs#6890]
I have created a MS Test project in VS Code and using selenium C#. In the project I got with launch.json and tasks.json files. I want to have some configuration values like connectionstring and applicationurl in the project. Where I have to create those values and how to read them in the project.

**Comment by mairaw** [comment]
Thanks @vinaysimharaju. Have you tried submitting this as a product feedback or asking on StackOverflow?    If you do submit an issue, please post the link here so others can find it as well.
