### ISSUE TITLE
Roslyn Tutorial: Refactoring to Tuple assignment

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#6891]
This tutorial would teach the refactoring actions, in contrast to the analyzer and code fix structure.

Developers would learn the different UX for a refactoring (surfaces on user request vs. generating warning or error), and how the code changes are updated.

This would replace code like:
 
```csharp
public Point(int x, int y)
{
   X = x;
   Y = y;
}
```

With:
 
```csharp
public Point(int x, int y) => (X ,Y) = (x, y);
```

**Comment by BillWagner** [comment]
/cc @IEvangelist 

This might still be useful to write as a tutorial.

**Comment by IEvangelist** [comment]
Even though the proposal for this refactoring has been closed, https://github.com/dotnet/roslyn/issues/38523 - the concept lives on.

**Comment by BillWagner** [comment]
I'll reopen it. I think it's a good sample.

Adding @jmarolf and @mikadumont. What's your opinion on this as a sample refactoring?

**Comment by jmarolf** [comment]
I like it! I'm assigning it to myself so I don't forget about this.

**Comment by Youssef1313** [comment]
@jmarolf I think you forgot to assign it to yourself?

**Comment by Youssef1313** [comment]
@IEvangelist Was this tutorial written in some PR? or was it decided to not write it?

**Comment by IEvangelist** [comment]
> @IEvangelist Was this tutorial written in some PR? or was it decided to not write it?

It was decided not to write it. I don't think anyone has time to commit to it. I'm starting an effort to go through older issues, if we really want to do this we could reopen it, but this is nearly four years old now and the related Rolsyn proposal that I wrote was closed years ago too.
