### ISSUE TITLE
No need to declare manually

### ISSUE THREAD

**Issue by imba-tjd** [dotnet/docs#6892]
From https://github.com/dotnet/docs.zh-cn/pull/167.
In #adding-features-to-the-service step 4:

> Add a declaration for the eventLog object in the MyNewService class, right after the line that declares the components variable: 

But as @Anti-Li said,

> After you drag a component into the designer, the declaration is automatically generated in the code by the designer and can no longer be declared.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75152e30-b486-3ba0-c606-25ada7347b22
* Version Independent ID: e797ddfe-a9d3-93a4-61bd-fd6dc9b8d6b4
* Content: [Walkthrough: Creating a Windows Service Application in the Component Designer](https://docs.microsoft.com/en-us/dotnet/framework/windows-services/walkthrough-creating-a-windows-service-application-in-the-component-designer)
* Content Source: [docs/framework/windows-services/walkthrough-creating-a-windows-service-application-in-the-component-designer.md](https://github.com/dotnet/docs/blob/master/docs/framework/windows-services/walkthrough-creating-a-windows-service-application-in-the-component-designer.md)
* Product: **dotnet-framework**
* GitHub Login: @ghogen
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks for your feedback @imba-tjd. We've added this to our backlog.

**Comment by Lordzalo** [comment]
I tried to install my service in the comand promt (as an administrator) a box pops up telling me that i require a pasword and username. Could someone answer why do I have to do?

**Comment by Lordzalo** [comment]
using* the comand promt

**Comment by gewarren** [comment]
@Lordzalo Did you set the account for the service process installer to LocalSystem?
