### ISSUE TITLE
Roslyn Tutorial: Refactor null check to ?.

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#6896]
This would be a more advanced tutorial because the code to search for and the replacement are both more involved.  Consider this code:

```csharp
If (person != null)
    someVar = person.FirstName;
else
    someVar = "Not submitted";
 ```

It could be replaced with:
 
```csharp
someVar = person?.FirstName ?? “Not submitted”;
```

There are a lot of cases to check in this scenario: else clause assignment, code without an else clause.

**Comment by Youssef1313** [comment]
Related to: #6891

@BillWagner @IEvangelist The two issues suggests to different new tutorials on code refactorings. Consider reopening only one of them if one is sufficient. Or both if you think it's going to be valuable.

**Comment by Youssef1313** [comment]
There is also: https://github.com/dotnet/docs/issues/6893 https://github.com/dotnet/docs/issues/6894 https://github.com/dotnet/docs/issues/6895

**Comment by BillWagner** [comment]
Adding @jmarolf @mikadumont 

All the issues referenced in this thread are potential ideas. As you develop your plans, consider which might be useful.
