### ISSUE TITLE
Information on generic type names is missing.

### ISSUE THREAD

**Issue by alphaleonis** [dotnet/docs#6898]
This section seems incomplete in that it does not cover how to specify a fully qualified type name of a generic type and its type arguments.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c3ddfcc-278c-aa14-1132-bb8fb6f12932
* Version Independent ID: 7e89d072-3394-2866-4e38-7a4931d96ca3
* Content: [Specifying Fully Qualified Type Names](https://docs.microsoft.com/en-us/dotnet/framework/reflection-and-codedom/specifying-fully-qualified-type-names)
* Content Source: [docs/framework/reflection-and-codedom/specifying-fully-qualified-type-names.md](https://github.com/dotnet/docs/blob/master/docs/framework/reflection-and-codedom/specifying-fully-qualified-type-names.md)
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by mairaw** [comment]
Thanks for your feedback @alphaleonis. We'll investigate this and address it a future sprint.

**Comment by rpetrusha** [comment]
Thanks for pointing out the absence of information on generic types, @alphaleonis. We've scheduled some time to revise this topic to add a section on generic type names.

**Comment by brian-reichle** [comment]
@rpetrusha , whilst the fix has added documentation regarding open generic type names, it's still missing information on closed generic types.

eg. the following are all [valid](https://dotnetfiddle.net/MgfoZk), yet not covered.
*  ``System.Nullable`1[System.Boolean]``
*  ``System.Nullable`1[[System.Boolean]]``
* ``System.Collections.Generic.Dictionary`2[System.String,System.Int32]``
* ``System.Collections.Generic.Dictionary`2[[System.String, mscorlib, PublicKeyToken=b77a5c561934e089],[System.String, mscorlib, PublicKeyToken=b77a5c561934e089]], mscorlib, PublicKeyToken=b77a5c561934e089``
