### ISSUE TITLE
Defining Attributes in Metadata Classes Doc for NetCore

### ISSUE THREAD

**Issue by ckams** [dotnet/docs#6906]
## Requests for new Topics
Explain how `ModelMetadataType` works.

Put there, in Table of Contents:

   - https://docs.microsoft.com/en-us/dotnet/standard/attributes/

Almost copy and past [from this page](https://docs.microsoft.com/en-us/previous-versions/msp-n-p/ff664465(v=pandp.50)).

**Adapt the code for NETCore:**
```
public class ProductMetadata
{
  [Required(ErrorMessage = "ID is required.")]
  [RegularExpression("[A-Z]{2}[0-9]{4}", 
          ErrorMessage = "Product ID must be 2 capital letters and 4 numbers.")]
  public object ID { get; set; };

  [StringLength(100, ErrorMessage = "Description must be less than 100 chars.")]
  public object Description { get; set; } ;
}
```

**Comment by svick** [comment]
If you're talking about [`Microsoft.AspNetCore.Mvc.ModelMetadataTypeAttribute`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.modelmetadatatypeattribute?view=aspnetcore-2.1), then that's specific to ASP.NET Core, so I think it shouldn't be documented in the general documentation for .Net.

If that's the case, then I think this issue should be closed here and reopened at [the aspnet/Docs repo](https://github.com/aspnet/Docs).

**Comment by ckams** [comment]
You right, I did a mistake…
