### ISSUE TITLE
Bounded Capacity

### ISSUE THREAD

**Issue by turowicz** [dotnet/docs#6908]
What's the recommended way to introduce DataflowBlockOptions to this example? Mainly bounded capacity.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe912a6b-f1de-948b-c1d3-bc873aa413e4
* Version Independent ID: 47c42c32-2b0d-c708-deb1-f79ff6e96988
* Content: [Walkthrough: Creating a Custom Dataflow Block Type](https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/walkthrough-creating-a-custom-dataflow-block-type#deriving-from-ipropagatorblock-to-define-the-sliding-window-dataflow-block)
* Content Source: [docs/standard/parallel-programming/walkthrough-creating-a-custom-dataflow-block-type.md](https://github.com/dotnet/docs/blob/master/docs/standard/parallel-programming/walkthrough-creating-a-custom-dataflow-block-type.md)
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by svick** [comment]
I think the best approach is to split the incoming `BoundedCapacity` in two (say, 50-50) and use those values to set `BoundedCapacity` of the two component blocks. That way, the resulting block will have capacity that is the sum of capacities of its components.

**Comment by JRAlexander** [comment]
@turowicz, I'm closing this issue as it looks like it's been resolved. Please reopen if that is not the case. Thanks!
