### ISSUE TITLE
Typo in Remarks.

### ISSUE THREAD

**Issue by HimuRami** [dotnet/docs#6925]
Under Remarks (there is a typo):
It reads:
The binary & operator evaluates both operators regardless of the first one's value.
Should Read:
The binary & operator evaluates both operands regardless of the first one's value.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c47bf29e-0135-c2d7-fe44-35f9dc57d585
* Version Independent ID: e4410660-f1dc-9740-220a-656359c5af10
* Content: [& Operator (C# Reference)](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/and-operator)
* Content Source: [docs/csharp/language-reference/operators/and-operator.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/operators/and-operator.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by rpetrusha** [comment]
Thanks for pointing out the typo, @HimuRami. We've opened PR #6943 to correct it.
