### ISSUE TITLE
Example usage of int.TryParse is incorrect in second paragraph

### ISSUE THREAD

**Issue by Shah-Nisarg** [dotnet/docs#6930]
The second paragraph states:

> If you have a string, it is slightly more efficient and straightforward to call a `TryParse` method (for example, `int.TryParse("11")`). 

However, [`int.TryParse`](https://msdn.microsoft.com/en-us/library/f02979c7(v=vs.110).aspx) method expects a second parameter of Int32 type. Having known this, the sentence comes across as confusing. I had to look up the documentation to see if there wasn't an overload that allowed just one parameter.

I would suggest using `int.Parse("11")` or `int.TryParse("11", out num)` instead, or omit the inline example entirely, to avoid confusion.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f91931f7-35de-15e0-4c20-53a3fa9246ec
* Version Independent ID: d9031bdc-890a-d5bd-c1ed-d767b0e27890
* Content: [How to: Convert a String to a Number (C# Programming Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/types/how-to-convert-a-string-to-a-number)
* Content Source: [docs/csharp/programming-guide/types/how-to-convert-a-string-to-a-number.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/types/how-to-convert-a-string-to-a-number.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by rpetrusha** [comment]
Thanks for pointing out that the method call is incorrect, @Shah-Nisarg. We've addressed the issue in PR #6950 by using `Int32.TryParse("11", out number)`.
