### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by lefig** [dotnet/docs#6935]
Great tutorial. It cuts to the chase and gets folk up to speed. Please consider similar material that explores other scenarios and some of the models used for selection. Thanks

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a30b3ff5-b5e6-ff02-6f60-b5cef6f34666
* Version Independent ID: fdf962e2-620e-d9ad-5057-5f96f52dc60f
* Content: [Use ML.NET to predict New York taxi fares (regression)](https://docs.microsoft.com/en-gb/dotnet/machine-learning/tutorials/taxi-fare)
* Content Source: [docs/machine-learning/tutorials/taxi-fare.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/taxi-fare.md)
* Product: **dotnet-ml**
* GitHub Login: @aditidugar
* Microsoft Alias: **johalex**

**Comment by JRAlexander** [comment]
Thanks, @lefig!
