### ISSUE TITLE
Comando "CreateOrderCommand" não existe no código-fonte linkado

### ISSUE THREAD

**Issue by LisandroSu** [dotnet/docs#6938]
@MarcoNicolodi commented on [Thu Aug 09 2018](https://github.com/dotnet/docs.pt-br/issues/61)

Na seção "Eliminando a duplicação de eventos de mensagem no nível do EventHandler" há um link para o código fonte, falando sobre o "CreateOrderCommand", que não existe no arquivo. 

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 384e5c2c-d3ba-b5ba-260b-65b8e900b78e
* Version Independent ID: a561cbc7-1e00-5732-e298-d9863f85191c
* Content: [Assinando eventos](https://docs.microsoft.com/pt-br/dotnet/standard/microservices-architecture/multi-container-microservice-net-applications/subscribe-events)
* Content Source: [docs/standard/microservices-architecture/multi-container-microservice-net-applications/subscribe-events.md](https://github.com/dotnet/docs.pt-br/blob/live/docs/standard/microservices-architecture/multi-container-microservice-net-applications/subscribe-events.md)
* GitHub Login: @CESARDELATORRE
* Microsoft Alias: **wiwagn**

---

@MarcoNicolodi commented on [Thu Aug 09 2018](https://github.com/dotnet/docs.pt-br/issues/61#issuecomment-411885925)

Provavelmente também a lógica citada no texto foi passada para dentro do handler do mediatr e não está mais no arquivo linkado, mas é preciso olhar com mais atenção. No momento estou no trabalho e não posso me aprofundar.

**Comment by LisandroSu** [comment]
Hello team,

Please check on the users comments. 

They roughly translate to _"In the "Deleting duplicate message events at the EventHandler level" section there is a link to the source code, talking about the "CreateOrderCommand", which does not exist in the file."_

And the one below: _"Probably also the logic quoted in the text was passed into the mediatr handler and is no longer in the linked file, but it is necessary to look more closely. At the moment I'm at work and I can not go deeper."_

Thanks!

**Comment by JRAlexander** [comment]
Thanks! It has been added to the backlog.

**Comment by mvelosop** [comment]
Fixed, will be included in the next PR (Chapter 6).
