### ISSUE TITLE
wrong URL

### ISSUE THREAD

**Issue by dodo99** [dotnet/docs#6939]
in step 4 … HYPERLINK "http://localhost:8000/ServiceModelSamples/Service" …
the address is wrong.  If you follow the first 3 tasks of the tutorial, the address should be "http://localhost:8000/GettingStarted/CalculatorService/"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c27c6cc-63c8-5c3d-f344-228f8ad86c90
* Version Independent ID: d560cf6a-e9bd-95e5-ce15-a08a5778181a
* Content: [How to: Create a Windows Communication Foundation Client](https://docs.microsoft.com/en-us/dotnet/framework/wcf/how-to-create-a-wcf-client)
* Content Source: [docs/framework/wcf/how-to-create-a-wcf-client.md](https://github.com/dotnet/docs/blob/master/docs/framework/wcf/how-to-create-a-wcf-client.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thank you for your feedback @dodo99. We've added this to our backlog.
