### ISSUE TITLE
What does it mean for a path to be "independent of the current directory"?

### ISSUE THREAD

**Issue by ElusiveTau** [dotnet/docs#6940]
"a file path is fully qualified (that is, it the path is independent of the current directory and does not change when the current directory changes)"

Can you provide an example of a fully qualified path and a non fully qualified path?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b74b99ff-32f8-c2d1-0a62-5907985f591e
* Version Independent ID: 716a28dc-360e-2964-47f5-0ff18bb00b1c
* Content: [File path formats on Windows systems](https://docs.microsoft.com/en-us/dotnet/standard/io/file-path-formats)
* Content Source: [docs/standard/io/file-path-formats.md](https://github.com/dotnet/docs/blob/master/docs/standard/io/file-path-formats.md)
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by rpetrusha** [comment]
Thanks for your question, @ElusiveTau. 

A fully qualified file path describes a path that starts from a drive and its root. For example, C:\users\user1\documents\reports\2018\ is fully qualified. Provided that they identify file system objects that actually exist, fully qualified paths should always succeed in identifying the file system resource.

A non-fully qualified path is any path that assumes some default for any of its parts. For example:
- \users\user1\documents\reports\2018\: assumes a default drive.
- documents\reports\2018: assumes that c:\users\user1\documents is the current directory
- ..\2017: assumes that C:\users\user1\documents\reports\2018 is the current directory
- .\reports\2018: assumes that C:\users\user1\documents is the current directory
A non-fully qualified path is always a relative path that starts from a particular drive some existing file system object to another file system object. The problem of a relative path is that if the current directory or current drive is not the assumed one, an exception results.

I hope that this helps to answer your question. If not please feel free to respond. In the meantime, I'll close this issue.
