### ISSUE TITLE
public class Process : System.ComponentModel.Component

### ISSUE THREAD

**Issue by sk0777** [dotnet/docs#6941]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84993cb7-37e6-01ef-9b25-8cea57f5a125
* Version Independent ID: 723dcba4-f26d-7567-77af-4e93f41a0df9
* Content: [Process Class (System.Diagnostics)](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process?view=netframework-4.7.2#Properties)
* Content Source: [xml/System.Diagnostics/Process.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Diagnostics/Process.xml)
* Product: **dotnet-api**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by rpetrusha** [comment]
Do you have a question about the Process class, @sk0777. The syntax indicates that Process inherits from System.ComponentModel.Component. 
I'll close this issue, but if you have a question, please feel free to reply.
