### ISSUE TITLE
Should Inheritance hierarchy be shown for value types and delegates?

### ISSUE THREAD

**Issue by svick** [dotnet/docs#6947]
I have noticed that in the API reference, Inheritance hierarchy is shown even for value types. E.g.:

![](https://user-images.githubusercontent.com/287848/43975096-c6f5800a-9cdc-11e8-9c00-20b5421e0a2c.png)
![](https://user-images.githubusercontent.com/287848/43975106-cf1eebae-9cdc-11e8-8ced-e71e6a578dbc.png)

While this information is certainly correct, my question is: Is it useful enough to be shown at such a prominent location?

`struct`s and `enum`s will always have exactly the same base type, so showing this is much less useful than it is for classes. Also, as far as I can tell, MSDN doesn't show its Inheritance hierarchy for value types.

Delegates are in a similar situation, e.g.:

![](https://user-images.githubusercontent.com/287848/43975371-a38ec6ac-9cdd-11e8-85d4-e338001e6509.png)

Note that this is not technically correct: `Action` (and all other delegate types) inherits from `MulticastDelegate`, not directly from `Delegate`. Though that distinction might be more confusing than useful.

**Comment by BillWagner** [comment]
I agree that it's a lot of space. Do you think that just showing `struct` or `delegate` is sufficient? Or do you have a different, more concise, presentation in mind?

**Comment by rpetrusha** [comment]
I agree that it's not particularly useful. The only marginal utility that I can think of is, in the case of enums and possibly of delegates, that it's a reminder that their members should be available through inheritance, since they're not listed in the documentation of delegates and enums.

**Comment by svick** [comment]
@BillWagner Now that I think about it, there might be a third option: making the `struct`/`enum`/`delegate` keyword in the definition into a link. Though I'm not sure myself whether it's a good idea. And it might be infeasible technically.

**Comment by mairaw** [comment]
This issue was moved to MicrosoftDocs/feedback#2368
