### ISSUE TITLE
How to: Connect to a Database - What if things go wrong?

### ISSUE THREAD

**Issue by BenMcLean** [dotnet/docs#6949]
This page needs to provide help on how to check whether the connection succeeded and what to try next in case it fails.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2448ac4-a6d0-e376-36fe-c6279fd606c8
* Version Independent ID: 50f1aa4e-8e0e-2bee-db10-9c65c11b4028
* Content: [How to: Connect to a Database](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/sql/linq/how-to-connect-to-a-database)
* Content Source: [docs/framework/data/adonet/sql/linq/how-to-connect-to-a-database.md](https://github.com/dotnet/docs/blob/master/docs/framework/data/adonet/sql/linq/how-to-connect-to-a-database.md)
* Product: **dotnet-framework**
* GitHub Login: @douglaslMS
* Microsoft Alias: **douglasl**

**Comment by douglaslMS** [comment]
@BenMcLean Your suggestion is a good suggestion. However, we don't have examples of retry code readily available to simply paste in, and opinions differ about the best way to write that code. (See for example [How to introduce retry logic into LINQ to SQL to deal with timeouts?](https://stackoverflow.com/questions/2591827/chow-to-introduce-retry-logic-into-linq-to-sql-to-deal-with-timeouts) and [Automatic Retry for LINQ to SQL](https://daveaglick.com/posts/automatic-retry-for-linq-to-sql).) We have added this request to our backlog to be prioritized and scheduled, and we are going to close this issue. Thank you for the suggestion.

**Comment by mairaw** [comment]
Reopened so @BenMcLean can keep track of when this is fixed and added to our backlog milestone.

**Comment by BenMcLean** [comment]
Oh thanks. Yeah, it would be nice to see what ends up getting written about this.
