### ISSUE TITLE
Disagreement with ECMA-334

### ISSUE THREAD

**Issue by LisandroSu** [dotnet/docs#6952]
@flaviotsales commented on [Fri Aug 10 2018](https://github.com/dotnet/docs.pt-br/issues/62)

The two comments
~~~
// Must be defined inside a class called Fahrenheit:
~~~
disagrees with the ECMA-334 standard on 11.5.2 Permitted user-defined conversions, which says

&gt;* Either S0 or T0 is the class or struct type in which the operator declaration takes place.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 265f75ba-8fe1-3586-6a53-e9a50acadab0
* Version Independent ID: 2f8d9e81-3004-8cef-2161-79b800a6538c
* Content: [Palavra-chave explicit (Referência de C#)](https://docs.microsoft.com/pt-br/dotnet/csharp/language-reference/keywords/explicit)
* Content Source: [docs/csharp/language-reference/keywords/explicit.md](https://github.com/dotnet/docs.pt-br/blob/live/docs/csharp/language-reference/keywords/explicit.md)
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by LisandroSu** [comment]
Hi team,

Please check on the issue reported by the user.

Thanks!

**Comment by BillWagner** [comment]
This is an error. The comment should read:

```csharp
// Must be defined either inside a class called Fahrenheit or Celsius:
```
