### ISSUE TITLE
Link to "Friend Assemblies" takes me to MSDN

### ISSUE THREAD

**Issue by Shah-Nisarg** [dotnet/docs#6955]
In the section "Class and Struct Accessibility", the final paragraph has a link to topic "Friend Assemblies":

> You can enable specific other assemblies to access your internal types by using the InternalsVisibleToAttribute. For more information, see [Friend Assemblies](http://msdn.microsoft.com/library/df0c70ea-2c2a-4bdc-9526-df951ad2d055).

However, the link takes me to MSDN, where I have to choose from either a C# link or a VB link. Clicking on the C# link takes me back to docs: https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/assemblies-gac/friend-assemblies.

Given that the original ["Access Modifiers"](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/access-modifiers) page I am looking at has CSharp in the URL, and the "Friend Assemblies" page I arrive at also has CSharp in the URL, I am not sure if the redirection to MSDN is necessary.

So I'm not sure if there is a practical limitation that requires this, but I'm just dropping a note in case this link was missed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8121f526-cfe4-091d-d031-2cdc274cd8ee
* Version Independent ID: 76a389f6-b568-3568-6483-6df440f96f0c
* Content: [Access Modifiers (C# Programming Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/access-modifiers)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/access-modifiers.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/access-modifiers.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
Thanks @Shah-Nisarg. It's a migration issue that we need to fix it,
