### ISSUE TITLE
C# Concepts are hard to link

### ISSUE THREAD

**Issue by Andikki** [dotnet/docs#6959]
"C# Concepts" (as seen on the left) section doesn't have a dedicated page, and half of the articles there lead to a different hierarchy. I like the content of this section, and think it's a great resource to point beginners to. But looks like there's no link to provide them with. It's not listed in the "C# Guide" page either.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3dff5a94-d9cd-e31b-4056-362abbe8d782
* Version Independent ID: cfb1ad21-e822-4075-2726-bd130ec2358d
* Content: [C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/)
* Content Source: [docs/csharp/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/index.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
Thanks @Andikki for your feedback. You're right. We should look into that and see how we can make the TOC and the experience better.

**Comment by williamgh2019** [comment]
Python is good hierarchy you should take some good point from.
Now I am looking for learning C# and look at the left hand side it too confuse and hard for beginner. You should prepare well docs for C# from zero to pro if posible

**Comment by BillWagner** [comment]
We've proposed a new [table of contents](https://gist.github.com/BillWagner/047cb97f6c0fe542d3a1299e994b2acd) that addresses this concern. We're working on updating the content to match the proposal.  This issues is handled under [this project](https://github.com/dotnet/docs/projects/93)
