### ISSUE TITLE
Implementation on Azure

### ISSUE THREAD

**Issue by neil-rubens** [dotnet/docs#6964]
How would you 

How could domain events be implemented on Azure.  In particular which Azure services are fitting, and do you combine them.

Relatively little has been written on this topic so far.  This presentation seems good: https://www.slideshare.net/biztalk360/serverless-cqrs-in-azure

It talks about possible implementations; e.g. Azure Functions vs Azure Logic Apps; and Azure Service Bus vs Azure Event Grid.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d432d5bb-24a7-3bec-1e17-910c8129226e
* Version Independent ID: e41af96d-f015-a8e0-4449-7a508d7bccc8
* Content: [Domain events. design and implementation](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/domain-events-design-implementation)
* Content Source: [docs/architecture/microservices/microservice-ddd-cqrs-patterns/domain-events-design-implementation.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/microservice-ddd-cqrs-patterns/domain-events-design-implementation.md)
* Product: **dotnet**
* Technology: **dotnet-ebooks**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by neil-rubens** [comment]
I've asked this question also on: https://stackoverflow.com/questions/51806013/implementing-domain-events-ddd-cqrs-on-azure

**Comment by mvelosop** [comment]
Thanks for the feedback @neil-rubens!

Even though it's an old question and it was already answered in SO, it's nice to include the mention in the guide.
