### ISSUE TITLE
"in-process" event firing/handling and micro-services

### ISSUE THREAD

**Issue by neil-rubens** [dotnet/docs#6965]
I assume that in micro-services architecture there many processes; so could one assume that event will be fired and handled "in-process"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d432d5bb-24a7-3bec-1e17-910c8129226e
* Version Independent ID: e41af96d-f015-a8e0-4449-7a508d7bccc8
* Content: [Domain events. design and implementation](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/domain-events-design-implementation)
* Content Source: [docs/architecture/microservices/microservice-ddd-cqrs-patterns/domain-events-design-implementation.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/microservice-ddd-cqrs-patterns/domain-events-design-implementation.md)
* Product: **dotnet**
* Technology: **dotnet-ebooks**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by crclz** [comment]
No. 'In-process' means the event is handled within the current process, for example, your .NetCore Web api process.

The traditional way of publishing an event is sending it to message services like a message queue. The message service then send the messages to processes that handle the messages.

Data transfers much faster in a process than through a socket. Having your message handled in the current process decreases the load of the message service. If your webapi process and your message service runs on different machines or even in different data centers, your service will suffer from high latency. Besides, having each process handle its domain event is an natural load-balancing design. There is no need for the message service to balance the load.
