### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by johnnyagerard** [dotnet/docs#6975]
The following code does not raise a NullReferenceException.

```csharp
int? i = null;
object o = i;
var j = (int?)o;
```
Is this considered as boxing and unboxing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75a88bb6-664f-99b3-07be-22a666888d11
* Version Independent ID: bea53588-8e8d-5f80-d572-178cd8ba48cb
* Content: [Boxing and Unboxing (C# Programming Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/types/boxing-and-unboxing)
* Content Source: [docs/csharp/programming-guide/types/boxing-and-unboxing.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/types/boxing-and-unboxing.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by imba-tjd** [comment]
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/nullable-types/using-nullable-types#boxing-and-unboxing

**Comment by johnnyagerard** [comment]
@imba-tjd Thanks.

**Comment by BillWagner** [comment]
@johnnyagerard The doc provided by @imba-tjd does answer the question: The nulll value is not boxed but rather the conversion produces null in your example above.

I'll close this as answered.
