### ISSUE TITLE
Possible typo

### ISSUE THREAD

**Issue by kunkliricsi** [dotnet/docs#6977]
In the Essential Samples section at the union part, the GetHashCode(Dog d) function shouldn't return b's but d's GetHashCode() function.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89e7bc95-4062-e6df-7475-21973ed1becc
* Version Independent ID: 571fd6fd-95b6-6fc9-d4df-9b44da6a01b4
* Content: [LINQ (Language Integrated Query)](https://docs.microsoft.com/en-us/dotnet/standard/using-linq)
* Content Source: [docs/standard/using-linq.md](https://github.com/dotnet/docs/blob/master/docs/standard/using-linq.md)
* Product: **dotnet**
* GitHub Login: @cartermp
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
Thanks for your feedback @kunkliricsi. Would you like to submit a PR for this?

**Comment by kunkliricsi** [comment]
Duplicate of #6997
