### ISSUE TITLE
StringBuilder note specific to .NET Framework 4.0 and 4.5

### ISSUE THREAD

**Issue by ChrisMaddock** [dotnet/docs#6979]
https://docs.microsoft.com/en-gb/dotnet/api/system.text.stringbuilder?view=netframework-4.7.2#notes-to-callers

In this section, the stringbuilder API docs refer specifically to .NET Framework 4.0 and 4.5. I assume the same comment also applies to everything later that .NET Framework 4.0, and all non-framework APIs (e.g. Core, Xamarin.)

I'm not sure what the convention is for referring to 'all those things', sorry! :smile:

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2e7c7d5-d12c-5430-bfee-b6171e843c4e
* Version Independent ID: 19d6c6e2-2fe7-bd44-1141-44d5337f22fe
* Content: [StringBuilder Class (System.Text)](https://docs.microsoft.com/en-gb/dotnet/api/system.text.stringbuilder?view=netframework-4.7.2#feedback)
* Content Source: [xml/System.Text/StringBuilder.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Text/StringBuilder.xml)
* Product: **dotnet-api**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by rpetrusha** [comment]
Thanks for pointing this out, @ChrisMaddock. I'll investigate and update the documentation.
