### ISSUE TITLE
Automatically get Latest Version

### ISSUE THREAD

**Issue by CodeSwimBikeRunner** [dotnet/docs#6980]
How would I automatically get the latest version? Lets say the package is maintained by me, and I always want the latest one from my nuget repository? I Tried Version="1.1.*.*" and this did not work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f76f1f9-ebac-1b77-f735-52cdf5b973ed
* Version Independent ID: 3e3f4bb2-4329-527e-2edb-9eabdfa29313
* Content: [Managing dependencies in .NET Core tooling](https://docs.microsoft.com/en-us/dotnet/core/tools/dependencies)
* Content Source: [docs/core/tools/dependencies.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dependencies.md)
* Product: **dotnet-core**
* GitHub Login: @blackdwarf
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
@KathleenDollard @livarcocc @dsplaisted can you help with this question? Is there a way to use * or something?

**Comment by livarcocc** [comment]
You can just use * in the version.

**Comment by CodeSwimBikeRunner** [comment]
You are more than welcome to close this. I think that the * in the version is as intended, but at the time of writing the question Visual Studio integration with this in combination with .net core did not work. It works now, and we have been using * in the version.
