### ISSUE TITLE
Missing Associativity

### ISSUE THREAD

**Issue by avifarah** [dotnet/docs#6981]
Missing Associativity

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7eeac581-6235-2192-d909-e7fe3d21197f
* Version Independent ID: 9d8e2a57-1c18-8cba-9bd4-eef546fe2dcb
* Content: [C# Operators](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/index)
* Content Source: [docs/csharp/language-reference/operators/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/operators/index.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@avifarah Can you add some detail on what you think is missing related to associativity here? An example would help.

**Comment by avifarah** [comment]
Ex 1.
a == b == c;
The == operator has a right-to-left associativity making the previous statement equivalent to a == (b == c);

Ex 2:
On the other hand 
a && b && c;
The && operator has a left-to-right associativity making the previous statement equivalent to (a && b) && c;

Thank you for your attention.

**Comment by avifarah** [comment]
I was mistaken in my example Ex 1 of my Missing Associativity response.  I should have used a = b = c as an example of a right-to-left associative operator.
