### ISSUE TITLE
Good basic overview for Software Rookie

### ISSUE THREAD

**Issue by crdr** [dotnet/docs#6984]
I have a hunch what CLR is. I ordered the book by Richter .. I am curious how C# and .NET correspond with Windows' browser .. we'll see.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c41cd795-9320-ab3c-b2d6-0184fc0985d2
* Version Independent ID: 93459fb6-e4db-8a74-79af-3bc3e606fcbb
* Content: [Common Language Runtime (CLR)](https://docs.microsoft.com/en-us/dotnet/standard/clr)
* Content Source: [docs/standard/clr.md](https://github.com/dotnet/docs/blob/master/docs/standard/clr.md)
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by JRAlexander** [comment]
Thanks for your feedback, @crdr!
