### ISSUE TITLE
Could you please provide contextual information and samples for DiagnosticAnalyzer?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [dotnet/docs#6994]
Other than https://msdn.microsoft.com/magazine/dn879356.aspx, I can't find anything on what this class is, why we'd use it, or how.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e42c855-e72c-4702-e3f6-bcd1e16ecb61
* Version Independent ID: 6e333fe2-60fe-748b-f3f0-744f3ff62270
* Content: [DiagnosticAnalyzer Class (Microsoft.CodeAnalysis.Diagnostics)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.diagnostics.diagnosticanalyzer?view=roslyn-dotnet)
* Content Source: [dotnet/xml/Microsoft.CodeAnalysis.Diagnostics/DiagnosticAnalyzer.xml](https://github.com/dotnet/roslyn-api-docs/blob/live/dotnet/xml/Microsoft.CodeAnalysis.Diagnostics/DiagnosticAnalyzer.xml)
* Product: **dotnet-roslyn-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by BillWagner** [comment]
I'm working on an article that should address this now. You can look at #6824 for the current draft. An updated version should be ready later today.
