### ISSUE TITLE
decimal points in pixel?

### ISSUE THREAD

**Issue by bobsort** [dotnet/docs#6995]
As far as I know, pixel is smallest unit of measurement (doesn't have decimal points).
How do you draw on 0.39 pixel or a 14.39 pixel line which doesn't cover 14 pixel or 15 pixel?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3f6c7d6-a5a5-0cfa-45ed-23e99e236b6e
* Version Independent ID: cc28c628-46d6-520a-d5e5-c47682c59bc6
* Content: [How to: Obtain Font Metrics](https://docs.microsoft.com/en-us/dotnet/framework/winforms/advanced/how-to-obtain-font-metrics)
* Content Source: [docs/framework/winforms/advanced/how-to-obtain-font-metrics.md](https://github.com/dotnet/docs/blob/master/docs/framework/winforms/advanced/how-to-obtain-font-metrics.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mikedn** [comment]
> As far as I know, pixel is smallest unit of measurement (doesn't have decimal points).

That pixel unit without decimal points is really a unit of rendering, not an unit of measurement.

As a unit of measurement, there's nothing special about fractional pixels even if you can't draw 2.3 pixels or start a line at (2.3, 3.7). During rendering, such fractional values will be transformed to integer pixel coordinates according to various rules (e.g. rounding). If antialiasing is enabled, the color of pixels can also be affected. For example, a horizontal line drawn at Y 10.5 may end up as 2 lines of pixels of lighter color.

**Comment by JRAlexander** [comment]
@bobsort, it looks like this has been resolved, so I'm closing it. Please reopen if this is not the case. @mikedn, Thanks for the assistance!!
