### ISSUE TITLE
Framework not conforming with ISO 3166 for country/region

### ISSUE THREAD

**Issue by higtrollers** [dotnet/docs#6998]
For example, Antarctica (AQ | ATA) and many others are not present when retrieving all regions.

Example:
```:
var regions = CultureInfo.GetCultures(CultureTypes.SpecificCultures)
                .Select(c =&gt; new RegionInfo(c.Name))
                .OrderBy(c =&gt; c);
```

The second paragraph (as per below) in `Remarks` section is not a true statement as I cannot find some of the cultures ISO 3166 presents.

&gt; The name of a RegionInfo object is one of the two-letter codes defined in ISO 3166 for country/region. Case is not significant. The Name, TwoLetterISORegionName, and ThreeLetterISORegionName properties return the appropriate codes in uppercase. For the current list of RegionInfo names, see English country names and code elements on the ISO website.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c46c7e37-a657-2baa-14e5-f28337dd264e
* Version Independent ID: 63a4813e-a212-2379-41b0-2abcd1e36754
* Content: [RegionInfo Class (System.Globalization)](https://docs.microsoft.com/en-gb/dotnet/api/system.globalization.regioninfo?view=netframework-4.7.1)
* Content Source: [xml/System.Globalization/RegionInfo.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Globalization/RegionInfo.xml)
* Product: **dotnet-api**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by svick** [comment]
I don't understand, that paragraph does not say anything about what `CultureInfo.GetCultures(CultureTypes.SpecificCultures)` returns.

If you want to get region info for a specific region based on its ISO code, you can use [its constructor](https://docs.microsoft.com/en-gb/dotnet/api/system.globalization.regioninfo.-ctor?view=netframework-4.7.1#System_Globalization_RegionInfo__ctor_System_String_). Though at least for `AQ`, it requires that you also specify the language and depending on the OS, the results might not be ideal.

For example, consider this code:

```c#
new RegionInfo("en-AQ").DisplayName
```

On .Net Framework on Windows 10, this returns "Unknown Region (AQ)", while on .Net Core on Ubuntu, it returns "Antarctica".

**Comment by JRAlexander** [comment]
This appears to be resolved and will be closed. If that is not the case, @higtrollers, please reopen. Thanks, @svick, for your answer.

**Comment by higtrollers** [comment]
Thanks all!
