### ISSUE TITLE
Issues with equality in LINQ examples

### ISSUE THREAD

**Issue by svick** [dotnet/docs#7002]
The examples in this article that are related to equality have several issues:

1. The implementation of `DogHairLengthComparer.GetHashCode` is:

    https://github.com/dotnet/docs/blob/c7539d980f4e424d511b2bd30ade9ee6e7a9f3bc/docs/standard/using-linq.md#L168-L172

    I don't know what "simple objects" are, but this code is wrong: when two objects are compared as equal, they have to have the same hash code and this code does not guarantee that. This is easy to fix by changing the code to `return d.HairLengthType.GetHashCode();`.

2. https://github.com/dotnet/docs/blob/c7539d980f4e424d511b2bd30ade9ee6e7a9f3bc/docs/standard/using-linq.md#L177-L178

    I don't see how this code could do anything close to what the comment says. What it will do (assuming the comparer is fixed) is to return a "representative" dog for each hair length. I don't see how that would be useful, so I don't think it's a good example.

3. https://github.com/dotnet/docs/blob/c7539d980f4e424d511b2bd30ade9ee6e7a9f3bc/docs/standard/using-linq.md#L184-L186

    It's not clear to me what the comment is trying to say or how `VolunteerTimeComparer` is supposed to be implemented.

    The most reasonable interpretation I can think of is that the comparer considers volunteers with the same identification (e.g. `Name`) and time spent the same. The result would then be volunteers who spend exactly the same time in both societies.

    In any case, I think this example either needs to be clarified, or rewritten.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89e7bc95-4062-e6df-7475-21973ed1becc
* Version Independent ID: 571fd6fd-95b6-6fc9-d4df-9b44da6a01b4
* Content: [LINQ (Language Integrated Query)](https://docs.microsoft.com/en-us/dotnet/standard/using-linq)
* Content Source: [docs/standard/using-linq.md](https://github.com/dotnet/docs/blob/master/docs/standard/using-linq.md)
* Product: **dotnet**
* GitHub Login: @cartermp
* Microsoft Alias: **wiwagn**

**Comment by rpetrusha** [comment]
Thanks, @svick, for pointing out the issues with this topic. We'll investigate and update this issue. @cartermp, do you have any context on this code?
