### ISSUE TITLE
Unclear documentation - ServiceContract vs. ServiceContractAttribute

### ISSUE THREAD

**Issue by brotherBear** [dotnet/docs#7003]
As a complete noob on .Net and WCF, I found it very confusing when the example on this page uses a different `attribute` than the text on the same page. 

Another source told me that the two are in fact synonyms. If this is the case, I would recommend that this fact is explained on this page (and on the documentation for the Attributes)

In any case, the intermingling of the terms is very confusing for those new to the API.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11654f00-80a4-2ea6-006d-181eef5b5fdb
* Version Independent ID: 6d1505a2-8743-7369-4aec-db276169ac5d
* Content: [Implementing Service Contracts](https://docs.microsoft.com/en-us/dotnet/framework/wcf/implementing-service-contracts)
* Content Source: [docs/framework/wcf/implementing-service-contracts.md](https://github.com/dotnet/docs/blob/master/docs/framework/wcf/implementing-service-contracts.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by JRAlexander** [comment]
Thanks for your feedback, @brotherBear! This has been added to the backlog.

**Comment by JamesMBristow2** [comment]
I suggest reading about attributes on https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/attributes/. The note under the "Using attributes" section does call out this common convention.
