### ISSUE TITLE
SecurityException?

### ISSUE THREAD

**Issue by mgregory22** [dotnet/docs#7012]
The explanation for why the WebRequest.CreateHttp() call would throw a SecurityException currently states: "The caller does not have permission to connect to the requested URI or a URI that the request is redirected to."  Is that thrown if and only if the server returns a 401 HTTP status?  No, that can't be right because the request hasn't even executed yet.  What security is this referring to?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68ae6a59-0996-d889-16f5-a9fb589acbe8
* Version Independent ID: 293c2a47-b75c-0a39-9ccf-0d5d912ad481
* Content: [WebRequest.CreateHttp Method (System.Net)](https://docs.microsoft.com/en-us/dotnet/api/system.net.webrequest.createhttp?view=netframework-4.6.2)
* Content Source: [xml/System.Net/WebRequest.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net/WebRequest.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
@davidsh, can you comment on this issue?

**Comment by davidsh** [comment]
>SecurityException 
The caller does not have permission to connect to the requested URI or a URI that the request is redirected to.

A "Security Exception" is thrown only if this application is running on .NET Framework and is using less than "full-trust" security profile.

CAS (Code Access Security) is a concept that allows for applications to be hosted that don't have full privileges on the machine.  This was frequently used for web hosting scenarios.

See: https://docs.microsoft.com/en-us/dotnet/framework/misc/code-access-security

The `WebRequest` APIs require an application to have [WebPermission](https://docs.microsoft.com/en-us/dotnet/api/system.net.webpermissionattribute?view=netframework-4.7.2).

By default, applications will run with "full-trust".  So, this exception wouldn't normally be seen.

**Comment by mgregory22** [comment]
Thanks!
