### ISSUE TITLE
How to Switch Between the 2

### ISSUE THREAD

**Issue by spottedmahn** [dotnet/docs#7013]
This page does a great job of describing the differences but I can't find a link to how to switch between the two.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b76cb0d-df6d-88c4-557d-ad327a566eef
* Version Independent ID: 95083e1c-ef53-e813-08e2-1aa31b431f00
* Content: [Choose between .NET Core and .NET Framework for server apps](https://docs.microsoft.com/en-us/dotnet/standard/choosing-core-framework-server#see-also)
* Content Source: [docs/standard/choosing-core-framework-server.md](https://github.com/dotnet/docs/blob/master/docs/standard/choosing-core-framework-server.md)
* Product: **dotnet**
* GitHub Login: @cartermp
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
@spottedmahn what do you mean switch between the two? Can you provide more information on what you're trying to achieve?

**Comment by spottedmahn** [comment]
Hi @mairaw - sorry, I went too fast.

I was referring to switching an ASP.NET Core project to run on .NET Core to .NET Full Framework or vice versa.

**Comment by mairaw** [comment]
@Rick-Anderson @scottaddie do we have any guidance on that?

**Comment by cartermp** [comment]
In general, I would not recommend switching back and forth.

Unless you have a hard requirement to run on Windows and .NET Framework. If that's not a requirement, then running against .NET Core is probably preferable.

**Comment by spottedmahn** [comment]
Hi @scottaddie - the other way 😢.  I started an ASP.NET Core 2.1 app **targeting Core** and then needed to reference `System.Data.OleDb` which apparently is a Windows only thing.

At that point, I needed to **switch** to targeting the full framework.  I ended up creating a new project and copied the `.csproj` contents to my original project.

I also learned about this along the way: [Windows Compatibility Pack for .NET Core](https://blogs.msdn.microsoft.com/dotnet/2017/11/16/announcing-the-windows-compatibility-pack-for-net-core/).  Maybe that was the "right" answer but I didn't see `System.Data.OleDb` in the list so I moved on.

Thoughts? 💭

**Comment by scottaddie** [comment]
@spottedmahn See https://github.com/dotnet/corefx/issues/23542 for a discussion on this. I recommend joining the conversation over there.

**Comment by xdvarpunen** [comment]
@spottedmahn You might not need OleDb. I had to query data from Access `.mdb` and utilizing System DNS with `Windows Compatibility Pack for .NET Core` given `System.Data.Odbc` and installing Access database 64-bit drivers separately for that worked fine in .NET Core 2.1 👍 But spending 99% time in documentation is not fun 😢

**Comment by spottedmahn** [comment]
Oh, nice, thanks @xdvarpunen!

We're working to query Visual FoxPro 🙀 which seems to [only support this OleDb provider.](https://www.microsoft.com/en-us/download/details.aspx?id=14839)

**Comment by mairaw** [comment]
@divega can you comment here?

**Comment by divega** [comment]
I have not used this but an ODBC driver for Visual Fox Pro exists: https://docs.microsoft.com/en-us/sql/odbc/microsoft/visual-foxpro-odbc-driver?view=sql-server-2017. If you try that, it would be great to hear how it goes.

**Comment by spottedmahn** [comment]
Oh, nice, we'll have to try it out, thanks @divega!  And the documentation looks very thorough (unlike the zero documentation on the OleDb provider)!

**Comment by spottedmahn** [comment]
Hi @mairaw - so back to my original issue... how would one switch between the full framework and core and vice versa?

Is there any guidance/documentation already on this topic?  Thanks!

**Comment by xdvarpunen** [comment]
@spottedmahn To convert to full framework change `<TargetFrameworkVersion>net471</TargetFrameworkVersion>` in .csproj, reinstall existing and check nugets compatibility. Going back to Core is done same way. 

Changing targetframework documentation can be found [here.](https://docs.microsoft.com/en-us/dotnet/standard/frameworks)

**Comment by spottedmahn** [comment]
Nice, thanks @xdvarpunen! 

What about a link to that page on "this" page?  Thoughts? 💭

![image](https://user-images.githubusercontent.com/14079228/44309680-57e85300-a398-11e8-9550-8d0fca994c39.png)

**Comment by spottedmahn** [comment]
Thank you so much to everyone in this thread!!

**Comment by scottaddie** [comment]
@spottedmahn Thank you for helping us improve the docs.
