### ISSUE TITLE
Incorrect Description for receiveTimeout

### ISSUE THREAD

**Issue by yxrkt** [dotnet/docs#7014]
The function of receiveTimeout is to close a session when no messages have been received for a while.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b2df044-5ee1-a253-80f6-3fa92c5a88ad
* Version Independent ID: 44498f0c-62e0-f0ab-2130-118d6a71c16c
* Content: [&lt;netNamedPipeBinding&gt;](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/wcf/netnamedpipebinding)
* Content Source: [docs/framework/configure-apps/file-schema/wcf/netnamedpipebinding.md](https://github.com/dotnet/docs/blob/master/docs/framework/configure-apps/file-schema/wcf/netnamedpipebinding.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
@Lxiamail @mconnew can you comment on this issue?

**Comment by mconnew** [comment]
All the timeouts close the session once the specified time has elapsed. The existing description is accurate as "when no messages have been received for a while" is another way of saying the same thing as the existing description.
