### ISSUE TITLE
Provide bigger images

### ISSUE THREAD

**Issue by sebastienros** [dotnet/docs#7015]
On this article:
https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/large-object-heap

Some image are too small to provide any meaning (Fig. 2 and 3), but their full-size original source is available on this blog post when you click on them: 
https://blogs.msdn.microsoft.com/maoni/2016/05/31/large-object-heap-uncovered-from-an-old-msdn-article/

**Comment by JRAlexander** [comment]
Thanks, @sebastienros, for the feedback. This has been added to the backlog.
