### ISSUE TITLE
Propogate Down the call stack?

### ISSUE THREAD

**Issue by andynewcomb** [dotnet/docs#7019]
This Exception handling guide keeps referring to an exception being thrown "down the call stack" and in the opening paragraph state: 

"Once an exception is thrown, it propagates up the call stack until a catch statement for the exception is found"

I believe the runtime is executing code at the top of the call stack, and therefore an exception would be thrown at the top of the call stack and then propagate DOWN the call stack until an appropriate "Catch" is found.  Am I missing something? Or is this guide using the wrong verbage?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b719792d-1f95-6743-743a-8906fe08e764
* Version Independent ID: f67c914a-a895-2fd4-5b5a-2f5bedde1f91
* Content: [Using Exceptions (C# Programming Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/exceptions/using-exceptions#feedback)
* Content Source: [docs/csharp/programming-guide/exceptions/using-exceptions.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/exceptions/using-exceptions.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@andynewcomb The standard term is "up the call stack" for [historical reasons](https://stackoverflow.com/questions/664744/what-is-the-direction-of-stack-growth-in-most-modern-systems) relate to the i86 CPU architecture. We use that terminology consistently.

I'll close this as resolved.

**Comment by andynewcomb** [comment]
I believe the confusion here is due to the author treating the "call stack" as the same thing as the physical "memory stack". The "call stack" is just a concept... a series of methods/functions that grows from bottom to top. The physical memory stack (which you have provided  links for) is a physical location that grows from top to bottom. 
So really... this guide is incorrect in saying that the exception propagates up the call stack...that would be implying that the exception is generated and then more methods are added to the call stack. Bit confusing.
