### ISSUE TITLE
There is no AsStream() method.

### ISSUE THREAD

**Issue by moyanming** [dotnet/docs#7021]
According to the example [here](https://docs.microsoft.com/en-us/dotnet/standard/io/how-to-convert-between-dotnet-streams-and-winrt-streams#to-convert-from-a-windows-runtime-random-access-stream-to-a-net-framework-stream), I can't get the AsStream() method, how to fix this?
![qq 20180815213759](https://user-images.githubusercontent.com/13234209/44151021-df7860d4-a0d3-11e8-9d27-f96fc613f4cb.jpg)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 952ee6c9-05d4-b0a7-a46f-a73610ae97c5
* Version Independent ID: 0fa95ca6-118e-9a8b-2717-805759d0297a
* Content: [How to: Convert Between .NET Framework Streams and Windows Runtime Streams](https://docs.microsoft.com/en-us/dotnet/standard/io/how-to-convert-between-dotnet-streams-and-winrt-streams)
* Content Source: [docs/standard/io/how-to-convert-between-dotnet-streams-and-winrt-streams.md](https://github.com/dotnet/docs/blob/master/docs/standard/io/how-to-convert-between-dotnet-streams-and-winrt-streams.md)
* Product: **dotnet**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by tdykstra** [comment]
@moyanming Apologies for late response - do you still need an answer to this question?

**Comment by moyanming** [comment]
Hi @tdykstra,
It is wrong of my code, I should use await to get the stream.
