### ISSUE TITLE
Problems in backreference construction in regular expressions

### ISSUE THREAD

**Issue by LisandroSu** [dotnet/docs#7023]
@Jokacer commented on [Wed Aug 15 2018](https://github.com/dotnet/docs.zh-cn/issues/186)

In "What Backreferences match", in the explanation of the pattern "(?&lt;1&gt; a)(?&lt;1&gt; \ 1b)*" ，I think "(?&lt;1&gt;\1b)*" should match 1  value in group 1 instead of 0 or 1,is it right?

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: e2fa77ea-67e4-d972-e6c4-9eff4203ce3e
* Version Independent ID: 266c2d26-307c-09df-05d0-3946e34fb448
* Content: [正则表达式中的反向引用构造](https://docs.microsoft.com/zh-cn/dotnet/standard/base-types/backreference-constructs-in-regular-expressions#numbered-backreferences)
* Content Source: [docs/standard/base-types/backreference-constructs-in-regular-expressions.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/standard/base-types/backreference-constructs-in-regular-expressions.md)
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by LisandroSu** [comment]
Hi team,

Please check the question reported by the user.

Thanks!

**Comment by JRAlexander** [comment]
Thanks, @LisandroSu, this has been added to the backlog.

**Comment by Thraka** [comment]
@Jokacer The description was slightly misleading and is missing the * that makes it 0 or more. But yes, if the * was not included, it would be 1 or more.
