### ISSUE TITLE
Typo? 

### ISSUE THREAD

**Issue by FaridaAkhtyamova** [dotnet/docs#7030]
&lt;quote&gt; Beginning with C# 7.0, you can use pattern matching to both examine and get a value of a nullable type: if (x is int xValue) y = xValue; &lt;/quote&gt;
I think it should be x.Value as in the previous example?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab99a9ea-4645-92cd-723a-4a38fbee371e
* Version Independent ID: 652ea928-6ded-800c-6bed-5b1f3f67fe3f
* Content: [Nullable types (C# Programming Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/nullable-types/index)
* Content Source: [docs/csharp/programming-guide/nullable-types/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/nullable-types/index.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by pkulikov** [comment]
@FaridaAkhtyamova the code is correct: 
- `x` variable is of type `int?` while
- `xValue` is another variable of type `int` that contains the value `x.Value` if `x` has value.

That code uses pattern matching, in particular, the [`is` type pattern matching expression](https://docs.microsoft.com/en-us/dotnet/csharp/pattern-matching#the-is-type-pattern-expression)

Thank you for feedback. To avoid any confusion, I'll update the variable's name.
