### ISSUE TITLE
Data para dados

### ISSUE THREAD

**Issue by LisandroSu** [dotnet/docs#7035]
@alrcastro commented on [Thu Jul 12 2018](https://github.com/dotnet/docs.pt-br/issues/57)

Só um detalhe que o path no exemplo esta como "Data" e no começo foi pedido para criar uma pasta com o nomes de "Dados"

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: a30b3ff5-b5e6-ff02-6f60-b5cef6f34666
* Version Independent ID: fdf962e2-620e-d9ad-5057-5f96f52dc60f
* Content: [Usar o ML.NET para prever tarifas de táxi em Nova York (regressão)](https://docs.microsoft.com/pt-br/dotnet/machine-learning/tutorials/taxi-fare)
* Content Source: [docs/machine-learning/tutorials/taxi-fare.md](https://github.com/dotnet/docs.pt-br/blob/live/docs/machine-learning/tutorials/taxi-fare.md)
* GitHub Login: @aditidugar
* Microsoft Alias: **johalex**

---

@LisandroSu commented on [Thu Jul 12 2018](https://github.com/dotnet/docs.pt-br/issues/57#issuecomment-404620564)

Olá, @alrcastro , 

Agradecemos seus comentários. 

Vamos analisar seus comentários e daremos um retorno para você em breve. 

Atenciosamente, 
Equipe Internacional do Microsoft DOCS

**Comment by pkulikov** [comment]
@LisandroSu  This is the translation issue. The step 2 of this list:
https://docs.microsoft.com/pt-br/dotnet/machine-learning/tutorials/taxi-fare#create-a-console-application

says to create the folder "Dados" while the code sample uses the "Data" folder. Step 2 should be translated as
>... Digite "Data" e pressione Enter

Note that in the first step "TaxiFarePrediction" is correctly not translated.

**Comment by LisandroSu** [comment]
Hi team,

The user created this issue because the document makes them create a folder called "Data" and then write some example code with that fact in mind.

But the word is not locked in the document so it's translated to Portuguese making it inconsistent with the code example. 

Perhaps you can use `Data` every time the the word is used to refer to the directory so it can be locked.

Thanks!

**Comment by mairaw** [comment]
I'll have to discuss this with the team @LisandroSu. When started the migration to docs, we standardized on using italic for paths. I know that backticks guarantee that the word is locked for translation, but using backticks for everything might make the topic look and feel heavy. We already use for so many things.

**Comment by LisandroSu** [comment]
Hi @mairaw 

Thanks for the answer!

**Comment by LisandroSu** [comment]
Hi @mairaw 

Thanks for the answer. We will also process the PR you requested as soon as possible.

CC: @Sara-Nicolini

**Comment by JRAlexander** [comment]
This is also an issue in https://docs.microsoft.com/pt-br/dotnet/machine-learning/tutorials/sentiment-analysis.

**Comment by JRAlexander** [comment]
I believe it has been decided to leave as is. Closing.
