### ISSUE TITLE
Rewrite page for Linux

### ISSUE THREAD

**Issue by lukeperkins** [dotnet/docs#7036]
Please provide the "deb" line so that I can update my "/etc/apt/sources.list". Then provide the "apt-get download" command line so that I can install this product.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cfd5cf0-f28e-be49-227a-c2bbe4e57b8d
* Version Independent ID: 016b2a9c-d1c9-6909-df3e-a49db60b7654
* Content: [Prerequisites for .NET Core on Linux](https://docs.microsoft.com/en-us/dotnet/core/linux-prerequisites?tabs=netcore2x)
* Content Source: [docs/core/linux-prerequisites.md](https://github.com/dotnet/docs/blob/master/docs/core/linux-prerequisites.md)
* Product: **dotnet-core**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by JRAlexander** [comment]
@lukeperkins Click on the appropriate install link and it will take you to the download page which has those instructions.

**Comment by JRAlexander** [comment]
Closing as this appears resolved.
