### ISSUE TITLE
SchUseStrongCrypto and SystemDefaultTlsVersions registry keys are not retained after Windows 10 upgrades

### ISSUE THREAD

**Issue by gholliday** [dotnet/docs#7040]
If the `SchUseStrongCrypto` or `SystemDefaultTlsVersions` registry keys are set on a machine running a particular version of Windows 10 (e.g. v1709), and that machine is then upgraded to v1803, those registry keys are not retained and are no longer set.

It would probably be best for customers if these registry key settings were retained/migrated between Windows versions.

In the absence of that, I think it would be worthwhile calling out the behavior in this doc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7341fa0a-f474-6c2d-d3c0-7e2df12fbb65
* Version Independent ID: e99c489a-7518-d293-ad93-7eaca8b7191a
* Content: [Transport Layer Security (TLS) best practices with the .NET Framework](https://docs.microsoft.com/en-us/dotnet/framework/network-programming/tls)
* Content Source: [docs/framework/network-programming/tls.md](https://github.com/dotnet/docs/blob/master/docs/framework/network-programming/tls.md)
* Product: **dotnet-framework**
* GitHub Login: @blowdart
* Microsoft Alias: **dotnetcontent**

**Comment by blowdart** [comment]
It's on the to be fixed list, as I'm sure you're aware.

**Comment by gholliday** [comment]
The docs are going to be updated, or the registry keys are going to be retained?

**Comment by blowdart** [comment]
The registry keys are getting listed so they are retained.

**Comment by mairaw** [comment]
Ok, so do we want to add anything to the docs for now @blowdart?

**Comment by blowdart** [comment]
@BrettLopez can make a decision
