### ISSUE TITLE
help

### ISSUE THREAD

**Issue by GalaxyFour** [dotnet/docs#7041]
how to select data when table is inserted with sqltransactions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2fdf0875-ec95-805c-d1eb-774bb032822b
* Version Independent ID: 8facbdab-29f6-e657-460c-18b4346757e3
* Content: [SqlTransaction Class (System.Data.SqlClient)](https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqltransaction?redirectedfrom=MSDN&view=netframework-4.7.2)
* Content Source: [xml/System.Data.SqlClient/SqlTransaction.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Data.SqlClient/SqlTransaction.xml)
* Product: **dotnet-api**
* GitHub Login: @douglaslMS
* Microsoft Alias: **douglasl**

**Comment by douglaslMS** [comment]
@GalaxyFour Can you please clarify the case that you're asking about? Do you mean, how to select data when you have _created_ the table inside a transaction, or how to select data when you have _inserted the data_ inside a transaction? Are you running into a specific error or failure that you're trying to resolve?

**Comment by douglaslMS** [comment]
@GalaxyFour Can you please clarify your question? See my comment from last week. Thanks.

**Comment by GalaxyFour** [comment]
i use trans = con.BeginTransaction(IsolationLevel.ReadUncommitted, "transInsert")
to edit or select inserted data in transaction
