### ISSUE TITLE
Error in the Stub static references "better" example?

### ISSUE THREAD

**Issue by Kornelis** [dotnet/docs#7044]
Hi,

shouldn't the optimized example of the `GetDiscountedPrice()` Method use `dateTimeProvider.DayOfWeek()` instead of `DateTime.Now`?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51947dc8-9ae8-21fa-13db-a7ffb3f9bc0e
* Version Independent ID: be661bf5-6f6e-cd18-344b-253edf5751ae
* Content: [Best practices for writing unit tests](https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-best-practices#lets-speak-the-same-language)
* Content Source: [docs/core/testing/unit-testing-best-practices.md](https://github.com/dotnet/docs/blob/master/docs/core/testing/unit-testing-best-practices.md)
* Product: **dotnet-core**
* GitHub Login: @jpreese
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for reporting this @Kornelis  We appreciate it.  You are correct, the final version of the code under test should make use of the `IDateTimeProvider` object.

@jpreese Do you want to submit the fix, or should I?

**Comment by jpreese** [comment]
Good catch @Kornelis! I've added a PR for this, @BillWagner.
