### ISSUE TITLE
Examples needed

### ISSUE THREAD

**Issue by 0ndrej** [dotnet/docs#7045]
There is no example for such complex problem like setting ACL for folder.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cea9204-8831-ce57-c43b-8bf75fe65802
* Version Independent ID: ef7a786f-d2e0-5272-9aa1-fd3a4c8b8f49
* Content: [FileSystemSecurity.SetAccessRule(FileSystemAccessRule) Method (System.Security.AccessControl)](https://docs.microsoft.com/en-us/dotnet/api/system.security.accesscontrol.filesystemsecurity.setaccessrule?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(System.Security.AccessControl.FileSystemSecurity.SetAccessRule);k(TargetFrameworkMoniker-.NETFramework,Version%3Dv4.7.1);k(DevLang-VB)%26rd%3Dtrue%26f%3D255%26MSPPError%3D-2147217396&view=netframework-4.7.2)
* Content Source: [xml/System.Security.AccessControl/FileSystemSecurity.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Security.AccessControl/FileSystemSecurity.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by JRAlexander** [comment]
@0ndrej, I think this is what you are looking for: https://docs.microsoft.com/en-us/dotnet/api/system.security.accesscontrol.directorysecurity?view=netframework-4.7.2

**Comment by JRAlexander** [comment]
@0ndrej, I believe this is resolved, so I'm closing it. If this isn't the case, please reopen.
