### ISSUE TITLE
.Net supported version missing

### ISSUE THREAD

**Issue by AizazAZ** [dotnet/docs#7046]
If I have to update so I have to see which .Net version is required for this control. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79395f69-e1fe-02ce-9687-923b42b96326
* Version Independent ID: de462407-3129-4299-6892-8106bf4823a7
* Content: [Differences Between the Windows Forms DataGridView and DataGrid Controls](https://docs.microsoft.com/en-us/dotnet/framework/winforms/controls/differences-between-the-windows-forms-datagridview-and-datagrid-controls)
* Content Source: [docs/framework/winforms/controls/differences-between-the-windows-forms-datagridview-and-datagrid-controls.md](https://github.com/dotnet/docs/blob/master/docs/framework/winforms/controls/differences-between-the-windows-forms-datagridview-and-datagrid-controls.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by JRAlexander** [comment]
Hi, @AizazAZ, You can click on the DataGridView link in the article, which will take you to the API page. On the right-hand side, click on the Applies To link, which will show you the applicable versions.  I've also included the link [here](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.datagridview?view=netframework-4.7.2#applies-to). Closing this item as I believe it is resolved. If this isn't the case, please reopen.
