### ISSUE TITLE
It would be nice to get the C# releases in the form of a feed

### ISSUE THREAD

**Issue by lfr** [dotnet/docs#7048]
This way I could have C# releases and their descriptions appear in my news aggregator!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c36588d0-6bdf-1740-220c-10b20bb88730
* Version Independent ID: 587ed47f-f532-e018-9b0d-6ee76afd20e4
* Content: [What's New in C# - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/)
* Content Source: [docs/csharp/whats-new/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/whats-new/index.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@dend I thought this was implemented, but I can't find the widget. Do you remember?

**Comment by BillWagner** [comment]
Transferred to MicrosoftDocs/Feedback#2010.

Closing this as docs-experience.
