### ISSUE TITLE
文章中改突出的行没有突出

### ISSUE THREAD

**Issue by LisandroSu** [dotnet/docs#7055]
@hjkl950217 commented on [Wed Aug 15 2018](https://github.com/dotnet/docs.zh-cn/issues/187)

文章中有提到“请注意突出的行”。但是实现显示时，代码中并没有看到有突出行

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 36115425-3181-1363-dcbd-42e48db8613c
* Version Independent ID: 57ca5426-2ae3-7260-cef9-e92dc9d4e856
* Content: [委托和 lambda](https://docs.microsoft.com/zh-cn/dotnet/standard/delegates-lambdas#feedback)
* Content Source: [docs/standard/delegates-lambdas.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/standard/delegates-lambdas.md)
* GitHub Login: @richlander
* Microsoft Alias: **wiwagn**

**Comment by JRAlexander** [comment]
@LisandroSu, can you please translate?

**Comment by LisandroSu** [comment]
Hi team,

The issue created by the user is about the documentation saying there are some "highlighted" lines of code but there's no highlighted code in the examples.

I checked the localized and source documents and neither have any highlighted lines of code. Could you help us out with this?

Thanks!

**Comment by hjkl950217** [comment]
I can watch the issues~

**Comment by mairaw** [comment]
I'm going to close this one as a duplicate of #7255, which covers other issues with the same topic.
