### ISSUE TITLE
Error in example

### ISSUE THREAD

**Issue by rickfleischer** [dotnet/docs#7056]
counter = ++counter + numberOfEmployees; // logic is wrong; should be
counter = ++numberOfEmployees; // add a few employees and you will see

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e8e455c-1162-d046-ed70-22dfe96cbbad
* Version Independent ID: 9448a018-a06c-0ae5-049b-c4c424d1df9a
* Content: [Interface Properties (C# Programming Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/interface-properties)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/interface-properties.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/interface-properties.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for pointing this out @rickfleischer 

I've added it to our backlog. 

If you'd like to submit a PR, I'll look at it and approve it.
