### ISSUE TITLE
 docs/docs/core/tools/csproj.md Missing NuGet Summary

### ISSUE THREAD

**Issue by MelbourneDeveloper** [dotnet/docs#7064]
There is no metadata field for NuGet Summary

EDIT by Thraka to add in the docs header info

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb4428fc-215c-78e1-5ff0-fe73f7a08260
* Version Independent ID: 6741b1de-38a4-fbb1-d79d-acc47d549a2d
* Content: [Additions to the csproj format for .NET Core - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/csproj)
* Content Source: [docs/core/tools/csproj.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/csproj.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment]
@MelbourneDeveloper This seems to have fallen off of the radar. I believe I understand what you're trying to get at, the csproj fields that correspond to the nuget fields is not documented very well, correct?

**Comment by MelbourneDeveloper** [comment]
Thanks @thraka but it's more about fields that cannot be edited in the csproj file. Visual Studio 2019 is a lot better than 2017 but I think there is still one or two fields missing. I have to manually edit the NuGet after building.

**Comment by MelbourneDeveloper** [comment]
It's all about the package tab of the project in VS

**Comment by Thraka** [comment]
Gotcha. This is more of a feature request around Visual Studio. I would file a bug over at https://developercommunity.visualstudio.com/spaces/8/index.html to start. This isn't a bug with our documentation 😄 I'm going to close this.
