### ISSUE TITLE
requestValidationMode=0.0 undocumented

### ISSUE THREAD

**Issue by ahockersten** [dotnet/docs#7075]
It seems, according to the reference source code (https://github.com/Microsoft/referencesource/blob/master/System.Web/HttpRequest.cs), that it is possible to set requestValidationMode="0.0", to disable validation completely. In fact, looking at that code (and my own experiments) setting it to "2.0" will not disable request validation completely, only setting it to "0.0" will do that.

This also means the section stating that "Any numeric value smaller than 4.0 (for example, 3.7, 2.9, or 2.0) is interpreted as 2.0." is erroneous, as "0.0" will result in a different behavior than setting "2.0".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a348f32-e8ba-0484-4bfe-d1f88ff9adef
* Version Independent ID: 6b3e9fd1-914a-3e40-bd2f-199da92c74d8
* Content: [HttpRuntimeSection.RequestValidationMode Property (System.Web.Configuration)](https://docs.microsoft.com/en-us/dotnet/api/system.web.configuration.httpruntimesection.requestvalidationmode?redirectedfrom=MSDN&view=netframework-4.7.2#System_Web_Configuration_HttpRuntimeSection_RequestValidationMode)
* Content Source: [xml/System.Web.Configuration/HttpRuntimeSection.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Web.Configuration/HttpRuntimeSection.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks for your feedback @ahockersten. @scottaddie @Rick-Anderson can one of you look at this?

**Comment by Rick-Anderson** [comment]
@danroth27  who can review this?

**Comment by danroth27** [comment]
@Eilon ?

**Comment by Rick-Anderson** [comment]
@HongGit can you answer this?

**Comment by HongGit** [comment]
@ahockersten what you have observed is correct.
Setting _requestValidationMode="0.0"_ will completely disable request validation in an application. 
Setting _requestValidationMode="2.0"_ will revert back to the original behavior.  

This change was added in .NET 4.6 and above.

@Rick-Anderson could you please help us to get the documentation updated?

**Comment by mairaw** [comment]
@Rick-Anderson has created PR https://github.com/dotnet/dotnet-api-docs/pull/447 for this. @HongGit please help review it.
