### ISSUE TITLE
Unable to build Project

### ISSUE THREAD

**Issue by NishantThakkar** [dotnet/docs#7077]
# Unable to build Project
Getting error message: CS5001 Program does not contain a static 'Main' method suitable for an entry point.

![2018-08-17_20-06-55](https://user-images.githubusercontent.com/5793534/44272063-6ed45b80-a259-11e8-82be-6a439e0169e8.png)

**Comment by JRAlexander** [comment]
Hi, @NishantThakkar, did you download the sample or work through the tutorial?

**Comment by NishantThakkar** [comment]
@JRAlexander, I have work through the tutorial not downloaded tutorial.

**Comment by JRAlexander** [comment]
Check your properties on Program.cs. Sounds like you may have changed the build action. Should be "C# compiler".

**Comment by JRAlexander** [comment]
@NishantThakkar, closing this as it appears to be resolved.

**Comment by JRAlexander** [comment]
That's good to hear!
