### ISSUE TITLE
Paging Methods description poor

### ISSUE THREAD

**Issue by NetMage** [dotnet/docs#7079]
Paging Methods says they return a single, specific element, but then includes methods like Skip, Take and TakeWhile that return multiple elements, and also TakeWhile is unsupported.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aeb5d98e-7ea1-6cad-8cb3-7c4a2495eb9a
* Version Independent ID: c3347c02-11ea-79f2-35cd-abf888df9904
* Content: [Standard Query Operators in LINQ to Entities Queries](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/ef/language-reference/standard-query-operators-in-linq-to-entities-queries)
* Content Source: [docs/framework/data/adonet/ef/language-reference/standard-query-operators-in-linq-to-entities-queries.md](https://github.com/dotnet/docs/blob/master/docs/framework/data/adonet/ef/language-reference/standard-query-operators-in-linq-to-entities-queries.md)
* Product: **dotnet-framework**
* GitHub Login: @douglaslMS
* Microsoft Alias: **douglasl**

**Comment by douglaslMS** [comment]
Based on [Supported and Unsupported LINQ Methods (LINQ to Entities) | Paging Methods](Paging Methods), it seems that the only supported methods are: **First, FirstOrDefault, Single, SingleOrDefault, Skip, Take**. So it seems that this list needs other corrections in addition to the corrections you're suggesting. Do you agree?

**Comment by NetMage** [comment]
Yes, Last and LastOrDefault are also not supported.
