### ISSUE TITLE
Inaccuracies on ManualResetEvent page

### ISSUE THREAD

**Issue by kwalker360** [dotnet/docs#7083]
I see two issues here:
(1) The C# code showing the class definition shows ManualResetEvent inherits from EventWaitHandle, but the Inheritence section shows it inherits from WaitHandle.
{2} The Reset() method is missing from the list of methods. (Fortunately it is discussed in the Remarks section and the link there works.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43502a0b-0e55-14fb-1771-26630e891c68
* Version Independent ID: 111d5b72-5469-93f2-f199-1456300225cd
* Content: [ManualResetEvent Class (System.Threading)](https://docs.microsoft.com/en-us/dotnet/api/system.threading.manualresetevent?redirectedfrom=MSDN&view=netframework-4.7.2)
* Content Source: [xml/System.Threading/ManualResetEvent.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Threading/ManualResetEvent.xml)
* Product: **dotnet-api**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by mairaw** [comment]
Thanks @kwalker360 for your feedback. It seems that our reflection tooling understands there differences between versions but then the UI doesn't know how to handle that:
https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Threading/ManualResetEvent.xml#L27

Given that this issue requires engineering work, I'm moving this to https://github.com/MicrosoftDocs/feedback/issues/616

/cc @dend

**Comment by kwalker360** [comment]
Okay, thanks!
