### ISSUE TITLE
checksum usage

### ISSUE THREAD

**Issue by ghost** [dotnet/docs#7095]
In which ASP.NET project file are we supposed to use the #pragma checksum directive?

I created a ASP.NET project and I did not find a checksum nor a .aspx file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 210e00ee-38fd-1392-c684-8a340e6b9df6
* Version Independent ID: af2c6344-1de0-ecb5-10c3-c6ccf238e372
* Content: [#pragma checksum (C# Reference)](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/preprocessor-directives/preprocessor-pragma-checksum)
* Content Source: [docs/csharp/language-reference/preprocessor-directives/preprocessor-pragma-checksum.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/preprocessor-directives/preprocessor-pragma-checksum.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@johnnyagerard You likely won't ever add this pragma yourself.
An ASP.NET WebForms application uses this pragma for the code generated from aspx pages. It's also used by some XAML frameworks.

That could be clarified in this article. I've added this to our backlog, and added the up-for-grabs label.

**Comment by johnnyagerard** [comment]
@BillWagner All right. Thank you for the explanation.

**Comment by jwwicks** [comment]
@BillWagner I'll grab this. There's a sentence about this being used for ASP.NET projects and .aspx pages already, Do you want to include a specific example for an ASP.NET/XAML framework instead of the generic one provided? Have to admit I've never used this pragma in .Net myself. I've seen it in auto generated files but never had to explicitly use it myself.

**Comment by BillWagner** [comment]
@jwwicks Thanks for grabbing this.

I think the current explanation is fine. I think the key addition is that the ASP.NET or XAML frameworks make use of this pragma. Most developers won't need to declare it.
