### ISSUE TITLE
target framework preprocessor symbols 

### ISSUE THREAD

**Issue by ghost** [dotnet/docs#7096]
If those preprocessor symbols are predefined, why can't I use them?

For example, I created a console app  that targets the .Net Framework 4.7.2.

I would expect that the NET472 symbol would be defined but it isn't.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a331b150-4033-7629-75ad-9f9ea74f3ce5
* Version Independent ID: 8e0adfd9-c41b-d059-a418-155021a95d7b
* Content: [#if preprocessor directive (C# Reference)](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/preprocessor-directives/preprocessor-if)
* Content Source: [docs/csharp/language-reference/preprocessor-directives/preprocessor-if.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/preprocessor-directives/preprocessor-if.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
That is only true for SDK-style projects @johnnyagerard. I need to fix that. Thanks for the feedback!

**Comment by mairaw** [comment]
Should also fix this internal issue as part of this work item: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/685179?
