### ISSUE TITLE
Incorrect?

### ISSUE THREAD

**Issue by LambertWM** [dotnet/docs#7098]
The page with title "ToolStripLayoutStyle Enum" contradicts the statement that "Table" is the default.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b11141f0-dc8e-f533-3057-d41ac21d8e9b
* Version Independent ID: 821e80b7-e61e-28ab-4e1b-624f27cc3d2b
* Content: [StatusStrip.LayoutStyle Property (System.Windows.Forms)](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.statusstrip.layoutstyle?redirectedfrom=MSDN&view=netframework-4.7.2#System_Windows_Forms_StatusStrip_LayoutStyle)
* Content Source: [xml/System.Windows.Forms/StatusStrip.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Windows.Forms/StatusStrip.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
Thanks for pointing out the contradiction, @LambertWM. Evidently, the ToolStripLayoutStyle enumeration documentation was written under the assumption either that ToolStrip was the only control that a LayoutStyle property or that no derived class of ToolStrip overrode the property value. 

We've addressed this issue in dotnet/dotnet-api-docs#446.
