### ISSUE TITLE
C# tutorials - attributes

### ISSUE THREAD

**Issue by stevehoag** [dotnet/docs#71]
Show how to provide additional information about programming elements such as types, fields, methods, and properties by using attributes.

Tutorials should include one or more code examples, each example should also show expected output and should include an explanation of the code where it isn't obvious. Examples shouldn't be dependent on a specific IDE or target platform.

**Comment by mgroves** [comment]
I'd be interested in writing this tutorial. Anything in particular that needs to be covered? The basics of how to write one, conventions, and how to use it?

Attributes really don't do anything by themselves (with some exceptions like CallerMemberName, CallerFilePath, and some others that I can't think of right now). So this would be a reflection-heavy tutorial?

Certainly a lot of tools/frameworks use them: MVC, Json.Net, EF, NUnit, and so on, and it might be worthwhile mentioning them as an example.

**Comment by BillWagner** [comment]
@mgroves Thanks for wanting to take this on! I apologize for the slightly late reply. I was traveling. 

I think this should cover:

1. How to add attributes to code.
2. How to create new attribute types.
3. How to restrict attribute usage to Class, Method, etc.
4. How to find Attributes attached to a code element (which would use reflection.)
5. Examples of a few common attributes in the BCL (obsolete, conditional, and so on).

Let me now if you have want early reviews of outlines or drafts.

**Comment by mgroves** [comment]
Sounds great. Should I just submit pull request for your review/feedback?

**Comment by BillWagner** [comment]
That would be great. Just @ - message me when you submit it.
