### ISSUE TITLE
GeneratePackageOnBuild missing from docs

### ISSUE THREAD

**Issue by dansiegel** [dotnet/docs#7101]
There doesn't seem to be any reference here (which there should be IMO) to the GeneratePackageOnBuild property. It would be great to have it added to the docs particularly with an explanation of how it works with IsPackable 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb4428fc-215c-78e1-5ff0-fe73f7a08260
* Version Independent ID: 6741b1de-38a4-fbb1-d79d-acc47d549a2d
* Content: [Additions to the csproj format for .NET Core](https://docs.microsoft.com/en-us/dotnet/core/tools/csproj)
* Content Source: [docs/core/tools/csproj.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/csproj.md)
* Product: **dotnet-core**
* GitHub Login: @blackdwarf
* Microsoft Alias: **mairaw**

**Comment by gewarren** [comment]
Some info is here: https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package-msbuild#automatically-generate-package-on-build

**Comment by gewarren** [comment]
Since the csproj article will be removed tomorrow, and its replacement doesn't cover NuGet publish properties directly, I'm going to close this issue. I will reopen https://github.com/NuGet/docs.microsoft.com-nuget/issues/1097 instead.
