### ISSUE TITLE
Alpine Linux installation links are wrong

### ISSUE THREAD

**Issue by leecow** [dotnet/docs#7103]
https://docs.microsoft.com/en-us/dotnet/core/linux-prerequisites

All links point to the SLES install page rather than the Alpine pages. Should be: 

* Runtime - https://www.microsoft.com/net/download/thank-you/dotnet-runtime-2.1.2-linux-x64-alpine-binaries
* SDK - https://www.microsoft.com/net/download/thank-you/dotnet-sdk-2.1.400-linux-x64-alpine-binaries 

Other available versions can be seen on https://www.microsoft.com/net/download/dotnet-core/2.1

**Comment by JRAlexander** [comment]
Thanks, @leecow. I'll get it updated straightaway!
