### ISSUE TITLE
Incorrect variable name 

### ISSUE THREAD

**Issue by su8898** [dotnet/docs#7107]
In the "Creating a continuation for a single antecedent" example, variable `taskB` is mentioned in the description but its not named accordingly in the code sample.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be073b14-6d0b-60be-7dff-4674bcb6c674
* Version Independent ID: a5fa3e78-73de-3360-1253-00545a2b4ef2
* Content: [Chaining Tasks by Using Continuation Tasks](https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/chaining-tasks-by-using-continuation-tasks#creating-a-continuation-for-a-single-antecedent)
* Content Source: [docs/standard/parallel-programming/chaining-tasks-by-using-continuation-tasks.md](https://github.com/dotnet/docs/blob/master/docs/standard/parallel-programming/chaining-tasks-by-using-continuation-tasks.md)
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by rpetrusha** [comment]
Thanks for pointing out the incorrect variable name, @su8898. We'll correct the error in the near future.
