### ISSUE TITLE
UdpState class does not exist but is used in example

### ISSUE THREAD

**Issue by fredlllll** [dotnet/docs#7108]
There is no such class as UdpState. where the hell does this come from? the example is not working with that

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1939bdd8-db2d-c0af-0e4d-121c9abf261f
* Version Independent ID: fab051cf-b3ec-889e-8b2b-2c41473084ea
* Content: [UdpClient.BeginReceive(AsyncCallback, Object) Method (System.Net.Sockets)](https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.udpclient.beginreceive?redirectedfrom=MSDN&view=netframework-4.7.2#System_Net_Sockets_UdpClient_BeginReceive_System_AsyncCallback_System_Object_)
* Content Source: [xml/System.Net.Sockets/UdpClient.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Sockets/UdpClient.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by Brutiful-Games** [comment]
It is a user-defined class according to MSDN Help.  This is according to bensari's response in this post:

https://social.msdn.microsoft.com/Forums/vstudio/en-US/4c2a3db7-5f82-4cae-9589-ad720b8efb64/where-can-i-find-udpstate-udp-programming-problem?forum=csharpgeneral

**Comment by fredlllll** [comment]
then that should be inside the example. though i am still wondering how i can cast a System.Net.Sockets.OriginalAddressOverlappedAsyncResult (which is what i get when debugging) to a custom type that has nothing to do with it. especially as the mentioned type is an internal one.

**Comment by rpetrusha** [comment]
Thanks for your comments, @fredlllll and @Brutiful-Games. I've opened PR dotnet/samples#249 to add the source for `UdpState` to the example.
