### ISSUE TITLE
Docs for Dummies !

### ISSUE THREAD

**Issue by stevehtml** [dotnet/docs#7112]
Been to many sites have excellent explanations miles over my head , or examples I need a degree in computer science to follow so this is very refreshing Thank you !

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e002f1d1-62ea-2075-f223-3da0afa9a779
* Version Independent ID: 1e082b3e-0d02-f6f0-90bb-5de3980b07fe
* Content: [DirectoryInfo Class (System.IO)](https://docs.microsoft.com/en-us/dotnet/api/system.io.directoryinfo?view=netframework-4.7.2)
* Content Source: [xml/System.IO/DirectoryInfo.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.IO/DirectoryInfo.xml)
* Product: **dotnet-api**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by rpetrusha** [comment]
Thanks for the positive feedback, @stevehtml. We're pleased that you found this content to be helpful and accessible.
