### ISSUE TITLE
Further Implementation details would be nice

### ISSUE THREAD

**Issue by BKSpurgeon** [dotnet/docs#7114]
Would like to see how Create(String, Int32, FileOptions) and Create(String, Int32, FileOptions, FileSecurity) is implemented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29d94a8d-341c-5f29-7640-704144f60b69
* Version Independent ID: bb63691f-ecc3-0e26-3297-32b6e329d06a
* Content: [File.Create Method (System.IO)](https://docs.microsoft.com/en-us/dotnet/api/system.io.file.create?redirectedfrom=MSDN&view=netframework-4.7.2#System_IO_File_Create_System_String_System_Int32_System_IO_FileOptions_)
* Content Source: [xml/System.IO/File.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.IO/File.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by BKSpurgeon** [comment]
> Or are you saying that the documentation should contain link to the source code of those methods?

That's correct.

Thank you for the link.

A simple Google search didn't yield the source code.

rgds

**Comment by gewarren** [comment]
Great news - the core .NET libraries now have links to source code!
Example: https://learn.microsoft.com/dotnet/api/system.string.chars?view=net-8.0
