### ISSUE TITLE
Not supported on .NET Core 2.x

### ISSUE THREAD

**Issue by boskjoett** [dotnet/docs#7115]
This method, and ToXmlString, is not supported on .NET Core 2.x so .NET Core 2.0/2.1 should not be mentioned in Applies To section.
See: https://github.com/dotnet/corefx/issues/23686

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e4d7732-8ac1-09f6-a2b4-859e1eeb405e
* Version Independent ID: a51533e9-699e-cf31-aca6-2a89a460c192
* Content: [RSA.FromXmlString(String) Method (System.Security.Cryptography)](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.rsa.fromxmlstring?view=netframework-4.7.2)
* Content Source: [xml/System.Security.Cryptography/RSA.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Security.Cryptography/RSA.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
Thanks for pointing this out, @boskjoett. We'll modify the documentation to note that a method call on .NET Copre throws a not supported exception.

**Comment by mairaw** [comment]
Just to clarify one aspect of the docs is that the Applies to section infers that information from the reference assemblies and that API exists in .NET Core 2.0+. The fact that it doesn't have an implementation is something that we need to manually call out.

**Comment by mairaw** [comment]
@pjanotti @kouvel for the [wiki page](https://github.com/dotnet/corefx/wiki/ApiCompat) page, can we have the specific APIs called out? For example, We have FromXmlString called out for the AsymmetricAlgorithm, but we don't have a specific one for RSA. Sure, RSA inherits from AsymmetricAlgorithm, but it won't be obvious as we try to document the exceptions.

**Comment by kouvel** [comment]
The [area owners](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/issue-guide.md) would be able to clarify.

CC @bartonjs @GrabYourPitchforks
