### ISSUE TITLE
chain of owner window

### ISSUE THREAD

**Issue by eladpotok** [dotnet/docs#7116]
assume that I have a chain of WPF windows which have an ownership.
window1 is owner of window2.
windo2 is owner of window3 and etc.

I found out that the ownership is broken at the 50s window.
does anyone know why and how can I solve this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60e12b63-d52c-fa7a-2af6-bcdcd1c35eed
* Version Independent ID: f48f07b4-52a3-e1b8-937d-22662542389f
* Content: [Window.Owner Property (System.Windows)](https://docs.microsoft.com/en-us/dotnet/api/system.windows.window.owner?redirectedfrom=MSDN&view=netframework-4.7.2#System_Windows_Window_Owner)
* Content Source: [xml/System.Windows/Window.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Windows/Window.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
Thanks for your comment, @eladpotok. This is a good question to ask on [StackOverflow](https://www.stackoverflow.com).
