### ISSUE TITLE
Incorrect | (logical OR) symbol in example

### ISSUE THREAD

**Issue by paultechguy** [dotnet/docs#7118]
else if (b1 == null | b2 == null)

should be:

else if (b1 == null || b2 == null)

https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.iequalitycomparer-1?redirectedfrom=MSDN&view=netframework-4.7.2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a605459-4c87-84d5-56d5-e6b43c42c9c2
* Version Independent ID: b052b058-9534-6a59-17c7-99c4d774571c
* Content: [IEqualityComparer&lt;T&gt; Interface (System.Collections.Generic)](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.iequalitycomparer-1?redirectedfrom=MSDN&view=netframework-4.7.2)
* Content Source: [xml/System.Collections.Generic/IEqualityComparer`1.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Collections.Generic/IEqualityComparer`1.xml)
* Product: **dotnet-api**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by rpetrusha** [comment]
Thanks for your comment, @paultechguy. Would you like to submit a PR to address this issue?

**Comment by paultechguy** [comment]
Done.

https://github.com/dotnet/samples/pull/252

/paul
