### ISSUE TITLE
missing command?

### ISSUE THREAD

**Issue by johnnyagerard** [dotnet/docs#7120]
Using the C# compiler help in the command line (by typing "csc /?", I can see that this compiler option is unlisted.
Furthermore, I get the following result:
```console
C:\Users\johnn\source\repos\Test&gt;csc *cs /bugreport:name
Microsoft (R) Visual C# Compiler version 2.9.0.63208 (958f2354)
Copyright (C) Microsoft Corporation. All rights reserved.

warning CS8001: The command line switch '/bugreport' is not yet implemented and was ignored.
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be33a52b-a760-85f8-c17c-0f183284569e
* Version Independent ID: eca8e682-35f9-d939-5fd1-c2b44614c19a
* Content: [-bugreport (C# Compiler Options)](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/bugreport-compiler-option)
* Content Source: [docs/csharp/language-reference/compiler-options/bugreport-compiler-option.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/bugreport-compiler-option.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by johnnyagerard** [comment]
first line of console code is:
C:\Users\johnn\source\repos\Test>csc *cs /bugreport:name

**Comment by mairaw** [comment]
@jcouv @jaredpar it seems we're waiting for your feedback on this issue

/cc @BillWagner

**Comment by jcouv** [comment]
My inclination is to not document. I'll let @jaredpar confirm

**Comment by jaredpar** [comment]
Agree do not document this switch. 

Now I need to go and read up on whath this switch is. In the 10+ years I've been on this team we've never used it to my understanding.

**Comment by mairaw** [comment]
Thank you for confirming @jcouv and @jaredpar. Closing this issue then.
