### ISSUE TITLE
How can I use C# version 7.3?

### ISSUE THREAD

**Issue by jahbenjah** [dotnet/docs#7123]
I'm running this example with dotnet version 2.1.400 in VSCode and get the warning  "CS8371: Field-targeted attributes on auto-properties are not supported in language version 7.0. Please use language version 7.3 or greater."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7bc5cfb-d247-62c8-2173-9403efe72b16
* Version Independent ID: 3fab702d-66a7-3338-6c61-f535b29d86a7
* Content: [Walkthrough: Persisting an Object using C#](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/serialization/walkthrough-persisting-an-object-in-visual-studio)
* Content Source: [docs/csharp/programming-guide/concepts/serialization/walkthrough-persisting-an-object-in-visual-studio.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/serialization/walkthrough-persisting-an-object-in-visual-studio.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by jahbenjah** [comment]
Here is the answer [Select C # language version] (https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version) but I think these documents should be linked in some way.

**Comment by BillWagner** [comment]
@jahbenjah has pointed to the correct fix.  This article should say that C# 7.3, and link to that article for instructions on how to set the language version.

I've added the up-for-grabs label, and added this article to our community contribution project if someone wants to create a PR for this issue.

**Comment by BillWagner** [comment]
@Niladri24dutta That would be the best fix.  Thanks.  I'll watch for the PR.

**Comment by Niladri24dutta** [comment]
@BillWagner PR created #8014
