### ISSUE TITLE
La dirección de UploadFile necesita incluir un nombre de archivo. Al cargar archivos con el método UploadFile , debe proporcionar un nombre de archivo en la ruta de acceso de destino.

### ISSUE THREAD

**Issue by gosali** [dotnet/docs#7135]
@yapusito commented on [Sat Aug 18 2018](https://github.com/dotnet/docs.es-es/issues/52)

Esa respuesta la hizo el mismo de: el teclado dejó de funcionar, presione una tecla para continuar"

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: b160765f-ed50-e0a8-a0b5-0295f91e8463
* Version Independent ID: 44084b0a-77b8-5e12-a602-84a55ef1f5a0
* Content: [La dirección de UploadFile necesita incluir un nombre de archivo.](https://docs.microsoft.com/es-es/dotnet/visual-basic/misc/the-address-for-uploadfile-needs-to-include-a-filename)
* Content Source: [docs/visual-basic/misc/the-address-for-uploadfile-needs-to-include-a-filename.md](https://github.com/dotnet/docs.es-es/blob/live/docs/visual-basic/misc/the-address-for-uploadfile-needs-to-include-a-filename.md)
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by gosali** [comment]
Hi Team,

The end user claims that the instructions are unclear or and useless. 
![image](https://user-images.githubusercontent.com/16022575/44368935-e3ea9f80-a4aa-11e8-97e1-6766b5957935.png)


Could you please check it can be improved?

Back Translation:
"That answer was made by the same: the keyboard stopped working, press a key to continue ""

**Comment by mairaw** [comment]
We'd need more information from @yapusito in order to repro his issue. Has he supplied the file name and is still not working? Can he show how he's making the call to the UploadFile method? 
I don't think this is the same as asking to press a key to continue when the keyboard stops working.

**Comment by mairaw** [comment]
@yapusitohe have you supplied the file name and is still not working? Can you show how you're making the call to the UploadFile method?
I don't think this is the same as asking to press a key to continue when the keyboard stops working.

#please-translate

/cc @DavidPrio

**Comment by CeciAc** [comment]
@mairaw translation: 

@yapusitohe, ¿has especificado el nombre de archivo y sigue sin funcionar? ¿Puedes mostrarme cómo haces la llamada al método UploadFile?
No creo que esto sea lo mismo que presionar una tecla para continuar cuando el teclado deja de funcionar.

**Comment by CeciAc** [comment]
Hola, @yapusito

Esta es una continuación de nuestro comentario anterior. Necesitamos más información para poder encargarnos de sus comentarios. ¿Puede proporcionar información más detallada y aclarar el comentario?

Atentamente,
Equipo internacional de Microsoft DOCS

**Comment by CeciAc** [comment]
Hola, @yapusito

Gracias nuevamente por su comentario.

Lamentablemente, aún nos falta información y no podemos procesar sus comentarios. En este momento, cerraremos este problema de GitHub, pero le animamos a enviar más comentarios en el futuro.

Atentamente,
Equipo internacional de Microsoft DOCS

**Comment by DavidPrio** [comment]
Hi @mairaw can this be closed since we are missing required information to proceed? Thanks!

**Comment by mairaw** [comment]
For sure @DavidPrio!
