### ISSUE TITLE
Push multiple package is not supprted

### ISSUE THREAD

**Issue by vlesierse** [dotnet/docs#7146]
It appears that NuGet currently not support pushing multiple packages by using a glob pattern. Don't know if this is a bug or intentional. `dotnet nuget push *.nupkg` should be removed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b363ab07-ea19-574f-e0db-25fd5702255d
* Version Independent ID: 6fa9479a-85db-5498-6b7e-2418fc7bac32
* Content: [dotnet nuget push command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-nuget-push?tabs=netcore21)
* Content Source: [docs/core/tools/dotnet-nuget-push.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-nuget-push.md)
* Product: **dotnet-core**
* GitHub Login: @karann-msft
* Microsoft Alias: **mairaw**

**Comment by JRAlexander** [comment]
@KathleenDollard, any thoughts?

**Comment by KathleenDollard** [comment]
@livarcocc @rrelyea Should this work?

**Comment by livarcocc** [comment]
@vlesierse what error do you get when this happens? On which operating system? And on which version of dotnet?

Also, globbing is not something that the dotnet does by itself, it is actually supported by the underlying shell.

I will let @rrelyea comment on whether or not multiple nupkg publishing is supported or not, independent of globbing.

**Comment by vlesierse** [comment]
@livarcocc It's not an error. It just pushed the first package it finds. All examples only includes one package, so it looks like it's working.

**Comment by jjpepper** [comment]
@vlesierse that doesn't seem right, the doco right here above states:

"Pushes all .nupkg files in the current directory to the default push source:
dotnet nuget push *.nupkg", so it should work.

**Comment by vlesierse** [comment]
@jjpepper Except it doesn't.

~~~sh
ls *.nupkg
XaasKit.AspNetCore.MultiTenancy.1.0.0-preview1-t000.nupkg
XaasKit.AspNetCore.MultiTenancy.Abstractions.1.0.0-preview1-t000.nupkg
~~~

~~~sh
dotnet nuget push *.nupkg -k <key> -s https://www.myget.org/F/xaaskit/api/v2/package
info : Pushing XaasKit.AspNetCore.MultiTenancy.1.0.0-preview1-t000.nupkg to 'https://www.myget.org/F/xaaskit/api/v2/package'...
info :   PUT https://www.myget.org/F/xaaskit/api/v2/package/
info :   Created https://www.myget.org/F/xaaskit/api/v2/package/ 636ms
info : Your package was pushed.
~~~

**Comment by jjpepper** [comment]
Yes, so they need to fix it or fix the doco.

**Comment by screig** [comment]
I see the same issue, we have 8 packages put only one is pushed

![image](https://user-images.githubusercontent.com/4292074/53794106-2f383d00-3f27-11e9-8d33-499d322713ed.png)

**Comment by kellcomnet2** [comment]
same issue on linux

**Comment by iberodev** [comment]
Any update on this?
I've just verified that dotnet nuget is unable to push multiple packages at the same time and I can see that the documentation has not been updated yet despite being wrong.

I've just tested it with the dotnet core 2.2 docker image: `mcr.microsoft.com/dotnet/core/sdk:2.2`

the command 
`dotnet nuget push */**/*.nupkg -s http://iberodev-repository/repository/mirepo/ `

only pushes the first nupkg it finds.

Any workaround?

**Comment by WhiteEagle5150** [comment]
@iberodev,

Your solution worked for me. Thank you.

My environment: 
gitlab-runner 11.9.1 / linux/Ubuntu 14.04
dotnet-sdk:2.1.302-v2.6

````dotnet nuget push $OUTPUT_DIR/**/*.nupkg ...````

**Comment by mairaw** [comment]
Thanks for providing the fix @iberodev. I've opened PR #13174 to update the commands for Preview 6 and included this fix as part of it. @karann-msft please verify.

**Comment by karann-msft** [comment]
I just tried this and it works for me....
```
C:\Users\karann\source\repos\ClassLibrary1\ClassLibrary1\bin\Debug>dotnet --version
3.0.100-preview5-011568
C:\Users\karann\source\repos\ClassLibrary1\ClassLibrary1\bin\Debug>dotnet nuget push *.nupkg -s https://apidev.nugettest.org/v3/index.json -k ~redacted~
info : Pushing KaranClassLibrary01.1.0.0.nupkg to 'https://dev.nugettest.org/api/v2/package'...
info :   PUT https://dev.nugettest.org/api/v2/package/
info :   Created https://dev.nugettest.org/api/v2/package/ 23394ms
info : Your package was pushed.
info : Pushing KaranClassLibrary02.1.0.0.nupkg to 'https://dev.nugettest.org/api/v2/package'...
info :   PUT https://dev.nugettest.org/api/v2/package/
info :   Created https://dev.nugettest.org/api/v2/package/ 430ms
info : Your package was pushed.
error: File does not exist (*.snupkg).
```

yes, there is an error at the end but that's a different issue. Both packages did get pushed.
https://dev.nugettest.org/packages/karanclasslibrary01
https://dev.nugettest.org/packages/karanclasslibrary02

**Comment by WhiteEagle5150** [comment]
@karann-msft,

You're using a preview version of 3.0, most current users have build environments using SDK buildpacks of either 2.1 or 2.2. For many, like myself, 3.0 preview isn't even an option yet.

**Comment by karann-msft** [comment]
@WhiteEagle5150 same result with dotnet 2.2.300

```
C:\Users\karann\source\repos\ClassLibrary1\ClassLibrary1\bin\Debug>dotnet --version
2.2.300
Successfully installed the ASP.NET Core HTTPS Development Certificate.
To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only). For establishing trust on other platforms refer to the platform specific documentation.
For more information on configuring HTTPS see https://go.microsoft.com/fwlink/?linkid=848054.
info : Pushing KaranClassLibrary01.1.0.1.nupkg to 'https://dev.nugettest.org/api/v2/package'...
info :   PUT https://dev.nugettest.org/api/v2/package/
info :   Created https://dev.nugettest.org/api/v2/package/ 1087ms
info : Your package was pushed.
info : Pushing KaranClassLibrary02.1.0.1.nupkg to 'https://dev.nugettest.org/api/v2/package'...
info :   PUT https://dev.nugettest.org/api/v2/package/
info :   Created https://dev.nugettest.org/api/v2/package/ 362ms
info : Your package was pushed.
error: File does not exist (*.snupkg).
```

**Comment by WhiteEagle5150** [comment]
@karann-msft 

Are you using Windows or Linux? I have to perform my builds from an Ubuntu container, using dotnet-sdk:2.1.302 build pack.

**Comment by karann-msft** [comment]
@WhiteEagle5150 do you mind trying 2.2.300 on whatever environment you are on.

**Comment by WhiteEagle5150** [comment]
@karann-msft,

Unfortunately, that isn't an option for me. Our GitLabs policies are pretty strict right now, but i anticipate they will loosen up a little over time. That 2.1 Sdk is all I can use right now. Part of this has to do with our hosting environment, right now, it is only supporting the 2.1 build packs for our docker containers.

**Comment by karann-msft** [comment]
@mairaw this seems to be a bug in older versions of the sdk. newer versions work fine.

**Comment by mairaw** [comment]
Thanks for checking @karann-msft. So, perhaps we should add a note about the bug in older versions of the SDK in the doc?

**Comment by AlexEngblom** [comment]
I seem to get this issue with latest range of dotnet tools when running my new [Github Actions CI](https://github.com/AlexEngblom/EfCoreJsonValueConverter/blob/master/.github/workflows/dotnetcore.yml) running on 'ubuntu-latest'.

From the workflow output:
`
Run dotnet --version
3.1.101

Run ls
...
Innofactor.EfCoreJsonValueConverter.2.0.1-beta0011.nupkg
Innofactor.EfCoreJsonValueConverter.Attributes.2.0.1-beta0011.nupkg
...

Run dotnet nuget push *.nupkg --api-key *** --source https://apiint.nugettest.org/v3/index.json --no-symbols true
info : Pushing Innofactor.EfCoreJsonValueConverter.2.0.1-beta0011.nupkg to 'https://int.nugettest.org/api/v2/package'...
info :   PUT https://int.nugettest.org/api/v2/package/
warn : The <licenseUrl> element is deprecated. Consider using the <license> element instead. Learn more: https://aka.ms/deprecateLicenseUrl.,The <iconUrl> element is deprecated. Consider using the <icon> element instead. https://aka.ms/deprecateIconUrl
info :   Created https://int.nugettest.org/api/v2/package/ 401ms
info : Your package was pushed.
`

**Comment by colbylwilliams** [comment]
For people who are still having this issue, I was able to resolve by wrapping in quotes:
```
dotnet nuget push '*.nupkg' ...
```

**Comment by rrelyea** [comment]
FYI @donnie-msft @aortiz-msft

**Comment by heng-liu** [comment]
Tried on Linux for multiple versions of  dotnet:
 2.1.302
```
henli@henli001UbuntuRepro:~/packages$ dotnet --version
2.1.302
henli@henli001UbuntuRepro:~/packages$ dotnet nuget push --source ~/source/ *.nupkg
info : Pushing project1.1.0.0.nupkg to '/home/henli/source/'...
info : Your package was pushed.
henli@henli001UbuntuRepro:~/packages$ dotnet nuget push --source ~/source/ '*.nupkg'
info : Pushing project1.1.0.0.nupkg to '/home/henli/source/'...
info : Your package was pushed.
info : Pushing project2.1.0.0.nupkg to '/home/henli/source/'...
info : Your package was pushed.
```
2.2.300
```
henli@henli001UbuntuRepro:~/packages$ dotnet --version
2.2.300
henli@henli001UbuntuRepro:~/packages$ dotnet nuget push --source ~/source/ *.nupkg
info : Pushing project1.1.0.0.nupkg to '/home/henli/source/'...
info : Your package was pushed.
henli@henli001UbuntuRepro:~/packages$ dotnet nuget push --source ~/source/ '*.nupkg'
info : Pushing project1.1.0.0.nupkg to '/home/henli/source/'...
info : Your package was pushed.
info : Pushing project2.1.0.0.nupkg to '/home/henli/source/'...
info : Your package was pushed.
```
3.1.201
```
henli@henli001UbuntuRepro:~$ dotnet --version
3.1.201
henli@henli001UbuntuRepro:~/packages$ dotnet nuget push --source ~/source/ *.nupkg
Pushing project1.1.0.0.nupkg to '/home/henli/source/'...
Your package was pushed.
henli@henli001UbuntuRepro:~/packages$ dotnet nuget push --source ~/source/ '*.nupkg'
Pushing project1.1.0.0.nupkg to '/home/henli/source/'...
Your package was pushed.
Pushing project2.1.0.0.nupkg to '/home/henli/source/'...
Your package was pushed.
```
Without quotes, only the first package is pushed.
With quotes, all packages are pushed.

**Comment by donnie-msft** [comment]
For clarity, Windows still works as expected in dotnet **3.1.300-preview-015048**.

Both push all expected packages (not just 1):
`dotnet nuget push *\**\*.nupkg --source "nugettest" --skip-duplicate`
`dotnet nuget push *\*\*\*.nupkg --source "nugettest" --skip-duplicate`

**Comment by zivkan** [comment]
Heng's comment shows it best. When using `'*.nupkg'`, it tells the shell not to expand the wildcard, so the `*` character is really passed to NuGet (via dotnet), and NuGet does its own globbing. Windows cmd.exe doesn't support globbing (not sure about powershell, my guess is no), which is why the single quotes are not needed around the `*.nupkg`. On Linux, every shell I've ever used supports globbing, so that individual apps don't need to.

Fundamentally, the issue is that `dotnet nuget push package1.nupkg package2.nupkg` doesn't work. That's what dotnet/NuGet sees on Linux (or other shells), where the shell supports globbing and expands it before passing the arguments to the process.

I think it's not Windows vs Linux, it's all about whether the shell expands globs, and NuGet appears to only support only a single argument.

**Comment by heng-liu** [comment]
Since the issue still exists, please reopen this issue. Thanks!

**Comment by heng-liu** [comment]
After discussion, we would like to keep it closed. Sorry for the confusion caused!
