### ISSUE TITLE
Anomaly Detection and Recommendation

### ISSUE THREAD

**Issue by astmehalthakor** [dotnet/docs#7150]
As I understand, PcaAnomaly detector is available in ML.Net 0.4. Can you please suggest when the Recommendation is planned to be a part of ML.Net? Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd15175c-5b7d-4310-ecf5-32ffc7bc588b
* Version Independent ID: 38adc676-934e-0ff9-c868-527f075c96df
* Content: [Machine learning tasks](https://docs.microsoft.com/en-us/dotnet/machine-learning/resources/tasks)
* Content Source: [docs/machine-learning/resources/tasks.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/resources/tasks.md)
* Product: **dotnet-ml**
* GitHub Login: @aditidugar
* Microsoft Alias: **johalex**

**Comment by JRAlexander** [comment]
@astmehalthakor, You can do recommendations using [FieldAwareFactorizationMachineBinaryClassifier](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.trainers.fieldawarefactorizationmachinebinaryclassifier?view=ml-dotnet). There should be a new movie recommendation sample using this at https://github.com/dotnet/machinelearning-samples soon. You can see it in action [here](https://channel9.msdn.com/Events/dotnetConf/2018/S201) - starting at about 21:59.

**Comment by JRAlexander** [comment]
Closing this as I believe its resolved. Please reopen if that is not the case. Thanks!
