### ISSUE TITLE
Bilisecond (long-lasting bug in documentation)

### ISSUE THREAD

**Issue by MikeRosoft** [dotnet/docs#7155]
There is no such thing as a bilisecond., and the 'bilisecond' parameter actually represents a number of microseconds (millionth of a second). A billionth of a second would be a nanosecond.

The statement new System.Data.SqlTypes.SqlDateTime(2018,1,1,10,0,0,500000) returns a value with 500 milliseconds.
The statement new System.Data.SqlTypes.SqlDateTime(2018,1,1,10,0,0,2000000) throws a SqlTypeException.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bdab136-172a-2c50-1dbe-ce41e7be24b5
* Version Independent ID: 3aed9a19-901d-120a-43d0-fad0f02b1039
* Content: [SqlDateTime Constructor (System.Data.SqlTypes)](https://docs.microsoft.com/en-us/dotnet/api/system.data.sqltypes.sqldatetime.-ctor?view=netframework-4.7.2#System_Data_SqlTypes_SqlDateTime__ctor_System_Int32_System_Int32_System_Int32_System_Int32_System_Int32_System_Int32_System_Int32_)
* Content Source: [xml/System.Data.SqlTypes/SqlDateTime.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Data.SqlTypes/SqlDateTime.xml)
* Product: **dotnet-api**
* GitHub Login: @douglaslMS
* Microsoft Alias: **douglasl**

**Comment by douglaslMS** [comment]
@MikeRosoft You're right that "nanosecond" would be correct here. However these API reference docs are autogenerated from code comments, and the code itself uses the unfortunate "bilisecond." If I update the doc page manually, it's only a matter of weeks before my fix is overwritten by an autogenerated sync to the code. In other words, fixing this would require a code bug, which (frankly) would probably be prioritized very low in this older .NET code.

**Comment by svick** [comment]
@douglaslMS 

> You're right that "nanosecond" would be correct here.

No, "microsecond" would be correct. And I think the documentation should use that name to describe the value here.

Another way to verify that is to look at [the source code](https://referencesource.microsoft.com/#System.Data/System/Data/SQLTypes/SQLDateTime.cs,9d88dbb7fc25c26f): the `bilisecond` value is divided by 1000 and the result is passed to the `double millisecond` parameter of the other constructor overload. This means the `bilisecond` value represents thousandths of millisecond, or in other words, microseconds.

> However these API reference docs are autogenerated from code comments, and the code itself uses the unfortunate "bilisecond."

Yes, the parameter name shouldn't be changed. If it was changed in the source, that would be a [breaking change](https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/breaking-change-rules.md#signatures).

**Comment by mairaw** [comment]
You can update the non-automated parts @douglaslMS. The .NET reference is not auto-generated from /// comments. Just the skeleton of the page is auto-generated.

**Comment by pkulikov** [comment]
@douglaslMS while the signature cannot be changed, the description of both the constructor and the argument can be updated to use the word "microsecond" (as @mairaw has just mentioned).

**Comment by douglaslMS** [comment]
@svick @pkulikov Thank you for explaining what's in the source code. I have made the suggested corrections.
