### ISSUE TITLE
No detection instructions for 4.6.1

### ISSUE THREAD

**Issue by breyed** [dotnet/docs#7156]
There are no instructions for detecting if version 4.6.1 is installed. In general, the columns look misaligned for that version.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81fe5242-e3b2-6cfe-5308-63fc96272657
* Version Independent ID: 1abaaeb7-d7ed-5522-c16f-409f22a074cc
* Content: [.NET Framework Versions and Dependencies](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/versions-and-dependencies)
* Content Source: [docs/framework/migration-guide/versions-and-dependencies.md](https://github.com/dotnet/docs/blob/master/docs/framework/migration-guide/versions-and-dependencies.md)
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by rpetrusha** [comment]
Thank you so much for reporting this, @breyed. I've opened PR #7163 to remove an extraneous blank column that caused the version detection information to not display.
