### ISSUE TITLE
What about the accessibility rules when inside a namespace instead of a module?

### ISSUE THREAD

**Issue by teo-tsirpanis** [dotnet/docs#7159]
This file seems to raise no errors for example:

``` fsharp
namespace Foo

type MyPreciousSecret = private MyPreciousSecret of string

module Foo =
    let getMPS (MyPreciousSecret mps) = mps
```

But is it a bug or not? The type `MyPreciousSecret` is not inside the `Foo` module. In C# for example, this code would break encapsulatin rules.

The docs say that each file is implicitly a module. Does that hold even when it declares a _namespace_?

Shouldn't the docs be updated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b203042-7c41-709b-7db1-2157b1ba6d45
* Version Independent ID: caa4ea7d-d490-f66f-0a0c-b8f62e883f1b
* Content: [Access Control (F#)](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/access-control)
* Content Source: [docs/fsharp/language-reference/access-control.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/language-reference/access-control.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by JRAlexander** [comment]
@cartermp, any thoughts?

**Comment by cartermp** [comment]
This code is (roughly) equivalent to:

```csharp
namespace Foo
{
    public sealed class MyPreciousSecret
    {
        internal readonly string item;

        private static MyPreciousSecret NewMyPreciousSecret(string item)
        {
            return new MyPreciousSecret(item);
        }

        internal MyPreciousSecret(string item)
        {
            this.item = item;
        }
    }
    public static class Foo
    {
        public static string getMPS(MyPreciousSecret _arg1)
        {
            return _arg1.item;
        }
    }
}
```

Which is fine, because the DU itself is public. If you change this to:

```fsharp
namespace Foo

type private MyPreciousSecret = private MyPreciousSecret of string

module Foo =
    let getMPS (MyPreciousSecret mps) = mps
```

You will get an error:

`The type 'MyPreciousSecret' is less accessible than the value, member or type 'val getMPS : MyPreciousSecret -> string' it is used in.`

This line in the docs:

> Individual cases in a discriminated union cannot have their own access control modifiers separate from the union type.

Is a bit misleading, since you can do that, but it doesn't make the individual case less accessible than the DU itself. Same goes for records, so the doc should still be updated.

Does that make sense?

**Comment by cartermp** [comment]
#7221
