### ISSUE TITLE
Implementing the dispose pattern for a base class

### ISSUE THREAD

**Issue by abmadmin1** [dotnet/docs#7162]
The documentation says you should call the base Dispose method with true for the disposing parameter but the example shows passing the disposing parameter. In this situation, the base class doesn't free up managed resources and depending on your situation, the derived class could get an error if a base resource is still in use.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 572ef6c6-5066-4a14-76a0-c3fb4b62e604
* Version Independent ID: 9c754da1-c234-fb12-580b-0fcf9ffe2c20
* Content: [Implementing a Dispose method](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-dispose#implementing-the-dispose-pattern-for-a-derived-class)
* Content Source: [docs/standard/garbage-collection/implementing-dispose.md](https://github.com/dotnet/docs/blob/master/docs/standard/garbage-collection/implementing-dispose.md)
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by BillWagner** [comment]
This article has been updated to address both concerns:
- The text no longer says to pass `true`, but says to set the arg based on calling from a Dispose method or a finalize method.
- The sample frees derived resource and sets the `disposed` flag before calling the base class method. That means the derived class should not be using an base class resources.

I'll close this.
