### ISSUE TITLE
If whoever adds a method to my event makes it async, how can my parent method await?

### ISSUE THREAD

**Issue by michael-hawker** [dotnet/docs#7170]
It'd be great to see a code sample for this async eventing paradigm.  Currently, if you just use the event and call it with the new EventName?.Invoke(this, args) paradigm, it'll blow through it if you make your method async...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f782a9c5-2dc8-d8d1-b17d-246ab8524863
* Version Independent ID: f6f825c5-c64b-d13b-1c7e-a01bfb93093d
* Content: [event (C# Reference)](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/event)
* Content Source: [docs/csharp/language-reference/keywords/event.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/event.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@michael-hawker Thanks for pointing this out. I've added it to our backlog and our async project.

Async events require some special handling because event handlers return void. The event handler is a void returning async method, and the event handlers are "fire and forget" methods. [This document](https://docs.microsoft.com/dotnet/standard/asynchronous-programming-patterns/implementing-the-event-based-asynchronous-pattern) is close to what you need, but not exactly the same.

**Comment by michael-hawker** [comment]
@pkulikov thanks for the link.  In contrast to the example there, I want to know how I could change the line in the NaiveButton Click method `Clicked?.Invoke(this, EventArgs.Empty);` to wait until the async handlers have completed.

E.g. I want to know how to rewrite my invoke method such that my output would look like this:
```
// Expected output:
// About to click a button...
// Somebody has clicked a button. Let's raise the event...
//    Handler 1 is starting...
//    Handler 1 is done.
//    Handler 2 is starting...
//    Handler 2 is about to go async...
//    Handler 3 is starting...
//    Handler 3 is done.

//    Handler 2 is done.        <--- how to achieve this?

// All listeners are notified.
// Button's Click method returned.
```

I'm ok with making the `Click` method in NaiveButton, i.e. `public async void ClickAsync()`, but it's not clear how to implement this pattern (if possible).  Would I have to do some threading magic with `BeginInvoke` for instance instead?

**Comment by pkulikov** [comment]
@michael-hawker I don't know how to implement such a pattern or if it's possible to do (most probably, it's possible with some code dances). 

The sad thing about `Clicked?.Invoke(this, EventArgs.Empty);` is that we don't know what subscriptions look like. Imagine we can handle async event handlers, but then what to do with such "synchronous" event handler:
```csharp
private void On_Clicked(object sender, EventArgs args)
{
    // Code to do some sync job...
    // ... and then
   Task.Run(() => { /* ... cheat on another thread ... */ });
}
```
