### ISSUE TITLE
H1 title overlap with in-page navigation column

### ISSUE THREAD

**Issue by zhiliangxu** [dotnet/docs#7175]
https://docs.microsoft.com/en-us/dotnet/api/system.func-17?view=netframework-4.7.2
Title is long: Func&lt;T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16,TResult&gt;
It overlaps with "in this article"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d95cd525-746d-313d-b7f9-4d442d2319df
* Version Independent ID: 930861a9-778b-7428-f582-58043958e890
* Content: [Func&lt;T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16,TResult&gt; Delegate (System)](https://docs.microsoft.com/en-us/dotnet/api/system.func-17?view=netframework-4.7.2)
* Content Source: [xml/System/Func`17.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System/Func`17.xml)
* Product: **dotnet-api**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by zhiliangxu** [comment]
![image](https://user-images.githubusercontent.com/2852646/44438080-1f42b680-a5f0-11e8-84aa-4a8eaa3cb3ce.png)

**Comment by mairaw** [comment]
Thanks @zhiliangxu for reporting this issue. Given this is a problem with the docs platform, I've moved this to https://github.com/MicrosoftDocs/feedback/issues/622.
