### ISSUE TITLE
What RFC does it conform to?

### ISSUE THREAD

**Issue by angularsen** [dotnet/docs#7184]
If I understand correctly, there are multiple RFC's defining what is a valid email address and parts of the address such as domain names. Comparing MailAddress to various online validators give different results and I don't know which are correct.

https://en.wikipedia.org/wiki/Email_address#Syntax
https://tools.ietf.org/html/rfc5322

For instance, these addresses should be invalid but are valid by MailAddress:
1234567890123456789012345678901234567890123456789012345678901234+x@example.com
Jane Doe &lt;foo@baz.com&gt;

These are valid, but not valid by MailAddress:
foo.bar."bux".bar.com@baz.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 202e3f9f-a12a-53de-9069-fd469e3dbebc
* Version Independent ID: fd3699bb-4881-b6b4-1275-43eed3d5f626
* Content: [How to: Verify that Strings Are in Valid Email Format](https://docs.microsoft.com/en-us/dotnet/standard/base-types/how-to-verify-that-strings-are-in-valid-email-format)
* Content Source: [docs/standard/base-types/how-to-verify-that-strings-are-in-valid-email-format.md](https://github.com/dotnet/docs/blob/master/docs/standard/base-types/how-to-verify-that-strings-are-in-valid-email-format.md)
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by Thraka** [comment]
I don't know that this conforms to any specific RFC. I feel like the original author would have put that in a comment somewhere. 

There is an open discussion on what to do with this article over at #9547
