### ISSUE TITLE
Delegates and generic types

### ISSUE THREAD

**Issue by jnad72** [dotnet/docs#7187]
If I have a delegate sub like this:

```vVB
Public Delegate Sub ExecuteBusinessServiceDelegate(Of TRequest As {BsRequest, New}, TResponse As {BsResponse, New})(pBusinessService As BusinessService(Of TRequest, TResponse), pExecutionContext As BsExecutionContext)
```

How to do the declaration using this delegate?

```vb
Private myExecuteBusinessServiceDelegate As ExecuteBusinessServiceDelegate(……
```

Edit by @billwagner to add code formatting.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1388f63d-1c05-2eb6-e505-67140b165d0c
* Version Independent ID: 41ccef34-e68c-dba3-2129-9ed720197257
* Content: [Anonymous Functions (C# Programming Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/statements-expressions-operators/anonymous-functions)
* Content Source: [docs/csharp/programming-guide/statements-expressions-operators/anonymous-functions.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/statements-expressions-operators/anonymous-functions.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by svick** [comment]
@jnad72 

What kind of declaration do you want to make? If you want a field, then it could be something like:

```vbnet
Private myExecuteBusinessServiceDelegate As ExecuteBusinessServiceDelegate(Of MyBsRequest, MyBsResponse)
```

Also, I'm not sure why are you looking for information about VB syntax in the C# Guide and not in [the VB Guide](https://docs.microsoft.com/en-us/dotnet/visual-basic/).

**Comment by BillWagner** [comment]
@jnad72 

Did the above comment answer your question? Can you tell me if the Visual Basic article on [Delegates](https://docs.microsoft.com/dotnet/visual-basic/programming-guide/language-features/delegates/index) helps? If so, I'll close this issue.

**Comment by jnad72** [comment]
Yes it did. You can close this issue. Thanks

**Comment by BillWagner** [comment]
Thanks. Closing as resolved.
