### ISSUE TITLE
canonical modulus

### ISSUE THREAD

**Issue by johnnyagerard** [dotnet/docs#7190]
"However, the behavior is the same for positive dividends."
 What behavior?
Can someone clarify?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 227f6a03-7076-a47a-24de-a2c3c31a90b5
* Version Independent ID: 8538cb70-a092-1166-1cd9-b77f5e6a80d4
* Content: [% Operator (C# Reference)](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/remainder-operator)
* Content Source: [docs/csharp/language-reference/operators/remainder-operator.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/operators/remainder-operator.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by rpetrusha** [comment]
What it intends to say, @johnnyagerard, is that the remainder operation produces the same result as the modulus operation for positive dividends, but a different result for negative dividends.

**Comment by johnnyagerard** [comment]
@rpetrusha @pkulikov Ok, thanks.

**Comment by rpetrusha** [comment]
I think at a minimum that we eliminate the ambiguity of "the behavior is the same for positive dividends". I'll assign this to myself for a future sprint. If either of you would like to do it in the meantime, @pkulikov and @johnnyagerard, please go ahead.

**Comment by pkulikov** [comment]
@rpetrusha I would like to update the article next week, if @johnnyagerard is fine with that.

**Comment by rpetrusha** [comment]
Thanks, @pkulikov. I've assigned the issue to you.
