### ISSUE TITLE
Introduction to Containers and dockers

### ISSUE THREAD

**Issue by rajancrp** [dotnet/docs#7193]
Good explanation for newbies 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ba2da58-10b2-ac3d-83ea-df35ebe776dc
* Version Independent ID: 19de8e78-b0be-988e-fdff-22ed585297c8
* Content: [Introduction to Containers and Docker](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/container-docker-introduction/index)
* Content Source: [docs/standard/microservices-architecture/container-docker-introduction/index.md](https://github.com/dotnet/docs/blob/master/docs/standard/microservices-architecture/container-docker-introduction/index.md)
* Product: **dotnet**
* GitHub Login: @CESARDELATORRE
* Microsoft Alias: **wiwagn**

**Comment by JRAlexander** [comment]
Thanks for the feedback, @rajancrp!
