### ISSUE TITLE
Broken link to Union File System

### ISSUE THREAD

**Issue by NinjaCross** [dotnet/docs#7195]
The given link to Union File System is broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f05fc76-7ca5-424d-63b5-f22e389e370b
* Version Independent ID: df2c93e2-a21f-455c-0f32-2ae15aa3df60
* Content: [State and data in Docker applications](https://docs.microsoft.com/en-us/dotnet/standard/containerized-lifecycle-architecture/design-develop-containerized-apps/state-and-data-in-docker-applications)
* Content Source: [docs/standard/containerized-lifecycle-architecture/design-develop-containerized-apps/state-and-data-in-docker-applications.md](https://github.com/dotnet/docs/blob/master/docs/standard/containerized-lifecycle-architecture/design-develop-containerized-apps/state-and-data-in-docker-applications.md)
* Product: **dotnet**
* GitHub Login: @CESARDELATORRE
* Microsoft Alias: **wiwagn**

**Comment by JRAlexander** [comment]
Thanks for your feedback, @NinjaCross. I've created a PR with the correct link. After it gets reviewed and approved, I'll merge and the changes will show up within a few days.
