### ISSUE TITLE
TargetedPatchingOptOut attributes are irrelevant for the documentation

### ISSUE THREAD

**Issue by jkotas** [dotnet/docs#7203]
The documentation should not include TargetedPatchingOptOut attributes on API signatures. These attributes were internal implementation plumbing for .NET Framework. They do not exist in .NET Core at all.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb7b63ce-50ba-fdb1-a002-58e127ecf4e1
* Version Independent ID: 38a2e573-13d6-f730-a8d5-93b711b1715b
* Content: [UriBuilder.Path Property (System)](https://docs.microsoft.com/en-us/dotnet/api/system.uribuilder.path?view=netcore-2.1#feedback)
* Content Source: [xml/System/UriBuilder.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System/UriBuilder.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks @jkotas. We have a PR already trying to remove that: https://github.com/dotnet/dotnet-api-docs/pull/439

**Comment by mairaw** [comment]
Also, showing the right attributes for the different implementations is on the pipeline of the engineering team. That will happen in a few months.
