### ISSUE TITLE
Update NUnit .NET Core get started

### ISSUE THREAD

**Issue by kendrahavens** [dotnet/docs#7204]
# NUnit template is now in dotnet CLI

Update https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-with-nunit#install-the-nunit-project-template

# General

Adding the package ```dotnet new -i NUnit3.DotNetNew.Template``` is no longer required since the template is pre-installed.

## Issues with Existing Topics

- Will probably need the screen shot discussed in https://github.com/dotnet/docs/issues/5293 updated anyway.

### Suggest reviewers

@mairaw

**Comment by mairaw** [comment]
Thanks @kendrahavens. We're adding this to our backlog of .NET Core items. If you'd like to submit a PR, we'll gladly review it.

**Comment by kendrahavens** [comment]
The PR is out https://github.com/dotnet/docs/pull/7318

There was much less to change than I thought there might be since the original topic doesn't actually use any of the NUnit template.

**Comment by mairaw** [comment]
You rock @kendrahavens! I'll get to it ASAP.

**Comment by kendrahavens** [comment]
Fixed in https://github.com/dotnet/docs/pull/7318

**Comment by kendrahavens** [comment]
F# and Visual Basic docs to follow.
