### ISSUE TITLE
This is great!

### ISSUE THREAD

**Issue by AluminumChassis** [dotnet/docs#7210]
One typo I found : you misspelled "ctrl" at the end of the paragraph.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b706537-d756-dae3-1e3f-979e840f8eaf
* Version Independent ID: db32bdba-1019-db26-dc4d-3dceb4bb3f34
* Content: [How to: Determine Which Modifier Key Was Pressed](https://docs.microsoft.com/en-us/dotnet/framework/winforms/how-to-determine-which-modifier-key-was-pressed)
* Content Source: [docs/framework/winforms/how-to-determine-which-modifier-key-was-pressed.md](https://github.com/dotnet/docs/blob/master/docs/framework/winforms/how-to-determine-which-modifier-key-was-pressed.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by JRAlexander** [comment]
Thanks for your feedback, @AluminumChassis! Good catch!  We can make the change or would you like to make the change and submit a PR?
