### ISSUE TITLE
What Regex expresion does this Attribute use?

### ISSUE THREAD

**Issue by Dc9894** [dotnet/docs#7213]
Hi,

Should a Regex appear here in order to see how does this attribute actually validate a phone number? If not where could I find how does this attributes actually validate a field?

Thanks for the help!

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 15724c53-7b55-e20f-f1e5-62c51cb57dfe
* Version Independent ID: 6155a1c3-8b3e-aa24-3d6b-a0804d6fc9dd
* Content: [PhoneAttribute Class (System.ComponentModel.DataAnnotations)](https://docs.microsoft.com/es-es/dotnet/api/system.componentmodel.dataannotations.phoneattribute?view=netcore-2.1#feedback)
* Content Source: [xml/System.ComponentModel.DataAnnotations/PhoneAttribute.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.ComponentModel.DataAnnotations/PhoneAttribute.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **riande**

**Comment by mairaw** [comment]
I'd consider this an implementation detail. But you can see the source at https://referencesource.microsoft.com/#System.ComponentModel.DataAnnotations/DataAnnotations/PhoneAttribute.cs.
