### ISSUE TITLE
Additional Instructions

### ISSUE THREAD

**Issue by UmarAlFarooq** [dotnet/docs#7218]
You'd do well to explain the use of \n escape characters as well as the use of $ sign in your documentation. This is an article for beginners.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b80f18fa-e6d2-50f6-dc08-a2ab5ba9f89a
* Version Independent ID: 5bebc66b-956a-47c7-7472-07967256be0c
* Content: [Building a Hello World application with .NET Core and C# in Visual Studio 2017](https://docs.microsoft.com/en-us/dotnet/core/tutorials/with-visual-studio#enhancing-the-hello-world-application)
* Content Source: [docs/core/tutorials/with-visual-studio.md](https://github.com/dotnet/docs/blob/master/docs/core/tutorials/with-visual-studio.md)
* Product: **dotnet-core**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by JRAlexander** [comment]
Thanks for your feedback, @UmarAlFarooq. This has been added to the backlog.

**Comment by don1941** [comment]
https://stackoverflow.com/questions/39155571/how-to-run-net-core-console-app-from-the-command-line Describes a critical step that should be included here.  Ways to run the console app from the command line should be included in this article or there should be a link to a page that has info like the SO article.

**Comment by MuhammadKaleemUllah** [comment]
{date:d} and {time:t} are little bit confusing. Beginner

**Comment by MuhammadKaleemUllah** [comment]
We can use date only to show date and time
or 
date:d & time:t to tell that the time and date was this ;)
