### ISSUE TITLE
Does this method get called in X509Store Dispose()?

### ISSUE THREAD

**Issue by kp101090** [dotnet/docs#7226]
As per remark here (https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.x509certificates.x509store?redirectedfrom=MSDN&view=netframework-4.7.2#remarks): Starting with the .NET Framework 4.6, this type implements the IDisposable interface. When you have finished using the type, you should dispose of it either directly or indirectly

Are we required to call this method if we are using "using" construct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8ec13f1-ff5a-35c4-78a7-70b737aa1caa
* Version Independent ID: f073fbd8-92ff-adde-6077-e70a8ecf62b9
* Content: [X509Store.Close Method (System.Security.Cryptography.X509Certificates)](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.x509certificates.x509store.close?view=netframework-4.7.2#feedback)
* Content Source: [xml/System.Security.Cryptography.X509Certificates/X509Store.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Security.Cryptography.X509Certificates/X509Store.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
No, you don't have to call it directly if you're using a `using` statement, @kp101090. The `using` statement wraps a call to IDisposable.Dispose.
