### ISSUE TITLE
cookieless

### ISSUE THREAD

**Issue by jo0ls** [dotnet/docs#7230]
What are the correct values for cookieless in 2018?
True/False  or
UseCookes, UseUri, UseDeviceProfile and AutoDetect. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7b70865-7f42-aceb-6554-5bbbbdf8d9ca
* Version Independent ID: a9422e8c-d713-59b8-ddb6-bd3f90cad9f1
* Content: [HttpSessionState.IsCookieless Property (System.Web.SessionState)](https://docs.microsoft.com/en-us/dotnet/api/system.web.sessionstate.httpsessionstate.iscookieless?view=netframework-4.7.2)
* Content Source: [xml/System.Web.SessionState/HttpSessionState.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Web.SessionState/HttpSessionState.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by JRAlexander** [comment]
@jo0ls, IsCookieless returns a boolean. true if the session is embedded in the URL; otherwise, false.
