### ISSUE TITLE
NO-BREAK SPACE (U+00A0) is in the "Space Separator Category"

### ISSUE THREAD

**Issue by NoelWidmer** [dotnet/docs#7231]
The NO-BREAK SPACE character does not appear in the list of characters with special treatment as correctly described in IsWhiteSpace(String, Int32) and IsWhiteSpace(Char). But in the "Remarks" section it is listed as a special character even if it is already included in the Space Seperator category as defined by Unicode. This is redundant information which should be removed becasue it can cause confusion.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb23715b-882f-fdbd-42c3-ebd9b910b8c9
* Version Independent ID: 657d7117-3ed1-a4f9-5b38-9beddfe5940e
* Content: [Char.IsWhiteSpace Method (System)](https://docs.microsoft.com/en-us/dotnet/api/system.char.iswhitespace?view=netframework-4.7.2)
* Content Source: [xml/System/Char.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System/Char.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
I agree; it is confusing, @NoelWidmer. Thanks for reporting this issue. I've address it in dotnet/dotnet-api-docs#461.
