### ISSUE TITLE
Properly summed up contents

### ISSUE THREAD

**Issue by cppxaxa** [dotnet/docs#7234]
Nice format for exposing the information about the feature

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcc06ead-fe51-85db-1340-87f6473db769
* Version Independent ID: 4f2c312e-609c-a643-4af6-c12c6cf74738
* Content: [Indexers](https://docs.microsoft.com/en-us/dotnet/csharp/indexers)
* Content Source: [docs/csharp/indexers.md](https://github.com/dotnet/docs/blob/master/docs/csharp/indexers.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by rpetrusha** [comment]
Thank you for letting us know that you found the article helpful, @cppxaxa!
