### ISSUE TITLE
Typo in Remarks section

### ISSUE THREAD

**Issue by johnye2e** [dotnet/docs#7235]
"Use the XmlMapping class instead of deriving a class directly from XmlMapping."

Maybe you wanted to write "Use the XmlTypeMapping class instead..."?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b0c295b-6527-b0f2-3abb-179a7f2431c4
* Version Independent ID: 25408c54-c557-eccc-0505-b4bbb21fd4ff
* Content: [XmlMapping Class (System.Xml.Serialization)](https://docs.microsoft.com/en-us/dotnet/api/system.xml.serialization.xmlmapping?view=netframework-4.7.2)
* Content Source: [xml/System.Xml.Serialization/XmlMapping.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Xml.Serialization/XmlMapping.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
I suspect that it actually intended to say "Use the XmlTypeMapping and XmlMemberMapping classes instead...", @johnye2e. It's also not true that it exposes no public or protected members.

**Comment by rpetrusha** [comment]
I've opened dotnet/dotnet-api-docs#465 to address this issue. Thanks for pointing it out, @johnye2e.
