### ISSUE TITLE
grouping of trainers based on type

### ISSUE THREAD

**Issue by Askjensen** [dotnet/docs#7237]
Hi, it would be very helpful to have trainers grouped  by their type, e.g. regressor, clustering, classification(binary or multilabel) etc. Is this in the pipeline or is there a specific reason for having them all under ml.trainers? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a058f7f4-11de-762a-166e-2ac0ecdb6280
* Version Independent ID: cde5ff68-186b-fd03-eb25-2898fb8e76c9
* Content: [Microsoft.ML.Trainers Namespace](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.trainers?view=ml-dotnet#feedback)
* Content Source: [dotnet/xml/ns-Microsoft.ML.Trainers.xml](https://github.com/dotnet/ml-api-docs/blob/live/dotnet/xml/ns-Microsoft.ML.Trainers.xml)
* GitHub Login: @dotnet-bot

**Comment by pkulikov** [comment]
@Askjensen I think it's work in progress and will be covered in the docs when #5698 is finished.

**Comment by Askjensen** [comment]
Alright, thx for the reply

**Comment by JRAlexander** [comment]
Yup, its still in progress. Hope to finish soon.

**Comment by JRAlexander** [comment]
Thanks for the question, @Askjensen! Closing this as it will be taken care of by #5698.
