### ISSUE TITLE
Explanations don't line up with code samples

### ISSUE THREAD

**Issue by jhgann** [dotnet/docs#7255]
There are references to line numbers in code samples, but the lines are not numbered.
There are references to highlighted lines of code, but there are no highlighted lines.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36115425-3181-1363-dcbd-42e48db8613c
* Version Independent ID: 57ca5426-2ae3-7260-cef9-e92dc9d4e856
* Content: [Delegates and lambdas](https://docs.microsoft.com/en-us/dotnet/standard/delegates-lambdas)
* Content Source: [docs/standard/delegates-lambdas.md](https://github.com/dotnet/docs/blob/master/docs/standard/delegates-lambdas.md)
* Product: **dotnet**
* GitHub Login: @richlander
* Microsoft Alias: **wiwagn**

**Comment by imba-tjd** [comment]
The second point is the same as https://github.com/dotnet/docs/issues/7055
