### ISSUE TITLE
Is this intended to be used like one would use `netsh`?

### ISSUE THREAD

**Issue by StingyJack** [dotnet/docs#7258]
As in `netsh http add urlacl url=http://localhost:1234/wcfService user=Everyone`?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 540a3f30-d598-0223-2e92-b1f50b2b793e
* Version Independent ID: 1cfd217d-bf73-763c-40de-bb18777c66c1
* Content: [SocketPermission Class (System.Net)](https://docs.microsoft.com/en-us/dotnet/api/system.net.socketpermission?view=netframework-4.7.2)
* Content Source: [xml/System.Net/SocketPermission.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net/SocketPermission.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks @StingyJack for your comment. @davidsh can you help with this question about SocketPermission?

**Comment by davidsh** [comment]
>As in netsh http add urlacl url=http://localhost:1234/wcfService user=Everyone?

No. SocketPermission refers to the use of .NET Framework APIs to grant various permissions to applications.

See: https://docs.microsoft.com/en-us/dotnet/framework/misc/code-access-security-basics

Most .NET Framework applications runs in "full-trust" and so already have all the permissions.  But scenarios such as web hosting can run in "partial-trust" and only have certain permissions.

**Comment by mairaw** [comment]
Thanks @davidsh!
