### ISSUE TITLE
API reference index does not support searching

### ISSUE THREAD

**Issue by svick** [dotnet/docs#726]
Pages in the API reference (e.g. [`System`](https://docs.microsoft.com/en-us/dotnet/core/api/system)) contain a very useful "Search Reference" field, which can be used to find types and namespaces.

Except the search field is not on the page where I think it would be most useful: [the API reference index](https://docs.microsoft.com/en-us/dotnet/core/api/index).

Right now, when I want to search for a class by name, I do something like:
1. Go to API reference index
2. Go to some random namespace
3. Search

I think step 2 should not be required.

**Comment by mairaw** [comment]
Yes, we're working on fixing that @svick!

**Comment by mairaw** [comment]
This has been fixed a while back. Closing this one.
