### ISSUE TITLE
The four parameter constructor is not accompanied by a good example

### ISSUE THREAD

**Issue by corcus** [dotnet/docs#7260]
The "CreateNode(XmlNodeType, String, String, String)" constructor has an example that does not explain the functionality of the prefix

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: caecb334-2c0e-8c42-f1af-5391a36236c4
* Version Independent ID: 6e62a120-287b-f53f-dd35-21b7b427c92f
* Content: [XmlDocument.CreateNode Method (System.Xml)](https://docs.microsoft.com/en-us/dotnet/api/system.xml.xmldocument.createnode?view=netframework-4.7.2)
* Content Source: [xml/System.Xml/XmlDocument.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Xml/XmlDocument.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by roel4ez** [comment]
I created a PR to help clarify this. Hope this helps!
