### ISSUE TITLE
Model introspection?

### ISSUE THREAD

**Issue by Hummer311** [dotnet/docs#7263]
Hi. I followed along the tutorial without major issues. Thanks for providing those! They're really helpful.

I'm wondering if there exists a way to look "into" the trained model? I'm basically trying to figure out the key feature, i.e., the feature that has the biggest impact on the trained model.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a30b3ff5-b5e6-ff02-6f60-b5cef6f34666
* Version Independent ID: fdf962e2-620e-d9ad-5057-5f96f52dc60f
* Content: [Use ML.NET to predict New York taxi fares (regression)](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/taxi-fare)
* Content Source: [docs/machine-learning/tutorials/taxi-fare.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/taxi-fare.md)
* Product: **dotnet-ml**
* GitHub Login: @aditidugar
* Microsoft Alias: **johalex**

**Comment by JRAlexander** [comment]
@GalOshri, any thoughts?

**Comment by GalOshri** [comment]
It is not easy to view feature importance with the existing APIs, but the new APIs will make this possible. This is discussed [here](https://github.com/dotnet/machinelearning/issues/584).

**Comment by Hummer311** [comment]
Thanks for the info, looking forward to the new API.

**Comment by mangeshw** [comment]
Can you update the tutorial with TaxiTripFarePrediction.FareAmount as string? Currently it appears as float. Below is the link:
Link: https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/taxi-fare

Also can you explain why is FareAmount's data type is different in TaxiTrip and TaxiTripFarePrediction?
