### ISSUE TITLE
The code sample does not cover all the switch clauses

### ISSUE THREAD

**Issue by aldav82** [dotnet/docs#7270]
The current code sample should be modified so the clause

    case Square sq when sq.Area > 0:

can be accessed. Currently, the first item in the sample collection passed is an object  of type Square (...new Square(10)...), but the current order of the case statements

      switch (obj)
      {
         case Shape shape when shape.Area == 0:
             ...
         case Rectangle r when r.Area > 0:
             ...
         case Square sq when sq.Area > 0:
             ...
         case Shape shape:
             ...
         case null:
             ...
         default:
             ...
      }

 does not allow to access the case when the object is of type Square and the area is greater than 0 (Square sq when sq.Area > 0), because the previous case condition is more general (Rectangle r when r.Area > 0). I would propose modify the case statements order:

             ...
         case Square sq when sq.Area > 0:
             ...
         case Rectangle r when r.Area > 0:
             ... 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ef10b29-fbf8-5af9-8f8b-a694a1416e33
* Version Independent ID: 15502bbc-5355-2add-0fa8-ae31dc01c122
* Content: [when (C# Reference)](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/when)
* Content Source: [docs/csharp/language-reference/keywords/when.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/when.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
Thanks @aldav82 for the feedback. Would you like to submit a pull request for this?

**Comment by aldav82** [comment]
Sure, I just can't quite figure out the location of the file needed to be changed. It is not [docs/csharp/language-reference/keywords/when.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/when.md), it is the c# code sample referenced at the end of that file, but I can't quite find out where in the repository is that file.

**Comment by aldav82** [comment]
Ok, I just realized the modifications should be done on the [dotnet/samples](https://github.com/dotnet/samples) repository. A [PR](https://github.com/dotnet/samples/pull/266) was created. Thanks.

**Comment by briandunnington** [comment]
PR here: https://github.com/dotnet/samples/pull/267
