### ISSUE TITLE
Dark theme issues

### ISSUE THREAD

**Issue by GaTechThomas** [dotnet/docs#7275]
With the docs.microsoft.com dark theme enabled, the images on the page are difficult to see.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49346f80-1204-08d7-df5e-3495c2404eca
* Version Independent ID: bcba2429-f5ab-0b27-6780-95155f27f142
* Content: [Designing a microservice-oriented application](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/multi-container-microservice-net-applications/microservice-application-design)
* Content Source: [docs/standard/microservices-architecture/multi-container-microservice-net-applications/microservice-application-design.md](https://github.com/dotnet/docs/blob/master/docs/standard/microservices-architecture/multi-container-microservice-net-applications/microservice-application-design.md)
* Product: **dotnet**
* GitHub Login: @CESARDELATORRE
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
Thanks for your feedback @GaTechThomas. I'm closing this as duplicate of #6547 since this occurs in the entire microservices book.

**Comment by mairaw** [comment]
Duplicate of #6547
