### ISSUE TITLE
Misspelled "especially"

### ISSUE THREAD

**Issue by nelfer** [dotnet/docs#7280]
There's a misspelled word "expecially" in the last paragraph of this section: https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/microservice-ddd-cqrs-patterns/nosql-database-persistence-infrastructure#a-model-used-by-mongodb-api

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f1e64c7-90e1-baec-014a-4da1e5465f92
* Version Independent ID: f05cea37-d22d-ed74-71ad-f592ac29f593
* Content: [Using NoSQL databases as a persistence infrastructure](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/microservice-ddd-cqrs-patterns/nosql-database-persistence-infrastructure)
* Content Source: [docs/standard/microservices-architecture/microservice-ddd-cqrs-patterns/nosql-database-persistence-infrastructure.md](https://github.com/dotnet/docs/blob/master/docs/standard/microservices-architecture/microservice-ddd-cqrs-patterns/nosql-database-persistence-infrastructure.md)
* Product: **dotnet**
* GitHub Login: @CESARDELATORRE
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
Thanks for pointing that out @nelfer. Would you like to submit a pull request for this fix?

**Comment by nelfer** [comment]
hehe... if I knew how to do that, I would :)

**Comment by pkulikov** [comment]
@nelfer try to follow this procedure:
https://docs.microsoft.com/en-us/contribute/#quick-edits-to-existing-documents

**Comment by nelfer** [comment]
That was easy! It's done

**Comment by mairaw** [comment]
Thanks @pkulikov for the help and @nelfer for your first contribution to our docs. I’m glad you found it easy!

**Comment by pkulikov** [comment]
@nelfer @mairaw then this issue can be closed :).

**Comment by mairaw** [comment]
Oh yeah. The fixes in the PR had a word in there so it didn’t close automatically.
