### ISSUE TITLE
Misleading comment

### ISSUE THREAD

**Issue by adrianwadey** [dotnet/docs#7281]
The comment in the code incorrectly says asynchronously when it is synchronous:
// Speak the contents of the prompt asynchronously.  
      synth.SpeakSsml(str); 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c495e9b5-a28f-8a6a-46da-1125291bf21c
* Version Independent ID: a7931045-5198-fd4d-6879-d896b09ebb86
* Content: [SpeechSynthesizer.SpeakSsml(String) Method (System.Speech.Synthesis)](https://docs.microsoft.com/en-us/dotnet/api/system.speech.synthesis.speechsynthesizer.speakssml?view=netframework-4.7.2)
* Content Source: [xml/System.Speech.Synthesis/SpeechSynthesizer.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Speech.Synthesis/SpeechSynthesizer.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mikkelbu** [comment]
Should be corrected by dotnet/dotnet-api-docs#471,

**Comment by rpetrusha** [comment]
Closing since dotnet/dotnet-api-docs#471 has merged.
