### ISSUE TITLE
Spaghetti code

### ISSUE THREAD

**Issue by thphan75** [dotnet/docs#7299]
ProcessStartInfo startInfo = new ProcessStartInfo();  (new is not needed here)

 startInfo = new ProcessStartInfo(fileName); (should check to see if file exists before this step)
                if (File.Exists(fileName))

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80042e9e-4961-6cef-0413-6b252be97bd3
* Version Independent ID: 309c2a7d-ea14-5b23-af0f-b14319e72f62
* Content: [ProcessStartInfo.Verbs Property (System.Diagnostics)](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.processstartinfo.verbs?view=netframework-4.7.2)
* Content Source: [xml/System.Diagnostics/ProcessStartInfo.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Diagnostics/ProcessStartInfo.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
You're right, @thphan75. This is indeed poorly written code. There's an unnecessary object instantiation, and the file check is performed much too late and, if it's performed earlier, eliminates the need to test for `null`. We'll revise it in the near future.
