### ISSUE TITLE
Confusing

### ISSUE THREAD

**Issue by ohadbitt** [dotnet/docs#7303]
You call the parameter  "index" - "The starting point in chars from which to begin writing."
While it is where you begin reading from buffer, not writing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9f85f1f-b853-fd00-36ac-f9b0439afb5d
* Version Independent ID: bfe5659e-18eb-887e-034b-da20ca551ca3
* Content: [BinaryWriter.Write Method (System.IO)](https://docs.microsoft.com/en-us/dotnet/api/system.io.binarywriter.write?view=netframework-4.7.2#System_IO_BinaryWriter_Write_System_Byte___System_Int32_System_Int32_)
* Content Source: [xml/System.IO/BinaryWriter.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.IO/BinaryWriter.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
Thanks for pointing this out, @ohadbitt. I agree that this is confusing; the documentation makes it sound as if index identifies a position in the stream, rather than the index from which data is to be read.

**Comment by rpetrusha** [comment]
We've corrected the parameter description for the two overloads of the Write method that write a portion of an array to the stream in dotnet/dotnet-api-docs#472, @ohadbitt.
