### ISSUE TITLE
Clarify guidance .NET Standard 2.0 supported frameworks

### ISSUE THREAD

**Issue by devlead** [dotnet/docs#7305]
Regarding https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support

Currently .NET 4.6.1 is listed as a recommended  minimum framework for .NET Standard 2.0

As per below recent tweet from @terrajobst , the recommendation is 
> If you want to consume .NET Standard 1.5+ from .NET Framework, I recommend to be on 4.7.2.

https://twitter.com/terrajobst/status/1031999730320986112

I can do the work and send a PR to update, just want to make sure if `4.7.2` is the number I should put here:
![image](https://user-images.githubusercontent.com/1647294/44657846-9fa55500-a9fe-11e8-96e6-7d1a4349b43d.png)

I get weekly issues with questions and would like to be able to point to some official guidance.

**Comment by devlead** [comment]
Also get this guidance might need to be reved

* https://github.com/dotnet/standard/blob/master/docs/versions/netstandard2.0.md#platform-support
* http://immo.landwerth.net/netstandard-versions/# (link from https://github.com/dotnet/standard/blob/master/docs/faq.md#as-a-library-author-which-version-of-net-standard-should-i-target)
* https://github.com/dotnet/standard/blob/master/docs/planning/netstandard-20/README.md#net-framework-461-supporting-net-standard-20

**Comment by mairaw** [comment]
Thanks @devlead. Adding @terrajobst here to comment on this request. Agreed that if we review the guidance, all those pointers should be updated as well.

See his comment from a similar request here:
https://github.com/dotnet/docs/issues/5915#issuecomment-406438591

If now is not the right time yet to change those cells to 4.7.2, we could also add a warning for now to the topic about the recommended .NET Framework version for 1.5+.

**Comment by Kryptos-FR** [comment]
Any update? It's been 3 months.

**Comment by SimonCropp** [comment]
almost up to six months. any update?
