### ISSUE TITLE
Dead link: azuremigrationcenter.com website expired?

### ISSUE THREAD

**Issue by andrePKI** [dotnet/docs#7308]
Dead link: azuremigrationcenter.com website expired?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff2c0df0-a19f-b03c-c614-31a2dc068729
* Version Independent ID: 96844a08-f041-4cab-a1e2-0905f7a3a63f
* Content: [Lift and shift existing .NET apps to Azure IaaS (Cloud Infrastructure-Ready)](https://docs.microsoft.com/en-us/dotnet/standard/modernize-with-azure-and-containers/lift-and-shift-existing-apps-azure-iaas)
* Content Source: [docs/standard/modernize-with-azure-and-containers/lift-and-shift-existing-apps-azure-iaas.md](https://github.com/dotnet/docs/blob/master/docs/standard/modernize-with-azure-and-containers/lift-and-shift-existing-apps-azure-iaas.md)
* Product: **dotnet**
* GitHub Login: @CESARDELATORRE
* Microsoft Alias: **wiwagn**

**Comment by JRAlexander** [comment]
Thanks, @andrePKI, for the heads up! Checking on it now.

**Comment by Youssef1313** [comment]
should be closed, that was fixed in https://github.com/dotnet/docs/pull/10218

**Comment by mairaw** [comment]
Thank you @Youssef1313 for noticing.
