### ISSUE TITLE
Add information about EventSource, Diagnostic Source and System.Diagnostics.Activity 

### ISSUE THREAD

**Issue by lmolkova** [dotnet/docs#7311]
.NET added DiagnosticSource and Activity APIs to help with distributed tracing and correlation. The document should mention them. 

EventSource is another way for production/in-field monitoring https://blogs.msdn.microsoft.com/vancem/2012/08/13/windows-high-speed-logging-etw-in-c-net-using-system-diagnostics-tracing-eventsource/

The document should cover where TraceSource vs EventSource vs DiagnosticSource should be used.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f541c73-b622-0458-a51e-e778dabb3a7e
* Version Independent ID: f9c0ddc1-6be3-0d18-c52c-9e02507f7050
* Content: [Tracing and Instrumenting Applications](https://docs.microsoft.com/en-us/dotnet/framework/debug-trace-profile/tracing-and-instrumenting-applications)
* Content Source: [docs/framework/debug-trace-profile/tracing-and-instrumenting-applications.md](https://github.com/dotnet/docs/blob/master/docs/framework/debug-trace-profile/tracing-and-instrumenting-applications.md)
* Product: **dotnet-framework**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by SwooshyCueb** [comment]
It looks like DiagnosticSource, DiagnosticListener, and Activity only have bare-bones "these classes exist with these members" reference documentation, but the source does include XML documentation comments. Is getting that moved to MSDN covered by this issue, or should a separate issue in dotnet/dotnet-api-docs be opened?
