### ISSUE TITLE
any code share？

### ISSUE THREAD

**Issue by zxs731** [dotnet/docs#7314]
is there any code share？where we can get the code mentioned in this article？

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c1c070c-b2ff-f29d-21df-bcc7bf9dd39d
* Version Independent ID: 02ba7d88-65d4-b492-880c-4bc8c044b34e
* Content: [Implementing the infrastructure persistence layer with Entity Framework Core](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/microservice-ddd-cqrs-patterns/infrastructure-persistence-layer-implemenation-entity-framework-core)
* Content Source: [docs/standard/microservices-architecture/microservice-ddd-cqrs-patterns/infrastructure-persistence-layer-implemenation-entity-framework-core.md](https://github.com/dotnet/docs/blob/master/docs/standard/microservices-architecture/microservice-ddd-cqrs-patterns/infrastructure-persistence-layer-implemenation-entity-framework-core.md)
* Product: **dotnet**
* GitHub Login: @CESARDELATORRE
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
We don't have a link to the repo from all topics but it can be found listed at the cover article for the e-book at least: https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/#about-this-guide

The sample location for the microservices book can be found at https://github.com/dotnet-architecture/eShopOnContainers.
