### ISSUE TITLE
Does ASP.NET Core implicit store apply to M.A.App in addition to M.A.All?

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/docs#7321]
See [ASP.NET Core implicit store](https://docs.microsoft.com/en-us/dotnet/core/deploying/runtime-store#aspnet-core-implicit-store) on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70e2a4f1-0f8e-0d0f-5c82-f7f3972e238e
* Version Independent ID: 6f43fca9-13cf-67c9-c583-df70ef1a5d44
* Content: [Runtime package store](https://docs.microsoft.com/en-us/dotnet/core/deploying/runtime-store#aspnet-core-implicit-store)
* Content Source: [docs/core/deploying/runtime-store.md](https://github.com/dotnet/docs/blob/master/docs/core/deploying/runtime-store.md)
* Product: **dotnet-core**
* GitHub Login: @bleroy
* Microsoft Alias: **mairaw**

**Comment by Rick-Anderson** [comment]
@natemcmaster can you answer this?

**Comment by natemcmaster** [comment]
Not anymore. The implicit store only applies to ASP.NET Core 2.0. In 2.1, introduced the Microsoft.AspNetCore.App shared framework and stopped using the runtime store feature altogether. We also converted M.A.All to a shared framework.

**Comment by JRAlexander** [comment]
This looks like it's been resolved. If not, please reopen.

**Comment by Rick-Anderson** [comment]
I need to update the doc to state We also converted M.A.All to a shared framework.

**Comment by Rick-Anderson** [comment]
@natemcmaster should I update this something like the following?

**ASP.NET Core implicit store**

The ASP.NET Core implicit store was used by ASP.NET Core 2.0 until version 2.0.x? Or is still used when you target 2.0?

We strongly recommend updating to ASP.NET Core 2.1 or later which doesn't use the runtime store. ASP.NET Core 2.1 and later use the [shared framework](https://github.com/dotnet/docs/issues/5009)

**Comment by natemcmaster** [comment]
The implicit store is used for all ASP.NET Core 2.0.x releases. It is always used when you reference the Microsoft.AspNetCore.All 2.0.x package.

And yes, we strongly recommend moving to ASP.NET Core 2.1. .NET Core 2.0 will not be supported after Oct. 1. See https://blogs.msdn.microsoft.com/dotnet/2018/06/20/net-core-2-0-will-reach-end-of-life-on-september-1-2018/
