### ISSUE TITLE
cref summary text won't show in .NET API Browser Description

### ISSUE THREAD

**Issue by imba-tjd** [dotnet/docs#7325]
For example, searching `missing`:
![qq 20180828152637](https://user-images.githubusercontent.com/24759802/44707339-d64e9e80-aad6-11e8-9131-aa67244fbc91.png)
![default](https://user-images.githubusercontent.com/24759802/44707364-e5355100-aad6-11e8-8d0b-047f090acd3f.png)
Source: https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Reflection/Missing.xml#L49

**Comment by mairaw** [comment]
I can repro this issue. Since content looks good and it seems to be a general site issue on how the API browser behaves, I've moved this feedback to https://github.com/MicrosoftDocs/feedback/issues/637. Thanks for reporting it @imba-tjd.
