### ISSUE TITLE
Syntax highlighting is inconsistent for Class names

### ISSUE THREAD

**Issue by Shah-Nisarg** [dotnet/docs#7328]
I saw this in one of the examples:

![image](https://user-images.githubusercontent.com/20351320/44721132-8bd51e00-aae6-11e8-93f0-007197fe164e.png)

Notice the highlighting on constructors of `XElement`; two of them are highlighted in lighter blue color, while the rest are in black color.

I noticed that you are using [highlight.js](https://highlightjs.org/) v9.12.0. So let me know if I should raise the issue on their repo.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4a44517-d9a2-454d-90f3-90d9553ff4be
* Version Independent ID: f31a6959-8212-a49f-eeb4-43936dbfbadb
* Content: [Data Transformations with LINQ (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/linq/data-transformations-with-linq)
* Content Source: [docs/csharp/programming-guide/concepts/linq/data-transformations-with-linq.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/linq/data-transformations-with-linq.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
Thank you for your feedback @Shah-Nisarg. Given this is about the site experience and not the content itself, I've moved the feedback to https://github.com/MicrosoftDocs/feedback/issues/641. Someone from the engineering team should follow up on that.
