### ISSUE TITLE
C# support for LINQ article improvements

### ISSUE THREAD

**Issue by Shah-Nisarg** [dotnet/docs#7331]
The page title is "C# Features That Support LINQ". However looking at some of the sections in the page, I am puzzled as to how they relate to the topic.

For example:
1. Object and Collection Initializers
    I can't think of any way in which the section relates to LINQ. It doesn't explain that either. 

2. Auto-Implemented Properties
    Again, I'm not sure how this section is relevant to LINQ, and there is no mention of how it is relevant.

I have refrained from touching on these points in my [PR](https://github.com/dotnet/docs/pull/7330). In case, those sections are actually relevant, could you explain how?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b67ec87-db79-aa53-86c3-c320f33a8a21
* Version Independent ID: 10925e94-c639-5c04-168c-b805c00e1230
* Content: [C# Features That Support LINQ](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/linq/features-that-support-linq)
* Content Source: [docs/csharp/programming-guide/concepts/linq/features-that-support-linq.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/linq/features-that-support-linq.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by rpetrusha** [comment]
Thank,  @Shah-Nisarg, for your comment (as well as for submitting your PR). Object and collection initializers, as the documentation notes, can project the data returned by a query into a new data type; the example included just doesn't provide an illustration, as it should. 

In terms of auto-implemented properties, I can't think of how they might be relevant to LINQ queries.

So the example for object and collection initializers needs to be replaced and the auto-implemented properties section probably needs to be deleted. I'll rename this issue, add it to the backlog, and add it to the community contributors' project.

**Comment by jmarkman** [comment]
Hi, I'd like to take a look at working on this issue.

**Comment by rpetrusha** [comment]
That would be great, @jmarkman. We'll look forward to reviewing your PR. And in the meantime, if you have any questions, please do not hesitate to ask.

**Comment by jmarkman** [comment]
Would it be going overboard/against style to add a method syntax version of a query? It might be out of scope since it would be the only section with a method syntax version of the query, but I think having both is important for novice dev readers and those unfamiliar with LINQ.

**Comment by BillWagner** [comment]
It's not going overboard.  That is useful information.

[This article](https://docs.microsoft.com/dotnet/csharp/programming-guide/concepts/linq/query-expression-syntax-for-standard-query-operators) covers the mapping now. But, it's not obvious that it's about the mapping from query syntax to method calls. 

I'd propose making that more clear rather than duplicating the information. (And, that might be a separate PR, depending on the scope).

**Comment by jmarkman** [comment]
@BillWagner 
> I'd propose making that more clear rather than duplicating the information.

This is in regards to the article you linked? Just want to make sure. If not, one thought I have is that I'd include a link to that page, but I'm not sure where it would go. Would it be best to modify the "For more information, see" area at the end of the section and add a link to that page like the following?

> For more information, see:
> - [Anonymous Types] //(path)
> - [Query Expression Syntax for Standard Query Operators] //(path)

**Comment by BillWagner** [comment]
@jmarkman Yes, I should have been more clear.

The "features that support LINQ" article should link to the "query expression syntax for standard query operators" article. Your suggestion to add it to "For more information see..." is correct.

The "query expression syntax for standard query operators" does explain the mapping. It could be improved, and that may be best handled in another PR.
