### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by MrExplode** [dotnet/docs#7339]
I have .NET 4.7.2 installed. Howewer, VS still says there is no namespace like System.Web.ClientServices.Providers

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 221496a6-b61f-967d-9765-b2fb47204aa7
* Version Independent ID: b3e1fb61-c336-a64f-2ea8-33bd1840eb7c
* Content: [How to: Implement User Login with Client Application Services](https://docs.microsoft.com/en-us/dotnet/framework/common-client-technologies/how-to-implement-user-login-with-client-application-services)
* Content Source: [docs/framework/common-client-technologies/how-to-implement-user-login-with-client-application-services.md](https://github.com/dotnet/docs/blob/master/docs/framework/common-client-technologies/how-to-implement-user-login-with-client-application-services.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Have you referenced the assembly needed in your project like System.Web.Extensions.dll?

**Comment by MrExplode** [comment]
Well, no. Then probably that will be the problem, thanks

**Comment by mairaw** [comment]
Closing this issue then.
