### ISSUE TITLE
Documentation needs to be updated to reflect VS 15.8+

### ISSUE THREAD

**Issue by lisaguthrie** [dotnet/docs#7341]
This documentation is out of date. VS 15.8+ no longer create a docker-compose project, just a Dockerfile. Also, the VS 2015 tools for Docker are no longer supported.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcf20f50-2d15-1744-386d-1d05ff9931fb
* Version Independent ID: b07f881a-4b4e-9db5-9eb6-c83cf0fba6b2
* Content: [Using Visual Studio Tools for Docker (Visual Studio on Windows)](https://docs.microsoft.com/en-us/dotnet/standard/containerized-lifecycle-architecture/design-develop-containerized-apps/visual-studio-tools-for-docker)
* Content Source: [docs/standard/containerized-lifecycle-architecture/design-develop-containerized-apps/visual-studio-tools-for-docker.md](https://github.com/dotnet/docs/blob/master/docs/standard/containerized-lifecycle-architecture/design-develop-containerized-apps/visual-studio-tools-for-docker.md)
* Product: **dotnet**
* GitHub Login: @CESARDELATORRE
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
Thanks @lisaguthrie. I just pinged you on a PR with the updates to this topic. Please take a look.

**Comment by mairaw** [comment]
@mvelosop please look at the set of changes that @gewarren is applying to the topics at PR #7214  and apply them to the e-book source.

**Comment by mvelosop** [comment]
Thanks @mairaw, that should go into the next chapter, I created issue #7888 so It gets into my review process!
