### ISSUE TITLE
.Net Core Cross Platform

### ISSUE THREAD

**Issue by atif-shamim** [dotnet/docs#7356]
Hi There,

Can anyone answer my question that What makes .NET Core Cross Platform and what are its different with previous .Net Framework which makes it cross platform

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 581f6cbb-c666-87ee-ab0c-f131baca403c
* Version Independent ID: 9205f603-e1d4-e0eb-1273-f176fcbf520f
* Content: [About .NET Core](https://docs.microsoft.com/en-us/dotnet/core/about)
* Content Source: [docs/core/about.md](https://github.com/dotnet/docs/blob/master/docs/core/about.md)
* Product: **dotnet-core**
* GitHub Login: @richlander
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Hi @atif-shamim, .NET Core is cross platform because it runs on Windows, macOS and Linux while .NET Framework is Windows only. .NET Core has a different implementation which allows the code to run on these different platforms.

This StackOverflow question covers a similar question:
https://stackoverflow.com/questions/38063837/whats-the-difference-between-net-core-net-framework-and-xamarin

I hope this helps!

**Comment by atif-shamim** [comment]
Hi @mairaw My Question was different what exactly there is difference  in implementation in .Net Core and .Net Framework which makes .Net Core Cross platform.

I understand since .Net Core runs on Windows, macOS and Linux that's why its Cross Platform but what exactly the implementation of .Net Core makes it Cross Platform.

Also one more question what exact implementation makes .Net Core high performance and scalable.

**Comment by svick** [comment]
@atif-shamin

> My Question was different what exactly there is difference in implementation in .Net Core and .Net Framework which makes .Net Core Cross platform.

I'd say the biggest difference is that whenever .Net Core needs some service from the operating system (like allocating memory or opening files), it goes though a Platform Abstraction Layer (PAL), which means each OS can have a different implementation.

> Also one more question what exact implementation makes .Net Core high performance and scalable.

There is no single thing that does that. When you want to make a high performance framework, pretty much every component has to be efficient. So you need good abstractions (like `await` or `Span<T>`), good library (like efficient `List<T>` or `HttpClient`) and good machine code compiler (RyuJIT).
