### ISSUE TITLE
Please provide the output that the example prints to console

### ISSUE THREAD

**Issue by davidbozjak** [dotnet/docs#7357]
In most of the examples we see on docs we also see na output that the sample would print. This is missing on the page below. Please add it to make the article more useful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f081c486-54a2-aee0-dc80-6cb3a658c67d
* Version Independent ID: c4cafc4d-797c-4f93-6318-84b16438a833
* Content: [Uri.Fragment Property (System)](https://docs.microsoft.com/en-us/dotnet/api/system.uri.fragment?redirectedfrom=MSDN&view=netframework-4.7.2#System_Uri_Fragment)
* Content Source: [xml/System/Uri.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System/Uri.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
Thanks for your feedback, @davidbozjak. We've added output for the examples in dotnet/samples#274.

**Comment by davidbozjak** [comment]
Thanks, looking forward to it being deployed.
