### ISSUE TITLE
Wrong type in description

### ISSUE THREAD

**Issue by boskjoett** [dotnet/docs#7359]
The description for CreateSerializer says "Returns a derivation of the XmlSerializerFactory class ..." in many places. It should be "Returns a derivation of the XmlSerializer class ..." in all places.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c41a03a1-fb09-d61a-35f7-5faf83e4cd41
* Version Independent ID: 880b85fa-8cb1-0bcc-7527-d996803a7375
* Content: [XmlSerializerFactory.CreateSerializer Method (System.Xml.Serialization)](https://docs.microsoft.com/en-us/dotnet/api/system.xml.serialization.xmlserializerfactory.createserializer?view=netframework-4.7.2#System_Xml_Serialization_XmlSerializerFactory_CreateSerializer_System_Type_)
* Content Source: [xml/System.Xml.Serialization/XmlSerializerFactory.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Xml.Serialization/XmlSerializerFactory.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
Thanks for pointing this out, @boskjoett. We've corrected the erroneous description in dotnet/docs#478.
