### ISSUE TITLE
Link takes me to MSDN

### ISSUE THREAD

**Issue by Shah-Nisarg** [dotnet/docs#7361]
In the first section there is a link: `How to: Generate XML from CSV Files`, which takes me to [MSDN](https://msdn.microsoft.com/library/dd7bab8c-96fa-4343-94d0-9739dd6a74fd), and after I choose C#, back to docs: https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/linq/how-to-generate-xml-from-csv-files.

The issue is similar to: https://github.com/dotnet/docs/issues/6955

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2730d0d-f5e5-9948-5566-008fb42b8a2d
* Version Independent ID: a9b9f250-0107-cf1b-c182-469c7fbe5fb5
* Content: [LINQ and Strings (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/linq/linq-and-strings)
* Content Source: [docs/csharp/programming-guide/concepts/linq/linq-and-strings.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/linq/linq-and-strings.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
We have a whole issue to review the MSDN links (#2037). You can see we're making progress towards that. 

But for this one in particular, I ended up already fixing that when I was addressing the other issue you reported:
https://github.com/dotnet/docs/pull/7374

**Comment by Shah-Nisarg** [comment]
@mairaw Thanks for letting me know. I assume that I don't need to report MSDN routing related issues separately.
