### ISSUE TITLE
WCF Test Client and TLS 1.2

### ISSUE THREAD

**Issue by marsti** [dotnet/docs#7366]
Using: Windows 10 with .NET Framework 4.7.2 and WCF Test Client 15.0.27825.0

I am trying to get the WCF Test Client to connect with a web server that only supports TLS 1.2.

Is this supported or do I have to do any changes in e.g. WcfTestClient.exe.config ?

**Comment by marsti** [comment]
Using: Windows 10 and WCF Test Client 16.0.28522.59 (Visual Studio 2019)

Still the same problem.

**Comment by nambir** [comment]
do you guys found any solution?
