### ISSUE TITLE
Docs for Dummies ( or "This is how we do it ! " )

### ISSUE THREAD

**Issue by stevehtml** [dotnet/docs#7367]
Icing on the cake , entire topic comes as PDF ! THANK You , so hard a time with so basic a skill. From what I've read so far you've made it very simple & uncomplicated. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 301116d4-ff88-c411-e0e3-ba8b552fc6ee
* Version Independent ID: 586f81d7-d9df-95f7-d73f-7d7b6db198a5
* Content: [How to: Read From a Text File (C# Programming Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/file-system/how-to-read-from-a-text-file)
* Content Source: [docs/csharp/programming-guide/file-system/how-to-read-from-a-text-file.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/file-system/how-to-read-from-a-text-file.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
Thank you for your comments @stevehtml. We're glad you liked the topic and the new functionalities we're adding to our new docs site.
