### ISSUE TITLE
Second and Third code examples are around the wrong way.

### ISSUE THREAD

**Issue by SteveGoodman** [dotnet/docs#7370]
Please swap the code samples for example 2 and 3 as they are currently around the wrong way.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 316c9bfd-da1c-0f69-7314-6bfb5caa42e5
* Version Independent ID: 457cdce2-b90e-4dfb-318f-895357738f1f
* Content: [How to: Create a Custom Security Token Authenticator](https://docs.microsoft.com/en-us/dotnet/framework/wcf/extending/how-to-create-a-custom-security-token-authenticator)
* Content Source: [docs/framework/wcf/extending/how-to-create-a-custom-security-token-authenticator.md](https://github.com/dotnet/docs/blob/master/docs/framework/wcf/extending/how-to-create-a-custom-security-token-authenticator.md)
* Product: **dotnet-framework**
* GitHub Login: @BrucePerlerMS
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
Thanks for pointing this out, @SteveGoodman. I've opened PR #7381 to correct it.
