### ISSUE TITLE
Where is PeekByte() ?

### ISSUE THREAD

**Issue by djmarcus1** [dotnet/docs#7373]
The class supports a PeekChar() but not PeekByte().

Given that is supports byte operations, then PeekByte() should have been there!.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85fe2be8-c1a2-75a5-2308-8e7572b647fb
* Version Independent ID: 84c4bc98-3b95-8502-3bb5-6591b49713d2
* Content: [BinaryReader Class (System.IO)](https://docs.microsoft.com/en-us/dotnet/api/system.io.binaryreader?view=netframework-4.7.2)
* Content Source: [xml/System.IO/BinaryReader.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.IO/BinaryReader.xml)
* Product: **dotnet-api**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Thanks for your feedback @djmarcus1. This repository is for content feedback only.

@JeremyKuhne, @pjanotti can comment on this product request and whether I should move to another repo.

**Comment by mairaw** [comment]
Thanks @JeremyKuhne. @djmarcus1 please submit your API suggestion at 
https://github.com/dotnet/corefx.
