### ISSUE TITLE
the pasword/username box that appears everytime I try to install the service.

### ISSUE THREAD

**Issue by Lordzalo** [dotnet/docs#7377]
I tried to install my service using the comand promt (as an administrator) a box pops up telling me that I need 
 pasword and username. Could someone answer why, and what do I have to do?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75152e30-b486-3ba0-c606-25ada7347b22
* Version Independent ID: e797ddfe-a9d3-93a4-61bd-fd6dc9b8d6b4
* Content: [Walkthrough: Creating a Windows Service Application in the Component Designer](https://docs.microsoft.com/en-us/dotnet/framework/windows-services/walkthrough-creating-a-windows-service-application-in-the-component-designer#BK_CreateProject)
* Content Source: [docs/framework/windows-services/walkthrough-creating-a-windows-service-application-in-the-component-designer.md](https://github.com/dotnet/docs/blob/master/docs/framework/windows-services/walkthrough-creating-a-windows-service-application-in-the-component-designer.md)
* Product: **dotnet-framework**
* GitHub Login: @ghogen
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
Thanks for your feedback, @Lordzalo. Make sure that the console window indicates that you're running as administrator. If you are, there could be many causes for this issue. This would be a good question for stackoverflow. Since this isn't a doc bug, I'll close this issue.
