### ISSUE TITLE
why not link?

### ISSUE THREAD

**Issue by kbdguy** [dotnet/docs#7384]
"see the Query by Example overview topic"  Great!  WHERE?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cf2d222-8338-1896-c9ab-48ad9bab0c0f
* Version Independent ID: 305a5a1b-7f2d-cba3-a2a5-1586cd477dfa
* Content: [PrincipalSearcher.QueryFilter Property (System.DirectoryServices.AccountManagement)](https://docs.microsoft.com/en-us/dotnet/api/system.directoryservices.accountmanagement.principalsearcher.queryfilter?view=netframework-4.7.2#System_DirectoryServices_AccountManagement_PrincipalSearcher_QueryFilter)
* Content Source: [xml/System.DirectoryServices.AccountManagement/PrincipalSearcher.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.DirectoryServices.AccountManagement/PrincipalSearcher.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
I'm apologize for this inconvenience, @kbdguy, that there was no link to the topic. It seems to have been removed from our documentation set; in any case, search hasn't succeeded in finding it. I've opened PR dotnet/dotnet-api-docs#480 to remove it.
