### ISSUE TITLE
Add description about from where assembly information are taken

### ISSUE THREAD

**Issue by LukaszDev** [dotnet/docs#739]
Hi Guys,

Following this issues:
- [Wrong assembly information / exe file details (dotnet/cli  #3620)](https://github.com/dotnet/cli/issues/3620)
- [Add information about assembly information (aspnet/Docs #1525 )](https://github.com/aspnet/Docs/issues/1525#issuecomment-228831915)

**Can you consider to add note/description in docs about from where assembly information are taken, please ?**

I mean relation between `project.json` (or any other future file) and `AssemblyInfo.cs`.

Currently `AssemblyInfo.cs` file is not included in new project created from default template in VS2015... It's mean that assembly information are taken form `project.json` - that's fine, but `AssemblyInfo.cs` it's still 'higher priority' file, and it's used if exist anywhere in the project...

It's mean that we have mess if we don't have our own `AssemblyInfo.cs` file (by default), but any of 3rd-party library (included by bower) contains that file (from any reason) - in that case this 3rd-party file will be taken as source of assembly information.

There is solution for that - we can exclude `lib` folder from compilation in `project.json` file - for example:

```
"buildOptions": {
  "compile": {
    "exclude": [ "lib" ]
  }
}
```

but still it confuse if you don't know about this, so my suggestion is mention about this potential situation in new docs.

Thanks in advance.

**Comment by mairaw** [comment]
@blackdwarf can you take a look at this?

**Comment by BillWagner** [comment]
I'm going to close this.

The .csproj format does not write assembly version information into the project file. The new product design means this doesn't apply.

@LukaszDev if you have any questions, please reopen with a comment.
