### ISSUE TITLE
Azure Guest OS registry settings

### ISSUE THREAD

**Issue by daiyoshi** [dotnet/docs#7390]
&gt;&gt;The Azure Guest OS image for Azure Cloud Services already has the SchUseStrongCrypto registry key set to a value of 1. 
In Azure Cloud Services' Azure guest OS image, the value of SchUseStrongCrypto registry key is not set to 1.
Therefore, if you do not do anything, you get an error and you can not connect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7341fa0a-f474-6c2d-d3c0-7e2df12fbb65
* Version Independent ID: e99c489a-7518-d293-ad93-7eaca8b7191a
* Content: [Transport Layer Security (TLS) best practices with the .NET Framework](https://docs.microsoft.com/en-us/dotnet/framework/network-programming/tls#azure-cloud-services)
* Content Source: [docs/framework/network-programming/tls.md](https://github.com/dotnet/docs/blob/master/docs/framework/network-programming/tls.md)
* Product: **dotnet-framework**
* GitHub Login: @blowdart
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
@blowdart can you help with this feedback?

**Comment by blowdart** [comment]
No, this is a question for Azure support.

**Comment by mairaw** [comment]
But we have this section on the docs about this: https://docs.microsoft.com/en-us/dotnet/framework/network-programming/tls#azure-guest-os-registry-settings

So is that information accurate?

**Comment by mairaw** [comment]
We're adding the clarification that is the Family 5 image that has the value already set.

**Comment by Thraka** [comment]
@KjetilEVRY I can't seem to find where the documentation is wrong. Can you clarify?
