### ISSUE TITLE
When adding cookie to cookie container, domain is invalid

### ISSUE THREAD

**Issue by mahspiir** [dotnet/docs#7393]
Hi,

When adding a cookie to a CookieContainer the VerifySetDefaults method will throw a CookieException with message "The 'Domain'='https://somedomain.com' part of the cookie is invalid." when using the example given because the protocol is included.

The correct format for domain seems to be "somedomain.com"

See this fiddle for reference
https://dotnetfiddle.net/KaT5DQ

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9d079bc-d7bb-393e-9ec8-78245396bdf9
* Version Independent ID: 4483aed9-7325-bffb-d190-0cccbdadda3e
* Content: [Cookie Constructor (System.Net)](https://docs.microsoft.com/en-us/dotnet/api/system.net.cookie.-ctor?view=netframework-4.7.2#System_Net_Cookie__ctor_System_String_System_String_System_String_System_String_)
* Content Source: [xml/System.Net/Cookie.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net/Cookie.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by karelz** [comment]
Good catch @mahspiir. I put up a PR to fix it: https://github.com/dotnet/dotnet-api-docs/pull/650
