### ISSUE TITLE
Longer C# example please.

### ISSUE THREAD

**Issue by Protiguous** [dotnet/docs#7406]
A longer C# example would be more helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4eb5036e-ef53-4f8e-c15d-3a7829fbe049
* Version Independent ID: 62552b5f-9427-92c3-af97-ec76e1992222
* Content: [Adding DataRelations](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/dataset-datatable-dataview/adding-datarelations)
* Content Source: [docs/framework/data/adonet/dataset-datatable-dataview/adding-datarelations.md](https://github.com/dotnet/docs/blob/master/docs/framework/data/adonet/dataset-datatable-dataview/adding-datarelations.md)
* Product: **dotnet-framework**
* GitHub Login: @douglaslMS
* Microsoft Alias: **douglasl**

**Comment by douglaslMS** [comment]
@Protiguous What would you expect to see in a longer C# example? The article provides a good, short C# example of creating a DataRelation. Any further examples are going to look almost identical.

**Comment by douglaslMS** [comment]
@Protiguous Help me understand what you're looking for in a longer example of adding a DataRelation. FYI I'll be away for two weeks so it will be a while before I comment again.

**Comment by Protiguous** [comment]
Thanks.
