### ISSUE TITLE
Broken link to "Default WPF Themes"

### ISSUE THREAD

**Issue by jstefanelli** [dotnet/docs#7408]
http://go.microsoft.com/fwlink/?LinkID=158252 is broken (redirects to archive.msdn.microsoft.com)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2271374f-b0a0-c7f6-121f-3b56f4d140ec
* Version Independent ID: 12639a1d-ef4e-86d8-bab6-43fe83425eb2
* Content: [Control Styles and Templates](https://docs.microsoft.com/en-us/dotnet/framework/wpf/controls/control-styles-and-templates)
* Content Source: [docs/framework/wpf/controls/control-styles-and-templates.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/controls/control-styles-and-templates.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks for your feedback @jstefanelli. @sambent is there a good replacement for this link?

**Comment by mairaw** [comment]
Actually, I found an old issue reporting the same problem, so I'll be closing this one as duplicate.

**Comment by mairaw** [comment]
Duplicate of #6831
