### ISSUE TITLE
Missing WebHttpBinding binding features

### ISSUE THREAD

**Issue by johnye2e** [dotnet/docs#7417]
WebHttpBinding is missing from the second table (Binding Features)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 684169cb-54a5-7351-3f62-2375fac8a73d
* Version Independent ID: 100e1821-3d93-6f8d-fe33-d58b0b5e87d1
* Content: [Configuring System-Provided Bindings](https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/configuring-system-provided-bindings)
* Content Source: [docs/framework/wcf/feature-details/configuring-system-provided-bindings.md](https://github.com/dotnet/docs/blob/master/docs/framework/wcf/feature-details/configuring-system-provided-bindings.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
Thanks for pointing out that WebHttpBinding is missing from the second table, @johnye2e. We've added it to the backlog.

**Comment by Niladri24dutta** [comment]
@rpetrusha I would like to work on this, but I have some doubt regarding the default transport mode,duplex mode for `WebHttpBinding`. Can you help me to find the correct reference for `WebHttpBinding` to look for these informations.
