### ISSUE TITLE
Broken sample code links.

### ISSUE THREAD

**Issue by dwhipps** [dotnet/docs#7418]
Broken sample code links. Broken sample code links everywhere!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9da5474c-bcac-8de8-b0ec-9d9e8f2bd22a
* Version Independent ID: 6c809d60-8df1-61e6-ae67-47c7f0c08536
* Content: [Walkthrough: Hosting WPF Content in Win32](https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/walkthrough-hosting-wpf-content-in-win32)
* Content Source: [docs/framework/wpf/advanced/walkthrough-hosting-wpf-content-in-win32.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/advanced/walkthrough-hosting-wpf-content-in-win32.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Yes, unfortunately when they shut down the archive site, the links in the docs weren't updated. A lot of the WPF samples were migrated to https://github.com/Microsoft/WPF-Samples. I think I found the right replacement and I've updated that FwLink. Thanks for letting us know @dwhipps!
