### ISSUE TITLE
Document exit code values for ngen.exe

### ISSUE THREAD

**Issue by tscott98** [dotnet/docs#7419]
It would be helpful to document whether ngen.exe sets an EXIT CODE upon termination or not, and if the exit code has any meaning.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 085ecaf8-233f-82eb-c564-b05137c899b9
* Version Independent ID: e2088737-ec20-b083-0a26-c041003d12dd
* Content: [Ngen.exe (Native Image Generator)](https://docs.microsoft.com/en-us/dotnet/framework/tools/ngen-exe-native-image-generator)
* Content Source: [docs/framework/tools/ngen-exe-native-image-generator.md](https://github.com/dotnet/docs/blob/master/docs/framework/tools/ngen-exe-native-image-generator.md)
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by mairaw** [comment]
Thanks for your feddback @tscott98. @noahfalk is this something your team can help with?

**Comment by noahfalk** [comment]
Adding @sergiy-k

**Comment by impr0t** [comment]
Came here specifically for this. Can we please get documentation on exit codes? @noahfalk @sergiy-k

**Comment by noahfalk** [comment]
Adding some folks on the .NET team who may know who is tending to ngen.exe these days? 
@fadimounir @davidwrighton @nattress 

(@sergiy-k has since left the team)
