### ISSUE TITLE
EF Core Tools Not Updating

### ISSUE THREAD

**Issue by markolbert** [dotnet/docs#7422]
I have a newly-created ASPNet Core v2.1 app which includes a separate project for an EF Core 2.1 SqlServer database.

When I run dotnet ef commands, I get a warning that I'm using an outdated version of the ef core tools (2.1.1-rtm-30846). There is no global.json file in my solution directory. I've installed the latest Net Core SDK 2.1. Why am I still getting this warning message? How do I get rid of it?

**Comment by markolbert** [comment]
The first link you provided ("here (second one)") took me to an Office Xml page. I don't think that's what you meant, but, in any event, I didn't see anything pertaining to the problem I encountered.

Yes, I followed the instructions in the migration/20-21 link.

Here is the csproj file for the project containing the EF Core context definition and migrations (apologies for not including it in the initial post):

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <ApplicationIcon />
    <OutputType>Library</OutputType>
    <StartupObject />
    <RuntimeFrameworkVersion>2.1.3</RuntimeFrameworkVersion>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="..\sharedsettings.json" Link="sharedsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="2.1.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.1.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="2.0.0" PrivateAssets="All" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.1.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="2.1.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="2.1.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="2.1.1" />
  </ItemGroup>

</Project>

```

**Comment by mairaw** [comment]
Argh, working on too many things. Fixed the link now. It should have been https://docs.microsoft.com/en-us/dotnet/core/tools/global-json#troubleshooting-build-warnings.

**Comment by markolbert** [comment]
No worries. I appreciate all you folks are doing to move things forward, and patch bugs...even if I sometimes run afoul of them :)

Here's the exact warning I'm getting (should've included this in the original post, too):

> The EF Core tools version '2.1.1-rtm-30846' is older than that of the runtime '2.1.2-rtm-30932'. Update the tools for the latest features and bug fixes.

However, I just noticed that depending upon how I invoke the migration tool, I either get or don't get the warning. Let me explain.

My solution holds two projects, RideMonitorSite (which is an AspNetCore website) and RideMonitorDb (which defines the SqlServer database used by RideMonitorSite and, eventually, some other related projects).  Schematically:

Solution
    RideMonitorDb
    RideMontiorSite

The template I used to create RideMonitorSite was the VS2017 one that uses RazorPages (i.e., the new default). I had it set up identity/authentication using a SqlServer database, so the template created an EF Core datacontext within the AspNetCore project. I then deleted this database stuff and created the separate RideMonitorDb project, which I referenced from within RideMonitorSite.

I also cleaned up the csproj file for RideMonitorServer, eliminating the tooling reference. It now looks like this:

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <RuntimeFrameworkVersion>2.1.3</RuntimeFrameworkVersion>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="..\sharedsettings.json" Link="sharedsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.1.3" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RideMonitorDb\RideMonitorDb.csproj" />
  </ItemGroup>

</Project>

```
If I run the EF Core tooling from within the RideMonitorDb project, no warning is generated.

If I run the tooling from within the RideMonitorSite project, the warning is generated.

In checking the status of Microsoft.AspNetCore.App in NuGet, I noticed that it is installed as 2.1.1. There are more recent versions (2.1.2, 2.1.3) shown in the Version dropdown, but they're greyed out because they're "blocked by project".

Which is really confusing because I thought the RuntimeFrameworkVersion entry in the csproj file was the way to remove that block.

Comments or suggestions?

**Comment by markolbert** [comment]
I just tried manually specifying version 2.1.3 on the Microsoft.AspNetCore.App PackageReference entry, and that didn't work. But now, after removing an explicit version, I have a yellow/black exclamation warning in the dependencies related to Microsoft.AspNetCore.App.

**Comment by markolbert** [comment]
Hmm, restarting VS made the warning icons go away. But I still get that warning if I run the tools from within the AspNetCore project.

**Comment by divega** [comment]
@markolbert @mairaw from what I remember this is a known issue we discovered with the patch. The guidance is to ignore the warning. However I can't remember how/if this was documented. 

cc @ajcvickers, @bricelam and @natemcmaster, in case on of them can point us somewhere.

**Comment by markolbert** [comment]
Okay, fair enough. It is just a warning, after all :). Although I have to admit I'm curious as to what's causing the problem. 

I'm fine with closing this as an issue if you want.

**Comment by natemcmaster** [comment]
This is a known issue in 2.1.3. See https://github.com/aspnet/Home/releases/tag/2.1.3#known-issues

**Comment by mairaw** [comment]
Thanks @natemcmaster. Closing this issue then.

**Comment by markolbert** [comment]
BTW, the second workaround in the link -- update the version to 2.1.3 -- does not work. The warning still appears. You might want to update the release notes re: known issues.
