### ISSUE TITLE
HttpMessageHandler description typo

### ISSUE THREAD

**Issue by breyed** [dotnet/docs#7429]
> HttpMessageHandler - A simple to class to derive from that supports the most common requirements for most applications.

Intended as "A simple class to derive from..."?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3caad5a-9fd8-ad87-b411-96d8a1b75585
* Version Independent ID: f8f9eb44-41a7-86ca-3146-60ccad61e35e
* Content: [HttpMessageHandler Class (System.Net.Http)](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpmessagehandler?view=netcore-2.0)
* Content Source: [xml/System.Net.Http/HttpMessageHandler.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Http/HttpMessageHandler.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by BillWagner** [comment]
Thanks for pointing this out @breyed 
We've added this to our backlog.
