### ISSUE TITLE
Visual Basic compiler error and warning numbers should be listed in one place

### ISSUE THREAD

**Issue by Crono1981** [dotnet/docs#7431]
It would kind of be useful. :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae1d424b-3af3-79ad-d782-b1886027fc3c
* Version Independent ID: d56626d1-8885-b7ca-4417-fe2d6dde438f
* Content: [-nowarn](https://docs.microsoft.com/en-us/dotnet/visual-basic/reference/command-line-compiler/nowarn)
* Content Source: [docs/visual-basic/reference/command-line-compiler/nowarn.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/reference/command-line-compiler/nowarn.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
Thanks for your comment, @Crono1981.  
Typically, warnings are suppressed on a warning-by-warning basis after the compiler emits a warning but the developer chooses to ignore it. In that case, the compiler output provides the warning number.
That said, it's difficult to determine from the documentation what Visual Basic error and warning numbers are. I've renamed your issue, added it to the backlog, and added it to the compiler and community contributors projects.

**Comment by Praveen-Rai** [comment]
To add my vote to the request, i have a scenario where i am building an analyzer and using in-process build with the help of roslyn apis. For CS i have referenced https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/ to get the ids which i need. A similar doc for VB would be much appreciated.
