### ISSUE TITLE
Exception: Cannot find resource named 'nameItemTemplate'. Resource names are case sensitive.

### ISSUE THREAD

**Issue by tapiov** [dotnet/docs#7439]
Hello,

On last build & launch, I get the following exception:
--------------
System.Windows.Markup.XamlParseException: ''Provide value on 'System.Windows.StaticResourceExtension' threw an exception.' Line number '38' and line position '55'.'

Exception: Cannot find resource named 'nameItemTemplate'. Resource names are case sensitive.
--------------

nameItemTemplate is found in two places within solution

1)
        <ListBox Name="peopleListBox" Grid.Column="1" Grid.Row="2" 
         ItemsSource="{Binding Source={StaticResource ExpenseDataSource}, XPath=Person}"
         ItemTemplate="{StaticResource nameItemTemplate}">
        </ListBox>

2)

           
            <DataTemplate x:Key="nameItemTemplate">
                <Label Content="{Binding XPath=@Name}"/>
            </DataTemplate>

Both within ExpenseITHome.xaml

The exception points to ExpenseITHome.xaml.cs, line 25, which reads 

       public ExpenseITHome()
        {
            InitializeComponent();  // This is line 25
        }

Commenting out InitializeComponent(); makes the application work. Is there a point in the tutorial where this Initialize line is changed/removed? Did I just miss it? Why does the error occur?

As a side note: I really don't like editing lines and lines of axml code, readability is poor, structuring is poor etc. I am hoping that I can build these in Designer (or in Blend) and the code the main operation to .cs.

Thanks,

Tapio Valli

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0dc39f7-b153-a46c-3b88-07c8ed2c71bc
* Version Independent ID: 78a14535-9703-e2af-4451-783a7c4c10be
* Content: [Create a WPF application in Visual Studio](https://docs.microsoft.com/en-us/dotnet/framework/wpf/getting-started/walkthrough-my-first-wpf-desktop-application)
* Content Source: [docs/framework/wpf/getting-started/walkthrough-my-first-wpf-desktop-application.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/getting-started/walkthrough-my-first-wpf-desktop-application.md)
* Product: **dotnet-framework**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by BlaiseRienzo** [comment]
Make sure the <Grid.Resources> section is the first item under <Grid>, or at least before any of the controls on the grid.

**Comment by magiczyf** [comment]
great! it really works
