### ISSUE TITLE
Zero clue as to what's going on.

### ISSUE THREAD

**Issue by zizuke** [dotnet/docs#7443]
I came from https://docs.microsoft.com/en-us/dotnet/csharp/quick-starts/interpolated-strings?tutorial-step=2 to here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de53e91d-edee-d4db-a731-b7ad9677cf9c
* Version Independent ID: bcee3fe6-8e5e-38f9-173b-2595b08c827a
* Content: [get (C# Reference)](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/get)
* Content Source: [docs/csharp/language-reference/keywords/get.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/get.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by pkulikov** [comment]
@zizuke could you please provide more information about how you've got to this page. The [source page](https://github.com/dotnet/docs/blob/master/docs/csharp/quick-starts/interpolated-strings.yml) of the interpolated strings quickstart doesn't contain the link to the [get keyword](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/get) page.

**Comment by BillWagner** [comment]
Closing as not actionable.
