### ISSUE TITLE
UUID version

### ISSUE THREAD

**Issue by pappasa** [dotnet/docs#7449]
Does NewGuid() produce a UUID version 4 according to RFC4122?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63c02116-1b9d-69f5-7446-76e2f756207f
* Version Independent ID: 2c3d5439-e4d0-fcf1-dbb1-b5cf14abfdd7
* Content: [Guid.NewGuid Method (System)](https://docs.microsoft.com/en-us/dotnet/api/system.guid.newguid?view=netframework-4.7.2)
* Content Source: [xml/System/Guid.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System/Guid.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by BillWagner** [comment]
@karelz Do you know who can answer this question?

**Comment by BillWagner** [comment]
Thanks for raising this issue @pappasa We've investigating the correct answer.

**Comment by karelz** [comment]
@pappasa version 4 seems to defined as "randomly or pseudo-randomly generated version". That's what `NewGuid` does. Did you check the bits in the output?

What is motivation for your question? Confirmation that the number is randomly/pseudo-randmly generated? Or do you need to know how exactly?

**Comment by pappasa** [comment]
Yes, I checked the bits in the output, and it seems to produce version 4. But will it **allways** produce version 4 UUIDs, even if I call it a trillion times?

**Comment by karelz** [comment]
That sounds more like implementation question - check the soruce code: https://github.com/dotnet/corefx#useful-links
* .NET Framework calls Windows API: https://referencesource.microsoft.com/#mscorlib/system/guid.cs,b7fae6994c22c22e
* .NET Core:
    * Also calls Windows API: https://source.dot.net/#System.Private.CoreLib/shared/System/Guid.Windows.cs,b7fae6994c22c22e
    * Calls some Unix API: https://github.com/dotnet/coreclr/blob/master/src/System.Private.CoreLib/shared/System/Guid.Unix.cs
        * https://github.com/dotnet/coreclr/blob/030a3ea9b8dbeae89c90d34441d4d9a1cf4a7de6/src/System.Private.CoreLib/shared/Interop/Unix/System.Native/Interop.GetRandomBytes.cs#L17-L20
        * etc.

For context: UUID versions: https://tools.ietf.org/html/rfc4122#section-4.1.3

**Comment by karelz** [comment]
That sounds more like implementation question - check the soruce code: https://github.com/dotnet/corefx#useful-links
* .NET Framework calls Windows API: https://referencesource.microsoft.com/#mscorlib/system/guid.cs,b7fae6994c22c22e
* .NET Core:
    * Also calls Windows API: https://source.dot.net/#System.Private.CoreLib/shared/System/Guid.Windows.cs,b7fae6994c22c22e
    * Calls some Unix API: https://github.com/dotnet/coreclr/blob/master/src/System.Private.CoreLib/shared/System/Guid.Unix.cs
        * https://github.com/dotnet/coreclr/blob/030a3ea9b8dbeae89c90d34441d4d9a1cf4a7de6/src/System.Private.CoreLib/shared/Interop/Unix/System.Native/Interop.GetRandomBytes.cs#L17-L20
        * etc.

For context: UUID versions: https://tools.ietf.org/html/rfc4122#section-4.1.3

**Comment by pappasa** [comment]
*   .NET Framework calls Windows API: https://referencesource.microsoft.com/#mscorlib/system/guid.cs,b7fae6994c22c22e

-> Guid.NewGuid calls Win32Native<https://referencesource.microsoft.com/mscorlib/microsoft/win32/win32native.cs.html#619db4d994b020d5>.CoCreateGuid<https://referencesource.microsoft.com/mscorlib/microsoft/win32/win32native.cs.html#78204c597ae067fb> not documented if Variant 2, Version 4.

  *   .NET Core:
     *   Also calls Windows API: https://source.dot.net/#System.Private.CoreLib/shared/System/Guid.Windows.cs,b7fae6994c22c22e

-> Guid.NewGuid calls Interop<https://source.dot.net/System.Private.CoreLib/P/0c5afec88b013285.html#0c5afec88b013285>.Ole32<https://source.dot.net/System.Private.CoreLib/shared/Interop/Windows/Ole32/Interop.CoCreateGuid.cs.html#8107506c279e441c>.CoCreateGuid<https://source.dot.net/System.Private.CoreLib/shared/Interop/Windows/Ole32/Interop.CoCreateGuid.cs.html#ee111d9e318539d6> not documented if Variant 2, Version 4.

     *   Calls some Unix API: https://github.com/dotnet/coreclr/blob/master/src/System.Private.CoreLib/shared/System/Guid.Unix.cs

-> Guid.NewGuid calls Interop.GetRandomBytes, and sets the bits for Variant 2, Version 4.


Therefore from the above, we know that .NET CORE Guid.New Guid on Unix produces Variant 2, Version 4. On Windows we do not know if Guid.NewGuid produces Variant 2, Version 4.

**Comment by xneoron** [comment]
Guid  may be duplicate or never ?

**Comment by karelz** [comment]
Good question for the underlying OS APIs. AFAIK they use MAC address + current time, which makes it fairly unique for normal purposes when you are not generating GUIDs in a tight loop.

The original question seems to be as answered as it can be, closing.

**Comment by xneoron** [comment]
> Good question for the underlying OS APIs. AFAIK they use MAC address + current time, which makes it fairly unique for normal purposes when you are not generating GUIDs in a tight loop.
> 
> The original question seems to be as answered as it can be, closing.
current time use milliseconds or nanosecond  it very difficult to duplicate and i can use lock thread prevent duplicates, maybe that right ?

**Comment by karelz** [comment]
@xneoron you're asking about OS implementation details. The best option IMO is to try it out and see if it is a problem at all.

**Comment by evanjmg** [comment]
It doesn't  - it's not lowercase

**Comment by ef-computas** [comment]
This question has not been given a clear answer.  The question is whether Guid.NewGuid() produces a UUID compliant with RFC4122. 

Since a random UUID compliant with RFC4122 cannot collide with other types of RFC4122, because the version or variant field is always set differently, this would be useful to know.
