### ISSUE TITLE
Timeouts

### ISSUE THREAD

**Issue by jiimaho** [dotnet/docs#7450]
"SendTimeout, OpenTimeout, CloseTimeout are the same as on the client."
Does this mean that they *should* be the same as on the client, or that setting them on the service has no value, since they will inherit them from the client anyway? The .NET SDK is very unclear, since the binding classes are the same for client/service.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0aefcf53-3c9e-b92c-2415-6be6777718ae
* Version Independent ID: 4c953f5d-43eb-6710-f7b4-4b437f94a05e
* Content: [Configuring Timeout Values on a Binding](https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/configuring-timeout-values-on-a-binding)
* Content Source: [docs/framework/wcf/feature-details/configuring-timeout-values-on-a-binding.md](https://github.com/dotnet/docs/blob/master/docs/framework/wcf/feature-details/configuring-timeout-values-on-a-binding.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by bkstill** [comment]
I agree the "SendTimeout, OpenTimeout, CloseTimeout are the same as on the client" statement is ambiguous. I have the same question.

**Comment by tanveerbadar** [comment]
That can easily be tested by setting different values on client and server side. All it comes down to is whether a wording change is needed or not.
