### ISSUE TITLE
Formatting issue in Related Resources for Introduction to LINQ in Visual Basic

### ISSUE THREAD

**Issue by mattarnster** [dotnet/docs#7459]
Hello,

There is a missing bracket in the markdown formatting in this page's Related Resources section.
`[LINQ to Objects]../../concepts/linq/linq-to-objects.md)`
Should be
`[LINQ to Objects](../../concepts/linq/linq-to-objects.md)`

Regards,
Matt

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca3752a4-ccb3-a26f-7424-f7508234aa0e
* Version Independent ID: ed640711-0e9b-4d71-da19-9bc1d06335aa
* Content: [Introduction to LINQ in Visual Basic](https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/language-features/linq/introduction-to-linq)
* Content Source: [docs/visual-basic/programming-guide/language-features/linq/introduction-to-linq.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/programming-guide/language-features/linq/introduction-to-linq.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by pkulikov** [comment]
@mattarnster thanks for reporting the issue. If you want you can create the pull request with the fix. See [this guide](https://docs.microsoft.com/en-us/contribute/#quick-edits-to-existing-documents) for the description how to do that.
