### ISSUE TITLE
Minor typos in DispatcherTimer Class remarks

### ISSUE THREAD

**Issue by RichardD2** [dotnet/docs#7461]
One small typo in the remarks:

> If a System.Timers.Timer is used in a WPF application, it is worth noting that the System.Timers.Timer runs on a different thread **then** the user interface (UI) thread.

Should be _"than"_, not _"then"_.

Also, a missing word in the same paragraph:

> Reasons for using a DispatcherTimer **opposed to** a System.Timers.Timer

Should be _"as opposed to"_.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5300b6ad-c347-7fb0-cede-88e6a3fa4eaf
* Version Independent ID: 651e166b-c162-8b22-9699-e4f8a8a6ef0b
* Content: [DispatcherTimer Class (System.Windows.Threading)](https://docs.microsoft.com/en-gb/dotnet/api/system.windows.threading.dispatchertimer?view=netframework-4.7.2)
* Content Source: [xml/System.Windows.Threading/DispatcherTimer.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Windows.Threading/DispatcherTimer.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks for reporting this issue @RichardD2 and @briandunnington for jumping on this issue to fix it. 

@RichardD2 also when you find issues like that, making quick edits should be easy if you'd like to contribute to our docs.

See https://docs.microsoft.com/en-us/contribute/#quick-edits-to-existing-documents for more information.
