### ISSUE TITLE
Bug in ValueObject.Equals(obj)?

### ISSUE THREAD

**Issue by ZUNNm1Xlwk** [dotnet/docs#7477]
The current example implementation of the ValueObject.Equals(obj) method returns true for different objects in the following case:
The GetAtromicValues() of the current ValueObject returns 2 objects. The GetAtromicValues() of the ValueObject in the Equals parameter returns 1 object (equal to the first of the current ValueObject).
Nevertheless the count of objects is different the result of an Equals(...) returns true. This is odd.
I fixed this in my code by converting the GetAtomicValues() results to lists and comparing the count of these lists. This is of course not very high performance for huge atomic value collections...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70b14bbb-dc66-f1a2-8b14-39ef3b4bde1d
* Version Independent ID: cf912666-9ad3-1673-8f69-6bf52c034ef9
* Content: [Implementing value objects](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/implement-value-objects#feedback)
* Content Source: [docs/architecture/microservices/microservice-ddd-cqrs-patterns/implement-value-objects.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/microservice-ddd-cqrs-patterns/implement-value-objects.md)
* Product: **dotnet**
* Technology: **dotnet-ebooks**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by hackked** [comment]
I also ran into this bug in a project.  It would be great to get the example updated.  If the objects are identical with the exception of either object having exactly one additional atomic value, the objects will still be considered equal.  Saving the result of the MoveNext() calls to a local variable can work around the problem and not require a ToList() on the GetAtomicValues() calls.

**Comment by mvelosop** [comment]
Hi @ZUNNm1Xlwk, @hackked, thanks for the feedback?

Well... no doubt you're both right!

Would some of you like to contribute a PR to [eShopOnContainers repo](https://github.com/dotnet-architecture/eShopOnContainers/pulls/) to fix this?

Thanks,
