### ISSUE TITLE
Logical error in code

### ISSUE THREAD

**Issue by SEHellFire** [dotnet/docs#7481]
' Don't do anything if the form's handle hasn't been created 
        ' or the form has been disposed.
        If (Not Me.IsHandleCreated And Not Me.IsDisposed) Then Return

The last line should be:

 If (Not Me.IsHandleCreated Or Me.IsDisposed) Then Return

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 405c17f3-a60d-4726-46ad-8958b25f1202
* Version Independent ID: 60b8e233-c59c-4e6f-aab5-45d7b0a06314
* Content: [MethodInvoker Delegate (System.Windows.Forms)](https://docs.microsoft.com/de-de/dotnet/api/system.windows.forms.methodinvoker?view=netframework-4.7.2)
* Content Source: [xml/System.Windows.Forms/MethodInvoker.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Windows.Forms/MethodInvoker.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks for reporting this issue @SEHellFire. @briandunnington has already jumped in on the issue and submitted a PR to fix this! Thanks Brian!
