### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by tombrown571** [dotnet/docs#7485]
The link to the Sample is broken   (archive.msdn.microsoft.com’s server IP address could not be found.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 278577af-89ab-c813-24e1-175a7b986b57
* Version Independent ID: 45394d15-a85d-95c1-c662-86a00f7ed4b7
* Content: [IDataObject.GetData Method (System.Windows)](https://docs.microsoft.com/en-us/dotnet/api/system.windows.idataobject.getdata?view=netframework-4.7.2#System_Windows_IDataObject_GetData_System_String_System_Boolean_)
* Content Source: [xml/System.Windows/IDataObject.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Windows/IDataObject.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks for reporting the issue @tombrown571. This has now been fixed!
