### ISSUE TITLE
Grouping by numeric range

### ISSUE THREAD

**Issue by johnnyagerard** [dotnet/docs#7487]
'Note also in the group clause that to avoid a "divide by zero" exception...'

I don't see how there would be any division by zero in the example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 781a32e0-448c-2ca7-649f-5bf181302ec3
* Version Independent ID: a3aa9b7d-0cc1-778d-b01b-6bedcd80799b
* Content: [group clause (C# Reference)](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/group-clause)
* Content Source: [docs/csharp/language-reference/keywords/group-clause.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/group-clause.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Your comment is correct @johnnyagerard The `avg` variable is only used as the numerator in the sample.  That sentence should be removed. The conditional can also be simplified to a simple assignment to `avg / 10`. 

I've added this to our backlog, and added the **up-for-grabs** label, if you'd like to submit a PR for the fix.
