### ISSUE TITLE
comment

### ISSUE THREAD

**Issue by johnnyagerard** [dotnet/docs#7488]
```csharp
// Create a delicious data source.
```
Thanks for this hilarious comment.
And by the way, how dare you put "apple" in your 'fruits' array?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3ca9ce1-c0c4-e919-31bd-47906a080351
* Version Independent ID: c772e0b2-8c4d-ef10-57a4-a481b7385b6e
* Content: [orderby clause (C# Reference)](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/orderby-clause)
* Content Source: [docs/csharp/language-reference/keywords/orderby-clause.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/orderby-clause.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for the comment @johnnyagerard 

We're glad you enjoyed the sample.

Closing as kudos.
