### ISSUE TITLE
Needs updating to include .NET Core 2.1 HttpClientFactory

### ISSUE THREAD

**Issue by rcollette** [dotnet/docs#7489]
Additionally, I have not seen much documentation that includes the method encapsulated HttpClient configuration pattern whose DI setup looks like.
'''
services.AddHttpClient&lt;IMyService, MyServiceImplementation>( configuration => ...)
'''

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bfcc1a8-ddda-810c-17b0-56a506045d67
* Version Independent ID: 5415878b-e60b-5433-7b4b-efc8259908f0
* Content: [Create a REST client using .NET Core](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/console-webapiclient)
* Content Source: [docs/csharp/tutorials/console-webapiclient.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/console-webapiclient.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for raising this issue @rcollette 

I've added this to our backlog for the next update to this sample.

**Comment by garfbradaz** [comment]
Any news on this Bill?

**Comment by wadebee** [comment]
For those of us behind corporate firewalls it would be helpful to include a discussion about proxy handling including examples of setting up the WebProxy and HttpClientHandler classes needed.

**Comment by cornel001** [comment]
For anybody who has trouble with proxy: This worked for me: Replace:
private static readonly HttpClient client = new HttpClient();
with
private static readonly HttpClientHandler handler = new HttpClientHandler
	{
			DefaultProxyCredentials = System.Net.CredentialCache.DefaultNetworkCredentials
	};
private static readonly HttpClient client = new HttpClient(handler);

**Comment by rcollette** [comment]
@dotnet/docs - This issue was not addressed and I still believe it is an important feature to document.

**Comment by scottaddie** [comment]
@rcollette Have you already read the following doc?

https://docs.microsoft.com/aspnet/core/fundamentals/http-requests

The doc contains some examples of calls to `AddHttpClient`.

**Comment by rcollette** [comment]
Yeah that suffices @scottaddie.   Thank you for responding.

**Comment by BillWagner** [comment]
Thanks @Scottaddie.

@rcollette We'll leave this closed, as addressed.
