### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by DonisMarshall** [dotnet/docs#7495]
I have an urgent need for some correct documentation on Enhanced Strong Names.  Here is the Microsoft article on Enhanced Strong Names:

https://docs.microsoft.com/en-us/dotnet/framework/app-domains/enhanced-strong-naming

It absolutely does not work. 

•	Signing with or without Key Migration does not work.  
•	The explanation of counter-signatures is incomplete.

When creating an Enhanced Strong name per the instructions, you get errors about an improper counter-signature. 

Donis Marshall - donis@mindspring.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 946a1a37-3aed-cf2e-4f44-5e0cb9bc498c
* Version Independent ID: 8977ace2-64e8-cae8-40f9-a207a17c2107
* Content: [Enhanced Strong Naming](https://docs.microsoft.com/en-us/dotnet/framework/app-domains/enhanced-strong-naming)
* Content Source: [docs/framework/app-domains/enhanced-strong-naming.md](https://github.com/dotnet/docs/blob/master/docs/framework/app-domains/enhanced-strong-naming.md)
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by mairaw** [comment]
@karelz @GrabYourPitchforks any suggestions on who could help with this?

**Comment by karelz** [comment]
@bartonjs might know (or Levi)
