### ISSUE TITLE
What if the key doesn't exist?

### ISSUE THREAD

**Issue by skst** [dotnet/docs#7499]
From the documentation, it's not clear to me what happens if the key doesn't exist in the collection? Nothing? Exception? Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4145e15d-d31f-6670-3ca2-9bde3b39d444
* Version Independent ID: a62534f3-398f-91f2-25d1-78b0a957c999
* Content: [KeyValueConfigurationCollection.Remove(String) Method (System.Configuration)](https://docs.microsoft.com/en-us/dotnet/api/system.configuration.keyvalueconfigurationcollection.remove?view=netframework-4.7.2)
* Content Source: [xml/System.Configuration/KeyValueConfigurationCollection.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Configuration/KeyValueConfigurationCollection.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mgroves** [comment]
I just submitted a PR to add a quick sentence. The base class is able to throw exceptions, but that functionality is encapsulated away in this implementation, so Remove will not do anything if an object by the given key is not found.

**Comment by rpetrusha** [comment]
@mgroves, you've opened a PR to merge to master of your own repository, not ours.

**Comment by mgroves** [comment]
@rpetrusha well that's embarrassing. Anyway, I think I did it correct this time :)
