### ISSUE TITLE
Observation on "Generalized async return types"

### ISSUE THREAD

**Issue by clperez** [dotnet/docs#7506]
Hi. On the following example

public ValueTask&lt;int&gt; CachedFunc()
{
    return (cache) ? new ValueTask&lt;int&gt;(cacheResult) : new ValueTask&lt;int&gt;(LoadCache());
}
private bool cache = false;
private int cacheResult;
private async Task&lt;int&gt; LoadCache()
{
    // simulate async work:
    await Task.Delay(100);
    cacheResult = 100;
    cache = true;
    return cacheResult;
}

Shouldn't cache and cacheResult variable be accesses through some kind of barrier like Volatile or interlocked? 

They are being written and read from different threads... right? 

Regards.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc229b53-a548-4ef8-86b9-58670a81344a
* Version Independent ID: aeb15230-e1cc-df50-7edb-fb50164e13be
* Content: [What's New in C# 7.0 - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-7)
* Content Source: [docs/csharp/whats-new/csharp-7.md](https://github.com/dotnet/docs/blob/master/docs/csharp/whats-new/csharp-7.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @clperez 

The sample could be structured better to ensure that `LoadCache` is only called once. I've added this to our backlog to be addressed as part of updating the async articles
