### ISSUE TITLE
New doc: Pipelines

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/docs#7516]
Moved from https://github.com/aspnet/Docs/issues/5521

See https://github.com/aspnet/KestrelHttpServer/issues/1980 and [Bedrock update](https://github.com/aspnet/KestrelHttpServer/issues/1980#issuecomment-377123245)
Document the lower layers. 
The transports

@KPixel wrote

The outline/TOC could be as in the [tutorial](https://github.com/KPixel/Prototypes/tree/master/Pipelines):

1. Link to learn about the primitives Span and Memory
2. Introduction to the Pipe class
3. Simple Pipe sample
4. The Receive() loop
5. Pipes in ASP.NET Core 2.1
6. Introducing IDuplexPipe
7. Creating a pair of DuplexPipes
8. Duplex Connection

Considering how advanced certains sections can get, I don't know if we should split this into many articles (now), or leave it as-is (and refactor later as the extra advanced topics get covered).

More fundamentally, I think this doc belongs in the .NET doc. Probably next to the doc for Span/Memory 

Here is the issue tracking the doc for Span: https://github.com/dotnet/docs/issues/4400

**Comment by KPixel** [comment]
Pipelines article on the official .NET blog:
https://blogs.msdn.microsoft.com/dotnet/2018/07/09/system-io-pipelines-high-performance-io-in-net/

The original specs from the lab:
https://github.com/dotnet/corefxlab/blob/master/docs/specs/pipelines.md
https://github.com/dotnet/corefxlab/blob/master/docs/specs/pipelines-io.md

Another in-depth article:
https://blog.marcgravell.com/2018/07/pipe-dreams-part-1.html
https://blog.marcgravell.com/2018/07/pipe-dreams-part-2.html

These articles all have different ways to approach Pipelines, so they may be useful.

**Comment by Rick-Anderson** [comment]
@KPixel 	are you still interested in writing this doc?

**Comment by Rick-Anderson** [comment]
@BillWagner 	https://github.com/KPixel/Prototypes/tree/master/Pipelines was reviewed by the PU in https://github.com/aspnet/Docs/issues/5521
Seems like a fantastic opportunity to get this great content added to the docs.

**Comment by KPixel** [comment]
> are you still interested in writing this doc?

Yes, I'm just looking for some guidance on how to move forward.
Do I make a pull request with that article as-is? (I can make some minor improvements [based on the other discussion](https://github.com/aspnet/Docs/issues/5521))
Where does it go in the overall doc?

**Comment by Rick-Anderson** [comment]
@BillWagner, @mairaw, or @rpetrusha should be able to help. Ping me back in 48 hours if you don't get a response.

**Comment by rpetrusha** [comment]
Yes, @KPixel, we'd be very interested in a topic on pipelines.  In the overall doc, it would be a child page of [Memory- and span-related types](https://docs.microsoft.com/en-us/dotnet/standard/memory-and-spans/), although that top-level article might have to be renamed.

Yes, you can open a pull request. If you want to use the article as-is with some improvements, that would be fine. Our contributor guide is [here](https://github.com/dotnet/docs/blob/master/CONTRIBUTING.md), and our style guide is [here](https://github.com/dotnet/docs/tree/master/styleguide). Let me know if you have any questions.

**Comment by KPixel** [comment]
Great. I will put this doc in [that folder](https://github.com/dotnet/docs/tree/master/docs/standard/memory-and-spans) for now.

**Comment by mairaw** [comment]
Awesome @KPixel. Open a PR once you're ready to get reviews started.

**Comment by KPixel** [comment]
@Rick-Anderson @mairaw I've opened the PR here #11347
