### ISSUE TITLE
Content Quality 

### ISSUE THREAD

**Issue by rakeshr1993** [dotnet/docs#7526]
highly standard contents.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ece1648c-e8a7-153d-a22b-350a619aa26d
* Version Independent ID: a0c9221a-cc55-4c31-4f54-0e5fbdcbce25
* Content: [Object-Oriented Programming (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/object-oriented-programming)
* Content Source: [docs/csharp/programming-guide/concepts/object-oriented-programming.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/object-oriented-programming.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by rpetrusha** [comment]
Thank you for your feedback, @rakeshr1993!
