### ISSUE TITLE
Incorrect wording

### ISSUE THREAD

**Issue by jasoncoulls** [dotnet/docs#7534]
The article states "The informational bar also provides an option to Restart Visual Studio as a DPI-aware process."....  This wording is the reverse of the truth.  This should read "The informational bar also provides an option to Restart Visual Studio as a DPI-unaware process."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43b74bf9-71c6-2559-66f7-2e17de0702ef
* Version Independent ID: 9ad214a4-3ae0-f7e6-bb89-86067d97059d
* Content: [Disable DPI-awareness in Visual Studio](https://docs.microsoft.com/en-us/dotnet/framework/winforms/disable-dpi-awareness-visual-studio)
* Content Source: [docs/framework/winforms/disable-dpi-awareness-visual-studio.md](https://github.com/dotnet/docs/blob/master/docs/framework/winforms/disable-dpi-awareness-visual-studio.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@jasoncoulls The informational bar in that sentence refers to the message that displays when VS is running as a DPI-unaware process, and gives you the option to restart as a DPI-aware process. This should be done once you're finished working in the WF Designer.

"When Visual Studio runs as a DPI-unaware process, the designer layout issues are resolved, but fonts may appear blurry. Visual Studio displays a different yellow informational message when it runs as a DPI-unaware process that says **Visual Studio is running as a DPI-unaware process. WPF and XAML designers might not display correctly.** The informational bar also provides an option to **Restart Visual Studio as a DPI-aware process**."
