### ISSUE TITLE
2nd parameter of CreateDelegete ----- L"HW, Version=1.0.0.0, Culture=neutral"

### ISSUE THREAD

**Issue by wschin** [dotnet/docs#7536]
I guess HW is the name of the assembly we're trying to load. But what do Version and Culture mean? Are they the only allowed extra information in addition to the assembly name?
On the other hand, I suggest to add GetLastError to print out the error code right after "HMODULE ret = LoadLibraryExW(coreDllPath, NULL, 0);" It took me 3 hours to find a way to get the correct error message (which is about loading 64-bit coreclr.dll in a win32 app).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83da7030-b5f1-72ad-71f6-424ff45b8b7f
* Version Independent ID: a98926cc-64ab-2911-e4b8-1eaf4573dfe4
* Content: [Hosting .NET Core](https://docs.microsoft.com/en-us/dotnet/core/tutorials/netcore-hosting)
* Content Source: [docs/core/tutorials/netcore-hosting.md](https://github.com/dotnet/docs/blob/master/docs/core/tutorials/netcore-hosting.md)
* Product: **dotnet-core**
* GitHub Login: @mjrousos
* Microsoft Alias: **mairaw**

**Comment by mjrousos** [comment]
Good feedback, @wschin. The version and culture are part of the [managed assembly name](https://docs.microsoft.com/en-us/dotnet/framework/app-domains/assembly-names). It could also include public key token or target architecture. I'll add a comment explaining that better.

Also, good suggestion to use `GetLastError`. I'll add that.
