### ISSUE TITLE
Type error

### ISSUE THREAD

**Issue by wschin** [dotnet/docs#7537]
// Extensions to probe for when finding TPA list files
wchar_t *tpaExtensions[] = {
	L"*.dll",
	L"*.exe",
	L"*.winmd"
};

This declaration is not good. To compile the code, I need to change wchar_t to "const wchar_t".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83da7030-b5f1-72ad-71f6-424ff45b8b7f
* Version Independent ID: a98926cc-64ab-2911-e4b8-1eaf4573dfe4
* Content: [Hosting .NET Core](https://docs.microsoft.com/en-us/dotnet/core/tutorials/netcore-hosting)
* Content Source: [docs/core/tutorials/netcore-hosting.md](https://github.com/dotnet/docs/blob/master/docs/core/tutorials/netcore-hosting.md)
* Product: **dotnet-core**
* GitHub Login: @mjrousos
* Microsoft Alias: **mairaw**

**Comment by rpetrusha** [comment]
Thanks, @wschin. We've added this to our backlog.
 
//cc @mjrousos, can you comment?

**Comment by mjrousos** [comment]
I'll take a look.

**Comment by mjrousos** [comment]
I see this error if using cl's `/Zc:stringStrings` option. I've fixed it and will open a PR shortly.
