### ISSUE TITLE
Incorrect example

### ISSUE THREAD

**Issue by thelazydogsback** [dotnet/docs#7540]
"or when you need to pass additional state into the task through its AsyncState property, as shown in the following example" - code does not show AsyncState example

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 050b2b8a-8b8d-c2de-f03d-b2ebb26a9c95
* Version Independent ID: 7d23f296-9a5e-ca0a-08c3-f718d0a90d94
* Content: [Task-based Asynchronous Programming](https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/task-based-asynchronous-programming)
* Content Source: [docs/standard/parallel-programming/task-based-asynchronous-programming.md](https://github.com/dotnet/docs/blob/master/docs/standard/parallel-programming/task-based-asynchronous-programming.md)
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by rpetrusha** [comment]
Thank you, @thelazydogsback, for reporting the incorrect code example. We've fixed it in PR #7546.
