### ISSUE TITLE
Remarks for Path.GetPathRoot Method has the wrong slash.

### ISSUE THREAD

**Issue by misterhaan** [dotnet/docs#7541]
The Remarks section on the Path.GetPathRoot Method document gives two examples using forward slash instead of a backslash:  "/" for absolute path on current drive, and "X:/" for relative path on a drive.  the UNC path example correctly uses backslashes.  The forward slashes should be corrected to backslashes as "\" and "X:\"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44fbcd8a-501d-6c90-9e0d-04a2d4a398f4
* Version Independent ID: d5479c65-09ad-ee9e-1581-528f4baa95d4
* Content: [Path.GetPathRoot Method (System.IO)](https://docs.microsoft.com/en-us/dotnet/api/system.io.path.getpathroot?redirectedfrom=MSDN&view=netframework-4.7.2#System_IO_Path_GetPathRoot_System_String_)
* Content Source: [xml/System.IO/Path.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.IO/Path.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
Thanks for reporting this, @misterhaan. In addition to the wrong path separator character, the documentation also errs in saying that device names are not supported. I've opened PR dotnet/dotnet-api-docs#507 to address these and other issues.
