### ISSUE TITLE
Can't find MSDN-style Socket class documentation 

### ISSUE THREAD

**Issue by petrroll** [dotnet/docs#7542]
Can't find documentation on Socket class (i.e. all members, methods, potential throws, …) only code examples. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54ee13e4-2078-cd89-81cd-165b72f41688
* Version Independent ID: 55552032-181e-9830-f3b3-8f942ca4f130
* Content: [Socket Code Examples](https://docs.microsoft.com/en-us/dotnet/framework/network-programming/socket-code-examples#feedback)
* Content Source: [docs/framework/network-programming/socket-code-examples.md](https://github.com/dotnet/docs/blob/master/docs/framework/network-programming/socket-code-examples.md)
* Product: **dotnet-framework**
* GitHub Login: @mcleblanc
* Microsoft Alias: **markl**

**Comment by petrroll** [comment]
Managed to find it here: https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.socket?view=netcore-2.1 through random walk across the docs.microsoft site. Googling didn't yield any results (tried `netcore socket class`, `.NET socket class docs`, and a few more).

**Comment by mairaw** [comment]
Thanks @petrroll. We're looking into this. When we redirected the content from MSDN, search authority should have been preserved. Different than #7548 where I could find the API on Google, I can't find this one except if I use the API browser.

**Comment by mairaw** [comment]
Our engineering team checked and Google is still indexing our multiple dotnet sitemaps. We've requested them to reindex the Socket page. Thanks!
