### ISSUE TITLE
Roslyn API reference should default to C#, not C++

### ISSUE THREAD

**Issue by Powerhelmsman** [dotnet/docs#7543]
This was created by @svick from https://github.com/MicrosoftDocs/feedback/issues/664
When I open an API reference page for a Roslyn type (e.g. Compilation), the page is shown with the C++ language selected. I think C# should be the default language and it was until recently.
I suspect this is related to the fact that API reference for Roslyn also shows C++/CX and C++/WinRT as possible languages, which I think don't make any sense for a .Net API:

Contrast this with API reference pages for .Net itself, which don't show those languages (and have C# listed first):

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0330ac55-d5c0-281b-8c2d-181ea57a1bd2
* Version Independent ID: 0d0cb4b7-7311-78b7-dd29-b8afde14c27c
* Content: [Compilation Class (Microsoft.CodeAnalysis)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.compilation?view=roslyn-dotnet)
* Content Source: [dotnet/xml/Microsoft.CodeAnalysis/Compilation.xml](https://github.com/dotnet/roslyn-api-docs/blob/live/dotnet/xml/Microsoft.CodeAnalysis/Compilation.xml)
* Product: **dotnet-roslyn-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
I've created https://github.com/dotnet/roslyn-api-docs/pull/54 to make C# the official default language.
@BillWagner which languages should we have for Roslyn API docs? The same as .NET? I believe @dend can help us configure the repo with the right languages.

**Comment by BillWagner** [comment]
I'm going to close this after merging dotnet/roslyn-api-docs#54  The other languages are supported, as these APIs are plain-old .NET APIs. C# is the correct default though.

**Comment by mairaw** [comment]
Ok, but none of our .NET APIs have those 3 C++ flavors, only one. Shouldn't they match?

**Comment by BillWagner** [comment]
Good point. Re-opening.

**Comment by mairaw** [comment]
@dend can you re-run CI for roslyn-api-docs without the extra C++ variations?

**Comment by mairaw** [comment]
This work is done now. Thanks for your help @dend! Closing.
