### ISSUE TITLE
Other ways to submit XPS content to the printer

### ISSUE THREAD

**Issue by KutanaDev** [dotnet/docs#7555]
AddJob ignores any device-specific PrintTickets contained in the XPS
But if you have device-specific xps in a Stream and copy it to a PrintQueueStream object then the PrintTickets are obeyed. This needs to be spelled out - lots of people think it's not possible to submit device-specific xps to a print queue - but it's just because they don't know about PrintQueueStream

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75ee7945-ebe0-40f3-ef1b-430e9146c02b
* Version Independent ID: 49eecbf5-bc7d-1acf-8a94-18a5653cb375
* Content: [How to: Programmatically Print XPS Files](https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/how-to-programmatically-print-xps-files)
* Content Source: [docs/framework/wpf/advanced/how-to-programmatically-print-xps-files.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/advanced/how-to-programmatically-print-xps-files.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by KutanaDev** [comment]
I should qualify this by saying that PrintTickets will be obeyed on Windows 8 and later but _not Windows 7_

**Comment by FrankLingwen** [comment]
Thanks for your great article, this is the best article I've seen and so useful, many thanks! Sometimes, when you need to print the XPS files to PDF, PS, EPS, Image or other formats, you can try with the VeryUtils XPS Print Command Line software, this is a great software to print XPS file to Windows Printer and other formats from command line and without require 3rd software, I hope it will useful to your customers.
