### ISSUE TITLE
CompareExchange with object/T should clarify use of reference equality

### ISSUE THREAD

**Issue by drewnoakes** [dotnet/docs#7556]
The documentation around CompareExchange for reference types says:

&gt; Compares two instances of the specified reference type `T` for equality and, if they are equal, replaces the first one.

Also:

&gt; If `comparand` and the value in `location1` are equal, then...

Without qualification, a reader might assume this calls the `object.Equals(object)` method to determine equality, whereas the implementation uses reference equality. The docs should clarify this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66574ed3-fe61-927f-c364-a3cf2565e9a2
* Version Independent ID: 9651cd4a-a520-66e4-8303-4eb5e62f6d81
* Content: [Interlocked.CompareExchange Method (System.Threading)](https://docs.microsoft.com/en-us/dotnet/api/system.threading.interlocked.compareexchange?view=netframework-4.7.2#System_Threading_Interlocked_CompareExchange_System_Object__System_Object_System_Object_)
* Content Source: [xml/System.Threading/Interlocked.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Threading/Interlocked.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by BillWagner** [comment]
@kouvel Can you provide insight into the right fix for this issue?
