### ISSUE TITLE
Sourced code solution please?

### ISSUE THREAD

**Issue by buttonsrtoys** [dotnet/docs#7557]
Any chance the solution for this example is available for download?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9da5474c-bcac-8de8-b0ec-9d9e8f2bd22a
* Version Independent ID: 6c809d60-8df1-61e6-ae67-47c7f0c08536
* Content: [Walkthrough: Hosting WPF Content in Win32](https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/walkthrough-hosting-wpf-content-in-win32)
* Content Source: [docs/framework/wpf/advanced/walkthrough-hosting-wpf-content-in-win32.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/advanced/walkthrough-hosting-wpf-content-in-win32.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
The source code is available in the dotnet/samples repo in GitHub at https://github.com/dotnet/samples/tree/master/snippets/cpp/VS_Snippets_Wpf/Win32HostingWPFPage/CPP. 
Since the issue has no documentation impact, I'll close it.
