### ISSUE TITLE
Minor typo

### ISSUE THREAD

**Issue by smarpug** [dotnet/docs#7562]
I believe the word "OnProgress" is mis-capitalized:
     lister.Progress += OnProgress;
Should be this, unless I'm misunderstanding?
     lister.Progress += onProgress;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e2507bc-e567-23f9-aeb9-f7529baa7032
* Version Independent ID: c42718d0-15b4-a87f-4353-e15656686889
* Content: [Introduction to Events](https://docs.microsoft.com/en-us/dotnet/csharp/events-overview)
* Content Source: [docs/csharp/events-overview.md](https://github.com/dotnet/docs/blob/master/docs/csharp/events-overview.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by rpetrusha** [comment]
No, you're not misunderstanding, @smarpug. It is a typo. Thanks for pointing it out. I've opened #7574 to correct it.
