### ISSUE TITLE
Visual Basic Guide: Decimal type is said to be not floating-point

### ISSUE THREAD

**Issue by pkulikov** [dotnet/docs#7564]
The docs of the `Decimal` data type in the Visual Basic guide should be revised, may be simplified with a lot of details being removed (instead link to `System.Decimal` API)

In particular, the [main article](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/data-types/decimal-data-type) says:
>`Decimal` is not a floating-point data type.

It's not **binary** floating-point type, but still floating-point type.

One more place with the same statement:
https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/language-features/data-types/numeric-data-types#nonintegral-numeric-types

**Comment by rpetrusha** [comment]
Thanks, @pkulikov. Would you like to address this issue yourself?

**Comment by pkulikov** [comment]
@rpetrusha no, not coming weeks.
