### ISSUE TITLE
To block format

### ISSUE THREAD

**Issue by sean-vogel** [dotnet/docs#7566]
Documentation should include the format of multiple email addresses especially in the (string, string) constructor.  What is the delimiting character?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 378befcb-4c9e-2d78-4013-26594ebf53f5
* Version Independent ID: 05d64899-1bfc-9f95-9972-9f0f1efdfb2e
* Content: [MailMessage Constructor (System.Net.Mail)](https://docs.microsoft.com/en-us/dotnet/api/system.net.mail.mailmessage.-ctor?view=netframework-4.7.2#System_Net_Mail_MailMessage__ctor_System_String_System_String_)
* Content Source: [xml/System.Net.Mail/MailMessage.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Mail/MailMessage.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
Thanks for your comment, @sean-vogel. Specifying the delimiter is an important detail that seems to be missing from the documentation.
@davidsh, is the delimiter a comma, as the [MailAddressCollection.Add](https://docs.microsoft.com/en-us/dotnet/api/system.net.mail.mailaddresscollection.add?view=netframework-4.7.2#System_Net_Mail_MailAddressCollection_Add_System_String_) method indicates?

**Comment by davidsh** [comment]
>@davidsh, is the delimiter a comma, as the MailAddressCollection.Add method indicates?

Yes.  Internally, calling `new MailMessage(from, to)` translates to this for parsing the value of the 'to' string. The string can contain multiple addresses separated by the delimiter.

https://github.com/dotnet/corefx/blob/52121c8d0376dcb0f69570e793b6d40232ccabf9/src/System.Net.Mail/src/System/Net/Mail/MailPriority.cs#L60-L62
