### ISSUE TITLE
Redundant dash "-" in the name of the article

### ISSUE THREAD

**Issue by aannenko** [dotnet/docs#7573]
Current name: "dotnet-clean"
Suggested name: "dotnet clean"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce4a4413-002d-4f6b-547d-3ac0c2cf84b8
* Version Independent ID: fad3d9a6-f1e8-7428-84cf-7895ece1efa2
* Content: [dotnet clean command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-clean?tabs=netcore2x)
* Content Source: [docs/core/tools/dotnet-clean.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-clean.md)
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by rpetrusha** [comment]
Thanks for pointing out a second confusing title, @aannenko. PR #7578 also corrects it.
