### ISSUE TITLE
Need more details

### ISSUE THREAD

**Issue by manikandantk88** [dotnet/docs#7582]
"The suspension of an async method at an await expression doesn't constitute an exit from the method, and finally blocks don’t run."

What do you mean "finally blocks don't run" here? Could you please add more details?
In below code, finally block is executed. 

        public async Task DoSomethingAsync()
        {
            Task&lt;string&gt; theTask = DelayAsync();

            try
            {
                string result = await theTask;
                Console.WriteLine("Result: " + result);
            }
            catch (Exception ex)
            {
                Console.WriteLine("Exception Message: " + ex.Message);
            }
            finally
            {
                Console.WriteLine("I am inside finally block");
            }
            Console.WriteLine("Task IsCanceled: " + theTask.IsCanceled);
            Console.WriteLine("Task IsFaulted:  " + theTask.IsFaulted);
            if (theTask.Exception != null)
            {
                Console.WriteLine("Task Exception Message: "
                    + theTask.Exception.Message);
                Debug.WriteLine("Task Inner Exception Message: "
                    + theTask.Exception.InnerException.Message);
            }
        }

        private async Task&lt;string&gt; DelayAsync()
        {
            await Task.Delay(100);

            // Uncomment each of the following lines to
            // demonstrate exception handling.

            //throw new OperationCanceledException("canceled");
            //throw new Exception("Something happened.");
            return "Done";
        }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17d27a0d-c072-8c9f-7e31-3de60bee9ae8
* Version Independent ID: e0c09794-e712-19ff-cb9f-12648d60d4f6
* Content: [Asynchronous Programming with async and await (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/)
* Content Source: [docs/csharp/programming-guide/concepts/async/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/async/index.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for raising this issue @manikandantk88 

The analysis provided by @pkulikov is correct. Language similar to that should be added to this article to better explain that finally clauses only run after all the awaited tasks have completed.

**Comment by pressacco** [comment]
IMHO: I think a fair number of developers miss the subtleties of concurrent programming (even more so with `async/await`), and they are unknowingly introducing potential race conditions / deadlocks.

To help curb this, it would be nice if the documentation included guidance on how to keep `async/await` "contained".  Once introduced, `async/await` has a way of spreading throughout the code base.
