### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by johnnygerard** [dotnet/docs#7584]
The "Certificate Stores" link is broken.

(For more information about certificate stores, see Certificate Stores.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6a828d2-3306-b5cb-4006-6e362128db76
* Version Independent ID: 98c0ddd6-cfee-6bd3-5fa2-aad775586abf
* Content: [Working with Certificates](https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/working-with-certificates)
* Content Source: [docs/framework/wcf/feature-details/working-with-certificates.md](https://github.com/dotnet/docs/blob/master/docs/framework/wcf/feature-details/working-with-certificates.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by BillWagner** [comment]
There are a number of links in addition to the "Certificate Stores" link that are being redirected to a 
"not found" page.

**Comment by mairaw** [comment]
It seems there are two broken links on that page:

- Certificate Stores - perhaps https://docs.microsoft.com/en-us/windows/desktop/secauthn/certificate-stores would be a good replacement?
- Windows Server 2008 R2 - Certificate Services - perhaps link to a more general topic about PKIs? https://docs.microsoft.com/en-us/windows/desktop/seccertenroll/public-key-infrastructure (this link is used in two topics) - @shortpatti @msatranjr would you have any suggestions about where to link for information about how to implement a PKI in Windows Server? There's also this MVA course on the subject: https://mva.microsoft.com/en-us/training-courses/windows-server-2012-r2-implementing-a-basic-pki-8419?l=qbdJhRKz_804984382

**Comment by shortpatti** [comment]
@mairaw, let me take a look at the server content to see where this content might be located :)

**Comment by mairaw** [comment]
@shortpatti did you find anything?

**Comment by shortpatti** [comment]
@mairaw, I apologize for the delay in responding.  I'll do some investigating this afternoon and I'll let you know my suggestions  :)

**Comment by shortpatti** [comment]
@mairaw, I think a good location would be in the NPS section of the server content, either in the [Plan Network Policy Server](https://docs.microsoft.com/en-us/windows-server/networking/technologies/nps/nps-plan-server) or on the [Deploy Network Policy Server](https://docs.microsoft.com/en-us/windows-server/networking/technologies/nps/nps-deploy).
