### ISSUE TITLE
Outdated MMC steps

### ISSUE THREAD

**Issue by JoelMagee** [dotnet/docs#7586]
The steps to view certificates in the MMC snap-in are slightly incorrect, at least based on my version of Management Console (3.0). Step 4 wasn't necessary, the dialog box in step 5 was different and step 9 wasn't required. I didn't follow any of the optional steps nor the IE instructions so I'm not sure if they're up to date or not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f950f479-532b-ab38-a676-653495777197
* Version Independent ID: 30fa2c1a-86bd-e683-3e6f-8a268f4dc4e5
* Content: [How to: View Certificates with the MMC Snap-in](https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/how-to-view-certificates-with-the-mmc-snap-in#feedback)
* Content Source: [docs/framework/wcf/feature-details/how-to-view-certificates-with-the-mmc-snap-in.md](https://github.com/dotnet/docs/blob/master/docs/framework/wcf/feature-details/how-to-view-certificates-with-the-mmc-snap-in.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by HappyNomad** [comment]
How is following these steps different than just running certlm.msc or certmgr.msc?

**Comment by Thraka** [comment]
@HappyNomad I don't think it is any different. The way documented here is just a more specific way of doing it. It should list both of those **.msc** files though...

**Comment by Thraka** [comment]
@JoelMagee Thank you for bringing this up. I'm adding it to the backlog.

**Comment by Thraka** [comment]
### Work
This article should be updated with the latest steps and screenshots. It should also mention how using certlm.msc or certmgr.msc can accomplish the same thing but is  just a little different.

**Comment by SamOxigen** [comment]
outdated material

**Comment by Youssef1313** [comment]
Did https://github.com/dotnet/docs/pull/10394 fix this issue?
cc: @adegeo
