### ISSUE TITLE
#HELP when using the CSI  command line C# compiler

### ISSUE THREAD

**Issue by node-student** [dotnet/docs#7591]
#HELP when using the CSI  command line C# compiler throws the CS1024  error but the compiler instructs the user to use the #HELP command to get help and it throws an error instead, is there something I need to install/add/config to get help  when using the beautiful CSI command line compiler

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff65be67-852d-a862-5f09-be4c720e005b
* Version Independent ID: f38287f8-ed77-2147-7935-a981be58dd15
* Content: [Compiler Error CS1024](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs1024)
* Content Source: [docs/csharp/misc/cs1024.md](https://github.com/dotnet/docs/blob/master/docs/csharp/misc/cs1024.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by rpetrusha** [comment]
@node-student, help is available with `-help` or `/help`, not `#help`. A leading `#` symbol indicates a preprocessor directive. 
I hope that this clears up any confusion. In the meantime, I'll close this issue.
