### ISSUE TITLE
Error 424: Object Required

### ISSUE THREAD

**Issue by M-Jow** [dotnet/docs#7593]
Using Access 2013 with the syntax described here produces a Compile Error (expected "=").
        FileSystemObject.CopyFile (strDbLocation & strLatestVer, strLocalDir & strLatestVer)
Using the following syntax produces Error 424.
        FileSystemObject.CopyFile strDbLocation & strLatestVer, strLocalDir & strLatestVer

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8587575-4f1f-31fd-c0e2-7d5451960ab1
* Version Independent ID: 87a934ee-0b4b-540b-9aa6-fb1060687d35
* Content: [How to: Create a Copy of a File in a Different Directory in Visual Basic](https://docs.microsoft.com/en-us/dotnet/visual-basic/developing-apps/programming/drives-directories-files/how-to-create-a-copy-of-a-file-in-a-different-directory?view=netframework-4.7.2)
* Content Source: [docs/visual-basic/developing-apps/programming/drives-directories-files/how-to-create-a-copy-of-a-file-in-a-different-directory.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/developing-apps/programming/drives-directories-files/how-to-create-a-copy-of-a-file-in-a-different-directory.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
Thanks for the comment, @M-Jow. Access supports Visual Basic for Applications (VBA), which is a different programming language than Visual Basic .NET, the language documented here.  I'm closing this issue as by design.

**Comment by M-Jow** [comment]
Well that was unhelpful.
