### ISSUE TITLE
How do you get the directory listing of a subdirectory?

### ISSUE THREAD

**Issue by eylvisaker** [dotnet/docs#7594]
Great example, but it only shows how to get the directory listing of the root directory on the ftp server (or the default login directory). A great addition would be show how to issue a remote "cd" command before getting the directory listing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7e276f6-b096-bb7d-fc03-f4b09a10de43
* Version Independent ID: 3d15a865-75ab-e43d-0a95-399f3db7de5a
* Content: [How to: List directory contents with FTP](https://docs.microsoft.com/en-us/dotnet/framework/network-programming/how-to-list-directory-contents-with-ftp)
* Content Source: [docs/framework/network-programming/how-to-list-directory-contents-with-ftp.md](https://github.com/dotnet/docs/blob/master/docs/framework/network-programming/how-to-list-directory-contents-with-ftp.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by belcat69** [comment]
It's very simple; just add the directory to the link that's in the example.  For example, if you want to list the contents of the directory "myExampleDirectory", then you'd change the line from:
FtpWebRequest request = (FtpWebRequest)WebRequest.Create("ftp://www.contoso.com/");
to
FtpWebRequest request = (FtpWebRequest)WebRequest.Create("ftp://www.contoso.com/myExampleDirectory/");
