### ISSUE TITLE
Return Values

### ISSUE THREAD

**Issue by zihotki** [dotnet/docs#7598]
It'd be good to also specify that `dotnet test` will return 0 if all tests were run successful and 1 if any test failed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61ca4064-7481-a263-60fc-c70127f2ad16
* Version Independent ID: 2878af44-8208-7bd8-46d4-3acda3e82ce0
* Content: [dotnet test command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-test?tabs=netcore21)
* Content Source: [docs/core/tools/dotnet-test.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-test.md)
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by BillWagner** [comment]
Thanks for the feedback @zihotki 

That would be a useful change. We've added it to our backlog. If you'd like, you can submit a PR to update this as well.
