### ISSUE TITLE
C# tutorials - serialization

### ISSUE THREAD

**Issue by stevehoag** [dotnet/docs#76]
Shows how to implement binary, XML, and SOAP serialization in C#.

Tutorials should include one or more code examples, each example should also show expected output and should include an explanation of the code where it isn't obvious. Examples shouldn't be dependent on a specific IDE or target platform.

**Comment by BethMassi** [comment]
Forget SOAP. Show JSON

**Comment by cartermp** [comment]
:+1: let's not have SOAP be a part of this.

**Comment by rtandel** [comment]
Is anybody working on this? I'm willing to do this if nobody else has already done it.

**Comment by richlander** [comment]
I'd love to see more people get involved in this project. Are you interested in contributing in general or is it this particular topic?

**Comment by rtandel** [comment]
Definitely! I'm still learning C# but I'm planning on contributing as I go along. I know a good bit of Java so it shouldn't be too long.

**Comment by richlander** [comment]
Great. This article is a more in-depth one, so it probably isn't the best one to start with. I would recommend starting with "getting started" material and then growing from there into more complex/deep material.

We were talking about porting some "getting started" .NET Framework content to core. It both needs to be massaged into markdown and validated that it the content applies to Core. We're going to start that exercise soon, but could use some help. Interested in that?

Here's the content: https://msdn.microsoft.com/en-us/library/ms172157(v=vs.110).aspx

**Comment by armadilloNik** [comment]
Rich - it sounds like there might be some bigger ideas/epics y'all want to tackle that aren't clearly reflected by the individual issues.  I'm interested in helping out.
