### ISSUE TITLE
PowerShell script does not work

### ISSUE THREAD

**Issue by LisandroSu** [dotnet/docs#7607]
@karelkral commented on [Mon Sep 10 2018](https://github.com/dotnet/docs.cs-cz/issues/5)

Get-ChildItem "HKLM:SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full\" | Get-ItemPropertyValue -Name Release | ForEach-Object { $_ -ge 394802 } 
ForEach-Object { $_ -ge 394802 }
The term 'Get-ItemPropertyValue' is not recognized as the name of a cmdlet,
function, script file, or operable program. Check the spelling of the name, or
if a path was included, verify that the path is correct and try again.At
line:1 char:76
+ Get-ChildItem "HKLM:SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full\" |
Get-I ...
+
~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-ItemPropertyValue:String) [
   ], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

---
#### Podrobnosti dokumentu

⚠ *Neupravujte tuto část. Vyžaduje se k propojení problémů docs.microsoft.com ➟ GitHub.*

* ID: 2115da38-e95e-46fc-1e2d-da88ef92c6cf
* Version Independent ID: a3790e8a-0654-851b-c991-ab7382025406
* Content: [Postupy: zjištění nainstalovaných verzí rozhraní .NET Framework](https://docs.microsoft.com/cs-cz/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed#ps_a)
* Content Source: [docs/framework/migration-guide/how-to-determine-which-versions-are-installed.md](https://github.com/dotnet/docs.cs-cz/blob/live/docs/framework/migration-guide/how-to-determine-which-versions-are-installed.md)
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

---

@svick commented on [Mon Sep 10 2018](https://github.com/dotnet/docs.cs-cz/issues/5#issuecomment-419903074)

Where did you get that code? I can't find it on the page you linked to, only on a comment for it: https://github.com/dotnet/docs/issues/7358.

Regarding your actual question, as far as I can tell, `Get-ItemPropertyValue` is only supported in PowerShell 5.0 or newer. What version of PowerShell are you using?

**Comment by LisandroSu** [comment]
Hi team,

Please check this issue reported by the user.

Thanks!

**Comment by karelkral** [comment]
I get this code right from Microsoft doc where I have reported the issue: https://docs.microsoft.com/cs-cz/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed#ps_a

**Comment by JRAlexander** [comment]
Unfortunately, I can't reproduce the error, as the PowerShell script works fine for me.  I'm on PowerShell version 5.1, Windows 10. What version are you using?

**Comment by karelkral** [comment]
It was on Windows Server 2008 R2, trying to test existence of FW 4.7.1

**Comment by svick** [comment]
@karelkral

> I get this code right from Microsoft doc where I have reported the issue

Sorry, yeah, you're right. I'm not sure how I missed that.

**Comment by Thraka** [comment]
From doing some searching it seems that the command only exists in PowerShell 5. If you're using a version <5 you need to change how you're getting the value.

See https://stackoverflow.com/questions/31705245/retrieve-information-from-registry-key-using-powershell for more information.

**Comment by mairaw** [comment]
Should we then just call out in the article that you need PowerShell 5 and later versions to run that script? And then we can also indicate for them to run something like $psversiontable to check their versions.

Thoughts?

**Comment by Thraka** [comment]
We could combine the scripts and put in a `# PowerShell 5` and `# PowerShell < 5` OR even just change the script to the code that works on both...

**Comment by mairaw** [comment]
I'm fine either way @Thraka.

**Comment by EliteLoser** [comment]
If anyone's interested, here's a thorough version of the PowerShell approach..: https://github.com/EliteLoser/DotNetVersionLister
