### ISSUE TITLE
Document how to use cryptography in a cross-plat way

### ISSUE THREAD

**Issue by twsouthwick** [dotnet/docs#761]
There seems to be some gotchas when working with crypto APIs on different platforms (can't think of anything specific, but seen stuff pop up on aliases and online). Some samples or examples could be really helpful for someone starting out with a crypto scenario on .NET Core.

**Comment by mairaw** [comment]
The entire crypto section needs to be reviewed. 

/cc @bartonjs

**Comment by bartonjs** [comment]
@twsouthwick https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/cross-platform-cryptography.md isn't as nice to read as if @mairaw wrote it; but it has lots of words.  And tables :smile:.

**Comment by twsouthwick** [comment]
That is exactly the kind of thing I was looking for :) Any plans to get this into the official docs?

**Comment by mairaw** [comment]
@bartonjs the link doesn't exist anymore. Any other sources for us to get started with this issue?

**Comment by bartonjs** [comment]
Rich moved it to https://github.com/dotnet/corefx/blob/master/Documentation/architecture/cross-platform-cryptography.md

**Comment by mairaw** [comment]
@twsouthwick just FYI, this is still in our backlog. We haven't been able to get to this one yet.
