### ISSUE TITLE
Can't find constructor StackTrace(bool)

### ISSUE THREAD

**Issue by netmailgopi** [dotnet/docs#7614]
I'm on a project targeting .NET Standard 2.0. While creating a StackTrace object I see the constructor (exception, bool) alone and nothing else. I cannot do StackTrace st = new StackTrace(true); 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f41c094a-35ce-dcbc-5bdc-49cfe73e4a14
* Version Independent ID: 8debd760-2c61-cefb-2b45-da2c26431902
* Content: [StackTrace Class (System.Diagnostics)](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.stacktrace?view=netstandard-2.0)
* Content Source: [xml/System.Diagnostics/StackTrace.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Diagnostics/StackTrace.xml)
* Product: **dotnet-api**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
These should be the APIs in .NET Standard 2.0
https://raw.githubusercontent.com/dotnet/standard/master/docs/versions/netstandard2.0_ref.md

![image](https://user-images.githubusercontent.com/12971179/45449995-aa611a80-b68b-11e8-8699-a3914b84c59e.png)

And I see 9 overloads when I created a test library using .NET Standard 2.0:
![image](https://user-images.githubusercontent.com/12971179/45450190-49861200-b68c-11e8-9889-06177a69ad71.png)

So not sure why you're only seeing one.
