### ISSUE TITLE
Document title make it hard to find

### ISSUE THREAD

**Issue by vbfox** [dotnet/docs#7622]
This document is specific to how references to types/methods & other constructs are identified but it's title is very generically about the XML file, making it hard to find from google/bing whatever

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79307f9a-ba5a-b108-918b-917df121facd
* Version Independent ID: 6d011fb8-572e-cea9-4e4e-70720dd76251
* Content: [Processing the XML File (C# Programming Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/processing-the-xml-file)
* Content Source: [docs/csharp/programming-guide/xmldoc/processing-the-xml-file.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/xmldoc/processing-the-xml-file.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this up @vbfox 

This should be updated to provide better findability.

**Comment by BillWagner** [comment]
reopening to address as part of updating the XML section.
