### ISSUE TITLE
Right alignment behaviour different to what's stated in the docs

### ISSUE THREAD

**Issue by RaulBastian** [dotnet/docs#7625]
With 'right' alignment and when the right screen-edge obscures the Popup, I find that it's the **right edge of the Popup** that repositions itself to the left edge of the PlacementTarget and not the left edge of the Popup as stated in the docs.

Parragraph:
  | A position of the Popup control that aligns its left edge with the right edge of the PlacementTarget and aligns its upper edge with the upper edge of the PlacementTarget. If the right screen-edge obscures the Popup, the control repositions itself so that its left edge aligns with the left edge of the PlacementTarget. If the left screen-edge obscures the Popup, the control repositions itself so that its left edge aligns with the left screen-edge. If the upper or lower screen-edge obscures the Popup, the control then repositions itself to align with the obscuring screen edge.
-- | --

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e09cd6b-9b1f-473e-7ba7-d1fa8dd2a0ac
* Version Independent ID: 34de618c-16b1-e504-b94a-032df08a6c8d
* Content: [PlacementMode Enum (System.Windows.Controls.Primitives)](https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.primitives.placementmode?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(System.Windows.Controls.Primitives.PlacementMode);k(SolutionItemsProject);k(TargetFrameworkMoniker-.NETFramework,Version%3Dv4.0);k(DevLang-csharp)%26rd%3Dtrue&view=netframework-4.7.2)
* Content Source: [xml/System.Windows.Controls.Primitives/PlacementMode.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Windows.Controls.Primitives/PlacementMode.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by Thraka** [comment]
@RaulBastian Thank you for pointing this out. We'll add this to our backlog and investigate. Thanks again!
