### ISSUE TITLE
How-to for Adorner in ScrollViewer - adorned elements of dynamic/changing position

### ISSUE THREAD

**Issue by ite-klass** [dotnet/docs#7626]
A how-to on how Adorners can/should be used within a ScrollViewer would be quite helpful, introducing and documenting both the handling of AdornerLayer in the context of scrolling/changing adorned elements and handling of positioning on changing content/content position, or more generally changing reference position/size or the adorned element.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75447836-d6d7-9edc-ad13-2e58f3d058a6
* Version Independent ID: 58b6e291-bcf2-5b11-4f18-5dc9205ed7dc
* Content: [Adorners How-to Topics](https://docs.microsoft.com/en-us/dotnet/framework/wpf/controls/adorners-how-to-topics)
* Content Source: [docs/framework/wpf/controls/adorners-how-to-topics.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/controls/adorners-how-to-topics.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
//cc @OliaG @SamBent a new topic request.

Thanks for the suggestion, @ite-klass. We've added it to our backlog.
