### ISSUE TITLE
Example for protected-internal is wrong

### ISSUE THREAD

**Issue by matthid** [dotnet/docs#7627]
The line

```
// baseObject.myValue = 10;
```

Can be un-commented and the example will still compile, because you are within the scope of "DerivedClass".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 650c563e-748e-7ad7-fea9-0504549a56ab
* Version Independent ID: ad6dac17-6e62-1447-e85d-e502ae39a343
* Content: [protected internal (C# Reference)](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/protected-internal)
* Content Source: [docs/csharp/language-reference/keywords/protected-internal.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/protected-internal.md)
* Product: **dotnet-csharp**
* GitHub Login: @sputier
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for pointing this out @matthid You are correct, the example has an error.

The correct fix is to move the `Main` method to a new class, not derived from `BaseClass`.

I've added this to our backlog, and our community project.  If you'd like to submit a PR for this, I'll review it and merge it.

**Comment by matthid** [comment]
Actually, I was wrong. The example is correct.

The description "A protected internal member is accessible from the current assembly or from types that are derived from the containing class. " It was a bit irritating. In fact the example shows that this is not true, there is another limitation where the variable has to be a derived type as well.

I could swear I tested this before posting, sorry.

**Comment by mairaw** [comment]
No worries @matthid. Thanks for getting back to us and closing the issue.
