### ISSUE TITLE
But what's in a Name?

### ISSUE THREAD

**Issue by smashedapples20** [dotnet/docs#7631]
I came here hoping to find out what is in the Name string. Is it literally just the file's name, or is it the path? I mean, I assume, based on the name of the property that it's just the filename which isn't very useful. Since this is a FileStream, I assume it can probably pretty easily expose the full path, but maybe not?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7cc1aa5-01fa-daaf-29e9-629c764c06c0
* Version Independent ID: 89fad939-286b-4cd6-dfb3-5f3cc1c893de
* Content: [FileStream.Name Property (System.IO)](https://docs.microsoft.com/en-us/dotnet/api/system.io.filestream.name?redirectedfrom=MSDN&view=netframework-4.7.2#System_IO_FileStream_Name)
* Content Source: [xml/System.IO/FileStream.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.IO/FileStream.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by smashedapples20** [comment]
At least show the output of the Console.WriteLine in the example. Showing how to invoke the Property is only half of the example... what it actually does is more interesting.

**Comment by Thraka** [comment]
@smashedapples20 Hello! Thanks for the question. I just did some tests and found out that it's the full absolute path to the file.
