### ISSUE TITLE
Documentation related to cultures (locales) needs updating: it is Windows-centric and doesn't mention deprecated elements

### ISSUE THREAD

**Issue by mklement0** [dotnet/docs#7635]
## Issues with Existing Topics

This is a follow-up from https://github.com/dotnet/corefx/issues/32207, in which @tarekgh mentions several deprecated elements relating to enumeration `System.Globalization.CultureTypes` enum and the `CultureInfo` type that are currently not marked as such in the documentation.

Additionally, the current documentation is entirely focused on Windows.

**Comment by rpetrusha** [comment]
Thanks for opening this issue, @mklement0. We'll schedule some time to address it in an upcoming sprint.
