### ISSUE TITLE
link to mstoolsfordocker is broken

### ISSUE THREAD

**Issue by GregHDC** [dotnet/docs#7638]
"To see more about installing Visual Studio Tools for Docker, go to http://aka.ms/vstoolsfordocker and "
This link gives a fancy 404 page, with the message "The requested extension '0f5b2caa-ea00-41c8-b8a2-058c7da0b3e4' doesn't exist."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcf20f50-2d15-1744-386d-1d05ff9931fb
* Version Independent ID: b07f881a-4b4e-9db5-9eb6-c83cf0fba6b2
* Content: [Using Visual Studio Tools for Docker (Visual Studio on Windows)](https://docs.microsoft.com/en-us/dotnet/standard/containerized-lifecycle-architecture/design-develop-containerized-apps/visual-studio-tools-for-docker)
* Content Source: [docs/standard/containerized-lifecycle-architecture/design-develop-containerized-apps/visual-studio-tools-for-docker.md](https://github.com/dotnet/docs/blob/master/docs/standard/containerized-lifecycle-architecture/design-develop-containerized-apps/visual-studio-tools-for-docker.md)
* Product: **dotnet**
* GitHub Login: @CESARDELATORRE
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
Thank you for letting us know @GregHDC about the broken link. @CESARDELATORRE @SteveLasker you guys seem to be the owners of that aka.ms link. Can you please update it?
