### ISSUE TITLE
New targets - Platform Extensions

### ISSUE THREAD

**Issue by liammoat** [dotnet/docs#7642]
I'm trying to understand Platform Extensions in the context of .NET Core and .NET Standard. Can you confirm if the following two statements (quoted from this article) should read "ASP.NET" instead of "ASP.NET Core".

* .NET Core + Platform Extensions: Includes the .NET Core APIs in addition to other APIs in the .NET ecosystem such as WCF, ASP.NET Core, FSharp, and Azure.
* .NET Standard + Platform Extensions: Includes the .NET Standard APIs in addition to other .NET ecosystem such as WCF, ASP.NET Core, FSharp, and Azure.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cdd8086b-9a95-38d5-160f-c12c653f954e
* Version Independent ID: 0f47d826-e3ef-8549-9d37-2e8afae29f46
* Content: [The .NET Portability Analyzer - .NET](https://docs.microsoft.com/en-us/dotnet/standard/analyzers/portability-analyzer#feedback)
* Content Source: [docs/standard/analyzers/portability-analyzer.md](https://github.com/dotnet/docs/blob/master/docs/standard/analyzers/portability-analyzer.md)
* Product: **dotnet**
* GitHub Login: @blackdwarf
* Microsoft Alias: **mairaw**

**Comment by svick** [comment]
> Can you confirm if the following two statements (quoted from this article) should read "ASP.NET" instead of "ASP.NET Core".

I don't think they should. You can't run an ASP.NET application on .Net Core, so I don't see how would it make sense to call ASP.NET part of platform extensions of .Net Core.

**Comment by BillWagner** [comment]
Thanks for asking the question @liammoat 

As @svick said, the document is correct: The extensions should mean "ASP.NET Core", not "ASP.NET".

I'll close this issue.
