### ISSUE TITLE
Conflicting documentation

### ISSUE THREAD

**Issue by reavill-d** [dotnet/docs#7645]
Under the ADO.NET Asynchronous Programming topic, it states
"Beginning in the .NET Framework 4.5, these methods no longer require Asynchronous Processing=true in the connection string.".

Is this statement directed toward only the legacy BeginExecute_____ methods or does it include the new async methods?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 187f434e-673a-4955-9cd4-73908eb0be8a
* Version Independent ID: 75484462-a041-9ae8-4134-954ede1ab85a
* Content: [SqlConnectionStringBuilder.AsynchronousProcessing Property (System.Data.SqlClient)](https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlconnectionstringbuilder.asynchronousprocessing?redirectedfrom=MSDN&view=netframework-4.7.2#System_Data_SqlClient_SqlConnectionStringBuilder_AsynchronousProcessing)
* Content Source: [xml/System.Data.SqlClient/SqlConnectionStringBuilder.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Data.SqlClient/SqlConnectionStringBuilder.xml)
* Product: **dotnet-api**
* GitHub Login: @douglaslMS
* Microsoft Alias: **douglasl**

**Comment by douglaslMS** [comment]
@reavill-d Thanks for your question. As implied by the location and phrasing of the "no longer required" statement, it's the legacy Begin... methods that no longer require Asynchronous Processing=true in the connection string. The new async methods don't and have never needed it. I'll see whether we can make this clearer. The [Asynchronous Programming](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/asynchronous-programming) page contains quite a number of samples for the new async methods in which the connection string doesn't include this parameter, so if nothing else it's clear from the examples.

**Comment by douglaslMS** [comment]
@reavill-d BTW sorry for the delay in responding! Your question came in while I was on vacation, and I overlooked it.

**Comment by douglaslMS** [comment]
#please-close
