### ISSUE TITLE
Escaping rules incorrectly described

### ISSUE THREAD

**Issue by ant-222** [dotnet/docs#7646]
This document has the description of the connection-string format copied from [Connection Strings in ADO.NET](https://github.com/dotnet/docs/blob/master/docs/framework/data/adonet/connection-strings.md). It has the same errors as described in issue [#7628](https://github.com/dotnet/docs/issues/7628) about that document.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a687d311-41e3-4f63-4ff3-632e3efbcda5
* Version Independent ID: 190e7115-3bd4-7ab7-8512-2110def4ee48
* Content: [Connection Strings](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/ef/connection-strings)
* Content Source: [docs/framework/data/adonet/ef/connection-strings.md](https://github.com/dotnet/docs/blob/master/docs/framework/data/adonet/ef/connection-strings.md)
* Product: **dotnet-framework**
* GitHub Login: @douglaslMS
* Microsoft Alias: **douglasl**

**Comment by BillWagner** [comment]
Thanks for pointing this out @ant-222 

I see that you've created a PR to address #7628 and @douglaslMS is reviewing that now. Once you've agreed on that update, do you want to submit a PR for this issue as well?

**Comment by ant-222** [comment]
I am not certain what a good PR would be. I would simply remove the partially duplicated and incorrect description and replace it with a reference to the dedicated article on connection strings. If that is OK with you, I can do it.

**Comment by douglaslMS** [comment]
This issue has been resolved by [PR 7628](https://github.com/dotnet/docs/issues/7628).

**Comment by douglaslMS** [comment]
Closing this issue as resolved.

**Comment by mairaw** [comment]
@douglaslMS #7628 is an issue. Was this resolved by a different PR then?

**Comment by douglaslMS** [comment]
@mairaw Thanks, I was confused by the 2 similar issues for 2 different topics. I will port the changes made in PR #7972 to fix issue #7628 to this issue and article.
