### ISSUE TITLE
MSTest Project (.NET Core)

### ISSUE THREAD

**Issue by gnilsson2** [dotnet/docs#7648]
Unit Test Project (.NET Core) seems to now be MSTest Project (.NET Core)
xUnit Test Project (.NET Core)  also works 
but with :
[Fact]
        public void ThingGetsObjectValFromNumber()
        {
            Assert.Equal(42, new Thing().Get(42));
        }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 852fcf8d-7873-c8cf-fd18-2b4b188003ef
* Version Independent ID: e3cec24b-80bf-fdfa-6f36-cf65d939f89d
* Content: [Building a complete .NET Core solution on Windows, using Visual Studio 2017](https://docs.microsoft.com/en-us/dotnet/core/tutorials/using-on-windows-full-solution)
* Content Source: [docs/core/tutorials/using-on-windows-full-solution.md](https://github.com/dotnet/docs/blob/master/docs/core/tutorials/using-on-windows-full-solution.md)
* Product: **dotnet-core**
* GitHub Login: @bleroy
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Thanks for your feedback @gnilsson2. We're revisiting our set of content for .NET Core and we'll include this topic in the evaluation. We probably will deprecate this one in favor of a series of tutorials we have including https://docs.microsoft.com/en-us/dotnet/core/tutorials/testing-library-with-visual-studio.

**Comment by tdykstra** [comment]
This article was removed. Closing the issue.
