### ISSUE TITLE
Function description is vague

### ISSUE THREAD

**Issue by jgscherber** [dotnet/docs#7649]
The description of the function is vague. The usage of the word "content" maybe clear when domain specific, but could be misinterpreted as meaning the entire message. The description of the property furthers that chance by referring to "output".
Propose changing the function description to something like:

> Gets or sets a value that indicates whether only the HTTP headers will be sent to the client.

With the property description being something like:

> `true `if HTTP message content in suppressed; otherwise, `false`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e927052-52e9-fa88-45ae-e27010edf7ad
* Version Independent ID: f222b976-a8ec-dc49-eb39-b918e8df2557
* Content: [HttpResponseBase.SuppressContent Property (System.Web)](https://docs.microsoft.com/en-us/dotnet/api/system.web.httpresponsebase.suppresscontent?view=netframework-4.7.2)
* Content Source: [xml/System.Web/HttpResponseBase.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Web/HttpResponseBase.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
Thank you for the suggestion, @jgscherber. Would you like to submit a pull request to make the changes yourself? For information on how to do it, see the [Contributing Guide](https://github.com/dotnet/docs/blob/master/CONTRIBUTING.md).
