### ISSUE TITLE
Wrong.  There is NO SUCH value to change!!!!

### ISSUE THREAD

**Issue by traderhut** [dotnet/docs#7650]
And Worse, you don't tell me where to add the dang thing!!!  Oh, and the project Arch. being built is x86, NOT MSIL, so it already matches, so you dang error is wrong... So, great runtime errors that will be impossible to track down?  Looking forward to it - NOT!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62b2e725-23a6-e54d-7afb-28448cf7a869
* Version Independent ID: 385f6d74-fe5c-7cc2-d0be-1cf0c0216f5d
* Content: [How to: Enable and Disable Automatic Binding Redirection](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/how-to-enable-and-disable-automatic-binding-redirection)
* Content Source: [docs/framework/configure-apps/how-to-enable-and-disable-automatic-binding-redirection.md](https://github.com/dotnet/docs/blob/master/docs/framework/configure-apps/how-to-enable-and-disable-automatic-binding-redirection.md)
* Product: **dotnet-framework**
* GitHub Login: @mcleblanc
* Microsoft Alias: **markl**

**Comment by Thraka** [comment]
Hello.

It's hard to understand what problem you're having exactly. I'm guessing it's that you got an error compiling that said there was a conflict between a dependency version. Have you searched stackoverflow for an answer such as https://stackoverflow.com/questions/1871073/resolving-msb3247-found-conflicts-between-different-versions-of-the-same-depen if you look at the various answers, you might find something that helps you figure out an answer to your problem.

**Comment by djangohunt** [comment]
I also don't have this setting, I have tried adding manually (trying to disable binding redirection) and it isn't working, my app.config is being overwritten with a binding redirect.

**Comment by Thraka** [comment]
@djangohunt can you share more information about your project?
