### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Number5isAlive** [dotnet/docs#7651]
invariannt culture.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06a17d5d-5f6e-d6bc-324b-af411a42ccb8
* Version Independent ID: f58588d7-70f6-aa32-5c6d-ac3e7d72d87c
* Content: [.NET Core Application Deployment](https://docs.microsoft.com/en-us/dotnet/core/deploying/index)
* Content Source: [docs/core/deploying/index.md](https://github.com/dotnet/docs/blob/master/docs/core/deploying/index.md)
* Product: **dotnet-core**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by mairaw** [comment]
Thanks for your feedback @Number5isAlive. Would you like to submit a pull request with the fix?
Check this guide for a quick explanation on how to do this: https://docs.microsoft.com/en-us/contribute/#quick-edits-to-existing-documents

**Comment by Number5isAlive** [comment]
label for link: https://docs.microsoft.com/en-us/dotnet/core/deploying/index
Current:  invariannt culture.
Proposed: invariant culture.

**Comment by Number5isAlive** [comment]
change looks correct.

**Comment by mairaw** [comment]
I've opened the pull request for you: https://github.com/dotnet/docs/pull/7654
