### ISSUE TITLE
Perform.exe vs perfmon.exe

### ISSUE THREAD

**Issue by nnpcYvIVl** [dotnet/docs#7652]
The article mentions "Perform.exe". Did it mean to say perfmon.exe?

e.g.
Use the Windows Perform.exe tool to monitor handle counts while injecting faults.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec59a8c7-3d69-ff0c-fe77-a42a138e28a3
* Version Independent ID: 1180a2bd-b960-616f-e14f-cc97f2f46106
* Content: [SafeHandle Class (System.Runtime.InteropServices)](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.safehandle?view=netframework-4.7.2)
* Content Source: [xml/System.Runtime.InteropServices/SafeHandle.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Runtime.InteropServices/SafeHandle.xml)
* Product: **dotnet-api**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by rpetrusha** [comment]
Yes, it should have said Perfmon.exe, @nnpcYvIVl. We've opened dotnet/dotnet-api-docs#522 to correct the text.
