### ISSUE TITLE
C#7.3 tuples: nested ('!=') '==' (in)equality needs clarification

### ISSUE THREAD

**Issue by glenn-slayden** [dotnet/docs#7664]
A the end of section https://docs.microsoft.com/en-us/dotnet/csharp/tuples#equality-and-tuples, the following text appears:

> Finally, tuples may contain nested tuples. Tuple equality **_compares the "shape"_** of each operand through nested tuples as shown in the following example
>
>     (int, (int, int)) nestedTuple = (1, (2, 3));
>     Console.WriteLine(nestedTuple == (1, (2, 3)) );

(First of all this should show the result of the result of the `WriteLine`, which is expected to be _true_ here.)

But as it stands, the documentation does not specify whether **C# 7.3** will consider tuples with equivalent "flattened" values--but different "shapes"--to be equal or not-equal, based exclusively on them having different "shapes." The more interesting case, then is:

     (int, (int, int)) nestedTuple = (1, (2, 3));
     Console.WriteLine(nestedTuple == ((1, 2), 3) );

Would this be _true_ or _false_?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bf15268-9d34-cf10-97b9-0b94022c3305
* Version Independent ID: 17728168-48fa-0f5f-0c19-31ae4ce6fdb9
* Content: [Tuple types - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/tuples)
* Content Source: [docs/csharp/tuples.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tuples.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this up @glenn-slayden 

I've added this to an upcoming milestone to address it.

**Comment by glenn-slayden** [comment]
>     (int, (int, int)) nestedTuple = (1, (2, 3));
>     Console.WriteLine(nestedTuple == ((1, 2), 3) );
>Would this be true or false?

The answer, as I found out is... neither. The code won't compile, implying that C# has elected to summarily rule out any/all notion of comparing non-isomorphic tuples as 'illogical'.

**Comment by glenn-slayden** [comment]
To be clear, the docs for the new capability added for nested tuples in **C# 7.3** might wish to mention that it is the language _*syntax*_ requires that the left/right tuple arguments of the `==` and `!=` operators be isomorphic (i.e. same-shaped, having identical nesting structure).

The distinction being that, the operation is only _defined_ between type-compatible tuples _**which must also be isomorphic**_.

The point being that (attempting to) apply `==` or `!=` between tuples that indeed have identical _*flattened*_ type layouts yet different nesting morphology yields a compile-time syntax error, as opposed to any (putative/presumed) effect at runtime.
