### ISSUE TITLE
invalid ProcId on win10

### ISSUE THREAD

**Issue by zhuangzhuang** [dotnet/docs#7668]
on win10 start `calc.exe` will start new process `calculator.exe`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 122a2ecd-89b1-44c7-ca26-74db80252b6f
* Version Independent ID: 341590f6-e4f6-e1bf-49b6-ce18c20f3a2b
* Content: [How to: Start an Application and Send it Keystrokes (Visual Basic)](https://docs.microsoft.com/en-us/dotnet/visual-basic/developing-apps/programming/computer-resources/how-to-start-an-application-and-send-it-keystrokes)
* Content Source: [docs/visual-basic/developing-apps/programming/computer-resources/how-to-start-an-application-and-send-it-keystrokes.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/developing-apps/programming/computer-resources/how-to-start-an-application-and-send-it-keystrokes.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
Thanks for submitting this feedback, @zhuangzhuang. @KathleenDollard, it seems that `Shell` is not returning a valid process ID. Is this a known issue? Should the documentation recommend the Process class instead?

**Comment by mairaw** [comment]
I can repro this. @KathleenDollard who could we follow up on this?

**Comment by KathleenDollard** [comment]
Weird. I also see the PID redirected. 

I have a guess that Calculator is unique and part of updating the calculator app. As such, I think we should change the sample to send "Hello" to Notepad and see if anyone encounters this problem with an app with a last storied history.

**Comment by arfen** [comment]
I have this problem, too. What's wrong with the PID of Calculator.EXE?

**Comment by KathleenDollard** [comment]
It appears to be redirecting the process - an issue with Calculator.EXE as best as I can tell.

**Comment by mairaw** [comment]
I've opened a PR to change this to Notepad then since we don't know what's going on with the calculator app being redirected on Windows 10
https://github.com/dotnet/samples/pull/1664

**Comment by Youssef1313** [comment]
@mairaw, should an issue be opened in https://github.com/microsoft/calculator ?

**Comment by mairaw** [comment]
Good idea @Youssef1313. I think it would be good to understand what's going on behind the scenes and why the process is being redirected. Do you want to do that?

**Comment by HowardWolosky** [comment]
@mairaw - Notepad isn't going to be a good example for this either, as it has been [moved to the Store in recent Insider builds of Windows 10](https://blogs.windows.com/windowsexperience/2019/08/16/announcing-windows-10-insider-preview-build-18963/#vqlAgDtJUehfexs6.97), and has a similar (but slightly different) redirection process happening there as well.

**Comment by mairaw** [comment]
Thanks @HowardWolosky for letting me know. I'll have to think of an alternative for this one then. For now, I think we can ship the Notepad change until I come up with another example. It will work for non-Insider builds for a while.
