### ISSUE TITLE
Needs an example

### ISSUE THREAD

**Issue by marcusl** [dotnet/docs#7672]
How to use this to retrieve something ECHO:ed from batfile into a build property, for example`?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b87ecbd3-988f-24fa-13c3-73c87561d3c2
* Version Independent ID: 499450dd-33bf-246f-326c-c152ec997e93
* Content: [Exec.ConsoleToMSBuild Property (Microsoft.Build.Tasks)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.build.tasks.exec.consoletomsbuild?redirectedfrom=MSDN&view=netframework-4.7.2#Microsoft_Build_Tasks_Exec_ConsoleToMSBuild)
* Content Source: [xml/Microsoft.Build.Tasks/Exec.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Build.Tasks/Exec.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
Thanks for requesting an example, @marcusl.  However, Exec.ConsoleToMSBuild is marked as for internal use only ("This API supports the product infrastructure and is not intended to be used directly from your code."), As a general rule, we don't provide examples for members that are intended for internal use only. I'll also close this issue.

**Comment by marcusl** [comment]
Thanks for the quick response @rpetrusha. Much appreciated! :)

I had missed that it was marked as internal use.

It seems like that is the only way to get something from an exe task into an item so I can put it into a property though?  Seems a bit odd to have it as internal. It's a common use case. 

I managed to get it working so I assume I was going the right way, and I'm happy with that.
