### ISSUE TITLE
Missing para on Application-scoped settings

### ISSUE THREAD

**Issue by ptoye** [dotnet/docs#7673]
The document needs a paragraph saying that Size cannot be bound to an Application setting. See ClientSize for suitable text. 
Alternatively, allow Size to be bound, which would seem to me the better solution.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87298191-c67d-d808-55ab-32c5972c3728
* Version Independent ID: 4b72648c-0222-6cb5-ec26-b97298b3f385
* Content: [Form.Size Property (System.Windows.Forms)](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.form.size?view=netframework-4.7.2)
* Content Source: [xml/System.Windows.Forms/Form.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Windows.Forms/Form.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
Thanks for your feedback, @ptoye. We've added this issue to our backlog.

@Tanya-Solyanik and @merriemcgaw, can you comment on allowing Size to be bound to an app setting?
