### ISSUE TITLE
No Help

### ISSUE THREAD

**Issue by schellem** [dotnet/docs#7675]
This did not help me learn a bit about Select

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3626f9c-d40c-8dcc-56d0-05b46fbac95f
* Version Independent ID: a7a6af0f-4033-f80c-8a68-5bbc7c64a29e
* Content: [Projection Operations (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/linq/projection-operations)
* Content Source: [docs/csharp/programming-guide/concepts/linq/projection-operations.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/linq/projection-operations.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
We need to look at our LINQ coverage and make it more cohesive with respect to the query expression syntax.

**Comment by BillWagner** [comment]
closing this.

It ill be handled as part of the [updated C# reorganization](https://gist.github.com/BillWagner/047cb97f6c0fe542d3a1299e994b2acd)
