### ISSUE TITLE
Need a troubleshooting guide for conditions that might prevent DPI Awareness changes in Visual Studio from working properly

### ISSUE THREAD

**Issue by rkttu-devsisters** [dotnet/docs#7677]
If the dpiAwareness setting is present in the HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\devenv.exe, then the DPI awareness transition in Visual Studio does not work properly (regardless of how the value is set). It seems that you need to explain that you need to remove this registry entry first.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43b74bf9-71c6-2559-66f7-2e17de0702ef
* Version Independent ID: 9ad214a4-3ae0-f7e6-bb89-86067d97059d
* Content: [Disable DPI-awareness in Visual Studio](https://docs.microsoft.com/en-us/dotnet/framework/winforms/disable-dpi-awareness-visual-studio)
* Content Source: [docs/framework/winforms/disable-dpi-awareness-visual-studio.md](https://github.com/dotnet/docs/blob/master/docs/framework/winforms/disable-dpi-awareness-visual-studio.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by mairaw** [comment]
@merriemcgaw @OliaG can you comment on this and whether we need to add this to the docs?

**Comment by merriemcgaw** [comment]
It might be worth adding that as a note. I can see how it would be confusing.
