### ISSUE TITLE
WCF Test Client does not support TLS 1.2

### ISSUE THREAD

**Issue by ghost** [dotnet/docs#7683]
I am unable to use the WCF Test Client after disabling TLS 1.0 and lower:
An error occurred while making the HTTP request to URL. This could be due to the fact that the server certificate is not configured properly with HTTP.SYS in the HTTPS case.

Tested against version 15.0.27825.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 599983a3-8520-1f76-61c6-4b77ef804492
* Version Independent ID: 37629297-b13c-bd53-aeac-5646c6bdc06f
* Content: [WCF Test Client (WcfTestClient.exe)](https://docs.microsoft.com/en-us/dotnet/framework/wcf/wcf-test-client-wcftestclient-exe)
* Content Source: [docs/framework/wcf/wcf-test-client-wcftestclient-exe.md](https://github.com/dotnet/docs/blob/master/docs/framework/wcf/wcf-test-client-wcftestclient-exe.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
@zhenlan can you or someone on your team help with this?

**Comment by zhenlan** [comment]
+ @mconnew

**Comment by mrholshi** [comment]
We are experiencing this issue too. TLS 1.0 and lower have been disabled across all systems. With a trusted localhost cert and a trusted FQDN cert, both endpoints will generate the following error when attempting to connect to a local service via HTTPS
`The client and server cannot communicate, because they do not possess a common algorithm`

Tested against version 15.0.28127.55

**Comment by mconnew** [comment]
I presume this is over HTTPS. If so, you could modify the ServicePointManager defaults in the TestClient app config file. I don't believe that TestClient is built specifying a target framework which means it gets 4.0 compatibility semantics by default which means HTTPS only uses SSL 3.0 and TLS 1.0.

**Comment by sagoo33** [comment]
Is there any update on this?
