### ISSUE TITLE
Text sniffer

### ISSUE THREAD

**Issue by timtim1z** [dotnet/docs#7684]
All cell data info copy clip, Geneva Pelfrey, 3044128440 iphone 8, datalogs 9/1/2017-9/1/2018, iPhone8recovery data 3044128440 Geneva Pelfrey

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e7307ad-9c65-507c-4eb4-d791f4bab49e
* Version Independent ID: 03ca1ca4-7f01-5864-f6ba-1714066e499f
* Content: [_Attribute.GetIDsOfNames(Guid, IntPtr, UInt32, UInt32, IntPtr) Method (System.Runtime.InteropServices)](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices._attribute.getidsofnames?view=netframework-4.7.2#System_Runtime_InteropServices__Attribute_GetIDsOfNames_System_Guid__System_IntPtr_System_UInt32_System_UInt32_System_IntPtr_)
* Content Source: [xml/System.Runtime.InteropServices/_Attribute.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Runtime.InteropServices/_Attribute.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Closing since this is not valid feedback.
