### ISSUE TITLE
UpdateSourceTrigger documentation

### ISSUE THREAD

**Issue by SimpleSamples** [dotnet/docs#7693]
In "What Triggers Source Updates" the first sentence of the fourth paragraph is "Similar to the Mode property, different dependency properties have different default UpdateSourceTrigger values.". I have read that many times and I don't understand it. I really think that the word "different" is used improperly. I would submit an update but as I said I can't figure out what it is supposed to say.

Is it trying to say that the default UpdateSourceTrigger value varies; it is not the same for all dependency properties? I guess that the remainder of the paragraph implies that.

Also "the Text property has a default value of LostFocus" is wrong. Just read the documentation; it says the "default is an empty string".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87567591-0d1a-a791-a609-fa7a3986d43c
* Version Independent ID: 29542eb2-683e-0217-71aa-14671a6f193a
* Content: [Data Binding Overview](https://docs.microsoft.com/en-us/dotnet/framework/wpf/data/data-binding-overview)
* Content Source: [docs/framework/wpf/data/data-binding-overview.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/data/data-binding-overview.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by SimpleSamples** [comment]
Thank you. I will work on that. I might include another sample that I 
think would help and you guys can polish it up too.

**Comment by sheridanworkshare** [comment]
<Setter Property="ToolTip" 
                    Value="{Binding RelativeSource={RelativeSource Self}, Path=(Validation.Errors)[0].ErrorContent}"/>

This will create an error in the Output window when it attempts to access the first item of the Validation.Errors collection if it is empty. A far superior solution would be to use this code:

<Setter Property="ToolTip" 
    Value="{Binding (Validation.Errors).CurrentItem.ErrorContent, RelativeSource={RelativeSource Self}}" />

The CurrentItem property will return null, rather than throwing an exception, when there are no errors in this collection.

**Comment by Thraka** [comment]
@sheridanworkshare Thanks, I'm going to get this fixed.
