### ISSUE TITLE
Creating a Binding

### ISSUE THREAD

**Issue by SimpleSamples** [dotnet/docs#7694]
The "Creating a Binding" section takes a major leap over some critical topics. I know from my struggles that DataContext is important to understand and it is not adequately described here. Also, you guys like to use those "Resources" things and that is not adequately described here.

And for such a beginner level article such as this you really should include the MyData class.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87567591-0d1a-a791-a609-fa7a3986d43c
* Version Independent ID: 29542eb2-683e-0217-71aa-14671a6f193a
* Content: [Data Binding Overview](https://docs.microsoft.com/en-us/dotnet/framework/wpf/data/data-binding-overview)
* Content Source: [docs/framework/wpf/data/data-binding-overview.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/data/data-binding-overview.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mrmsbarnes** [comment]
There _are_ still beginners.  We come here for the needed details.
I agree with SimpleSamples' posts, especially this one.
