### ISSUE TITLE
Great

### ISSUE THREAD

**Issue by HeWhoDoesntKnow** [dotnet/docs#7696]
This is a good and beautifully arranged lesson about LINQ.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7857551e-2454-b536-e44d-fb6b14413d5e
* Version Independent ID: 2826bd18-b9ae-38b1-5004-9e575203dfeb
* Content: [Introduction to LINQ Queries (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/linq/introduction-to-linq-queries)
* Content Source: [docs/csharp/programming-guide/concepts/linq/introduction-to-linq-queries.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/linq/introduction-to-linq-queries.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
Thank you for your feedback @HeWhoDoesntKnow. We're glad you liked it!
