### ISSUE TITLE
My Namespace for C#

### ISSUE THREAD

**Issue by NajiElKotob** [dotnet/docs#7699]
For VB .NET programmers, this code allows you to imitate the same "My namespace" VB .NET syntax in C# https://github.com/NajiElKotob/MyNamespaceForCSharp e.g. My.Computer.Info.AvailablePhysicalMemory;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f95eba7-f99a-050f-b938-c135cf6417dc
* Version Independent ID: f1f66514-47d5-3ee0-0d24-e966fc80fd55
* Content: [How to: Use the My Namespace (C# Programming Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/namespaces/how-to-use-the-my-namespace)
* Content Source: [docs/csharp/programming-guide/namespaces/how-to-use-the-my-namespace.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/namespaces/how-to-use-the-my-namespace.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
That is a good library @NajiElKotob 

I'm going to close this, but I'll suggest you promote your library in other forums and C# community sites.
