### ISSUE TITLE
No examples

### ISSUE THREAD

**Issue by nickakalis** [dotnet/docs#7701]
Need more examples of using ML.NET!
It is desirable, in Russian

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: f24e7062-1f2e-3c06-e422-78c879c7b5a2
* Version Independent ID: 6af3085b-bf30-ac66-f01e-b26888a72679
* Content: [DatasetTransformScorer Class (Microsoft.ML.Transforms)](https://docs.microsoft.com/ru-ru/dotnet/api/microsoft.ml.transforms.datasettransformscorer?view=ml-dotnet)
* Content Source: [dotnet/xml/Microsoft.ML.Transforms/DatasetTransformScorer.xml](https://github.com/dotnet/ml-api-docs/blob/live/dotnet/xml/Microsoft.ML.Transforms/DatasetTransformScorer.xml)
* GitHub Login: @dotnet-bot

**Comment by JRAlexander** [comment]
There are tutorials here: https://docs.microsoft.com/ru-ru/dotnet/machine-learning/tutorials/sentiment-analysis. Although they arent in Russian, you can also find more samples at https://github.com/dotnet/machinelearning-samples. Thanks!
