### ISSUE TITLE
Missing link

### ISSUE THREAD

**Issue by escalonn** [dotnet/docs#7718]
Page has text "For more information, see . ". Probably missing a link to .NET Guide "Working with calendars" page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f13c7138-f5d0-8a34-7cf6-8003828ade9e
* Version Independent ID: 14786da1-9e1a-729d-4f0c-bf7cd1da4fe0
* Content: [GregorianCalendar Class (System.Globalization)](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.gregoriancalendar?view=netframework-4.7.2)
* Content Source: [xml/System.Globalization/GregorianCalendar.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Globalization/GregorianCalendar.xml)
* Product: **dotnet-api**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by mairaw** [comment]
Thanks for letting us know @escalonn. We'll fix that.
