### ISSUE TITLE
BitArray should be algebraically consistent

### ISSUE THREAD

**Issue by mwpowellhtx** [dotnet/docs#7720]
What does that mean? Any operators, be they methods or actual operator overloads, such as And, Or, Xor, Not, etc, should leave the **operands** themselves untouched, and return a new instance. That's not the way it is with the current BitArray; though, to your credit, at least you did document as much. I found  that out to my chagrin investigating some Ones Complement weirdness that was going on when I ran into that issue. It also prompted me to develop my own "ImmutableBitArray". The name is not the greatest, but I wanted to convey that operands themselves should be immutable when they are involved in such an operation. So if I did something like this ~((A &amp; B) ^ C) that should yield D but leave A B and C untouched.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b934a3c7-7fc7-87cf-a8b3-bff04470f004
* Version Independent ID: 92a8d7a4-ad0a-1e41-1796-e2ccdb41be56
* Content: [BitArray Class (System.Collections)](https://docs.microsoft.com/en-us/dotnet/api/system.collections.bitarray?view=netframework-4.7.2)
* Content Source: [xml/System.Collections/BitArray.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Collections/BitArray.xml)
* Product: **dotnet-api**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by rpetrusha** [comment]
Thanks for your comment, @mwpowellhtx. Your comment has opened an issue in the dotnet/docs repo, which is devoted to problems with the documentation. In this case, however, we've adequately documented the And, Not, Or, and Xor methods.
For compatibility reasons, it is doubtful that the existing behavior of these methods could be changed. We recommend that you open an [issue in the dotnet/corefx repo](https://github.com/dotnet/corefx/issues) that proposes a new set of APIs in the BitArray class that parallel the existing And, Not, Or, and XOr methods.
Given that your comment doesn't impact the documentation, I'll close it.
