### ISSUE TITLE
Use dash arguments to msbuild

### ISSUE THREAD

**Issue by dasMulli** [dotnet/docs#7732]
MSBuild arguments should use the dash form (e.g. `-p:` instead of `/p:`) wherever possible as to avoid clashing with actual files or directory on *nix / *nix-like systems.

see the following issues for possible clashes:
https://github.com/Microsoft/msbuild/issues/2351
https://github.com/dotnet/cli/issues/6551
https://github.com/dotnet/cli/issues/7227
https://github.com/dotnet/cli/issues/10014
(on the CLI side, https://github.com/dotnet/cli/pull/8969 changed the defaults that are passed to `dotnet msbuild` from CLI commands)

**Comment by mairaw** [comment]
Thanks for opening the issue and the PR @dasMulli.

@Mikejo5000 do you think you need to review the [MSBuild docs](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild?view=vs-2017) to make sure they work cross-platform? We've been changing switches all over our reference to use - instead of /.

**Comment by rainersigwald** [comment]
I think this is reasonable. The slashes usually work but using hyphens is definitely preferable on non-Windows, and isn't that weird on Windows any more. I wouldn't object to changing the upstream docs too, as long as we add explanatory text that `/switch` and `-switch` are equivalent (which we should do regardless).

**Comment by Mikejo5000** [comment]
OK, I'll create a work item.

**Comment by mairaw** [comment]
Yes, that's what we did for the C# compiler options for example: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/. We mention that both are valid, but then show only the -. People also voted in our issue and the majority preferred the dash: #4072

**Comment by Mikejo5000** [comment]
Some are C++ compiler options. I presume the x-plat format works there as well...

**Comment by rainersigwald** [comment]
@Mikejo5000 I wouldn't touch anything on the tool pages--almost all of those are for tools that predate meaningful xplat efforts and may not support dashes instead of slashes.

**Comment by Mikejo5000** [comment]
@rainersigwald I won't be updating any of the non-MSBuild topics.
Is this update strictly limited to the documented switches in the MSBuild Command Line topic:
https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-command-line-reference?view=vs-2017

Or, is it also possible to use some of the compiler switches we talk about in other topics from the command line as well--or are the compiler switches supported in XML elements only?
https://docs.microsoft.com/en-us/visualstudio/msbuild/cl-task?view=vs-2017

In this topic, we have statements like this:
"For more information, see /I (Additional include directories)."
I would leave this alone of course, as "/I" is the actual doc name we are linking to. But it raises a couple of questions for me, such as whether it is possible to use the compiler switches from the command line, and whether the C++ compiler switches are supported in x-plat form ("-").

**Comment by rainersigwald** [comment]
I wouldn't touch anything that doesn't refer to an MSBuild command-line argument. It looks like the VC++ compiler `cl.exe` _does_ support dash arguments, but that won't be the case for all tools, and I don't think it's worth the time checking them individually.

**Comment by Mikejo5000** [comment]
Made these updates here:
https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/3040
