### ISSUE TITLE
Microsoft hacking av min konto!!!

### ISSUE THREAD

**Issue by ArnfinnA** [dotnet/docs#7736]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d49bc05d-7c8e-5f89-aac5-d133225da4d5
* Version Independent ID: 2f831fc9-dfe6-15db-4ec6-00f59c2dacc2
* Content: [.NET Core Guide](https://docs.microsoft.com/en-us/dotnet/core/)
* Content Source: [docs/core/index.md](https://github.com/dotnet/docs/blob/master/docs/core/index.md)
* Product: **dotnet-core**
* GitHub Login: @richlander
* Microsoft Alias: **mairaw**

**Comment by ArnfinnA** [comment]
Hello
I’m pretty shocked that almost everything used for hacking my accounts has GitHub name on it. I hope 🤞 you have got a copy of the site. If not send me a email or text. 
Best regards Arnfinn Aursoey

**Comment by BillWagner** [comment]
I'll close this, as there's no doc action to address this concern.

**Comment by rpetrusha** [comment]
Closing.
