### ISSUE TITLE
HttpClient streams for PUT response

### ISSUE THREAD

**Issue by kiranpradeep** [dotnet/docs#7737]
Thanks for helpful document. One of the nice features shown here is the usage of `GetStreamAsync` API. When dealing with response as big JSON structures (200MB), streams are really helpful to avoid loading the entire JSON into memory at once. I am able to throw away large part of response (JSON) and streams really help. What is missing here is, if I need to use PUT method instead of GET method, I don't have a way to work with streams. There is no `PutAsyncWithResponseStream` method on HttpClient. This implies while dealing with large responses, the entire response (a large JSON in my case) is loaded into memory causing a memory spike. All I have is a `PutAsync` which gives an `HttpResponseMessage` back. That by default loads the large response to memory. Is there a way to work with streams while using HttpClient and PUT/POST methods.

Ofcourse, I can use `response.Content.ReadAsStreamAsync` on the response of `PutAsync`, but by that load entire large JSON got loaded into memory which I like to avoid.

[1] https://www.newtonsoft.com/json/help/html/Performance.htm

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bfcc1a8-ddda-810c-17b0-56a506045d67
* Version Independent ID: 5415878b-e60b-5433-7b4b-efc8259908f0
* Content: [Create a REST client using .NET Core](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/console-webapiclient)
* Content Source: [docs/csharp/tutorials/console-webapiclient.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/console-webapiclient.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
@davidsh can you please take a look at this feedback item? Do you have any suggestions?

**Comment by davidsh** [comment]
The `GetStreamAsync` API is just a convenience method.  If a developer needs to send an HTTP 'PUT, 'POST', etc. method to a server but not read the response body fully, then then should do something like this by using the HttpClient.SendAsync() method directly.

```c#
            var client = new HttpClient();
            var request = new HttpRequestMessage();
            request.Method = HttpMethod.Put;
            request.Content = new StringContent("Some sample content to post");
            request.RequestUri = new Uri("http://example.com");

            // Use 'HttpCompletionOption.ResponseHeadersRead' to prevent the response body
            // from being read/buffered.
            HttpResponseMessage response = await client.SendAsync(request, HttpCompletionOption.ResponseHeadersRead);

            Stream responseBody = await response.Content.ReadAsStreamAsync();

            // Now you have the response stream 'responseBody' that can be read as a stream.
```

**Comment by mairaw** [comment]
Thanks @davidsh. I'm closing this issue then @kiranpradeep.
