### ISSUE TITLE
Word Spelling -- hte  > the

### ISSUE THREAD

**Issue by Number5isAlive** [dotnet/docs#7738]
Framework-dependent deployment with third-party dependencies
3. If Newtonsoft.Json is already installed on your system, add it to your project by selecting your project in the right pane of hte Manage Packages for Solution tab.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50511188-600e-18f6-6d92-c93b135d3db6
* Version Independent ID: 559262e6-f27b-e581-255f-0967b006a922
* Content: [.NET Core app deployment with Visual Studio](https://docs.microsoft.com/en-us/dotnet/core/deploying/deploy-with-vs?tabs=vs156)
* Content Source: [docs/core/deploying/deploy-with-vs.md](https://github.com/dotnet/docs/blob/master/docs/core/deploying/deploy-with-vs.md)
* Product: **dotnet-core**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by pkulikov** [comment]
This was fixed by PR #7739

**Comment by mairaw** [comment]
Oh yeah, thanks @pkulikov. No need to file an issue and a PR for small fixes like this @Num5IsAlive. Thank you again!
