### ISSUE TITLE
Clear -> IsEmpty

### ISSUE THREAD

**Issue by tymtam2** [dotnet/docs#7741]
I think 

            // Clear the stack, and verify that it is empty
            cs.Clear();
            if (!cs.IsEmpty)
            {
                Console.WriteLine("CS: IsEmpty not true after Clear()");
                errorCount++;
            }

is misleading. In a multi-threaded application it's possible, arguably even expected, that very soon after a clear, the collection will not be empty as someone else may have added an item(s).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 480dd10d-0db5-e0ff-8400-391463138474
* Version Independent ID: 97f39363-44cd-1b19-1698-976389fa539d
* Content: [ConcurrentStack&lt;T&gt; Class (System.Collections.Concurrent)](https://docs.microsoft.com/en-us/dotnet/api/system.collections.concurrent.concurrentstack-1?view=netframework-4.7.2)
* Content Source: [xml/System.Collections.Concurrent/ConcurrentStack`1.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Collections.Concurrent/ConcurrentStack`1.xml)
* Product: **dotnet-api**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by rpetrusha** [comment]
Thanks for pointing this out, @tymtam2. The example is definitely a poor one that assumes a single-threaded application. We've added it to our backlog. We'll also open an issue to evaluate the Collections.Concurrent classes, since many of the examples seem to assume a single-threaded execution environment.

**Comment by tymtam2** [comment]
Re:Closed 
If I look at https://docs.microsoft.com/en-us/dotnet/api/system.collections.concurrent.concurrentstack-1?view=netframework-4.7.2 
it still have the problem. :/
