### ISSUE TITLE
Figure 2-3 doesn't fit on my screen and there's no horizontal scroll bars.

### ISSUE THREAD

**Issue by jwdonahue** [dotnet/docs#7744]
Figure 2-3 doesn't fit on my screen and there's no horizontal scroll bars. I tried it on recent versions of Chrome and Edge.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3befff27-c4fc-a699-90b3-903ce60234af
* Version Independent ID: 71ff10df-c0b0-9497-e448-82388ef1b1a1
* Content: [What is Docker?](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/container-docker-introduction/docker-defined)
* Content Source: [docs/standard/microservices-architecture/container-docker-introduction/docker-defined.md](https://github.com/dotnet/docs/blob/master/docs/standard/microservices-architecture/container-docker-introduction/docker-defined.md)
* Product: **dotnet**
* GitHub Login: @CESARDELATORRE
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
I can repro that @jwdonahue. Thanks for reporting. I've opened a PR to try to fix this.
