### ISSUE TITLE
.DoEvents

### ISSUE THREAD

**Issue by maryob77062** [dotnet/docs#7745]
Really???

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5154904d-b7d9-3eaa-7d2e-5ca8308f1f48
* Version Independent ID: 8b82f235-ec9c-5c72-d001-b761b491d400
* Content: [Handling Events (Visual Basic)](https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/language-features/events/walkthrough-handling-events)
* Content Source: [docs/visual-basic/programming-guide/language-features/events/walkthrough-handling-events.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/programming-guide/language-features/events/walkthrough-handling-events.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
@maryob77062, do you want to provide more detailed feedback about the topic that might help us improve it?

**Comment by mairaw** [comment]
Closing due to the lack of response
