### ISSUE TITLE
Illustration error

### ISSUE THREAD

**Issue by mc0re** [dotnet/docs#7752]
Comment to the illustration: loadBitmaps block is also connected to operationCancelled.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d45218e-2933-c3df-73bc-0f72856029c3
* Version Independent ID: 9b5657fd-1e70-a4ce-5b64-1f3e7e0c4bdc
* Content: [Walkthrough: Using Dataflow in a Windows Forms Application](https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/walkthrough-using-dataflow-in-a-windows-forms-application)
* Content Source: [docs/standard/parallel-programming/walkthrough-using-dataflow-in-a-windows-forms-application.md](https://github.com/dotnet/docs/blob/master/docs/standard/parallel-programming/walkthrough-using-dataflow-in-a-windows-forms-application.md)
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by rpetrusha** [comment]
Thanks, @mc0re, for pointing out the inaccuracy in the illustration. We've added it to our backlog.
