### ISSUE TITLE
Interactive running for snippets doesn't work

### ISSUE THREAD

**Issue by jeffy-grh** [dotnet/docs#7754]
When clicking 'Run' option to see the snippets in action, the interactive window throw errors as `using System.Globalization` is missing.
I have added a [relevant comment](https://github.com/dotnet/docs/commit/1ff02eeead394fd80dbd8d4989cf05285cd2f3aa#r30545249) in the PR which originally bought in the issue

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dda93f14-f1b5-fde6-e441-302cdac261ab
* Version Independent ID: 96abc7c4-3719-82da-e271-881d62f0640f
* Content: [Custom Date and Time Format Strings](https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings#feedback)
* Content Source: [docs/standard/base-types/custom-date-and-time-format-strings.md](https://github.com/dotnet/docs/blob/master/docs/standard/base-types/custom-date-and-time-format-strings.md)
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by svick** [comment]
I have already reported this issue for another article in https://github.com/dotnet/try/issues/130.

**Comment by rpetrusha** [comment]
Thanks for pointing this out, @jeffy-grh, and thanks for replying, @svick. Until I saw the issue you opened, I was unaware that culture-specific code isn't working. It does seem to work if a `using` statement is added (at least when I explicitly add one in the REPL), so I'll modify these examples and verifying that they're runnable.
