### ISSUE TITLE
Interactive snippet reset scroll to the top

### ISSUE THREAD

**Issue by jeffy-grh** [dotnet/docs#7755]
When clicking run option to see a code in action, the doc window scroll is reset to the top. 
This can cause readers to lose context.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dda93f14-f1b5-fde6-e441-302cdac261ab
* Version Independent ID: 96abc7c4-3719-82da-e271-881d62f0640f
* Content: [Custom Date and Time Format Strings](https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings#feedback)
* Content Source: [docs/standard/base-types/custom-date-and-time-format-strings.md](https://github.com/dotnet/docs/blob/master/docs/standard/base-types/custom-date-and-time-format-strings.md)
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by mairaw** [comment]
Thanks for your feedback @jeffy-grh. Since this is about the site experience and not the content, I moved this issue to https://github.com/MicrosoftDocs/feedback/issues/695.
