### ISSUE TITLE
Recommendation engine

### ISSUE THREAD

**Issue by AnassKartit** [dotnet/docs#7757]
Hi,
Can you please add movie recommendation engine example.
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e855e630-1a30-d138-4ac6-bfeefebf9aae
* Version Independent ID: afc0a7d1-d3c2-acf2-d4ea-d2565e22b237
* Content: [ML.NET tutorials](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/)
* Content Source: [docs/machine-learning/tutorials/index.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/index.md)
* Product: **dotnet-ml**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by JRAlexander** [comment]
It should have been added to https://github.com/dotnet/machinelearning-samples per .NET Conf session. @GalOshri, do you know when the samples from .NET Conf will be added?

**Comment by CESARDELATORRE** [comment]
The samples using the new API (Pigsty/Static/Typed) will be added in the upcoming days/weeks while this new API is stabilized. For early sneak-peak monitor additional branches other than "Master" at  https://github.com/dotnet/machinelearning-samples

**Comment by Techupdate11** [comment]
@CESARDELATORRE Thanks for the update. Could you please let us know a tentative date, when you will share the movie recommendation example source code?

**Comment by Techupdate11** [comment]
@CESARDELATORRE Any updates on this please?

**Comment by CESARDELATORRE** [comment]
Yes, this can be closed. 👍
