### ISSUE TITLE
Consufing terminology: syntax and format

### ISSUE THREAD

**Issue by ant-222** [dotnet/docs#7770]
The document uses the terms *syntax* and *format* in what I think is a confusing manner. It says:

&gt; The syntax depends on the data provider

and then

&gt; The format of a connection string is a semicolon-delimited list of key/value parameter pairs

I propose to:

1. avoid the term *format* altogether to prevent its confusion with *syntax* because the distinction is not obvious.

1. say that *all* connection strings share the same syntax, and

1. say that it is only the set of recognised keys (or keywords) that is specific to each provider.

I am willing to prepare a pull request with these modifications after issue #7628 is solved, to avoid a possible merging conflict.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c0ea979-365a-bfce-31ed-638781065bca
* Version Independent ID: 3672ed45-e05f-a292-16a0-9779254492be
* Content: [Connection Strings in ADO.NET](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/connection-strings)
* Content Source: [docs/framework/data/adonet/connection-strings.md](https://github.com/dotnet/docs/blob/master/docs/framework/data/adonet/connection-strings.md)
* Product: **dotnet-framework**
* GitHub Login: @douglaslMS
* Microsoft Alias: **douglasl**

**Comment by BillWagner** [comment]
@douglaslMS Can you comment on this proposal to update this article?

**Comment by BillWagner** [comment]
Thanks for submitting this @ant-222 

I'd like others to answer if this is the right direction for this article.

**Comment by ant-222** [comment]
Let us hear others' opinions. For my part, the issue was prompted by a grave misunderstanding on the part of an employee of a large company that has its own RDBMS with an *ADO.NET* provider. He used this line:
> Valid connection string syntax depends on the provider

as an argument for not complying with the general escaping requirements and forcing the user manually to escape schema names with a full stop in them, e.g.:

    Schema="My.Schema";

instead of the correct

    Schema=My.Schema;

He would have been able to defend his incorrect opinion with clearer documentation.

**Comment by douglaslMS** [comment]
@ant-222 cc @BillWagner I've verified your input about escaping with an ADO.NET subject matter expert. Can you do us the favor of preparing a pull request to capture your learnings? Thank you.

**Comment by douglaslMS** [comment]
@ant-222 Excuse me, I was confused while looking at the several related issues and PRs that you've created. Yes, please create a PR for the changes that you recommend in this issue.

cc @BillWagner

**Comment by ant-222** [comment]
@douglaslMS OK, just give me some time, for I am very busy on workdays.

**Comment by ant-222** [comment]
Can you please tell me how to add proper references to:
a. [`DbConnection.ConnectionString`](https://docs.microsoft.com/en-us/dotnet/api/system.data.common.dbconnection.connectionstring?view=netframework-4.7.2) and
b. [`DbConnection.Open()`](https://docs.microsoft.com/en-us/dotnet/api/system.data.common.dbconnection.open?view=netframework-4.7.2) ?

I have tried to find their *Markdown* sources but failed.

**Comment by douglaslMS** [comment]
You can use this syntax:

<xref:UID>
<xref:UID?displayProperty=nameWithType>

xamples:

<xref:System.String> displays as String

<xref:System.String?displayProperty=nameWithType> displays as System.String

**Comment by ant-222** [comment]
@douglaslMS does't seem to work for me. Maybe a shall surround these `xref:` elements with some *Markdown* syntax?

**Comment by ant-222** [comment]
@douglaslMS I have made a [commit](https://github.com/dotnet/docs/compare/master...ant-222:patch-3) but I still need help in fixing `xref`s, whence no pull request yet.

**Comment by mairaw** [comment]
@ant-222 the xref should look like this:
`<xref:System.Data.Common.DbConnection.ConnectionString?displayProperty=nameWithType>`

**Comment by ant-222** [comment]
@mairaw I have copied your example into the Markdown source, but to no avail. See the last [commit](https://github.com/ant-222/docs/blob/patch-3/docs/framework/data/adonet/connection-strings.md). Sorry for misunderstanding something obvious.

**Comment by ant-222** [comment]
My usage of `xref` is correct. It is only the preview here on *github* that does not handle them.

**Comment by douglaslMS** [comment]
@ant-222 That's probably right, GitHub doesn't know about some of the Markdown extensions that we use internally at Microsoft.
