### ISSUE TITLE
I have an IDataView I implemented, how do I add that to a pipeline?

### ISSUE THREAD

**Issue by KevinGrealish** [dotnet/docs#7773]
I have an IDataView I implemented, how do I add that to a pipeline? Do I need to implement a Loader? How is that done?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebe32cd2-0ab5-a3bb-5f18-8dcde3d0a27f
* Version Independent ID: f8a7176d-8b1b-2c49-14b5-567a382e6a9d
* Content: [LearningPipeline.Add(ILearningPipelineItem) Method (Microsoft.ML)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.learningpipeline.add?view=ml-dotnet)
* Content Source: [dotnet/xml/Microsoft.ML/LearningPipeline.xml](https://github.com/dotnet/ml-api-docs/blob/live/dotnet/xml/Microsoft.ML/LearningPipeline.xml)
* GitHub Login: @dotnet-bot

**Comment by JRAlexander** [comment]
@KevinGrealish - check out the docs at https://github.com/dotnet/machinelearning/tree/master/docs/code - they may answer your questions. Thanks!

**Comment by mairaw** [comment]
Closing since this API no longer exists. /cc @natke
