### ISSUE TITLE
How would I implement this method?

### ISSUE THREAD

**Issue by KevinGrealish** [dotnet/docs#7774]
There is no information given here on what an implementation of this method is expected to do. If I am creating my own data loader, what is expected here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90ff8285-ad51-1a4a-26d9-a55c091ca773
* Version Independent ID: 5351be84-fa4c-be47-f1f7-6fe43e5d67ec
* Content: [ILearningPipelineLoader.SetInput(IHostEnvironment, Experiment) Method (Microsoft.ML)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.ilearningpipelineloader.setinput?view=ml-dotnet#Microsoft_ML_ILearningPipelineLoader_SetInput_Microsoft_ML_Runtime_IHostEnvironment_Microsoft_ML_Runtime_Experiment_)
* Content Source: [dotnet/xml/Microsoft.ML/ILearningPipelineLoader.xml](https://github.com/dotnet/ml-api-docs/blob/live/dotnet/xml/Microsoft.ML/ILearningPipelineLoader.xml)
* GitHub Login: @dotnet-bot

**Comment by JRAlexander** [comment]
@KevinGrealish - check out the docs at https://github.com/dotnet/machinelearning/tree/master/docs/code - they may answer your questions. Thanks!

**Comment by mairaw** [comment]
Closing since this API no longer exists. /cc @natke
