### ISSUE TITLE
Placeholder?

### ISSUE THREAD

**Issue by KevinGrealish** [dotnet/docs#7775]
To be a loader in a pipeline I need to implement this yet the documentation gives no details on what this method should do or how to form a Var from a I DataView that I have implemented. How would one implement this to create a custom data loader.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc9dcd99-639f-f99c-d03d-e42165108b12
* Version Independent ID: 0669d064-15e1-43f9-42cd-e62317f663d7
* Content: [ILearningPipelineItem.GetInputData Method (Microsoft.ML)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.ilearningpipelineitem.getinputdata?view=ml-dotnet#Microsoft_ML_ILearningPipelineItem_GetInputData)
* Content Source: [dotnet/xml/Microsoft.ML/ILearningPipelineItem.xml](https://github.com/dotnet/ml-api-docs/blob/live/dotnet/xml/Microsoft.ML/ILearningPipelineItem.xml)
* GitHub Login: @dotnet-bot

**Comment by mairaw** [comment]
@sfilipi can you please take a look at this feedback?

**Comment by JRAlexander** [comment]
@KevinGrealish - check out the docs at https://github.com/dotnet/machinelearning/tree/master/docs/code - they may answer your questions. Thanks!

**Comment by mairaw** [comment]
Closing since this API no longer exists. /cc @natke
