### ISSUE TITLE
One Repository per Aggregate Root + One Repository Per Lookup Table

### ISSUE THREAD

**Issue by peteralbanese** [dotnet/docs#7776]
In the real world the Address table would have two foreign keys: StateId and CountryId, linking the Address table to a State lookup table and a Country lookup table. This article suggests that your Order Repository would also need methods for AddState(), UpdateState(), DeleteState(), AddCountry(), UpdateCountry(), DeleteCountry() ? Further, in order to administer your system to stop accepting Orders from let's say Alaska, you would have to use the Order object to delete a State? Therefore, I would like to recommend a repository per Aggregate Root + a repository per Lookup Table. Please correct me if I'm wrong and you have a valid solution.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3000b84-336c-df28-05d2-de8b9d9708ee
* Version Independent ID: 5d327117-1420-8110-963b-822b6acdc976
* Content: [Designing the infrastructure persistence layer](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/infrastructure-persistence-layer-design)
* Content Source: [docs/architecture/microservices/microservice-ddd-cqrs-patterns/infrastructure-persistence-layer-design.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/microservice-ddd-cqrs-patterns/infrastructure-persistence-layer-design.md)
* Product: **dotnet**
* Technology: **dotnet-ebooks**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by CESARDELATORRE** [comment]
@peteralnanese - I think you are aligned. In the documentation/eBook we clearly recommend to have one Repository per AggregateRoot. the OrderRepository should just manage the Order Aggregate.
If the Order had just foreign keys/ids for the Country and State entities (not the values), in the Order Agregate you would just have the IDs but not the Country and State entities. 
Country would usually be a whole Aggregate with single entity, same for State. Then, you’d have a different Repository for updating each of those aggregates, CountryRepository and StateRepository.

**Comment by peteralbanese** [comment]
Thank you for the clarification Sir.

**Comment by mairaw** [comment]
Ok to close this @peteralbanese?

**Comment by mairaw** [comment]
Closing due to the lack of response. Please get back to us if this is still an issue for you.
