### ISSUE TITLE
Link to a parked domain

### ISSUE THREAD

**Issue by WillSullivan** [dotnet/docs#7784]
The line "For an interactive table, see .NET Standard versions." links to a parked domain and should be removed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9eb8b774-c6f0-8235-6964-15219baf2ea7
* Version Independent ID: 6819a4a7-7527-d8c7-e132-767f7344e00e
* Content: [.NET Standard](https://docs.microsoft.com/en-us/dotnet/standard/net-standard)
* Content Source: [docs/standard/net-standard.md](https://github.com/dotnet/docs/blob/master/docs/standard/net-standard.md)
* Product: **dotnet**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by svick** [comment]
The link to http://immo.landwerth.net/netstandard-versions/# works fine for me:

![](https://user-images.githubusercontent.com/287848/45758874-ea457600-bc26-11e8-9ecd-837a89ecdf2f.png)

**Comment by WillSullivan** [comment]
Hmmm... landwerth.net is parked.

**Comment by mairaw** [comment]
@terrajobst can you comment on this? Are there any plans to move that page to a more official place such as dot.net?

**Comment by mairaw** [comment]
Ping @terrajobst

**Comment by mairaw** [comment]
I don't think we support raw JS and I don't think we will. @DuncanmaMSFT can you comment here?

@rowanmiller is this something we could host on https://dotnet.microsoft.com/ perhaps?

**Comment by DuncanmaMSFT** [comment]
Ignoring the current implementation, the idea of moving this information to docs seems like a good idea. No, we won't just post up a set of random javascript though (despite it's source being @terrajobst )

**Comment by rowanmiller** [comment]
Yep we could definitely put this on the .NET site. We could build a simple page that has a brief summary of what .NET Standard is (plus this table) and then follow the usual model of sending folks to docs for more technical details. Any push-back on that? If not, I'll get it started.

**Comment by mairaw** [comment]
I like that approach @rowanmiller. @DuncanmaMSFT if we can't host random javascript, is there any solution that would allow us to get this into docs? Or should I go the dotnet.microsoft.com route?

**Comment by DuncanmaMSFT** [comment]
Putting it on the .NET site seems appropriate to me

**Comment by mairaw** [comment]
Thanks for the feedback @DuncanmaMSFT. @rowanmiller please proceed with your plan then!

**Comment by rowanmiller** [comment]
Great. I'll work with @terrajobst on moving it.

**Comment by rowanmiller** [comment]
For anyone reading this thread, the replacement page is at https://dotnet.microsoft.com/platform/dotnet-standard
