### ISSUE TITLE
String Escape Sequence section

### ISSUE THREAD

**Issue by B13rg** [dotnet/docs#7787]
"Unicode Encoding" value for "\x" escape sequence should be "\x41='A'" instead of "\x0041='A'" to show how \x is similar to \u.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7aa6134-64e2-28a7-f7d0-d0c1512f4520
* Version Independent ID: 3317fd4a-9cd3-57cd-66f7-abb271e302e8
* Content: [Strings (C# Programming Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/strings/)
* Content Source: [docs/csharp/programming-guide/strings/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/strings/index.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by rpetrusha** [comment]
Thanks for the feedback, @B13rg. It would probably be even more helpful to list both versions -- \\x41 and \\x0041. Would you like to submit a pull request to do that?  Information on submitting PRs can be found in our [Contributor's Guide](https://github.com/dotnet/docs/blob/master/CONTRIBUTING.md#process-for-contributing).

**Comment by pkulikov** [comment]
@rpetrusha @mairaw this was fixed by #7823

**Comment by rpetrusha** [comment]
Thanks for pointing that out, @pkulikov. I'll close this issue.
