### ISSUE TITLE
Parse<T> is not available in .NET Standard 2.0

### ISSUE THREAD

**Issue by martingbrown** [dotnet/docs#7794]
This page covers four overloads of Parse. The Applies to section at the bottom is misleading as it is only accurate for the non generic overloads.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e75dbc27-b028-1391-4da0-ec0096275879
* Version Independent ID: 2ee2b273-0d10-54f6-1703-a52ee1de3cd1
* Content: [Enum.Parse Method (System)](https://docs.microsoft.com/en-us/dotnet/api/system.enum.parse?view=netcore-2.0#System_Enum_Parse__1_System_String_)
* Content Source: [xml/System/Enum.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System/Enum.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by svick** [comment]
There is already a more general request about this: https://github.com/MicrosoftDocs/feedback/issues/314.

**Comment by rpetrusha** [comment]
Thanks for the feedback, @martingbrown. Since this is an external build issue that's already covered by MicrosoftDocs/feedback#314, as @svick points out, I'll close this issue.
