### ISSUE TITLE
Not much info here

### ISSUE THREAD

**Issue by swinterrowd** [dotnet/docs#7799]
How about an example of how to use this method. There are lots of people having problems using this method. I am one of them this info does nothing to explain when and how to use this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d29d207a-26e8-6396-c2b7-b37168ca9c30
* Version Independent ID: 90fed95b-2b1f-62bb-c205-b377bf9745d3
* Content: [ListBox.ScrollIntoView(Object) Method (System.Windows.Controls)](https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.listbox.scrollintoview?view=netframework-4.7.2#System_Windows_Controls_ListBox_ScrollIntoView_System_Object_)
* Content Source: [xml/System.Windows.Controls/ListBox.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Windows.Controls/ListBox.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks for your feedback @swinterrowd. We've added this to our backlog and community contribution project.  Can you point out where did you see people having issues using this method? The page views for this article are low.
