### ISSUE TITLE
Show output from example applications

### ISSUE THREAD

**Issue by mikebk** [dotnet/docs#7800]
Can I suggest that you include the output of this example program? 

It's a convenience for those with Visual Studio. The audience for this example is actually broader than just developers. This audience doesn't have access to Visual Studio and hence, can't run the example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d18f38fe-b0a2-c435-e72f-0f178ba4ca4f
* Version Independent ID: 54f0837d-5fc4-1b8b-588b-07acc1459762
* Content: [XmlElement.InnerText Property (System.Xml)](https://docs.microsoft.com/en-us/dotnet/api/system.xml.xmlelement.innertext?view=netframework-4.7.2)
* Content Source: [xml/System.Xml/XmlElement.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Xml/XmlElement.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
That's a good suggestion @mikebk. We've added this to our backlog. We also welcome contributions if you'd like to submit a PR.
