### ISSUE TITLE
No animation on first button.

### ISSUE THREAD

**Issue by Zalant82** [dotnet/docs#7802]
In the example provided, the animation of the first button does not work. Its size does not change. A similar problem in my project led me here.

What could be wrong?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62d6f305-ee68-74f4-8a8c-8d9aa6cb9e5d
* Version Independent ID: ff16a248-622a-754e-d3f9-76e3a99fa242
* Content: [How to: Animate the Size of a FrameworkElement](https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/how-to-animate-the-size-of-a-frameworkelement)
* Content Source: [docs/framework/wpf/advanced/how-to-animate-the-size-of-a-frameworkelement.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/advanced/how-to-animate-the-size-of-a-frameworkelement.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thank you for your feedback @Zalant82. We'd have to test this to see what's wrong. We're moving this to our backlog for now.

**Comment by mairaw** [comment]
I just tested the sample and it seems to be working. You can find the whole sample here: https://github.com/dotnet/samples/tree/master/snippets/xaml/VS_Snippets_Wpf/transformanimations_snip/XAML

![image](https://user-images.githubusercontent.com/12971179/45979578-54359500-c004-11e8-8fd3-32f3a7a15137.png)

![image](https://user-images.githubusercontent.com/12971179/45979579-5861b280-c004-11e8-9b3f-83c0b415766c.png)
