### ISSUE TITLE
Null Name Argument

### ISSUE THREAD

**Issue by ahwm** [dotnet/docs#7804]
The document says that "name" can be null but it doesn't explain what happens if it is null. This page really should be updated to include this. One would guess either all keys are removed or no keys are removed. Only trying yourself will demonstrate which. Judging by the reference source, it appears it removes the entry where the key is null. So that means it doesn't perform how one would expect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe5e4de6-c970-6112-de79-95041f7df15e
* Version Independent ID: 1ff3c917-a2ad-369f-5150-3a22ab70921b
* Content: [NameValueCollection.Remove(String) Method (System.Collections.Specialized)](https://docs.microsoft.com/en-us/dotnet/api/system.collections.specialized.namevaluecollection.remove?view=netframework-4.7.2)
* Content Source: [xml/System.Collections.Specialized/NameValueCollection.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Collections.Specialized/NameValueCollection.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks for your feedback @ahwm. Exactly, it removes the entry where the key is null. I'll add this information to remarks.
