### ISSUE TITLE
DriveInfo (and other System.IO classes) should be explicit about their thread-safety.

### ISSUE THREAD

**Issue by ericmutta** [dotnet/docs#7809]
Since I/O is the type of thing that you would expect to be done from multiple threads, it would be very handy to know the thread-safety guarantees (if any) of the various `System.IO` classes.

For example, what happens if two threads read the `DriveInfo.AvailableFreeSpace` property? Though the property is read-only, the information it returns is constantly changing as threads create/delete files, so what does one need to keep in mind about this fact when writing portable multi-threaded I/O code?

I was hoping to see something similar to the [thread safety information](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.dictionary-2?view=netstandard-2.0#thread-safety) for the `Dictionary<K,V>` class. In fact I seem to remember the "thread safety" section being a standard part of all (if not most) documentation similar to the very important "Applies To" section which lists applicable platforms.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b18f2264-6230-68d2-98d2-4c3c7210c4a7
* Version Independent ID: 94faff8f-a332-cbfd-ddc4-7d2214ef7f01
* Content: [DriveInfo Class (System.IO)](https://docs.microsoft.com/en-us/dotnet/api/system.io.driveinfo?view=netstandard-2.0#definition)
* Content Source: [xml/System.IO/DriveInfo.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.IO/DriveInfo.xml)
* Product: **dotnet-api**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by ericmutta** [comment]
I may need to file a seperate issue for this, but just thought I should mention it here since I noticed the problem when filing this issue.

When filing a github issue from docs site, if you type `Dictionary<K,V>` (i.e use the angle brackets) the result here on github ends up like this `Dictionary&lt;K,V&gt;` (i.e the angle brackets are replaced with `&lt;` and `&gt;` which github doesn't recognise).

**Comment by mairaw** [comment]
Yes, separate issues please @ericmutta and both should be filed under https://github.com/MicrosoftDocs/feedback. I'm moving the first one for you.

**Comment by mairaw** [comment]
Issue movd to https://github.com/MicrosoftDocs/feedback/issues/697

**Comment by ericmutta** [comment]
> @mairaw I'm moving the first one for you.

Many thanks, will head on over there to file the other issue :+1:
