### ISSUE TITLE
Neat!

### ISSUE THREAD

**Issue by IgorIgorevich94** [dotnet/docs#7822]
This article is NEAT! Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 384e5c2c-d3ba-b5ba-260b-65b8e900b78e
* Version Independent ID: a561cbc7-1e00-5732-e298-d9863f85191c
* Content: [Subscribing to events](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/multi-container-microservice-net-applications/subscribe-events)
* Content Source: [docs/standard/microservices-architecture/multi-container-microservice-net-applications/subscribe-events.md](https://github.com/dotnet/docs/blob/master/docs/standard/microservices-architecture/multi-container-microservice-net-applications/subscribe-events.md)
* Product: **dotnet**
* GitHub Login: @CESARDELATORRE
* Microsoft Alias: **wiwagn**

**Comment by Thraka** [comment]
Glad you liked it! :)
