### ISSUE TITLE
TextBlock[1|2|3]

### ISSUE THREAD

**Issue by macginitie** [dotnet/docs#7824]
The C# code shows, e.g., TextBlock1 or TextBlock2 but the corresponding XAML doesn't. Might be a bit clearer to add it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca5b65ce-7ab7-5cdc-99b1-b70ede120ee8
* Version Independent ID: 91674c1b-71dd-eab4-702f-f060382591ce
* Content: [How to: Create a Text Decoration](https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/how-to-create-a-text-decoration#example)
* Content Source: [docs/framework/wpf/advanced/how-to-create-a-text-decoration.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/advanced/how-to-create-a-text-decoration.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by Thraka** [comment]
Hi! Thanks for filing an issue. These are actually two different ways of doing the same thing. I don't think the docs website presents the code samples in that way. 

The C# example is showing how to add a decoration via code and the XAML is also showing how to do it without any code. The C# code is not talking to the XAML element that is described in the next code block.

**Comment by Thraka** [comment]
I'm going to close this issue. If you have any other comments or thoughts, or feel I was incorrect in my assumption, feel free to reopen or comment. Thanks again!

**Comment by macginitie** [comment]
I figured that out, that the XAML and C# are alternatives, but the 1,2,3 threw me off at first. Perhaps if they all used TextBox1? Probably not worth changing after all.

**Comment by Thraka** [comment]
It makes more sense when you see that the examples are from an app, which demonstrates 3 different boxes: https://github.com/dotnet/samples/tree/master/snippets/csharp/VS_Snippets_Wpf/TextDecorationSnippets/CSharp
