### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by macginitie** [dotnet/docs#7827]
typo in this comment:
// Build the geometry object that represents the text hightlight.
    

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4306b95c-fd66-550f-0dd5-3b5d57d5295c
* Version Independent ID: ec6963a2-bbd4-9269-adfd-88a2bf40df05
* Content: [How to: Create Outlined Text](https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/how-to-create-outlined-text)
* Content Source: [docs/framework/wpf/advanced/how-to-create-outlined-text.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/advanced/how-to-create-outlined-text.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thank you for your feedback @macginitie. We'll get that fixed.
