### ISSUE TITLE
Working with LINQ tutorial needs a little work

### ISSUE THREAD

**Issue by perk32725** [dotnet/docs#7829]
I would like to see some additions to this tutorial; specifically, when adding a snippet of code, it would be useful to point out which file the snippet actually belongs to (Program.cs, extensions.cs, etc). Also, when a new "using" directive is needed, that could be added as well. While I don't mind digging in to the github repository, having this information at hand would make this tutorial more illuminating.
Just my $0.02, and thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a2b7453-076c-a18e-f999-cbd57ab13e60
* Version Independent ID: b687ed5b-5013-cceb-01e5-77f9cc7bb534
* Content: [Working with LINQ](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/working-with-linq)
* Content Source: [docs/csharp/tutorials/working-with-linq.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/working-with-linq.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by jmarkman** [comment]
Hi, although I've got another issue cooking, I'd like to work on this ticket as well; I actually have ground work on it already.

**Comment by regal60740** [comment]
Another problem I ran into is where does "select new PlayingCard(s, r))" come from. I guess I have to continue to refer to GitHub code to see what is going on.
