### ISSUE TITLE
Please add/modify an example to have at least one usage of XAttribute

### ISSUE THREAD

**Issue by cowlinator** [dotnet/docs#7830]
Please add/modify an example to have at least one usage of XAttribute

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e560c974-8b41-6f50-2997-e512c7e49134
* Version Independent ID: d55b88af-c6bd-a2ed-f64d-a58dd158675a
* Content: [Creating XML Trees in C# (LINQ to XML)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/linq/creating-xml-trees-linq-to-xml-2)
* Content Source: [docs/csharp/programming-guide/concepts/linq/creating-xml-trees-linq-to-xml-2.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/linq/creating-xml-trees-linq-to-xml-2.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by rpetrusha** [comment]
Thanks, @cowlinator, for your feedback.  The topic certainly could benefit from an XAttribute usage example. We've added it to our backlog.
