### ISSUE TITLE
Missing command-line option docs

### ISSUE THREAD

**Issue by VPeruS** [dotnet/docs#7835]
You can use .sln file to build your projects, `dotnet build -h` also missing this

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 910cd365-d63a-00dc-417c-db017f83bf6f
* Version Independent ID: 5e495ddd-140e-de5c-a793-d4a9f88be51e
* Content: [dotnet build command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-build?tabs=netcore2x)
* Content Source: [docs/core/tools/dotnet-build.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-build.md)
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by KathleenDollard** [comment]
I'm a bit confused about the -h comment as that appears to be there. 

@livarcocc and @mairaw is there a way for us to include the solution in the syntax. We could include it in the text quite easily

**Comment by Thraka** [comment]
@mairaw I'll nab this P1

@KathleenDollard if you run the `-h` help in dotnet core doesn't specify that it also works on solution files, though it does. The documentation also omits this.

I'm going to fix this in the documentation, but what should we do to get this fixed in the dotnet core cli help?

Also, does the 1.x cli support solution files?

**Comment by mairaw** [comment]
Sounds good @Thraka! Thank you!

**Comment by livarcocc** [comment]
It always has worked on solution files. Thought dotnet test on solution files is being worked on and dotnet publish does work well either.

**Comment by Thraka** [comment]
Ok, good to know. I just got done doing a simple test with 1.1 in a container to verify :)

**Comment by KathleenDollard** [comment]
Livar left out a word here: 

>It always has worked on solution files. Thought dotnet test on solution files is being worked on and dotnet publish does NOT work well either.
