### ISSUE TITLE
word missing?

### ISSUE THREAD

**Issue by macginitie** [dotnet/docs#7836]
after 'as': "...objects can be declared as , shared among multiple objects, made read-only to improve performance, cloned, and made thread-safe."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c601379b-db4e-11e5-85d1-29e8fa9cf2d2
* Version Independent ID: a54aea44-1a05-19a1-4de6-969c63b188e5
* Content: [Geometry Class (System.Windows.Media)](https://docs.microsoft.com/en-us/dotnet/api/system.windows.media.geometry?view=netframework-4.7.2)
* Content Source: [xml/System.Windows.Media/Geometry.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Windows.Media/Geometry.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks for reporting this @macginitie. We'll get it fixed.
