### ISSUE TITLE
Another Custom Partitioner with same "shared IEnumator" between parition of parallel.foreach 

### ISSUE THREAD

**Issue by bubba9999** [dotnet/docs#7848]
https://stackoverflow.com/questions/52457816/is-there-a-way-to-change-how-parallel-foreach-interlaces-an-array-that-its-opera

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a8a3e55-3be6-6f3b-9eb0-6556558c1399
* Version Independent ID: dada060c-49e0-f200-cb3a-1c50c37da1c0
* Content: [Custom Partitioners for PLINQ and TPL](https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/custom-partitioners-for-plinq-and-tpl)
* Content Source: [docs/standard/parallel-programming/custom-partitioners-for-plinq-and-tpl.md](https://github.com/dotnet/docs/blob/master/docs/standard/parallel-programming/custom-partitioners-for-plinq-and-tpl.md)
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by mairaw** [comment]
Thanks for your feedback @bubba9999. @stephentoub could you help with this issue?

**Comment by stephentoub** [comment]
What's the question?

**Comment by mairaw** [comment]
@bubba9999 can you please provide more information about your issue so we can understand it better?

**Comment by mairaw** [comment]
Closing due to the lack of response.
