### ISSUE TITLE
jannatfb 

### ISSUE THREAD

**Issue by jannatfb** [dotnet/docs#7850]
- [x] Domain name: @jannatfb.com #7106  [server](url) `http://www.jannatfb.com`
[About](url)  [Contact](url) [privacy](url) [policy](url) [press](url) [blog](url) [service](url)  [support](url) [apply](url) [docs.microsoft.com](url) 
[wikidot.com](url) 

  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 298f66a4-8f7f-5d66-0e9a-454fbcad5af7
* Version Independent ID: 62a306ee-be56-b5fa-8d47-8f1a7afd1ef6
* Content: [AppDomain.ActivationContext Property (System)](https://docs.microsoft.com/en-us/dotnet/api/system.appdomain.activationcontext?view=netframework-4.7.2#System_AppDomain_ActivationContext)
* Content Source: [xml/System/AppDomain.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System/AppDomain.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
No actionable feedback. Closing.
