### ISSUE TITLE
Better example need

### ISSUE THREAD

**Issue by lm28** [dotnet/docs#7851]
Trying to follow https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/sort-filter-page?view=aspnetcore-2.1, but I'm having trouble to get my code working.
I therefore referred to the sample code (see the Student\Student.cshtml.cs file) on GitHub, and found it riddled with #if/#endif statements, but no explanation. Hence my visit to this page.
Your example above, refers to target frameworks or configuration  (and I doubt that #if/#endif is limited to only these parameters).
So, either the sample code in the abovementioned article is faulty, or the content itself is missing vital info. 
Either way, if you made reference to the sample code used by Rick, (assuming that there is no error in his code) your explanation might be  more helpful to learners like me.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a331b150-4033-7629-75ad-9f9ea74f3ce5
* Version Independent ID: 8e0adfd9-c41b-d059-a418-155021a95d7b
* Content: [#if preprocessor directive (C# Reference)](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/preprocessor-directives/preprocessor-if)
* Content Source: [docs/csharp/language-reference/preprocessor-directives/preprocessor-if.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/preprocessor-directives/preprocessor-if.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by pkulikov** [comment]
@lm28 
>Your example above, refers to target frameworks or configuration (and I doubt that #if/#endif is limited to only these parameters).

You're right: `#if` can be used with the user-defined symbols as well. The first example in the [Examples section](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/preprocessor-directives/preprocessor-if#examples) shows how to define a symbol (`MYTEST`) and use it with `#if` and other symbols.

What makes you think that "the content itself is missing vital info"?

**Comment by lm28** [comment]
Hi pkulikov
Believe this or not, as an absolute newbie have I dived into ASP.Net Core2 for Razor Pages and followed the instructions to the 'T'...and yet I run into issues. (Sometimes, what works today, doesn't work tomorrow after rebooting my machine? For example: Today for the first time ever, I got an error saying that there was an unexpected literal string in my @model statement. But I haven't change that line of code in two weeks) anyhow...I digress.
When I went to the sample code to see where I was going wrong, I was suddenly confronted with the #if statements and had no idea how they were being used. (This concept had not been discussed anywhere in the Razor Pages tutorial - hence my statement "the content is missing vital info")
I find that the majority of the MS reference pages the authors try to keep their content as concise as possible, but this often leaves the newbie thinking that they must somehow absorb 'missing' info by osmosis!
And by 'missing', I mean that the author assumes that the reader already has some knowledge. But unfortunately, that is not always the case.

Coming back to your example, it was still not clear to me how the feature is used.
After putting my question out on SO, (see https://stackoverflow.com/a/52464308/10051727) ,  Frank Ferardo was able to put the sample code in context for me. I found his explanation VERY informative.  In fact, I shall be using the #if/#endif feature whenever I edit existing code in future.

I understand that its really difficult to predict your target audience (newbies vs seasoned user who want a 'quick' answer), but the newbies will take a LOT longer to become seasoned users when the given information seems to be cryptic.  So for newbies, verbose is better than concise!
Thanks

**Comment by lm28** [comment]
Sorry...just as an aside note here. I have used #region/#endregion before.
My understanding is that #region/#endregion is not processed, (ie: its ignored by the processor) but rather, its a 'handy' navigation tool for the developer.
I therefore assumed (incorrectly) that any # was simply a comment tag on steroids (ie # has the ability to collapse/expand content in the block)

**Comment by pkulikov** [comment]
@Im28 thank you for feedback, I think the doc text can be made clearer about user defined symbols. @BillWagner if you are fine with that, please assign this issue to me.

**Comment by mairaw** [comment]
@pkulikov Bill is at Ignite this week so it might take a while for him to see this. Tagging @Rick-Anderson as well since the original statement is about a topic on ASP.NET Core docs.

**Comment by Rick-Anderson** [comment]
@lm28 	 writes:
> Trying to follow docs.microsoft.com/en-us/aspnet/core/data/ef-rp/sort-filter-page?view=aspnetcore-2.1, but I'm having trouble to get my code working.

I can tell you the code works and we have lots of reported customers telling us it works. It's an advanced tutorial. 
Can you try https://github.com/aspnet/Docs/tree/master/aspnetcore/data/ef-rp/intro/samples/21StageSnapShots/Part-3-Sorting
It doesn't have many `#region` statements.

**Comment by Rick-Anderson** [comment]
@lm28 can you close this issues since it has nothing to do with the article you opened it against?

The `#if` blocks in the the download sample you looked at are used to have multiple stages of the tutorial. The link I sent should work better for you.

**Comment by mairaw** [comment]
Closing this issue then. If you're still having problems @lm28, please let us know.
