### ISSUE TITLE
KeyPress, KeyDown documentation very poor.

### ISSUE THREAD

**Issue by msheliga1** [dotnet/docs#7852]
A complete example of how to get an event to run would be extremely helpful.  Details about which key was pressed are not important.  Getting the handler to run is both crucial and extremely hard to get working.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d132e3a6-8c55-e1a7-db68-d784a538fa71
* Version Independent ID: 3e634cb6-391d-87d3-8bdc-884864559543
* Content: [Control.KeyPress Event (System.Windows.Forms)](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.control.keypress?view=netframework-4.7.2)
* Content Source: [xml/System.Windows.Forms/Control.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Windows.Forms/Control.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
Thanks for pointing out the need for a complete example, @msheliga1. We've added your issue to our backlog, as well as to the community contributor's project.
