### ISSUE TITLE
Specify overloads

### ISSUE THREAD

**Issue by imba-tjd** [dotnet/docs#7857]
See the two overloads' `Remark` section

> Use the [CopyTo](https://docs.microsoft.com/en-us/dotnet/api/system.io.fileinfo.copyto?view=netframework-4.7.2) method to allow overwriting of an existing file

> Use this method to allow or prevent overwriting of an existing file. Use the [CopyTo](https://docs.microsoft.com/en-us/dotnet/api/system.io.fileinfo.copyto?view=netframework-4.7.2) method to prevent overwriting of an existing file by default. 

The first link was meant to link to the second overload and the second link to the first.

---

I have read https://github.com/dotnet/docs/blob/master/styleguide/template.md but I didn't find a way to look up an overload of a function in xref. It only says how to change from an overload one to a generic one. And as far as I tried, searching `ms.assetid` in api docs will get nothing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9d30864-d911-3e65-3aa7-5b75bdb7bd8f
* Version Independent ID: 457bfa45-ef57-2da5-f55d-09751e3e335a
* Content: [FileInfo.CopyTo Method (System.IO)](https://docs.microsoft.com/en-us/dotnet/api/system.io.fileinfo.copyto?view=netframework-4.7.2#System_IO_FileInfo_CopyTo_System_String_)
* Content Source: [xml/System.IO/FileInfo.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.IO/FileInfo.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
In these cases, @imba-tjd, the xref links have to include the method parameters. So the first one should be \<xref:System.IO.FileInfo.CopyTo(System.String,System.Boolean)>. The second should be \<xref:System.IO.FileInfo.CopyTo(System.String)>. Would you like us to open a PR to make the change, or would you like to make it?

**Comment by mairaw** [comment]
We do talk about the xref site to search for overloads. Did you try that @imba-tjd? For example, https://xref.docs.microsoft.com/autocomplete?text=CopyTo

**Comment by fenxu** [comment]
@mairaw As I mentioned in Teams Channel, the xref auto complete service hasn't running for a long time. So, I think recently new added methods won't be added into current API response. If you still want to enable auto complete service again, please contact with @meganbradley (PM of that feature)

cc @TianqiZhang

**Comment by imba-tjd** [comment]
Will you team still track this issue or perhaps reopen it?:joy:

**Comment by mairaw** [comment]
No need @imba-tjd. I’m following up offline with them.
