### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by SezMe** [dotnet/docs#7858]
The link under See Also is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6b338a6-e07d-9e98-4958-ec16be074c84
* Version Independent ID: ec2f540f-f2ce-c60b-37c2-13f33c304a10
* Content: [ItemsControl.Items Property (System.Windows.Controls)](https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.itemscontrol.items?view=netframework-4.7.1#System_Windows_Controls_ItemsControl_Items)
* Content Source: [xml/System.Windows.Controls/ItemsControl.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Windows.Controls/ItemsControl.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
Thanks for reporting the broken link, @SezMe. I've opened dotnet/docs#547 to fix it.
