### ISSUE TITLE
Link to CNTK is broken

### ISSUE THREAD

**Issue by kkm000** [dotnet/docs#7859]
The link to CNTK (first paragraph under the `#type-abbreviations` anchor) does not work. This, with added `en-us/`, does: https://www.microsoft.com/en-us/cognitive-toolkit/

Not clear with what part the fault lies, as many MS links do work when the language ID is not present (all KB links do, for example, as does this very site). But anyway, as is, it does not work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 402e43bd-76b8-a1c8-2c62-e14017f5ed1e
* Version Independent ID: 990e56cd-648d-45c4-30e0-b221874ec329
* Content: [F# coding conventions](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/conventions#type-abbreviations)
* Content Source: [docs/fsharp/style-guide/conventions.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/style-guide/conventions.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by cartermp** [comment]
Looks like it's en-us only. I'll update this shortly.
