### ISSUE TITLE
Sample problem

### ISSUE THREAD

**Issue by Mackhdo** [dotnet/docs#7861]
I can't find the problem but with the exact code of this tutorial, my output is this:
Not adding a normalizer.
Making per-feature arrays
Changing data from row-wise to column-wise
  Bad value at line 7 in column Label
  Bad value at line 186 in column Label
  Bad value at line 111 in column Label
  Bad value at line 8 in column Label
  Bad value at line 9 in column Label
  Bad value at line 10 in column Label
  Bad value at line 11 in column Label
  Bad value at line 12 in column Label
  Suppressing further bad value messages
  Bad value at line 187 in column Label
  Bad value at line 112 in column Label
Processed 1628 rows with 1593 bad values and 0 format errors
Processed 2 instances
Binning and forming Feature objects
Reserved memory for tree learner: 108 bytes
Starting to train ...
Warning: 5 of the boosting iterations failed to grow a tree. This is commonly because the minimum documents in leaf hyperparameter was set too high for this dataset.
Not training a calibrator because it is not needed.
  Bad value at line 7 in column Label
  Bad value at line 183 in column Label
  Bad value at line 111 in column Label
  Bad value at line 8 in column Label
  Bad value at line 184 in column Label
  Bad value at line 185 in column Label
  Bad value at line 186 in column Label
  Bad value at line 188 in column Label
  Suppressing further bad value messages
  Bad value at line 9 in column Label
  Bad value at line 112 in column Label
Processed 866 rows with 829 bad values and 0 format errors

PredictionModel quality metrics evaluation
------------------------------------------
Accuracy: 0,00 %
Auc: NaN
F1Score: NaN

Sentiment Predictions
---------------------
Sentiment: Please refrain from adding nonsense to Wikipedia. | Prediction: Negative
Sentiment: He is the best, and the article should say that. | Prediction: Negative

It seems there is a problem with the value of the sample ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8e22825-c4ee-5a36-f911-8ad456970ecc
* Version Independent ID: ad0bf640-7dfc-1184-077c-358bb14277a7
* Content: [Use ML.NET in a sentiment analysis binary classification scenario](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/sentiment-analysis#)
* Content Source: [docs/machine-learning/tutorials/sentiment-analysis.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/sentiment-analysis.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johnalex**

**Comment by mairaw** [comment]
@JRAlexander can you please triage this one?

**Comment by JRAlexander** [comment]
@Mackhdo, you need to check your data files. Most likely they are the html. You need to download the raw files and you should be good to go.

**Comment by JRAlexander** [comment]
Closing. Please reopen if you still have issues.
