### ISSUE TITLE
No code, no good

### ISSUE THREAD

**Issue by KamranBehzad** [dotnet/docs#7862]
You give a couple of programmatic Line examples. As soon as you go into Geometries and paths, you shift into xaml! Why? Where are the code examples for geometries? If we need to draw thousands of shapes we are gonna b doing it with xaml!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6e810a3-6843-918e-4406-d13ca007a139
* Version Independent ID: 22b01fce-7843-fa89-6586-13fe0f322de4
* Content: [Shapes and Basic Drawing in WPF Overview](https://docs.microsoft.com/en-us/dotnet/framework/wpf/graphics-multimedia/shapes-and-basic-drawing-in-wpf-overview)
* Content Source: [docs/framework/wpf/graphics-multimedia/shapes-and-basic-drawing-in-wpf-overview.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/graphics-multimedia/shapes-and-basic-drawing-in-wpf-overview.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thank you for your feedback @KamranBehzad. We've added this to our backlog.
