### ISSUE TITLE
Please use existing APIs.

### ISSUE THREAD

**Issue by kunom** [dotnet/docs#7865]
`Nullable.GetUnderlyingType(type) != null` would exactly do the job with almost no additional code. Why isn't it mentioned?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6f96935-2039-9c62-9a91-996bdf6e0ae5
* Version Independent ID: 567637a1-bc1b-9b07-762d-c14530d6ca38
* Content: [How to: Identify a nullable type (C# Programming Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/nullable-types/how-to-identify-a-nullable-type#feedback)
* Content Source: [docs/csharp/programming-guide/nullable-types/how-to-identify-a-nullable-type.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/nullable-types/how-to-identify-a-nullable-type.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by pkulikov** [comment]
@kunom thanks for the observation, the current doc code almost repeats the `GetUnderlyingType` implementation. I will update the code example.
