### ISSUE TITLE
Change absolute URLs to APIs to use the xref syntax

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#787]
There are several topics that are using absolute URLs to docs instead of using the API linking syntax, such as this topic:
https://github.com/dotnet/core-docs/blob/master/docs/standard/collections/index.md

The following topic shows an example of how to use the @ syntax:
https://raw.githubusercontent.com/dotnet/core-docs/master/api/index.md

What follows the @ symbol, it's the API UID. An explanation of the UID and how to use it can be found here: https://dotnet.github.io/docfx/spec/docfx_flavored_markdown.html#cross-reference

Right now, there is no easy way to find the UIDs. The best way to confirm what's the right one is by searching for the type in this repo: https://github.com/docascode/coreapi

**Comment by isaac2004** [comment]
@mairaw what is the status of this issue? Ongoing?

**Comment by mairaw** [comment]
Let me check on this one @isaac2004. We also changed the guidance to use the xref syntax (`<xref:UID>` instead of `@UID`).

**Comment by isaac2004** [comment]
Oh that is what I assumed was being referred to :)

**Comment by mairaw** [comment]
I think we might have some of these conversions left to do as well from `@` to xref. 

The first topics that got manually migrated were actually linking to the APIs with an absolute URL (https://docs.microsoft.com/dotnet/core/api/System.Collections.IEnumerable) as you can see in this commit:
https://github.com/dotnet/docs/commit/cfe65fcba1b3fdc09ffcac704a760d8ce29ea60b#diff-cca8a3e6c48b40ade7f58c2fb0edc73b
So that was what this issue was about. This might be finished already. Then I'd open a new one for the conversion from `@` to xref.

**Comment by rpetrusha** [comment]
@mairaw, since we're using the xref: syntax, should this issue be closed?

**Comment by mairaw** [comment]
@rpetrusha I'll assign this to myself to finish. It's only 4 files left.

**Comment by isaac2004** [comment]
Oh no, I totally forgot about this one. Thanks for being great @mairaw!

**Comment by mairaw** [comment]
We did too @isaac2004. No worries!
