### ISSUE TITLE
IStructuralComparable.CompareTo() documentation "Returns" is incorrect

### ISSUE THREAD

**Issue by irontoby** [dotnet/docs#7874]
[Enter feedback here]
Documentation indicates that `IStructuralComparable.CompareTo(object other, System.Collections.IComparer comparer)` returns -1, 0, or 1. This is incorrect. It can return _any_ number less than zero if current instance precedes `other`, and _any_ number greater than zero if current instance follows `other`.

Compare to [correct documentation here](https://docs.microsoft.com/en-us/dotnet/api/system.icomparable.compareto?view=netcore-2.1) for IComparable.CompareTo().

Simple test case:

    var val1 = new byte[] { 0, 55, };
    var val2 = new byte[] { 0, 99, };

    var comp = ((IStructuralComparable)val1).CompareTo(val2, Comparer<byte>.Default);
    Console.WriteLine(comp); // writes -44, not -1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 875e11d9-d3e8-71fa-9068-04762037896e
* Version Independent ID: 5662d353-4f93-21f9-bc0a-c5dc586e7cc7
* Content: [IStructuralComparable.CompareTo(Object, IComparer) Method (System.Collections)](https://docs.microsoft.com/en-us/dotnet/api/system.collections.istructuralcomparable.compareto?view=netcore-2.1)
* Content Source: [xml/System.Collections/IStructuralComparable.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Collections/IStructuralComparable.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
Thanks for pointing this out, @irontoby. We've opened dotnet/dotnet-api-docs#555 to correct the issue.
