### ISSUE TITLE
Typo: it should be "an exception" instead of "a exception" 

### ISSUE THREAD

**Issue by jwatkin** [dotnet/docs#7876]
I believe the words "You can also use a exception filter ..." should have been written as "You can also use an exception filter ...". 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8cde2a6-1c92-8b1e-a795-4b1e04510575
* Version Independent ID: 3b8f6b0d-08a9-0730-3241-da241f8444b4
* Content: [try-catch (C# Reference)](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/try-catch)
* Content Source: [docs/csharp/language-reference/keywords/try-catch.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/try-catch.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
Thanks for the feedback @jwatkin. Yes, you're right! Would you like to submit a pull request to fix this? Our contributor guide has instructions on how to make quick fixes like that: https://docs.microsoft.com/en-us/contribute/#quick-edits-to-existing-documents.
