### ISSUE TITLE
Required field indicator

### ISSUE THREAD

**Issue by lm28** [dotnet/docs#7881]
Suppose that I have a required field in my database. 
Could I use the DisplayFormatAttribute to highlight the DisplayName in say a different colour and or font, so that the user knows a field is required. 
I appreciate that norm appears is simply put an asterisk (or other symbol) in the DisplayName.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51af23c7-832d-b4db-a403-68e7a5ee5e09
* Version Independent ID: 99860299-dbda-74c6-785e-9c5856588a8f
* Content: [DisplayFormatAttribute Class (System.ComponentModel.DataAnnotations)](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.dataannotations.displayformatattribute?view=netcore-2.1)
* Content Source: [xml/System.ComponentModel.DataAnnotations/DisplayFormatAttribute.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.ComponentModel.DataAnnotations/DisplayFormatAttribute.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **riande**

**Comment by Thraka** [comment]
@lm28 Hi! The string format is just that, a string. It is up to the display system to determine how to render the string. For example, setting a "color" for a console app is different than setting "color" in a WPF app. 

You would need to setup whatever is reading and displaying that string to respect some sort of color setting. You could also inherit from `DisplayFormatAttribute` to add other properties like color or `IsRequired` but still, you need to have the rendering side of things know about your custom class.

Let me know if this answers your question or not.

**Comment by lm28** [comment]
Thanks Thraka.
While I am not quite sure how to implement this in a ASP.Net Core for Razor page, your reply makes sense.
