### ISSUE TITLE
List<string> does not contain a definition for Changed

### ISSUE THREAD

**Issue by solaomosola** [dotnet/docs#7884]
List&lt;string&gt; names = new List&lt;string&gt;();
names.Changed += new EventHandler(ListChanged);
List&lt;T&gt; does not contain a definition for Changed. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8181f41d-b6ce-ad66-084e-8d2b514b87e2
* Version Independent ID: 494c4344-b752-4f86-5b66-1ef4b81c1e75
* Content: [Classes and Objects in C# - A tour of the C# Language](https://docs.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/classes-and-objects#other-function-members)
* Content Source: [docs/csharp/tour-of-csharp/classes-and-objects.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tour-of-csharp/classes-and-objects.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by pkulikov** [comment]
@solaomosola it's not the perfect naming. The `List` class used is not the standard .NET class, but the one defined earlier in the topic:
https://docs.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/classes-and-objects#other-function-members

**Comment by solaomosola** [comment]
Okay, I understand now. That should be changed or a little note added to explain that. Thank you.

**Comment by Thraka** [comment]
Agreed. I think we should actually change the name of the class to `MyList` or something else. We shouldn't use an extremely common class name like `List`.

**Comment by Thraka** [comment]
@BillWagner I know you're out this week but I'm assigning this to you. I "triaged" it the best I could so feel free to adjust anything and everything when you get back.
