### ISSUE TITLE
Excellent!

### ISSUE THREAD

**Issue by sujon2100** [dotnet/docs#7899]
Very nice explanation. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bc2f58f-8fbc-9ff2-2312-8a5715536f1f
* Version Independent ID: 1dbd0d51-e1dc-8970-93f8-2a44fa71f7ba
* Content: [as (C# Reference)](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/as)
* Content Source: [docs/csharp/language-reference/keywords/as.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/as.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by rpetrusha** [comment]
Thanks, @sujon2100. We're pleased that you found the article useful.
