### ISSUE TITLE
Define Guidance for TOC and URLs

### ISSUE THREAD

**Issue by richlander** [dotnet/docs#790]
# Proposal for TOC and URLs

We are going to be adding a lot of documentation into this repository and TOC this year, for .NET Core, .NET Framework, UWP and Xamarin. Also, ASP.NET, EF, NuGet and WCF. There are others too, that I'm missing. We need a good model for structuring the repository, which directly impacts URLs, and for managing the TOC. Every team that adds content to the repository should know what to do and the final result should be consistent. We need a plan in preparation for all of this effort and activity.
## Model

We've adopted the concept of "Guides" for .NET products and the bigger technology areas (like a language). I don't think we intend everything to be a "Guide". Instead, I think we should have "Guides" and "Technologies". For example, .NET Core would have a Guide and WCF and EF would fall under Technologies.
## TOC

The TOC will present "Guides" at the top-level and put "Technologies" under a top-level node of the same name.
- .NET Core Guide
- .NET Framework Guide
- C# Guide
- ASP.NET Guide
- Technologies
  - WCF
  - EF
  - WPF
  - NuGet

This approach has the advantage of maintaining a slim(ish) TOC, providing everything a home, limiting duplication across Core and Framework (many of the technologies apply to both) and providing attention on the top-level topics as guides.

The major question, then, is which things should be "Guides". ASP.NET is in a bit of a middle ground there. It's basically a "Technology" that rises to the level of a "Guide". I suspect that this will be a subjective decision and may change over time.
## URLs and Repo Structure

From a URL and repo structure standpoint, guides and technologies will be the same.

Examples Guides:
- https://docs.microsoft.com/dotnet/standard (.NET Standard Guide)
- https://docs.microsoft.com/dotnet/core (.NET Core Guide)
- https://docs.microsoft.com/dotnet/framework (.NET Framework Guide)
- https://docs.microsoft.com/dotnet/csharp (C# Guide)

Example Technologies:
- https://docs.microsoft.com/dotnet/nuget (NuGet libraries, command-line and server)
- https://docs.microsoft.com/dotnet/ef (EF libraries)
- https://docs.microsoft.com/dotnet/roslyn (roslyn libraries)

Some components have multiple versions, that target .NET Framework and .NET Core. EF is a good example. We'll expect to see three URLs exposed for EF:
- https://docs.microsoft.com/dotnet/ef (describes EF generally)
- https://docs.microsoft.com/dotnet/ef/core (describes EF Core)
- https://docs.microsoft.com/dotnet/ef/framework (describes EF that targets .NET Framework)

**Comment by BillWagner** [comment]
I like the model, and the TOC.

To get the URLs to match the model an the TOC, should you add a 'technologies' element to the path:

> Some components have multiple versions, that target .NET Framework and .NET Core. EF is a good example. We'll expect to see three URLs exposed for EF:
> • https://docs.microsoft.com/dotnet/ef (describes EF generally)
> • https://docs.microsoft.com/dotnet/ef/core (describes EF Core)
> • https://docs.microsoft.com/dotnet/ef/framework (describes EF that targets .NET Framework)
> 

Would become:

Some components have multiple versions, that target .NET Framework and .NET Core. EF is a good example. We'll expect to see three URLs exposed for EF:
• https://docs.microsoft.com/dotnet/technologies/ef (describes EF generally)
• https://docs.microsoft.com/dotnet/technologies/ef/core (describes EF Core)
• https://docs.microsoft.com/dotnet/technologies/ef/framework (describes EF that targets .NET Framework)

the positive side is that it puts all the EF materials in one location under a larger umbrella (which is implied in the TOC). 

The negative side is that it's a longer URL.

**Comment by richlander** [comment]
@BillWagner Indeed, this is the key choice. There are two challenges with this other proposal:

- Longer URL (as you raised)
- Hard distinction between things we make "Guide" vs "Technology" and awkward to change over time and also hard for customers to guess the URLs.

**Comment by BillWagner** [comment]
@richlander I'd like to see this flushed out for asp.net. That should help land in the right spot.

I was keying on this statement:

> Some components have multiple versions, that target .NET Framework and .NET Core.

That wouldn't be true for anything that rose to the level of "guides". I may be approaching this from too much of a language perspective: C#, VB.NET, and F# will be the same for core and .NET Framework. EF (and other technologies) will have different features for different versions.

ASP.NET is the one location where we've defined a "Guide" that has differences between the .NET Framework and .NET Core. How would that be presented?

**Comment by cartermp** [comment]
Since we basically have a good TOC and URL structure/model, we're closing this.
