### ISSUE TITLE
Nice.

### ISSUE THREAD

**Issue by sujon2100** [dotnet/docs#7900]
new, virtual, base: all in one place.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27ea7de0-7f9a-cbda-2e6f-69dbc9a9601b
* Version Independent ID: d213dce7-2e17-07c6-5f97-47b3e391976c
* Content: [base keyword (C# Reference)](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/base)
* Content Source: [docs/csharp/language-reference/keywords/base.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/base.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
Thank you for your feedback @sujon2100! We appreciate it.
