### ISSUE TITLE
Suggestion on the guideline

### ISSUE THREAD

**Issue by GordonLam** [dotnet/docs#7903]
In case my scenario is fully disable SSL 3.0 and TLS 1.0 and 1.1, I need to update registry key setting anyway.
The simple decision to read this guideline should be like:
1. For &gt;=.net 4.0 and &lt; .net 4.7, I should apply EXTRA registry setting
https://docs.microsoft.com/en-us/dotnet/framework/network-programming/tls#configuring-security-via-the-windows-registry
2. For &lt;= .net 3.5, I should be aware of code change should be required.
https://docs.microsoft.com/en-us/dotnet/framework/network-programming/tls#if-your-app-targets-net-framework-35​
https://support.microsoft.com/en-us/help/3154520/support-for-tls-system-default-versions-included-in-the-net-framework​

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7341fa0a-f474-6c2d-d3c0-7e2df12fbb65
* Version Independent ID: e99c489a-7518-d293-ad93-7eaca8b7191a
* Content: [Transport Layer Security (TLS) best practices with the .NET Framework](https://docs.microsoft.com/en-us/dotnet/framework/network-programming/tls#configuring-security-via-the-windows-registry)
* Content Source: [docs/framework/network-programming/tls.md](https://github.com/dotnet/docs/blob/master/docs/framework/network-programming/tls.md)
* Product: **dotnet-framework**
* GitHub Login: @blowdart
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
@Blowdart, can you comment?


Thanks for submitting your feedback, @GordonLam. We'll investigate.

**Comment by blowdart** [comment]
Disabling SSL is not part of this document, so IMO it'd muddy the waters.

**Comment by Thraka** [comment]
Closing this due to suggestion that this not be implemented.
