### ISSUE TITLE
Lambda expressions

### ISSUE THREAD

**Issue by edwinmuraya** [dotnet/docs#7906]
Nice docs..Great work. Thanks for the support

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12c8b202-5b65-9d30-d57e-dd060a507b9a
* Version Independent ID: 92cfc461-56ed-c046-bb03-cc5e46ebf5ba
* Content: [Lambda Expressions](https://docs.microsoft.com/en-us/dotnet/csharp/lambda-expressions)
* Content Source: [docs/csharp/lambda-expressions.md](https://github.com/dotnet/docs/blob/master/docs/csharp/lambda-expressions.md)
* Product: **dotnet-csharp**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by Thraka** [comment]
Thank you!!
