### ISSUE TITLE
Sendkeys vs SendInput

### ISSUE THREAD

**Issue by thomb1** [dotnet/docs#7910]
Does SendKeys eventually resolve down to a SendInput call with an array of KEYBDINPUT structures? The above hints that it does (SendWait discusses messages ...)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2974536-2af9-ba39-a1ec-0901b9b24335
* Version Independent ID: edebaaa9-b33c-22ff-87be-518c0f274346
* Content: [SendKeys.Send(String) Method (System.Windows.Forms)](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.sendkeys.send?view=netframework-4.7.2)
* Content Source: [xml/System.Windows.Forms/SendKeys.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Windows.Forms/SendKeys.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by Thraka** [comment]
Seems like it: https://referencesource.microsoft.com/#System.Windows.Forms/winforms/Managed/System/WinForms/SendKeys.cs,594

I'm going to close this question. If you have any other questions, please feel free to comment or reopen. 😄

**Comment by thomb1** [comment]
Hi Andy,
Thank you! I forgot that you can access the source code like that – very cool that you’all did that. I’m also very impressed with how quickly you’all have been responding to these sorts of questions/feedback.
Regards,
Thom

Thom C. Blackwell,  VP Technical Services
Boston Software Systems, Inc.
Phone: 866.653.5105 x807
Mobile: 508.423.8463
Fax: 508.319.3015
www.bostonsoftwaresystems.com<http://www.bostonsoftwaresystems.com/>

The information contained in this message may be confidential and legally protected under applicable law. The message is intended solely for the addressee(s). If you are not the intended recipient, you are hereby notified that any use, forwarding, dissemination, or reproduction of this message is strictly prohibited and may be unlawful. If you are not the intended recipient, please contact the sender by return e-mail and destroy all copies of the original message.

**Comment by Thraka** [comment]
You're welcome :) We're trying to keep up with them, but there are a lot :D
