### ISSUE TITLE
make final page more helpful

### ISSUE THREAD

**Issue by abdo1819** [dotnet/docs#7913]
it was a good quick start it would be good if you add links for good courses
or a book or even a deeper tutorial in c# and .net 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d9e98de-9df3-d63f-f6a6-aa079eb5095f
* Version Independent ID: a057574c-020f-a9f0-9dfc-f8936a1132fe
* Content: [Collections interactive tutorial - C# quickstarts](https://docs.microsoft.com/en-us/dotnet/csharp/quick-starts/list-collection?tutorial-step=7)
* Content Source: [docs/csharp/quick-starts/list-collection.yml](https://github.com/dotnet/docs/blob/live/docs/csharp/quick-starts/list-collection.yml)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by parthpandyappp** [comment]
I would like to contribute to this...!

**Comment by abdo1819** [comment]
thanks bro books you mentioned seem to be really useful

**Comment by parthpandyappp** [comment]
Why tjis PR didn't merged...?

**Comment by parthpandyappp** [comment]
Why this PR didn't got merged...?

**Comment by svick** [comment]
@parthpandyappp 

@rpetrusha gave you an explanation when he closed your PR in https://github.com/dotnet/docs/pull/8157#issuecomment-427948943. Is that not sufficient for you?

**Comment by parthpandyappp** [comment]
@svick Yes.!
He said that these books were very useful to him the also that PR didn't got merged...?
