### ISSUE TITLE
Compare to certlm.msc and certmgr.msc

### ISSUE THREAD

**Issue by HappyNomad** [dotnet/docs#7916]
How is following these steps different than just running certlm.msc or certmgr.msc?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f950f479-532b-ab38-a676-653495777197
* Version Independent ID: 30fa2c1a-86bd-e683-3e6f-8a268f4dc4e5
* Content: [How to: View Certificates with the MMC Snap-in](https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/how-to-view-certificates-with-the-mmc-snap-in)
* Content Source: [docs/framework/wcf/feature-details/how-to-view-certificates-with-the-mmc-snap-in.md](https://github.com/dotnet/docs/blob/master/docs/framework/wcf/feature-details/how-to-view-certificates-with-the-mmc-snap-in.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by Thraka** [comment]
@HappyNomad I'm going to close this one and keep #7586 open. That article needs to be rewritten with and also needs to show certlm.msc or certmgr.msc
