### ISSUE TITLE
Update DPI Awareness Gold bar topic to include enable/disable setting

### ISSUE THREAD

**Issue by merriemcgaw** [dotnet/docs#7922]
**Issue description**

https://docs.microsoft.com/en-us/dotnet/framework/winforms/disable-dpi-awareness-visual-studio should be updated to include the new tools->options property which allows the user to stop seeing the DPI gold bar message.  We also changed the strings in the gold bar text. @KlausLoeffelmann can provide images.

**Target framework**

Check the .NET target framework(s) being used, and include the version number(s).

- [ ] .NET Core
- [x] .NET Framework
- [ ] .NET Standard

If using the .NET Core SDK, include `dotnet --info` output. If using .NET Framework without the .NET Core SDK, include info from Visual Studio's **Help** > **About Microsoft Visual Studio** dialog.

<details>
<summary><strong>dotnet --info output</strong> or <strong>About VS info</strong></summary>

```console
<replace>
```
</details>

**Comment by mairaw** [comment]
@gewarren this was assigned to sprint 144. Is this done already or should I move?

**Comment by gewarren** [comment]
Oops this fell off my radar. I can do it this week.

**Comment by gewarren** [comment]
@merriemcgaw I assume this is the setting in Tools > Options > Windows Forms Designer?

![image](https://user-images.githubusercontent.com/24882762/50115183-81f13b00-01fb-11e9-81fd-57023f5a810e.png)

**Comment by merriemcgaw** [comment]
@gewarren , you are correct. @KlausLoeffelmann  can answer any technical questions you may have.
