### ISSUE TITLE
Feature request - add search / browse

### ISSUE THREAD

**Issue by TimJarvis** [dotnet/docs#7923]
I have installed a couple of insanely useful tools - but can't help feeling that there are others out there that I don't know about, would love some kind of discovery mechanism.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0c5b03c-2854-8462-57dc-b0239388096e
* Version Independent ID: 13b38200-ed54-7bfe-f7cf-099cf1b010f4
* Content: [.NET Core Global Tools](https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools)
* Content Source: [docs/core/tools/global-tools.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/global-tools.md)
* Product: **dotnet-core**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **mairaw**

**Comment by rpetrusha** [comment]
Thanks, @TimJarvis, for your feedback. A list of available global tools would indeed be useful. There may be something in the works.
@livarcocc  @KathleenDollard should we move this issue to another repo?

**Comment by KathleenDollard** [comment]
@TimJarvis 

I'm a PM on the .NET Team. 

We agree!! We hope to do this and are frustrated that it isn't done yet. Sadly it will be a while longer before we can align the work to complete this. 

In the meantime, people can self-register tools [here:](https://github.com/natemcmaster/dotnet-tools)

Feel free to create issues on [dotnet-cli](https://github.com/natemcmaster/dotnet-tools) when you encounter frustrations.

**Comment by TimJarvis** [comment]
Hi Kathleen,

Great to know that it's planned.

Cheers Tim Jarvis.

**Comment by mairaw** [comment]
Thanks @KathleenDollard. We'll close this doc issue then.
