### ISSUE TITLE
Wrong Links when you download PDF

### ISSUE THREAD

**Issue by n1v3k** [dotnet/docs#7925]
Hello guys love the work on this documentation, I used to had a copy of this documentation, but lost that pdf, now that im trying to download again, the bookmark section all links takes you to the incorrect pages, anyway great material especially in pdf form where i can make annotations and whatnot.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3dff5a94-d9cd-e31b-4056-362abbe8d782
* Version Independent ID: cfb1ad21-e822-4075-2726-bd130ec2358d
* Content: [C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/)
* Content Source: [docs/csharp/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/index.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by rpetrusha** [comment]
@dend, can you help with this? The link downloads the .NET Guide, not the C# Guide.

**Comment by n1v3k** [comment]
Its actually the whole .net guide, 1 pdf file +2000 pages long, it used to have all links pointing to the right pages (my old copy months ago) but now the one I just downloaded, all links takes u to wrong pages, but if the guide is used in the browser (no pdf) then all links work fine, they take you to the proper pages.

**Comment by mairaw** [comment]
Given this is a site feature and not a content issue, I've moved this feedback to https://github.com/MicrosoftDocs/feedback/issues/895.
