### ISSUE TITLE
missing 'throws' section

### ISSUE THREAD

**Issue by StephaneDelcroix** [dotnet/docs#7926]
throws AmbiguoudMatchException, and I guess NRE too if name is `null`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82f5859f-bf16-d3dd-5844-0ff0ac944ab2
* Version Independent ID: 8facbdf6-d0d2-b504-eb38-a0fb9d6a3c5a
* Content: [RuntimeReflectionExtensions.GetRuntimeProperty(Type, String) Method (System.Reflection)](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.runtimereflectionextensions.getruntimeproperty?view=netframework-4.7.1#System_Reflection_RuntimeReflectionExtensions_GetRuntimeProperty_System_Type_System_String_)
* Content Source: [xml/System.Reflection/RuntimeReflectionExtensions.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Reflection/RuntimeReflectionExtensions.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
Thanks for pointing out the missing exception information, @StephaneDelcroix. In looking at the source, it appears that the method throws:
- An ArgumentNullException if `t` is null.
- An ArgumentException if `t` is not a RuntimeType.
- An AmbiguousMatchException, if more than one property named `name` is found. 
 We've added this issue to our backlog and will address it in an upcoming sprint. In the meantime, if you'd like to submit a PR to add the missing exception information, we'd welcome your contribution.

**Comment by StephaneDelcroix** [comment]
@rpetrusha thanks. don't forget to review the other ones in `RuntimeReflectionExtensions` while you're at it.
