### ISSUE TITLE
Confusing lock example

### ISSUE THREAD

**Issue by kustox** [dotnet/docs#7927]
Maybe my english isn't good enough, but I'm having difficulties in understanding this example:
"For example, if a container object is to be used by multiple threads, then the container can be passed to lock, and the synchronized code block following the lock would access the container. As long as other threads locks on the same contain before accessing it, then access to the object is safely synchronized."
Did You mean:
  public object containerObjectAcessedByMultipleThreads=new FancyContainer();
  on some thread:
  lock(containerObjectAcessedByMultipleThreads){
    containerObjectAcessedByMultipleThreads.MessWith();
  }
  on some other thread:
  lock(containerObjectAcessedByMultipleThreads){
    containerObjectAcessedByMultipleThreads.MessWith();
  }
and all be ok this way?
If so the last sentence should say:
"As long as other threads lock on the same container before accessing it, access to the object is safely synchronized."
By the way can I syncronize unsafely?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2241f353-b3c7-2ea8-2ac3-2e61c855ae9c
* Version Independent ID: 47ad8e5e-2506-0909-11d0-2f1fddb4ec06
* Content: [Thread Synchronization (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/threading/thread-synchronization#feedback)
* Content Source: [docs/csharp/programming-guide/concepts/threading/thread-synchronization.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/threading/thread-synchronization.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by pkulikov** [comment]
@kustox making it public may introduce problems as you don't know if the clients synchronize access. Keeping it private gives you the full control over how a resource is accessed. In particular, you can put every access behind a lock. And yes, if a container is a reference type, you can lock directly on a container instance.

You are right about the typo in the docs. However, I wouldn't bother fixing it, as this article will be removed by #7790 

An example of unsafe synchronisation is when access to a resource is protected by different locks or one access is behind a lock while another one is not. However, one might say it's not synchronisation at all.

**Comment by kustox** [comment]
Thank you for the clarification.
