### ISSUE TITLE
Images for MessageBox icons

### ISSUE THREAD

**Issue by Danghor** [dotnet/docs#7930]
I think it would be helpful to display sample images from the current operating system (i.e. Windows 10) to see what the icons will look like. This way, chosing the right icon will be faster.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8900db20-f08a-6069-f39e-0ddc260420a3
* Version Independent ID: 59408b8d-e4f7-bf8c-820f-286537ea7eb0
* Content: [MessageBoxIcon Enum (System.Windows.Forms)](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.messageboxicon?view=netframework-4.7.2#feedback)
* Content Source: [xml/System.Windows.Forms/MessageBoxIcon.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Windows.Forms/MessageBoxIcon.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
Thanks for the suggestion, @Danghor. I've added it to our backlog, as well as to the community contributor's project.

**Comment by nic-hartley** [comment]
Alright, I've got the images. Looking for the best way to put them in now, with the help of some Python magic. Wish me luck!

**Comment by rpetrusha** [comment]
Keep us posted, @nic-hartley. And let us know if you have any questions.

**Comment by nic-hartley** [comment]
@rpetrusha Still trying to figure out how to embed images in the Fields section; I can figure out how to do it in the main body, but I'm struggling to get it in there -- it doesn't seem possible, unless I'm missing something.

**Comment by rpetrusha** [comment]
I suspect that it's not possible. The best alternative is to add to the enum description a sentence about the Remarks section containing images for each symbol, and add a table in the Remarks section.

**Comment by nic-hartley** [comment]
That's frustrating, but yeah, it looks like I'll have to do that. I got sucked into another project at work, so this is on the back burner -- I'll have it done by Sunday if no one else has.

**Comment by nic-hartley** [comment]
...Or I'll entirely forget about this until just now. I'll have the images in within... probably three or four hours, at most.

**Comment by nic-hartley** [comment]
@rpetrusha Apologies again for taking so long to get to this, I got distracted by work. (I know, I know, who needs a life when you have open-source...)

How do I build the documentation? I'm pretty sure I've got this done on [my fork](https://github.com/nic-hartley/dotnet-api-docs), but I can't figure out how to build it so I can make sure I actually did it right.
