### ISSUE TITLE
Dead link in .NET Standard 2.0 documentation

### ISSUE THREAD

**Issue by dipidoo** [dotnet/docs#7935]
https://github.com/dotnet/standard/blob/master/docs/planning/netstandard-20/README.md#assembly-unification is a dead link
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de130a75-fed2-0567-6e3d-07a384900eec
* Version Independent ID: a2993c26-93f8-7281-d6ca-5fcc899e95f3
* Content: [What's new in the .NET Standard](https://docs.microsoft.com/en-us/dotnet/standard/whats-new/whats-new-in-dotnet-standard?tabs=csharp)
* Content Source: [docs/standard/whats-new/whats-new-in-dotnet-standard.md](https://github.com/dotnet/docs/blob/master/docs/standard/whats-new/whats-new-in-dotnet-standard.md)
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by rpetrusha** [comment]
Thanks for reporting the broken link, @dipidoo. We've fixed it in #7947.
