### ISSUE TITLE
part of sentence missing?

### ISSUE THREAD

**Issue by macginitie** [dotnet/docs#7936]
The 2nd sentence here: "You can also supply a cancellation token by calling the Wait(CancellationToken) and Wait(Int32, CancellationToken) methods. If the token's IsCancellationRequested property is true, the wait is cancelled; if it becomes true while the Wait method terminates." -- I can't parse it (make sense of it). If it becomes true while the Wait method [is executing?], the Wait method terminates... ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2ed6735-94cc-2017-7e0e-56ec795936c9
* Version Independent ID: 01acc39c-61ed-a138-3b73-5d1d2878cf6e
* Content: [Task Class (System.Threading.Tasks)](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.task?view=netframework-4.7.2)
* Content Source: [xml/System.Threading.Tasks/Task.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Threading.Tasks/Task.xml)
* Product: **dotnet-api**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by rpetrusha** [comment]
Thanks for pointing out the missing text, @macginitie. We've opened dotnet/dotnet-api-docs#565 to address this issue.
