### ISSUE TITLE
out of date?

### ISSUE THREAD

**Issue by macginitie** [dotnet/docs#7938]
"Accept the default name, "image". [similarly for button]" -- does VS supply a default name any more?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8400406-e7fc-8407-2394-dabe839375b0
* Version Independent ID: 8f6ad0a9-2d8d-8e5c-7b80-a7c55c02aff9
* Content: [TaskScheduler Class (System.Threading.Tasks)](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.taskscheduler?redirectedfrom=MSDN&view=netframework-4.7.2#Sync)
* Content Source: [xml/System.Threading.Tasks/TaskScheduler.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Threading.Tasks/TaskScheduler.xml)
* Product: **dotnet-api**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by rpetrusha** [comment]
Thanks for letting us know that the example instructions are outdated, @macginitie. We've opened dotnet/dotnet-api-docs#566 to update them.
