### ISSUE TITLE
Floating blocks

### ISSUE THREAD

**Issue by realbart** [dotnet/docs#7940]
This one gets messed up when renaming seattleCustomers or when using a proportional font:

var seattleCustomers = from cust in customers
                       where cust.City == "Seattle"
                       select cust.Name;

This one doesn't:

var localDistributors =
    from customer in customers
    join distributor in distributors on customer.City equals distributor.City
    select new { Customer = customer, Distributor = distributor };

For this reason, other guidelines say: "If continuation lines are not indented automatically, indent them one tab stop (four spaces). (source: https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/inside-a-program/coding-conventions)

So some of these examples conflict with your different coding guidelines

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a3c147e-2271-4d7c-712b-2f705b5ecbc5
* Version Independent ID: 2c1a7cfe-364e-408e-77c1-9fae2b0da643
* Content: [C# Coding Conventions (C# Programming Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/inside-a-program/coding-conventions#linq-queries)
* Content Source: [docs/csharp/programming-guide/inside-a-program/coding-conventions.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/inside-a-program/coding-conventions.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by realbart** [comment]
This one gets messed up when renaming seattleCustomers or when using a proportional font:

var seattleCustomers = from cust in customers
            where cust.City == "Seattle"
            select cust.Name;

This one doesn't:

var localDistributors =
    from customer in customers
    join distributor in distributors on customer.City equals distributor.City
    select new { Customer = customer, Distributor = distributor };

For this reason, other guidelines say: "If continuation lines are not indented automatically, indent them one tab stop (four spaces). (source: https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/inside-a-program/coding-conventions)

So some of these examples conflict with your different coding guidelines

#7940 opened just now by realbart

**Comment by wekempf** [comment]
My preferred format for this very reason (it complies with both guidelines):

```csharp
var seattleCustomers =
    from cust in customers
    where cust.City == "Seattle"
    select cust.Name;
````

**Comment by mairaw** [comment]
Thanks for your feedback @realbart. Our team discussed and we don't see any issues with the current formatting for the LINQ queries. But we welcome your contribution if you feel strongly about this. Something like what @wekempf suggested would be fine.
