### ISSUE TITLE
Misleading page title?

### ISSUE THREAD

**Issue by mapfel** [dotnet/docs#7941]
As described in the first paragraph, the article describes the prerequisites for .NET Core development. So the title should be "Prerequisites for .NET Core development on Windows".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff5c1c2a-7d86-703c-038e-062f5dcfc5b0
* Version Independent ID: cab4f67f-f338-8990-6454-853a0f01627e
* Content: [Prerequisites for .NET Core on Windows](https://docs.microsoft.com/en-us/dotnet/core/windows-prerequisites?tabs=netcore21)
* Content Source: [docs/core/windows-prerequisites.md](https://github.com/dotnet/docs/blob/master/docs/core/windows-prerequisites.md)
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by rpetrusha** [comment]
You're right, @mapfel; the title could be improved to indicate explicitly that it focuses on developers. Would you like to submit a pull request to make the change? For information about submitting a PR, see the [Contributor's Guide](https://github.com/dotnet/docs/blob/master/CONTRIBUTING.md#process-for-contributing).

**Comment by omerlh** [comment]
I can take it. I think it's better to fix the headline - the page is for developers, the first 2 sections are just prerequisite. This page might be confusing for non-dev who will wonder if they need Visual Studio or Visual C++.

**Comment by mairaw** [comment]
Pasting the comment from the PR here: I still feel that changing the title is not the right thing for this page. The supported Windows versions and dependencies like C++ are not specific to development time. I think we can make changes to that page to make the distinction clearer but I don't think we should touch the title.

**Comment by Thraka** [comment]
I don't feel like the VS content belongs here. Developer or not, Visual Studio isn't a prerequisite for .NET Core. It's an IDE to develop .NET Core apps.

**Comment by mairaw** [comment]
I've created PR #9419 to try to make this page less misleading. See what you think.

We are also discussing whether it's worth to separate the VS piece from the topic, but this would be later. Feedback from customers seem to indicate they like having that info there.
