### ISSUE TITLE
Erroneous remark for DistributedIdentifier

### ISSUE THREAD

**Issue by fredericDelaporte** [dotnet/docs#7942]
The documentation for `TransactionInformation.DistributedIdentifier` property in `System.Transactions` states in its "Remarks" section:

> If the transaction is not escalated, the value is `null`. 

This is impossible, as the property is not nullable. It is a `System.Guid`. Instead, the value is `Guid.Empty`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aca8b80b-4b39-1649-f0eb-28d7953baa5c
* Version Independent ID: 4639599f-30ce-7df6-4dad-a1d16d0b00e7
* Content: [TransactionInformation.DistributedIdentifier Property (System.Transactions)](https://docs.microsoft.com/en-us/dotnet/api/System.Transactions.TransactionInformation.DistributedIdentifier?view=netframework-4.7.1)
* Content Source: [xml/System.Transactions/TransactionInformation.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Transactions/TransactionInformation.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by BillWagner** [comment]
You are correct @fredericDelaporte We've added this to our backlog and our community project.  Do you want to submit a PR for the fix?

**Comment by fredericDelaporte** [comment]
I am not sure I will take the time to look into doing a PR any time soon.
