### ISSUE TITLE
Good article

### ISSUE THREAD

**Issue by mayerhofer** [dotnet/docs#7945]
Please fix "this" keyword before String parameter. It might lead to wrong ideas.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 826876cc-d286-3e10-515e-bba12d85f1f4
* Version Independent ID: 5dfbe5a8-f7be-617d-c9ff-db2fa2d6a396
* Content: [Building a .NET Standard class library with C# and .NET Core in Visual Studio 2017](https://docs.microsoft.com/en-us/dotnet/core/tutorials/library-with-visual-studio)
* Content Source: [docs/core/tutorials/library-with-visual-studio.md](https://github.com/dotnet/docs/blob/master/docs/core/tutorials/library-with-visual-studio.md)
* Product: **dotnet-core**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by rpetrusha** [comment]
We're please that you liked the article, @mayerhofer.

The `this` before the parameter of type `string`, however, is correct. It defines the parameter as an extension method; as a result, the method can be called as if it were a member of the String class. And that's how it's used in the unit tests and the consuming article,
