### ISSUE TITLE
ProxyAttribute.CreateInstance(Type) Method does not call constructors on object creation

### ISSUE THREAD

**Issue by jeffschwMSFT** [dotnet/docs#7946]
I would recommend that we add the following:
Returns
MarshalByRefObject 
An uninitialized MarshalByRefObject or a transparent proxy.
>> When creating a transparent proxy the object constructor is not called.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 157eed91-dd98-f43c-a9a2-719e99446864
* Version Independent ID: 2963cff2-c3fe-defd-d588-2e5cf4c76a3f
* Content: [ProxyAttribute.CreateInstance(Type) Method (System.Runtime.Remoting.Proxies)](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.remoting.proxies.proxyattribute.createinstance?view=netframework-4.7.2)
* Content Source: [xml/System.Runtime.Remoting.Proxies/ProxyAttribute.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Runtime.Remoting.Proxies/ProxyAttribute.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by BillWagner** [comment]
This appears to have been fixed in the last CI update.  Closing.

If you meant something different @jeffschwMSFT re-open and clarify for us.
