### ISSUE TITLE
Link is Broken：  How to: Apply a Transform to a Drawing

### ISSUE THREAD

**Issue by urmyfaith** [dotnet/docs#7949]
&gt; Transforms the DrawingGroup contents. For an example, see How to: Apply a Transform to a Drawing.

https://msdn.microsoft.com/library/0d525f2b-682d-4d67-9660-cf46929fbabd?f=255&MSPPError=-2147217396

this link is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1e79552-c0db-355c-9b16-e8a44b187f31
* Version Independent ID: 66554754-5882-dc6c-39dd-8465e0a5daf4
* Content: [Drawing Objects Overview](https://docs.microsoft.com/en-us/dotnet/framework/wpf/graphics-multimedia/drawing-objects-overview)
* Content Source: [docs/framework/wpf/graphics-multimedia/drawing-objects-overview.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/graphics-multimedia/drawing-objects-overview.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by svick** [comment]
Specifically, I think it's broken only in Chinese:

![](https://user-images.githubusercontent.com/287848/46244130-efe74c80-c3da-11e8-8c0e-59d243185aa8.png)

It works fine in English:

![](https://user-images.githubusercontent.com/287848/46244133-fbd30e80-c3da-11e8-97dd-d654eb3a320d.png)

**Comment by urmyfaith** [comment]
seems works now.
