### ISSUE TITLE
Grammar issue on "Covariance and Contravariance (Visual Basic)" page.

### ISSUE THREAD

**Issue by ericmutta** [dotnet/docs#7955]
Towards the end of [Covariance and Contravariance (Visual Basic)](https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/concepts/covariance-contravariance/) we have this sentence:

> In .NET Framework 4 or later Visual Basic **support** covariance and contravariance in generic interfaces and delegates and **allow** for implicit conversion of generic type parameters.

I believe the words in bold above, should appear in their plural form so the sentence reads as follows (corrected words in ALL CAPS):

> In .NET Framework 4 or later Visual Basic **SUPPORTS** covariance and contravariance in generic interfaces and delegates and **ALLOWS** for implicit conversion of generic type parameters.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e70a7c1-a575-2ef3-42de-98284562303a
* Version Independent ID: 8dbca2db-76f6-3895-bd83-4ffc916fd1a6
* Content: [Covariance and Contravariance (Visual Basic)](https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/concepts/covariance-contravariance/)
* Content Source: [docs/visual-basic/programming-guide/concepts/covariance-contravariance/index.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/programming-guide/concepts/covariance-contravariance/index.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by valerianpereira** [comment]
@rpetrusha I believe the PR is merged and this issue is resolved? Close it?

**Comment by ericmutta** [comment]
@valerianpereira the PR has been merged and the change is live (thanks @aramkoukia @rpetrusha @Thraka). I am closing the issue :+1:
