### ISSUE TITLE
Issue adding Service Reference

### ISSUE THREAD

**Issue by bhadanimayank** [dotnet/docs#7957]
When I am running GettingStartedHost Project. I am unable to add the Service Reference to GettingStartedClient Project because the option is disabled. I have all the three GettingStartedLib, GettingStartedHost, GettingStartedClient   projects is a single solution.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c27c6cc-63c8-5c3d-f344-228f8ad86c90
* Version Independent ID: d560cf6a-e9bd-95e5-ce15-a08a5778181a
* Content: [How to: Create a Windows Communication Foundation Client](https://docs.microsoft.com/en-us/dotnet/framework/wcf/how-to-create-a-wcf-client)
* Content Source: [docs/framework/wcf/how-to-create-a-wcf-client.md](https://github.com/dotnet/docs/blob/master/docs/framework/wcf/how-to-create-a-wcf-client.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by shamimevatix** [comment]
I am facing the exact same issue like @bhadanimayank. I can't solve this puzzle

**First, start up the GettingStartedHost console application.**

Do we need to create a separate solution to run this?. When i run the GettingStartedHost.exe from cli, the url http://localhost:8000/GettingStarted/CalculatorService returns 400 http code.

Please help.

**Comment by koviroli** [comment]
I have the same problem, but remember about 2-3 months ago I could do this tutorial with no problem.

**Comment by mairaw** [comment]
@Lxiamail @zhenlan can you help? Thanks!

**Comment by koviroli** [comment]
There is also an incorrent base address where creating client code in C# section. I think the VB script also incorrect?

`svcutil.exe /language:cs /out:generatedProxy.cs /config:app.config http://localhost:8000/GettingStartedClient/service`

should be

`svcutil.exe /language:cs /out:generatedProxy.cs /config:app.config http://localhost:8000/GettingStarted/CalculatorService`

**Comment by Thraka** [comment]
@bhadanimayank @shamimevatix Hi! @koviroli just submitted a pull request that may have fixed your issue. It will take less than a day to appear online, but you can review the change here: #8493 

**Please let me know if this fixes your issue.**

----

I also filed issue #8556 to hopefully get some work done on that entire series to make sure it's all still working.

**Comment by zigfig21** [comment]
The bug is in the descriptive text: 

Enter the following URL in the address box of the Add Service Reference dialog: http://localhost:8000/GettingStarted/CalculatorService

should be
Enter the following URL in the address box of the Add Service Reference dialog: http://localhost:8000/GettingStarted/

**Comment by Thraka** [comment]
@zigfig21 This article series is being rewritten according to #9957 and possible finished today
