### ISSUE TITLE
Does this make alwas make copy?

### ISSUE THREAD

**Issue by thriolsson** [dotnet/docs#7961]
This completely lacks any form of useful documentation of the "contract". Without knowing if this will always return a new copy or not, the effect is that I must always make a copy. Surely I can look at the source code for .NET Core for the current implementation, but without knowing what the contract is, I cannot really rely on this since it might change in the future.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56051527-1696-2060-25b3-e4c4084691df
* Version Independent ID: 16feb5ab-0e70-bf3f-4212-e4466dca224c
* Content: [Memory&lt;T&gt;.ToArray Method (System)](https://docs.microsoft.com/en-us/dotnet/api/system.memory-1.toarray?view=netcore-2.1)
* Content Source: [xml/System/Memory`1.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System/Memory`1.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
This should be fixed when we merge the following PR: https://github.com/dotnet/dotnet-api-docs/pull/548. Take a look and see if that answers your question @thriolsson! Thanks.
