### ISSUE TITLE
Add link to xUnit documentation 

### ISSUE THREAD

**Issue by yakuramori** [dotnet/docs#7962]
One can specify additional parameters for test execution in xunit.runner.json file in root directory.
More info about possible configuration here: https://xunit.github.io/docs/configuring-with-json.html

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e39c2f1b-f41a-bdf9-2646-09379941453d
* Version Independent ID: 422811cb-6287-03af-ba8d-1daebee9744d
* Content: [Unit testing C# code in .NET Core using dotnet test and xUnit](https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-with-dotnet-test)
* Content Source: [docs/core/testing/unit-testing-with-dotnet-test.md](https://github.com/dotnet/docs/blob/master/docs/core/testing/unit-testing-with-dotnet-test.md)
* Product: **dotnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **wiwagn**

**Comment by manolis82** [comment]
Hello. 
I am willing to add the [link to the xUnit docs](https://xunit.github.io/#documentation) and it looks like the 'Additional resources' section at the bottom of the page is a good place for it.

What do you think?
