### ISSUE TITLE
Description about SingleOrDefault is incorrect.

### ISSUE THREAD

**Issue by JmlSaul** [dotnet/docs#7967]
while the collection does not contain exactly one element will not return default value but throw exception, please kindly update the doc refers to 'More Information'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 425902b5-2b2a-c899-91fb-44aa9ea3dc1b
* Version Independent ID: e2866096-c7fe-61cb-b53b-6fa0f78800f5
* Content: [Element Operations (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/linq/element-operations)
* Content Source: [docs/csharp/programming-guide/concepts/linq/element-operations.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/linq/element-operations.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by pkulikov** [comment]
@JmlSaul thanks for pointing out the incorrect description.
