### ISSUE TITLE
Wrong link

### ISSUE THREAD

**Issue by Luperco** [dotnet/docs#7996]
The link "Popup Placement Sample" bring to a non existent domain archive.msdn.microsoft.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80c649c8-b40a-bb58-79ce-b204031f05e2
* Version Independent ID: ab7d588a-67c0-5fbc-5819-5dc36e8ce635
* Content: [Popup Placement Behavior](https://docs.microsoft.com/en-us/dotnet/framework/wpf/controls/popup-placement-behavior)
* Content Source: [docs/framework/wpf/controls/popup-placement-behavior.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/controls/popup-placement-behavior.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
Thanks, @Luperco, for reporting the broken link. The sample is no longer available from the Microsoft Download Center, and it also does not seem to be available at <https://github.com/Microsoft/WPF-samples/>. I'll add this to our backlog while we investigate whether the sample is available.
