### ISSUE TITLE
Values correspond to what?

### ISSUE THREAD

**Issue by nhwilly** [dotnet/docs#7997]
I'm sure everyone but me knows this somehow, but exactly what do the values correspond to?  I understand that the bigger the number, the more curved the corners are, but a little guidance on how the radius is related to the size of the object, say, to construct a circle, etc. would be really helpful.

Like, any value more than half the diameter will be ignored, etc.  I just want to have a guideline for the effect I want.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1908c4d-7038-cf2c-2091-1b3e2acc7346
* Version Independent ID: e1aa070d-2eba-a9dc-cd2d-50ba59a87c32
* Content: [CornerRadius Struct (System.Windows)](https://docs.microsoft.com/en-us/dotnet/api/system.windows.cornerradius?view=netframework-4.7.2&viewFallbackFrom=netcore-2.1)
* Content Source: [xml/System.Windows/CornerRadius.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Windows/CornerRadius.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by BillWagner** [comment]
This looks like it will be fixed in #8025

**Comment by nhwilly** [comment]
Ok, this was me probably being lazy.  I was thinking `radius` in terms of distance from the center of the control and not in terms of a line segment.  Couldn't get my head around it, got stuck and confused myself.  Thanks for even looking at it.
