### ISSUE TITLE
Not useful

### ISSUE THREAD

**Issue by DarthDerrr** [dotnet/docs#7998]
How is this supposed to be configured? Could a link to any documentation about the corresponding configuration be added. This by itself is pretty useless.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e563a255-5406-284a-965b-33596e660a3c
* Version Independent ID: 0ec2b3bb-8937-50be-d499-df3659fdd5ce
* Content: [System.Runtime.Caching.Configuration Namespace](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.caching.configuration?view=netframework-4.7.2)
* Content Source: [xml/ns-System.Runtime.Caching.Configuration.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/ns-System.Runtime.Caching.Configuration.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
Thanks for your feedback, @DarthDerrr. This page describes the general functionality that the types in the namespace make available. It is intended primarily to list the types in the namespace and not to provide detailed configuration documentation.
