### ISSUE TITLE
Code example causes an error

### ISSUE THREAD

**Issue by DarthDerrr** [dotnet/docs#7999]
I'm using .net 4.0 in an asp.net application. I pasted the named caches configuration into my system.runtime.caching node of config verbatim and got an error:

Description: An error occurred during the processing of a configuration file required to service this request. Please review the specific error details below and modify your configuration file appropriately. 

Parser Error Message: Unrecognized attribute 'physicalMemoryPercentage'. Note that attribute names are case-sensitive.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a67406db-e7fe-e4d3-1d5c-9a4d581f5ff6
* Version Independent ID: e70febe8-b1c1-187d-19f9-88f8c26cf07a
* Content: [&lt;system.runtime.caching&gt; Element (Cache Settings)](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/runtime/system-runtime-caching-element-cache-settings)
* Content Source: [docs/framework/configure-apps/file-schema/runtime/system-runtime-caching-element-cache-settings.md](https://github.com/dotnet/docs/blob/master/docs/framework/configure-apps/file-schema/runtime/system-runtime-caching-element-cache-settings.md)
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by rpetrusha** [comment]
Thanks for pointing this out, @DarthDerrr. The example fails because the correct name of the attribute is `physicalMemoryLimitPercentage`. I've opened #8021 to correct the documentation.
