### ISSUE TITLE
How to Remove Question at top of the screen.

### ISSUE THREAD

**Issue by jkaisler** [dotnet/docs#8005]
I also had this problem.   Just received a Dell 7730 with 4K screen set to 226% / 216dpi.   Enabled the proper Key setting described in Layers.   Always get the question at the top of the screen saying Reset to DPI-Aware.   I have to click the X to make question go away.   If I have configured it to be DPI UNAWARE, why keep questioning me?  Visual Studio 2017 - 15.8.5

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43b74bf9-71c6-2559-66f7-2e17de0702ef
* Version Independent ID: 9ad214a4-3ae0-f7e6-bb89-86067d97059d
* Content: [Disable DPI-awareness in Visual Studio](https://docs.microsoft.com/en-us/dotnet/framework/winforms/disable-dpi-awareness-visual-studio)
* Content Source: [docs/framework/winforms/disable-dpi-awareness-visual-studio.md](https://github.com/dotnet/docs/blob/master/docs/framework/winforms/disable-dpi-awareness-visual-studio.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
I believe there'll be an option to dismiss the gold bar with the message in Visual Studio 2017 version 15.9.

**Comment by mairaw** [comment]
@OliaG @merriemcgaw can you confirm that?

**Comment by merriemcgaw** [comment]
@mairaw that is correct. We're getting it in Preview 4 I think. But it's going in.

**Comment by jkaisler** [comment]
Hi,
    Just wanted to revisit this again.   I am now at VS 2017 15.9.2 and still have the issue. with the question at the top when viewing projects.
