### ISSUE TITLE
Fire and forget

### ISSUE THREAD

**Issue by maximdx** [dotnet/docs#8009]
But what if we want to call the async method in a fire-and-forget way? It is good to call async method without awaiting it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26b7aabd-59fb-dcb9-dd1b-55bf64730aee
* Version Independent ID: b9add390-2fcf-5eb9-3079-0659e68ecdcf
* Content: [Because this call is not awaited, the current method continues to run before the call is completed](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/error-messages/because-this-call-is-not-awaited-the-current-method-continues-to-run)
* Content Source: [docs/visual-basic/language-reference/error-messages/because-this-call-is-not-awaited-the-current-method-continues-to-run.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/language-reference/error-messages/because-this-call-is-not-awaited-the-current-method-continues-to-run.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by BillWagner** [comment]
Thanks for writing this @maximdx We do think the current doc addresses this: If you don't await, you run risks related to exceptions and errors in the code that' not awaited.

I'm closing this as answered in the doc.
