### ISSUE TITLE
What will it take for Microsoft to open-source the WCF Test Client app?

### ISSUE THREAD

**Issue by stamminator** [dotnet/docs#8011]
Is there any reason this shouldn't be open sourced? Simple, inanely basic features like alphabetic sorting and filtering of endpoint names are and have always been absent from this app. In keeping with your new company culture and mission, why not let the community spruce it up?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 599983a3-8520-1f76-61c6-4b77ef804492
* Version Independent ID: 37629297-b13c-bd53-aeac-5646c6bdc06f
* Content: [WCF Test Client (WcfTestClient.exe)](https://docs.microsoft.com/en-us/dotnet/framework/wcf/wcf-test-client-wcftestclient-exe)
* Content Source: [docs/framework/wcf/wcf-test-client-wcftestclient-exe.md](https://github.com/dotnet/docs/blob/master/docs/framework/wcf/wcf-test-client-wcftestclient-exe.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rhyous** [comment]
I couldn't agree more.

**Comment by mairaw** [comment]
@glennc @Lxiamail @zhenlan can one of you comment on this request?

**Comment by Lxiamail** [comment]
@stamminator  and @rhyous Thank you for your suggestion. WcfTestClient.exe currently is part of visual studio release. It has some dependencies on VS. We can't open source it without relatively involved refactoring work. There is no plan to open source it now. However, we like to continue collecting customer feedbacks.

**Comment by mairaw** [comment]
Thanks for your input @Lxiamail. Closing this issue then.

**Comment by acsteitz** [comment]
OK, so you won't open source it.  Please add "Simple, inanely basic features like alphabetic sorting and filtering of endpoint names".
