### ISSUE TITLE
{Binding Source={StaticResource MyPhotos}}

### ISSUE THREAD

**Issue by LisandroSu** [dotnet/docs#8017]
@O4D commented on [Tue Oct 02 2018](https://github.com/dotnet/docs.fr-fr/issues/68)

Dear LisandroSu,

I used "Give a feedback on the product", again, to write this post. 

So : this documentation doesn't show how to implement MyPhotos object.
If I use ItemsSource="{Binding Source={StaticResource MyPhotos}}" XAML seems to search into the &lt;resources&gt; something called MyPhotos.

And if I write only {Binding MyPhotos} in my XAML and create a List&lt;Photo&gt; in my .cs, the link isn't automaticaly done (MainWindow).

Can you update the documentation to write the missing part about the MyPhotos object declaration ?

Regards

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 9dfc55ee-0061-cd98-fd01-ad6156f8d155
* Version Independent ID: 594e424a-30ed-9f1e-dac7-e56acdd022e0
* Content: [Application d'un style et création de modèles](https://docs.microsoft.com/fr-fr/dotnet/framework/wpf/controls/styling-and-templating)
* Content Source: [docs/framework/wpf/controls/styling-and-templating.md](https://github.com/dotnet/docs.fr-fr/blob/live/docs/framework/wpf/controls/styling-and-templating.md)
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by LisandroSu** [comment]
Hi Team,

Please check this issue.

Thanks!

**Comment by Thraka** [comment]
I cleaned up this article and the example project. The example project defines a resource named `MyPhotos`.
