### ISSUE TITLE
project.json for samples includes unnecessary nodes generated by tools

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#803]
See comments from @cartermp on PR #801 

The CLI generates the imports nodes, and (in test projects) the dependency on `System.Runtime.Serialization.Primitives`. 

The docs should continue to match the files generated by the tools. When the tools are updated (see this issue: https://github.com/dotnet/cli/issues/1717 the docs should match.

**Comment by BillWagner** [comment]
This should be part of the work to update the experience with the new build tools. All the samples will have the project.json format throughout the topic and the samples. This should be a reminder that all those should be updated so that the files generated by the tools match the text shown in the topic.

**Comment by mairaw** [comment]
No longer an issue.
