### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by alpaix** [dotnet/docs#8057]
Dialog Box Sample link appears to be broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bc9312d-0333-286d-9d05-aaae6b98011d
* Version Independent ID: 5dd7b554-95f7-e86c-7338-2c8714a23df4
* Content: [Dialog Boxes Overview](https://docs.microsoft.com/en-us/dotnet/framework/wpf/app-development/dialog-boxes-overview)
* Content Source: [docs/framework/wpf/app-development/dialog-boxes-overview.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/app-development/dialog-boxes-overview.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thank you for reporting this issue @alpaix. The link is now fixed.
