### ISSUE TITLE
The code is invalid

### ISSUE THREAD

**Issue by daniel-zazula** [dotnet/docs#8064]
There's no overload of Attribute.GetCustomAttributes that accepts a System.Type parameter:
https://docs.microsoft.com/en-us/dotnet/api/system.attribute.getcustomattributes?redirectedfrom=MSDN&view=netframework-4.7.2#overloads

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e3cbdd1-b9fe-6377-b9f1-e6d9fc1041cb
* Version Independent ID: c8c67935-4563-ad22-8826-8984b97cdf4b
* Content: [Accessing Attributes by Using Reflection (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/attributes/accessing-attributes-by-using-reflection)
* Content Source: [docs/csharp/programming-guide/concepts/attributes/accessing-attributes-by-using-reflection.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/attributes/accessing-attributes-by-using-reflection.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Thraka** [comment]
@daniel-zazula Hi!

The code will use the [GetCustomAttributes(MemberInfo)](https://docs.microsoft.com/en-us/dotnet/api/system.attribute.getcustomattributes?view=netframework-4.7.2#System_Attribute_GetCustomAttributes_System_Reflection_MemberInfo_) because `Type` inherits from `MemberInfo`.
