### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by Shinsentoh** [dotnet/docs#8066]
&lt;security mode="Message" /&gt;  
...
&lt;/security&gt; 

must be written as 
&lt;security mode="Message"&gt;  
...
&lt;/security&gt; 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4cc06336-d0e1-c981-7ad4-c48efc715c17
* Version Independent ID: 5279893b-a235-a006-74c9-655aec9c4d9c
* Content: [How to: Set the Security Mode](https://docs.microsoft.com/en-us/dotnet/framework/wcf/how-to-set-the-security-mode)
* Content Source: [docs/framework/wcf/how-to-set-the-security-mode.md](https://github.com/dotnet/docs/blob/master/docs/framework/wcf/how-to-set-the-security-mode.md)
* Product: **dotnet-framework**
* GitHub Login: @BrucePerlerMS
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
You're right @Shinsentoh. Would you like to submit a pull request with a fix? You can see more information about this at https://docs.microsoft.com/en-us/contribute/#quick-edits-to-existing-documents.
