### ISSUE TITLE
Cannot convert int to short

### ISSUE THREAD

**Issue by taha3azab** [dotnet/docs#8068]
why the below line is not compiled 
short x = condition ? 0 : 1;
and I have to cast it 
short x = (short) (condition ? 0 : 1);

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5379a49c-6a81-82a5-cca2-3ab71f432c5c
* Version Independent ID: 1a00e3ec-bec1-3030-9766-a788912bc3b9
* Content: [?: Operator (C# Reference)](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/conditional-operator)
* Content Source: [docs/csharp/language-reference/operators/conditional-operator.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/operators/conditional-operator.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@taha3azab 

That's because integral numeric literals are of type `int`. That's detailed in the C# spec on [integer literals](https://docs.microsoft.com/dotnet/csharp/language-reference/language-specification/lexical-structure#integer-literals)

Closing this.
