### ISSUE TITLE
Change headings and titles to use sentence-style capitalization

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#808]
Microsoft's guidance for titles and headings is to use sentence-style capitalization. So I'm adding this information to our template file but also we need to review existing topics to have the proper capitalization.

**Comment by richlander** [comment]
This topic and the ones around it are good ones to start with.

https://docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-test

**Comment by mairaw** [comment]
@tompratt-AQ once you're done with your tasks, let's take a look at this one. A co-worker shared a script that could help us do that. Thanks!

**Comment by automation-dojo** [comment]
> 
> 
> This topic and the ones around it are good ones to start with.
> 
> https://docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-test

@mairaw should this be changed to `Dotnet test`?

**Comment by mairaw** [comment]
No @automation-dojo since this is the name of the command.

**Comment by BillWagner** [comment]
closing, as this is being updated as we update individual topics.
