### ISSUE TITLE
C# example throws an error

### ISSUE THREAD

**Issue by samirm** [dotnet/docs#8081]
replace "Key.Return" with "Windows.System.VirtualKey.Enter"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcd32f6d-4a54-b4a9-643e-1bfa30f98d4d
* Version Independent ID: f42b5de3-7407-4d1c-8504-f07620f57c04
* Content: [How to: Detect When the Enter Key Pressed](https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/how-to-detect-when-the-enter-key-pressed)
* Content Source: [docs/framework/wpf/advanced/how-to-detect-when-the-enter-key-pressed.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/advanced/how-to-detect-when-the-enter-key-pressed.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by Thraka** [comment]
@samirm Hi!

The `Windows.System.VirtualKey.Enter` type is for the UWP area. While it is a XAML-based technology, it is different from WPF. The article you're looking at and copying the sample from is based on WPF.

**Comment by samirm** [comment]
@Thraka oh my bad. I did not realize this article was WPF only since it doesn't mention it anywhere on that page. I came across it from a search engine.
