### ISSUE TITLE
Caveats

### ISSUE THREAD

**Issue by Chris-MD** [dotnet/docs#8110]
I have come accross so many pages where this feature does not work, and only once have I seen a suggestion that it only work on a single web page, ie which doesn't involve a Master Page.

Can any one provide the caveats or explain why this feature doesn't seem to work?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f0669d5-239c-52c4-a313-ef268dd832f9
* Version Independent ID: 17cb46fe-fa70-f64c-28f8-6b92e1fe2ac2
* Content: [Page.MaintainScrollPositionOnPostBack Property (System.Web.UI)](https://docs.microsoft.com/en-us/dotnet/api/system.web.ui.page.maintainscrollpositiononpostback?view=netframework-4.7.2)
* Content Source: [xml/System.Web.UI/Page.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Web.UI/Page.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks for your feedback @Chris-MD. @Rick-Anderson can you help triage this issue?

**Comment by Rick-Anderson** [comment]
Looks like it doesn't work on all browsers. See https://forums.asp.net/t/1755559.aspx

**Comment by Rick-Anderson** [comment]
@Chris-MD 	I'm sorry we couldn't have given you a better answer. Closing this issue for now.
