### ISSUE TITLE
Explore combining the different language topics for .NET Core unit test

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#8117]
We have one entry per language but this process is painful when we need to make updates. We should look into this and see if it makes sense to combine them into one per technology and have tabs for each language.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a64f7e75-fbea-18ba-f290-3e5bb3ab0da7
* Version Independent ID: 24639c20-6c3a-738e-2ff8-9a6ee6f232dc
* Content: [Unit Testing in .NET Core](https://docs.microsoft.com/en-us/dotnet/core/testing/)
* Content Source: [docs/core/testing/index.md](https://github.com/dotnet/docs/blob/master/docs/core/testing/index.md)
* Product: **dotnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
We can also have one per language and use the tabs for the different unit testing frameworks:

```
[MSTest](#tab/mstest)
[NUnit](#tab/nunit)
[xUnit](#tab/xunit)
```

**Comment by mairaw** [comment]
Any preference on this @BillWagner? The way the articles are structured right now, it would be easier to have tabs per language for each technology. Also, because C# would probably be more popular, having that always available first seems to make more sense to me. I'd like to add a vendor task for this.
