### ISSUE TITLE
Looks like an update is needed?

### ISSUE THREAD

**Issue by tabareh** [dotnet/docs#8143]
Hi,

When I'm looking into the Ignite 2018, I see a different approach in code for creating the env and context etc. Actually pipelines belong to Legacy part of the namespace now. 
Could you please update these tutorials with the new releases.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a30b3ff5-b5e6-ff02-6f60-b5cef6f34666
* Version Independent ID: fdf962e2-620e-d9ad-5057-5f96f52dc60f
* Content: [Use ML.NET to predict New York taxi fares (regression)](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/taxi-fare#feedback)
* Content Source: [docs/machine-learning/tutorials/taxi-fare.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/taxi-fare.md)
* Product: **dotnet-ml**
* GitHub Login: @aditidugar
* Microsoft Alias: **johalex**

**Comment by pkulikov** [comment]
I'm willing to update the tutorials to use the new ML.NET API.

However, there are two points to consider:

- As far as I understand, the new API is still work in progress and might change in the following ML.NET versions. Thus, it might make sense to update tutorials later (with 0.7 or 0.8 version) when API is more stable. Or, tutorial-wise, API is already good enough?

- Should both approaches (`LearningPIpeline` and new API) be presented in the docs? Or updated tutorials would replace the current ones?

@JRAlexander what do you think?

**Comment by JRAlexander** [comment]
@pkulikov - Good question. @GalOshri - Thoughts here?

**Comment by pkulikov** [comment]
@GalOshri 
>However, we will likely want to update some of the intro material at least to help people get started with the latest APIs.

Current docs make a note of the new API and provide the links to the intro topics in dotnet/machinelearning repo:
https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/

**Comment by pkulikov** [comment]
@JRAlexander #8839 updates the sentiment analysis tutorial to 0.7 version. Is it fine, if I'll update the clustering tutorial meanwhile?
