### ISSUE TITLE
Wrong example

### ISSUE THREAD

**Issue by misterspeedy** [dotnet/docs#8155]
The final example given seems to be for an integer range rather than a DateTime range as stated. The Type parameter isn't used.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7381fca5-c4b3-d912-e29e-5fcb6c135919
* Version Independent ID: c7df12cc-b527-7a3b-c17b-855f3fa2def4
* Content: [RangeAttribute Constructor (System.ComponentModel.DataAnnotations)](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.dataannotations.rangeattribute.-ctor?view=netframework-4.7.2#System_ComponentModel_DataAnnotations_RangeAttribute__ctor_System_Type_System_String_System_String_)
* Content Source: [xml/System.ComponentModel.DataAnnotations/RangeAttribute.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.ComponentModel.DataAnnotations/RangeAttribute.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by GKotfis** [comment]
I'd like to take this one.
I did some research and first what I see is that [linked examples](https://github.com/dotnet/samples/blob/master/snippets/csharp/VS_Snippets_WebNet/System.ComponentModel.DataAnnotations.RangeAttribute/CS/Product.cs) looks good. But I have a feeling that the source is completely than [real docs](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.dataannotations.rangeattribute.-ctor?view=netframework-4.7.2) :) I can switch to C++ example but there is no link for that in source.  It's a little weird for me

**Comment by mairaw** [comment]
Thanks for letting us know @misterspeedy. @GKotfis since we just need to change the snippet tag number on these, we'll just go ahead and fix it.
