### ISSUE TITLE
System.Collections.Generic x System.Collections

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#8177]
@maicomoreira commented on [Sat Oct 06 2018](https://github.com/dotnet/docs.pt-br/issues/80)

Resultado do post o cima não: 
Generic Sort: System.Collections.Generic.List\`1[System.Int32] Time taken: 0.0789ms
Non-Generic Sort: System.Collections.ArrayList Time taken: 2.4324ms
--&gt; NÃO É VERDADE NO ASP NET CORE &lt;-- 
VEJAM:
Generic Sort: System.Collections.Generic.List`1[System.Int32]  
 Time taken: 12.8626ms
Non-Generic Sort: System.Collections.ArrayList  
 Time taken: 2.0332ms

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: a25e736b-b6df-d882-5ff1-7d22061ad35b
* Version Independent ID: b5c640cf-8c46-2f44-3196-a504a54a5ded
* Content: [Visão Geral dos Tipos Genéricos (Genéricos)](https://docs.microsoft.com/pt-br/dotnet/standard/generics)
* Content Source: [docs/standard/generics.md](https://github.com/dotnet/docs.pt-br/blob/live/docs/standard/generics.md)
* GitHub Login: @kuhlenh
* Microsoft Alias: **wiwagn**

**Comment by CeciAc** [comment]
Hi team, 
I'm moving this here since the user reported an accuracy issue.
Rough translation: 

> 
> Post result the top not:
> Generic Sort: System.Collections.Generic.List`1[System.Int32] Time taken: 0.0789ms
> Non-Generic Sort: System.Collections.ArrayList Time taken: 2.4324ms
> -> IT IS NOT TRUE IN ASP NET CORE <-
> See:
> Generic Sort: System.Collections.Generic.List`1[System.Int32]
> Time taken: 12.8626ms
> Non-Generic Sort: System.Collections.ArrayList
> Time taken: 2.0332ms
>

**Comment by mairaw** [comment]
The time will never be the same for every machine. I'll make some changes to the topic to indicate that but this is what I got when I ran the code on a .NET Core 2.0 project:
![image](https://user-images.githubusercontent.com/12971179/46634163-e2ca0c00-cb04-11e8-93da-46fed6e38d7f.png)

**Comment by mairaw** [comment]
PR to improve this topic created: https://github.com/dotnet/docs/pull/8190

@maicomoreira se quiser me passar um projeto para poder reproduzir esse problema, ajudaria. Mas todos os testes que fiz, incluindo com .NET Core 2.0, a versão genérica era sempre mais rápida.
