### ISSUE TITLE
Error al compilar

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#8178]
@anarro commented on [Mon Oct 08 2018](https://github.com/dotnet/docs.es-es/issues/59)

Falta añadir el ensamblado el System.Drawing

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 937bc3bb-60f4-b9d3-ae82-eb1a6f84d6a0
* Version Independent ID: 0a4bb3ac-fa15-4153-0ed6-048eae0448ea
* Content: [Cómo: Implementar el modo virtual con la carga de datos Just-In-Time en el control DataGridView de formularios Windows Forms](https://docs.microsoft.com/es-es/dotnet/framework/winforms/controls/virtual-mode-with-just-in-time-data-loading-in-the-datagrid)
* Content Source: [docs/framework/winforms/controls/virtual-mode-with-just-in-time-data-loading-in-the-datagrid.md](https://github.com/dotnet/docs.es-es/blob/live/docs/framework/winforms/controls/virtual-mode-with-just-in-time-data-loading-in-the-datagrid.md)
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Hi team, 
The user is reporting a compilation error
They say the "System.Drawing assemblies" is missing

Kind regards,
Microsoft DOCS International Team

**Comment by mairaw** [comment]
We'll have to investigate and see if we can repro this one.

**Comment by mairaw** [comment]
I'm going to close this one as not repro. When you create a new Windows Forms app, the System.Drawing assembly is automatically referenced by the project.

**Comment by anarro** [comment]
Hi Celia/Miriam,

I'm new in VB .Net, when I was young I used another platform (Delphi). Now I trying learning with VB .Net..., if I read in your documents:

>.
..
To add a complete code example to a Visual Studio project
1. In the Help topic that contains the complete code listing, click Copy Code. 
2. In Visual Studio, on the File menu, point to New, and then select Project. 
The New Project dialog box appears. 
3. In the Project Types pane, expand Visual Basic or Visual C#, and then select Windows. 
4. In the Templates pane, select **Empty Project**. 
5. Specify a name and location for the project and click OK. 
The new project opens in Visual Studio. 
6. In Solution Explorer, right-click your project, and then select Add Reference. 
7. In the Add Reference dialog box, select the assemblies required by the example and click OK. 
The assemblies are typically listed at the end of the Help topic that contains the complete code example. 
8. In Solution Explorer, right-click your project, point to Add, and then select Class. 
9. In the Add New Item dialog box, specify a name for the class and click Add. 
The new class opens in the code editor. 
10 Select the code in the new class file, and then replace it by pasting in the code from the Help topic. 
11. Press F5 to compile and run the example. 
..
.
> 

and I think.... if I use a "Empty Project" when I try to compile I have a error... 

![image](https://user-images.githubusercontent.com/8436433/46650549-3d16ab80-cb9d-11e8-9a91-917d78476567.png)

Not it's correct?


Thank you.
Antoni.

**Comment by mairaw** [comment]
Hola @anarro!

That topic is part of the Windows Forms documentation. 

Which version of Visual Studio are you using?
For Visual Studio 2017, the easiest way to get this working is to create a new  Windows Forms project called VirtualJustInTimeDemo.
So instead of choosing the **Empty Project** template, select **Windows Forms App** under **Windows Desktop**.

Names might be slightly different if you're using a different version.

**Comment by anarro** [comment]
Hi, @mairaw.

I use the last version of Visual Studio 2017 (15.8.6)...
