### ISSUE TITLE
Struct constructors are invoked with the new operator, but that does not imply that memory is being allocated.

### ISSUE THREAD

**Issue by xamarin-volkan** [dotnet/docs#8183]
It is stated as title.
Is it right? Need some clarification or source for explanation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 071b082e-a4aa-00af-1f03-9f6f7205c0bc
* Version Independent ID: cbd67b7f-8aae-2d43-a1dc-26a8b870389e
* Content: [C# structs - A tour of the C# language](https://docs.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/structs)
* Content Source: [docs/csharp/tour-of-csharp/structs.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tour-of-csharp/structs.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Thraka** [comment]
@BillWagner I think I understand what @xamarin-volkan is talking about. It says "but that does not imply that memory is being allocated." when you use the new keyword with a struct. Isn't any/all memory allocated in some form? Perhaps it would be better to word that whole paragraph as:

**bold is my change to the paragraph**

>Struct constructors are invoked with the `new `operator, **similar to an object constructor. But, instead** of dynamically allocating an object and returning a reference to it, a struct constructor simply returns the struct value itself (typically in a temporary location on the stack), and this value is then copied as necessary.

**Comment by BillWagner** [comment]
@Thraka I like that. I'll suggest one more clarification:

> Struct constructors are invoked with the `new` operator, similar to a class constructor. But, instead of dynamically allocating an object **on the managed heap** and returning a reference to it, a struct constructor simply returns the struct value itself (typically in a temporary location on the stack), and this value is then copied as necessary.

**bold** is my addition

Adding the "up for grabs" label, and adding this to the community contribution project.
