### ISSUE TITLE
Add Azure Authentication Docs

### ISSUE THREAD

**Issue by richlander** [dotnet/docs#819]
As we start documenting app-models with UI, we need to include topics like this for each one of them

https://developer.xamarin.com/guides/xamarin-forms/web-services/authentication/azure/

We can close this issue once we do it for the first one, which I assume we'll be for UWP. It's mostly just a reminder that we need to do this.

**Comment by mairaw** [comment]
Shouldn't this be covered on the Azure side of the house like https://docs.microsoft.com/en-us/azure/app-service-mobile/ @richlander?
