### ISSUE TITLE
Specify default value like MaxMessagesPerTask

### ISSUE THREAD

**Issue by houseofcat** [dotnet/docs#8194]
The default is -1, which indicates an unlimited number of messages.

Please and thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d4bc98e-e4a2-ff5f-d76b-05b919e993ed
* Version Independent ID: d940df1c-bcc8-661f-3438-9f5899c1c2cd
* Content: [DataflowBlockOptions.BoundedCapacity Property (System.Threading.Tasks.Dataflow)](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.dataflow.dataflowblockoptions.boundedcapacity?view=netcore-2.1)
* Content Source: [xml/System.Threading.Tasks.Dataflow/DataflowBlockOptions.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Threading.Tasks.Dataflow/DataflowBlockOptions.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
Thanks for pointing this out, @houseofcat. Would you like to submit a PR to update the documentation? In the meantime, I'll add this issue to our backlog.

**Comment by houseofcat** [comment]
@rpetrusha Here you go Ron!
https://github.com/dotnet/dotnet-api-docs/pull/602
