### ISSUE TITLE
Clarification for bools

### ISSUE THREAD

**Issue by fitdev** [dotnet/docs#8196]
For `bool`s is `x |= y` the same as `x = x | y` (as the article suggests) OR is it the same as `x = x || y` (the later being short cicuiting, with the possibility of `y` never being evaluated).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b47cbbfe-718d-143b-d6b4-2b32a9b0d3a9
* Version Independent ID: 05a1b6cf-f195-894f-aaeb-7c7644e06077
* Content: [|= Operator (C# Reference)](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/or-assignment-operator?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(|%3D_CSharpKeyword)%3Bk(SolutionItemsProject)%3Bk(DevLang-csharp)%26rd%3Dtrue)
* Content Source: [docs/csharp/language-reference/operators/or-assignment-operator.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/operators/or-assignment-operator.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mikkelbu** [comment]
It is the same as `x = x | y`. We can replace `y` with something with a side-effect, so we can observe that it is being evaluated, e.g. writing to the console, incrementing a value, or throwing an exception. So the following
```c#
      bool b = true;
      int i = 0;
      bool f() { i++; return false; }
      b |= f();
      Console.WriteLine(b);
      Console.WriteLine(i);
```
will write `true` and `1`.

**Comment by fitdev** [comment]
@mikkelbu Thank you. Yes, I figured it myself after performing a similar test. It would be nice if it was explicitly mentioned though.

**Comment by BillWagner** [comment]
That behavior is documented in the section on [compound assignment operators](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/expressions#compound-assignment) in the C# spec.

The language reference is less complete but gives the basics for each feature.  

I'm closing this, as the answer is in the spec.
