### ISSUE TITLE
Registry Key did not work

### ISSUE THREAD

**Issue by BenLussier** [dotnet/docs#8202]
Unfortunately, it doesn't appear I can attach a screenshot here. I followed the Add a Registry Key instructions but I am not sure if I did it correctly or it is not working properly. In RegEdit I had to right-click &gt; New &gt; Key and enter "Layers" because it did not exist under ..\AppCompatFlags\. I then right-clicked under the default &gt; New &gt; String Value and entered the %ProgramFiles(x86)%\Microsoft Visual Studio\2017\Community\Common7\IDE\devenv.exe into the Name and set the value to DPIUNAWARE. It did not seem to take affect when I restarted VS 2017 Community. Did I enter the key correctly? Does it require a reboot? Also, I did not have the ..\devenv.exe key so that should not be affecting it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43b74bf9-71c6-2559-66f7-2e17de0702ef
* Version Independent ID: 9ad214a4-3ae0-f7e6-bb89-86067d97059d
* Content: [Disable DPI-awareness in Visual Studio](https://docs.microsoft.com/en-us/dotnet/framework/winforms/disable-dpi-awareness-visual-studio)
* Content Source: [docs/framework/winforms/disable-dpi-awareness-visual-studio.md](https://github.com/dotnet/docs/blob/master/docs/framework/winforms/disable-dpi-awareness-visual-studio.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by mairaw** [comment]
@merriemcgaw @OliaG can you help here?

**Comment by merriemcgaw** [comment]
@KlausLoeffelmann , can you help troubleshoot Ben's issue? I don't know if this is an OS specific key.  @BenLussier can you give us your system information? Is there a reason why you can't/won't be using the gold bar and it's link to launch VS in DPI Unaware mode?

**Comment by BenLussier** [comment]
It really is just that it gets to be a pain to have to click that everytime I open VS. I am on a HDPI monitor so I will always be using DPI Unaware mode. Its really just an annoyance more than anything.
Specs: Win 10 Home, version 10.0.17134 build 17134, lenovo thinkcentre m900, intell i5-6600T, x64, 16GB ram

**Comment by Shadowfita** [comment]
Same issue here. 4k display 300% scaling. Registry key made no difference. Windows 10 Pro.

**Comment by Gachl** [comment]
I have this issue too, created the registry key but am still prompted to restart VS2017 in DPI unaware mode. I have checked the path and it's correctly pointing to my VS2017 installation.

Screenshot: https://i.imgur.com/gVhbYDy.png

**Comment by Tanya-Solyanik** [comment]
Hi @Gachl Thank you for pointing out this problem! Could you please specify literal value of the path to the process instead of using %ProgramFiles(x86)%. This macro is not processed for this key.
For example this is a `.reg` script that works for my installation path:

> Windows Registry Editor Version 5.00
> 
> [HKEY_CURRENT_USER\Software\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers]
> "C:\\Program Files (x86)\\Microsoft Visual Studio\\Preview\\Enterprise\\Common7\\IDE\\devenv.exe"="DPIUNAWARE"
>

**Comment by Tanya-Solyanik** [comment]
Hi @BenLussier, could you please verify if you used a % macro in the path to devenv, or if you substituted it with a literal path? Could you please try the literal path as a registry value name?

**Comment by Gachl** [comment]
I can confirm that using the literal path did solve the issue and I am no longer prompted to switch to the DPI unaware mode. Thanks!
