### ISSUE TITLE
Possibly missing word

### ISSUE THREAD

**Issue by Dc9894** [dotnet/docs#8207]
Hi, english is not my first language, but it seems to me that a verb is missing in the sentence:

" … Adding and removing entities is directly _____ on the appropriate DbSet property ..."
 Should it be either "done" or "performed"?

Which is located in the third paragraph in the "Fetching and storing data" section. I know it's not a huge thing, just trying to improve readability for other readers :-)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e1a443c-c3dd-b865-58b2-0ff0902308ce
* Version Independent ID: 8843df22-85a5-c35b-864b-0b18864e5347
* Content: [Work with data in ASP.NET Core Apps](https://docs.microsoft.com/en-us/dotnet/standard/modern-web-apps-azure-architecture/work-with-data-in-asp-net-core-apps#ef-core-or-micro-orm)
* Content Source: [docs/standard/modern-web-apps-azure-architecture/work-with-data-in-asp-net-core-apps.md](https://github.com/dotnet/docs/blob/master/docs/standard/modern-web-apps-azure-architecture/work-with-data-in-asp-net-core-apps.md)
* Product: **dotnet**
* GitHub Login: @ardalis
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
Thanks for letting us know about this issue @Dc9894. A community member already jumped in to fix it.

Also, submitting quick edits to the documents should be super easy, in case you're interested:
https://docs.microsoft.com/en-us/contribute/#quick-edits-to-existing-documents
