### ISSUE TITLE
The content of the image is not accurate even though this way it is more useful to undestand the result.

### ISSUE THREAD

**Issue by xamarin-volkan** [dotnet/docs#8213]
The one at the end of the section named as "Creating the Data Set" with an url of https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/media/working-with-"linq/console.png".
Correct includings may be
{ Suit = clubs, Rank = two }
{ Suit = clubs, Rank = three }
...

Sorry if it's my bad.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a2b7453-076c-a18e-f999-cbd57ab13e60
* Version Independent ID: b687ed5b-5013-cceb-01e5-77f9cc7bb534
* Content: [Working with LINQ](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/working-with-linq#manipulating-the-order)
* Content Source: [docs/csharp/tutorials/working-with-linq.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/working-with-linq.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by xamarin-volkan** [comment]
Or may be to change for block as "Console.WriteLine(c.Rank + " of "+ c.Suit);"

**Comment by Thraka** [comment]
Hi @xamarin-volkan thanks for bringing this to our attention.

I think the screenshot was taken from the end of the tutorial, specifically from the "Preparing for New Features" section where the `ToString()` method was overridden.

This should be easy to fix.
