### ISSUE TITLE
Missing using rows in "Creating the Data Set"

### ISSUE THREAD

**Issue by xamarin-volkan** [dotnet/docs#8214]
Hi, thanks for your efforts. Really helpful. 
I wanted to inform you just because it is not followed as in previous tutorials.

using System.Collections.Generic;
using System.Linq;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a2b7453-076c-a18e-f999-cbd57ab13e60
* Version Independent ID: b687ed5b-5013-cceb-01e5-77f9cc7bb534
* Content: [Working with LINQ](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/working-with-linq#conclusion)
* Content Source: [docs/csharp/tutorials/working-with-linq.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/working-with-linq.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by svick** [comment]
This issue was fixed in https://github.com/dotnet/docs/pull/8136 and should be closed.

**Comment by xamarin-volkan** [comment]
thanks
