### ISSUE TITLE
Last edited date should use a better date format

### ISSUE THREAD

**Issue by svick** [dotnet/docs#822]
Currently, the header of an article looks like this (from [_About .NET_](https://docs.microsoft.com/en-us/dotnet/articles/about/index)):

![](http://i.imgur.com/WAFrxaf.png)

Notice the date: 7/6/2016. I realize that the `M/d/yyyy` date format is common in the US, but I find it very confusing, since I'm used to `d. M. yyyy` (e.g. 6. 7. 2016).

I think the date should be formatted in a way that is unambiguous to people used to either date format (or even other, more exotic date formats). I think the best choice is `d MMMM yyyy` (e.g. 6 July 2016). Another option would be to use ISO 8601 format: `yyyy-MM-dd` (e.g. 2016-07-06).

---

There's another thing I find confusing about the date: why is it 6 July? The article has `ms.date: 06/23/2016` and the latest commit that touched it is dated 4 July. This applies to both [live](https://github.com/dotnet/core-docs/blob/live/docs/about/index.md) and [master](https://github.com/dotnet/core-docs/blob/master/docs/about/index.md) branches.

**Comment by mairaw** [comment]
Thanks @svick. I already had bugs filed internally for the two issues reported. I've noticed the date mismatch the other day and an Australian customer complained about the date format on the site.

**Comment by svick** [comment]
It seems to me both issues are fixed now:

![](http://imgur.com/n2jrtBL.png)

The date is shown to me in a format that's readable to me and the date shown corresponds to `ms.date` from metadata.
