### ISSUE TITLE
Shared source package publishing locations?

### ISSUE THREAD

**Issue by TylerBrinkley** [dotnet/docs#8224]
What are the recommended locations for publishing a shared source package if not to nuget.org? Only private repositories? Providing support for older frameworks has always been a pain for developers so I was thinking a shared source package for adding missing commonly used API's could be helpful for library authors. Eg. https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Utilities/LinqBridge.cs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33821846-a525-de11-06a3-ac4552d6421f
* Version Independent ID: 30297ee3-b24d-9fd2-f007-6d381d125282
* Content: [Dependencies and .NET libraries](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/dependencies)
* Content Source: [docs/standard/library-guidance/dependencies.md](https://github.com/dotnet/docs/blob/master/docs/standard/library-guidance/dependencies.md)
* Product: **dotnet**
* GitHub Login: @JamesNK
* Microsoft Alias: **mairaw**

**Comment by jairbubbles** [comment]
Do you have any plans to provide tooling to help creating shared source packages? I do agree that it can help a lot managing dependencies but they're currently not much used at all. `nuget.exe` or `dotnet.exe` should allow to create such packages automatically: generate .nuspec, check that everything is internal, maybe set a specific flag in the metadata to indicate it is a source package and MsBuild should always import them as private.

**Comment by jairbubbles** [comment]
Why can't we have language specific packages on nuget.org? I mean if the package is properly flagged as a C# package, toolings from other languages could easily report an error when referenced and NuGet gallery can display them in a special category with proper dicsclaimers displayed.

**Comment by JamesNK** [comment]
> What are the recommended locations for publishing a shared source package if not to nuget.org?

MyGet, or Azure DevOps's package feature.

> Why can't we have language specific packages on nuget.org?

You can if you want to, it just isn't recommended. A shared source library excludes everyone that doesn't use the same language as you.

**Comment by jairbubbles** [comment]
> You can if you want to, it just isn't recommended. A shared source library excludes everyone that doesn't use the same language as you.

By reading the doc I feel like we're encouraged to make shared source packages but asking not to publish on nuget.org is like the opposite, like "do that but keep them hidden to the rest of the community".
