### ISSUE TITLE
Missing connector?

### ISSUE THREAD

**Issue by Dc9894** [dotnet/docs#8225]
Reading through the "Kinds of automated tests / Integration tests" the last section (last paragraph and the code) seem to have no connection with the previous text, a question arises when you read this: How is the code of the LocalFileImageService service relates to the integration tests subject? its like it appears out of nowhere and leads nowhere. 

It's like there is a missing paragraph explaining the point the author is trying to make with the code. Hope this could help other readers, or correct me if I'm wrong.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 628ba44f-bfb6-e9bf-0bba-b91ee867340d
* Version Independent ID: e7beb014-243f-1569-fca0-0c59bf6f3c05
* Content: [Test ASP.NET Core MVC apps](https://docs.microsoft.com/en-us/dotnet/architecture/modern-web-apps-azure/test-asp-net-core-mvc-apps)
* Content Source: [docs/architecture/modern-web-apps-azure/test-asp-net-core-mvc-apps.md](https://github.com/dotnet/docs/blob/master/docs/architecture/modern-web-apps-azure/test-asp-net-core-mvc-apps.md)
* Product: **dotnet**
* Technology: **dotnet-ebooks**
* GitHub Login: @ardalis
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
Thanks for your feedback @Dc9894.  @CESARDELATORRE @mvelosop @ardalis can one of you look at this issue?

**Comment by Dc9894** [comment]
Any news on this? I was just reading this doc today again and found myself lost again while trying to understand what's the point of that code. Does it even belong in this page?

**Comment by ardalis** [comment]
Currently the last paragraph on the page seems fine:

> This functional test exercises the full ASP.NET Core MVC / Razor Pages application stack, including all middleware, filters, binders, etc. that may be in place. It verifies that a given route ("/") returns the expected success status code and HTML output. It does so without setting up a real web server, and so avoids much of the brittleness that using a real web server for testing can experience (for example, problems with firewall settings). Functional tests that run against TestServer are usually slower than integration and unit tests, but are much faster than tests that would run over the network to a test web server. You should use functional tests to ensure your application's front-end stack is working as expected. These tests are especially useful when you find duplication in your controllers or pages and you address the duplication by adding filters. Ideally, this refactoring won't change the behavior of the application, and a suite of functional tests will verify this is the case.

If there is still a problem with this content (other than what you reference in #13273) can you let me know specifically what it is? There used to be a small sample showing an EF Core integration test, but that was removed. I'm in the process of fixing your other issue by removing the sentence that still referenced it. In a future update I may add back in something similar. Thanks!

**Comment by Dc9894** [comment]
Hi, I'm not referring to the last paragraph of the page, but to the last
paragraph of the "Integration Tests" Section.

There is a code there of a class "LoadFileImageService" that has no
relation with the previous context.

You can read the GitHub thread, where this was already acknowledged.

Regards.

**Comment by ardalis** [comment]
Ah, thanks for clarifying. Re-reading...

**Comment by ardalis** [comment]
Ok, when I first read through this I thought https://github.com/dotnet/docs/pull/10831 had been applied but now realize it never was. Requesting that PR be merged, which should resolve this issue (and give credit to @veleek for the fix).
