### ISSUE TITLE
Update RSACng doc with xPlatform supportability information

### ISSUE THREAD

**Issue by Raviuppa** [dotnet/docs#824]
CNG is Windows centric only and not supported on other platforms. However, the current doc https://docs.microsoft.com/en-us/dotnet/core/api/system.security.cryptography.rsacng is not disclosing any such and this may lead to confuse for developers who develop on Windows and deploy on Linux/Mac. 

The below .NET Core 1.0 app executes fine on Windows where as on non Windows such as Ubuntu, Mac, RHEL and other supported *NIX platforms, it throws System.TargetPlatformNotSupportedException.

using System;
using System.Security.Cryptography;

namespace ConsoleApp1
{
    public class Program
    {
        public static void Main(string[] args)
        {

```
          RSACng rsa = new RSACng();    

    }
}
```

}
# Error:

Unhandled Exception: **System.PlatformNotSupportedException**: Operation is not supported on this platform.
   at System.Security.Cryptography.RSACng..ctor()
   at ConsoleApp1.Program.Main(String[] args)

As CNG is Windows only technology, not disclosing this in our API docs may lead to confusion while targeting xPlat. 
## Issues with Existing Topics

CNG is Windows centric only and not supported on other platforms. However, the current doc https://docs.microsoft.com/en-us/dotnet/core/api/system.security.cryptography.rsacng is not disclosing any such and this may lead to confuse for developers who develop on Windows and deploy on Linux/Mac.

**Comment by joshfree** [comment]
The docs need to be improved here.  The issue is that developers should be using RSA.Create (platform agnostic) instead of directly using the concrete RSACng (windows) or RSAOpenSsl (linux, mac) classes when writing code that targets all platforms. 

/cc: @bartonjs

**Comment by mairaw** [comment]
I've updated the initial issue description to remove the boilerplate text from our template. The API reference right now is just using the IntelliSense from .NET to generate the basic API docs. We'll be able to improve those docs once we have our final solution for the API docs in place.
