### ISSUE TITLE
More Information?

### ISSUE THREAD

**Issue by wschin** [dotnet/docs#8255]
I know exactly every word here, but sadly I still don't know what this structure is for.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d83416c-37cc-9bf2-30c7-f88b9ce6b1f9
* Version Independent ID: 3dfec537-bdec-f88f-a682-73d01dd2154b
* Content: [MemoryHandle Struct (System.Buffers)](https://docs.microsoft.com/en-us/dotnet/api/system.buffers.memoryhandle?view=netcore-2.1)
* Content Source: [xml/System.Buffers/MemoryHandle.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Buffers/MemoryHandle.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks for your feedback @wschin. We're still in the process of documenting the new .NET Core APIs. We hope to address this shortly.
