### ISSUE TITLE
Typo in remarks sections

### ISSUE THREAD

**Issue by lardman** [dotnet/docs#8257]
Is there a typo in this sentence?: 
"For , LayoutKind.Sequential controls both the layout in managed memory and the layout in unmanaged memory"

I feel that 'blittable types' should follow 'for'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a787be3-458b-b2e6-f937-e7d2f6f629fc
* Version Independent ID: 4a246ad7-aba9-a4d9-20b4-079f3b65b3a3
* Content: [StructLayoutAttribute Class (System.Runtime.InteropServices)](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.structlayoutattribute?view=netframework-4.7.2)
* Content Source: [xml/System.Runtime.InteropServices/StructLayoutAttribute.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Runtime.InteropServices/StructLayoutAttribute.xml)
* Product: **dotnet-api**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by rpetrusha** [comment]
Thanks, @lardman, for pointing out that text is missing. And you're correct; the missing text is "blittable types". We've opened dotnet/dotnet-api-docs#609 to restore it.
