### ISSUE TITLE
TreeView and TreeNode for AspNet Core 2.1

### ISSUE THREAD

**Issue by Raghumu** [dotnet/docs#8264]
Are there any classes that replace TreeView and TreeNode in AspNet Core 2.1?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6f79099-978d-9b1e-7b87-fff907dc1017
* Version Independent ID: aeb00ac5-4497-e455-3909-8d689994e982
* Content: [System.Web.UI.WebControls Namespace](https://docs.microsoft.com/en-us/dotnet/api/system.web.ui.webcontrols?view=netframework-4.7.2)
* Content Source: [xml/ns-System.Web.UI.WebControls.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/ns-System.Web.UI.WebControls.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
@scottaddie @Rick-Anderson can you help with this question?

**Comment by scottaddie** [comment]
@Raghumu Microsoft doesn't ship any controls like this in ASP.NET Core. There are, however, 3rd party controls available from Microsoft partners (e.g. Telerik's [TreeView](https://www.telerik.com/aspnet-core-ui/treeview)).
