### ISSUE TITLE
This is not TDD

### ISSUE THREAD

**Issue by arnonax** [dotnet/docs#8266]
The article says: "To use test-driven development (TDD), you create a failing implementation of the PrimeService class:"
That's not TDD. In TDD you first write the unit test which doesn't compile, then the failing implementation of the PrimeService class, and then you implement the body of the PrimeService method(s).
I suggest that you simply remove that sentence, and keep the article as is except of it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c123f1f-8ae8-db21-2eac-4297bfc30b44
* Version Independent ID: 4675decb-333f-0508-5a3d-ce71dc85936d
* Content: [Unit testing C# with MSTest and .NET Core](https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-with-mstest)
* Content Source: [docs/core/testing/unit-testing-with-mstest.md](https://github.com/dotnet/docs/blob/master/docs/core/testing/unit-testing-with-mstest.md)
* Product: **dotnet-core**
* GitHub Login: @ncarandini
* Microsoft Alias: **wiwagn**

**Comment by mfe-** [comment]
>  In TDD you first write the unit test which doesn't compile
This confuses me. @arnonax From my knowledgebase you would write first a failing unittest and then write the implementation. To get the unit test failing it must be compileable. Shouldn't be that the case?

**Comment by drewkill32** [comment]
>In TDD you first write the unit test which doesn't compile

TTD means your write the test first before writing any logic to the unit under test. That does not mean that you write the test first and make sure it doesn't compile. You can write an empty function first, then the failing test, then the logic to the function. 

I think you are taking TTD to literally. The point of TTD is that the test is written before any logic is written. You don't literally have to write the test first, just before writing the internals of the function.
