### ISSUE TITLE
Surely this is not the latest syntax specification?

### ISSUE THREAD

**Issue by PatrickRyder** [dotnet/docs#8267]
What about being able to test for null and declare a strong type in the same statement?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bc2f58f-8fbc-9ff2-2312-8a5715536f1f
* Version Independent ID: 1dbd0d51-e1dc-8970-93f8-2a44fa71f7ba
* Content: [as (C# Reference)](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/as)
* Content Source: [docs/csharp/language-reference/keywords/as.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/as.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for pointing this out @PatrickRyder 

I thought I had updated this page as part of the additions for pattern matching in C# 7.  I clearly missed it.  

What needs to be added:

- [ ] Using `as` with a strongly typed variable initializer.
- [ ] Using `as` with value types
- [ ] using `as` to perform null checking.

**Comment by pkulikov** [comment]
@BillWagner I'm confused. The following still produces compile error:
```csharp
object a = 4;
var b = a as int;
```

@PatrickRyder did you mean the `is` expression, which is documented?
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/is#pattern-matching-with-is
https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-7#is-expression

**Comment by PatrickRyder** [comment]
Hi, Petr,

I think I was getting confused with the is keyword.  I was trying to find the new syntax for declaring a variable at the same time as testing it, e.g.:

if( sender is ComboBox myComboBox )
{
var item = myComboBox.SelectedItem;
}

My apologies.


  *
Patrick

________________________________

**Comment by BillWagner** [comment]
@pkulikov *sigh* you're right.  That's what I get for looking at something when my brain was totally focused on a different problem.

I hid my previous comment as resolved. (That seemed the best strategy).

One change that would be useful on the page for `as`:  Add a new sentence at the beginning of the **Remarks** section something like:

> The `is` expression can both test that a conversion will succeed and conditionally assign a variable when the conversion will succeed. In many scenarios, it is more concise than using the `as` operator.

The `is` above would be linked to the keyword for `is.

**Comment by pkulikov** [comment]
@PatrickRyder thanks for raising the issue. I don't think you are the only one who confuses `as` and `is`, especially given, how close those two in functionality and usage. As far as I remember, ReSharper suggests refactoring that converts `as` usage to the pattern matching with `is`. So, the addition suggested by @BillWagner is "in-field" and it's good it gets to the docs.
