### ISSUE TITLE
Need more info on the first C# code snippet

### ISSUE THREAD

**Issue by Arash-Sabet** [dotnet/docs#8274]
Would you please specify clearly the type of ```addedCategories``` and show how it's populated? This document should be self-expressive enough to help doing away from guessing.

```
// Configure the command and parameter.  
SqlCommand insertCommand = new SqlCommand(sqlInsert, connection);  
SqlParameter tvpParam = insertCommand.Parameters.AddWithValue("@tvpNewCategories", addedCategories);  
tvpParam.SqlDbType = SqlDbType.Structured;  
tvpParam.TypeName = "dbo.CategoryTableType";
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 560c5e47-3225-2f5f-c0ae-befbb281d347
* Version Independent ID: 6d2efc68-1645-e15a-91f0-25c188d8125a
* Content: [Table-Valued Parameters](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/sql/table-valued-parameters)
* Content Source: [docs/framework/data/adonet/sql/table-valued-parameters.md](https://github.com/dotnet/docs/blob/master/docs/framework/data/adonet/sql/table-valued-parameters.md)
* Product: **dotnet-framework**
* GitHub Login: @douglaslMS
* Microsoft Alias: **douglasl**

**Comment by douglaslMS** [comment]
@Arash-Sabet The content of the _addedCategories_ variable is explained by the examples in the following sections of the article:

For example, in [Passing a Table-Valued Parameter to a Stored Procedure](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/sql/table-valued-parameters#passing-a-table-valued-parameter-to-a-stored-procedure):

`DataTable addedCategories = CategoriesDataTable.GetChanges(DataRowState.Added);`

The examples demonstrate the statement in [Configuring a SqlParameter Example](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/sql/table-valued-parameters#configuring-a-sqlparameter-example): "System.Data.SqlClient supports populating table-valued parameters from DataTable, DbDataReader or IEnumerable<T> \ SqlDataRecord objects."

**Comment by douglaslMS** [comment]
@Arash-Sabet The [IDbColumnSchemaGenerator Interface](https://docs.microsoft.com/en-us/dotnet/api/system.data.common.idbcolumnschemagenerator?view=netcore-2.1) is _not_ only for internal use. You can use it to provide a custom implementation to generate a column schema through your implementation of the [IDbColumnSchemaGenerator.GetColumnSchema Method](https://docs.microsoft.com/en-us/dotnet/api/system.data.common.idbcolumnschemagenerator.getcolumnschema?view=netcore-2.1#System_Data_Common_IDbColumnSchemaGenerator_GetColumnSchema), from which you return a collection of `DbColumn` objects.

**Comment by Arash-Sabet** [comment]
Thanks @douglaslMS for the clarification. back to your first comment in this thread,  I think it makes sense to move up the definition of ```addedCategories``` right before the 1st code snippet just to reduce back and forth.
