### ISSUE TITLE
The link to the LocBAML source code is stale

### ISSUE THREAD

**Issue by PeterSmithRedmond** [dotnet/docs#8276]
The link https://go.microsoft.com/fwlink/?LinkID=160016 is no longer valid.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72e544a8-3979-26ea-39fb-316eafa71cdb
* Version Independent ID: 5b84e3b3-e09f-be5d-8936-ed1ceb81203c
* Content: [How to: Localize an Application](https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/how-to-localize-an-application)
* Content Source: [docs/framework/wpf/advanced/how-to-localize-an-application.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/advanced/how-to-localize-an-application.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks @PeterSmithRedmond. I'm closing this as a duplicate of #3623.
