### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by cheong00** [dotnet/docs#8288]
Please fix spelling "hte" to "the".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7eb81599-a548-5d41-4013-812d9148b09d
* Version Independent ID: de28387f-e401-9ecd-1fc0-a9e37d55d6ea
* Content: [String Class (System)](https://docs.microsoft.com/en-us/dotnet/api/system.string?view=netframework-4.7.2)
* Content Source: [xml/System/String.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System/String.xml)
* Product: **dotnet-api**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by mairaw** [comment]
Thank you @cheong00! Would you like to contribute and make the change yourself? We explain the process here: https://docs.microsoft.com/en-us/contribute/#quick-edits-to-existing-documents

If not, just lest us know and we'll take care of it!
