### ISSUE TITLE
The Win32 Clock interoperation sample link is broken

### ISSUE THREAD

**Issue by Arush-Agarampur** [dotnet/docs#8326]
That link at the very bottom of the page under the last picture is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f36a9db1-2776-6334-0438-f174d9c249db
* Version Independent ID: b62b7131-3e43-8e3a-251a-19f348006c70
* Content: [Walkthrough: Hosting a WPF Clock in Win32](https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/walkthrough-hosting-a-wpf-clock-in-win32)
* Content Source: [docs/framework/wpf/advanced/walkthrough-hosting-a-wpf-clock-in-win32.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/advanced/walkthrough-hosting-a-wpf-clock-in-win32.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thank you @Arush-Agarampur for your feedback. The link has been fixed.
