### ISSUE TITLE
Add an example project.json https://www.microsoft.com/net/core

### ISSUE THREAD

**Issue by blackdwarf** [dotnet/docs#835]
Cross-post from dotnet/cli#3633

This is a more of a doc bug , please please add an example project.json showing all the options at 
https://www.microsoft.com/net/core#windows
All i wanted to do was to add some exiting file and spent almost an hour searching for how to do it and then had to ask around to finally figure it out.

How do i add existing source files to project.json
How do i add local reference ( i don't want to use nuget )
I guess there are more questions like this.

/cc @tijoytom

**Comment by svick** [comment]
@tijoytom Why would you expect answers to your fairly specific questions on a "here is the bare minimum to get you started" page? Have you tried looking for links leading to more documentation or tutorials on that page?

---

That page currently says:

> You now have .NET core running on your machine!

> You can create a [website with ASP.NET Core](https://docs.asp.net/en/latest/getting-started.html) or you can visit the [.NET Core on GitHub](https://github.com/dotnet/core/) for more samples. Take a look at the [.NET Documentation](http://docs.microsoft.com/dotnet) to learn more about .NET Core, use one of our [interactive online tutorials](https://www.microsoft.com/net/learn) or get involved with the [community](https://dotnet.github.io/support) to learn more about .NET Core!

Maybe putting the links to documentation and tutorials before the dotnet/core samples would make more sense?

**Comment by blackdwarf** [comment]
@svick maybe. There is a documentation link high up there. But also, one thing that I've noticed here is that there is no link from the TOC under the .NET Core node to the project.json reference. This should also be fixed.

**Comment by mairaw** [comment]
This seems like scenarios we'd want to cover in our Getting Started @bleroy @cartermp

**Comment by BillWagner** [comment]
I propose we close this as no longer relevant with the csproj tooling.

Please vote 👍 or :-1:

**Comment by cartermp** [comment]
Oh yeah, we're closing this.
