### ISSUE TITLE
Very good

### ISSUE THREAD

**Issue by mredulorfiaz** [dotnet/docs#8355]
It was very helpful

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 322a60f9-0bd8-b432-653a-069c477a93fe
* Version Independent ID: dbc29edd-b142-f2d7-4824-dec9951f32c7
* Content: [Using Properties (C# Programming Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/using-properties)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/using-properties.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/using-properties.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
Thank you for your feedback @mredulorfiaz!
