### ISSUE TITLE
Rename C# Quickstarts as C# Tutorials

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#8359]
Search data indicates that the term "QuickStart" is not a common search term, when associated with a programming language. 

The quickstarts will be rebranded as tutorials, with updated redirection and terminology throughout those articles.

In addition, the String Interpolation quickstart will move to the section with the other tutorials as it assumes more existing knowledge of C# and .NET.

Tracked internally [here](https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1359786)

**Comment by pkulikov** [comment]
@BillWagner I'd be happy to contribute to the string interpolation part of this issue. 

>In addition, the String Interpolation quickstart will move to the section with the other tutorials as it assumes more existing knowledge of C# and .NET.

Does that mean that during the move, the quickstart can be simplified by removing the bits that explain what class is, what property is? In that case the quickstart becomes the subset of the current tutorial:
https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/string-interpolation

Do you think those two should be merged?

**Comment by BillWagner** [comment]
@pkulikov That's a second step.  I'll get the first part done (just moving).

Then, I'll open a new issue for those items. It would be great to have you help on that.

**Comment by BillWagner** [comment]
The task list for this issue is:

- [ ] rename "quick-start" directory to "intro-to-csharp" under "tutorials"
- [ ] configure all redirects
- [ ] find and update all links
- [ ] update TOCs
- [ ] Update the .NET Landing page
- [ ] update any internal text for "quick start" to "Introduction to C# tutorial"

**Comment by BillWagner** [comment]
Extra list of tasks discovered while updating internal text:

- [ ] Create issue to update Roslyn SDK quickstarts to tutorials (make that a separate PR)
- [ ] Update directories and namespaces in related local tutorials.
