### ISSUE TITLE
Change absolute https://docs.microsoft.com/dotnet links to relative links

### ISSUE THREAD

**Issue by rpetrusha** [dotnet/docs#8364]
## Change absolute https://docs.microsoft.com/dotnet links to relative links
 
There are a number of fully qualified URLs in the dotnet/docs repo that point to files in the dotnet/docs repo itself. These can be changed to relative links. For example, `https://docs.microsoft.com/dotnet/csharp/somearticle.md` can be changed a relative link.
 
There may also be some links in the dotnet/dotnet-api-docs repo, although most of the ones that surface in a search are in the XML portion of the managed reference and should be left as-is.

**Comment by msschl** [comment]
There are still some absolute links pointing to `https://docs.microsoft.com/dotnet/api/...`.

I don't know whether these links could be changed to relative links as well.

**Comment by NextTurn** [comment]
@rpetrusha 

I would suggest a supplement to the issue description:

Prefer `../` to `~/` in links for files in the same repo, as described in [styleguide/template.md](https://github.com/dotnet/docs/blob/master/styleguide/template.md#internal-links).
