### ISSUE TITLE
SDK Project Packaging Shouldn't be Recommended Yet

### ISSUE THREAD

**Issue by CoolDadTx** [dotnet/docs#8368]
There are too many gaps between the SDK project packaging and a standard nuspec file. The guidelines should only recommend this approach for the most basic of packages.  Known list of issues that I'm aware of:

1) Doesn't support all the standard NuGet specifiers that nuspec does.
2) Cannot have more than 1 DLL per package.
3) Cannot use project references at all unless you are OK with always releasing all projects at the same time. (e.g. no hotfixes).

Until these (and other) issues are resolved you shouldn't recommend the SDK project packaging. That is just trying to promote a feature that isn't ready yet. It's been over a year so most of these issues were reported so clearly there is no rush to get it right.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc2b4abb-c382-17ef-f1f3-1413ee27aaa0
* Version Independent ID: 4d4bb4d2-a8f4-f142-7154-40ce7fc7ae32
* Content: [NuGet and .NET libraries](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/nuget)
* Content Source: [docs/standard/library-guidance/nuget.md](https://github.com/dotnet/docs/blob/master/docs/standard/library-guidance/nuget.md)
* Product: **dotnet**
* GitHub Login: @JamesNK
* Microsoft Alias: **mairaw**

**Comment by JamesNK** [comment]
It is a recommendation to consider, not something we recommend everyone doing.

Would some additional detail about the limitations of SDK project packaging help?

**Comment by CoolDadTx** [comment]
Yes I think it is very important to identify the current limitations because switching to SDK packaging from nuspec is a big deal just to find out it won't work for your case.

**Comment by mairaw** [comment]
I'm moving this to our backlog @JamesNK. But let us know once you intend to work on this and I can assign this to a given sprint.

**Comment by davidfowl** [comment]
> Doesn't support all the standard NuGet specifiers that nuspec does.

Which ones?

> Cannot have more than 1 DLL per package.

Do you mean in a first class way? cc @natemcmaster Isn't there a way to add more dlls to the package?

> Cannot use project references at all unless you are OK with always releasing all projects at the same time. (e.g. no hotfixes).

Can you elaborate here?

**Comment by CoolDadTx** [comment]
@davidfowl ,
Which ones? https://developercommunity.visualstudio.com/content/problem/266675/package-metadata-properties-are-missing-from-sdk-p.html

Do you mean in a first class way? Project references are converted to package references in the nuspec file irrelevant of whether the project actually generates a package or not. Example: You have a solution called MyLib. It contains MyLib.Core and MyLib.Data. MyLib.Core is needed by MyLib.Data but by itself it doesn't make sense to use so historically you'd have a nuspec file in MyLib.Data that references both assemblies. However with the SDK format it assumes every project reference is a package and so the generated nuspec file references the MyLib.Core package even though no such package exists.

Can you elaborate here? Suppose you have a solution called OurSolution containing projects OurSolution.Core and OurSolution.Data. OurSolution.Data relies on OurSolution.Core. In this case both projects are separate packages that can be used by others. You release 1.0.0 so both packages are shipped as such. Later you find a bug in OurSolution.Data so you build a new version 1.0.1. However since you have no control over the generated dependencies the generated nuspec file for OurSolution.Data references the 1.0.1 version of OurSolution.Core. However since that project didn't have an issue you had no intentions of deploying it. But if you don't deploy both packages then when clients try to get 1.0.1 of OurSolution.Data it looks for 1.0.1 of OurSolution.Core and won't find it. Hence you cannot install it. I think there was mention of this issue occurring a short while back related to some VS SDK assemblies that were published so this problem exists in the wild today.

**Comment by natemcmaster** [comment]
>  Isn't there a way to add more dlls to the package?

Yeah, you write a .nuspec. I agree with @CoolDadTx's point about it being painful to customize some aspects of nuspec generation. Example: https://github.com/NuGet/Home/issues/5063. Sometimes, it's just not possible to get the .csproj to layout the package the way you want. In these cases, I recommend writing a nuspec file manually. This can still be used with a .csproj like this: 

```xml
<!-- In the .csproj -->
<PropertyGroup>
   <!-- When this is specified, msbuild /t:Pack aka (dotnet pack) will use your nuspec instead. -->
   <NuspecFile>MyCustomThing.nuspec</NuspecFile>
   <!-- optional: replacement tokens -->
   <NuspecProperties>dllPath=$(TargetPath);var=123;var2=xyz</NuspecProperties>
</PropertyGroup>
```

Example:
 * https://github.com/aspnet/BuildTools/blob/cd8e302fe13584c3bc0f5880d7ea9092c133bf09/src/ApiCheck.Console/Microsoft.AspNetCore.BuildTools.ApiCheck.nuspec
 * https://github.com/aspnet/BuildTools/blob/cd8e302fe13584c3bc0f5880d7ea9092c133bf09/src/ApiCheck.Console/ApiCheck.Console.csproj

By the way, the docs repo isn't really the right place for this issue. https://github.com/NuGet/Home is a better place for this. I've given feedback like this to the NuGet team over the last few years, but making it easier to pack custom layouts does not appear to be a high priority for them.

**Comment by JamesNK** [comment]
There aren't any changes I want to make to the .NET lib guidance for this. The current recommendation to use it if you can, or use a nuspec for other projects. I think that is fine.

**Comment by tdykstra** [comment]
@CoolDadTx Thanks for the suggestion, but per the comment from JamesNK I'm closing this issue:

>There aren't any changes I want to make to the .NET lib guidance for this. The current recommendation to use it if you can, or use a nuspec for other projects. I think that is fine.
>
>Going into detail about when you can and can't use an SDK project is outside of the scope of this documentation.
