### ISSUE TITLE
ListVIew closing tag in separated XAML block

### ISSUE THREAD

**Issue by LisandroSu** [dotnet/docs#8369]
@Prodigio commented on [Mon Oct 15 2018](https://github.com/dotnet/docs.de-de/issues/105)

The closing tag of `ListView` is separated from the XAML block. Should be together.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 3afc3f4f-bb7e-97fa-8ae2-31b5a550978b
* Version Independent ID: 279b1fbb-7225-1644-c6b1-12cdbbc05639
* Content: [Gewusst wie: Gruppieren von Elementen in einem ListView, in dem ein GridView implementiert ist](https://docs.microsoft.com/de-de/dotnet/framework/wpf/controls/how-to-group-items-in-a-listview-that-implements-a-gridview)
* Content Source: [docs/framework/wpf/controls/how-to-group-items-in-a-listview-that-implements-a-gridview.md](https://github.com/dotnet/docs.de-de/blob/live/docs/framework/wpf/controls/how-to-group-items-in-a-listview-that-implements-a-gridview.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by LisandroSu** [comment]
Hi Team,

Please check the issue.

Thanks!

**Comment by mairaw** [comment]
The customer is right. We have already an issue tracking the same problem: #2994
