### ISSUE TITLE
Add RepositoryUrl

### ISSUE THREAD

**Issue by Tornhoof** [dotnet/docs#8378]
As this is specifically for open-source libraries, maybe add a Consider adding RepositoryUrl/RepositoryType to the metadata list or other guidance on how to populate the repository element.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: fc2b4abb-c382-17ef-f1f3-1413ee27aaa0
* Version Independent ID: 4d4bb4d2-a8f4-f142-7154-40ce7fc7ae32
* Content: [NuGet and .NET libraries](https://docs.microsoft.com/de-de/dotnet/standard/library-guidance/nuget)
* Content Source: [docs/standard/library-guidance/nuget.md](https://github.com/dotnet/docs/blob/master/docs/standard/library-guidance/nuget.md)
* Product: **dotnet**
* GitHub Login: @JamesNK
* Microsoft Alias: **mairaw**

**Comment by JamesNK** [comment]
Ideally you should be using SourceLink and SourceLink will populate that information for you.

Calling that out on this page would be useful.
