### ISSUE TITLE
Proposal for API Docs - Attributes

### ISSUE THREAD

**Issue by richlander** [dotnet/docs#838]
# Proposal for API Docs - Attributes

Attributes provide extra information about types or members via decorating types and members with this information. Some attributes form part of the public contract (e.g. SerializableAttribute) whereas others simply augment (e.g. DebuggerDisplayAttribute) an experience with the type or member. The docs should be focussed on the first case since the second case is likely to distract from key issues and potentially confuse readers.

Today, the .NET API docs have a few problems with attributes:
- The docs try to hide attributes in the second category above, but do not have a complete list of these attributes to "opt-out". Various teams create and use new attributes all the time, so the "opt-out" strategy is a losing proposition.
- The docs don't do a good job of explaining why attributes are important.
- The attributes are displayed as part of the API signature and take away attention from this key information.

There are two parts of the proposal:
- Display only attributes that have been opted-in to being displayed. Ensure that the docs explain why each of these attributes is important, establishing an important concept for developers to understand.
- Move attributes to a different section of the page, leaving the declaration section to be focussed on signatures.
## Documenting Important Attributes

All of the important attributes should be documented, to introduce and describe each attribute and their associated concept. These attributes should be documented in (repo location) ~docs/standard/attributes.md.

The text for each attribute should be no longer than a paragraph, ideally 2 sentences. The sentence should link to both the API definition for the attributes and to a conceptual page that describes the associated concepts.

The following is an example of the expected format:
- [Serializable](https://docs.microsoft.com/en-us/dotnet/core/api/system.serializableattribute) - Indicates that a type can be serialized and deserialized with any serializer that supports standard .NET serialization, such as [Binary Serializer](https://msdn.microsoft.com/en-us/library/72hyey7b%28v=vs.110%29.aspx) or [JSON.NET](http://www.newtonsoft.com/json/help/html/SerializationAttributes.htm). [Serialization](https://msdn.microsoft.com/en-us/library/7ay27kt9%28v=vs.110%29.aspx) enables objects to be saved for later use (even after the program has teminated) or transfered to other processes or machines.

There are multiple categories of attributes. Assuming we can define intuitive categories, the attributes should be split into different sections within the document.
## Display on API pages

A given type or member should display all of the attributes that have been applied to it that are in the opt-in list. Each one of these attributes should link to the page where the attribute is described. For example: 
- [Serializable](https://docs.microsoft.com/en-us/dotnet/articles/standard/attributes#Serializable)

The list of attributes should be in a different location on the page than the API signature. Examples of current (undesired) behaviour:
- https://docs.microsoft.com/en-us/dotnet/core/api/system.aggregateexception
- https://docs.microsoft.com/en-us/dotnet/core/api/system.attribute
- https://docs.microsoft.com/en-us/dotnet/core/api/system.lazy-1
- https://docs.microsoft.com/en-us/dotnet/core/api/system.timezoneinfo
## Defining important attributes

We need to establish a list of important attributes that should be displayed on type and member pages. Each of these attributes should be adequately documented in a conceptual topic, to explain and describe why the attribute is important in the daily life of a .NET developer. 

Most of the attributes that need to be shown for any .NET docs will be in the "opt-in" list defined by the .NET Team. Some higher-level products will need to opt-in additional attributes, but they will be fewer in number. Those attributes should be opted-in in the same way, but not in core-docs repo.

There are two obvious options:
- Tools understand the format used in attributes.md and can glean the list of attributes from it. This is the easiest approach for writers.
- A sidecar file defines the set of important attributes, for example, attributes.json. Writers maintain the set of attributes in both attributes.md and attributes.json. The advantage of this approach is that it's easier for tools to read attribute.json and it allows for the possibility that attributes.md could document more attributes than deserve to show up in API documentation.

The second option is a bit more work for writers, but is easier for tools and offers more flexibility. It appears to be the better option.
## Plan

Develop this new capability in the documentation system. Start with ~3 attributes documented to pilot the feature, deploy live and then add the rest of the attributes over time.

**Comment by svick** [comment]
Related: Namespace summary in API reference should not show attributes #809

**Comment by mairaw** [comment]
We should already have this list somewhere since we don't display these attributes on MSDN. @bradygaster is this the one you were mentioning today that you were following up?

**Comment by mairaw** [comment]
@dend @adkinn

**Comment by mairaw** [comment]
We're closing this one. The API docs already list the attributes separately and you can click on each one for more information. We do a file called Filter.xml where we define which attributes should be shown or not shown.

If there's more work you'd like to see being done, please reopen this @richlander.
