### ISSUE TITLE
Contradictory advice

### ISSUE THREAD

**Issue by michael-wolfenden** [dotnet/docs#8382]
If I have a netstandard 2.0 library that can also target net461 without any code changes, should I ?

"CONSIDER adding a target for net461 when you're offering a netstandard2.0 target" indicates that I should to improve the experience for developers that are still on .NET Framework 4.6.1.

"AVOID using multi-targeting with .NET Standard if your source code is the same for all targets." seems to indicate that I shouldn't.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b3638c9-ea3c-1c9e-2763-5c3e8e965663
* Version Independent ID: aff99d6b-9471-9277-160b-670ee8028b53
* Content: [Cross-platform targeting](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/cross-platform-targeting)
* Content Source: [docs/standard/library-guidance/cross-platform-targeting.md](https://github.com/dotnet/docs/blob/master/docs/standard/library-guidance/cross-platform-targeting.md)
* Product: **dotnet**
* GitHub Login: @JamesNK
* Microsoft Alias: **mairaw**

**Comment by supergibbs** [comment]
I read that as: Don't add a bunch of `.NET Standard` targets if the code is the same, just use the lowest one. Additionally, due to a few issues in the .NET framework that weren't resolved until `v4.7.2`, including a `v4.6.1` target is nice for those using `v4.6.1 - v4.7.1` even though it's technically `.NET Standard 2.0`

**Comment by michael-wolfenden** [comment]
Right, so I should always multi target `netstandard2.0` and `net461`?

**Comment by Thraka** [comment]
If possible and you want to, that is the advice. You don't have to obviously.

**Comment by Thraka** [comment]
I'm going to close this unless you have any other questions. Thanks!!
