### ISSUE TITLE
Information about 

### ISSUE THREAD

**Issue by FabrizioCicala** [dotnet/docs#8383]
Hello, 
I'm a Computer Science student and I'm developing a thesis about ransomware. Through my research I found out that some ransomware are implemented in C# and they use the System.Security.Cryptography classes to achieve encryption. In the documentation it is claimed that when a new instance of one of the encryption algorithm classes is created, keys are autogenerated for ease of use, and default properties are as safe and secure as possible.  
Is it possible to know how exactly the randomness of the key and IV generation is achieved for the AesCryptoServiceProvider and for the RsaCryptoServiceProvider?

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff97b07c-d5f0-ed39-27d9-333a47531a72
* Version Independent ID: f327a9d1-e7cb-cd7d-2e20-38b8967fb688
* Content: [Cryptographic Services](https://docs.microsoft.com/en-us/dotnet/standard/security/cryptographic-services)
* Content Source: [docs/standard/security/cryptographic-services.md](https://github.com/dotnet/docs/blob/master/docs/standard/security/cryptographic-services.md)
* Product: **dotnet**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by tdykstra** [comment]
@FabrizioCicala Apologies for late response to this -- do you still need this information or have you already found the answer somewhere else?
