### ISSUE TITLE
Breaking Change Should Be Avoided Too

### ISSUE THREAD

**Issue by rvhuang** [dotnet/docs#8385]
The breaking changes between versions should be avoided as much as possible. In some situations, if breaking changes are inevitable, a comprehensible migration guide should be presented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e80fe2fd-cbdb-699e-0dbb-a0a310bd372c
* Version Independent ID: 266d08ae-344a-683b-11e2-143b704e21a8
* Content: [Open-source library guidance](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/)
* Content Source: [docs/standard/library-guidance/index.md](https://github.com/dotnet/docs/blob/master/docs/standard/library-guidance/index.md)
* Product: **dotnet**
* GitHub Login: @JamesNK
* Microsoft Alias: **mairaw**

**Comment by AndyCJ** [comment]
This page just describes the type of recommendations. It's not the list of actual recommendations. If you click "Getting Started" you'll be taken to the list of contents, and one of the listed pages is: https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/breaking-changes

**Comment by CShepartd** [comment]
Semver describe that. There is no reason to be avoided as much as possible a breaking changes, until it following semver and changelog
