### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by ChrisMaddock** [dotnet/docs#8386]
https://www.myget.org/opensource no longer exists.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e51d820-1f85-192c-9169-cd965581b4f1
* Version Independent ID: 9e7ea8c7-ae47-eda8-4ba0-d5f59a3ade3c
* Content: [Publishing a NuGet package](https://docs.microsoft.com/en-gb/dotnet/standard/library-guidance/publish-nuget-package)
* Content Source: [docs/standard/library-guidance/publish-nuget-package.md](https://github.com/dotnet/docs/blob/master/docs/standard/library-guidance/publish-nuget-package.md)
* Product: **dotnet**
* GitHub Login: @JamesNK
* Microsoft Alias: **mairaw**

**Comment by JamesNK** [comment]
Hmmm, MyGet may no longer offer a plan for open source projects.

**Comment by tbolon** [comment]
It does, but it is not displayed anymore on their website, see comments on the [acquisition announcement](https://blog.myget.org/post/2018/08/31/assembla-acquisition.html).

**Comment by ChrisMaddock** [comment]
Good find @tbolon. It would be great if there was a more authoritative source though.

I wonder if @maartenba or @xavierdecoster could advise?

**Comment by laithassembla** [comment]
Hi everyone, we certainly do still support the open source community (we just removed the page from the site). Our free plan includes the same features as the old open source plan. You can create and share public feeds. You can simply sign up for a free trial here. The trial includes all paid features for 14 days then automatically reverts to a free (open source) plan after 14 days. No credit card or payment required. Hope this helps. Thank you! https://www.myget.org/Account/Register?ReturnUrl=%2FSubscription%2FSignUp%3Fsubscription_type%3Dtrial

**Comment by JamesNK** [comment]
Good news! We'll need to remove the dead link and reword the article in our docs.

**Comment by Thraka** [comment]
@laithassembla @JamesNK @giotavekiari 

I think the myget website should make this clear, not our docs here. This will just cause confusion because we'll be saying there is something free behind a subscription model that really could change at any moment (as it did in this case of removing the page from the myget site) 

We should just simply state that "MyGet is available for public and private feeds." We shouldn't advertise more than what is actually printed on the website.

**Comment by ChrisMaddock** [comment]
Foxed in https://github.com/dotnet/docs/pull/8615 - thanks!
