### ISSUE TITLE
Why AVOID NuGet package references that demand an exact version?

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/docs#8389]
Why AVOID NuGet package references that demand an exact version? What package version should be used when reference a package?

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: e80fe2fd-cbdb-699e-0dbb-a0a310bd372c
* Version Independent ID: 266d08ae-344a-683b-11e2-143b704e21a8
* Content: [Open-source library guidance](https://docs.microsoft.com/zh-cn/dotnet/standard/library-guidance/)
* Content Source: [docs/standard/library-guidance/index.md](https://github.com/dotnet/docs/blob/master/docs/standard/library-guidance/index.md)
* Product: **dotnet**
* GitHub Login: @JamesNK
* Microsoft Alias: **mairaw**

**Comment by maxwellb** [comment]
If your new FooLibrary in depends on BarPackage version 1.1 _exactly_, then a person installing your FooLibrary from NuGet will not be able to use updates to BarPackage such as 1.2.

See [Version ranges and wildcards
](https://docs.microsoft.com/en-us/nuget/reference/package-versioning#version-ranges-and-wildcards) and the [.nuspec <dependencies> element](https://docs.microsoft.com/en-us/nuget/reference/nuspec#dependencies-element) references for more information.

**Comment by JamesNK** [comment]
This page just describes the type of recommendations. It's not the list of actual recommendations. If you click "Getting Started" you'll be taken to the list of contents. 

https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/dependencies#nuget-dependency-version-ranges

**Comment by pkulikov** [comment]
@JamesNK 
>This page just describes the type of recommendations. 

To make that statement explicit and make the page less confusing, should the **Recommendations** section be renamed to **Types of recommendations**. Then, its first paragraph can be clarified in the following way:
> Articles in this guidance contain recommendations of four following types: **Do**, **Consider**, **Avoid**, and **Do not**. The type of a recommendation indicates how strongly the recommendation should be followed.

**Comment by WeihanLi** [comment]
Thanks

**Comment by ronenfe** [comment]
How do you even specify an exact version. When I specify an exact version in the project file, it makes it as a minimum version.
