### ISSUE TITLE
"Windows Azure Access Control Service" almost retired 

### ISSUE THREAD

**Issue by SychevIgor** [dotnet/docs#8393]
"for example, the Windows Azure Access Control Service (ACS)."
ACS will be retired during next 3 weeks. It will be right to cleanup this document from this retired feature during next couple of weeks 
https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-acs-migration

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1597a0b7-494d-0cca-bc54-e432719d2256
* Version Independent ID: 17d1429f-ff5d-8f13-bdbd-b8147808305b
* Content: [Claims Based Authorization Using WIF](https://docs.microsoft.com/en-us/dotnet/framework/security/claims-based-authorization-using-wif)
* Content Source: [docs/framework/security/claims-based-authorization-using-wif.md](https://github.com/dotnet/docs/blob/master/docs/framework/security/claims-based-authorization-using-wif.md)
* Product: **dotnet-framework**
* GitHub Login: @BrucePerlerMS
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
@SychevIgor thanks for your input. I believe we're trying to retire the entire section for WIF: https://docs.microsoft.com/en-us/dotnet/framework/security/. 

/cc @brentschmaltz

**Comment by brentschmaltz** [comment]
@mairaw the WIF code is still part of .Net Framework and will be supported for some time. What do you mean by 'retire'?

**Comment by SychevIgor** [comment]
@mairaw @brentschmaltz

**Comment by jordanmills** [comment]
Brent, https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-acs-migration

**Comment by brentschmaltz** [comment]
@jordanmills I am not seeing where WIF is being 'retired' in the link above.
