### ISSUE TITLE
Which XML Schema version is used in the validation?

### ISSUE THREAD

**Issue by YvonneArnoldus** [dotnet/docs#8399]
Hi,

Which XML Schema version (1.0 & 1.1) is used in the validation? We do a &lt;xs:redefine&gt; in our schema with 
&lt;xs:choice&gt;
          &lt;xs:element ref="no-topic-nesting" maxOccurs="0" minOccurs="0"/&gt;
 &lt;/xs:choice&gt;

Which gives the error "Invalid particle derivation by restriction" in XmlSchemaSet.Compile(). We did a schema validation in Oxygen and which we do not get the error. 

Oxygen uses XML Schema version 1.1 it would be nice to know which version Microsoft is using.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e99bf3b5-3eb2-a0d3-2009-4fb2b9de3b76
* Version Independent ID: 8252e3d3-0718-9814-d685-852387f16afd
* Content: [XML Schema (XSD) Validation with XmlSchemaSet](https://docs.microsoft.com/en-us/dotnet/standard/data/xml/xml-schema-xsd-validation-with-xmlschemaset)
* Content Source: [docs/standard/data/xml/xml-schema-xsd-validation-with-xmlschemaset.md](https://github.com/dotnet/docs/blob/master/docs/standard/data/xml/xml-schema-xsd-validation-with-xmlschemaset.md)
* Product: **dotnet**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by tdykstra** [comment]
@YvonneArnoldus Apologies for late response to this -- do you still need this information or has it already found the answer somewhere else?

**Comment by yvonne-arnoldus** [comment]
@tdykstra,

I have not found the answer and would like to know.

**Comment by mairaw** [comment]
@buyaa-n, @krwq can you help with this question about which XML schema version is used by .NET? I believe it's 1.0 but not sure.

**Comment by buyaa-n** [comment]
Yes we support 1.0 https://www.w3.org/TR/xmlschema-1/

**Comment by mairaw** [comment]
Thanks for confirming @buyaa-n.
