### ISSUE TITLE
translation

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#8404]
@autumn009 commented on [Fri Oct 12 2018](https://github.com/dotnet/docs.ja-jp/issues/161)

原文が少々曖昧さを含んでいるので、少し語句を補った方が良いと思います。

戻されるタスクが完了する前にチェックされるキャンセル トークン。
The cancellation token that will be checked prior to completing the returned task.
　↓
戻されるタスクが完了するタイミング以前にタスクをキャンセルするか否かをチェックされるキャンセル トークン。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 6ec08720-a8de-c325-20d4-7735044afa5a
* Version Independent ID: e3828f5f-0390-8640-3e1d-518b1f08145a
* Content: [Task.Delay Method (System.Threading.Tasks)](https://docs.microsoft.com/ja-jp/dotnet/api/system.threading.tasks.task.delay?view=netframework-4.7.2#feedback)
* Content Source: [xml/System.Threading.Tasks/Task.xml](https://github.com/dotnet/dotnet-api-docs.ja-jp/blob/live/xml/System.Threading.Tasks/Task.xml)
* Product: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

---

@LisandroSu commented on [Fri Oct 12 2018](https://github.com/dotnet/docs.ja-jp/issues/161#issuecomment-429404410)

こんにちは、@autumn009

フィードバックをお送りいただきありがとうございました。 

コメントを確認中で、改めてご連絡させていただきます。 

敬具 
Microsoft DOCS International Team 

---

@CeciAc commented on [Tue Oct 16 2018](https://github.com/dotnet/docs.ja-jp/issues/161#issuecomment-430332354)

こんにちは、@autumn009

コメントをお送りくださりありがとうございます。今回のご提案内容に基づき修正を行った場合、原文と訳文にずれが生じてしまうため、申し訳ございませんが見送らせていただきます。いただいたフィードバックは原文の品質向上に役立てさせていただきます。貴重なご意見をありがとうございました。

という理由で、承認基準に完全には適合していないという結果になりました。

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。   
 
敬具  
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hi team, 
This came as a linguistic issue, but after reviewing it, our linguist suggested a modification in the source content.
_This feedback requests an addition to the target side. It has to be declined to keep the source-target alignment, but could you please escalate it to an appropriate party that is in charge of the source text so that the feedback helps improve the source side?

Source: The cancellation token that will be checked prior to completing the returned task.

Suggested correction to the source: The cancellation token that will be checked whether the returned task is cancelled or not prior to completing it._

Kind regards
Microsoft DOCS International Team

**Comment by rpetrusha** [comment]
Thanks, @CeciAc. We've opened dotnet/dotnet-api-docs#627, which replaces the text with the standard text ("A cancellation token to observe while waiting for the task to complete.") that we've used elsewhere to describe the CancellationToken parameter.
