### ISSUE TITLE
Interlocked: confusing paragraph about 64-bit overloads

### ISSUE THREAD

**Issue by pkulikov** [dotnet/docs#8405]
The paragraph in question:
>The `Read` method and the 64-bit overloads of the `Increment`, `Decrement`, and `Add` methods are truly atomic only on systems where a `System.IntPtr` is 64 bits long. On other systems, these methods are atomic with respect to each other, but not with respect to other means of accessing the data. Thus, to be thread safe on 32-bit systems, any access to a 64-bit value must be made through the members of the `Interlocked` class.

The sentence that puzzles me is that one:
> On other systems, these methods are atomic with respect to each other, but not with respect to other means of accessing the data.

Does it say that mentioned `Interlocked` methods do not perform atomic operations on 32 bit systems?

And then it confuses even more:
> Thus, to be thread safe on 32-bit systems, any access to a 64-bit value must be made through the members of the `Interlocked` class.

The paragraph has just stated that those `Interlocked` methods are not atomic and recommends using them.

What message is this paragraph trying to deliver? Should it be removed at all from the docs?

/cc @rpetrusha 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57970c3f-b84d-e0c2-9260-4a60d3ccd60e
* Version Independent ID: ada70915-3c7d-3c1a-1668-70027bf9bb04
* Content: [Interlocked.Read(Int64) Method (System.Threading)](https://docs.microsoft.com/en-us/dotnet/api/system.threading.interlocked.read?view=netframework-4.7.2)
* Content Source: [xml/System.Threading/Interlocked.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Threading/Interlocked.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
I agree that it's confusing (or perhaps mystifying), @pkulikov. And it clearly implies that Interlocked is not thread-safe on 32-bit systems unless other Interlocked methods are used. I'd interpret that to mean that, during a call to an Interlocked method, some call to a non-interlocked method can cause the interlocked method to be non-atomic and so corrupt the data. @stephentoub, do you know whether that's really what the documentation intended to say, or whether it means something else instead?

**Comment by mikedn** [comment]
> The paragraph has just stated that those Interlocked methods are not atomic and recommends using them.

They are atomic. But only if all accesses are done using them. If in one place you have `Interlocked.Read(ref longVar)` and in another place you have `longVar = 42;` then the result of the read might not be 42.

**Comment by stephentoub** [comment]
What @mikedn said.

You can see this pretty easily with a little experiment.  Compile/run the following as 32-bit:
```C#
using System;
using System.Threading;
using System.Threading.Tasks;

class Program
{
    static void Main()
    {
        long value = 0;

        Task.Run(() =>
        {
            for (int i = 0; i < int.MaxValue; i++)
            {
                //value = ((long)i << 32) | i;
                Interlocked.Exchange(ref value, ((long)i << 32) | i);
            }
        });

        while (true)
        {
            long readValue = Interlocked.Read(ref value);
            int high = (int)(readValue >> 32);
            int low = (int)readValue;
            if (high != low)
            {
                Console.WriteLine($"Failed: {high:x} != {low:x}");
            }
        }
    }
}
```
You shouldn't see any output.  Then comment out the Interlocked.Exchange and uncomment the line above it, and you'll see a whole bunch of failures along the lines of:
```
Failed: f9 != fa
Failed: 10ed96 != 10ed97
Failed: 17a82f != 17a830
Failed: 1971aa != 1971ab
Failed: 1b23dc != 1b23dd
Failed: 1cec05 != 1cec06
Failed: 1e7d36 != 1e7d37
Failed: 1fcff4 != 1fcff5
Failed: 211a27 != 211a28
Failed: 22663c != 22663d
Failed: 23aec3 != 23aec4
Failed: 250bbb != 250bbc
Failed: 264622 != 264623
Failed: 277a50 != 277a51
...
```
due to the torn read/writes.

**Comment by pkulikov** [comment]
@rpetrusha @mikedn thanks for quick replies; they explain a lot

>I'd interpret that to mean that, during a call to an Interlocked method, some call to a non-interlocked method can cause the interlocked method to be non-atomic and so corrupt the data.

@rpetrusha could you please clarify what "atomic" means and how "call to a non-interlocked method can cause the interlocked method to be non-atomic"? I interpret it as the instructions of the non-interlocked call are inserted in the middle of the interlocked call. I think my interpretation is wrong here.

I understand that the interlocked call instructions might be executed in the middle of the non-interlocked call instructions. That makes data corrupt. Also, in the example given by @mikedn the read might be not 42 because the interlocked `Read` is executed in the middle of `longVar = 42;`. Is it correct understanding?

What confused me about the paragraph is that it sounds like the interlocked method can be torn by other instructions.

**Comment by pkulikov** [comment]
@stephentoub thanks a lot for the example!
> due to the torn read/writes.

To clarify: in all the cases the write is torn by the read, and not vice versa?

**Comment by mikedn** [comment]
> Also, in the example given by @mikedn the read might be not 42 because the interlocked Read is executed in the middle of longVar = 42;. Is it correct understanding?

Yep. On 32 bit `longVar = 42` becomes 2 instructions in assembly code - one stores the lower 32 bits and the other stores the upper 32 bits, in no particular order. It's like a struct containing 2 `int` fields. Even if the read is atomic, the write `longVar = 42` is not so the read may produce something other than 42. It will always produce 42 in the lower 32 bits, the question is what you get in the upper 32 bits - it can be 0 or whatever was there before the `longVar = 42` write.

> The Read method and the 64-bit overloads of the Increment, Decrement, and Add methods are truly atomic only on systems where a System.IntPtr is 64 bits long

Perhaps the above documentation bit needs adjusting, it is misleading. These operations are atomic, period. Sure, if they are used improperly then the result may not be what you expect. But the same is true about pretty much all other thread synchronization constructs - you need cooperation. Much like all users of a shared resource need to acquire its lock to use it, if some fail to do that it does not mean that the lock isn't doing its job.

**Comment by pkulikov** [comment]
@mikedn thanks! You caught the essence: 
> But the same is true about pretty much all other thread synchronization constructs - you need cooperation. 

@rpetrusha should this paragraph be rephrased in the following way:
> Make sure that all read/writes from/to a variable are done with the methods from the `Interlocked` class. Otherwise, the data might be corrupted or the read value might be incorrect.

And, as this is the general statement, this paragraph should be placed in the class overview.
What do you think?
