### ISSUE TITLE
Update the Running Windows Vista, Windows Server 2008 R2 or Windows 7 section

### ISSUE THREAD

**Issue by hufftracey** [dotnet/docs#8406]
Update the "Running Windows Vista, Windows Server 2008 R2 or Windows 7" section to include Server 2012 R2.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9096dc31-bc97-a413-880f-962603bed316
* Version Independent ID: 68c92a65-812f-f665-7df2-24e1e1e65048
* Content: [Configuring HTTP and HTTPS](https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/configuring-http-and-https)
* Content Source: [docs/framework/wcf/feature-details/configuring-http-and-https.md](https://github.com/dotnet/docs/blob/master/docs/framework/wcf/feature-details/configuring-http-and-https.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thank you for your feedback @hufftracey. I've updated the topic to remove some of the older operating systems instructions. The changes should go live within a day.
