### ISSUE TITLE
Cross-platform targeting: Add advice on targeting .Net Core

### ISSUE THREAD

**Issue by brandonh-msft** [dotnet/docs#8407]
Would love to see this included. It seems to be a constant point of confusion when/if one should target/reference .Net Core vs .Net Standard and what considerations should be made if/when you do so

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b3638c9-ea3c-1c9e-2763-5c3e8e965663
* Version Independent ID: aff99d6b-9471-9277-160b-670ee8028b53
* Content: [Cross-platform targeting](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/cross-platform-targeting)
* Content Source: [docs/standard/library-guidance/cross-platform-targeting.md](https://github.com/dotnet/docs/blob/master/docs/standard/library-guidance/cross-platform-targeting.md)
* Product: **dotnet**
* GitHub Login: @JamesNK
* Microsoft Alias: **mairaw**

**Comment by rpetrusha** [comment]
Thanks for the suggestion, @brandonh-msft. We've added it to our backlog, as well as to our community contributor's project.

**Comment by dozer75** [comment]
@rpetrusha 

What's the progress on this (or does any source for advice exist)? It's been over a year, but no information. 

I am struggling seeing when (and why) to target .NET Core/.NET Standard other than the dependent packages does so it would be really nice if this information was added to the article.

Looking at Microsoft packages they're doing it different, so it's not clear by looking at them either.
