### ISSUE TITLE
Useful example but with some rework

### ISSUE THREAD

**Issue by hansmichielscom** [dotnet/docs#8408]
Besides the fact that the example is useful and working I personally think it is a pity that GUI (WinForm) and business logic (Encryption/Decryption) is not separated for easier reuse. If this would be the case, the form would only handle the code needed to interact with the user and would delegate the business logic to a separate class. Now there are a lot of hidden dependencies (which private field is used where?) and hidden logic in the naming of original file, decrypted and encrypted file. Why not pass the full paths to the encryption/decryption methods, and let the consumer of the class decide on the filenames?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a8e441d-cd59-de15-a814-0d86d4cda052
* Version Independent ID: c94ca6d4-7e93-8aac-93d1-7f249c77d243
* Content: [Walkthrough: Creating a Cryptographic Application](https://docs.microsoft.com/en-us/dotnet/standard/security/walkthrough-creating-a-cryptographic-application)
* Content Source: [docs/standard/security/walkthrough-creating-a-cryptographic-application.md](https://github.com/dotnet/docs/blob/master/docs/standard/security/walkthrough-creating-a-cryptographic-application.md)
* Product: **dotnet**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by tdykstra** [comment]
@hansmichielscom Thanks for the suggestion, but we don’t have the resources to implement it, so we are closing the issue. If we get more 👍 responses to the issue, we’ll reconsider.
