### ISSUE TITLE
Re: how-to-retrieve-data-from-the-clipboard

### ISSUE THREAD

**Issue by rwhoech** [dotnet/docs#8409]
I am trying to retrieve text from clipboard for a c++ app.   Your examples are for C#, which has left me feeling deflated (D-flatted?).  Where can I find sample code that MS VS 2015 C++ DS will compile?   

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28fa8e4a-d21b-c83a-c786-9cc2a40368e1
* Version Independent ID: 056c932f-5717-4be1-0915-7fe872f2f5c9
* Content: [How to: Retrieve Data from the Clipboard](https://docs.microsoft.com/en-us/dotnet/framework/winforms/advanced/how-to-retrieve-data-from-the-clipboard)
* Content Source: [docs/framework/winforms/advanced/how-to-retrieve-data-from-the-clipboard.md](https://github.com/dotnet/docs/blob/master/docs/framework/winforms/advanced/how-to-retrieve-data-from-the-clipboard.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by tdykstra** [comment]
@rwhoech Apologies for the delayed response, but check out https://docs.microsoft.com/en-us/windows/win32/dataxchg/using-the-clipboard

It has an example of using [GetClipboardData](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getclipboarddata) in several ways, in the [Example of a Clipboard viewer](https://docs.microsoft.com/en-us/windows/win32/dataxchg/using-the-clipboard#example-of-a-clipboard-viewer) sample code.
