### ISSUE TITLE
Why is this guidance limited to open source?

### ISSUE THREAD

**Issue by paulbatum** [dotnet/docs#8416]
Much of this guidance is applicable to library authors regardless of whether the library is open source. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e80fe2fd-cbdb-699e-0dbb-a0a310bd372c
* Version Independent ID: 266d08ae-344a-683b-11e2-143b704e21a8
* Content: [Open-source library guidance](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/)
* Content Source: [docs/standard/library-guidance/index.md](https://github.com/dotnet/docs/blob/master/docs/standard/library-guidance/index.md)
* Product: **dotnet**
* GitHub Login: @JamesNK
* Microsoft Alias: **mairaw**

**Comment by JamesNK** [comment]
I tried to come up with a quick way to describe libraries that are released publicly and this guidance should be applied to, vs a C# libraries that are internal to an app and most of this guidance doesn't matter.

"Open source libraries" is the best descriptor I could think of to differentiate the two.

**Comment by paulbatum** [comment]
It makes sense, I just feel like most of this guidance is applicable to anything published to NuGet, regardless of whether its open source or not! There are a few exceptions (source linking, how to handle strong name key) but they seem relatively minor. Its great guidance and I'd like to make sure its as broadly discovered and internalized by the .NET community as possible. If you're not comfortable changing the wording around this and want to keep it limited to open source, then I think we can just close this issue.

**Comment by mairaw** [comment]
So, maybe something as "Public .NET libraries guidance"?

**Comment by terrajobst** [comment]
Quite frankly, I believe we try to hard. The term "Library guidance" seems sufficient to me. I'd argue this guidance equally applies to internal libraries; but of course it might not be worth it. But I think customers should decide this for themselves.

Any objections to the rename?

**Comment by SamuelEnglard** [comment]
Hasn't been renamed @mairaw (I would tag the team, but I cannot)

**Comment by BillWagner** [comment]
reopening per comment.

Let's go with "Library guidance".

When fixing this remember to check the TOC, H1 headings, title metadata and inbound links.
