### ISSUE TITLE
Out of date

### ISSUE THREAD

**Issue by GeekAndProud** [dotnet/docs#8417]
This documentation refers to features that were removed from Visual Studio years ago...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02bb2607-4589-179e-55c1-0749dd134ed5
* Version Independent ID: a8dc7f55-6bff-cf9e-9fa5-8c74df09f3b6
* Content: [Walkthrough: Using Client Application Services](https://docs.microsoft.com/en-us/dotnet/framework/common-client-technologies/walkthrough-using-client-application-services)
* Content Source: [docs/framework/common-client-technologies/walkthrough-using-client-application-services.md](https://github.com/dotnet/docs/blob/master/docs/framework/common-client-technologies/walkthrough-using-client-application-services.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thank you for bringing this to our attention @GeekAndProud. I think we should remove this topic from the current documentation set.
