### ISSUE TITLE
hosts file?

### ISSUE THREAD

**Issue by samrueby** [dotnet/docs#8418]
Does this method bypass the hosts file?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd3de4e8-2530-2565-2873-053d4b0d9d38
* Version Independent ID: 058be335-0104-8c08-5adb-a9b5aea2a077
* Content: [Dns.GetHostAddresses(String) Method (System.Net)](https://docs.microsoft.com/en-us/dotnet/api/system.net.dns.gethostaddresses?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(System.Net.Dns.GetHostAddresses);k(TargetFrameworkMoniker-.NETFramework,Version%3Dv4.6.2);k(DevLang-csharp)%26rd%3Dtrue&view=netframework-4.7.2)
* Content Source: [xml/System.Net/Dns.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net/Dns.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by samrueby** [comment]
I learned that it does NOT bypass the hosts file.

This is confusing because the name of the class is "DNS". I would assume this would return results strictly from DNS, like how the nslookup utility functions.

**Comment by karelz** [comment]
Aren't host files kind of explicit DNS configuration?
AFAIK we do not parse the files ourselves, we ask DNS APIs which return us values based on their configuration.

cc @wfurt @davidsh

**Comment by wfurt** [comment]
DNS is network protocol. However it is often used as broader "name resolution" service. 
host file processing is not part of RFC1035 but is used on all supported platforms as part of the name services including  Dns.GetHostAddresses()
On Unix for example that function will also use other providers (like NIS)

**Comment by davidsh** [comment]
>AFAIK we do not parse the files ourselves

Correct.  Our System.Net networking layer does not parse any 'hosts' file directly.  The DNS subsystem in the operating system uses the 'hosts' file.

>This is confusing because the name of the class is "DNS". I would assume this would return results strictly from DNS, like how the nslookup utility functions.

Unfortunately, you are correct about what the System.Net.Dns class actually does.  It does NOT strictly use DNS protocol.  It uses higher-layer "name resolver" functions in the OS.  This means it will use non-DSN protocol mechanisms to resolves names, like NetBIOS, etc.

We have had requests for enhancements to the System.Net.Dns class such as adding the ability to return TXT or MX records for example.  But strictly speaking, despite the name 'Dns' of the .NET type, this class is not strictly a DNS class.

**Comment by karelz** [comment]
DNS apparently can refer to both - the protocol or subsystem. We use it in the sense of subsystem.
Unless it confuses more developers, I suggest to close the issue as answered. @samrueby are you ok with that?

**Comment by samrueby** [comment]
The documentation explicitly wrote "The GetHostAddresses method queries a DNS server...". "DNS Server" is the reason this is confusing and seemed to make it clear it meant the protocol.

I am okay with closing this because I created a documentation pull request: https://github.com/dotnet/dotnet-api-docs/pull/653
