### ISSUE TITLE
Error in this doc: `GetDescription` text and link should be `GetGroupName`

### ISSUE THREAD

**Issue by estherpt** [dotnet/docs#8419]
The sentence "Use the GetDescription method instead"
should be: "Use the GetGroupName method instead"
and the link it points to should be getgroupname:
https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.dataannotations.displayattribute.getgroupname?view=netframework-4.7.2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: caca46e0-f7e4-5e7f-853f-7bf6caede928
* Version Independent ID: b4e02d40-78f9-1900-8db6-19726d7b1af0
* Content: [DisplayAttribute.GroupName Property (System.ComponentModel.DataAnnotations)](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.dataannotations.displayattribute.groupname?view=netframework-4.7.2)
* Content Source: [xml/System.ComponentModel.DataAnnotations/DisplayAttribute.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.ComponentModel.DataAnnotations/DisplayAttribute.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thank you for your feedback @estherpt! I've opened a PR to fix this issue:
https://github.com/dotnet/dotnet-api-docs/pull/633
