### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by Jonas-Marty** [dotnet/docs#8423]
http://www.microsoft.com/typography/otspec/otff.htm is a dead link.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 521252b3-7520-e140-0bd7-a525a4d60301
* Version Independent ID: 9a14188c-0945-38d2-bf67-83f54e5717d7
* Content: [FontWeights Class (System.Windows)](https://docs.microsoft.com/en-us/dotnet/api/system.windows.fontweights?view=netframework-4.7.2)
* Content Source: [xml/System.Windows/FontWeights.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Windows/FontWeights.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thank you for your feedback @Jonas-Marty. A member of the community has already created a PR to address this.
