### ISSUE TITLE
Great Example

### ISSUE THREAD

**Issue by LaboMax** [dotnet/docs#8426]
It was very useful for me.
Thank you.
Massimo

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4c50ad3-42e0-aa9e-be7c-d16afa3369a6
* Version Independent ID: a8999211-e04e-9b68-6f4e-2a9845dc62aa
* Content: [DataGridViewComboBoxColumn Class (System.Windows.Forms)](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.datagridviewcomboboxcolumn?view=netframework-4.7.2)
* Content Source: [xml/System.Windows.Forms/DataGridViewComboBoxColumn.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Windows.Forms/DataGridViewComboBoxColumn.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
Thank you, @LaboMax. We're happy that you found it useful.
