### ISSUE TITLE
Missing guidelines for mono development

### ISSUE THREAD

**Issue by fleed** [dotnet/docs#8428]
Which runtime identifier should be selected to build applications that should run under `mono`?
Is only the platform important?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 009616d0-6c93-a2de-82fe-4f7168817f18
* Version Independent ID: 4c2c5549-0151-516d-91d0-9b017c74e787
* Content: [.NET Core Runtime IDentifier (RID) catalog](https://docs.microsoft.com/en-us/dotnet/core/rid-catalog)
* Content Source: [docs/core/rid-catalog.md](https://github.com/dotnet/docs/blob/master/docs/core/rid-catalog.md)
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment]
Correct, you should still target the OS/Architecture identified from the runtime identifier. Mono is an open source implementation of .NET Framework. So while you can install and run .NET Core on linux/mac/windows, you can also do that with Mono, but they are different. 

You can find more information about this scenario if you do a search on the internet about running .NET Core projects in Mono.

I'm going to close this issue as it's not something we'll call out in this article. Thanks though.
