### ISSUE TITLE
Feedback for Example: Return the Set Union of Two Sequences

### ISSUE THREAD

**Issue by Blackbaud-LoriWeiss** [dotnet/docs#8432]
You only show an example of the code, and do not show any examples of the data being used in the code and what it actually results to. This literally only shows syntax and no functionality. This is *useless*.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3807d861-6ece-e4a1-15dd-051563fe5d06
* Version Independent ID: 81401e00-1786-6a08-604b-cac5503ce9df
* Content: [Return the Set Union of Two Sequences](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/sql/linq/return-the-set-union-of-two-sequences)
* Content Source: [docs/framework/data/adonet/sql/linq/return-the-set-union-of-two-sequences.md](https://github.com/dotnet/docs/blob/master/docs/framework/data/adonet/sql/linq/return-the-set-union-of-two-sequences.md)
* Product: **dotnet-framework**
* GitHub Login: @douglaslMS
* Microsoft Alias: **douglasl**

**Comment by douglaslMS** [comment]
@Blackbaud-LoriWeiss I agree that the example should at least show the type of the return value, instead of using "var." Presumably the coder has a use case in mind, and knows how to move forward once he/she knows what's in the variable. There's such a variety of use cases for a UNION ALL, however, that a specific example would probably be useful only to a small percentage of readers.

**Comment by Blackbaud-LoriWeiss** [comment]
This [page](https://docs.microsoft.com/en-us/dotnet/api/system.linq.queryable.union?view=netframework-4.7.2) was very helpful. Perhaps this example page is not needed at all, since examples exist on the Union doc page itself.

**Comment by douglaslMS** [comment]
@Blackbaud-LoriWeiss Thanks for the info. Although this page already references the other page, I'm adding a sentence to call out explicitly that the other page provides more info and examples.
