### ISSUE TITLE
fsi.exe isn't there

### ISSUE THREAD

**Issue by MuziburRahman** [dotnet/docs#8439]
"c:\Program Files (x86)\Microsoft SDKs\F#&lt;version&gt;\Framework&lt;version&gt;" this path is not available in my pc. I*n the Microsoft SDKs folder, there's no folder named F#.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ea5b069-0d43-f577-3f95-fde5aaf919d5
* Version Independent ID: 0ea5685e-45cc-06d2-3985-cffb530f9e67
* Content: [F# Interactive (fsi.exe) Reference](https://docs.microsoft.com/en-us/dotnet/fsharp/tutorials/fsharp-interactive/)
* Content Source: [docs/fsharp/tutorials/fsharp-interactive/index.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/tutorials/fsharp-interactive/index.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by cartermp** [comment]
Thanks @MuziburRahman, this will need to get updated.
