### ISSUE TITLE
Document .NET Core pre-reqs

### ISSUE THREAD

**Issue by richlander** [dotnet/docs#844]
.NET Core pre-reqs should be documented. #843  does that.

The pre-reqs are not short and include workarounds in some cases. Very few people benefit from seeing macOS, Windows and Linux pre-reqs all together. It's a better experience to see this information in a file per OS. As a user, I prefer that over linking to an anchor.

**Comment by BillWagner** [comment]
The files for Windows were renamed and merged in #843   What remains are the following subtasks:

- [ ] Create the pre-reqs doc for the MacOS / OSX
- [ ] Create the pre-reqs doc for Linux. (Open Question: Do we need one per Linux distro?)
- [ ] Rationalize the Windows pre-reqs to make it easier for developers choosing either Visual Studio, or VS Code / CLI (or another editor). 

At this time, the Windows pre-reqs are a bit muddled between CLI / VS Code and the Visual Studio experience.

**Comment by blackdwarf** [comment]
@BillWagner you are using the workarounds in the known issues doc in dotnet/core repo?

**Comment by BillWagner** [comment]
@blackdwarf Currently, we only documented the one setup issue. We should do that going forward for all platforms.

**Comment by mairaw** [comment]
I saw the new topic yesterday and I was wondering if these pre-reqs docs should be under Getting Started.

**Comment by richlander** [comment]
Few things have changed since I created this issue:

* OpenSSL is only required for 1.x not 2.x. See: https://github.com/dotnet/announcements/issues/21.
* We've moved to a generic Linux distribution model, but dependencies are still distro-specific.
* We should focus on dependencies and less on IDE vs. CLI vs. text editor.

**Comment by mairaw** [comment]
@JRAlexander you moved this to done in the project. Should we close the issue too?
