### ISSUE TITLE
Indexed property documentation issues

### ISSUE THREAD

**Issue by kbattocchi** [dotnet/docs#8442]
1.  I don't think it's correct that `Ordinal` and `Cardinal` are special names in any way; as far as I can tell they are treated the same as any other name (except for `Item`, which is truly special)
2.  Furthermore, even when the name is `Item`, the declaration form described as "Indexed property that has get only." seems to result in the declaration of a method, not an indexed property.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b47d926c-72f6-0a8e-140d-7a31cd8e17d3
* Version Independent ID: 5d587fbe-7771-c826-7a72-75f69d61bc55
* Content: [Indexed Properties (F#)](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/members/indexed-properties)
* Content Source: [docs/fsharp/language-reference/members/indexed-properties.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/language-reference/members/indexed-properties.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by cartermp** [comment]
Yeah, this page was just off entirely.
