### ISSUE TITLE
Logical Error?

### ISSUE THREAD

**Issue by LisandroSu** [dotnet/docs#8444]
@yiwangwenrou commented on [Wed Oct 17 2018](https://github.com/dotnet/docs.zh-cn/issues/219)

DBBool TRUE = DBBool.True,NULL = DBBool.Null;    if(NULL && TRUE)  与 if(!(NULL && TRUE)   都为逻辑true

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: f818b111-bdeb-96a1-721a-1be183519f6d
* Version Independent ID: e98c5f3f-24d8-ae0e-d4b8-5607ce40f6b9
* Content: [false 运算符（C# 参考）](https://docs.microsoft.com/zh-cn/dotnet/csharp/language-reference/keywords/false-operator#see-also)
* Content Source: [docs/csharp/language-reference/keywords/false-operator.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/csharp/language-reference/keywords/false-operator.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

---

@imba-tjd commented on [Wed Oct 17 2018](https://github.com/dotnet/docs.zh-cn/issues/219#issuecomment-430613297)

I actually got `DBBool.Null`, both of them.
![default](https://user-images.githubusercontent.com/24759802/47075706-a5196180-d22f-11e8-981e-dde9ab6e266b.png)

**Comment by LisandroSu** [comment]
Hi team,

Please check this issue. Rough translation: _DBBool TRUE = DBBool.True, NULL = DBBool.Null; if(NULL && TRUE) and if(!(NULL && TRUE) are both logically true_

Thanks!

**Comment by mairaw** [comment]
@imba-tjd can you help us understand what @yiwangwenrou is asking here?

**Comment by mairaw** [comment]
Ah no worries. I assumed you understood because you answered his comment on the original repo 😄

**Comment by mairaw** [comment]
@yiwangwenrou can you please give us more information about what you were doing and expected results? Is there something wrong on the page?

#please-translation

/cc @JasonCard

**Comment by JasonCard** [comment]
@yiwangwenrou can you please give us more information about what you were doing and expected results? Is there something wrong on the page?

#please-translate

cc @DavidPrio

**Comment by DavidPrio** [comment]
@yiwangwenrou 您能否告诉我们您当时在进行什么操作以及当初预期的结果是什么？页面上出现了什么问题吗？

#请翻译

cc @JasonCard @mairaw

**Comment by imba-tjd** [comment]
它们的运算结果是DBBool而不是bool，那些运算符都重载过了。你给的例子的结果是DBBool.Null，对它取反还是DBBool.Null应该没什么问题吧

**Comment by yiwangwenrou** [comment]
感谢您们的回答，抱歉此时才回复您：
       具体代码如下：
            DBBool NULL = DBBool.Null;
            DBBool TRUE = DBBool.True;
            
            if ((NULL && TRUE))
                Debug.WriteLine("Is True");
            else
                Debug.WriteLine("Is False");

            if (!(NULL && TRUE))
                Debug.WriteLine("Is True");
            else
                Debug.WriteLine("Is False");
        }
两个if的判断条件为互反，但都将执行else分支（也就是说：输出两个  Is False），请问是我代码有问题吗？ 还是我的知识欠缺？又或者  该例属于未定义行为？

**Comment by imba-tjd** [comment]
@mairaw  It seems that overloading `true` and `false` operators makes `DBBool` be able to implicit convert to `bool`. This behavior is inconsistent with `bool?`.
Shall we remove them?

**Comment by CeciAc** [comment]
Hi team, any update on this?
@JasonCard @mairaw

**Comment by mairaw** [comment]
@BillWagner can you check this one?

**Comment by pkulikov** [comment]
@BillWagner given that there is the `bool?` type with predefined `|` and `&` operators:
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/nullable-types/using-nullable-types#the-bool-type

should those `DBBool` examples be removed? 

Moreover, the code snippet itself states:
```csharp
// For example purposes only. Use the built-in nullable bool 
// type (bool?) whenever possible.
public struct DBBool
```

I would rather come up with another example to demonstrate one of those scenarios:
>A type that overloads the `true` and `false` operators can be used for the controlling expression in `if`, `do`, `while`, and `for` statements and in conditional expressions.

If you agree, I'd be happy to submit a PR with revision of both the `true` and `false` operators articles.

**Comment by BillWagner** [comment]
There are several moving parts here.  Many of these came up while updating the C# standard to C# 5.  

@pkulikov A PR would be awesome.  I've added notes from the standards meetings to help guide the updates.

- [ ] Built in `bool?` is preferred to defining a different types.  The spec isn't clear what is supposed to happen when a short-circuit operator `&&` or `||` is used with an expression of a nullable user-defined type. It is explicit about `Nullable<bool>` and the `bool?`. 
- [ ] We should use a better example for `operator false`, `operator true`. This was discussed in the standards meetings:

> Using `not false` and `not true` to short-circuit `&&` and `||` correctly support user defined implementations of & and |. The language does not allow user defined operators for && and ||. They are composed using operator true, operator false, and & and |.

> Consider this user defined type:

>I have a struct that defines launch / abort conditions:

>Red => No launch.
>Yellow => if only one sub-system is yellow, we can launch.
>Green => OK for launch.
>I want to write:

>bool okToLaunch = Fuel.LaunchStatus && Navigation.LaunchStatus;

>When Fuel.LaunchStatus is Green, okToLaunch should be true if Navigation.LaunchStatus is either Green or Yellow.

>When Fuel.LaunchStatus is Red, okToLaunch should be false, and there is no reason to evaluate Navigation.LaunchStatus.

>The interesting case for this discussion is when Fuel.LaunchStatus is Yellow. Navigation.LaunchStatus must be evaluated, and if it is Green, then okToLaunch should be true.

>To achieve this, operator & would need to be defined this way:

>Red & Red => Red
>Red & Yellow => Red
>Red & Green => Red
>Yellow & Red => Red
>Yellow & Yellow => Red (so that operator false returns 'true')
>Yellow & Green => Green (so that operator true returns 'true')
>Green & Red => Red
>Green & Yellow => Green
>Green & Green => Green

This became the following note in the C# 5 standard:

> note: The reason that short circuiting uses the 'not true' and 'not false' conditions is to enable user defined conditional operators to define when short circuiting applies. User defined types could be in a state where operator true returns false and operator false returns false. In those cases, neither && or || would short circuit.

Does that provide all the notes you'd need for updates @pkulikov ?

**Comment by pkulikov** [comment]
@BillWagner please check my understanding that follows.

First, it looks that still both the `true` and `false` operator articles should contain a note that recommends using the built-in `bool?` type instead of implementing user-defined database Boolean type (even though `DBBool` example would be gone).

Second, while both `true` and `false` operators must be defined together on a user-defined type, there might be instances of the type that result in `false` Boolean value for both `true` and `false` operators. So, those two operators do not complement each other. I think that is something to mention as well.

Third, according to the [spec](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/expressions#user-defined-conditional-logical-operators), the `&&` operator short-circuits based on the result of the `false` operator, while the `||` operator - the `true` operator. I'm not sure if it should be in the article; maybe the link to the spec would be enough.

At last, thanks for the example. May I use it as the example in the article?

With that understanding, I'll make a PR where we'll discuss any further details.

**Comment by BillWagner** [comment]
@pkulikov Thanks for taking this on!  Answers follow:

> First, it looks that still both the true and false operator articles should contain a note that recommends using the built-in bool? type instead of implementing user-defined database Boolean type (even though DBBool example would be gone).

Yes, that's the recommendation. Use `bool?` when you can.

> Second, while both true and false operators must be defined together on a user-defined type, there might be instances of the type that result in false Boolean value for both true and false operators. So, those two operators do not complement each other. I think that is something to mention as well.

Yes. Although I'd use weasel words: "The `true` and `false` operators are not guaranteed to complement each other."

> Third, according to the spec, the && operator short-circuits based on the result of the false operator, while the || operator - the true operator. I'm not sure if it should be in the article; maybe the link to the spec would be enough.

I think the important for this article is that the most common reason to implement `operator true` or `operator false` is to achieve the desired short-circuiting behavior. For more details, see the spec.

> At last, thanks for the example. May I use it as the example in the article?

Yes! That's why I posted it. 😀

**Comment by CeciAc** [comment]
Hi team, 
If this was solved can you #pleaseClose this ticket?
@BillWagner

**Comment by pkulikov** [comment]
@BillWagner I'm planning to submit a PR discussed above in coming two weeks.
