### ISSUE TITLE
TLS 1.3 is now latest standard

### ISSUE THREAD

**Issue by jricha34** [dotnet/docs#8454]
Should correct that TLS 1.3 is now the newest released standard. 

https://datatracker.ietf.org/doc/rfc8446/

Any idea when MSFT products will start supporting it in their products including AD/ADLDS, etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7341fa0a-f474-6c2d-d3c0-7e2df12fbb65
* Version Independent ID: e99c489a-7518-d293-ad93-7eaca8b7191a
* Content: [Transport Layer Security (TLS) best practices with the .NET Framework](https://docs.microsoft.com/en-us/dotnet/framework/network-programming/tls)
* Content Source: [docs/framework/network-programming/tls.md](https://github.com/dotnet/docs/blob/master/docs/framework/network-programming/tls.md)
* Product: **dotnet-framework**
* GitHub Login: @blowdart
* Microsoft Alias: **dotnetcontent**

**Comment by blowdart** [comment]
True, @mairaw can we change initial paragraph to something like.

_The Transport Layer Security (TLS) protocol is an industry standard designed to help protect the privacy of information communicated over the Internet. TLS 1.2 is the now the widely accepted security standard, with TLS 1.3 being ratified in Octore 2018. This article presents recommendations to secure .NET Framework applications that use the TLS protocol by moving from TLS 1.0 and 1.1 to use TLS 1.2._

This document, and github wouldn't be the place to comment on future product planning.

**Comment by karelz** [comment]
@dagolinuxoid put up PR #8538, thanks!
