### ISSUE TITLE
Guidance on whether to indicate CLS compliance

### ISSUE THREAD

**Issue by Eilon** [dotnet/docs#8455]
Can/should we have guidance on whether to indicate CLS compliance? It comes up from customers/community every so often, but in my view the cases for it tend to be weak because they are based on hypothetical cases, or circular logic.

For example:
1. What if some obscure language is used?
  * I think it'll probably work just fine anyway, as long as you're not actually doing anything that isn't CLS complient
2. But I want to mark my own assembly as CLS compliant and I can't because it depends on XYZ, which isn't
  * This goes back to (1) and whether there's any point to it at all these days in modern libraries

I think it would be good to have explicit guidance on this that we can point people to.

cc @KathleenDollard @richlander @terrajobst @DamianEdwards 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e80fe2fd-cbdb-699e-0dbb-a0a310bd372c
* Version Independent ID: 266d08ae-344a-683b-11e2-143b704e21a8
* Content: [Open-source library guidance](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/)
* Content Source: [docs/standard/library-guidance/index.md](https://github.com/dotnet/docs/blob/master/docs/standard/library-guidance/index.md)
* Product: **dotnet**
* GitHub Login: @JamesNK
* Microsoft Alias: **mairaw**

**Comment by JamesNK** [comment]
Agreed. Right now the guidance focuses on higher level topics like cross-platform and packaging. There is an opportunity to have one or more articles on the API design. For example:
* Discussing CLS
* Recommending [Framework Design Guidelines](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/)
* Highlight recommended extension points for logging, configuration, ASP.NET, Azure, etc
* Providing testable libraries

**Comment by mairaw** [comment]
@JamesNK should this be moved to our backlog?
