### ISSUE TITLE
Add a tutorial/example using the MNIST dataset 

### ISSUE THREAD

**Issue by rvberloo** [dotnet/docs#8460]
I think the MNIST dataset would be a nice candidate for a new Tutorial for ML.NET
I would mainly be interested to see how a dateset with hundreds of columns gets modeled, do we need to make a hardcoded class property for each column?

**Comment by JRAlexander** [comment]
cc: @GalOshri, @asthana86

**Comment by GalOshri** [comment]
Agreed that's a good tutorial to have.

Regarding reading many columns, an example with the new APIs can be found [here](https://github.com/dotnet/machinelearning/blob/9157ceacffe0106c01580d6b7aa79ce918048434/docs/code/MlNetCookBook.md#how-do-i-load-data-with-many-columns-from-a-csv). An example with the older APIs can be found [here](https://github.com/dotnet/machinelearning/issues/420).

**Comment by JRAlexander** [comment]
Hey @rvberloo! There is an MNIST sample here:  https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/getting-started/MulticlassClassification_MNIST

**Comment by JRAlexander** [comment]
Closing as I think this is resolved.  Please reopen or comment if that is not the case. Thanks!
