### ISSUE TITLE
Unsuitable examples chosen

### ISSUE THREAD

**Issue by BrunoJuchli** [dotnet/docs#8464]
In [Handle common conditions without throwing exceptions](https://docs.microsoft.com/en-us/dotnet/standard/exceptions/best-practices-for-exceptions#handle-common-conditions-without-throwing-exceptions) an unfitting example was chosen:

Connections usually involve a local and a remote endpoint, Often either can close it - concurrently. If that is the case, checking state before performing the operation becomes a performance optimization (and thus, in most cases, superfluous code).
(Note: if the connection allows concurrent internal state modification then an external state check is not reliable - the state might change between the check and the execution. Catching the exception then also is expected to happen as soon as that race condition occurs and does not signify a problem. )

The problem here, too, is, that if this connection really does throw an InvalidOperationException we don't have a way to distinguish this from an InvalidOperationException that has a truly exceptional cause. Thus, if anything, it should throw a SocketClosedException. We can catch this one and safely say: oh, i wanted to close this, but it's already closed.. so we just swallow it. No need to even log it.

Now, I postulate, that once we've reached this point we could just as well have .Close be silent. We don't need to know that we can't close the connection because it's already closed. That's entirely fine.

By the way, this is also a requirement for implementations of IDisposable.Dispose. Multiple invocations should not lead to exceptions.

Henceforth I'd suggest:

- use a more appropriate type for the example (like IDictionary["foo"] and IDictionary.ContainsKey("foo")).

-- of course show-case the exception-less example of TryGet

-- might be worthwile to also add a sample for `IDictionary&lt;TKey, TValue&gt;GetOrAdd(TKey, Func&lt;TKey, TValue&gt; valueCreator)`, as this is quite a common pattern to ensure that an operation succeeds. However, might also be judged be too localized to be worth mentioning here.

--- this example could also be used to take it one step further and show that it's not sensible to have Dictionary catch an exception thrown by `Func&lt;TKey, TValue&gt; valueCreator`.

- keep a connection example and explain while in this case throwing an exception is bad.

-- at the same time, state that most methods (like Send, Receive...) still need to follow the pattern of either throwing exception or being a TryXYZ method.

Of course I haven't even started to describe how you should handle success and failure cases in F#... ;-)

------------

Also, the `TransferFunds` example doesn't seem so great. If we have the concept of transactions then surely we should have a transaction spanning both, withdrawal and deposit!
And as soon as we introduce transactions, we should have the concept of:

-Transactions are only committed if there is *no* exception. We should never rely on a `catch` handler for rollback. Because that's way less safe. `OutOfMemoryException`?

Hence a pattern should more look like:

    using (ITransaction transaction = db.StartTransaction())
    {
        from.Withdrawal(amount)
        to.Deposit(amount)
        transaction.Commit();
    }

(ignoring the probable need for an `IDisposable` implementation on `ITransaction` we could remove the `using` directive).

No need to handle any exceptions, at all.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1ea31f6-516f-100d-046e-1a0445d92824
* Version Independent ID: a713e8c9-8210-761d-9ae7-238793825ff3
* Content: [Best Practices for Exceptions](https://docs.microsoft.com/en-us/dotnet/standard/exceptions/best-practices-for-exceptions#lf-content=191034115:765277250)
* Content Source: [docs/standard/exceptions/best-practices-for-exceptions.md](https://github.com/dotnet/docs/blob/master/docs/standard/exceptions/best-practices-for-exceptions.md)
* Product: **dotnet**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by tdykstra** [comment]
@BrunoJuchli Thanks for the suggestions. The article's intention is to illustrate some general principles and it doesn't go into the level of detail you're proposing. We're closing the issue for now, but if you'd like to submit a pull request that addresses these issues while still clearly presenting the same general guidelines, you're welcome to reopen the issue.
