### ISSUE TITLE
Double comma in lists

### ISSUE THREAD

**Issue by snowpardx** [dotnet/docs#8465]
Hi, seems there is something with page creation in lists (like supported .net core version, .netframework and so on) we have two commas instead of one. Please consider to have a look into.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c28aef58-53cb-67ba-b806-04ec0c513d55
* Version Independent ID: 125bdaad-99da-b8d9-3184-4b92afadc637
* Content: [ReflectionTypeLoadException.Types Property (System.Reflection)](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.reflectiontypeloadexception.types?view=netframework-4.7.2#feedback)
* Content Source: [xml/System.Reflection/ReflectionTypeLoadException.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Reflection/ReflectionTypeLoadException.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by pkulikov** [comment]
@snowpardx thanks for the note!
However it's duplicate of MicrosoftDocs/feedback#773

**Comment by snowpardx** [comment]
@pkulikov got it, thanks. Let me close the one in that case.
