### ISSUE TITLE
Authenticode signing

### ISSUE THREAD

**Issue by jherby2k** [dotnet/docs#8472]
Should we authenticode sign open source assemblies? Many enterprises want all their code signed if they are doing application whitelisting. There are several challenges for open source projects. Particularly, what to do with the private key.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e80fe2fd-cbdb-699e-0dbb-a0a310bd372c
* Version Independent ID: 266d08ae-344a-683b-11e2-143b704e21a8
* Content: [Open-source library guidance](https://docs.microsoft.com/en-ca/dotnet/standard/library-guidance/)
* Content Source: [docs/standard/library-guidance/index.md](https://github.com/dotnet/docs/blob/master/docs/standard/library-guidance/index.md)
* Product: **dotnet**
* GitHub Login: @JamesNK
* Microsoft Alias: **mairaw**

**Comment by tdykstra** [comment]
@Jamesnk Is this a topic we should cover in the OS library guidance doc?

**Comment by JamesNK** [comment]
Sure. It and NuGet package signing
