### ISSUE TITLE
Multiple OS targeting 

### ISSUE THREAD

**Issue by jherby2k** [dotnet/docs#8473]
My project has different compilation paths for Linux, Windows and OSX. What’s the best way to package these together in a single nuget, avoiding custom build scripts and nuspec files if possible?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e80fe2fd-cbdb-699e-0dbb-a0a310bd372c
* Version Independent ID: 266d08ae-344a-683b-11e2-143b704e21a8
* Content: [Open-source library guidance](https://docs.microsoft.com/en-ca/dotnet/standard/library-guidance/)
* Content Source: [docs/standard/library-guidance/index.md](https://github.com/dotnet/docs/blob/master/docs/standard/library-guidance/index.md)
* Product: **dotnet**
* GitHub Login: @JamesNK
* Microsoft Alias: **mairaw**

**Comment by Mizux** [comment]
@jherby2k why don't using a multiple nuget runtime package approach (e.g. `runtime.linux-x64.Company.Project.nupkg`, `runtime.osx-x64.Company.Project`) **and** with a meta nuget package (e.g. `Company.Project`)

see https://github.com/google/or-tools/tree/master/ortools/dotnet for working examples

**Comment by Mizux** [comment]
You may be interested by https://github.com/Mizux/dotnet-native
