### ISSUE TITLE
Broken Link in See Also Section

### ISSUE THREAD

**Issue by amaldevv** [dotnet/docs#8490]
In the See Also section, there is some formatting issue which is causing the hyperlink  to show as plain text

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 028dd37e-f540-1b9f-a74c-0e0cb94102b3
* Version Independent ID: 96998139-7136-8b7c-41ea-621bdd1b6ec5
* Content: [&lt;compiler&gt; Element](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/compiler/compiler-element)
* Content Source: [docs/framework/configure-apps/file-schema/compiler/compiler-element.md](https://github.com/dotnet/docs/blob/master/docs/framework/configure-apps/file-schema/compiler/compiler-element.md)
* Product: **dotnet-framework**
* GitHub Login: @mcleblanc
* Microsoft Alias: **markl**

**Comment by Niladri24dutta** [comment]
@amaldevv fixed with PR #8492
