### ISSUE TITLE
static async Task Main(string[] args)    return error cs5001

### ISSUE THREAD

**Issue by elizad** [dotnet/docs#8497]
Error	CS5001	Program does not contain a static 'Main' method suitable for an entry point	

   ```
//class Program
    //{
    //    static async Task Main(string[] args)
    //    {
    //        await Task.Delay(2000);
    //       return await DoAsyncWork();


    //    }
    //}
```

**Comment by pkulikov** [comment]
@elizad this page might be helpful:
https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs5001

**Comment by BillWagner** [comment]
See dotnet/roslyn#26326 which should fix this.

**Comment by tdykstra** [comment]
@elizad Did https://github.com/dotnet/roslyn/issues/26326 provide the solution?
