### ISSUE TITLE
Installing .NET Framework

### ISSUE THREAD

**Issue by venividi2** [dotnet/docs#8499]
All very nice but how do I find "Windows features" on a computer that speaks Italian? What is the translation?
Besides this, the I overlooked filling the window above about and it took me some time to understand that it was "Title" as it was hidden by a dark red colour thatg manuy people do not perceive

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea654e23-2ec5-637e-99c3-8870b895030c
* Version Independent ID: 9c054590-c5e3-199c-b852-e1a856b4aae7
* Content: [Install the .NET Framework 3.5 on Windows 10, Windows 8.1, and Windows 8](https://docs.microsoft.com/en-gb/dotnet/framework/install/dotnet-35-windows-10)
* Content Source: [docs/framework/install/dotnet-35-windows-10.md](https://github.com/dotnet/docs/blob/master/docs/framework/install/dotnet-35-windows-10.md)
* Product: **dotnet-framework**
* GitHub Login: @rlander
* Microsoft Alias: **mairaw**

**Comment by venividi2** [comment]
Thank you very very much
Regards

Valeria Vernon a.k.a. venividi





----- Messaggio originale -----
Da: Peter Toonen <notifications@github.com>
Rispondi a: dotnet/docs 
<reply@reply.github.com>
A: dotnet/docs <docs@noreply.github.com>
Cc: venividi2 <info@vernondata.it>, Mention <mention@noreply.github.com>
Inviato: 29/10/2018 14:26:32
Oggetto: Re: [dotnet/docs] Installing .NET Framework (#8499)



@venividi2 This is a problem with a lot of options in Windows. What I usually 
do when 
I'm on a different language version is windows key + r and then enter 'appwiz.cpl'. This guides me to the right place (it's 
the option that requires UAC).

**Comment by mairaw** [comment]
It seems your issue was resolved. There's also the Italian version of the topic that might help you:
https://docs.microsoft.com/it-it/dotnet/framework/install/dotnet-35-windows-10

**Comment by venividi2** [comment]
Thank you Mairaw, Yes I solved giving up installing the application I wanted to instal. Very simple solution that can be summed up with "cutting off the bull's head". However I wonder if there is a Microsoft site adressing these translation options for anyone around the world. II don't think it is difficult to organize
