### ISSUE TITLE
No description of how to write a <see> with generics, but <seealso> linked here promising one :-(

### ISSUE THREAD

**Issue by chrisfcarroll** [dotnet/docs#8505]
No description of how to write a &lt;see&gt; with generics, but &lt;seealso&gt; linked here promising one :-(

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 337464b6-c9f4-87ee-f774-5f4509c3830e
* Version Independent ID: 9626e965-109d-5e3c-eb42-ef8fbccf2fb4
* Content: [&lt;seealso&gt; (C# Programming Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/seealso)
* Content Source: [docs/csharp/programming-guide/xmldoc/seealso.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/xmldoc/seealso.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by peteraritchie** [comment]
This seems like it should be closed, based on https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/seealso
