### ISSUE TITLE
Error in Code Example

### ISSUE THREAD

**Issue by nbahmanyar** [dotnet/docs#8509]
In the Callback Example on this page, there is a missing quotation mark in this line:
        wait...");  

It should be "wait

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 802d87ab-5dfc-5a15-b2e7-8192fb4e82b5
* Version Independent ID: c0f9046a-9e10-b564-c81d-99b3fed7bcae
* Content: [Windows Applications Using Callbacks](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/sql/windows-applications-using-callbacks#feedback)
* Content Source: [docs/framework/data/adonet/sql/windows-applications-using-callbacks.md](https://github.com/dotnet/docs/blob/master/docs/framework/data/adonet/sql/windows-applications-using-callbacks.md)
* Product: **dotnet-framework**
* GitHub Login: @douglaslMS
* Microsoft Alias: **douglasl**

**Comment by dagolinuxoid** [comment]
@initram I'm wondering why did you make your own commit on the issue even though mikkelbu made it already (so it's just waiting to be reviewed)?

**Comment by initram** [comment]
@dagolinuxoid that was a mistake. I did not see that there was already a pull request open for this issue. I will close my pull request. Sorry for wasting your time.

**Comment by dagolinuxoid** [comment]
I got it. No worries :)
