### ISSUE TITLE
VB.net

### ISSUE THREAD

**Issue by HeraldOfOmega** [dotnet/docs#8519]
Can you do this in VB.net?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e45eceaa-9d7f-67b5-1d92-58776c2e137d
* Version Independent ID: ff90e4c3-d9ad-5f91-c3b8-851b6b577649
* Content: [File.Exists(String) Method (System.IO)](https://docs.microsoft.com/en-us/dotnet/api/system.io.file.exists?view=netframework-4.7.2#remarks)
* Content Source: [xml/System.IO/File.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.IO/File.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Yes @HeraldOfOmega. You can switch the language on top to VB.NET:
![image](https://user-images.githubusercontent.com/12971179/47321188-c8b22280-d608-11e8-9248-1567cc1f4685.png)
