### ISSUE TITLE
Encoding issue

### ISSUE THREAD

**Issue by anvish** [dotnet/docs#8520]
Text "(?(1)&#124;\s?\p{Sc})?" contains encoded character instead of character itself

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ab2ffb4-6f22-c12c-6e3f-969b515fcf61
* Version Independent ID: 16e735bf-9c96-3a28-ab98-b0cf74c38a97
* Content: [Regex.Replace Method (System.Text.RegularExpressions)](https://docs.microsoft.com/en-us/dotnet/api/system.text.regularexpressions.regex.replace?view=netframework-4.7.2#System_Text_RegularExpressions_Regex_Replace_System_String_System_String_)
* Content Source: [xml/System.Text.RegularExpressions/Regex.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Text.RegularExpressions/Regex.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mikkelbu** [comment]
Note that `&#124;` appears twice in the source and both places the result is wrong. I wonder whether this is related to #8034?

**Comment by imba-tjd** [comment]
I fixed them once. This is because \| is superior to \` in markdown tables. You can use \<code> instead.
