### ISSUE TITLE
reader view unavailable

### ISSUE THREAD

**Issue by tabareh** [dotnet/docs#8521]
How come the reader view is not available for this page on surface 2012 but its available on apple devices?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e1a443c-c3dd-b865-58b2-0ff0902308ce
* Version Independent ID: d974261f-2544-dee9-f401-e02d715012cb
* Content: [Work with data in ASP.NET Core Apps](https://docs.microsoft.com/en-us/dotnet/architecture/modern-web-apps-azure/work-with-data-in-asp-net-core-apps)
* Content Source: [docs/architecture/modern-web-apps-azure/work-with-data-in-asp-net-core-apps.md](https://github.com/dotnet/docs/blob/master/docs/architecture/modern-web-apps-azure/work-with-data-in-asp-net-core-apps.md)
* Product: **dotnet**
* Technology: **dotnet-ebooks**
* GitHub Login: @ardalis
* Microsoft Alias: **wiwagn**

**Comment by sergiogomes** [comment]
Hi there!
In this last Cache example, "public class CachedCatalogService : ICatalogService", I didn't understand how to connect it to a SQL query. Is there an example where we use the set method with absoluteExpirationRelativeToNow?
Thanks

**Comment by quocdai92** [comment]
I think the cache method is cache your data to web server (memory cache), not SQL. So instead of request to SQL, your http request will access to memory cache to get data.

**Comment by mairaw** [comment]
Apologies for the delay here @tabareh. I believe this can be closed now? Unless I'm misunderstanding the request.

**Comment by tabareh** [comment]
Yes, I don't use the old surface tablet anyways and if you think it's solved then please go ahead and close it.
