### ISSUE TITLE
What is Windows in the .NET implementation support matrix

### ISSUE THREAD

**Issue by hannni** [dotnet/docs#8527]
Is that about WinRT (Windows Runtime) support in Windows 8(.1)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9eb8b774-c6f0-8235-6964-15219baf2ea7
* Version Independent ID: 6819a4a7-7527-d8c7-e132-767f7344e00e
* Content: [.NET Standard](https://docs.microsoft.com/en-us/dotnet/standard/net-standard)
* Content Source: [docs/standard/net-standard.md](https://github.com/dotnet/docs/blob/master/docs/standard/net-standard.md)
* Product: **dotnet**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
@terrajobst @weshaggard can you help clarify this?

**Comment by terrajobst** [comment]
@hannni, could you quote the particular section that you’re referring to?

**Comment by svick** [comment]
@terrajobst I think it refers to the "Windows" row in the table:

![](https://user-images.githubusercontent.com/287848/47363145-590a6900-d6d6-11e8-960a-4118963eb92c.png)

**Comment by hannni** [comment]
@terrajobst exactly the line that @svick referenced

**Comment by terrajobst** [comment]
This was the precursor to UWP. Over the years there were several names for that experience (.NET for Metro-style Apps, which became just "Windows" in 8.1. when Phone and UWP were converging). Given that it's effectively done I wonder whether we can gray them out or even remove them entirely.

@mairaw, can we use some inline HTML to gray out rows?

**Comment by mairaw** [comment]
I missed your question earlier @terrajobst. Only if we used HTML instead of Markdown, which is not recommended but doable if really necessary. What do you prefer? Gray out or remove?

**Comment by terrajobst** [comment]
Good question. I'll ping a few folks.
