### ISSUE TITLE
Outdated Remarks text

### ISSUE THREAD

**Issue by AderitoSilva** [dotnet/docs#8537]
Its nothing really important, its just to let you know about it... On the **Remarks** section there is the text "as shown in the example **later in this topic**". The text mentions an example that is now shown before the **Remarks** section, so the expression that says "**later** in this topic" could be changed to be more accurate with the new Docs platform.

Thank you very much and keep up the good work!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5dd83b5-9450-8c1b-19c6-3b444309feae
* Version Independent ID: 0fe343a1-432c-ee42-f08e-afea34734214
* Content: [RsaProtectedConfigurationProvider Class (System.Configuration)](https://docs.microsoft.com/en-us/dotnet/api/system.configuration.rsaprotectedconfigurationprovider?view=netframework-4.7.2)
* Content Source: [xml/System.Configuration/RsaProtectedConfigurationProvider.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Configuration/RsaProtectedConfigurationProvider.xml)
* Product: **dotnet-api**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by mairaw** [comment]
Every detail matters @AderitoSilva! Obrigada! And thanks @Chris-Johnston for jumping on the issue.
