### ISSUE TITLE
This is a lot of boilerplate code to do something very basic

### ISSUE THREAD

**Issue by pengowray** [dotnet/docs#8540]
I'm incredibly excited that Microsoft has embraced Docker + Linux and the whole open source ethos with .NET Core, but the amount of boilerplate code to copy, modify and maintain just run a basic command line app in Docker with an argument (as shown here and in the sample application) is enough to make even Java look positively laconic by comparison. I beg you to please look at finding ways to simplify this all in future.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8136668-5c80-9640-ed08-bdda6418fa19
* Version Independent ID: e07d8d3c-7566-9652-892d-e6cc711078d8
* Content: [Running Console applications in Docker](https://docs.microsoft.com/en-us/dotnet/framework/docker/console)
* Content Source: [docs/framework/docker/console.md](https://github.com/dotnet/docs/blob/master/docs/framework/docker/console.md)
* Product: **dotnet-framework**
* GitHub Login: @spboyer
* Microsoft Alias: **dotnetcontent**

**Comment by spboyer** [comment]
@quole - Perhaps the title of this document does not represent the scenario?  The doc here covers a number of things.

- Windows Containers
- Migration of a console application 
- Using Powershell to complete all the tasks

There could be an additional doc for a simple "HelloWorld" console application, here we are trying to cover a balance between that and perhaps a more realistic scenario.

Thanks for the issue.
