### ISSUE TITLE
System.setting

### ISSUE THREAD

**Issue by 1Manzaidm** [dotnet/docs#8546]
Sopport gagalxyj600gh data setting versi:9.0.1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed8df2ab-b8b5-c743-76d3-3ecf9ed501fa
* Version Independent ID: 66515ce3-9a6a-0032-ab95-9b4a351a4fb1
* Content: [Configuration Class (System.Configuration)](https://docs.microsoft.com/en-us/dotnet/api/system.configuration.configuration?view=netframework-4.7.2)
* Content Source: [xml/System.Configuration/Configuration.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Configuration/Configuration.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **riande**

**Comment by mairaw** [comment]
It's not clear what you meant by this feedback @1Manzaidm so I'm closing it. Let us know if you have additional information you can provide to us.
