### ISSUE TITLE
Method doesn't exist

### ISSUE THREAD

**Issue by tdworshak** [dotnet/docs#8547]
The Clear() method does not actually exist on the ConcurrentBag class.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5be83e8-3895-6556-9cc9-d894db33aba9
* Version Independent ID: 4f506e89-d1ce-2b1a-697e-123fc044e70f
* Content: [ConcurrentBag&lt;T&gt;.Clear Method (System.Collections.Concurrent)](https://docs.microsoft.com/en-us/dotnet/api/system.collections.concurrent.concurrentbag-1.clear?view=netcore-2.1&viewFallbackFrom=netframework-4.7.2)
* Content Source: [xml/System.Collections.Concurrent/ConcurrentBag`1.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Collections.Concurrent/ConcurrentBag`1.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mikkelbu** [comment]
@tdworshak Note that this is documentation is for .NET Core 2.1. It is correct that the method does not exists in .NET Framework, but it does for .NET Core 2.0 and forward. The method was added here https://github.com/dotnet/corefx/issues/2338

**Comment by mairaw** [comment]
I hope @mikkelbu's answer helps you clarify what's going on so I'm closing this.
