### ISSUE TITLE
docker-compose.ci.build.yml is no longer in the repo

### ISSUE THREAD

**Issue by AFallad** [dotnet/docs#8552]
docker-compose.ci.build.yml was deleted on with commit c38d576e86598e5bbb17c3e39137848919f4f866, however this chapter still has examples that require it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 965c8ae7-7e10-fa78-8797-6df625d020d8
* Version Independent ID: d4570cd2-f4f9-4d5e-8361-774a6d4027e9
* Content: [Defining your multi-container application with docker-compose.yml](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/multi-container-microservice-net-applications/multi-container-applications-docker-compose)
* Content Source: [docs/architecture/microservices/multi-container-microservice-net-applications/multi-container-applications-docker-compose.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/multi-container-microservice-net-applications/multi-container-applications-docker-compose.md)
* Product: **dotnet**
* Technology: **dotnet-ebooks**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by mvelosop** [comment]
There are no references (at least couldn't find them) to the docker-compose.ci.build.yml file. I remember there was a reference in an image, but it was updated in the last large review.

Closing this issue now, but feel free to comment, will reopen if needed.
