### ISSUE TITLE
Example is not useful, other issues

### ISSUE THREAD

**Issue by miss-programgamer** [dotnet/docs#8558]
The provided example does not show how to use the event. It doesn't even have code in it besides the signature for the method. I'd go as far as saying it taunts anyone reading the article with the (very useless) comment that reads "Omitted Code: Insert code that does something whenever the text changes..."

A more useful example would be one that shows how to filter a character that gets added and check if it's valid or not, or one that checks if a user can remove a character at a given position.

It's also unclear from this page if the contents of the textbox changes before or after the event is fired.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 610aef48-e9cc-f0c1-58b5-a2e287d637fe
* Version Independent ID: be00f2a2-7d18-7d61-b23c-864e1752d635
* Content: [How to: Detect When Text in a TextBox Has Changed](https://docs.microsoft.com/en-us/dotnet/framework/wpf/controls/how-to-detect-when-text-in-a-textbox-has-changed?view=netframework-4.7.2)
* Content Source: [docs/framework/wpf/controls/how-to-detect-when-text-in-a-textbox-has-changed.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/controls/how-to-detect-when-text-in-a-textbox-has-changed.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mati23** [comment]
I agree.  There is a good explanation  about the topic but no good examples of how to use it.
