### ISSUE TITLE
Image was broken on System.Windows.Media.Visual.

### ISSUE THREAD

**Issue by HirotoHirata** [dotnet/docs#8564]
msdn documents is no problem, but this image's texts deleted when migration to docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c08cf280-bb74-6eab-3475-b42508967afc
* Version Independent ID: 2dfcc4dd-6241-84d6-994a-413a54a259ff
* Content: [WPF Architecture](https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/wpf-architecture#feedback)
* Content Source: [docs/framework/wpf/advanced/wpf-architecture.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/advanced/wpf-architecture.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
@HirotoHirata I'm looking at an internal copy we have from MSDN and it looks exactly the same. For this reason, I'm closing this issue.
