### ISSUE TITLE
finally

### ISSUE THREAD

**Issue by Babster** [dotnet/docs#8565]
I can't understand what is the difference in the program behavior between finally block and just code without it. Isn't the code below the same as written with the finally block?
        try
        {
            // Invalid conversion; obj contains a string, not a numeric type.
            i = (int)obj;

            // The following statement is not run.
            Console.WriteLine("WriteLine at the end of the try block.");
        }
            // Report that the finally block is run, and show that the value of
            // i has not been changed.
            Console.WriteLine("\nIn the finally block in TryCast, i = {0}.\n", i);

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cd59701-079e-fdda-0c47-290f24f9eb4e
* Version Independent ID: a6f2953b-0da7-19fd-e121-aaeb65f60b17
* Content: [try-finally (C# Reference)](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/try-finally)
* Content Source: [docs/csharp/language-reference/keywords/try-finally.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/try-finally.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
The code in the finally block is executed even when an exception is thrown in the `try` block associated with the `finally` block.

Any code in the `try` block that follows the statement that throws the exception is not executed.
