### ISSUE TITLE
Inconsistency in behaviour

### ISSUE THREAD

**Issue by kaimikael** [dotnet/docs#8574]
I am using Visual Studio for Mac Community 7.6.9, which behaves somewhat differently.  Right-clicking on a project name brings up a menu which contains an ”Options” option.  Alternatively one may select from the Project menu ”&lt;project name&gt; Options”.  In the popup window that opens, one can navigate to Build/Compiler which has a checkbox for “Generate xml documentation”.  This does not however seem to make any difference to the generation of an XML file.
Using -doc:file.xml from the command line does work as expected.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99ceb5f1-d81a-ca44-6234-4b725e356328
* Version Independent ID: 2cd58b31-4d66-1b99-14a9-beb1d8de2c35
* Content: [-doc (C# Compiler Options)](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/doc-compiler-option)
* Content Source: [docs/csharp/language-reference/compiler-options/doc-compiler-option.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/doc-compiler-option.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by tdykstra** [comment]
I tried this in VS for Mac 8.8 and the checkbox for “Generate xml documentation” does generate an XML file. I'll add VS Mac instructions to the doc.
