### ISSUE TITLE
Add .NET Framework Installation docs

### ISSUE THREAD

**Issue by richlander** [dotnet/docs#858]
There are several docs that I wrote that are part of the .NET Framework deployment experience. Customers see the following dialog. 

![image](https://cloud.githubusercontent.com/assets/2608468/17344385/b45507d4-58b6-11e6-84f3-6e22c4b21a5f.png)

They are taken to a page (in their browser) when they press "Yes". The target page is variable, dependent on the .NET Framework version they need and the Windows version they have. The following pages are all possible targets. They should be added to this repo, the first part of the .NET Framework guide, I guess. Once there are moved here, I'll redirect the traffic to these docs.

Docs in current use:
- http://getdotnet.azurewebsites.net/help/dotnet4-xp.html
- http://getdotnet.azurewebsites.net/help/dotnet45-xp.html
- http://getdotnet.azurewebsites.net/help/install_dotnet_control_panel.html
- http://getdotnet.azurewebsites.net/help/dotnet-framework-initialization-error.html
- http://support.microsoft.com/kb/2715633

The docs are here: https://github.com/Microsoft/getdotnet/tree/master/help.

In terms of form, I'd prefer to keep the pages as single units. It's a better experience (IMO) to get directed to a page that solely explains your situation. The readers are all consumers (with the exception of the second last one) so we want to make it very simple and intuitive.

These pages are similar in nature to:
- https://support.microsoft.com/en-us/kb/2785188
- https://msdn.microsoft.com/library/hh506443(v=VS.110).aspx

We should probably move those over at the same time. The produce also sends a lot of traffic to those help pages, so when we move those pages, I'll change that link to point to these docs as well.

**Comment by mairaw** [comment]
Is this something that would not be on the TOC?

**Comment by richlander** [comment]
I would think they would show up in the TOC, just like how the "Windows 8 / .NET 3.5" one does. Thoughts?

**Comment by mairaw** [comment]
They feel more like support pages than actual docs, but it's fine by me. So they would go under the Installation node once we move the .NET docs, correct? 

I agree that we should keep those simple and as single units if regular consumers are being redirected to those. That Windows 8 / .NET 3.5 topic is a major point of frustration for customers. Non developers find it too difficult and others are frustrated they cannot get .NET installed.

**Comment by richlander** [comment]
The problem with support pages is that they are not at all approachable for consumers to read. They typically force a format that is intended for a different audience. There is no perfect option, but our docs seem better than the alternative. Also, we get an opportunity to address feedback since it's in our doc-set.

Anyway, I think we agree. It's better for us to own/deliver more of the experience than less.
