### ISSUE TITLE
Typo in First Image comparing patterns

### ISSUE THREAD

**Issue by thiagoloureiro** [dotnet/docs#8593]
It's written AMPQ, it shouldn't be AMQP (Advanced Message Queuing Protocol) ?

this image:
https://github.com/dotnet/docs/blob/master/docs/standard/microservices-architecture/architect-microservice-container-applications/media/image15.png

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89fd8427-589c-9158-f9e9-6b59d34ac4e2
* Version Independent ID: 3091e297-8939-cc0c-7437-5ec8be56ae3c
* Content: [Communication in a microservice architecture](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/architect-microservice-container-applications/communication-in-microservice-architecture)
* Content Source: [docs/standard/microservices-architecture/architect-microservice-container-applications/communication-in-microservice-architecture.md](https://github.com/dotnet/docs/blob/master/docs/standard/microservices-architecture/architect-microservice-container-applications/communication-in-microservice-architecture.md)
* Product: **dotnet**
* GitHub Login: @CESARDELATORRE
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
Thanks for your feedback @thiagoloureiro. 
@CESARDELATORRE @mvelosop can you please take a look at this feedback? I also noticed that the image uses i.e. several times, which is against our guidelines: https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/i/ie

**Comment by mvelosop** [comment]
Hi @mairaw, @thiagoloureiro is right, fixed in PR #9011.
