### ISSUE TITLE
Error in euqlity short-circuit documentation

### ISSUE THREAD

**Issue by hackerzhuli** [dotnet/docs#8594]
"These comparisons short-circuit. The == operator stops evaluating members as soon as one pair is not equal. The != operator stops evaluating members as soon as one pair is equal."
I believe the != operator also stops evaluating members as soon as one pair is not equal.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bf15268-9d34-cf10-97b9-0b94022c3305
* Version Independent ID: 17728168-48fa-0f5f-0c19-31ae4ce6fdb9
* Content: [Tuple types - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/tuples)
* Content Source: [docs/csharp/tuples.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tuples.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@hackerzhuli Thanks for spotting this and pointing it out for us.

You are correct, the explanation for short-circuiting on `!=` should be reversed.

Do you want to issue a PR for this? I've added it to the next milestone, and added the "up-for-grabs" label. If so, I'll assign it to you, and watch for a PR.  If not, I'll make the change in the next few weeks.

**Comment by M-Zuber** [comment]
I'd be happy to make the PR if @hackerzhuli is not going to

**Comment by BillWagner** [comment]
@M-Zuber Thanks.  I'll watch for a PR.  (I wanted to wait a few days, and haven't heard from @hackerzhuli).
