### ISSUE TITLE
Please add a way to stop the infinite loop.

### ISSUE THREAD

**Issue by kunggom** [dotnet/docs#8595]
I ran the code to solve the challenge and fall into an infinite loop, and I was embarrassed to find no way to stop it. I think we should add a button to stop the infinite loop manually, or add a feature to automatically stop code that takes too long to execute.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d9e98de-9df3-d63f-f6a6-aa079eb5095f
* Version Independent ID: a057574c-020f-a9f0-9dfc-f8936a1132fe
* Content: [Collections interactive tutorial - C# quickstarts](https://docs.microsoft.com/en-us/dotnet/csharp/quick-starts/list-collection?tutorial-step=7)
* Content Source: [docs/csharp/quick-starts/list-collection.yml](https://github.com/dotnet/docs/blob/live/docs/csharp/quick-starts/list-collection.yml)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by jonsequitur** [comment]
This looks like a bug on the Try .NET end where our usual timeout protection fails under certain circumstances but the server still returns 200. I'm looking into a fix.

**Comment by mairaw** [comment]
@jonsequitur is this still an issue or has it been fixed? If it hasn't been fixed, maybe we should port it to the try.net repo?

**Comment by jonsequitur** [comment]
The run button no longer gets stuck, so I think this can be closed.

There's another related change in Try .NET that will deploy next week that will make the proactive timeout a bit faster.

**Comment by BillWagner** [comment]
Closing as this has been fixed in the try.net experience.
