### ISSUE TITLE
Attaching debugger

### ISSUE THREAD

**Issue by austvik** [dotnet/docs#8596]
How do you attach a debugger and pause before execution until the debugger is attached?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd3f4227-cd9b-7b1c-7e1b-ffb3d42ae496
* Version Independent ID: 7e78f9f5-f77c-828d-ef76-8ef8593d5803
* Content: [dotnet run command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-run?tabs=netcore21)
* Content Source: [docs/core/tools/dotnet-run.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-run.md)
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment]
You either have to run the project in a program that supplies the debugger (VSCode, Visual Studio, etc) or add the `System.Diagnostics.Debugger.Launch();` line to your code which will prompt you to attach a debugger and pause the code at that point. I was able to call `Launch` and then open VSCode and tell it to attach to a process and start debugging at that point.

As this question is not related to the CLI reference article and is more generic, I'm going to close this. Thanks!
