### ISSUE TITLE
Compiler Error CS0724 has a wrong, irrelevant code sample

### ISSUE THREAD

**Issue by equin0x80** [dotnet/docs#8600]
Compiler Error CS0724 is an error about the CLSCompliant attribute. However, the code sample that is supposed to produce this error is completely irrelevant and relates to try-catch.  In fact this code sample looks like it should be at CS1626 instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db150051-3261-09c1-ec10-9d7513dcae2f
* Version Independent ID: f902dd18-2e34-a913-fd68-50396d0875cc
* Content: [Compiler Error CS0724](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs0724)
* Content Source: [docs/csharp/misc/cs0724.md](https://github.com/dotnet/docs/blob/master/docs/csharp/misc/cs0724.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mikkelbu** [comment]
Isn't it the text that is wrong and not the code? https://github.com/thomaslevesque/GenerateCSharpErrors/blob/master/CSharpErrorsAndWarnings.md states that CS0724 is an Error with the following text "A throw statement with no arguments is not allowed in a finally clause that is nested inside the nearest enclosing catch clause". According to the page it is extracted from the roslyn source code, see e.g.
* https://github.com/dotnet/roslyn/blob/14e0068d9d529ade86c0ed1544477a221809d0e0/src/Compilers/CSharp/Portable/Binder/BinderFlags.cs#L67
* https://github.com/dotnet/roslyn/blob/14e0068d9d529ade86c0ed1544477a221809d0e0/src/Compilers/CSharp/Test/IOperation/IOperation/IOperationTests_TryCatch.cs#L6949

**Comment by Youssef1313** [comment]
The code sample is correct, but the text of the error isn't. I've opened #15422 to fix the error message text.
