### ISSUE TITLE
Compiler Error CS1626: mistake in the docs?

### ISSUE THREAD

**Issue by equin0x80** [dotnet/docs#8601]
Compiler Error CS1626 states: "A yield statement is not allowed in a try block if there is a catch clause associated with the try block. To avoid this error, move the yield statement out of the catch clause."
This does not make sense: if the problematic yield statement is in a TRY block, then how can it be moved out of a CATCH?  I think the writer confused the words TRY and CATCH.  (The code sample seems to confirm that this is a mistake.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c0911c4-db28-56c2-9e10-db98404bca40
* Version Independent ID: 0822b9c2-3b52-0384-5991-f3e2f00a45b0
* Content: [Compiler Error CS1626](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs1626)
* Content Source: [docs/csharp/misc/cs1626.md](https://github.com/dotnet/docs/blob/master/docs/csharp/misc/cs1626.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by rpetrusha** [comment]
Thanks for your feedback, @equin0x80; we appreciate it. @brian-fors  has addressed this issue in #9417.
