### ISSUE TITLE
Thank you.

### ISSUE THREAD

**Issue by mmuratay** [dotnet/docs#8605]
Thank you so much. As a new developer, this is what i need.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3dff5a94-d9cd-e31b-4056-362abbe8d782
* Version Independent ID: cfb1ad21-e822-4075-2726-bd130ec2358d
* Content: [C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/)
* Content Source: [docs/csharp/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/index.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for the compliments. I'm glad it is what you needed.
