### ISSUE TITLE
string (C# Reference)

### ISSUE THREAD

**Issue by LisandroSu** [dotnet/docs#8616]
@ArtemIsaev13 commented on [Wed Oct 24 2018](https://github.com/dotnet/docs.ru-ru/issues/141)

On the page 
https://docs.microsoft.com/ru-ru/dotnet/csharp/language-reference/keywords/string
you can see the text:

**_The advantage of verbatim strings is that escape sequences are not processed, which makes it easy to write, for example, a fully qualified file name:
@"c:\Docs\Source\a.txt"  // rather than "c:\\Docs\\Source\\a.txt"_**

Maybe you mean this text:
**_@"c:/Docs/Source/a.txt"  // rather than "c:\\Docs\\Source\\a.txt"_**
?

best regards
Isaev Artem
---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 67b95029-3bf2-c56d-48ab-be7ad1f43762
* Version Independent ID: a5f74e00-3f77-804d-f47d-26caa05bfc40
* Content: [string (Справочник по C#)](https://docs.microsoft.com/ru-ru/dotnet/csharp/language-reference/keywords/string)
* Content Source: [docs/csharp/language-reference/keywords/string.md](https://github.com/dotnet/docs.ru-ru/blob/live-sxs/docs/csharp/language-reference/keywords/string.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by LisandroSu** [comment]
Hi Team, please check on this issue reported by the user.

Thanks!

**Comment by mairaw** [comment]
Nope @ArtemIsaev13. The document is correct. 

See another example with and without the verbatim at this topic:
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/verbatim

```csharp
string filename1 = @"c:\documents\files\u0066.txt";
string filename2 = "c:\\documents\\files\\u0066.txt";
```

Let us know if you still have questions. Thanks!
