### ISSUE TITLE
Only returns a single out of multiple exceptions

### ISSUE THREAD

**Issue by ygoe** [dotnet/docs#8621]
&gt; If any of the supplied tasks completes in a faulted state, the returned task will also complete in a Faulted state, where its exceptions will contain the aggregation of the set of unwrapped exceptions from each of the supplied tasks. 

That doesn't match my observation. Here's the test code:

	private Task Test1()
	{
		throw new Exception("Test1");
	}

	private Task Test2()
	{
		throw new Exception("Test2");
	}

	public async Task RunAsync()
	{
		try
		{
			var list = new List&lt;Task&gt;();
			list.Add(Task.Run(() =&gt; Test1()));
			list.Add(Task.Run(() =&gt; Test2()));
			await Task.WhenAll(list);
		}
		catch (Exception ex)
		{
		}
	}

Call `RunAsync` and look at the exception `ex`. It's a System.Exception (no AggregateException or anything else) with the message "Test1". The second exception is not there. Where can I find that from my code?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db7b0ad3-c574-7956-3a5d-f70ea7689a42
* Version Independent ID: 646e4b02-2f82-5942-62f7-cf5d26b9e213
* Content: [Task.WhenAll Method (System.Threading.Tasks)](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.task.whenall?view=netframework-4.7.2#System_Threading_Tasks_Task_WhenAll_System_Collections_Generic_IEnumerable_System_Threading_Tasks_Task__)
* Content Source: [xml/System.Threading.Tasks/Task.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Threading.Tasks/Task.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by BillWagner** [comment]
Your example does match the documented behavior for the `await` expression. The `await` unwraps the `AggregateException` and throws the first exception in the collection. Instead, try this:

```csharp
public void RunAsync()
{
	try
	{
		var list = new List&lt;Task&gt;();
		list.Add(Task.Run(() =&gt; Test1()));
		list.Add(Task.Run(() =&gt; Test2()));
		Task.WhenAll(list).Wait(); // Not recommended, but needed to observe all exceptions
	}
	catch (Exception ex)
	{
	}
}
```
