### ISSUE TITLE
Problems with WriteObject

### ISSUE THREAD

**Issue by aliaga-d** [dotnet/docs#8630]
Regarding [https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/how-to-serialize-and-deserialize-json-data](url)  in step 3, which says

> Use the WriteObject method to write JSON data to the stream. 

When said object p ' string member (say name) contains a '/' , WriteObject writes it as '\/'. Is there any way to avoid this?

**Comment by tdykstra** [comment]
What would you want it to do with the slash character (`/`)?
