### ISSUE TITLE
Deprecated?

### ISSUE THREAD

**Issue by rfcdejong** [dotnet/docs#8641]
Looking at the repository readme https://github.com/aspnet/HealthChecks/, is this way of health checking deprecated and replaced in 2.2 Core.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e98bdd99-d89d-8720-9018-25f73dcfdbd8
* Version Independent ID: c02edf4f-eb03-f02a-c72d-510cc17c8c9e
* Content: [Health monitoring](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/implement-resilient-applications/monitor-app-health)
* Content Source: [docs/standard/microservices-architecture/implement-resilient-applications/monitor-app-health.md](https://github.com/dotnet/docs/blob/master/docs/standard/microservices-architecture/implement-resilient-applications/monitor-app-health.md)
* Product: **dotnet**
* GitHub Login: @CESARDELATORRE
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
@CESARDELATORRE @mvelosop it seems that this guidance needs to be reviewed for ASP.NET Core 2.2. Please take a look.

**Comment by CESARDELATORRE** [comment]
Sure, we're already working on that update as part of a major update targeting .NET Core 2.2 for this guidance. 👍 
The code is already implemented in eShopOnContainers and will be merged into DEV pretty soon, too.

**Comment by nishanil** [comment]
@rfcdejong We just updated the doc. Now, we refer to the new Health Check feature introduced in ASP.NET Core 2.2.

**Comment by mvelosop** [comment]
Closing this issue now, as the new health checks have been referenced in the docs and it's already merged into dev, but feel free to comment, will reopen if needed.

**Comment by bugejakurt** [comment]
Can this article be renamed to Health Checks? It is confusing and can sometimes be seen as a .NET Core alternative to Health Monitoring in Full Framework (https://docs.microsoft.com/en-us/previous-versions/bb398933(v=vs.140))
