### ISSUE TITLE
Command Not Working

### ISSUE THREAD

**Issue by regal60740** [dotnet/docs#8647]
I could not get "dotnet published\aspnetapp.dll" from above to work in console. I had to change to the "C:\Windows\System32\dotnet-docker\samples\aspnetapp\aspnetapp\published" directory to get it to work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9731aae1-505b-abb1-0d4b-d6a83ec735e1
* Version Independent ID: 760790d5-0e81-ea6c-19ea-f226d08ddf1f
* Content: [Building .NET Core Docker Images](https://docs.microsoft.com/en-us/dotnet/core/docker/building-net-docker-images)
* Content Source: [docs/core/docker/building-net-docker-images.md](https://github.com/dotnet/docs/blob/master/docs/core/docker/building-net-docker-images.md)
* Product: **dotnet-core**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by f2calv** [comment]
Ditto - "dotnet published\aspnetapp.dll" (windows) and "dotnet published/aspnetapp.dll" (linux) need to be amended to "dotnet aspnetapp\published\aspnetapp.dll" & "dotnet aspnetapp/published/aspnetapp.dll"

**Comment by mairaw** [comment]
@richlander @spboyer can you help to fix this topic or at least validate the proposed solution is correct?

**Comment by spboyer** [comment]
@regal60740 & @f2calv 

In the step -> https://docs.microsoft.com/en-us/dotnet/core/docker/building-net-docker-images#run-the-aspnet-app-locally

The instructions state to change directory into `aspnetapp` prior to building and running the commands. The command assumes you are currently in the `aspnetapp` directory.

```console
cd dotnet-docker
cd samples
cd aspnetapp // solution scope where the dockerfile is located

docker build -t aspnetapp .
docker run -it --rm --name aspnetcore_sample aspnetapp
```

**Comment by Thraka** [comment]
This article is going to move to the ASP.NET repo. 

@mairaw @scottaddie Can someone move this issue?

**Comment by Thraka** [comment]
@regal60740 This article moved over to the ASP.NET repo and was fixed up. I'm going to close this issue. If you click on the web link on your first comment, you will be moved to the other repo where you can verify the fix. 

I'm going to close this issue, thanks!
