### ISSUE TITLE
Example is wrong

### ISSUE THREAD

**Issue by GreatisNate** [dotnet/docs#8648]
Example for the subtraction is incorrect, the second set console output accidentally repeats the first date minus second date, when it should be third date, the output comments for the differences are correct, but not the range,

Console.WriteLine("({0}) - ({1}): {2} days, {3}:{4:d2}", 
                  firstDate.ToString(), 
                  thirdDate.ToString(), 
                  difference.Days, 
                  difference.Hours, 
                  difference.Minutes); 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40208747-c4a9-aa58-7362-be7da3f733ec
* Version Independent ID: 68ce45b0-4c7b-064f-131b-17264d8c9d23
* Content: [DateTimeOffset.Subtract Method (System)](https://docs.microsoft.com/en-us/dotnet/api/system.datetimeoffset.subtract?view=netframework-4.7.2)
* Content Source: [xml/System/DateTimeOffset.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System/DateTimeOffset.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Good catch @GreatisNate! We'll take care of that.
