### ISSUE TITLE
Wrong Directory

### ISSUE THREAD

**Issue by regal60740** [dotnet/docs#8663]
Where it says: Execute the following command in the unit-testing-using-dotnet-test directory:

console

Copy
dotnet sln add .\PrimeService.Tests\PrimeService.Tests.csproj

It should say "unit-testing-using-nunit" directory.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0063ceb-57ea-f30c-efed-b2a36314ccaa
* Version Independent ID: bd9a321e-2ef2-491d-cd37-2d9c66f90cc9
* Content: [Unit testing C# with NUnit and .NET Core](https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-with-nunit)
* Content Source: [docs/core/testing/unit-testing-with-nunit.md](https://github.com/dotnet/docs/blob/master/docs/core/testing/unit-testing-with-nunit.md)
* Product: **dotnet-core**
* GitHub Login: @rprouse
* Microsoft Alias: **mairaw**

**Comment by chandanadesilva** [comment]
Ideally change the back slashes to forward slashes to keep in line with the rest of document
dotnet sln add  PrimeService.Tests/PrimeService.Tests.csproj
