### ISSUE TITLE
Wrong Directory Name

### ISSUE THREAD

**Issue by regal60740** [dotnet/docs#8665]
"Execute dotnet sln add .\PrimeService.Tests\PrimeService.Tests.csproj in the unit-testing-using-dotnet-test directory." should be the "unit-testing-using-mstest" directory.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c123f1f-8ae8-db21-2eac-4297bfc30b44
* Version Independent ID: 4675decb-333f-0508-5a3d-ce71dc85936d
* Content: [Unit testing C# with MSTest and .NET Core](https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-with-mstest)
* Content Source: [docs/core/testing/unit-testing-with-mstest.md](https://github.com/dotnet/docs/blob/master/docs/core/testing/unit-testing-with-mstest.md)
* Product: **dotnet-core**
* GitHub Login: @ncarandini
* Microsoft Alias: **wiwagn**

**Comment by regal60740** [comment]
Also, when get to "Run dotnet test, and two of these tests fail." I get a total of 4 tests, and three fail. after changing the if statement to "if (candidate < 2)", I still get 4 tests but they all pass.

**Comment by mikkelbu** [comment]
@regal60740 I get 5 tests (the original + one for `ReturnFalseGivenValuesLessThan2`, and one for each of the values -1, 0, and 1). And the tests for `ReturnFalseGivenValuesLessThan2`, -1, and 0 fail. I guess that the overall test `ReturnFalseGivenValuesLessThan2`  is failing as one or more of the child tests are failing. Whether this is something new for MSTest I don't know as I have never used MSTest.
