### ISSUE TITLE
Cut off words

### ISSUE THREAD

**Issue by Structed** [dotnet/docs#8675]
Some instances of the word "Attribute" are cut off, where the first character ("a") is missing. Sometimes, appearing as either

  - doubled, e.g. `ttribute attribute`
or
  - alone, e.g. `ttribute`

Examples with context:

> `You use the ttribute class to [...]`
> `The ttribute attribute lets [...]`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71654f5f-8c0e-87c9-8b8c-ad17f578d427
* Version Independent ID: ab6d5a69-3cbc-fcf7-10f2-6e2deb1ed30c
* Content: [DataType Enum (System.ComponentModel.DataAnnotations)](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.dataannotations.datatype?view=netframework-4.7.2)
* Content Source: [xml/System.ComponentModel.DataAnnotations/DataType.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.ComponentModel.DataAnnotations/DataType.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **riande**

**Comment by mairaw** [comment]
Thanks @Structed. I've opened https://github.com/dotnet/dotnet-api-docs/pull/673 to fix this.

**Comment by mairaw** [comment]
Actually, I changed my PR to fix a similar issue on different classes and @mikkelbu created https://github.com/dotnet/dotnet-api-docs/pull/674 to fix this one.
