### ISSUE TITLE
Direct link to GitHub for Content feedback is broken

### ISSUE THREAD

**Issue by Structed** [dotnet/docs#8676]
On [this documentation page](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.dataannotations.datatype?view=netframework-4.7.2), the direct link to leave feedback on GitHub is broken.

![image](https://user-images.githubusercontent.com/29922/47593493-d56fa700-d977-11e8-82e6-aeb7d8964a97.png)

Instead, it points to `https://docs.microsoft.com/en-us/dotnet/api/%7B0%7D`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71654f5f-8c0e-87c9-8b8c-ad17f578d427
* Version Independent ID: ab6d5a69-3cbc-fcf7-10f2-6e2deb1ed30c
* Content: [DataType Enum (System.ComponentModel.DataAnnotations)](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.dataannotations.datatype?view=netframework-4.7.2)
* Content Source: [xml/System.ComponentModel.DataAnnotations/DataType.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.ComponentModel.DataAnnotations/DataType.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **riande**

**Comment by mairaw** [comment]
Thanks @Structed for letting us know. I've moved this feedback to https://github.com/MicrosoftDocs/feedback/issues/807 for our engineering team to take a look.
