### ISSUE TITLE
This is why?

### ISSUE THREAD

**Issue by CwjXFH** [dotnet/docs#8682]
Do not throw System.Exception, System.SystemException, System.NullReferenceException, or System.IndexOutOfRangeException intentionally from your own source code.

If throw these exception in my own source code,will there be any negative effects?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36032d47-681c-e39e-331a-14f178d7e583
* Version Independent ID: 46c574db-a657-f2a9-9d0f-dfb9a83a124f
* Content: [Creating and Throwing Exceptions (C# Programming Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/exceptions/creating-and-throwing-exceptions)
* Content Source: [docs/csharp/programming-guide/exceptions/creating-and-throwing-exceptions.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/exceptions/creating-and-throwing-exceptions.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by dan101201** [comment]
Yes as you most likely want to catch the exceptions, and if that catch is not universal (if something other than what you threw made that exception and your catch doesn't work with that) then you can run into bugs, and other stuff. There is really no reason to not make your own exceptions.

**Comment by CwjXFH** [comment]
I see,thanks!
