### ISSUE TITLE
When will you start creating content that is useful?

### ISSUE THREAD

**Issue by VProfirov** [dotnet/docs#8701]
You explain in the typeof documentation about GetType, but you say almost nothing about the subject at hand, why is that?

Here is a peace of useful info from you know where(just a taste):
"All are different.
typeof takes a type name (which you specify at compile time).
GetType gets the runtime type of an instance.
is returns true if an instance is in the inheritance tree.
...etc."
And this is across the board so often.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e46579c-383b-1049-fee9-59c27328f7ba
* Version Independent ID: e9a776dd-e2b4-a2b2-6db4-4de7a4a0baeb
* Content: [typeof (C# Reference)](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/typeof#c-language-specification)
* Content Source: [docs/csharp/language-reference/keywords/typeof.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/typeof.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
What is missing in this document that you need @VProfirov ?

**Comment by mairaw** [comment]
Closing due to the lack of response. Please let us know if you can share more information about what you'd like to see on this page.
