### ISSUE TITLE
Console Teleprompter sample: Missing 'x' and 'X' when `GetInput` is refactored to use the config object

### ISSUE THREAD

**Issue by tdnelson2** [dotnet/docs#8705]
Also, It would probably be helpful to also listen for '.' and ',' because the average user probably won't think to hold down the shift key.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4a28322-944d-73c3-177c-d9bec577c08b
* Version Independent ID: 15ce52df-1eb1-7743-8440-dbef3169487c
* Content: [Console Application](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/console-teleprompter)
* Content Source: [docs/csharp/tutorials/console-teleprompter.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/console-teleprompter.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by XavierAGarciaR** [comment]
Yes! We are left with the doubt of seeing it in action the 'X' and the 'x', but I think that it can be added to the GetInput and rehearse.

**Comment by BillWagner** [comment]
These are good suggestions. Would you like to submit a PR @XavierAGarciaR or @tdnelson2 

I've added this issue to the community contributions project, and added the up-for-grabs label.
