### ISSUE TITLE
Link to 2-D Transforms Sample not working

### ISSUE THREAD

**Issue by milbrandt** [dotnet/docs#8709]
Tries to Access https://archive.msdn.microsoft.com/Project/Download/FileDownload.aspx?ProjectName=wpfsamples&DownloadId=7812 and gets "The DNS name does not exist."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 925e5755-a2ab-e85f-e14d-174a8f521451
* Version Independent ID: 6e56d499-295e-bf95-a4a2-d416da2c5912
* Content: [How to: Translate an Element](https://docs.microsoft.com/en-us/dotnet/framework/wpf/graphics-multimedia/how-to-translate-an-element)
* Content Source: [docs/framework/wpf/graphics-multimedia/how-to-translate-an-element.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/graphics-multimedia/how-to-translate-an-element.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks @milbrandt. I've fixed the link target to go to new sample location.
