### ISSUE TITLE
Thanks for your time and effort for this good piece of documentation.

### ISSUE THREAD

**Issue by xamarin-volkan** [dotnet/docs#8711]
I would not write this on a normal day but after reading other unnecessary comments I did want to add one, too.
At the last line of the output, it is written as "Press any key to exit." because of the code;  Console.WriteLine("Press any key to exit.");.
Thanks again. You made a very well job with this doc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4343ac18-37c1-9a3e-0210-b69bf924db91
* Version Independent ID: 19d63151-4d8a-30c6-35de-0c8c277cde25
* Content: [Classes (C# Programming Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/classes)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/classes.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/classes.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Thraka** [comment]
@xamarin-volkan Thanks for the compliments 😄 I think it's OK to omit that from the output as it's not important. Thanks!
