### ISSUE TITLE
No error or warning if specified SDK doesn't exist

### ISSUE THREAD

**Issue by yhvicey** [dotnet/docs#8720]
I have below 2.1.4yz sdks installed on my machine:
```cmd
$ dotnet --list-sdks
2.1.400-preview-009063 [C:\Program Files\dotnet\sdk]
2.1.400-preview-009171 [C:\Program Files\dotnet\sdk]
2.1.400 [C:\Program Files\dotnet\sdk]
```
And I specified sdk version to `2.1.403` in global.json, however there's no error or warning when I build these projects. Is it by design? In [Matching rules](https://docs.microsoft.com/en-us/dotnet/core/tools/global-json#matching-rules) section it says that in this situation there should be an error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a94c335b-0b65-96cc-1c25-65777fbe4bb5
* Version Independent ID: 6d80613f-42dc-35d7-aeff-3187a36dbbca
* Content: [global.json overview](https://docs.microsoft.com/en-us/dotnet/core/tools/global-json#matching-rules)
* Content Source: [docs/core/tools/global-json.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/global-json.md)
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Thanks for filing this issue @yhvicey. According to the issue you filed in the other repo, it seems that this was a bug on the SDK behavior for previous versions that was rolling backwards, not an issue with docs. So closing this.
