### ISSUE TITLE
typo: correct text to make clear that guidance is to use attributes from System.Runtime.Serialization and not System.Xml.Serialization

### ISSUE THREAD

**Issue by fgenolini** [dotnet/docs#8722]
In the section

> AVOID designing your types specifically for XML Serialization, unless you have a very strong reason to control the shape of the XML produced. This serialization technology has been superseded by the Data Contract Serialization discussed in the previous section.
> 
> In other words, don't apply attributes from the **System.Xml.Serialization** namespace to new types, unless you know that the type will be used with XML Serialization. The following example shows how System.Xml.Serialization can be used to control the shape of the XML -produced.

make sure that the namespace is **System.Xml.Serialization**, not System.Runtime.Serialization

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 690b0523-b74b-ec96-6c50-0586cbb4c297
* Version Independent ID: e6d9ec13-2d5d-227b-1a12-5f322a31d0a9
* Content: [Serialization guidelines](https://docs.microsoft.com/en-us/dotnet/standard/serialization/serialization-guidelines)
* Content Source: [docs/standard/serialization/serialization-guidelines.md](https://github.com/dotnet/docs/blob/master/docs/standard/serialization/serialization-guidelines.md)
* Product: **dotnet**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by Thraka** [comment]
@BillWagner I don't think this issue is correct. To me the original wording is correct. `DO NOT APPLY to new types unless you know it is going to be used by xml serialization...`

**Comment by BillWagner** [comment]
@Thraka I agree with you. In my opinion, the original text is correct.

**Comment by Thraka** [comment]
@fgenolini Thank you for creating this issue. We believe the article wording is correct and should not be changed. I'll close this issue but if you would like to continue the discussion, please feel free to comment. Thanks!

**Comment by fgenolini** [comment]
Hi,

The original text confused me and your answer confuses me even more.

Could you please confirm my understanding?

The new types belong to a new namespace called 
<<
System.Runtime.Serialization 
>>

1. The guidance is that this new type is new for a good reason and that new code should only use these new attributes and this new namespace.

2. However, if you alter old code, or write new code that will have to work with old code, then keep using the old attributes and the old namespace.

If you confirm both these statements then you should alter the documentation as I have pointed out.

**Comment by Thraka** [comment]
@fgenolini Hi! Thanks for writing back 😄 

After reading your reply and looking through the docs again, I think I have figured out why this all sounds odd. I think that the statement should read as follows:

>AVOID designing your types specifically for XML Serialization, unless you have a very strong reason to control the shape of the XML produced. This serialization technology has been superseded by the Data Contract Serialization discussed in the previous section.

>In other words, **don't** apply attributes from the **System.Xml.Serialization** namespace to new types, unless you know that the type will be used with XML Serialization. The following example shows how System.Xml.Serialization can be used to control the shape of the XML -produced.

**Comment by fgenolini** [comment]
Oh yes, that was my other explanation: a typo on the namespace, which sadly inverts the meaning of the sentence ;-)

**Comment by Thraka** [comment]
@fgenolini Would you agree that my suggestion fixes the problem? 😄

**Comment by fgenolini** [comment]
Yes

**Comment by Thraka** [comment]
@fgenolini OK, I updated your original issue comment with what needs to be done and I've reopened this issue. Thanks for being persistent on this 😄

**Comment by mairaw** [comment]
@fgenolini would you like to submit a pull request with the fix?
You can find more information about this at https://docs.microsoft.com/en-us/contribute/#quick-edits-to-existing-documents.

**Comment by Thraka** [comment]
@Soundug wants to fix it.
