### ISSUE TITLE
Reword .NET Standard targeting guidance?

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/docs#8726]
I found this confusing:
&gt; ❌ AVOID using multi-targeting with .NET Standard if your source code is the same for all targets.

I believe it means, don't target specific platforms in addition to targeting .NET Standard if they will be built from the same source code. However "multi-targeting with .NET Standard" sounds like a concept, so it sounds like it's advising against targeting .NET Standard at all. Perhaps something like this:

&gt; ❌ AVOID multi-targeting as well as targeting .NET Standard, if your source code is the same for all targets.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b3638c9-ea3c-1c9e-2763-5c3e8e965663
* Version Independent ID: aff99d6b-9471-9277-160b-670ee8028b53
* Content: [Cross-platform targeting](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/cross-platform-targeting)
* Content Source: [docs/standard/library-guidance/cross-platform-targeting.md](https://github.com/dotnet/docs/blob/master/docs/standard/library-guidance/cross-platform-targeting.md)
* Product: **dotnet**
* GitHub Login: @JamesNK
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
@JamesNK can you comment on this feedback from @danmosemsft?

**Comment by JamesNK** [comment]
Looks good to me :shipit:

**Comment by mairaw** [comment]
Ok, I'll create the PR then.
