### ISSUE TITLE
Confusing example `if (obj is var _)`

### ISSUE THREAD

**Issue by OJacot-Descombes** [dotnet/docs#8727]
In chapter [Pattern matching with switch and is](https://docs.microsoft.com/en-us/dotnet/csharp/discards#pattern-matching-with-switch-and-is) in the code snippet ...
```
private static void ProvidesFormatInfo(object obj)
{
    if (obj is IFormatProvider fmt)
        Console.WriteLine($"{fmt} object");
    else if (obj is null) {
        Console.Write("A null object reference: ");
        Console.WriteLine("Its use could result in a NullReferenceException");
    }
    else if (obj is var _)
        Console.WriteLine($"Some object type without format information");
}
```

... the last `else if (obj is var _)` is confusing. It seems to me that a simple `else` would have the same effect. What does it mean exactly? Does it always return`true` or is it equivalent to `obj != null`?

An explanation for what `obj is var _` means should be given.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8047b417-55af-c6df-9333-f1e1c428e594
* Version Independent ID: 8bcc16bb-c2d8-0b6d-af20-6958964efe9e
* Content: [Discards - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/discards)
* Content Source: [docs/csharp/discards.md](https://github.com/dotnet/docs/blob/master/docs/csharp/discards.md)
* Product: **dotnet-csharp**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by lucasnobredev** [comment]
Hello @OJacot-Descombes . 
I made some tests and all types got inside in last "else if". I agree with a simple else { } too. 
About the explanation for what *var _* means, in second paragraph the article is pretty clear, in my opinion.

**Comment by elgonzo** [comment]
I agree that the example given is quite contrived and will quite likely confuse inexperienced programmers (which would rely more on the documentation than more seasoned programmers).

Small correction to lucas' comment (you can call it nitpicking, because that is what i am doing here): To understand `something is var _`, you would need to understand pattern matching with the so-called "var pattern" (see here: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/is#a-namevar--var-pattern-a) , which is independent from `_` discards. This is yet another tidbit that shows _how_ confusing this code example really is... ;-)

**Comment by OJacot-Descombes** [comment]
The same article also says: "Every expression always matches the discard pattern.". There is no _discard pattern_. Discards can be used in conjunction with patterns but are not patterns themselves. It would however be correct to say: "A pattern match with the var pattern always succeeds."

**Comment by elgonzo** [comment]
"_Discard pattern_" (o.O)?

Are there (reasonable) situations, where one would want to combine `is` pattern matching with `_` discards? I failed to come up with a single plausible scenario. Please forgive me, but to me it looks pointless to combine the two...

**Comment by lucasnobredev** [comment]
@elgonzo I agree with you. Reading again, content it's a kind of confusing and not so clear how I said before.
--
I want to bring here a suggestion made by @rpetrusha in another discussion in https://github.com/dotnet/samples/pull/426#discussion_r229385478.

Although the final result in if/else is the same, if we remove condition of code and remove the phrase "It also used the discard pattern to handle non-null objects of any other type", the section lost the sense to exist.

Even so, if we think about the important of the section, like @elgonzo said, it already seems to be pointless.

**Comment by elgonzo** [comment]
There is a little something that bugged me last night. `_` is not just a (contextual) keyword but it also might just be an identifier, like:

```
var someText = "Riddle me that";

var x = someText;
Console.WriteLine(x);

var _ = someText;
Console.WriteLine(_);
```

Now let me cheekily put this example with "var pattern" + discard here:

```
var someText = "Riddle me that";

if (someText is var x)
    Console.WriteLine(x);

if (someText is var _)
    Console.WriteLine(_);
```
Jarring, isn't it? I don't have a C# 7 compiler at hand, so i don't know if the second example would actually compile or what the behavior of this code would be. But anyway, keeping my first code example here in mind, why would you expect `_` being a discard instead of just being a variable identifier? Wouldn't it make (obvious?) sense to treat/read `_` here just as a variable identifier and not as a discard?

It feels to me like that this whole "var pattern" + discard thing is doing no good for the expressiveness of the C# language.

My head hurts.
Really.

**Comment by julealgon** [comment]
I think there was a big mistake in updating the code like that. Now, the example makes no sense whatsoever in that context as it doesn't show the usage of the `_` discard pattern in conjunction with the `is` or `switch`.

 I see 3 valid options here:
- Put the example back as is was. Even if confusing, it was at least showcasing the feature being discussed.
- Change the example to be less confusing, but still use the discard pattern in it.
- Remove the entire section altogether (I'd be against this one quite strongly, but it is still a possibility).

The way it is now makes absolutely no sense and made me scratch my head when I searched for the `_` in the code sample only to not find it anywhere.

**Comment by lucasnobredev** [comment]
@BillWagner Can we re-open this discussion?

**Comment by SuryakantSoniOfficial** [comment]
Right now, the example makes no sense. It doesn't show the use of discards at all.
It would be really good if it can reverted back to its original. That way, at least it will show the use of discards, even though unnecessary, which the topic is all about.

**Comment by BillWagner** [comment]
Reopening based on discussions.

**Comment by Narvey** [comment]
I have a feeling there is no legitimate use case for discards in `is var` pattern matching. If the expression always returns true, then the only reason you are even doing it is for the output value, right? Then why would you throw that value away?

**Comment by psaxton** [comment]
As it is currently written, the [Pattern matching with `switch` and `is`](https://docs.microsoft.com/en-us/dotnet/csharp/discards#pattern-matching-with-switch-and-is) section doesn't use `switch` or `discard` anywhere in it. This should be removed or fixed.

**Comment by jnieman21** [comment]
+1 that this is confusing. I searched for some time trying to find the _ with no success, only to find this comment thread.

**Comment by OJacot-Descombes** [comment]
To begin with, the text introduces the term **discard pattern** but does explain what it consists of. In relation with switch expressions, the discard pattern is simply an underscore with no preceding `var`. A blog of Mads, [Do more with patterns in C# 8.0](https://devblogs.microsoft.com/dotnet/do-more-with-patterns-in-c-8-0/) says: 

> default has been replaced with the _ discard pattern for brevity.

In [Recursive Pattern Matching](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-8.0/patterns) the **antlr** syntax is given as
```
discard_pattern
    : '_'
    ;
```
and
```
var_pattern
    : 'var' designation
    ;
```
where `designation` can be different things. Among them is the `discard_designation` which is a `_`. According to these definitions `var _` is not a **discard pattern** but a **var pattern** with a **discard designation**. The discard can also be used in the **declaration pattern**:
```
declaration_pattern
    : type simple_designation
    ;
```
where `simple_designation` can be a  `discard_designation`. The text should explain the **discard pattern**, the **var pattern** with **discard designation** and the **declaration pattern** with **discard designation**. Also, it should be explained that the expression `is var _` is a valid syntactical construct that always returns `true` and has no legitimate use, since the variable is discarded and that it can be replaced by a simpler expression (e.g. `true`) or optimized away (like simply using an `else` with no following `if`).

Examples of the above should be given for `is` and `switch`.
