### ISSUE TITLE
Types in XML docs not working, also 404s

### ISSUE THREAD

**Issue by bchavez** [dotnet/docs#8728]
https://docs.microsoft.com/en-us/dotnet/api/?term=System.IO.Pipelines

![chrome_2311](https://user-images.githubusercontent.com/478118/47666779-a87ee800-db61-11e8-96ab-552d2b69bc88.png)

### Also,
At this page: https://docs.microsoft.com/en-us/dotnet/api/system.io.pipelines.pipe.-ctor?view=dotnet-plat-ext-2.1#System_IO_Pipelines_Pipe__ctor_System_IO_Pipelines_PipeOptions_

Clicking on "You may also leave feedback  directly on GitHub".
![chrome_2312](https://user-images.githubusercontent.com/478118/47666793-af0d5f80-db61-11e8-9bc0-6838ef1dd0fe.png)

### Leads to:
![chrome_2313](https://user-images.githubusercontent.com/478118/47666815-bc2a4e80-db61-11e8-98fa-497ed04599ed.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69fc4a29-8e75-2e20-0713-563d859f34ec
* Version Independent ID: 1af6c385-4d38-5661-fa47-8adb9b326f54
* Content: [Pipe Constructor (System.IO.Pipelines)](https://docs.microsoft.com/en-us/dotnet/api/system.io.pipelines.pipe.-ctor?view=dotnet-plat-ext-2.1#System_IO_Pipelines_Pipe__ctor_System_IO_Pipelines_PipeOptions_)
* Content Source: [xml/System.IO.Pipelines/Pipe.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.IO.Pipelines/Pipe.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by imba-tjd** [comment]
Dup of https://github.com/MicrosoftDocs/feedback/issues/637 and https://github.com/MicrosoftDocs/feedback/issues/807
