### ISSUE TITLE
shili

### ISSUE THREAD

**Issue by LisandroSu** [dotnet/docs#8733]
@Houheshuai commented on [Mon Oct 29 2018](https://github.com/dotnet/docs.zh-cn/issues/226)

实例不多啊

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 874ea00d-6ec4-55f4-f0e3-e818d21454c7
* Version Independent ID: 98072328-af31-5bc6-9ba4-1353328d5f10
* Content: [Expression-bodied 成员（C# 编程指南）](https://docs.microsoft.com/zh-cn/dotnet/csharp/programming-guide/statements-expressions-operators/expression-bodied-members)
* Content Source: [docs/csharp/programming-guide/statements-expressions-operators/expression-bodied-members.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/csharp/programming-guide/statements-expressions-operators/expression-bodied-members.md)
* Product: **dotnet-csharp**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by LisandroSu** [comment]
Hi team,
The user says that there aren't many examples in the document.

Thanks

**Comment by rpetrusha** [comment]
In both the zh-cn and en-us versions, there is an example for each type of expression-bodied member. Closing as not repo.
