### ISSUE TITLE
Well documented!

### ISSUE THREAD

**Issue by ThiruPraveen18** [dotnet/docs#8745]
Clear info.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1571bd84-84b9-ef24-f96f-304665e22bea
* Version Independent ID: f238803f-7e31-e6b1-0d23-cebb0672de95
* Content: [Porting to .NET Core - Analyze your third-party dependencies](https://docs.microsoft.com/en-us/dotnet/core/porting/third-party-deps)
* Content Source: [docs/core/porting/third-party-deps.md](https://github.com/dotnet/docs/blob/master/docs/core/porting/third-party-deps.md)
* Product: **dotnet-core**
* GitHub Login: @cartermp
* Microsoft Alias: **mairaw**

**Comment by elgonzo** [comment]
This is not a report about an issue. Please don't produce noise and close this "report" here. Thanks!
(I am not affiliated with Microsoft in any way; i am just a GitHub user)

**Comment by ThiruPraveen18** [comment]
FYI, this is a feedback as requested by the official site
https://docs.microsoft.com/en-us/dotnet/core/porting/third-party-deps
<https://www.google.com/url?q=https://docs.microsoft.com/en-us/dotnet/core/porting/third-party-deps&sa=D&source=hangouts&ust=1540982389518000&usg=AFQjCNGfNb6cDlcohsztCAs_iIPO_N7zRg>
at
the end. The feedback section uses GitHub as the medium for the same.
Please check the details and the tags used before poking into someone's
statements.

With regards,
Praveen Thirumurugan.

**Comment by BillWagner** [comment]
Thanks for the compliments @ThiruPraveen18 We appreciate it.

@elgonzo We do use GitHub issues for positive feedback as well as reporting problems. It helps us get a more complete picture of the docs. We do close these daily. 

Closing as kudos.

**Comment by elgonzo** [comment]
My apologies. Guess i got hung-up too much on the word "issue(s)"...
