### ISSUE TITLE
Example section is now ahead of Remarks section in .NET API Browser

### ISSUE THREAD

**Issue by imba-tjd** [dotnet/docs#8748]
For example https://docs.microsoft.com/en-us/dotnet/api/system.action-1?view=netcore-2.1
I'm not sure whether this is a bug or feature. I suppose it is a bug because I remembered `Remarks` was ahead of `Example` and it has some things like `In this topic` which are designed to be in the front of the article.

**Comment by mikkelbu** [comment]
@mairaw That could also explain why I thought that the sentence was wrong in https://github.com/dotnet/dotnet-api-docs/commit/2b3c19ab4839f263a489710c840e0ff2a8fa38d3 (related to #8675). If **Remarks** came first then the removed sentence could refer to the list in the **Fields** section.

**Comment by imba-tjd** [comment]
@mikkelbu Now I think this is a feature :joy:, closing then.
