### ISSUE TITLE
Sync services are not importing

### ISSUE THREAD

**Issue by srinivaskacham** [dotnet/docs#8756]
1. It is importing async services only when I add WCF service reference to asp.net core project. I am not sure how to import sync services.
2. My WCF service returns data table, could you let me know how to convert ReponseAsDataTable from service to DataTable in asp.net core?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e89651a-5ad9-c3f9-146f-8d87b87d9e11
* Version Independent ID: 85c0e55f-abc0-3b2d-409a-06042b1f3ebb
* Content: [Microsoft WCF Web Service Reference Provider Tool](https://docs.microsoft.com/en-us/dotnet/core/additional-tools/wcf-web-service-reference-guide)
* Content Source: [docs/core/additional-tools/wcf-web-service-reference-guide.md](https://github.com/dotnet/docs/blob/master/docs/core/additional-tools/wcf-web-service-reference-guide.md)
* Product: **dotnet-core**
* GitHub Login: @mlacouture
* Microsoft Alias: **johalex**

**Comment by mlacouture** [comment]
Hi @srinivaskacham 
Thank you for your feedback.  The first question is the same as issue #654, in short, the generated code implements the async pattern which requires all calls to be async in the call stack, please refer to issue #654 for more details. 

As per your second question, given that it is not a documentation/feature question but more of a general technical question, can you report a separate issue under the [WCF GitHub repo](https://github.com/dotnet/wcf/issues/new)? You will need to provide details about the _ResponseAsDataTable_ type which seems specific for the service proxy code or provide the web service's URL or wsdl to investigate.

This issue should be resolved as no documentation update is required to be tracked with it.

**Comment by wildj79** [comment]
@mlacouture #654 doesn't seem to have anything to do with the posted question. Did you link to the wrong issue?

**Comment by mlacouture** [comment]
@wildj79, thanks for pointing out the link error, I updated the link.
