### ISSUE TITLE
Translate(zh-cn) is not exact.

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#8758]
@twenty0ne commented on [Sun Oct 28 2018](https://github.com/dotnet/dotnet-api-docs.zh-cn/issues/2)

https://docs.microsoft.com/zh-cn/dotnet/api/system.net.httpwebrequest.timeout?view=netframework-4.7.2#%E6%B3%A8%E8%A7%A3

下面的代码示例设置HttpWebRequest对象的Timeout属性。
Timeout 是发出同步请求GetResponse或者GetRequestStream后等待响应或者流的毫秒时间。 Timeout适用于整个请求和响应，不用单独对GetRequestStream和GetResponse方法调用。 如果在设定时间内未返回该资源，请求将引发一个Status属性为WebExceptionStatus.Timeout的WebException。
Timeout属性必须在调用GetRequestStream或GetResponse方法之前设置，调用GetRequestStream或GetResponse方法后更改Timeout属性不起作用。
Timeout属性不会影响异步请求BeginGetResponse或BeginGetRequestStream。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: ab5b51e1-234c-183f-74a5-64b5e485e994
* Version Independent ID: fae4d7de-f017-e9eb-1c76-0903ac951ce1
* Content: [HttpWebRequest.Timeout Property (System.Net)](https://docs.microsoft.com/zh-cn/dotnet/api/system.net.httpwebrequest.timeout?view=netframework-4.7.2#%E6%B3%A8%E8%A7%A3)
* Content Source: [xml/System.Net/HttpWebRequest.xml](https://github.com/dotnet/dotnet-api-docs.zh-cn/blob/live/xml/System.Net/HttpWebRequest.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

---

@LisandroSu commented on [Mon Oct 29 2018](https://github.com/dotnet/dotnet-api-docs.zh-cn/issues/2#issuecomment-434076495)

你好，@twenty0ne
 
感谢你的反馈。 
 
我们正在积极查看你的评论，并会很快地再次和你取得联系。 
 
深深的祝福， 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hi team
I'm moving this here since https://github.com/dotnet/dotnet-api-docs doesn't have the issues tab enabled.
The contributor is reporting an inaccuracy issue in the code:

Rought translation: 
> 
> https://docs.microsoft.com/zh-cn/dotnet/api/system.net.httpwebrequest.timeout?view=netframework-4.7.2#%E6%B3%A8%E8%A7%A3
> The following code example sets the Timeout property of the HttpWebRequest object.
> Timeout is the millisecond of waiting for a response or stream after issuing a synchronization request GetResponse or GetRequestStream. Timeout applies to the entire request and response, without the need to call the GetRequestStream and GetResponse methods separately. If the resource is not returned within the set time, the request will throw a WebException with a Status property of WebExceptionStatus.Timeout.
> The Timeout property must be set before the GetRequestStream or GetResponse method is called. Changing the Timeout property after calling the GetRequestStream or GetResponse method does not work.
> The Timeout property does not affect the asynchronous request BeginGetResponse or BeginGetRequestStream.

**Comment by imba-tjd** [comment]
I'm sure this is not a source issue but a Linguistic Suggestion.

**Comment by CeciAc** [comment]
Thanks for your clarification @imba-tjd 

@JasonCard can you please assign this to @DavidPrio so we can work on it?

**Comment by JasonCard** [comment]
@CeciAc I also do not have permission to assign GitHub Issues for this repo.
Since this issue is about zh-cn translation, can you move this issue to [https://github.com/dotnet/dotnet-api-docs.zh-cn](https://github.com/dotnet/dotnet-api-docs.zh-cn)?

**Comment by imba-tjd** [comment]
You may close this one and reopen the original one.
