### ISSUE TITLE
Bad example in the documentation of CollectionBase

### ISSUE THREAD

**Issue by Kryptos-FR** [dotnet/docs#8767]
The example is unfortunate as it demonstrates the use of the `CollectionBase`  for a value type (`Int16`) which will results in boxing.

I also think that there should a big warning section encouraging users to use `List<T>` as an alternative. In fact I am wondering: what is the purpose of this class in .net 2.0+ (i.e. with generics)? Shouldn't it be marked `[Obsolete]`?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f259eb6-5dc4-5d30-3175-d842c1eb1c49
* Version Independent ID: 9433481e-da0a-0328-2816-eac43ad810e8
* Content: [CollectionBase Class (System.Collections)](https://docs.microsoft.com/en-us/dotnet/api/system.collections.collectionbase?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk%2520System.Collections.CollectionBase%2520%253Bk%2520SolutionItemsProject%2520%253Bk%2520SolutionItemsProject%2520%253Bk%2520TargetFrameworkMoniker-.NETFramework%252CVersion%3Dv4.5.2%2520%253Bk%2520DevLang-csharp%2520%26rd%3Dtrue%233056756358380579537&view=netframework-4.7.2#21411989814081434303)
* Content Source: [xml/System.Collections/CollectionBase.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Collections/CollectionBase.xml)
* Product: **dotnet-api**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by rpetrusha** [comment]
Thanks for your feeback, @Kryptos-FR. In dotnet/dotnet-api-docs#672, we've added a note that CollectionBase is not recommended for new development. Once the PR is merged, the recommendation will appear live in the documentation. Given that the PR should address this issue, I'll close it.
