### ISSUE TITLE
What exactly the Cluster result is displaying

### ISSUE THREAD

**Issue by syedshanu** [dotnet/docs#8769]
Hi when we run the program every time we get the different Cluster ID ,Is the Cluster ID 1 means Iris-setosa ,ID 2 means Iris-versicolor, and ID 3 means Iris-virginica ,But we can see that as the Input is related to Iris-setosa in the program but in out put the result is as Cluster: 2 ,Can you kindly help me to clear about what exactly is for ClusterID and also the score result distance means what exactly the Score output is used for ,In Regression model we get the clear output,In Clustering how can we find which exact output.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 925c8fe9-ba0b-bd2c-cea0-9d851ece8825
* Version Independent ID: 41cafff5-6418-2e54-3a0d-ee29fb1fca1f
* Content: [Use ML.NET to cluster iris flowers (clustering)](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/iris-clustering)
* Content Source: [docs/machine-learning/tutorials/iris-clustering.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/iris-clustering.md)
* Product: **dotnet-ml**
* GitHub Login: @pkulikov
* Microsoft Alias: **johalex**

**Comment by syedshanu** [comment]
My question is for this Input
internal static readonly IrisData Setosa = new IrisData
{
    SepalLength = 5.1f,
    SepalWidth = 3.5f,
    PetalLength = 1.4f,
    PetalWidth = 0.2f
};
when we run we get the result as 
Cluster: 2
Distances: 0.4192338 0.0008847713 0.9660053
again we run with same input then we get  as
Cluster: 1
Distances: 0.3192338 0.0009847713 0.5660053
Why the Cluster is changing for the same inputs for different runs

**Comment by syedshanu** [comment]
It's only to distinguish different clusters
here the different clusters are  Iris-setosa,Iris-versicolor and Iris-virginica

**Comment by JRAlexander** [comment]
Closing as I believe it's been resolved. If that isn't the case, please reopen. Thanks!

**Comment by LeifRoss** [comment]
I am also wondering how we can retrieve the cluster centroids after fitting the model, preferable also containing the label.

**Comment by Lelelo1** [comment]
> I am also wondering how we can retrieve the cluster centroids after fitting the model, preferable also containing the label.

I don't think you can retrieve the cluster centroids - it is just a template for the data. The label in the case of clustering is the cluster id. The input columns is only features and does not contain a label.

**Comment by Lelelo1** [comment]
Running the clustering_iris sample I get the following `IrisPrediction` data structure:

![IrisPredictionData](https://user-images.githubusercontent.com/42244983/60337447-5ff32500-99a3-11e9-9680-eee6f8ceaa99.png)

The `PredictedLabel` (SelectedClusterId) is supposed to be `"The closest cluster's index predicted by the model."`

Reading from the distance array: Shoulden't that be index 1 - thereby `SelectedClusterId = 1`?
