### ISSUE TITLE
Document CRT dependency on Windows 7/8

### ISSUE THREAD

**Issue by richlander** [dotnet/docs#877]
.NET Core requires a CRT install on Windows 7 and 8.

Cases where you are OK:
- You install .NET Core via MSI. It installs this dependency for you.

Cases you need to install the CRT yourself:
- You 'install' .NET Core via a .zip. This can include build/CI/CD servers.
- You build the product from source
- You publish a self-contained app and deploy to a machine w/o the CRT (again, only Windows 7/8).

We need to document this so that folks know what to do and when. We need to document the steps and appropriate links for users.

/cc @blackdwarf

**Comment by gkhanna79** [comment]
This is documented at https://github.com/dotnet/core/blob/master/Documentation/prereqs.md.

**Comment by mairaw** [comment]
Isn't this what's documented at https://docs.microsoft.com/en-us/dotnet/articles/core/windows-prerequisites already?

**Comment by blackdwarf** [comment]
@mairaw @gkhanna79 we need to add a little bit more information and something similar to what @richlander outlined in the issue above is a good starting point.
