### ISSUE TITLE
How to use the table for .net core 2.1 targetting full framework 4.6.2 ?

### ISSUE THREAD

**Issue by srini1978** [dotnet/docs#8770]
Hi,

I am looking at the table and want to understand which row should I be using if I want to find out the .net standard I need to target for my current application architecture that is : A web application built on .net core 2.1 Visual studio template but with target framework as .Net framework 4.6.2 ?

**Before you open an issue**

If the issue is:

- A simple typo or similar correction, you can submit a PR. See [the contributor guide](https://docs.microsoft.com/contribute/#quick-edits-to-existing-documents) for instructions.
- A general support question, consider asking on a support forum site.
- A site design concern, create an issue at [MicrosoftDocs/Feedback](https://github.com/MicrosoftDocs/Feedback/Issues/new/choose).
- A problem completing a tutorial, compare your code with the completed sample.
- A duplicate of an open or closed issue, leave a comment on that issue.

**Issue description**

&lt;include description here&gt;

**Target framework**

Check the .NET target framework(s) being used, and include the version number(s).

- [ ] .NET Core
- [x] .NET Framework
- [ ] .NET Standard

If using the .NET Core SDK, include `dotnet --info` output. If using .NET Framework without the .NET Core SDK, include info from Visual Studio's **Help** > **About Microsoft Visual Studio** dialog.

<details>
<summary><strong>dotnet --info output</strong> or <strong>About VS info</strong></summary>

```console
<replace>
```
</details>

**Comment by srini1978** [comment]
#

**Comment by Rick-Anderson** [comment]
@scottaddie 	is the expert on that. He should respond soon.
