### ISSUE TITLE
Code snippet - Boolean value color 

### ISSUE THREAD

**Issue by andrewcahill** [dotnet/docs#8775]
Hi,

An extremely minor thing I noticed in the first code snippet on the line : 
'bool test = true;' 
the Boolean value 'true' is in green and not blue as you would see in Visual Studio

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1144c44-369d-fd62-fad9-3d07d229f04e
* Version Independent ID: c0189b06-4720-0a7e-b459-20cef88e31a5
* Content: [Basic Types - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/basic-types)
* Content Source: [docs/csharp/basic-types.md](https://github.com/dotnet/docs/blob/master/docs/csharp/basic-types.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Transferred to MicrosoftDocs/feedback#2023

Closing here.
