### ISSUE TITLE
typo on doc for HttpClientHandler.UseCookies Property

### ISSUE THREAD

**Issue by sangheestyle** [dotnet/docs#8778]
"true if the if the handler supports" should be "true if the handler supports"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf10cc28-59b2-2861-b92c-fdc3ed479ef2
* Version Independent ID: 1c517315-c10d-5fb5-731a-e2e733e630ba
* Content: [HttpClientHandler.UseCookies Property (System.Net.Http)](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclienthandler.usecookies?view=netcore-2.1#System_Net_Http_HttpClientHandler_UseCookies)
* Content Source: [xml/System.Net.Http/HttpClientHandler.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Http/HttpClientHandler.xml)
* Product: **dotnet-api**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

**Comment by karelz** [comment]
@sangheestyle thanks for report! Can you please submit PR? Should be fairly simple.

**Comment by sangheestyle** [comment]
@karelz Done. https://github.com/dotnet/dotnet-api-docs/pull/689 👍

**Comment by karelz** [comment]
Great, thanks!
