### ISSUE TITLE
Include details on operation complexity (Big O notation)

### ISSUE THREAD

**Issue by Mnaukal** [dotnet/docs#8779]
Why there is no information on operation complexity (Big O notation)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77cedae1-a256-c620-8a60-3d8b62bf21d7
* Version Independent ID: dcbe42bf-0249-fb3a-715f-3b52bb69ca9b
* Content: [SortedSet&lt;T&gt;.Min Property (System.Collections.Generic)](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.sortedset-1.min?view=netframework-4.7.2#System_Collections_Generic_SortedSet_1_Min)
* Content Source: [xml/System.Collections.Generic/SortedSet`1.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Collections.Generic/SortedSet`1.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by BillWagner** [comment]
See conversation on #5474 

The work for this is in progress. Closing as duplicate.
