### ISSUE TITLE
Include details on operation complexity (Big O notation) 

### ISSUE THREAD

**Issue by Mnaukal** [dotnet/docs#8780]
Why there is no information on operation complexity (Big O notation)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bded88bd-3dae-1648-adfc-75d1921849bb
* Version Independent ID: 1552b37f-9f02-8eda-8b2e-452218b72afc
* Content: [SortedSet&lt;T&gt;.Remove(T) Method (System.Collections.Generic)](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.sortedset-1.remove?view=netframework-4.7.2#System_Collections_Generic_SortedSet_1_Remove__0_)
* Content Source: [xml/System.Collections.Generic/SortedSet`1.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Collections.Generic/SortedSet`1.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by BillWagner** [comment]
See #5474  

Closing as duplicate.
