### ISSUE TITLE
Info about time complexity and implementation

### ISSUE THREAD

**Issue by Mnaukal** [dotnet/docs#8781]
Why there is no information about time complexity (Big O notation) of the operations? Or at least some info about implementation (is it a Red-Black tree?).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fcaf414-0048-fdd4-8ba9-a0b1983de98d
* Version Independent ID: 1f2a5277-4d18-6053-9291-048ed117981b
* Content: [SortedSet&lt;T&gt; Class (System.Collections.Generic)](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.sortedset-1?view=netframework-4.7.2)
* Content Source: [xml/System.Collections.Generic/SortedSet`1.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Collections.Generic/SortedSet`1.xml)
* Product: **dotnet-api**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by BillWagner** [comment]
Closing as duplicate of #5474 

Thanks for writing these @Mnaukal  

The referenced issue has an ongoing conversation on how we'll address this. Join the conversation there, and as PRs are created, your reviews are welcome.
