### ISSUE TITLE
Need confirmation

### ISSUE THREAD

**Issue by skasyanoff** [dotnet/docs#8785]
"Property TimeSpan that specifies how long the application has to receive a message before timing out. The default value is 10 minute." - is it 1 minute or 10 minutes? I suppose it's 1 minute.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43bec50e-e06f-a8fd-a271-ff342c8a0ab7
* Version Independent ID: e1363b5c-082a-78d4-0355-fcb53f41aefd
* Content: [Binding.ReceiveTimeout Property (System.ServiceModel.Channels)](https://docs.microsoft.com/en-us/dotnet/api/system.servicemodel.channels.binding.receivetimeout?view=netframework-4.7.2)
* Content Source: [xml/System.ServiceModel.Channels/Binding.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.ServiceModel.Channels/Binding.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by pkulikov** [comment]
@skasyanoff unlike other timeouts, [it's 10 minutes](https://referencesource.microsoft.com/#System.ServiceModel/System/ServiceModel/ServiceDefaults.cs,598f6f8a7a3853b5,references)
