### ISSUE TITLE
Add references to async/await?

### ISSUE THREAD

**Issue by bjorn-jarisch** [dotnet/docs#8799]
Starting with C# 5.0 / .NET 4.5, async/await is the new recommended approach for writing asynchronous code. Sentences such as "For both of these reasons, in the .NET Framework, TPL is the preferred API for writing multi-threaded, asynchronous, and parallel code." are no longer accurate and should be amended, e.g. by adding a reference to https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/. Strictly speaking, async/await are merely syntactic sugar in C# leveraging Task, but at least the code examples do no longer represent best practice. Also, methods such as Parallel.Invoke have been superseded by Task.WhenAll.

This criticism also applies to other areas of the "Task Parallel Library" section, e.g. the section on TPL and Traditional .NET Framework Asynchronous Programming mentioning "The .NET Framework provides the following two standard patterns for performing I/O-bound and compute-bound asynchronous operations.

I have not provided a pull request because I don't know to which extent the content should be amended, reorganized, or marked as obsolete/deprecated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 050b2b8a-8b8d-c2de-f03d-b2ebb26a9c95
* Version Independent ID: 7d23f296-9a5e-ca0a-08c3-f718d0a90d94
* Content: [Task-based Asynchronous Programming](https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/task-based-asynchronous-programming)
* Content Source: [docs/standard/parallel-programming/task-based-asynchronous-programming.md](https://github.com/dotnet/docs/blob/master/docs/standard/parallel-programming/task-based-asynchronous-programming.md)
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by mairaw** [comment]
Thanks for your feedback @maverickelementalch. @BillWagner will be working on a big review of the async/await docs and we'll be reviewing this issue as part of that.
