### ISSUE TITLE
'Building a scheduled task in ASP.NET...' linkbroken

### ISSUE THREAD

**Issue by killnine** [dotnet/docs#8805]
The link to maartenballiauw.be appears to be broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d49a03c0-a844-26eb-48a5-33a612dd3ead
* Version Independent ID: 45b409c8-f64d-da19-a2ec-b91f21696a5b
* Content: [Implement background tasks in microservices with IHostedService and the BackgroundService class](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/multi-container-microservice-net-applications/background-tasks-with-ihostedservice#implementing-ihostedservice-with-a-custom-hosted-service-class-deriving-from-the-backgroundservice-base-class)
* Content Source: [docs/standard/microservices-architecture/multi-container-microservice-net-applications/background-tasks-with-ihostedservice.md](https://github.com/dotnet/docs/blob/master/docs/standard/microservices-architecture/multi-container-microservice-net-applications/background-tasks-with-ihostedservice.md)
* Product: **dotnet**
* GitHub Login: @CESARDELATORRE
* Microsoft Alias: **wiwagn**

**Comment by mikkelbu** [comment]
It seems that the link is working again

**Comment by mairaw** [comment]
I can't repro the issue. Closing.
