### ISSUE TITLE
Outdated samples

### ISSUE THREAD

**Issue by rido-min** [dotnet/docs#8809]
The MSDN docs are outdated. 
The most recent WPF samples can be found in https://github.com/microsoft/wpf-samples 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6848ed69-e05f-3d43-4bfe-1c0120908bc9
* Version Independent ID: d556f312-d66c-617c-f4bd-65aefa02ffcf
* Content: [WPF Samples](https://docs.microsoft.com/en-us/dotnet/framework/wpf/wpf-samples)
* Content Source: [docs/framework/wpf/wpf-samples.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/wpf-samples.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
Thanks, @rido-min. We've opened #8821  to address this issue.
