### ISSUE TITLE
I can`t use the My.Settings.

### ISSUE THREAD

**Issue by ZabojczyBuldog56** [dotnet/docs#8811]
It shows the "BC30456" error code with description "Settings is not a member of My". Please, add it back again!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86c2c022-126a-c32a-a202-312400f7804b
* Version Independent ID: cb5a97b5-11b8-5933-9953-01d8d25a5a6a
* Content: [My.Settings Object (Visual Basic)](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/objects/my-settings-object)
* Content Source: [docs/visual-basic/language-reference/objects/my-settings-object.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/language-reference/objects/my-settings-object.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by KathleenDollard** [comment]
@ZabojczyBuldog56 Are you using .NET Framework or .NET Core. 

Or: If you are using Visual Studio, can you open Project Properties and tell me what the application targets.

**Comment by BillWagner** [comment]
closing after lack of response.
