### ISSUE TITLE
As the very first example, a generic with 2 parameters?

### ISSUE THREAD

**Issue by Endi24** [dotnet/docs#8813]
If someone has come here, they need guidance to understand the material first. Using such an example is very hard on new learners or those having trouble understanding delegates, like myself. Please consider going easier in the concept, maybe with just a delegate declaration as a void with no parameters first.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1dcd91a4-603a-feb9-cff2-94f1985417fc
* Version Independent ID: a86cde90-1eba-e1d5-2b42-2a3cd37f5499
* Content: [System.Delegate and the `delegate` keyword](https://docs.microsoft.com/en-us/dotnet/csharp/delegate-class#feedback)
* Content Source: [docs/csharp/delegate-class.md](https://github.com/dotnet/docs/blob/master/docs/csharp/delegate-class.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by orhunerdem** [comment]
I agree, using generics as first example creates unnecessary confusion.

**Comment by asloppyone** [comment]
Maybe the author wrote all these in some kind of sequence and assume that the reader has already read the "generics".
