### ISSUE TITLE
Convert Flight Delay Azure ML Studio example to ML.NET

### ISSUE THREAD

**Issue by jdorseywx** [dotnet/docs#8816]
It would be great to see the Flight Delay Azure ML Studio experiment converted to an ML.NET project, example is here - https://gallery.azure.ai/Experiment/Binary-Classification-Flight-delay-prediction-3

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e855e630-1a30-d138-4ac6-bfeefebf9aae
* Version Independent ID: afc0a7d1-d3c2-acf2-d4ea-d2565e22b237
* Content: [ML.NET tutorials](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/)
* Content Source: [docs/machine-learning/tutorials/index.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/index.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by JRAlexander** [comment]
Thanks, @jdorseywx! We've added this to the backlog.

**Comment by CESARDELATORRE** [comment]
@jdorseywx - Thanks for the suggestion. I added it to our ML.NET Sample apps here:
https://github.com/dotnet/machinelearning-samples/blob/master/docs/Samples-Backlog.md
However, feel free to create the sample and submit a PR for review/merge in the GitHub samples repo if you have the time. ML.NET is all about OPEN SOURCE contributions too! :)

**Comment by luisquintanilla** [comment]
Currently in machinelearning-samples backlog https://github.com/dotnet/machinelearning-samples/projects/1#card-24046517

[AB#1596631](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1596631)
