### ISSUE TITLE
Possible doc inconsistency

### ISSUE THREAD

**Issue by CoffeeUnderstands** [dotnet/docs#8818]
This article:  https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/reference-types

says that strings are reference types.   If this is so, why is the keyword ref needed in the example on https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/passing-reference-type-parameters

Also, the first example says int[] in a reference type.  What makes it a reference type, the fact that it is an array?   Are all arrays reference types?   Each page by itself seems clear, but when looked at together they create confusion. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79cbd9e8-6ef8-932b-24f7-90eff098b4f0
* Version Independent ID: 62fa8115-2692-7c9a-30ef-c4ecf92168e0
* Content: [Passing Reference-Type Parameters (C# Programming Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/passing-reference-type-parameters)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/passing-reference-type-parameters.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/passing-reference-type-parameters.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mikkelbu** [comment]
Strings are reference types. The reason for why the `ref` is needed is stated after the program

> In this example, the parameters need to be passed by reference to affect the variables in the calling program. If you remove the ref keyword from both the method header and the method call, no changes will take place in the calling program.

If you did not have the `ref`s then the result would be 
```
Inside Main, before swapping: John Smith
Inside the method: Smith John
Inside Main, after swapping: John Smith
```
as swapping around the references will not affect the calling code.

> Also, the first example says int[] in a reference type. What makes it a reference type, the fact that it is an array? Are all arrays reference types? 

Yes all arrays are reference types. The standard states (see e.g. https://www.ecma-international.org/publications/files/ECMA-ST-ARCH/ECMA-334%201st%20edition%20December%202001.pdf)

> C# supports two kinds of types: value types and reference types. Value types include simple types (e.g., char, int, and float), enum types, and struct types. Reference types include class types, interface types, delegate types, and **array types**.

**Comment by xamarin-volkan** [comment]
Hi, first of all, thank you for this doc. I have learned something new, today.

This is confusing "pass a reference-type parameter by value ". How can i pass an array by value when it is not value type? 
Then this code comes "pArray[0] = 888;  // This change affects the original element.", so the reference of the object is passed.

Next, this line makes it more complex "pArray = new int[5] {-3, -1, -2, -3, -4};   // This change is local.". So i understand that new address assignment is not possible. ref keyword makes this possible.

String is another story. I did not know, it works this way.

**Comment by mikkelbu** [comment]
> This is confusing "pass a reference-type parameter by value ". How can i pass an array by value when it is not value type?

By default, all parameters are passed by value in C#. When the type of parameter is a value type, then you are passing the actual value as a parameter, but when the type of the parameter is a reference type, you are passing (the value of) a reference rather than an actual value. 

Jon Skeet has a longer explanation in http://jonskeet.uk/csharp/parameters.html, but I think that the difference is easier to understand when using diagrams, so perhaps https://codewala.net/2016/05/22/passing-a-reference-type-using-ref-keyword/ will be more accessible.

**Comment by BillWagner** [comment]
As others have said, there are two important concepts that both use the terms 'reference' and 'value': 
- whether a type is a **reference type** or a **value type**. Structs are values types, classes are reference types.
- whether a variable is **passed by value** or **passed by reference**. In C#, by default, all arguments and return values are passed by value. The `ref`, `in` or `out` modifiers mean that a reference to the variable is passed.

Once those two concepts are clear, the rest of the explanations should make sense.

I'm closing this issue, but if you have further questions, re-open and add more context.
