### ISSUE TITLE
Explicitly say to use camelCase for local variable

### ISSUE THREAD

**Issue by mbarakatt** [dotnet/docs#8825]
As it is now, it's not obvious what one should use as a convention for local variable names. The article starts with "The PascalCasing convention, used for all identifiers except parameter names [...]" . If someone stops reading here, they would assume (rightly) that local variables are named with the PascalCase convention ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eba6b11-5703-355f-0e85-08ee7451120d
* Version Independent ID: 4691fbb3-7b6d-8c02-e372-315ca302e48e
* Content: [Capitalization Conventions](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/capitalization-conventions)
* Content Source: [docs/standard/design-guidelines/capitalization-conventions.md](https://github.com/dotnet/docs/blob/master/docs/standard/design-guidelines/capitalization-conventions.md)
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by mairaw** [comment]
The book covers coding conventions for public API design, not local or private fields.

Our team adopted the convention of camelCase for such cases.
