### ISSUE TITLE
Leading indentation in csharp code snippet files not consistent

### ISSUE THREAD

**Issue by danielchalmers** [dotnet/docs#8835]
The leading indentation in `*/codesnippet/*/*` isn't consistent.

Some have 0 spaces ([[a]](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/arrays/codesnippet/CSharp/object-and-collection-initializers_7.cs)), some 4 ([[a]](https://github.com/dotnet/docs/blob/f94de4e8a12244f9e4226673fa6471169cf82716/docs/csharp/language-reference/operators/codesnippet/CSharp/equality-comparison-operator_1.cs), [[b]](https://github.com/dotnet/docs/blob/f94de4e8a12244f9e4226673fa6471169cf82716/docs/csharp/programming-guide/arrays/codesnippet/CSharp/how-to-store-the-results-of-a-query-in-memory_1.cs)), some 8 ([[a]](https://github.com/dotnet/docs/blob/f94de4e8a12244f9e4226673fa6471169cf82716/docs/csharp/language-reference/operators/codesnippet/CSharp/member-access-operator_2.cs), [[b]](https://github.com/dotnet/docs/blob/f94de4e8a12244f9e4226673fa6471169cf82716/docs/csharp/programming-guide/arrays/codesnippet/CSharp/jagged-arrays_1.cs), [[c]](https://github.com/dotnet/docs/blob/f94de4e8a12244f9e4226673fa6471169cf82716/docs/csharp/programming-guide/arrays/codesnippet/CSharp/multidimensional-arrays_1.cs)), some even more ([[a]](https://github.com/dotnet/docs/blob/f94de4e8a12244f9e4226673fa6471169cf82716/docs/csharp/language-reference/keywords/codesnippet/CSharp/implicitly-typed-local-variables_3.cs), [[b]](https://github.com/dotnet/docs/blob/f94de4e8a12244f9e4226673fa6471169cf82716/docs/csharp/programming-guide/arrays/codesnippet/CSharp/anonymous-functions_1.cs), [[c]](https://github.com/dotnet/docs/blob/f94de4e8a12244f9e4226673fa6471169cf82716/docs/csharp/programming-guide/arrays/codesnippet/CSharp/how-to-handle-null-values-in-query-expressions_2.cs)). Seems like most inline snippets ([[a]](https://raw.githubusercontent.com/dotnet/docs/f94de4e8a12244f9e4226673fa6471169cf82716/docs/csharp/expression-classes.md), [[b]](https://raw.githubusercontent.com/dotnet/docs/f94de4e8a12244f9e4226673fa6471169cf82716/docs/csharp/expression-trees-translating.md), [[c]](https://raw.githubusercontent.com/dotnet/docs/f94de4e8a12244f9e4226673fa6471169cf82716/docs/csharp/tutorials/working-with-linq.md)) have **no** leading indentation

Not a big issue because [docs.microsoft.com](http://docs.microsoft.com) trims it but I figure it's worth tracking.

**Comment by tdykstra** [comment]
Thanks for contacting us. Given that the site trims the leading indentation, this isn't high enough priority for us to devote resources to fixing, so we're closing the issue.
