### ISSUE TITLE
Firstname and Lastname need to switch places

### ISSUE THREAD

**Issue by EvertKuijpers** [dotnet/docs#8837]
In "How to: Join Content from Dissimilar Files (LINQ) (Visual Basic)" the first field is the lastname and the second field is the firstname of each student.
Therefore the split names are in wrong order.
The line
    .FirstName = splitName(0), .LastName = splitName(1), .ID = splitName(2),
should change to
    .FirstName = splitName(1), .LastName = splitName(0), .ID = splitName(2),
.
After that the output of both subroutines will be the same, and read as follows:
    ' Output:
    ' The average score of Svetlana Omelchenko is 82,5
    ' The average score of Claire O'Donnell is 72,25
    ' The average score of Sven Mortensen is 84,5
    ' The average score of Cesar Garcia is 88,25
    ' The average score of Debra Garcia is 67
    ' The average score of Fadi Fakhouri is 92,25
    ' The average score of Hanying Feng is 88
    ' The average score of Hugo Garcia is 85,75
    ' The average score of Lance Tucker is 81,75
    ' The average score of Terry Adams is 85,25
    ' The average score of Eugene Zabokritski is 83
    ' The average score of Michael Tucker is 92

Greets, Evert Kuijpers from Tilburg in The Netherlands

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c848eba-3709-952f-ee39-bd8e022fda88
* Version Independent ID: 6b1b2cea-255d-6c86-038c-9219deaae65b
* Content: [How to: Populate Object Collections from Multiple Sources (LINQ) (Visual Basic)](https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/concepts/linq/how-to-populate-object-collections-from-multiple-sources-linq)
* Content Source: [docs/visual-basic/programming-guide/concepts/linq/how-to-populate-object-collections-from-multiple-sources-linq.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/programming-guide/concepts/linq/how-to-populate-object-collections-from-multiple-sources-linq.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by rpetrusha** [comment]
Could you take a look at my comments in #8888, @KathleenDollard? Once you address them, it will be ready to merge.
