### ISSUE TITLE
The output is not as described

### ISSUE THREAD

**Issue by EvertKuijpers** [dotnet/docs#8841]
The output I get begins with
Merge two spreadsheets:
Omelchenko,Svetlana,111, 97, 92, 81
O'Donnell,Claire,112, 75, 84, 91
and should begin with
Merge two spreadsheets:
Omelchenko, 97, 92, 81, 60
O'Donnell, 75, 84, 91, 39
.
I conclude that the firstname and the student ID have been added and that the grades for the fourth exam are missing.

To my opininon the lines
    Select n(0) & "," & n(1) & "," & n2(0) & "," & n2(1) & "," &  
      n2(2) & "," & n2(3)  
need to be replaced by the lines
    Select n(0) & "," & n2(1) & "," & n2(2) & "," &
      n2(3) & "," & n2(4)
in order to get the described output.

Greets, Evert Kuijpers from Tilburg in The Netherlands

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 776aadf4-4af5-753d-8ce9-ca5dbe3681f4
* Version Independent ID: 4d9cb98b-c8a7-6e62-d0a0-a3247c627347
* Content: [How to: Join Content from Dissimilar Files (LINQ) (Visual Basic)](https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/concepts/linq/how-to-join-content-from-dissimilar-files-linq)
* Content Source: [docs/visual-basic/programming-guide/concepts/linq/how-to-join-content-from-dissimilar-files-linq.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/programming-guide/concepts/linq/how-to-join-content-from-dissimilar-files-linq.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by KathleenDollard** [comment]
Thank you, 

I've submitted a Pull Request to change this. 

Our docs are OSS. This means you can edit on GitHub, it will create a fork with your ID and you can submit a Pull Request we will review.

**Comment by mairaw** [comment]
This was fixed by PR #9388
