### ISSUE TITLE
How to load sos.dll into intermediate window VS 2017?

### ISSUE THREAD

**Issue by vchirikov** [dotnet/docs#8847]
How to load sos.dll in intermediate window in VS 2017? 
I installed wdk, enable mixed mode, native code debugging, nothing helps.
It's possible to use sos from intermediate window in VS 2017? (or only in older VS?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e01c075-7a07-5850-d462-706675b545f1
* Version Independent ID: 0dd6c661-01a1-592c-ea53-8427412ff8d0
* Content: [SOS.dll (SOS Debugging Extension)](https://docs.microsoft.com/en-us/dotnet/framework/tools/sos-dll-sos-debugging-extension)
* Content Source: [docs/framework/tools/sos-dll-sos-debugging-extension.md](https://github.com/dotnet/docs/blob/master/docs/framework/tools/sos-dll-sos-debugging-extension.md)
* Product: **dotnet-framework**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by noahfalk** [comment]
Adding @gregg-miskelly and @mikem8361 

My understanding is that VS 2017 does not support using SOS in the intermediate window, only earlier VS versions support it.

**Comment by noahfalk** [comment]
If it helps you can still use SOS from windbg as always, and you can non-invasively attach windbg to the same debuggee that VS is debugging. If you do that you have to detach windbg before debuggee execution can resume.

**Comment by gregg-miskelly** [comment]
Noah is correct
