### ISSUE TITLE
Confusing

### ISSUE THREAD

**Issue by yuriry** [dotnet/docs#8848]
lister.Progress -= onProgress;
Listener listens to events, but the sample names the event emitter a listener.  onProgress should be a listener.

PS. I misread - it's a lister, not a listener.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e2507bc-e567-23f9-aeb9-f7529baa7032
* Version Independent ID: c42718d0-15b4-a87f-4353-e15656686889
* Content: [Introduction to Events](https://docs.microsoft.com/en-us/dotnet/csharp/events-overview)
* Content Source: [docs/csharp/events-overview.md](https://github.com/dotnet/docs/blob/master/docs/csharp/events-overview.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Thraka** [comment]
Actually, this is the second bug opened related to that name. I think it's confusing and should be changed. Further, I think that the code should not define a lambda to assign the event handler to. This is the "introduction to events" and it should really display creating a method to assign to the event.

@BillWagner Do you agree? I can change this

**Comment by Thraka** [comment]
Related to #5926

**Comment by Thraka** [comment]
1st PR to fix the issue is still open.
