### ISSUE TITLE
Compiling error on the first example

### ISSUE THREAD

**Issue by phuctv95** [dotnet/docs#8849]
I got a compiling error on the line `return new string(s.Reverse().ToArray());` of the first example:

     Program.cs(10,33): error CS1061: 'string' does not contain a definition for 'Reverse' and no accessible extension method 'Reverse' accepting a first argument of type 'string' could be found (are you missing a using directive or an assemblyreference?)

Edit: I'm using .NET Core 2.1.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36115425-3181-1363-dcbd-42e48db8613c
* Version Independent ID: 57ca5426-2ae3-7260-cef9-e92dc9d4e856
* Content: [Delegates and lambdas](https://docs.microsoft.com/en-us/dotnet/standard/delegates-lambdas)
* Content Source: [docs/standard/delegates-lambdas.md](https://github.com/dotnet/docs/blob/master/docs/standard/delegates-lambdas.md)
* Product: **dotnet**
* GitHub Login: @richlander
* Microsoft Alias: **wiwagn**

**Comment by pkulikov** [comment]
@phuctv95 thanks for reporting the issue. All code examples have missed necessary using statements. For example, the error you've reported should be fixed by adding the `using System.Linq;` line to the top of the file. 

#8851 adds necessary usings.
