### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by volkan-yazilim** [dotnet/docs#8854]
I believe there is a typo in these sentences.

"By default these accessors have the same visibility, or access level: that of the "//** no need comma or :

"Also, the accessibility level of both the property/indexer, an" //** no need for second comma

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 865bd72b-8d26-ec50-4fc0-e3754a00c00c
* Version Independent ID: 5607825a-87ff-1138-3743-0f1fd8408b16
* Content: [Restricting Accessor Accessibility (C# Programming Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/restricting-accessor-accessibility#see-also)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/restricting-accessor-accessibility.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/restricting-accessor-accessibility.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
Thank you for your feedback @xamarin-volkan. Would you like to submit a PR with your suggestions?
For information on how to do this, see https://docs.microsoft.com/en-us/contribute/#quick-edits-to-existing-documents.
