### ISSUE TITLE
Just a small improvement

### ISSUE THREAD

**Issue by PerttuLaurinen** [dotnet/docs#8857]
In step 2, it should read: dotnet new, rather than dotnet new console.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cc2e9c2-f333-f6a1-064e-790d950b684c
* Version Independent ID: 25a4c9b9-2808-e296-df03-5837000dcbad
* Content: [Get started with C# and Visual Studio Code - C# Guide](https://docs.microsoft.com/en-us/dotnet/core/tutorials/with-visual-studio-code)
* Content Source: [docs/core/tutorials/with-visual-studio-code.md](https://github.com/dotnet/docs/blob/master/docs/core/tutorials/with-visual-studio-code.md)
* Product: **dotnet-core**
* GitHub Login: @kendrahavens
* Microsoft Alias: **mairaw**

**Comment by mikkelbu** [comment]
@PerttuLaurinen On dotnet version 2.1.101 I get the help text if I just write `dotnet new`.

```
F:\TEMP\DotNet $ dotnet new
Getting ready...
Usage: new [options]

Options:
  -h, --help          Displays help for this command.
  -l, --list          Lists templates containing the specified name. If no name is specified, lists all templates.
  -n, --name          The name for the output being created. If no name is specified, the name of the current directory
is used.
  -o, --output        Location to place the generated output.
  -i, --install       Installs a source or a template pack.
  -u, --uninstall     Uninstalls a source or a template pack.
  --type              Filters templates based on available types. Predefined values are "project", "item" or "other".
  --force             Forces content to be generated even if it would change existing files.
  -lang, --language   Specifies the language of the template to create.


Templates                                         Short Name       Language          Tags
--------------------------------------------------------------------------------------------------------
Console Application                               console          [C#], F#, VB      Common/Console
Class library                                     classlib         [C#], F#, VB      Common/Library
Unit Test Project                                 mstest           [C#], F#, VB      Test/MSTest
xUnit Test Project                                xunit            [C#], F#, VB      Test/xUnit
ASP.NET Core Empty                                web              [C#], F#          Web/Empty
ASP.NET Core Web App (Model-View-Controller)      mvc              [C#], F#          Web/MVC
....
```

**Comment by kendrahavens** [comment]
@mikkelbu Is correct. In newer version of .NET Core `dotnet new` will print out the templating options instead of assuming you want to create a console class. You need to specify console.

@PerttuLaurinen Let us know if there is any documentation still documenting the old behavior. Some may still need an update. Thank you for helping improve docs!

**Comment by Thraka** [comment]
I'm going to close this as the current documentation is correct. Thank you for the feedback!
