### ISSUE TITLE
pack argument accepts project or solution

### ISSUE THREAD

**Issue by zivkan** [dotnet/docs#8860]
[This stackoverflow question has a comment](https://stackoverflow.com/a/52935200/2843065) from a customer who was confused by the docs because it claims the argument only accepts a project file, but testing with a solution file, it packs all the projects in the solution (at least in my simple 2 classlib project solution). I think it would be good if the docs (and `dotnet pack -h`) were updated to mention that the argument could also be a sln file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7e805a3-f2ec-b05a-d5c8-29f7a8c16a5f
* Version Independent ID: 4257ec12-df6f-ec52-aad3-012e5fce8133
* Content: [dotnet pack command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-pack?tabs=netcore2x)
* Content Source: [docs/core/tools/dotnet-pack.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-pack.md)
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mkvalluri** [comment]
And this issue still exists

**Comment by mairaw** [comment]
Thanks for the feedback @zivkan and apologies on the delay on getting this triaged. I'm going through the issues for dotnet pack as I'm making some updates to it at the moment. @KathleenDollard @livarcocc `dotnet pack --help` also states that only projects are accepted. So should I open a bug in the CLI repo too for this?

**Comment by mairaw** [comment]
I just confirmed it works with solution files as well, so I'm adding that to the docs.

**Comment by KathleenDollard** [comment]
And please open an issue on dotnet/cli

**Comment by mairaw** [comment]
Ok. I've actually opened a PR for that @KathleenDollard https://github.com/dotnet/cli/pull/12331

**Comment by IanKemp** [comment]
It would also be very helpful to explain what `dotnet pack <sln>` does behind the scenes (i.e. how it figures out what to pack), since `nuget pack` doesn't support packing a solution file.
