### ISSUE TITLE
 for initializer

### ISSUE THREAD

**Issue by not1two** [dotnet/docs#8861]
In the section "Work with the for loop" should it say "int counter = 0;" instead of "for counter = 0;"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77dec100-463d-f684-03b6-25f511d1d18f
* Version Independent ID: 27921da6-71b0-6dfc-2824-c84844152d8e
* Content: [Branches and loops - Introduction to C# interactive tutorial](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/intro-to-csharp/branches-and-loops?tutorial-step=7)
* Content Source: [docs/csharp/tutorials/intro-to-csharp/branches-and-loops.yml](https://github.com/dotnet/docs/blob/live/docs/csharp/tutorials/intro-to-csharp/branches-and-loops.yml)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for pointing this out @not1two 

I'm making edits to those files now, so I'll address this in the same PR.
