### ISSUE TITLE
Converting

### ISSUE THREAD

**Issue by PeterPann23** [dotnet/docs#8862]
I would be interested to see how one could convert an array&lt;T&gt; to a Vector&lt;T&gt;, as I am not finding any documentation on this

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8474dbad-abde-5b22-0446-4aa54f1ca8f9
* Version Independent ID: 014178fc-9b56-5142-e19c-f1c6d9a969ad
* Content: [Numerics in .NET](https://docs.microsoft.com/en-us/dotnet/standard/numerics)
* Content Source: [docs/standard/numerics.md](https://github.com/dotnet/docs/blob/master/docs/standard/numerics.md)
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by rs38** [comment]
what do you mean?
@PeterPann23  Taking an Array T[] is one of the standard constructor of  Vector<T>
https://docs.microsoft.com/en-us/dotnet/api/system.numerics.vector-1.-ctor?view=netstandard-2.1#System_Numerics_Vector_1__ctor__0___

**Comment by PeterPann23** [comment]
never mind, it's in the constructor
