### ISSUE TITLE
Unexpected visual style of the alert boxes

### ISSUE THREAD

**Issue by Powerhelmsman** [dotnet/docs#8867]
This issues was created by @pkulikov from https://github.com/MicrosoftDocs/feedback/issues/830

Colors and header icons of the alert boxes (for example, warnings and notes) are not as expected.
Expected visuals are presented at the dotnet/docs doc template:
![image](https://user-images.githubusercontent.com/33136632/48012873-d9b66580-e0d7-11e8-8cbc-c613362c19da.png)

Reality is different:
Warnings do not stand out (related issue: dotnet/docs#8798) (and no icon at the header):
https://docs.microsoft.com/en-us/dotnet/api/system.net.mail.smtpclient
Important messages are in calming blue-ish color (and have an "i" icon at the header):
https://docs.microsoft.com/en-us/dotnet/standard/threading/overview-of-synchronization-primitives
While, mere notes really stand out (and have an exclamation mark icon at the header):
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/bitwise-complement-operator
Tips are as expected:
https://docs.microsoft.com/en-us/dotnet/framework/wcf/samples/
As far as I remember, the change has happened during the past two weeks.
However, if it's a new style, the dotnet/docs template doc should be updated with new visuals. /cc @mairaw @rpetrusha

**Comment by mairaw** [comment]
My goal is to eliminate https://github.com/dotnet/docs/blob/master/styleguide/template.md in favor of https://docs.microsoft.com/en-us/contribute/markdown-reference. I need to make sure the new page is covering everything we need.
