### ISSUE TITLE
Confusing

### ISSUE THREAD

**Issue by regal60740** [dotnet/docs#8878]
I am at "Building the application" and I am not getting anywhere fast. I created the build.ps1 script, but when I try to run it, I get a message saying the project doesn't exist?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8136668-5c80-9640-ed08-bdda6418fa19
* Version Independent ID: e07d8d3c-7566-9652-892d-e6cc711078d8
* Content: [Running Console applications in Docker](https://docs.microsoft.com/en-us/dotnet/framework/docker/console)
* Content Source: [docs/framework/docker/console.md](https://github.com/dotnet/docs/blob/master/docs/framework/docker/console.md)
* Product: **dotnet-framework**
* GitHub Login: @spboyer
* Microsoft Alias: **dotnetcontent**

**Comment by zscn** [comment]
The project can be found here: [ConsoleRandomAnswerGenerator](https://github.com/dotnet/samples/tree/master/framework/docker/ConsoleRandomAnswerGenerator), I believe the doc team missed the link inside this page.

**Comment by zscn** [comment]
This has been fixed by issue #11506 , and can be closed now.
