### ISSUE TITLE
Is there a list of all of Int32s  operator overloads

### ISSUE THREAD

**Issue by YairHalberstadt** [dotnet/docs#8894]
I'm looking for a list of all of Int32s operator overloads. Does such a list exist? Should it exist?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94025c26-9253-eeb2-133a-b565eca8ac88
* Version Independent ID: bfaa10c9-fb5f-8c3a-dc6e-8f5c309020b1
* Content: [Int32 Struct (System)](https://docs.microsoft.com/en-us/dotnet/api/system.int32?view=netframework-4.7.2#feedback)
* Content Source: [xml/System/Int32.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System/Int32.xml)
* Product: **dotnet-api**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by elgonzo** [comment]
Yes, there is. You just looked in the wrong place ;-)
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/statements-expressions-operators/overloadable-operators

**Comment by YairHalberstadt** [comment]
Thanks
I meant the list of all operators that Int32 overloads, not all overloadable operators.

For example Int32 is implicitly convertible to long, but explicitly convertible to short. It's defines +(int, int) but not +(int, long).
etc.

**Comment by elgonzo** [comment]
I am not sure such a list exists somewhere, but there is a list of (all) operators here: 
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/index

Note that that list does not spell out explicitely whether a particular operator is applicable to some integral data type. However, i would say that if you know what the function/purpose of an operator is then you would know whether it can be used with integral data types. On the other hand, if you don't know if what a particulary operator does, then the documentation saying "this xyz operator can be used with Int32" won't help understanding that operator, either. Just my 2c...

**Comment by elgonzo** [comment]
> For example Int32 is implicitly convertible to long, but explicitly convertible to short. It's defines +(int, int) but not +(int, long).

Why would you think that an +(int, long) overload makes sense? After all, you said yourself, an Int32 is implicitly convertible to long. That scenario thus would be covered by the long operator +(long, long)...

**Comment by YairHalberstadt** [comment]
@elgonzo
I agree. I'm just asking if there is a list of all operators that Int32 actually overloads, not whether it should or shouldn't.

The context is I'm implementing a custom numerical type, and it will help me make sure I've overloaded all operators correctly if I can compare it to the overloads int overloads. I could work them all out for myself, but it could save me a bit of work.

Thanks for your help though :-)

**Comment by elgonzo** [comment]
Okay, i see what you are trying to do.

First, you can only create user-defined operators in your type from overloadable operators. You don't need to look at Int32 to figure out which operators can be overloaded by your custom type per-se , just look at the list of operators that are overloadable (it also lists non-overloadable operators with an explanation to which overloadable operators will be used to achieve the functionality of certain non-overloadable operators) : https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/statements-expressions-operators/overloadable-operators

With regard to my previous comment, if you want/need to know how C# resolves an operator and how it chooses which (possible) implicit conversion, look at the C# language spec. under "Numeric promotions": https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/expressions#numeric-promotions


1. What operators are possible with numeric types (overloadable or not). See the

**Comment by elgonzo** [comment]
Okay, i guess i see what you are trying to do.

First, you can only create user-defined operators in your type from overloadable operators. You don't need to look at Int32 to figure out which operators can be overloaded by your custom type per-se , just look at the list of operators that are overloadable (it also lists non-overloadable operators with an explanation to which overloadable operators will be used to achieve the functionality of certain non-overloadable operators) : https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/statements-expressions-operators/overloadable-operators

With regard to my previous comment, if you want/need to know how C# resolves an operator and how it chooses which (possible) implicit conversion, look at the C# language spec. under "Numeric promotions": https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/expressions#numeric-promotions

**Comment by BillWagner** [comment]
@YairHalberstadt These operators are specified by the language, not the `int` type. The information you want is in the C# Language spec:

- [Implicit numeric conversions](https://docs.microsoft.com/dotnet/csharp/language-reference/language-specification/conversions#implicit-numeric-conversions)
- [Explicit numeric conversions](https://docs.microsoft.com/dotnet/csharp/language-reference/language-specification/conversions#explicit-numeric-conversions)

I'll close this issue, as the needed information is provided.
