### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by ZakroKhitalishvili** [dotnet/docs#8897]
I think a modifier of the class should be public in order to have an entry point accessible

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f73bc048-976f-8951-292e-4f98163be9c9
* Version Independent ID: b245217a-d35a-8883-8d55-e73405ae4d8c
* Content: [How to: Determine an Assembly's Fully Qualified Name](https://docs.microsoft.com/en-us/dotnet/framework/app-domains/how-to-determine-assembly-fully-qualified-name#example)
* Content Source: [docs/framework/app-domains/how-to-determine-assembly-fully-qualified-name.md](https://github.com/dotnet/docs/blob/master/docs/framework/app-domains/how-to-determine-assembly-fully-qualified-name.md)
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by elgonzo** [comment]
Why would you think that?
(If you create console project in VS, the `Program` class created by default by the project wizard does not put a `public` modifier on the class, either. Yet, there is no problem for the compiler and program to find and invoke the entry point/main method...)

**Comment by elgonzo** [comment]
Note that the documentation mentiones at several occassions that the accessiblity of the method used as entry point doesn't matter. For example:

https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/basic-concepts

https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/main-and-command-args/

**Comment by ZakroKhitalishvili** [comment]
I thought that It is supposed to support class without a modifier but when I tested this code on dotnetfiddle.net I got a message : 

> Fatal Error: Public Main() method is required in a public class

That made me to think something was wrong with the example.

You are right, it works in Visual Studio. It seems dotnetfiddle compiler has an issue.

**Comment by elgonzo** [comment]
FYI: dotnetfiddle lists this as a restriction on its knowledge base/support page: "_In Console Project Type - Main function must be public inside public class_". Quite interesting is the reason given for this restriction: "_[...] to prevent malicious code_". Don't ask me how this restriction could help preventing malicious code on dotnetfiddle... (o.O)?

**Comment by mairaw** [comment]
Given that this is a restriction of dotnetfiddle, I'll just close this issue.
