### ISSUE TITLE
Do you mean `StreamWriter`?

### ISSUE THREAD

**Issue by phuctv95** [dotnet/docs#8898]
At the line:

> `StreamReader` - An API for reading files (`StringWriter`) Can be used to write files.

Which API does used for write files? `StreamReader` or `StringWriter` can do that? Or you mean `StreamWriter`?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5cb1365-bb1f-b869-84db-8400ffb223d2
* Version Independent ID: 6c4e9725-7689-b6a0-777d-e76e7999c138
* Content: [Framework Libraries](https://docs.microsoft.com/en-us/dotnet/standard/framework-libraries)
* Content Source: [docs/standard/framework-libraries.md](https://github.com/dotnet/docs/blob/master/docs/standard/framework-libraries.md)
* Product: **dotnet**
* GitHub Login: @richlander
* Microsoft Alias: **ronpet**

**Comment by mairaw** [comment]
Reopening since that sentence is slightly confusing without punctuation.
