### ISSUE TITLE
We don't actively promote 3rd party packages on our official docs

### ISSUE THREAD

**Issue by DalSoft** [dotnet/docs#8913]
In reference to https://github.com/dotnet/docs/issues/6280

Sorry this isn't true and disappointing. On reading the .NET Core docs today - I can see that you actively  promote these open source third party packages in the official docs:

* [Swashbuckle](https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-2.1&tabs=visual-studio)

* [NSwag](https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-nswag?view=aspnetcore-2.1&tabs=visual-studio%2Cvisual-studio-xml)

* [Gulp](https://docs.microsoft.com/en-us/aspnet/core/client-side/using-gulp?view=aspnetcore-2.1)

*  [Grunt](https://docs.microsoft.com/en-us/aspnet/core/client-side/using-grunt?view=aspnetcore-2.1)

* [Bower](https://docs.microsoft.com/en-us/aspnet/core/client-side/bower?view=aspnetcore-2.1)

* [Npgsql.EntityFrameworkCore.PostgreSQ](https://docs.microsoft.com/en-us/ef/core/providers/)

* [Pomelo.EntityFrameworkCore.MySql](https://docs.microsoft.com/en-us/ef/core/providers/l)

Your even promoting paid for packages, which is disappointing given there are alternatives.
[Devart.Data.Oracle.EFCore](https://docs.microsoft.com/en-us/ef/core/providers/)

It's upsetting that you don't equally support other people that contribute to the .NET community by spending their time creating packages. This includes MS blogs that only seem to promote projects coming from the same groups of people. 

In an effort to be fair and impartial most companies have an open policy for being listed or at least acknowledged. What is the MS criteria to be supported / promoted in the official docs / blogs, so that I can change my projects to meet the requirements. Or is it just the case that the same groups and people will always be supported no room for new contributions?

_Originally posted by @DalSoft in https://github.com/dotnet/docs/issue_comments#issuecomment-436577183_

**Comment by rpetrusha** [comment]
@DalSoft, you can open a PR to add the DalSoft project to [/NET Open Source Developer Projects](https://github.com/Microsoft/dotnet/blob/master/dotnet-developer-projects.md).

**Comment by DalSoft** [comment]
Thanks @rpetrusha I'll do that

**Comment by tdykstra** [comment]
It appears that this issue has been addressed. Closing.  

Feel free to reopen if further discussion is needed.
