### ISSUE TITLE
Search not finding documents

### ISSUE THREAD

**Issue by ptoye** [dotnet/docs#8915]
[I was trying to find out a detail about VB.Net structures, so went to the main VB page, typed "structures" into the search box, and found no relevant matches - only for F#! There's perfectly good page called "structures" at https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/language-features/data-types/structures  I'd attach a screen shot but it doesn't work.

]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 675b0c08-6b7f-b01b-4b1a-eda4618d6430
* Version Independent ID: db682cf0-c8e9-a054-7b24-3cc19aaf0a98
* Content: [Visual Basic](https://docs.microsoft.com/en-us/dotnet/visual-basic/index)
* Content Source: [docs/visual-basic/index.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/index.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by KathleenDollard** [comment]
@rpetrusha and @mairaw This is an issue with tagging or something. The page exists here:

https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/language-features/data-types/structures

but does not show up when you type either "structure" or "structures" in the help filter.

**Comment by rpetrusha** [comment]
@KathleenDollard, it surfaces in search using Goggle and Bing as well as in the search text box on docs., It only does not appear when using the filter. I'll open a PR to add some metadata, but its metadata is already comparable to that for C# and F#, which do surface when using the filter. 

@mairaw and @BillWagner do you have any sense of what the problem might be?

**Comment by pkulikov** [comment]
@ptoye @KathleenDollard @rpetrusha  when you talk about search field/help filter, do you mean the one above the TOC:
![image](https://user-images.githubusercontent.com/15279990/48212768-96305580-e37c-11e8-8e21-4d98ae9a9785.png)

To my impression, this filter box is only applied to the currently displayed TOC. The article in question is not in the main TOC, so it doesn't appear during the search.

**Comment by rpetrusha** [comment]
Thanks for pointing that out, @pkulikov. I hadn't thought to really look at how the Structures topic appears in the TOC. And that indeed is why it doesn't appear -- the data types section has a separate TOC. I'll close my existing PR to add metadata to the structures topic and open a new one to comsolidate the date types topics into the main TOC.

**Comment by rpetrusha** [comment]
I've opened #8940 to incorporate the child TOC into the top-level TOC.
