### ISSUE TITLE
Typo!

### ISSUE THREAD

**Issue by ptoye** [dotnet/docs#8919]
['interred' -> 'inferred' (or should tuples be buried?)]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 936fd464-c238-3352-c260-da97c3deaeef
* Version Independent ID: 876d507e-a0d9-c36e-2647-7caa5f685861
* Content: [Tuples in Visual Basic](https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/language-features/data-types/tuples)
* Content Source: [docs/visual-basic/programming-guide/language-features/data-types/tuples.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/programming-guide/language-features/data-types/tuples.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by pkulikov** [comment]
@ptoye thanks for reporting it! Learnt a new word today :).
