### ISSUE TITLE
vb.net memuat hak akses dengan medaftarkan form2 aplikasi

### ISSUE THREAD

**Issue by yudiaugust** [dotnet/docs#8921]
bagaimana cara pemanggilannya,
table saya nik,access,form dari table hakakses

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f1c3b56-e69e-a045-0cd8-f964cb2cdaf8
* Version Independent ID: 43e53c60-1991-e151-56bb-9f61328286d6
* Content: [Public member '&lt;membername&gt;' on type '&lt;typename&gt;' not found](https://docs.microsoft.com/en-us/dotnet/visual-basic/misc/public-member-membername-on-type-typename-not-found)
* Content Source: [docs/visual-basic/misc/public-member-membername-on-type-typename-not-found.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/misc/public-member-membername-on-type-typename-not-found.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by mairaw** [comment]
I can't understand this issue even with the help of Google translator. Closing.
