### ISSUE TITLE
Memory<T>.Pin doc needs to be filled out

### ISSUE THREAD

**Issue by eerhardt** [dotnet/docs#8925]
We should have a summary, remarks and examples on how to use this API. What am I supposed to do with the MemoryHandle? What are the best practices?  etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c0c5532-ec7e-21f2-9e33-8b1c89073abf
* Version Independent ID: 851ecd39-f742-6f2a-a2d9-c1a7f1dd0f82
* Content: [Memory&lt;T&gt;.Pin Method (System)](https://docs.microsoft.com/en-us/dotnet/api/system.memory-1.pin?view=netcore-2.1)
* Content Source: [xml/System/Memory`1.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System/Memory`1.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by Thraka** [comment]
@eerhardt  Hi! Thank you for opening this issue. We just shipped the docs for `Memory<T>` and `IMemoryOwner<T>` in PR dotnet/dotnet-api-docs#548 which should be published today.

I'm going to close this issue. Thanks again.
