### ISSUE TITLE
MemoryPool<T> has a poor description

### ISSUE THREAD

**Issue by levarato** [dotnet/docs#8931]
MemoryPool&lt;T&gt; Class has a poor description, compared to the other .net documentations

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e4e395e-edad-3131-711c-f750ba52ec65
* Version Independent ID: 31232975-60aa-1e0d-d6d9-a5f13e2a198a
* Content: [MemoryPool&lt;T&gt; Class (System.Buffers)](https://docs.microsoft.com/en-us/dotnet/api/system.buffers.memorypool-1?view=netcore-2.1#feedback)
* Content Source: [xml/System.Buffers/MemoryPool`1.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Buffers/MemoryPool`1.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by Thraka** [comment]
@levarato Hi! Thank you for opening this issue. We just shipped the docs for `Memory<T>` and `IMemoryOwner<T>` in PR dotnet/dotnet-api-docs#548

There is an open issue related to documenting MemoryPool at #8074

I'm going to close this issue. Thanks again.
