### ISSUE TITLE
Just now i added  new  registry keys 

### ISSUE THREAD

**Issue by RAJU2529** [dotnet/docs#8933]
On Windows 10 1809 64bit, I added new registry according to your article.

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\.NETFramework\policy\APTCA\aptcagac]
"APTCA_FLAG"=dword:00000001

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\.NETFramework\Windows Presentation Foundation\Features]
"XBAPDisallow"=dword:00000000
"LooseXamlDisallow"=dword:00000000
"WebBrowserDisallow"=dword:00000000
"MediaAudioDisallow"=dword:00000000
"MediaImageDisallow"=dword:00000000
"MediaVideoDisallow"=dword:00000000
"ScriptInteropDisallow"=dword:00000000

Should i keep these keys or else delete them, Do i get any security problems while browsing on IE11  and on EDGE  browser keeping this setting.

Thanks for your article 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc421c44-f66c-6e10-3413-00d6fee7ce81
* Version Independent ID: 6c375715-042f-f4e9-a0db-580b3df37320
* Content: [Security (WPF)](https://docs.microsoft.com/en-us/dotnet/framework/wpf/security-wpf#SafeTopLevelNavigation)
* Content Source: [docs/framework/wpf/security-wpf.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/security-wpf.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by tdykstra** [comment]
@RAJU2529 Apologies for the late response.  This issue is now a year old -- did you find an answer somewhere else or are you still looking for an answer?

**Comment by RAJU2529** [comment]
@tdykstra. No sir I didn't got answer. I need clarification , if I add above registry keys on Windows 10 1909 64bit enterprise , do I get any secure issues  and while browsing on edge and internet explorer

**Comment by tdykstra** [comment]
@GrabYourPitchforks can you answer this security-related question or direct it to someone who can?

**Comment by tdykstra** [comment]
Closing as duplicate of #8874
