### ISSUE TITLE
What EXACTLY shall we do to prevent delegate GC?

### ISSUE THREAD

**Issue by goyzhang** [dotnet/docs#8936]
I follow the link to this page https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.gchandle?view=netframework-4.7.2
It indicates " platform invoke will prevent delegate to be garbage collected before call end" I think the GCHandle link is a little bit misleading. It makes me think that I need to pin the delegate. Then I found out that I can't pin a delegate.` GCHandle.Alloc()` gives me an "Object contains non-primitive or non-blittable data." error.
Accroding to this https://social.msdn.microsoft.com/Forums/en-US/bd662199-d150-4fbf-a5ee-7a06af0493bb/interop-pinning-and-delegates?forum=clr

> We need to extend the lifetime of delegate instead of pin it. 

The _Note_ section doesn't give a clear indication about what to do but a GCHandle link, which is very misleading, since we don't need GCHandle for delegate. I hope we can improve this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c203f7db-db27-7bed-d13b-d6c36872d264
* Version Independent ID: 853806ef-6613-72f6-3462-9534d8b5701e
* Content: [Marshaling a Delegate as a Callback Method](https://docs.microsoft.com/en-us/dotnet/framework/interop/marshaling-a-delegate-as-a-callback-method)
* Content Source: [docs/framework/interop/marshaling-a-delegate-as-a-callback-method.md](https://github.com/dotnet/docs/blob/master/docs/framework/interop/marshaling-a-delegate-as-a-callback-method.md)
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by gewarren** [comment]
@Maoni0 Can you comment on what we should add to the note?

https://docs.microsoft.com/en-us/dotnet/framework/interop/marshaling-a-delegate-as-a-callback-method
