### ISSUE TITLE
StringBuilder memory allocation strategy

### ISSUE THREAD

**Issue by damirarh** [dotnet/docs#8942]
**Issue description**

While reading the documentation I encountered what seem to be 2 contradictory statements regarding the memory allocation in the StringBuffer class:

In the "The String and StringBuilder types" section:

> New data is appended to the buffer if room is available; otherwise, a new, larger buffer is allocated, data from the original buffer is copied to the new buffer, and the new data is then appended to the new buffer.

In the "Performing StringBuilder operations" section:

> Performance is severely impacted because each character access walks the entire linked list of chunks to find the correct buffer to index into.

Which statement is correct? Does the StringBuilder class always have a single buffer and copies the old contents to the new buffer or does it maintain multiple buffers?

(I have not selected the target framework below because I don't think it applies. If there are any differences between the implementations in different runtimes, they should be mentioned in the documentation.)

**Comment by tdykstra** [comment]
@karelz who could look into this?  There does seem to be a contradiction between these two sections of https://docs.microsoft.com/en-us/dotnet/api/system.text.stringbuilder

**Comment by karelz** [comment]
How are the statements contradictory? They seem to be independent. What am I missing?

**Comment by tdykstra** [comment]
In one case it sounds like there is always one single buffer, handling growth by replacing a buffer with a larger one and copying to it.  In the other case it sounds like growth is handled by adding buffers.
