### ISSUE TITLE
It would be great

### ISSUE THREAD

**Issue by CrazyTim** [dotnet/docs#8948]
It would be great if we had a setting to "turn on" Interpolated strings for an entire file without having to always prepend "$" to every string in it. Would just save some time, and increase adoption.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32f4b61b-ee05-3221-9a2c-0cdf31645f67
* Version Independent ID: b5ca0b9a-d789-d9a6-e5d5-1a4709879091
* Content: [Interpolated Strings (Visual Basic)](https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/language-features/strings/interpolated-strings)
* Content Source: [docs/visual-basic/programming-guide/language-features/strings/interpolated-strings.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/programming-guide/language-features/strings/interpolated-strings.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by hDoubleE** [comment]
I like Tim's idea. Or some solution. More broadly, is there any existing strategy to eradicate legacy string concatenation across all Docs and replace with modern string interpolation? I run into this all over the platform and it nags me. Just curious...

**Comment by BillWagner** [comment]
I'm going to close for two reasons:

1. There (almost certainly) won't be a language change to remove the `$` requirement. That would be a massive breaking change. (The expression "{0}, {1}" is valid as an interpolated string: it evaluates to "0 1".)
1. Issue #9002 better describes the docs tasks to incorporate interpolated strings throughout the doc set.
