### ISSUE TITLE
If a base class does not offer a default constructor, the derived class must make an explicit call to a base constructor by using base.

### ISSUE THREAD

**Issue by volkan-yazilim** [dotnet/docs#8958]
But this code, below, runs. Need some explanation, please.

```csharp
    public class Employee
    {
        public int salary;

        public Employee(int annualSalary)
        {
            salary = annualSalary;
        }

        public Employee(int weeklySalary, int numberOfWeeks)
        {
            salary = weeklySalary * numberOfWeeks;
        }
    }

    class Manager { public Manager() { } }

    class Program
    {
        static void Main(string[] args)
        {
           Manager x = new Manager();
        }
    }
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 374a58d4-1905-c664-04b6-fd68e617f8c9
* Version Independent ID: 36d0bf3a-29bf-5162-c700-142b03f9a16c
* Content: [Using Constructors (C# Programming Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/using-constructors)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/using-constructors.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/using-constructors.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Thraka** [comment]
@xamarin-volkan Hi!

This works because the if the `Employee` class omits all constructors, a parameterless constructor (like you have in `Manager`) is automatically added. If it didn't add that constructor for you automatically, no one could create an instance of the class.

**Comment by xamarin-volkan** [comment]
I understand and agree with you. But if this is the situation, why does this version not work?

class Program
    {
        static void Main(string[] args)
        {
            Employee y = new Employee();
            Manager x = new Manager();
            Console.ReadLine();
        }
    }

I believe there is a missing explanation that I am currently looking for it.
About inherited class constructors, if base is used then the exact definiton of ctor needs to be defined and used. If base is not used then default ctor is used even though not defined.

**Comment by Thraka** [comment]
Oh I'm sorry, I misread your code 😄 If you have 0 constructors defined, the basic default `constructor()` is automatically defined for you. If you add any constructor, this default constructor is not added automatically, you have to do it. So in the case of `Employee` you have opted to NOT include a default constructor.

However, in your example, you're not inheriting from either class.

**Comment by elgonzo** [comment]
I guess what volkan is pointing out here is that in the given documention page, the Employee class implementation does NOT have a default constructor.

However, when the documentation page then talks about how Manager (derived from Employee) would invoke the base class constructor, it pretends that Employee suddenly has a default constructor.

Note how the two included code samples demonstrate Manager constructors calling a parameterless base-class constructor implictly and explictly:

[!code-csharp[csProgGuideObjects#58](../../../csharp/programming-guide/classes-and-structs/codesnippet/CSharp/using-constructors_6.cs)]  

[!code-csharp[csProgGuideObjects#57](../../../csharp/programming-guide/classes-and-structs/codesnippet/CSharp/using-constructors_7.cs)]

This is in conflict with the implementation of the Manager and Employee class established just a few paragraphs earlier. For beginners (which are the target group for this particular documentation page), this can indeed be rather confusing.

**Comment by elgonzo** [comment]
I guess what volkan is pointing out here is that in the given documention page, the Employee class implementation does NOT have a default constructor.

However, when the documentation page then talks about how Manager (derived from Employee) would invoke the base class constructor, it pretends that Employee suddenly has a default constructor.

Note how the two included code samples demonstrate Manager constructors calling a parameterless base-class constructor implictly and explictly:

[!code-csharp[csProgGuideObjects#58](../../../csharp/programming-guide/classes-and-structs/codesnippet/CSharp/using-constructors_6.cs)]  
  
    [!code-csharp[csProgGuideObjects#57](../../../csharp/programming-guide/classes-and-structs/codesnippet/CSharp/using-constructors_7.cs)]
[!code-csharpcsProgGuideObjects#58]

    [!code-csharpcsProgGuideObjects#57]

This is in conflict with the implementation of the Manager and Employee class established just a few paragraphs earlier. For beginners (which are the target group for this particular documentation page), this can indeed be rather confusing.

**Comment by elgonzo** [comment]
I guess what volkan is pointing out here is that in the given documention page, the Employee class implementation does NOT have a default constructor.

However, when the documentation page then talks about how Manager (derived from Employee) would invoke the base class constructor, it pretends that Employee suddenly has a default constructor.

Note how the two included code samples demonstrate Manager constructors calling a parameterless base-class constructor implictly and explictly:
```
[!code-csharp[csProgGuideObjects#58](../../../csharp/programming-guide/classes-and-structs/codesnippet/CSharp/using-constructors_6.cs)]
[!code-csharp[csProgGuideObjects#57](../../../csharp/programming-guide/classes-and-structs/codesnippet/CSharp/using-constructors_7.cs)]
```

This is in conflict with the implementation of the Manager and Employee class established just a few paragraphs earlier. For beginners (which are the target group for this particular documentation page), this can indeed be rather confusing.

**Comment by Thraka** [comment]
@elgonzo It's sometimes hard to understand if someone is just asking a general question or is referring to something specific.

Looking at the section you jut pointed out, I see the confusion. 

@BillWagner using the manager class (whose base omitted the default constructor) to demonstrate the implicit default constructor is confusing.

**Comment by xamarin-volkan** [comment]
@Thraka sorry if I could not make it clear at first.
@elgonzo has explained my confusion, right.

**Comment by davidg-skyward** [comment]
Another problem with this page is the fallacy of this statement:
"A constructor that takes no parameters is called a default constructor."

A constructor that takes no parameters is a "no arg constructor", or a constructor with no parameters.  

The constructor provided by the compiler in the event the programmer fails to define ANY constructor is the "default" constructor.

**Comment by Thraka** [comment]
> Another problem with this page is the fallacy of this statement:
> "A constructor that takes no parameters is called a default constructor."
> 
> A constructor that takes no parameters is a "no arg constructor", or a constructor with no parameters.
> 
> The constructor provided by the compiler in the event the programmer fails to define ANY constructor is the "default" constructor.

Doing some quick searching I found that C# uses the wording "parameterless constructor" over "no argument constructor"
