### ISSUE TITLE
Uwp

### ISSUE THREAD

**Issue by neven10** [dotnet/docs#8960]
Is there any way to run this on UWP?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8e22825-c4ee-5a36-f911-8ad456970ecc
* Version Independent ID: ad0bf640-7dfc-1184-077c-358bb14277a7
* Content: [Use ML.NET in a sentiment analysis binary classification scenario](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/sentiment-analysis)
* Content Source: [docs/machine-learning/tutorials/sentiment-analysis.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/sentiment-analysis.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by neven10** [comment]
There seems to be an issue. Check this :
https://github.com/dotnet/corefx/issues/33434

**Comment by JRAlexander** [comment]
@neven10, I'm going to close this and we will document UWP support when it's available in the product. You can track the PR here:  https://github.com/dotnet/machinelearning/issues/1736 along with the above corefx issue you referenced. Thanks!
