### ISSUE TITLE
A client that calls in a .NET COM DLL (that implements Windows.Forms controls) as out-of-proc, hangs. The client never comes back displaying the Windows control.

### ISSUE THREAD

**Issue by shmisra** [dotnet/docs#8965]
Issue Description
=================
A client that calls in a .NET COM DLL (that implements Windows.Forms controls) as out-of-proc, hangs. The client never comes back displaying the Windows control.

Here is what you can do to reproduce the issue. 

1. Create a .NET COM DLL that implements a Windows.Forms control (for example say we name it as: PlugIn). 
2. Configured a default COM surrogate process for PlugIn, so that the PlugIn control loads out-of-proc via dllhost.exe

 OR 

 Create a COM server EXE that hosts PlugIn.

To test this create a client application that is an ActiveX Container and create an out-of-proc COM component for PlugIn. 

For example: 
I am using "TSTCON Sample" Ref: https://msdn.microsoft.com/en-us/library/f9adb5t5(v=vs.100).aspx which is an ActiveX Container as the C++ client. When I create the PlugIn object as CLSCTX_LOCAL_SERVER, the dllhost.exe gets spanned OR calls the COM server EXE that hosts PlugIn. 
So, activating the object is not the problem here. However immediately the client app TSTCON is hung and waiting for a response from dllhost.exe OR the COM server EXE that hosts PlugIn.

I took dumps of the client which is TstCon.exe & the server (dllhost.exe OR the COM server EXE that hosts PlugIn).
 
TstCon.exe is HUNG & never comes back. Below is the call-stack of the thread which is blocked.
==============================================================================================
1 thread [stats]: 0
    76672b9c win32u!NtUserWaitMessage+0xc
    74479004 user32!DialogBox2+0x103
    74474b0a user32!InternalDialogBox+0xdf
    74474a22 user32!DialogBoxIndirectParamAorW+0x32
    744749db user32!DialogBoxIndirectParamW+0x1b
    47091c2b oledlg!UStandardInvocation+0x59
    47085dd3 oledlg!OleUIBusyW+0x33
    470844a3 oledlg!OleUIBusyA+0xa3
    0f63fe80 mfc140d!COleBusyDialog::DoModal+0x60
    0f66aeab mfc140d!COleMessageFilter::OnNotRespondingDialog+0x7b
    0f66ab19 mfc140d!COleMessageFilter::XMessageFilter::MessagePending+0x129
    76c06a6e combase!CCliModalLoop::HandlePendingMessage+0x103
    76c06cfb combase!CCliModalLoop::HandleWakeForMsg+0x51
    76c07126 combase!CCliModalLoop::BlockFn+0x181
    76c068b1 combase!ModalLoop+0x9b
    76c0666e combase!ClassicSTAThreadWaitForCall+0xe
    76c58f97 combase!ThreadSendReceive+0x137
    (Inline) combase!CSyncClientCall::SwitchAptAndDispatchCall+0x1bd
    76c57f97 combase!CSyncClientCall::SendReceive2+0x427
    (Inline) combase!SyncClientCallRetryContext::SendReceiveWithRetry+0x29
    (Inline) combase!CSyncClientCall::SendReceiveInRetryContext+0x29
    76c06760 combase!ClassicSTAThreadSendReceive+0x70
    76c57712 combase!CSyncClientCall::SendReceive+0x2b2
    (Inline) combase!CClientChannel::SendReceive+0x7c
    76c005d5 combase!NdrExtpProxySendReceive+0xd5
    (Inline) rpcrt4!NdrpProxySendReceive+0x1b
    76695856 rpcrt4!NdrClientCall2+0x526
    76695324 rpcrt4!NdrClientCall4+0x14
    (Inline) combase!IViewObject_RemoteDraw_Proxy+0x2b
    76da8e89 combase!IViewObject_Draw_Proxy+0x69
    013cd3c3 TstCon!CTestContainer98Item::DrawBackToFront+0x1b3
    013da6a2 TstCon!CTestContainer98View::OnDraw+0x1b2
    0f69d9d2 mfc140d!CView::OnPaint+0xb2
    0f6d049f mfc140d!CWnd::OnWndMsg+0x10cf
    0f6d4401 mfc140d!CWnd::WindowProc+0x61
    0f6c54fc mfc140d!AfxCallWndProc+0x13c
    0f6c64f5 mfc140d!AfxWndProc+0xb5
    0f4056dd mfc140d!AfxWndProcBase+0x6d
    7449be6b user32!_InternalCallWinProc+0x2b
    (Inline) user32!InternalCallWinProc+0x1a
    7449833a user32!UserCallWinProcCheckWow+0x3aa
    74497eda user32!DispatchClientMessage+0xea
    7449a629 user32!__fnDWORD+0x49
    76f4c6cd ntdll!KiUserCallbackDispatcher+0x4d
    76672e3c win32u!NtUserDispatchMessage+0xc
    74497cfa user32!DispatchMessageWorker+0x31a
    744979d0 user32!DispatchMessageW+0x10
    (Inline) combase!CCliModalLoop::MyDispatchMessage+0xa
    76c06e14 combase!CCliModalLoop::HandleWakeForMsg+0x16a
    76c07126 combase!CCliModalLoop::BlockFn+0x181
    76c068b1 combase!ModalLoop+0x9b
    76c0666e combase!ClassicSTAThreadWaitForCall+0xe
    76c58f97 combase!ThreadSendReceive+0x137
    (Inline) combase!CSyncClientCall::SwitchAptAndDispatchCall+0x1bd
    76c57f97 combase!CSyncClientCall::SendReceive2+0x427
    (Inline) combase!SyncClientCallRetryContext::SendReceiveWithRetry+0x29
    (Inline) combase!CSyncClientCall::SendReceiveInRetryContext+0x29
    76c06760 combase!ClassicSTAThreadSendReceive+0x70
    76c57712 combase!CSyncClientCall::SendReceive+0x2b2
    (Inline) combase!CClientChannel::SendReceive+0x7c
    76c005d5 combase!NdrExtpProxySendReceive+0xd5
    (Inline) rpcrt4!NdrpProxySendReceive+0x1b
    76695856 rpcrt4!NdrClientCall2+0x526
    76cd2990 combase!ObjectStublessClient+0x70
    76cca92f combase!ObjectStubless+0xf
    0f62e834 mfc140d!COleClientItem::SetExtent+0x84
    013cf4e6 TstCon!CTestContainer98Item::Move+0x146
    013dc84a TstCon!CTestContainer98View::OnLButtonDown+0x3ca
    0f6d0dd5 mfc140d!CWnd::OnWndMsg+0x1a05
    0f6d4401 mfc140d!CWnd::WindowProc+0x61
    0f6c54fc mfc140d!AfxCallWndProc+0x13c
    0f6c64f5 mfc140d!AfxWndProc+0xb5
    0f4056dd mfc140d!AfxWndProcBase+0x6d
    7449be6b user32!_InternalCallWinProc+0x2b
    (Inline) user32!InternalCallWinProc+0x1a
    7449833a user32!UserCallWinProcCheckWow+0x3aa
    74497bee user32!DispatchMessageWorker+0x20e
    7448cd30 user32!DispatchMessageA+0x10
    0f695889 mfc140d!AfxInternalPumpMessage+0x129
    0f696da3 mfc140d!CWinThread::PumpMessage+0x13
    0f696ead mfc140d!CWinThread::Run+0xed
    0f50146c mfc140d!CWinApp::Run+0x6c
    0f70d8af mfc140d!AfxWinMain+0x19f
    013edd68 TstCon!WinMain+0x18
    013eae6e TstCon!invoke_main+0x1e
    013ead07 TstCon!__scrt_common_main_seh+0x157
    013eab9d TstCon!__scrt_common_main+0xd
    013eaee8 TstCon!WinMainCRTStartup+0x8
    74608484 kernel32!BaseThreadInitThunk+0x24
    76f4305a ntdll!__RtlUserThreadStart+0x2f
    76f4302a ntdll!_RtlUserThreadStart+0x1b
 
 
Server - The server is stuck with the thread call-stack as shown below. 
=======================================================================
1 thread [stats]: 1
    76672b4c win32u!NtUserMessageCall+0xc
    7447c09a user32!SendMessageWorker+0x3da
    7447bc57 user32!SendMessageW+0x137
    06c30e2b 0x6c30e2b
    7a4d4cb4 System_Windows_Forms_ni+0x204cb4
    7a9ff283 System_Windows_Forms_ni+0x72f283
    7a9fa569 System_Windows_Forms_ni+0x72a569
    50605cd9 mscorwks!COMToCLRWorkerBody+0x1de
    50605de3 mscorwks!COMToCLRWorkerDebuggerWrapper+0x37
    50605f4c mscorwks!COMToCLRWorker+0x157
    0410b4f5 0x410b4f5
    (Inline) combase!IViewObject_Draw_Stub+0x45
    76d62138 combase!IViewObject_RemoteDraw_Thunk+0x58
    76697684 rpcrt4!NdrStubCall2+0x7d4
    76ca47d9 combase!CStdStubBuffer_Invoke+0x99
    (Inline) combase!InvokeStubWithExceptionPolicyAndTracing::__l6::<lambda_1ba7c1521bf8e7d0ebd8f0b3c0295667>::operator()+0x4e
    76c5f218 combase!ObjectMethodExceptionHandlingAction<<lambda_1ba7c1521bf8e7d0ebd8f0b3c0295667> >+0xa8
    (Inline) combase!InvokeStubWithExceptionPolicyAndTracing+0xfa
    76c5ec9d combase!DefaultStubInvoke+0x2bd
    (Inline) combase!SyncStubCall::Invoke+0x1e
    (Inline) combase!SyncServerCall::StubInvoke+0x1e
    (Inline) combase!StubInvoke+0x498
    76c5faa7 combase!ServerCall::ContextInvoke+0x677
    (Inline) combase!CServerChannel::ContextInvoke+0x8e
    (Inline) combase!DefaultInvokeInApartment+0xa8
    76c5c0c9 combase!AppInvoke+0x359
    76c5b40d combase!ComInvokeWithLockAndIPID+0x60d
    76c66da3 combase!ThreadInvoke+0x1d13
    766a84a0 rpcrt4!DispatchToStubInCNoAvrf+0x20
    766a807c rpcrt4!RPC_INTERFACE::DispatchToStubWorker+0x17c
    (Inline) rpcrt4!RPC_INTERFACE::DispatchToStub+0x82
    766a83ab rpcrt4!RPC_INTERFACE::DispatchToStubWithObject+0x13b
    (Inline) rpcrt4!LRPC_SBINDING::DispatchToStubWithObject+0x20
    766a71a3 rpcrt4!LRPC_SCALL::DispatchRequest+0x123
    (Inline) rpcrt4!LRPC_SCALL::QueueOrDispatchCall+0x2f
    766a764c rpcrt4!LRPC_SCALL::HandleRequest+0x37c
    (Inline) rpcrt4!LRPC_SASSOCIATION::HandleRequest+0x1e6
    766abc91 rpcrt4!LRPC_ADDRESS::HandleRequest+0x2d1
    766ac4bf rpcrt4!LRPC_ADDRESS::ProcessIO+0x22f
    (Inline) rpcrt4!LrpcServerIoHandler+0x14
    766b24c0 rpcrt4!LrpcIoComplete+0xa0
    76f2c899 ntdll!TppAlpcpExecuteCallback+0xa9
    76f2cf5f ntdll!TppWorkerThread+0x63f
    74608484 kernel32!BaseThreadInitThunk+0x24
    76f4305a ntdll!__RtlUserThreadStart+0x2f
    76f4302a ntdll!_RtlUserThreadStart+0x1b
 
Post discussions with the COM PG team we came to a conclusion having the following points: 

+ "WinForms controls” implementation was never designed to work out-of-proc.
+ It was designed to interoperate correctly with in-proc ActiveX containers, but not out-of-proc containers.  This is "by design" and won't work out-of-proc. 
+ The "WinForms controls” implementation has a lot of dependencies on running in-proc, so attempting to run them out-of-proc would have all sorts of unintended details that would break the behaviour. As a result a feature request to implement it out-of-proc cannot be improvised.

Requirement
=========
Update MSDN pages with the above information.

Environment
=========
Any supported version of .NET Framework that can implement a Windows.Forms control. 
We used .NET Framework 4.6 & above for the tests. 
OS: We tested this on Windows 10 version 1803.

**Comment by adegeo** [comment]
This issue got lost. This sounds like a bug in .NET Framework and isn't related to documentation. I would report this issue through the Visual Studio Feedback mechanism in the IDE. I'm going to close this.
