### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by BadgerB1** [dotnet/docs#8968]
Why are almost all the examples are the same?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bba28ced-32df-6cf8-3df6-a81e8aa6facc
* Version Independent ID: a79c380b-4aef-6d86-76c3-f422299e19b6
* Content: [Query Expression Syntax Examples: Join Operators](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/ef/language-reference/query-expression-syntax-examples-join-operators)
* Content Source: [docs/framework/data/adonet/ef/language-reference/query-expression-syntax-examples-join-operators.md](https://github.com/dotnet/docs/blob/master/docs/framework/data/adonet/ef/language-reference/query-expression-syntax-examples-join-operators.md)
* Product: **dotnet-framework**
* GitHub Login: @douglaslMS
* Microsoft Alias: **douglasl**

**Comment by douglaslMS** [comment]
@BadgerB1 I had to stare at this one for a minute! The first and third example for GroupJoin were identical. I removed the duplicate in the linked PR. Thanks for bringing this to our attention.
