### ISSUE TITLE
Oveflow bug

### ISSUE THREAD

**Issue by Damilope** [dotnet/docs#8978]
The page overflows, especially in focus mode and hides the overflowed parts making me have to switch between modes to read or copy content to test.
I added, "overflow-x: auto" to the styles in the "tutorial-row-main" class and it seems to fix everything. Even the overflowing of the whole page outside of focus mode.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1eb6b35f-44b4-b377-7e41-b865aa29d09e
* Version Independent ID: 35a57251-54ec-8ea9-298f-3033beca7731
* Content: [String interpolation - C# interactive tutorial](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/intro-to-csharp/interpolated-strings?tutorial-step=5)
* Content Source: [docs/csharp/tutorials/intro-to-csharp/interpolated-strings.yml](https://github.com/dotnet/docs/blob/live/docs/csharp/tutorials/intro-to-csharp/interpolated-strings.yml)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@dend Can you look at this feedback for the experience for interactive tutorials?

**Comment by mairaw** [comment]
Given this is about the site experience and not the content, I've moved this to https://github.com/MicrosoftDocs/feedback/issues/905.
