### ISSUE TITLE
Apparently this can include an msbuild-sdk element

### ISSUE THREAD

**Issue by martingbrown** [dotnet/docs#8980]
I know there is a See Also that points to the relevant documentation. But it might be clearer if the msbuild-sdks element was mentioned in the "global.json schema" section of this document.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a94c335b-0b65-96cc-1c25-65777fbe4bb5
* Version Independent ID: 6d80613f-42dc-35d7-aeff-3187a36dbbca
* Content: [global.json overview](https://docs.microsoft.com/en-gb/dotnet/core/tools/global-json)
* Content Source: [docs/core/tools/global-json.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/global-json.md)
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Thanks for your feedback @martingbrown. I think it makes sense to add that.
@KathleenDollard is msbuild-sdks part of the official schema for global.json?

**Comment by mairaw** [comment]
@KathleenDollard can you help with my earlier question?

**Comment by mairaw** [comment]
@nguerrera can you help with this one? Would this be similar to what you said in https://github.com/dotnet/docs/issues/14687#issuecomment-537626540?
