### ISSUE TITLE
Incorrect value for ClaimTypes.Email

### ISSUE THREAD

**Issue by stefann42** [dotnet/docs#8982]
Documentation should say "The URI for a claim that specifies the email address of an entity, http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress." because that's the value in code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa803eba-477c-0952-b29f-c9218db2b260
* Version Independent ID: f65f3125-4b1b-f260-a021-d7249167f898
* Content: [ClaimTypes Class (System.Security.Claims)](https://docs.microsoft.com/en-us/dotnet/api/system.security.claims.claimtypes?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(System.Security.Claims.ClaimTypes);k(TargetFrameworkMoniker-.NETFramework,Version%3Dv4.7.1);k(DevLang-csharp)%26rd%3Dtrue&view=netframework-4.7.2)
* Content Source: [xml/System.Security.Claims/ClaimTypes.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Security.Claims/ClaimTypes.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks for your feedback @stefann42. I've created a PR to fix this: https://github.com/dotnet/dotnet-api-docs/pull/732

You can also make edits to our docs when you find issues like that if you'd like:
https://docs.microsoft.com/en-us/contribute/#quick-edits-to-existing-documents

**Comment by stefann42** [comment]
Thanks, didn't realize I could directly submit edits.
