### ISSUE TITLE
Incorrect value for ClaimTypes.Email

### ISSUE THREAD

**Issue by stefann42** [dotnet/docs#8983]
Documentation should say "The URI for a claim that specifies the email address of an entity, http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress." because that's the value in code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45ad1a02-2b33-ffcf-95ef-5f242b277dd8
* Version Independent ID: cf937f03-4f36-f7f2-960a-51120de539f6
* Content: [ClaimTypes.Email Field (System.Security.Claims)](https://docs.microsoft.com/en-us/dotnet/api/system.security.claims.claimtypes.email?view=netframework-4.7.2)
* Content Source: [xml/System.Security.Claims/ClaimTypes.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Security.Claims/ClaimTypes.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Duplicate of #8982

**Comment by mairaw** [comment]
Thanks @stefann42 but I'll close this as a duplicate. My fix should take care of this issue as well since the source for both pages is the same.
