### ISSUE TITLE
Connections refused error

### ISSUE THREAD

**Issue by tsholom** [dotnet/docs#8986]
I'm stuck on this part:

"docker build -t dotnetapp-dev ."

on step 4/7 I get the following error:
"/usr/share/dotnet/sdk/2.1.403/NuGet.targets(114,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. [/app/Hello.csproj]
/usr/share/dotnet/sdk/2.1.403/NuGet.targets(114,5): error : Connections refused [/app/Hello.csproj] 
The command '/bin/sh -c dotnet restore' returned a non-zero code: 1"

however if I just run the restore it completes successfully... I've tried googling, but none of the solutions provided to other people with the same issue have helped me... if you can offer some suggestions or point me in the right direction where I might find the answer, that would be much appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72ef1481-3b6f-30bf-330d-45400c0a349c
* Version Independent ID: 03a156f7-b178-4d54-503d-26d229f89dcd
* Content: [Learn Docker Basics with .NET Core](https://docs.microsoft.com/en-us/dotnet/core/docker/docker-basics-dotnet-core)
* Content Source: [docs/core/docker/docker-basics-dotnet-core.md](https://github.com/dotnet/docs/blob/master/docs/core/docker/docker-basics-dotnet-core.md)
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **johnalex**

**Comment by Thraka** [comment]
I'm not sure what to do about this. I rewrote the article which should be published today. Please try the new version and let me know if that fixes your problem. Otherwise it sounds like an internet connection issue.
