### ISSUE TITLE
Where is the nupkg file downloaded by 'dotnet restore'?

### ISSUE THREAD

**Issue by sy-github** [dotnet/docs#8992]
My system is Ubuntu. I created a C# project and ran 'dotnet add package xxx'. But I can't find the downloaded package file.

**Comment by svick** [comment]
Why do you want to know that? In general, this is not something that you would need to know.

If you really want to know, it should be in ~/.nuget/packages.

**Comment by sy-github** [comment]
@svick you are right in that it's implementation details. I just want to know as much as possible. Thanks for the answer in the end.
