### ISSUE TITLE
Minor spelling and grammar

### ISSUE THREAD

**Issue by hDoubleE** [dotnet/docs#8994]
Reading about LinkedList&lt;T&gt; and came across two small spelling/grammar issues…
In Examples:
```
// Change the last node be 'yesterday'.
```
Grammar: to be...or just to?
```
// Indicate, by using parentheisis
```
Spelling: Parenthesis

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6351a8ba-536f-6921-f562-9c81b577a2fc
* Version Independent ID: 994dcbd3-d6eb-0042-f472-22525e5c4d6f
* Content: [LinkedList&lt;T&gt; Class (System.Collections.Generic)](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.linkedlist-1?view=netframework-4.7.2)
* Content Source: [xml/System.Collections.Generic/LinkedList`1.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Collections.Generic/LinkedList`1.xml)
* Product: **dotnet-api**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Thank you for your feedback @hDoubleE. I've opened the following PR to fix this:
https://github.com/dotnet/samples/pull/457

**Comment by hDoubleE** [comment]
Any tips/resources/reading on how to go about doing this the right way? Instead of just flagging the issue on docs page, can I make changes and provide solutions? How could I have done this better? Being that I'm new...

**Comment by mairaw** [comment]
I commented on the PR, but also commenting here for completeness @hDoubleE.
Here's the general contributor guide: https://docs.microsoft.com/en-us/contribute/

You can continue to submit feedback comments, but you can also click the Edit button and submit the changes. Feel free to ask us if the change is not straightforward or you're not sure what to do.
