### ISSUE TITLE
Expected "using" directives

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#8995]
@veotani commented on [Mon Nov 12 2018](https://github.com/dotnet/docs.ru-ru/issues/153)

In the paragraph "Define data and model paths" there is the following phrase: "To make the preceding code compile, add the following using directives at the top of the Program.cs file:". Expected some using directives, but got this: "var metrics = mlContext.Regression.Evaluate(predictions, "Label", "Score");". Feels like it shouldn't be here.

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: a30b3ff5-b5e6-ff02-6f60-b5cef6f34666
* Version Independent ID: fdf962e2-620e-d9ad-5057-5f96f52dc60f
* Content: [Использование ML.NET для прогнозирования платы за проезд в такси в Нью-Йорке (регрессия)](https://docs.microsoft.com/ru-ru/dotnet/machine-learning/tutorials/taxi-fare)
* Content Source: [docs/machine-learning/tutorials/taxi-fare.md](https://github.com/dotnet/docs.ru-ru/blob/live/docs/machine-learning/tutorials/taxi-fare.md)
* Product: **dotnet-ml**
* GitHub Login: @aditidugar
* Microsoft Alias: **johalex**

---

@veotani commented on [Mon Nov 12 2018](https://github.com/dotnet/docs.ru-ru/issues/153#issuecomment-437996687)

If i am not mistaken, the "using Microsoft.ML.Runtime.Data;" as the code sample should be there.

**Comment by CeciAc** [comment]
Hi team, 
I moved this here since the user is making a suggestion on the souce page

Best regards

**Comment by pkulikov** [comment]
@CeciAc @veotani it's an artifact of not-yet-translated article. This article was rewritten to use the new ML.NET 0.7 API: both samples and the text were updated. The Russian translation is of the old version of the tutorial, but it references the snippets for the new version.

Compare the new version in English:
https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/taxi-fare#define-data-and-model-paths

**Comment by mairaw** [comment]
Thanks @pkulikov for your help. I'll close this since this is not a source issue but a loc issue. I've reopened the original issue @CeciAc.
