### ISSUE TITLE
Consider adding a target for `net461` — why?

### ISSUE THREAD

**Issue by qbit86** [dotnet/docs#8997]
&gt; Using .NET Standard 2.0 from .NET Framework has some issues that were addressed in .NET Framework 4.7.2.

Could you please elaborate more on this? Which issues? What exactly are we solving by targeting `net461` in addition to just `netstandard2.0`?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b3638c9-ea3c-1c9e-2763-5c3e8e965663
* Version Independent ID: aff99d6b-9471-9277-160b-670ee8028b53
* Content: [Cross-platform targeting for .NET libraries](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/cross-platform-targeting)
* Content Source: [docs/standard/library-guidance/cross-platform-targeting.md](https://github.com/dotnet/docs/blob/master/docs/standard/library-guidance/cross-platform-targeting.md)
* Product: **dotnet**
* GitHub Login: @JamesNK
* Microsoft Alias: **mairaw**

**Comment by JamesNK** [comment]
@terrajobst Do you know of a blog post or article that discusses the issues netstandard2.0 has with net461? I'll add a link to it in the docs.

**Comment by terrajobst** [comment]
Not yet :-(

**Comment by gallivantor** [comment]
I thought .NET 4.7.1 fully implemented .NET Standard 2.0... if this is not the case then more detail should definitely be provided about what the problem is

**Comment by mairaw** [comment]
@terrajobst is there a quick explanation here you can add on why we're recommending this?
