### ISSUE TITLE
Wide adoption of string interpolation

### ISSUE THREAD

**Issue by hDoubleE** [dotnet/docs#9002]
Spinning off of #8948

Is there any long term strategy for eradicating legacy string concatenation and format strings and replacing these with modern string interpolation across the Docs platform? I know…massive job. But I’m just curious. Is there any big picture discussion about this specific issue?

For example, the [Strings C#](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/strings/) page makes no mention of string interpolation, just a link, but there’s a whole block dedicated to Format Strings. I’m sorry, but since the adoption of string interpolation, format strings are gross and wonky. 

The language is always changing, do the Docs reflect more progressive modern methods or just what works? Modern string interpolation is being adopted. In languages outside the framework, too. Countless Docs code snippets are still dealing with strings the old way, which granted works. Should the Docs be updated to reflect this impactful new feature? Do they embrace modern best practices or cover the basics and build from there? 

I don’t know the answers, just thought I’d bring it up.

**Comment by hDoubleE** [comment]
Thanks for your feedback @BillWagner . As a follow up, using the [workflow](https://docs.microsoft.com/en-us/contribute/how-to-write-workflows-major) outlined here as a guide. Can I write up a user facing content block about string interpolation for the [C# String Page](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/strings/) and submit it? Obviously, this would get chopped up and revised, but can I start the process? In short, how would you recommend starting? And how might I be involved and help out?

**Comment by pkulikov** [comment]
@hDoubleE @BillWagner 

>For example, the Strings C# page makes no mention of string interpolation, just a link, but there’s a whole block dedicated to Format Strings.

I think the good way to update the article is to rewrite the [Format strings](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/strings/#format-strings) section in terms of string interpolation and link the main article about string interpolation from there. Ideally, not too much duplication should be introduced. Additionally, referencing [Formatting types](https://docs.microsoft.com/en-us/dotnet/standard/base-types/formatting-types) for more information about formatting.

**Comment by hDoubleE** [comment]
@pkulikov I agree the [Formatting Types](https://docs.microsoft.com/en-us/dotnet/standard/base-types/formatting-types) article should be linked to the strings page. I'll try to work that in. Just curious, should Formatting Types article also make mention string interpolation? What are your thoughts?

**Comment by pkulikov** [comment]
> Just curious, should Formatting Types article also make mention string interpolation? What are your thoughts?

Partially, it's already done. As string interpolation is equivalent to the composite formatting feature, it's mentioned at the [Composite formatting](https://docs.microsoft.com/en-us/dotnet/standard/base-types/composite-formatting) article. That article is in the subset of the "Formatting types" article. A similar mention of string interpolation can be made in the [corresponding section on composite formatting](https://docs.microsoft.com/en-us/dotnet/standard/base-types/formatting-types#composite-formatting), though. With another PR as @BillWagner notes.
