### ISSUE TITLE
Broken link. The "Northwind model" link in "Entity Framework examples".

### ISSUE THREAD

**Issue by MarcioAB** [dotnet/docs#9009]
Broken link. The "Northwind model" link in "Entity Framework examples".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c7bb383-fcde-22f1-16fb-dd0c05a6dd35
* Version Independent ID: 446292d0-2dfa-79ac-113f-3c456869b0d3
* Content: [ADO.NET code examples](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/ado-net-code-examples#linq-to-entities)
* Content Source: [docs/framework/data/adonet/ado-net-code-examples.md](https://github.com/dotnet/docs/blob/master/docs/framework/data/adonet/ado-net-code-examples.md)
* Product: **dotnet-framework**
* GitHub Login: @douglaslMS
* Microsoft Alias: **douglasl**

**Comment by douglaslMS** [comment]
@MarcioAB I can't find the target of this link anywhere on the Microsoft site, so I have removed the link. Fortunately, it's relatively easy to create one's own model against the Northwind sample database. Thank you for bringing this to our attention.
