### ISSUE TITLE
Vector<T> Constructors: Remarks section contains malformed content.

### ISSUE THREAD

**Issue by adyavanapalli** [dotnet/docs#9014]
Remarks section contains malformed content:

![image](https://user-images.githubusercontent.com/8067797/48433988-8337cf80-e746-11e8-965b-9b8bbf244123.png)

I would correct it, but I'm not exactly sure what it's trying to say. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2979dc6-af83-b90f-77c1-e84d54ec1c36
* Version Independent ID: 46c3f559-dd39-6276-8d35-b818e03ee643
* Content: [Vector&lt;T&gt; Constructor (System.Numerics)](https://docs.microsoft.com/en-us/dotnet/api/system.numerics.vector-1.-ctor?view=netcore-2.1)
* Content Source: [xml/System.Numerics/Vector`1.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Numerics/Vector`1.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thank you @adyavanapalli! We'll get that link fixed.
