### ISSUE TITLE
Broken link: "Quickstart" link in "Learn more" item, "Getting Starded" paragraph.

### ISSUE THREAD

**Issue by MarcioAB** [dotnet/docs#9016]
Broken link: "Quickstart" link in "Learn more" item, "Getting Starded" paragraph.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a44958f-e0d6-167a-8749-0c244cf79f09
* Version Independent ID: 3aa59386-dadd-6658-f80d-bee7c7c52263
* Content: [Entity Framework Overview](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/ef/overview)
* Content Source: [docs/framework/data/adonet/ef/overview.md](https://github.com/dotnet/docs/blob/master/docs/framework/data/adonet/ef/overview.md)
* Product: **dotnet-framework**
* GitHub Login: @douglaslMS
* Microsoft Alias: **douglasl**

**Comment by mairaw** [comment]
Thanks @MarcioAB. I've opened PR #9019 to fix this link in two topics plus some others I've found with the same problem.
