### ISSUE TITLE
Great WCF documents for beginners

### ISSUE THREAD

**Issue by thegongben** [dotnet/docs#9017]
These are great documents for WCF beginners. I used to work heavily with Oracle databases and now am learning dot Net WCF (C#) and these documents help.
Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6dfc0a8-94a8-92b2-29ce-40e7b52ac4f9
* Version Independent ID: 98c8be93-23b8-6736-149f-be571c9f50ce
* Content: [Basic Programming Lifecycle](https://docs.microsoft.com/en-us/dotnet/framework/wcf/basic-programming-lifecycle)
* Content Source: [docs/framework/wcf/basic-programming-lifecycle.md](https://github.com/dotnet/docs/blob/master/docs/framework/wcf/basic-programming-lifecycle.md)
* Product: **dotnet-framework**
* GitHub Login: @Lxiamail
* Microsoft Alias: **wcfsrvt**

**Comment by mairaw** [comment]
Thanks for your kind words. We're glad they are helping you @thegongben!
