### ISSUE TITLE
good learning 

### ISSUE THREAD

**Issue by mushtaq96** [dotnet/docs#9023]
the structure of the tutorials was brilliantly written.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1eb6b35f-44b4-b377-7e41-b865aa29d09e
* Version Independent ID: 35a57251-54ec-8ea9-298f-3033beca7731
* Content: [String interpolation - C# interactive tutorial](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/intro-to-csharp/interpolated-strings?tutorial-step=5)
* Content Source: [docs/csharp/tutorials/intro-to-csharp/interpolated-strings.yml](https://github.com/dotnet/docs/blob/live/docs/csharp/tutorials/intro-to-csharp/interpolated-strings.yml)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thank you @mushtaq96 We're glad this helped. Closing as kudos

tagging @rpetrusha who wrote this.
