### ISSUE TITLE
Need to understand how it works.

### ISSUE THREAD

**Issue by hersegu** [dotnet/docs#9026]
All these are explaining how to use the instructions.
It does not explain the mechanism behind like when an handler is called, or I did not find it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cd9a6e9-1206-f69d-edb5-f35ef80869ef
* Version Independent ID: 0b930fe6-7d11-c1b9-8ed1-b1dfa4e6da67
* Content: [RemoveHandler Statement (Visual Basic)](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/statements/removehandler-statement)
* Content Source: [docs/visual-basic/language-reference/statements/removehandler-statement.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/language-reference/statements/removehandler-statement.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by KathleenDollard** [comment]
@hersegu Did you read the "Events" article in the resources at the bottom? 

In general, our references articles like this one cover the details - reference material - and concepts are in the linked articles. If the Visual Basic Events article comes up short, I'd like to fix that article. 

> It does not explain the mechanism behind like when an handler is called, or I did not find it.

Is there something deeper than "when the event is fired"?

I guess I'm asking whether you are familiar with events and the articles did not go deep enough or whether you are new to events (perhaps quite experienced with other types of programming) and the overview didn't clarify sufficiently.

**Comment by BillWagner** [comment]
I'll close this as answered by @KathleenDollard 

@hersegu I hope this answered your question. If not, you can reopen this issue.
