### ISSUE TITLE
More explanation is needed.

### ISSUE THREAD

**Issue by xamarin-volkan** [dotnet/docs#9028]
1) "By constraining the type parameter, you increase the number of ... "    Should it be "increase" or "decrease" ?

2) Could you give some little more explanation about this sentence.
"When you design generic classes or methods, if you will be performing any operation on the generic members beyond simple assignment or calling any methods not supported by System.Object, you will have to apply constraints to the type parameter."

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5712215d-b167-d9cb-bd51-80df0e300d50
* Version Independent ID: 22b2c77c-2721-9384-3863-046e391ea4b1
* Content: [Constraints on Type Parameters (C# Programming Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/generics/constraints-on-type-parameters#enum-constraints)
* Content Source: [docs/csharp/programming-guide/generics/constraints-on-type-parameters.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/generics/constraints-on-type-parameters.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
> "By constraining the type parameter, you increase the number of ... " Should it be "increase" or "decrease" ?

"increase" is correct. Specifying constraints restricts the types that can be specified for a type parameter. Those restrictions means the type parameter has more capabilities.

> "When you design generic classes or methods, if you will be performing any operation on the generic members beyond simple assignment or calling any methods not supported by System.Object, you will have to apply constraints to the type parameter."

Without constraints, the compiler must assume that *any* type is possible. Therefore, only the APIs available on *all* types can be assumed to be present.

The document explains these concepts, I'm closing this issue.
