### ISSUE TITLE
Safe handle example: method hiding vs overriding

### ISSUE THREAD

**Issue by leifurhauks** [dotnet/docs#9035]
In the code example under "Using a safe handle to implement the dispose pattern for a derived class", the derived class hides the base class implementation of Dispose(bool) instead of overriding it. Shouldn't the derived class override the method instead, as is the case in the example code on the API doc page for IDisposable https://docs.microsoft.com/en-us/dotnet/api/system.idisposable?

The way the example code is written here, the following would result in only the base class implementation being called, while the derived class implementation would be ignored:

```csharp
using (DisposableStreamResource resource = new DisposableStreamResource2("file1.txt") {
    // do work with the resource
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 572ef6c6-5066-4a14-76a0-c3fb4b62e604
* Version Independent ID: 9c754da1-c234-fb12-580b-0fcf9ffe2c20
* Content: [Implementing a Dispose method](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-dispose)
* Content Source: [docs/standard/garbage-collection/implementing-dispose.md](https://github.com/dotnet/docs/blob/master/docs/standard/garbage-collection/implementing-dispose.md)
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by rpetrusha** [comment]
I apologize for the length of time that it's taken for us to respond, @leifurhauks, but you're quite correct; `Dispose(bool)` should have overridden the base class method. We'll schedule some time to address this error in an upcoming sprint unless you'd like to submit a PR to address the issue beforehand. For information on submitting a PR, see the [contributor's guide](https://github.com/dotnet/docs/blob/master/CONTRIBUTING.md).
