### ISSUE TITLE
Is this useful?

### ISSUE THREAD

**Issue by volkan-yazilim** [dotnet/docs#9037]
void DoWork() { }
void DoWork&lt;T&gt;() { }
void DoWork&lt;T, U&gt;() { }

Because T and U are not used as parameters,;
- does not all methods have the same signature? Does signature includes T and U
- Can we use them in the block? 
- Could you give a sample code to understand the possible usage of this.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3fba961-e752-eb89-f339-089fb06651f4
* Version Independent ID: f5147198-1751-5d96-dd17-a00291ca0ad5
* Content: [Generic Methods (C# Programming Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/generics/generic-methods)
* Content Source: [docs/csharp/programming-guide/generics/generic-methods.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/generics/generic-methods.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by SuryakantSoniOfficial** [comment]
1. All the methods have different signatures here. This means method's type parameters are considered to be a part of its signature. Hence, these three methods are overloads.
2. Yes, you can use the type parameters in the method block(definition). But a normal code block (`{ }`), which is not a method, cannot have its own type parameters.
3.  Here you go:
`public T GetObjectOfType<T>()
{
    T temp = default(T);
    return temp;
}`
