### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by xamarin-volkan** [dotnet/docs#9041]
Hi, I would like to learn the name of this usage "(Name, ID) = (s, i);"

public Employee(string s, int i) =&gt; (Name, ID) = (s, i);

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5712215d-b167-d9cb-bd51-80df0e300d50
* Version Independent ID: 22b2c77c-2721-9384-3863-046e391ea4b1
* Content: [Constraints on Type Parameters (C# Programming Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/generics/constraints-on-type-parameters)
* Content Source: [docs/csharp/programming-guide/generics/constraints-on-type-parameters.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/generics/constraints-on-type-parameters.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mikkelbu** [comment]
@xamarin-volkan Actually, `(Name, ID) = (s, i)` consists of both a tuple construction, creating the tuple `(s, i)`, and a tuple deconstruction, assigning `s` to `Name` and `i` to `ID`.
