### ISSUE TITLE
Page is older version of an identical page elsewhere in the documentation

### ISSUE THREAD

**Issue by elgonzo** [dotnet/docs#9043]
It looks like an older version of this page: https://docs.microsoft.com/en-us/dotnet/csharp/methods.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de0ee481-866a-602c-a6af-287fe125b04c
* Version Independent ID: 2558e84e-4be6-5136-0d2b-5788dd9eb799
* Content: [Methods (C# Programming Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/methods)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/methods.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/methods.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by rpetrusha** [comment]
Thanks for pointing this out, @elgonzo. @BillWagner, it seems that these are identical topics that have been revised independently of each other. I've created a [project](https://github.com/dotnet/docs/projects/65) to track such instances of duplication.
