### ISSUE TITLE
Heavy use

### ISSUE THREAD

**Issue by 9Rune5** [dotnet/docs#9049]
"will exhaust the number of sockets available under heavy loads"

So, if used properly, a single HttpClient instance will be able to prevent problems arising from ephemeral ports and the like? 

A few more words on how HttpClient handles its underlying resources would be most helpful. What benefits can be reaped by using HttpClient rather than other classes that seemingly does the same thing (harvest content from web sites).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6396a608-2b0b-d2d2-6236-ccc5ac747298
* Version Independent ID: b79d1c28-2664-e045-2723-71f60e6a3248
* Content: [HttpClient Constructor (System.Net.Http)](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.-ctor?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(System.Net.Http.HttpClient.%2523ctor);k(SolutionItemsProject);k(TargetFrameworkMoniker-.NETFramework,Version%3Dv4.6.1);k(DevLang-csharp)%26rd%3Dtrue%26f%3D255%26MSPPError%3D-2147217396&view=netframework-4.7.2)
* Content Source: [xml/System.Net.Http/HttpClient.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Http/HttpClient.xml)
* Product: **dotnet-api**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

**Comment by karelz** [comment]
@9Rune5 what exactly would you suggest? Can you please put up a PR?
IMO the description above is reasonable and sufficient, not sure what else we should use without describing implementation details.

**Comment by 9Rune5** [comment]
We have a "link checker" which basically ends up checking thousands (and then some...) of URLs to see if the links are still alive/reachable. 

Our current version use HttpWebRequest and now I am rewriting this to avoid the aforementioned problems. Converting the code to use HttpClient instead seems like a logical first step.

Thus I need a little more hint on how to use HttpClient. E.g. I already have a static HttpClient instance in my code elsewhere, but I cannot use that instance since I need to pass a HttpClientHandler object with different parameters set.

So how do two HttpClient instances interact to make sure they don't exhaust the number of available connections? Or should I throttle this manually just to be on the safe side?

I have started digging into the HttpClient source code, but it isn't too obvious to me what is going on. (for one thing the implementation under Linux is of course different, so I found it difficult to cover all the bases)

There are other issues as well. SendAsync() can throw a HttpRequestException, but code insight suggests that HttpRequestException is a base class, so I guess I need to check the implementation to figure out if I can get more detailed exception information in some cases (the docs hints at DNS resolution problems as one possible cause IIRC, but doesn't tell me how I can detect that scenario).

**Comment by karelz** [comment]
2 `HttpClient` instances do NOT interact (unless they share same handler) - HttpClient is the boundary everyone can use to isolate and control number of connections and other tweaks.
The key information there is to NOT use new `HttpClient` per request, that's all. Having multiple instances (or recycling instances) is valid scenario, not discouraged.
Depending on your workload, you may need to adjust the usage anyway - for example: If you hit 100K different endpoints at once, you will likely get port exhaustion/timeouts as well (due to 64K limit of ports).

Why would you need to check implementation of `SendAsync` for more detailed exceptions? That is likely implementation dependent and can change without any notice ...

**Comment by karelz** [comment]
You can always just log the exception text. We plan to expose HttpStatus code in future .NET Core releases - https://github.com/dotnet/corefx/issues/26477

I realized that I don't fully know if `HttpClient` instances are isolated on .NET Framework. They are on .NET Core.

Seems to be answered, closing.
