### ISSUE TITLE
Last Example, again

### ISSUE THREAD

**Issue by volkan-yazilim** [dotnet/docs#9050]
colAlias::Hashtable test = new colAlias::Hashtable();

I understand :: means to tell where to start looking for following namespace, type or method. 
But it is neither necessary nor instructive, here.

Thanks for great docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be9c78b1-4949-0bdb-43af-a9db6e5ebffa
* Version Independent ID: cfea46ac-3926-6274-b29e-4c48f1d3cd63
* Content: [How to: Use the Global Namespace Alias (C# Programming Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/namespaces/how-to-use-the-global-namespace-alias#example)
* Content Source: [docs/csharp/programming-guide/namespaces/how-to-use-the-global-namespace-alias.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/namespaces/how-to-use-the-global-namespace-alias.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by jnsn** [comment]
The **See Also** section contains a link to the [Constraints on type parameters](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/generics/constraints-on-type-parameters) article which clarifies the different possibilities of constraints.

In this case, changing
```cs
class ExampleClass<T> where T : new()
```
to 
```cs
class ExampleClass<T> where T : class
```
should suffice for the `new T(1)` call to succeed.
