### ISSUE TITLE
Sample code or simplification please

### ISSUE THREAD

**Issue by xamarin-volkan** [dotnet/docs#9051]
- Use the GetValueOrDefault() method to return either the assigned value, or the default value of the underlying value type if the value of the nullable type is null.
- Use the GetValueOrDefault(T) method to return either the assigned value, or the provided default value if the value of the nullable type is null.

Why is it necessary to make two separate line for these?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab99a9ea-4645-92cd-723a-4a38fbee371e
* Version Independent ID: 652ea928-6ded-800c-6bed-5b1f3f67fe3f
* Content: [Nullable types (C# Programming Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/nullable-types/)
* Content Source: [docs/csharp/programming-guide/nullable-types/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/nullable-types/index.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mikkelbu** [comment]
@xamarin-volkan They are different methods. The first returns the default value of the underlying type if the value of the nullable type is null. The second method returns the provided value if the value of the nullable type is null.

**Comment by sadqiang** [comment]
The article said that:
> Nullable types represent value-type variables that can be assigned the null value. You cannot create a nullable type based on a reference type. (Reference types already support the null value.)

My comment:
Now in the incoming C# 8.0, a reference type can be a nullable type.
The article above needs some modification, right?
