### ISSUE TITLE
What is valueOfA, here?

### ISSUE THREAD

**Issue by xamarin-volkan** [dotnet/docs#9052]
if (aNullableBoxed is int valueOfA)
{
    Console.WriteLine($"aNullableBoxed is boxed int: {valueOfA}");
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2552ed95-c11d-4657-0dad-9e0cccba9ca4
* Version Independent ID: 326dd492-3549-0312-3d46-a179d3fe76c6
* Content: [Using nullable types (C# Programming Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/nullable-types/using-nullable-types#boxing-and-unboxing)
* Content Source: [docs/csharp/programming-guide/nullable-types/using-nullable-types.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/nullable-types/using-nullable-types.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mikkelbu** [comment]
@xamarin-volkan It is a variable of type `int`. This is using the pattern-matching construct. Before one could have written it as follows:
```csharp
if (aNullableBoxed is int)
{
    int valueOfA = (int) aNullableBoxed;
    Console.WriteLine($"aNullableBoxed is boxed int: {valueOfA}");
}
```

**Comment by rpetrusha** [comment]
Thanks for your question, @xamarin-volkan, and for your answer, @mikkelbu. You can read more about pattern matching in the [C# Pattern matching](https://docs.microsoft.com/en-us/dotnet/csharp/pattern-matching) article. 
Since pattern matching is adequately documented, I'll close this issue.
