### ISSUE TITLE
String.IndexOf(Char,StringComparison)

### ISSUE THREAD

**Issue by af4jm** [dotnet/docs#9054]
documentation is missing for subject method... and String.LastIndexOf(Char,StringComparison) entire method is missing, which doesn't make sense for IndexOf to have the StringComparison overload but LastIndexOf to not have it

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a56dabf0-0019-e842-8cf0-31b3da5d1e79
* Version Independent ID: 0cde8a5d-1c97-0376-cacb-a8e0a7303e85
* Content: [String.IndexOf Method (System)](https://docs.microsoft.com/en-us/dotnet/api/system.string.indexof?view=netcore-2.1#System_String_IndexOf_System_Char_System_StringComparison_)
* Content Source: [xml/System/String.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System/String.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
Thanks for pointing out the missing documentation, @af4jm. We've opened dotnet/dotnet-api-docs#739 to document it. 
In terms of String.LastIndexOf(Char, StringComparison), feel free to open an issue in the [dotnet/coreclr](https://github.com/dotnet/coreclr/issues) repo that recommends adding the API.
