### ISSUE TITLE
dotnet new -u <FILE_SYSTEM_DIRECTORY> appears to require an absolute path

### ISSUE THREAD

**Issue by kenlefeb** [dotnet/docs#9060]
If I use a relative path with the `--uninstall` command, it responds with an error message that it cannot find anything to uninstall, even though I just installed from a relative path moments before.

The error was `Could not find something to uninstall called '.\directory-name\'.`

Perhaps the documentation, here, should mention this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e7deb06-37bb-b659-7cf3-9c47a91e065e
* Version Independent ID: d6e6f989-3956-6a0e-5e9c-fb3d1f9bd751
* Content: [Custom templates for dotnet new](https://docs.microsoft.com/en-us/dotnet/core/tools/custom-templates#uninstalling-a-template)
* Content Source: [docs/core/tools/custom-templates.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/custom-templates.md)
* Product: **dotnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Thanks @kenlefeb for your feedback. We do cover that in the dotnet new reference but I'll add something here too:
![image](https://user-images.githubusercontent.com/12971179/48581760-87472700-e8d7-11e8-9a0a-eef53f126cf2.png)

**Comment by kenlefeb** [comment]
Ha! I didn't even realize I wasn't at the canonical reference for `dotnet new`! Thanks!
