### ISSUE TITLE
Code ain't compiling nor working

### ISSUE THREAD

**Issue by maristhek** [dotnet/docs#9071]
A direct copy and paste of Program.cs in SentimentAnalysis code, using VS2017 15.7.6 generates the "The name xxx does not exist in the current context" errors for Train, Predict, and PredictWithModelLoadedFromFile functions and a "Non-invocable member 'Evaluate" cannot be used like a method" exception.

It's configged as a .NET Core 2.1 ConsoleApplication.

The usings :
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Microsoft.ML;
using Microsoft.ML.Core.Data;
using Microsoft.ML.Runtime.Api;
using Microsoft.ML.Runtime.Data;
using Microsoft.ML.Transforms.Text;

The code :
namespace SentimentAnalysis
{
    class Program
    {
        static readonly string _trainDataPath = Path.Combine(Environment.CurrentDirectory, "Data", "wikipedia-detox-250-line-		data.tsv");
        static readonly string _testDataPath = Path.Combine(Environment.CurrentDirectory, "Data", "wikipedia-detox-250-line-		test.tsv");
        static readonly string _modelPath = Path.Combine(Environment.CurrentDirectory, "Data", "Model.zip");
        static TextLoader _textLoader;

        static void Main(string[] args)
        {
            MLContext mlContext = new MLContext(seed: 0);
            // &lt;/Snippet3&gt;

            // The TextLoader loads a dataset with comments and corresponding postive or negative sentiment. 
            // When you create a loader, you specify the schema by passing a class to the loader containing
            // all the column names and their types. This is used to create the model, and train it. 
            // Initialize our TextLoader
            // &lt;Snippet4&gt;
            _textLoader = mlContext.Data.TextReader(new TextLoader.Arguments()
            {
                Separator = "tab",
                HasHeader = true,
                Column = new[]
                                                                {
                                                                  new TextLoader.Column("Label", DataKind.Bool, 0),
                                                                  new TextLoader.Column("SentimentText", DataKind.Text, 1)
                                                                }
            }
            );
            // &lt;/Snippet4&gt;

            // &lt;Snippet5&gt;
            var model = Train(mlContext, _trainDataPath);
            // &lt;/Snippet5&gt;

            // &lt;Snippet11&gt;
            Evaluate(mlContext, model);
            // &lt;/Snippet11&gt;

            // &lt;Snippet16&gt;
            Predict(mlContext, model);
            // &lt;/Snippet16&gt;

            // &lt;Snippet25&gt;
            PredictWithModelLoadedFromFile(mlContext);
            // &lt;/Snippet25&gt;

            Console.WriteLine();
            Console.WriteLine("=============== End of process ===============");
        }

    }
}

Please advise !!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8e22825-c4ee-5a36-f911-8ad456970ecc
* Version Independent ID: ad0bf640-7dfc-1184-077c-358bb14277a7
* Content: [Use ML.NET in a sentiment analysis binary classification scenario](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/sentiment-analysis)
* Content Source: [docs/machine-learning/tutorials/sentiment-analysis.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/sentiment-analysis.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by maristhek** [comment]
Sorry. My bad coupla typos in the translation.

However be aware :
Need these tags in your <PropertyGroup> in the .csproj file :
<RuntimeIdentifiers>win10-x64</RuntimeIdentifiers>
<LangVersion>7.1</LangVersion>

**Comment by maristhek** [comment]
Correction since posting removes raw tags
"<TargetFramework>netcoreapp2.1</TargetFramework>"
"<RuntimeIdentifiers>win10-x64</RuntimeIdentifiers>"

**Comment by maristhek** [comment]
One more time :
&ltruntimeIdentifiers&gtwin10-x64&lt/runtimeIdentifiers&gt
&ltLangVersion&gt7.1&lt/LangVersion&gt

**Comment by mairaw** [comment]
@JRAlexander can you triage this issue?

**Comment by JRAlexander** [comment]
Hi @maristhek, It looks like you only have main in your code above. Unless that is an excerpt, You may be missing the rest of the code.  Please try downloading the complete sample from here and see if that fixes it. Thanks!

**Comment by maristhek** [comment]
Sorry, just jumped the gun on a bad assumption.  Was not a good day.

... and tried to post the need to include the following tags in csproj and the feedback comment area HTML formatter mangled it badly
<RuntimeIdentifiers>win10-x64</RuntimeIdentifiers>
<LangVersion>7.1</LangVersion>

I suggest putting a note in the docs to do so.  BTW i'm runing on Win Srv 2012 R2

**Comment by JRAlexander** [comment]
Thanks, @maristhek, for following up. I'm glad you got this resolved! We'll look at adding the tags in the sample.
