### ISSUE TITLE
Unexpected binary values for short binary numbers

### ISSUE THREAD

**Issue by guganems** [dotnet/docs#9075]
If we try to print number using toString() which doesn't consists of "thousands of" bits, we get unexpected results, like:

uint a = 0b10111011;
uint b = ~a;
Console.WriteLine(Convert.ToString(b, toBase: 2));
// Output:
// 11111111111111111111111101000100

It seems that all, even unused 0-s converted to 1-s

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a212a5d3-05d9-ed88-cde9-128189a5952e
* Version Independent ID: a0e653f2-1541-7fcd-01dd-10c32e6eeb85
* Content: [~ Operator (C# Reference)](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/bitwise-complement-operator)
* Content Source: [docs/csharp/language-reference/operators/bitwise-complement-operator.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/operators/bitwise-complement-operator.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by svick** [comment]
There's no such thing as "unused zeroes". Why did you expect that leading zeroes would not be changed by the `~` operator? Do you think the article is unclear? Do you have a suggestion on how to improve it?
