### ISSUE TITLE
ReadOnlyCollection<T> clarification

### ISSUE THREAD

**Issue by desmondgc** [dotnet/docs#9076]
Regarding "Collection Properties and Return Values," I think the guideline could use some clarification.

"In general, prefer ReadOnlyCollection&lt;T&gt;."

I think it would be helpful to distinguish between ReadOnlyCollection&lt;T&gt; and IReadOnlyCollection&lt;T&gt;. Is the guideline explicitly recommending the concrete type rather than an interface for return values?

What about System.Collections.Immutable?

It's clear there is some debate/confusion within the community, and the guideline here feels somewhat airy.

* https://stackoverflow.com/questions/24880268/ienumerable-vs-ireadonlycollection-vs-readonlycollection-for-exposing-a-list-mem
* https://stackoverflow.com/questions/491375/readonlycollection-or-ienumerable-for-exposing-member-collections

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 054b4dfe-1565-dbec-2f8e-b62716d0fe41
* Version Independent ID: f51a9db2-d49a-0079-89c7-32d8a56131f2
* Content: [Guidelines for Collections](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/guidelines-for-collections)
* Content Source: [docs/standard/design-guidelines/guidelines-for-collections.md](https://github.com/dotnet/docs/blob/master/docs/standard/design-guidelines/guidelines-for-collections.md)
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by rpetrusha** [comment]
Thank you for your feedback, @desmondgc. Because this material has been reprinted with the permission of  Pearson Education, Inc, we are unable to modify this content. Because of this, I'll close this issue.
