### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by es-repo** [dotnet/docs#9077]
While idempotence mean that same call returns the same result it would be more correct to say that queries are side-effect free in the sentence below:

"The essence of those patterns, and the important point here, is that queries are idempotent: no matter how many times you query a system, the state of that system will not change."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84d83855-4370-90e8-024a-12c5ac8220e9
* Version Independent ID: 01be3db1-4a00-c8f2-aa59-59656f206b93
* Content: [Applying CQRS and CQS approaches in a DDD microservice in eShopOnContainers](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/microservice-ddd-cqrs-patterns/eshoponcontainers-cqrs-ddd-microservice#feedback)
* Content Source: [docs/standard/microservices-architecture/microservice-ddd-cqrs-patterns/eshoponcontainers-cqrs-ddd-microservice.md](https://github.com/dotnet/docs/blob/master/docs/standard/microservices-architecture/microservice-ddd-cqrs-patterns/eshoponcontainers-cqrs-ddd-microservice.md)
* Product: **dotnet**
* GitHub Login: @CESARDELATORRE
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
@CESARDELATORRE @mvelosop can you comment on this issue?

**Comment by CESARDELATORRE** [comment]
Well, I agree, we can add "**,meaning that queries are side-effect free.**" or similar at the end of that sentence. 👍 
I just added a small PR for that. 👍
