### ISSUE TITLE
Invalid external url  for Standard ECMA-334 5th Edition

### ISSUE THREAD

**Issue by ziasistani** [dotnet/docs#9078]
Page Item "Standard ECMA-334 5th Edition"
Proposed Resolution: Change "ecma" in the url to UPPERCASE
Bad   URL : "https://www.ecma-international.org/publications/files/ECMA-ST/Ecma-334.pdf"
Good URL : "http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-334.pdf"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c72c5185-07d6-017f-5dde-3580a3a33609
* Version Independent ID: 26905192-8e31-d5e4-fdea-915754e225bf
* Content: [C# 6.0 draft language specification](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/index)
* Content Source: [docs/csharp/language-reference/language-specification/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/language-specification/index.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for pointing this out @ziasistani 

I agree with your proposed resolution.  Do you want to submit a PR for this? (If not, I'll make the fix).

**Comment by pkulikov** [comment]
Remark on the good URL: it can still be https

**Comment by BillWagner** [comment]
Good catch (I misread that and thought the existing was "http:")

**Comment by mairaw** [comment]
So the good URL should be https://www.ecma-international.org/publications/files/ECMA-ST/ECMA-334.pdf

**Comment by svick** [comment]
@ziasistani It looks like you created the Pull Request on your fork of the repository ([ziasistani/docs](https://github.com/ziasistani/docs)), which means it won't have any effect. Can you recreate the Pull Request in this repository?

**Comment by ziasistani** [comment]
Dear @svick 
What I did was according to .NET Docs Contributing Guide(https://github.com/dotnet/docs/blob/master/CONTRIBUTING.md)
Which step I did wrong ?

**Comment by svick** [comment]
@ziasistani Looks like you figured it out. The PR you created now (https://github.com/dotnet/docs/pull/9100) is correct.
