### ISSUE TITLE
Sentiment Analysis not working correctly

### ISSUE THREAD

**Issue by rah132** [dotnet/docs#9081]
I have copied and run the Sentiment Analytics project.  The result predicts that "He is the best, and the article should say that." is Toxic with a Probability of 0.9918675!!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e855e630-1a30-d138-4ac6-bfeefebf9aae
* Version Independent ID: afc0a7d1-d3c2-acf2-d4ea-d2565e22b237
* Content: [ML.NET tutorials](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/)
* Content Source: [docs/machine-learning/tutorials/index.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/index.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by JRAlexander** [comment]
This is resolved. I missed adding it to the PR.
