### ISSUE TITLE
https://docs.microsoft.com/en-us/dotnet/framework/security/json-web-token-handler

### ISSUE THREAD

**Issue by xboysms** [dotnet/docs#9088]
How to run it on project ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55593a45-0e29-f738-cc92-d8537eca1569
* Version Independent ID: 772101df-914a-20b6-d442-4a97b8677f6c
* Content: [JSON Web Token Handler](https://docs.microsoft.com/en-us/dotnet/framework/security/json-web-token-handler)
* Content Source: [docs/framework/security/json-web-token-handler.md](https://github.com/dotnet/docs/blob/master/docs/framework/security/json-web-token-handler.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by gewarren** [comment]
Looks like we could link to this sample: https://github.com/Azure-samples/active-directory-dotnet-webapi-manual-jwt-validation
