### ISSUE TITLE
Help with understanding the example

### ISSUE THREAD

**Issue by sfinotto** [dotnet/docs#9090]
Hi. I believe I can understand the query except for "group newGroup2 by newGroup1.Key;".
I'd find it helpful if the example adds a few sentences to explain why or how newGroup2 can be grouped by newGroup1.Key . 
I see each newGroup2 contains the students from a certain year grouped by last name, but I don't get how newGroup1.Key is available to be used as key to group the newGroups2.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 728b8960-bd9b-6e47-0697-1ede60319dcc
* Version Independent ID: f2080e9b-3a61-ec89-eb34-b61aff1641fa
* Content: [Create a nested group (LINQ in C#)](https://docs.microsoft.com/en-us/dotnet/csharp/linq/create-a-nested-group)
* Content Source: [docs/csharp/linq/create-a-nested-group.md](https://github.com/dotnet/docs/blob/master/docs/csharp/linq/create-a-nested-group.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by LJ9999** [comment]
Good luck getting a response. I think there was only one developer in Redmond who wrote that confusing unexplained crap and he quit.
