### ISSUE TITLE
missing parentheses in C# syntax spec for catch / when

### ISSUE THREAD

**Issue by jibal** [dotnet/docs#9094]
catch ExceptionType [e] when (expr)

should be

catch (ExceptionType [e]) when (expr)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ef10b29-fbf8-5af9-8f8b-a694a1416e33
* Version Independent ID: 15502bbc-5355-2add-0fa8-ae31dc01c122
* Content: [when (C# Reference)](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/when)
* Content Source: [docs/csharp/language-reference/keywords/when.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/when.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by svick** [comment]
Do you want to fix the error yourself by submitting a Pull Request? If you do and don't know how, [you might want to read this guide](https://docs.microsoft.com/en-us/contribute/#quick-edits-to-existing-documents).
