### ISSUE TITLE
Simple and useful, clear examples.

### ISSUE THREAD

**Issue by jvargasvillegas** [dotnet/docs#9095]
This step by step is really useful. I like a lot the statements about what an abstract class/field may or must do and what they do not do.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c00e23c2-618d-0b84-8ea8-0b0b4de1101a
* Version Independent ID: 8c00f924-bf5a-a748-331d-3809321e5547
* Content: [abstract (C# Reference)](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/abstract)
* Content Source: [docs/csharp/language-reference/keywords/abstract.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/abstract.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for the compliments.  Closing as kudos.
