### ISSUE TITLE
Quick links not working

### ISSUE THREAD

**Issue by jonsing** [dotnet/docs#9099]
In the table with quick links many points to pages that dosent exist any more e.g "Download page for 4.7.1 web installer".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf46f86d-940f-3d1b-a83c-6ced0ead20bb
* Version Independent ID: 56305860-d431-de58-1503-cdf57e4814b5
* Content: [Install the .NET Framework developer pack or redistributable](https://docs.microsoft.com/en-us/dotnet/framework/install/guide-for-developers)
* Content Source: [docs/framework/install/guide-for-developers.md](https://github.com/dotnet/docs/blob/master/docs/framework/install/guide-for-developers.md)
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by Thraka** [comment]
Just noticed this issue and tested the links. They are working OK.

Sorry for the delay.
