### ISSUE TITLE
Some background would be nice

### ISSUE THREAD

**Issue by zspitz** [dotnet/docs#9102]
Describing why this limitation exists would be a nice addition.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77652ea7-f08b-6024-ec90-7899488cb988
* Version Independent ID: 70e8934d-9d82-acbc-f190-b7b6b9f230b3
* Content: [Compiler Error CS0825](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs0825)
* Content Source: [docs/csharp/misc/cs0825.md](https://github.com/dotnet/docs/blob/master/docs/csharp/misc/cs0825.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by jmarkman** [comment]
Although it's not an urgent priority, I was interested in trying my hand at this.
