### ISSUE TITLE
I understand passing by reference like this, when use ref keyword, is right?

### ISSUE THREAD

**Issue by CwjXFH** [dotnet/docs#9111]
**init:**
```c#
var array = new string[] {"csharp","java","python","go"};
var value = array[0];
ref var refValue = ref array[0];
```

![image](https://user-images.githubusercontent.com/11468733/48683894-3478b280-ebea-11e8-804b-9dff5070135d.png)

**modify value**, it will point another object and doesn't effect the original array
```c#
value = "dotnet";
```
![image](https://user-images.githubusercontent.com/11468733/48683971-8c171e00-ebea-11e8-9bf0-6db308194e7c.png)

**modify refValue**, it point a new object and will change the original array element's value
```c#
refValue = "dotnet";
```

![image](https://user-images.githubusercontent.com/11468733/48684309-05634080-ebec-11e8-857e-234437d3ba36.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d67349b-72bc-b7cf-f754-fa62d1fb592d
* Version Independent ID: 4f413bcc-90e7-d971-fe75-b4876124e75d
* Content: [ref keyword (C# Reference)](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/ref#ref-locals)
* Content Source: [docs/csharp/language-reference/keywords/ref.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/ref.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Your understanding is correct @CwjXFH 

Closing as the doc is correct.

**Comment by FrankHileman** [comment]
I would like to see an example using a struct as well.

**Comment by CwjXFH** [comment]
@FrankHileman 

Maybe this example will help you, in the picture below, **refValue** passed by ref,  has the same address and value with **num**; argument **value** passed by value, it just has the same value with **num**, the address is different.

![](https://user-images.githubusercontent.com/11468733/79937005-618a5e00-848b-11ea-88bf-7550e744e467.png)





And recommended that you read the following document:  

[Passing Parameters (C# Programming Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/passing-parameters)  
[Method Parameters (C# Reference)](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/method-parameters)  
[The address-of operator](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/unsafe-code#the-address-of-operator)
