### ISSUE TITLE
Missing compiler option: -shared

### ISSUE THREAD

**Issue by zuckerthoben** [dotnet/docs#9119]
You can use the shared flag to use the compiler server. Please document this option as its not well documented overall but quite important I think.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b29fc27-0985-b3ea-e1d4-338c1dc126ed
* Version Independent ID: cc362e14-4bcb-0b38-36ce-9b8502e5e4e2
* Content: [C# Compiler Options Listed Alphabetically](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/listed-alphabetically)
* Content Source: [docs/csharp/language-reference/compiler-options/listed-alphabetically.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/listed-alphabetically.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@jcouv are you familiar with the "shared" option?

**Comment by jcouv** [comment]
Not really, but we do have some compiler doc on the topic:
https://github.com/dotnet/roslyn/blob/master/docs/compilers/Compiler%20Server.md

**Comment by zuckerthoben** [comment]
I advise to add a small summary to the doc mentioned in OP and to add the extended documentation as a link.
