### ISSUE TITLE
Signed assemblies: It's not clear what to do with the 2 files created in previous step

### ISSUE THREAD

**Issue by dombat** [dotnet/docs#9120]
In the previous tutorial we created a keypair file and extracted the public key into a separate file. 

In this tutorial it says "In the Choose a strong name key file box, choose &lt;Browse…&gt;, and then navigate to the key file. " Which key file? At this point I have created 2.

It later says;
"keyfileName: The name of the container or file that contains the key pair. Assembly Linker interprets a relative path in relationship to the current directory." 
This is more obvious. The question remains, what should we do with the public key file we created in the previous tutorial?

For beginners trying to follow the steps, there is some ambiguity in the tutorials.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cadf5e8-f790-3892-d187-6fafd9a5647b
* Version Independent ID: 8993ead4-6e89-f6fe-9b39-730194d59f7f
* Content: [How to: Sign an Assembly with a Strong Name](https://docs.microsoft.com/en-us/dotnet/framework/app-domains/how-to-sign-an-assembly-with-a-strong-name)
* Content Source: [docs/framework/app-domains/how-to-sign-an-assembly-with-a-strong-name.md](https://github.com/dotnet/docs/blob/master/docs/framework/app-domains/how-to-sign-an-assembly-with-a-strong-name.md)
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by Thraka** [comment]
This could be improved. I'll add it to the backlog and see if the community would like to take this on. Thanks!
