### ISSUE TITLE
Rewrite example using Task-based Asynchronous Pattern

### ISSUE THREAD

**Issue by vanillajonathan** [dotnet/docs#9121]
Example code is written using the old `IAsyncResult` pattern.
Rewrite examples using [Task-based Asynchronous Pattern](https://docs.microsoft.com/en-us/dotnet/standard/asynchronous-programming-patterns/task-based-asynchronous-pattern-tap).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91e33dad-b973-a334-e6d2-203472cb9aca
* Version Independent ID: 8a42e2e8-6617-74e0-81fc-009df48fff82
* Content: [Asynchronous Client Socket Example](https://docs.microsoft.com/en-us/dotnet/framework/network-programming/asynchronous-client-socket-example)
* Content Source: [docs/framework/network-programming/asynchronous-client-socket-example.md](https://github.com/dotnet/docs/blob/master/docs/framework/network-programming/asynchronous-client-socket-example.md)
* Product: **dotnet-framework**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

**Comment by HamidMolareza** [comment]
I hope this is useful:
[Rewritten according to the **Task-based Asynchronous Pattern**](https://github.com/HamidMolareza/AsynchronousClient)

**Comment by vanillajonathan** [comment]
@HamidMolareza,
The code still have references to Begin* and End*.
https://github.com/HamidMolareza/AsynchronousClient/blob/master/AsynchronousClient/Program.cs#L114
https://github.com/HamidMolareza/AsynchronousClient/blob/master/AsynchronousClient/Program.cs#L60

Which is part of the old `IAsyncResult` API.

**Comment by HamidMolareza** [comment]
@vanillajonathan
If i use base methods like Socket.Send(), Receive() and so on, is it useful to you?

**Comment by HamidMolareza** [comment]
@vanillajonathan
Please see this updated source.
IAsyncResult methods (like Begin* and End*) have been removed:
[Template2 - AsynchronousClient](https://github.com/HamidMolareza/AsynchronousClient/blob/master/AsynchronousClient/Template2.cs)

**Comment by vanillajonathan** [comment]
@HamidMolareza This is better.
Maybe it should use `Encoding.UTF8` instead of `Encoding.ASCII` though.

Line 112 looks suspicious.
But [line 112](https://github.com/HamidMolareza/AsynchronousClient/blob/master/AsynchronousClient/Template2.cs#L112) and [line 132](https://github.com/HamidMolareza/AsynchronousClient/blob/master/AsynchronousClient/Template2.cs#L132) looks suspicious. Is that wrapping the result of a synchronous method in a task instead of calling an asynchronous method?

**Comment by HamidMolareza** [comment]
I checked, you're right. Those lines are not really asynchronous. (Also line 68)  :(

So after looking at the [.NET Framework source](https://referencesource.microsoft.com), I saw the two methods used here:
1- [TaskFactory.FromAsync](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.taskfactory.fromasync?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(System.Threading.Tasks.TaskFactory.FromAsync%60%601);k(TargetFrameworkMoniker-.NETFramework,Version%3Dv4.6.1);k(DevLang-csharp)%26rd%3Dtrue&view=netframework-4.7.2) that is used in [Template1 source](https://github.com/HamidMolareza/AsynchronousClient/blob/master/AsynchronousClient/Template1.cs) and recommended for converting patterns.
2- [TaskFactory.StartNew](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.taskfactory.startnew?view=netframework-4.7.2) or [Task.Run](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.task.run?view=netframework-4.7.2) that will be created on a new thread. (Not the current thread)

I did not find another way.

**Comment by HamidMolareza** [comment]
@vanillajonathan
I checked, you're right. Those lines are not really asynchronous. (Also line 68)  :(

So after looking at the [.NET Framework source](https://referencesource.microsoft.com), I saw the two methods used here:
1- [TaskFactory.FromAsync](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.taskfactory.fromasync?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(System.Threading.Tasks.TaskFactory.FromAsync%60%601);k(TargetFrameworkMoniker-.NETFramework,Version%3Dv4.6.1);k(DevLang-csharp)%26rd%3Dtrue&view=netframework-4.7.2) that is used in [Template1 source](https://github.com/HamidMolareza/AsynchronousClient/blob/master/AsynchronousClient/Template1.cs) and recommended for converting patterns.
2- [TaskFactory.StartNew](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.taskfactory.startnew?view=netframework-4.7.2) or [Task.Run](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.task.run?view=netframework-4.7.2) that will be created on a new thread. (Not the current thread)

I did not find another way.

**Comment by zenith85** [comment]
**Attention** "save the noobs"
This code doesn't work out of the BOX , there is a hidden error , the client will simply closes up the console without a successful attempt of connection. 

Solution: 
Line 40 . change 
IPHostEntry ipHostInfo = Dns.GetHostEntry("host.contoso.com");
Into 
IPHostEntry ipHostInfo = Dns.GetHostEntry(Dns.GetHostName());

**Attention "is over"**

P. S. for this thread owner , i am very thankful, if you correct the code , please delete my attention Comment. 
Thanks.

**Comment by svick** [comment]
The sibling article, [Asynchronous Server Socket Example](https://docs.microsoft.com/en-us/dotnet/framework/network-programming/asynchronous-server-socket-example) should also be updated to use `async`-`await` instead of APM.
