### ISSUE TITLE
Confusing Tutorial

### ISSUE THREAD

**Issue by regal60740** [dotnet/docs#9129]
The tutorial is very confusing. There are lines of code but not clear instructions on what to do with the code. Do we always have to refer to GitHub code to figure out what the author is talking about?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 948bdbcf-e49f-bd3a-89c4-d83f86cfddc5
* Version Independent ID: 5c6e688e-7afa-1201-2887-e3cae35abe54
* Content: [Microservices hosted in Docker - C#](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/microservices)
* Content Source: [docs/csharp/tutorials/microservices.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/microservices.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
That tutorial is outdated.  I'm going to remove it and re-direct the link to our Docker section under the .NET Core guide. That content is more up to date.
