### ISSUE TITLE
URI to ECMA-334 document doesn't work

### ISSUE THREAD

**Issue by Styxxy** [dotnet/docs#9132]
The URI to Standard ECMA-334 5th Edition document (https://www.ecma-international.org/publications/files/ECMA-ST/Ecma-334.pdf) doesn't work. It gives a 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c72c5185-07d6-017f-5dde-3580a3a33609
* Version Independent ID: 26905192-8e31-d5e4-fdea-915754e225bf
* Content: [C# 6.0 draft language specification](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/index)
* Content Source: [docs/csharp/language-reference/language-specification/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/language-specification/index.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
Thanks for your feedback @Styxxy. This is fixed by the PR #9100 which is going live in a few hours.
