### ISSUE TITLE
The title does not align with what the article is describing

### ISSUE THREAD

**Issue by fabfella** [dotnet/docs#9136]
The title says "...Make an Object follow the Mouse Pointer" yet the sentence underneath says "This example shows how to change the dimensions of an object"

So basically this article does not show how the object follows the mouse it shows how the object's dimension is changed using the MouseMoveHandler.

I clicked on this article because I wanted to see how to make an object move with the mouse, not to see if the dimensions change.

Please could this article be updated to show C# code on how to get an object to move with the mouse pointer" 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de122630-13b5-cfce-5c63-481c78e380ea
* Version Independent ID: d01a4f34-29e7-e00f-6a2b-28c6040f43ff
* Content: [How to: Make an Object Follow the Mouse Pointer](https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/how-to-make-an-object-follow-the-mouse-pointer)
* Content Source: [docs/framework/wpf/advanced/how-to-make-an-object-follow-the-mouse-pointer.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/advanced/how-to-make-an-object-follow-the-mouse-pointer.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by elgonzo** [comment]
The verb "follow" has several meanings. One of it is like "to watch", "to keep mind on" (see Merriam-Webster dictionary, point 8a,b,c: https://www.merriam-webster.com/dictionary/follow). In this sense, the title does align with the article.

But i agree, the title should be rephrased to avoid this kind of misunderstanding.
