### ISSUE TITLE
Show how to configure client and server on different machines

### ISSUE THREAD

**Issue by skst** [dotnet/docs#9142]
This sample is extremely limited. Very few WCF apps will run on the same computer. Please show how to configure the client and server to run on different machines.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81879896-7161-3352-eecb-87a2158dc003
* Version Independent ID: 286eb468-4007-fc0d-1d33-76139225d565
* Content: [How to: Use a Windows Communication Foundation Client](https://docs.microsoft.com/en-us/dotnet/framework/wcf/how-to-use-a-wcf-client)
* Content Source: [docs/framework/wcf/how-to-use-a-wcf-client.md](https://github.com/dotnet/docs/blob/master/docs/framework/wcf/how-to-use-a-wcf-client.md)
* Product: **dotnet-framework**
* GitHub Login: @Lxiamail
* Microsoft Alias: **wcfsrvt**

**Comment by Khad515** [comment]
Yea, actually, im looking for some information about that.

**Comment by jonaramos** [comment]
When you add the Service Reference on the client, instead of clicking the Discover button, you have to type in the endpoint Url of your WFC service hosted on the remote machine.

**Comment by willemgons** [comment]
The writing of a WCF Service / Client combination and local testing is EASY. Then come the ifs and buts. In our case we have 4 servers carrying approx 60 client webs and Databases in total. This is the first time that we decided to write WCF to publish only to those IIS / Server combinations that needed it. Typing endpoints is NOT the answer. The answer is probably in adding the config items into the service codebase itself. Anyone out there who has a definitive approach as to HOW TO implement the WCF client into a large MVC web application COULD greatly assist here.

**Comment by willemgons** [comment]
Turns out that the correct answer for us is to use web.config transforms.
