### ISSUE TITLE
Not enough documentation

### ISSUE THREAD

**Issue by trogan42** [dotnet/docs#9143]
"' Insert code here that implements this method.". Please do so. And also insert code that calls an implemented method.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 452fa284-1197-faa8-c9e4-377a98c05ede
* Version Independent ID: bc9e24e7-1ffe-bab3-f99b-c4244d01195c
* Content: [Interfaces (Visual Basic)](https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/language-features/interfaces/)
* Content Source: [docs/visual-basic/programming-guide/language-features/interfaces/index.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/programming-guide/language-features/interfaces/index.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by KathleenDollard** [comment]
I'm a bit confused about what you are looking for here. The code of the method is not relevant to how the point of an article - how an interface works. 

If you have a specific suggestion, there is an Edit button on each docs page. That leads you through about four steps to submitting a PR to docs.

**Comment by trogan42** [comment]
Thx Kathleen. Like most developers I would think, I go straight to the code, when trying to develop an understanding of what a new concept does. A good example of this is found at https://www.dotnetperls.com/interface-vbnet. … Tony
