### ISSUE TITLE
Breaking changes in .NET Core 2.1 structs

### ISSUE THREAD

**Issue by martinsuchan** [dotnet/docs#9148]
There are breaking changes in some .NET Core 2.1 structs - these structs now have private fields and cannot be instantiated without `new`. There should be probabaly some official "breaking changes" section in this document.
https://github.com/dotnet/corefx/issues/6185

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bc74517-2839-4b16-8539-d31aba49bcfd
* Version Independent ID: 5511dd8b-d5d6-a3fb-172a-f35ff530cfc8
* Content: [What's new in .NET Core 2.1](https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-2-1)
* Content Source: [docs/core/whats-new/dotnet-core-2-1.md](https://github.com/dotnet/docs/blob/master/docs/core/whats-new/dotnet-core-2-1.md)
* Product: **dotnet-core**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by gewarren** [comment]
@martinsuchan Thanks, we will document this as a breaking change.
