### ISSUE TITLE
More Information Would be Useful

### ISSUE THREAD

**Issue by PatrickRyder** [dotnet/docs#9150]
"...consider using a class type constraint or interface constraint."

A link to an example of how to do this would be extremely useful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f834b78-2763-76ec-68ef-9403dc419bc4
* Version Independent ID: 305a297d-c23c-713e-91aa-1e28743213d2
* Content: [Compiler Error CS0417](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0417)
* Content Source: [docs/csharp/language-reference/compiler-messages/cs0417.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-messages/cs0417.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by jnsn** [comment]
The **See Also** section contains a link to the [Constraints on type parameters](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/generics/constraints-on-type-parameters) article which clarifies the different possibilities of constraints.

In this case, changing
```cs
class ExampleClass<T> where T : new()
```
to 
```cs
class ExampleClass<T> where T : class
```
should suffice for the `new T(1)` call to succeed.
