### ISSUE TITLE
--no-build does not implicitly set --no-restore

### ISSUE THREAD

**Issue by adam-c-anderson** [dotnet/docs#9154]
The docs state that it does, but when running `dotnet test` with only `--no-build`, the output clearly shows attempts to restore packages. Adding the `--no-restore` flag stops this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61ca4064-7481-a263-60fc-c70127f2ad16
* Version Independent ID: 2878af44-8208-7bd8-46d4-3acda3e82ce0
* Content: [dotnet test command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-test?tabs=netcore21)
* Content Source: [docs/core/tools/dotnet-test.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-test.md)
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by tdykstra** [comment]
@adam-c-anderson I just tried this and the implicit no-restore for `--no-build` seems to be working as documented. Do you still see restores happening for `--no-build`, and if so what version of the SDK are you using?

**Comment by adam-c-anderson** [comment]
Oh dear, 1.5 year old issue and submitted through docs.microsoft.com, so the usual cues to provide this information were missing for me. You can probably assume it was whatever the current version was at the time, but it's too long ago for me to recall now.

**Comment by tdykstra** [comment]
Sorry for delayed response. Since I can't repro I'll close this issue -- if you run across the problem again in the future feel free to reopen.
