### ISSUE TITLE
missing documentation on how to add "cs files" to a dotnet core project from visual studio code 

### ISSUE THREAD

**Issue by wm2015email** [dotnet/docs#9155]
I wanted to use visual studio code and dotnet core to write a console application, however, the tutorial section for using visual studio code with dotnet core doesn't have any explaination on how to have a project with more than one cs file.  so I gave up on on using .netcore and switched to python instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cc2e9c2-f333-f6a1-064e-790d950b684c
* Version Independent ID: 25a4c9b9-2808-e296-df03-5837000dcbad
* Content: [Get started with C# and Visual Studio Code - C# Guide](https://docs.microsoft.com/en-us/dotnet/core/tutorials/with-visual-studio-code)
* Content Source: [docs/core/tutorials/with-visual-studio-code.md](https://github.com/dotnet/docs/blob/master/docs/core/tutorials/with-visual-studio-code.md)
* Product: **dotnet-core**
* GitHub Login: @kendrahavens
* Microsoft Alias: **mairaw**

**Comment by kendrahavens** [comment]
We should definitely add a section on how to add a .cs file to a dotnet project. Thank you for providing feedback! @KathleenDollard @livarcocc 

In case others are running into this same issue:

To add a .cs file right click in the File Explorer in VSCode and select "New File." Name the new file and add the .cs extension at the end. .NET Core projects are folder based so any .cs file in the same folder or sub folder of a .csproj is a part of the project. (Make sure the new file uses the appropriate namespace as well.)

![image](https://user-images.githubusercontent.com/8293542/49415163-a7297800-f72a-11e8-9c96-26ccc36b8ea1.png)

You can also use the New File icon in the VSCode Explorer.
![image](https://user-images.githubusercontent.com/8293542/49415219-db049d80-f72a-11e8-90d7-a501e7dc8874.png)
