### ISSUE TITLE
Scope

### ISSUE THREAD

**Issue by Ponchothewise** [dotnet/docs#9164]
The comment about how the isolation level has connection-wide scope doesn't appear to be correct. If set within a called procedure, the isolation level is not set at the new level when returning to the calling procedure. This contradicts 'once set for a connection with the SET TRANSACTION ISOLATION LEVEL statement, it remains in effect until the connection is closed or another isolation level is set'

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d70415dc-0749-6104-11eb-0e9efc7b0f59
* Version Independent ID: 3b8b7bd5-49f3-6307-e2c6-8f16e8752f3a
* Content: [Snapshot Isolation in SQL Server](https://docs.microsoft.com/en-gb/dotnet/framework/data/adonet/sql/snapshot-isolation-in-sql-server)
* Content Source: [docs/framework/data/adonet/sql/snapshot-isolation-in-sql-server.md](https://github.com/dotnet/docs/blob/master/docs/framework/data/adonet/sql/snapshot-isolation-in-sql-server.md)
* Product: **dotnet-framework**
* GitHub Login: @douglaslMS
* Microsoft Alias: **douglasl**

**Comment by tdykstra** [comment]
@cheenamalhotra @karinazhou Who would know if the documentation is incorrect?

**Comment by cheenamalhotra** [comment]
@Ponchothewise 

The statement is correct:

> _Isolation levels_ or lock hints **set in stored procedures or functions do not change the isolation level of the connection that calls them** and are in effect only for the duration of the stored procedure or function call.

This means when a transaction isolation is set from inside a function/stored procedure does not change ISOLATION LEVEL of active connection which is out of procedure scope, e.g. if you set Isolation Level within a Stored procedure as under:

```sql
CREATE PROCEDURE <MyProcedure>
AS  
 -- This Isolation Level is applicable only for queries beyond this point inside procedure
  SET TRANSACTION ISOLATION LEVEL READ COMMITTED
  -- Print to verify Isolation Level is Read Committed (*1)
GO
```
Connection Scope testing:
```sql
-- This is connection level Isolation Level
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
GO
-- Print to verify Isolation Level is READ UNCOMMITTED
EXEC <MyProcedure> -- Prints Isolation Level is Read Committed (*1) from procedure
GO
-- Print to verify Isolation Level is READ UNCOMMITTED
```

This verifies:
> An isolation level has connection-wide scope, and once set for a connection with the SET TRANSACTION ISOLATION LEVEL statement, it remains in effect until the connection is closed or another isolation level is set.

**Comment by tdykstra** [comment]
@cheenamalhotra Thanks for the explanation!

@Ponchothewise Thanks for contacting us. We believe that the question you've raised has been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
