### ISSUE TITLE
Possibly wrong bind definition

### ISSUE THREAD

**Issue by saboco** [dotnet/docs#9165]
It seems to me that delaying Done is not necessary and add extra steps when we want to run the computation.

Defining bind like this:
```fsharp
let rec bind func expr =
        printfn "Bind %A to %A" expr func
        match expr with
        | Done value -> func value
        | NotYetDone work -> NotYetDone (fun () -> bind func (work()))
```

We can run the computation in 4 steps:

```fsharp
// prints "x = 1"
// prints "x = 2"
// returns "Done 7"
comp |> step |> step |> step |> step 
```

Before we needed 8 steps that didn't make sens to me when trying the example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 247c440d-b855-0df1-f2db-076cd3393a0b
* Version Independent ID: 1cbccd4d-1721-e14f-7546-8fa868c965b1
* Content: [Computation Expressions (F#)](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/computation-expressions)
* Content Source: [docs/fsharp/language-reference/computation-expressions.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/language-reference/computation-expressions.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by cartermp** [comment]
Thanks @saboco, your suggestion totally makes sense.
