### ISSUE TITLE
KB link wrong

### ISSUE THREAD

**Issue by euclideansphere** [dotnet/docs#9167]
"see Knowledge Base article Q248802." this does not link to anything relevant. What does this script actually do?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91bc630b-9e6d-3015-a110-f15311e6924f
* Version Independent ID: 658594e6-77cb-e41c-3307-bb0a4e6224e1
* Content: [How to: Set Environment Variables for the Visual Studio Command Line](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/how-to-set-environment-variables-for-the-visual-studio-command-line)
* Content Source: [docs/csharp/language-reference/compiler-options/how-to-set-environment-variables-for-the-visual-studio-command-line.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/how-to-set-environment-variables-for-the-visual-studio-command-line.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
ping @mairaw 

The KB link in the first paragraph of this article goes to an unrelated article. Any idea where to look for the correct article?

**Comment by mairaw** [comment]
Nope @BillWagner. Might be better to just remove that sentence? And perhaps add later on the topic about running it with -help to see the options?

**Comment by BillWagner** [comment]
I like your idea @mairaw 

Adding this to the backlog, and adding the up-for-grabs label

**Comment by RoyiAvital** [comment]
The page doesn't specify how to initialize `x64` environment from `VsDevCmd.BAT`.

How could one do that?
