### ISSUE TITLE
Explain that thumbprint is not part of x 509 spec

### ISSUE THREAD

**Issue by jimweiler** [dotnet/docs#9169]
It would be useful to mention that the thunbprint is calculated by the Windows tools and is not part of the certificate specification and you will not see a thumbprint  field in a cert when you view it with other tools like OpenSSL.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba798f60-80a8-5d2c-555c-dd62917111ec
* Version Independent ID: b3e6d006-b2e4-3959-46f6-e5a6284ee3d4
* Content: [How to: Retrieve the Thumbprint of a Certificate](https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/how-to-retrieve-the-thumbprint-of-a-certificate)
* Content Source: [docs/framework/wcf/feature-details/how-to-retrieve-the-thumbprint-of-a-certificate.md](https://github.com/dotnet/docs/blob/master/docs/framework/wcf/feature-details/how-to-retrieve-the-thumbprint-of-a-certificate.md)
* Product: **dotnet-framework**
* GitHub Login: @Lxiamail
* Microsoft Alias: **wcfsrvt**

**Comment by mlibner** [comment]
The statement about removing the spaces in between the hex numbers was very valuable info. Thank you!

**Comment by SrinikhilReddy** [comment]
Is there a way I can access the thumbprint from powershell/cmdline?
