### ISSUE TITLE
Downloaded PDF bookmarks links are wrong

### ISSUE THREAD

**Issue by MarcinSommer** [dotnet/docs#9173]
When I click Download PDF, the generated file has a list of bookmarks, which point to inadequate places in document.
Contents table has no links at all.
Problem exists in .NET guides and ASP.NET Core

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d49bc05d-7c8e-5f89-aac5-d133225da4d5
* Version Independent ID: 2f831fc9-dfe6-15db-4ec6-00f59c2dacc2
* Content: [.NET Core Guide](https://docs.microsoft.com/en-us/dotnet/core/)
* Content Source: [docs/core/index.md](https://github.com/dotnet/docs/blob/master/docs/core/index.md)
* Product: **dotnet-core**
* GitHub Login: @richlander
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Is this still happening @MarcinSommer? I can't repro. Please give more details on which links are not working.

**Comment by fldef** [comment]
I'm able to reproduce the problem with namespaces in [the .NET API Browser](https://docs.microsoft.com/en-us/dotnet/api/?view=netframework-4.7.2).

Two arbitrary examples:

**System.Drawing**
1. Visit https://docs.microsoft.com/en-us/dotnet/api/system.drawing?view=netframework-4.7.2
2. Click "Download PDF"
3. The links are broken. E.g. "Bitmap" refers to file:///T:/dk50/api/System.Drawing.Bitmap.html
---

**Microsoft.VisualBasic**
1. Visit https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualbasic?view=netframework-4.7.2
2. Click "Download PDF"
3. The links are broken. E.g. "Collection" refers to file:///T:/dk50/api/Microsoft.VisualBasic.Collection.html

---

The links are pointing outside the PDF.

**Comment by mairaw** [comment]
Thanks for that information @fldef. I can repro your issue but I don't understand what the original issue was referring to, so I'll be closing this one.

For your issue @fldef, would you mind opening an issue for our engineering team at https://github.com/microsoftdocs/feedback/issues? Thanks!
