### ISSUE TITLE
Why make getting basic information so convoluted?

### ISSUE THREAD

**Issue by sime3000** [dotnet/docs#9174]
Hello Microsoft.  I don't suspect that you know or care how much time people waste collectively following these instructions just to get a simple answer about a commonly installed component do you? (rhetorical question). Does the .NET team really hate users that much that they cant be bothered to provide a simple command line utility, or a single PowerShell command, or some reference in Programs and Features or something that doesn't require the arcane procedures in articles such as this. The year is almost 2019, not 1999 - why continue to waste everyone's time like this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2115da38-e95e-46fc-1e2d-da88ef92c6cf
* Version Independent ID: a3790e8a-0654-851b-c991-ab7382025406
* Content: [How to: Determine which .NET Framework versions are installed](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed)
* Content Source: [docs/framework/migration-guide/how-to-determine-which-versions-are-installed.md](https://github.com/dotnet/docs/blob/master/docs/framework/migration-guide/how-to-determine-which-versions-are-installed.md)
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by sime3000** [comment]
@Thraka A single command that a normal administrator can run to clearly list all of the decimal versions of .NET that are installed on the system without the convoluted approach of searching for a registry entry then matching it to a table to get a human-readable version number.  Perhaps something like the Windows ver and winver commands to get either a command line or GUI output.  Or a simple get-dotnetversion PowerShell command without all of the syntax and tables you require in your example.  .NET is an important component in any system and this information should be available as well in Computer Management on a workstation and the server properties screen of Server Manager on a server.   If you wanted to do everyone including yourselves a favor there should be some sort of integrity check for installed versions of .NET along with built-in caveats warning administrators about things such as "version X.X.X on .NET does not support the installed version of Microsoft Exchange", etc.

**Comment by EliteLoser** [comment]
I know this isn't what you want, but at least I handle the "convoluted logic" in this function: https://github.com/EliteLoser/DotNetVersionLister -- For Microsoft: Maybe a "registry folder" with version numbers mapped to .NET framework names in a human-readable format, and the greatest number is the latest version.. something like that - give it some thought. :)
