### ISSUE TITLE
Never use mutable structs as in in argument

### ISSUE THREAD

**Issue by qbit86** [dotnet/docs#9180]
Could you please clarify: is passing mutable struct with `in` is less performant than passing the same mutable struct by value with no modifiers at all? As far as I understand if `in` is specified then there is only one defensive copy before actual call, and reference to this copy is passed to function. Why should other copies (six ones in example) be created inside called function on access to (potentially mutating) properties and methods? Are they created if we'd pass mutable struct by value with no `in` modifier?

Another question regards generics. Is it recommended or discouraged to specify `in` in generic methods — comparing to not specifying modifiers at all? For example:
```
public interface IGetTargetPolicy<TGraph, TVertex, in TEdge>
{
    bool TryGetTarget(/* in? */ TGraph graph, TEdge edge, out TVertex target);
}
```
Should `graph` be passed here as `in`? I see three scenarios:
1. `TGraph` is `class` — passing reference by reference, not that bad.
2. `TGraph` is `readonly struct` — perfectly ok if `TGraph` is large; worse but still good enough if `TGraph` is small.
3. `TGraph` is mutable `struct` — ? Is there only the cost of one copy (like in case if no modifiers specified at all), or there can be more significant implications for performance?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac8804c7-6acd-ab2a-4e14-0b99265969a5
* Version Independent ID: 183efcbd-a781-d303-f9cd-1c22da1676de
* Content: [Write safe and efficient C# code](https://docs.microsoft.com/en-us/dotnet/csharp/write-safe-efficient-code)
* Content Source: [docs/csharp/write-safe-efficient-code.md](https://github.com/dotnet/docs/blob/master/docs/csharp/write-safe-efficient-code.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by qbit86** [comment]
> If I get something by ref I want to get all changes done by related members to it or don’t I? If I do why the copy exists?

This particular thing is not about all those new `ref`s. For example take a look at old post by @jskeet [The surprising inefficiency of readonly fields](https://codeblog.jonskeet.uk/2014/07/16/micro-optimization-the-surprising-inefficiency-of-readonly-fields/).

**Comment by Uzivatel919** [comment]
Part “It can't directly assign to any field of an in parameter when that value is a struct type. In addition, you can't pass an in parameter to any method using the ref or out modifier. These rules apply to any field of an in parameter, provided the field is a struct type and the parameter is also a struct type. In fact, these rules apply for multiple layers of member access provided the types at all levels of member access are structs. The compiler enforces that struct types passed as in arguments and their struct members are read-only variables when used as arguments to other methods.” is bad.

I tested this behavior I found:
1) Readonly applies also to props not only fields.
2) Rules are enforced also members of reference types.

**Comment by qbit86** [comment]
If struct is `readonly` then its immutability (by own members) is already checked at the time of compilation of this struct and no defensive copies needed when passed by reference via `in`.

If struct isn't `readonly` then it is potentially mutable even via property getters. Compiler cannot check that getters do not modify struct. At least because at the time of call compilation there can be no sources of this struct (if it's some third party type already compiled). So to enforce that original instance of struct is not modified by call to it's potentially mutating members compiler has to make defensive copy.

**Comment by qbit86** [comment]
@Uzivatel919 

> I don’t understand part, “To ensure that the object isn't modified, the compiler creates a copy and calls member references using that copy. Any modifications are to that defensive copy.”

In the following example compiler emits a defensive copy of mutable struct to prevent `TestIn()` method to modify passed struct with mutating getter:

```csharp
using System;

struct MutableStruct
{
    private int _counter;
    public int Counter => _counter;
    public int PlusPlusCounter => ++_counter;
}

internal static class Program
{
    private static void Main()
    {
        {
            var s = new MutableStruct();
            Console.WriteLine($"Main => Counter: {s.Counter}"); // Main => Counter: 0
            TestRef(ref s);                                     // TestRef => PlusPlusCounter: 1
            Console.WriteLine($"Main => Counter: {s.Counter}"); // Main => Counter: 1
        }
        {
            var s = new MutableStruct();
            Console.WriteLine($"Main => Counter: {s.Counter}"); // Main => Counter: 0
            TestIn(s);                                          // TestIn => PlusPlusCounter: 1
            Console.WriteLine($"Main => Counter: {s.Counter}"); // Main => Counter: 0
        }
    }

    private static void TestRef(ref MutableStruct s)
    {
        Console.WriteLine($"TestRef => PlusPlusCounter: {s.PlusPlusCounter}");
    }

    private static void TestIn(in MutableStruct s)
    {
        Console.WriteLine($"TestIn => PlusPlusCounter: {s.PlusPlusCounter}");
    }
}
```

**Comment by Uzivatel919** [comment]
I am sorry for spamming you thread. I did not reliaze I am commenting instead of creating but thanks for link to article with info about ensuring readonlyness of readonly struct field. That article is not longer true nevertheless the copy of field is still present as you noted.

I gonna deleted all off-topic comments. You can follow with your answers to keep readness.

**Comment by BillWagner** [comment]
@qbit86 

> is passing mutable struct with in is less performant than passing the same mutable struct by value with no modifiers at all? 

The only way to be sure is to measure performance both ways. There are other conditions that affect performance in this scenario: The size of the struct, how many times the method accesses members of the struct. In the general case, it's likely to be slower to pass by readonly ref.

> As far as I understand if in is specified then there is only one defensive copy before actual call, and reference to this copy is passed to function. 

That could be where the confusion arises: declaring the parameter as `in` means it is passed by reference. Inside that method, any number of defensive copies are needed.

> Another question regards generics. Is it recommended or discouraged to specify in in generic methods — comparing to not specifying modifiers at all? 

I don't know that there is any specific guidance here. It would really depend on how the parameter is used in the method. This could be a case where you provide both overloads, and let the caller pick which overload based on knowledge of the particular struct type.

I don't think there's a change needed to the doc, so I'm closing this. If you have further questions, add them, or open a new issue.

**Comment by BillWagner** [comment]
Parts of the conversation have been moved to #9229
