### ISSUE TITLE
Exception, not a -1 return

### ISSUE THREAD

**Issue by HenrikRClausen** [dotnet/docs#9181]
This comment seems to be in error:
// This method finds the day or returns -1

The code reads differently: If no day is found, an Exception is thrown. This should be noted in the comment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5323b38b-8dc5-8f50-f5e7-b58ca0e88ad7
* Version Independent ID: 3d9a83cd-98e3-fc6e-727b-32c8e9228c69
* Content: [Using Indexers (C# Programming Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/indexers/using-indexers)
* Content Source: [docs/csharp/programming-guide/indexers/using-indexers.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/indexers/using-indexers.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for pointing this out @HenrikRClausen 

I've added this to our backlog, and added the up-for-grabs label for community contribution.
