### ISSUE TITLE
One more reason for indexers

### ISSUE THREAD

**Issue by HenrikRClausen** [dotnet/docs#9183]
I believe that it also deserves mention that indexers hide the implementation details of the objects in question. That contributes to robustness, not least if the implementation was to change one day.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5323b38b-8dc5-8f50-f5e7-b58ca0e88ad7
* Version Independent ID: 3d9a83cd-98e3-fc6e-727b-32c8e9228c69
* Content: [Using Indexers (C# Programming Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/indexers/using-indexers)
* Content Source: [docs/csharp/programming-guide/indexers/using-indexers.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/indexers/using-indexers.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
That's a good point @HenrikRClausen It should be added.

Do you want to submit a PR with a suggested fix. Otherwise, we'll address this when we next update this article.
