### ISSUE TITLE
No documentation about what the data types represent

### ISSUE THREAD

**Issue by Nepomuceno** [dotnet/docs#9184]
How can I choose the data type with no information about what each one of those represent? What is UG what is R4?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbe7af6f-d0db-6da8-5e2c-301750a3695d
* Version Independent ID: b67dfcf5-5d21-d81f-37d1-76d8d7111111
* Content: [DataKind Enum (Microsoft.ML.Runtime.Data)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.runtime.data.datakind?view=ml-dotnet)
* Content Source: [dotnet/xml/Microsoft.ML.Runtime.Data/DataKind.xml](https://github.com/dotnet/ml-api-docs/blob/live/dotnet/xml/Microsoft.ML.Runtime.Data/DataKind.xml)
* Product: **dotnet-ml-api**
* GitHub Login: @sfilipi
* Microsoft Alias: **johalex**

**Comment by Mcgrady2009** [comment]
[https://github.com/dotnet/docs/issues/9278](url)
you can see this url

**Comment by mairaw** [comment]
Thanks for your feedback @Nepomuceno.  
@sfilipi @JRAlexander the duplicate item of this issue had quite a few thumbs-up. Is that something you can add /// comments for?

**Comment by cihanyakar** [comment]
A small info:
U means unsigned => in c# U1:byte, U2:ushort, U4:uint, U8:ulong UG or U16:Microsoft.ML.Data.RowId
I means signed Integer => in c# I1:sbyte, I2:short, I4:int, I8: long
R means real numbers => in c# R4 or Num:float, R8:double
TX, TXT, Text => in c# string or ReadOnlyMemory<char>
BL,Bool => in c# bool
TS,TimeSpan => in c# TimeSpan
DT => in c# DateTime
DZ => in c# DateTimeOffset

**Comment by mairaw** [comment]
Closing this one since issue opened by @sfilipi also got closed.

API docs is now at https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.data.datakind?view=ml-dotnet.
