### ISSUE TITLE
Comparison with .NET Framework

### ISSUE THREAD

**Issue by kennethjohnsen** [dotnet/docs#9185]
"App-models ..... it doesn't support ASP.NET Web Forms and MVC ....."
Is this correct? MVC is supported by ASP.NET Core, right?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 581f6cbb-c666-87ee-ab0c-f131baca403c
* Version Independent ID: 9205f603-e1d4-e0eb-1273-f176fcbf520f
* Content: [About .NET Core](https://docs.microsoft.com/en-us/dotnet/core/about#feedback)
* Content Source: [docs/core/about.md](https://github.com/dotnet/docs/blob/master/docs/core/about.md)
* Product: **dotnet-core**
* GitHub Login: @richlander
* Microsoft Alias: **mairaw**

**Comment by JosephRufft** [comment]
.Net Core needs Web Forms!

**Comment by AlexanderDerck** [comment]
To my understanding there is ASP.NET MVC (built on top of the .NET Framework) and ASP.NET Core MVC (built on top of .NET Framework **and** .NET Core) which are 2 different frameworks so I guess it's not an error.
