### ISSUE TITLE
Compile error in "Creating the data set (Method syntax )"

### ISSUE THREAD

**Issue by KeyvanKashani** [dotnet/docs#9188]
Hello , 
Thanks for this helpful documentation .
I think the following code has an error .
Suits().SelectMany(suit =&gt; Ranks(rank =&gt; new { Suit = suit, Rank = rank }));
"No overload for method 'Ranks' takes 1 arguments [linq]"
To produce the same result as query syntax, suggested code would be 
Suits().SelectMany(suit =&gt; Ranks().Select(rank =&gt; new {Suits=suit ,Rank=rank }));

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a2b7453-076c-a18e-f999-cbd57ab13e60
* Version Independent ID: b687ed5b-5013-cceb-01e5-77f9cc7bb534
* Content: [Working with LINQ](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/working-with-linq#creating-the-data-set)
* Content Source: [docs/csharp/tutorials/working-with-linq.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/working-with-linq.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mikkelbu** [comment]
Hi @KeyvanKashani 
You are right. I've prepared a PR with your suggestion.

**Comment by KeyvanKashani** [comment]
Thank you @mikkelbu .
