### ISSUE TITLE
Can't get sample code to work

### ISSUE THREAD

**Issue by maryob77062** [dotnet/docs#9193]
In the section under Making Thread-Safe Calls to Windows Forms Controls there are 3 sections of VB code. First demoThread is not declared. I hate it when I get red squiggles in sample code. I am trying to step through the code and I can't get .InvokeRequired to return True.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be7944fe-6db1-0fe4-7a89-29f5594b2674
* Version Independent ID: 152ac482-0811-0869-addd-258b689fbe3f
* Content: [How to: Make Thread-Safe Calls to Windows Forms Controls](https://docs.microsoft.com/en-us/dotnet/framework/winforms/controls/how-to-make-thread-safe-calls-to-windows-forms-controls)
* Content Source: [docs/framework/winforms/controls/how-to-make-thread-safe-calls-to-windows-forms-controls.md](https://github.com/dotnet/docs/blob/master/docs/framework/winforms/controls/how-to-make-thread-safe-calls-to-windows-forms-controls.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks for your feedback @maryob77062. This article has been update in PR #10761 so this section no longer exists. If you continue to have issues with this article, please open a new issue for us to investigate.
