### ISSUE TITLE
Update Visual Studio versions in the table.

### ISSUE THREAD

**Issue by TobiasKnauss** [dotnet/docs#9196]
Please add Visual Studio 2017 and the latest update version of Visual Studio 2015 (has Update 3, which seems to include .net 4.6.1) and older in the table.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81fe5242-e3b2-6cfe-5308-63fc96272657
* Version Independent ID: 1abaaeb7-d7ed-5522-c16f-409f22a074cc
* Content: [.NET Framework Versions and Dependencies](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/versions-and-dependencies)
* Content Source: [docs/framework/migration-guide/versions-and-dependencies.md](https://github.com/dotnet/docs/blob/master/docs/framework/migration-guide/versions-and-dependencies.md)
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by sitefinitySDK** [comment]
Same feedback as what TobiasKnauss said. The table does not list VS versions after 2015 in the Included in Visual Studio version column.

**Comment by mairaw** [comment]
Thanks for the feedback @TobiasKnauss and @sitefinitySDK. From what I can see, VS 2017 comes with 4.6.1 by default if you install the workload, so it doesn't come completely by default anymore.
So we should note that as well.
