### ISSUE TITLE
Use of `dotnet run` instead of `dotnet path/file.dll`

### ISSUE THREAD

**Issue by Mizux** [dotnet/docs#9198]
In https://docs.microsoft.com/en-us/dotnet/core/tools/index?tabs=netcore2x#command-structure
Why don't using (and advertise) `dotnet run` instead of calling the dll directly ?
i.e. I would rework the example like this
```shell
dotnet new console
dotnet build
dotnet run
```
Also depending on platform (OS), rid, Target Framework Moniker, build Type (Debug default) the .dll can be anywhere and you don't explain where to find it ;)
e.g. on my debian it will be `dotnet bin/Debug/netcoreapp2.1/plop.dll `

```shell
find . -type f -name "*.dll"
./bin/Debug/netcoreapp2.1/plop.dll
./obj/Debug/netcoreapp2.1/plop.dll
```
or in obj ?

Bonus point: dotnet run **cannot** be use if you change the default output directory since there is no option `--output` for `dotnet run` ontrary to `dotnet build` ....

related to #4243 ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7e47565-cc59-b1a6-24be-0143c550c0b2
* Version Independent ID: c6859ca6-e2b1-3645-872c-60390ffd429a
* Content: [.NET Core Command-Line Interface (CLI) Tools](https://docs.microsoft.com/en-us/dotnet/core/tools/index?tabs=netcore2x#command-structure)
* Content Source: [docs/core/tools/index.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/index.md)
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by tdykstra** [comment]
> Why don't using (and advertise) `dotnet run` instead of calling the dll directly ?

The reason is that this section's purpose is only to illustrate the use of options and arguments.  It could do dotnet new and dotnet run but that wouldn't use options and arguments.
