### ISSUE TITLE
Ordinal String Operations vs Current Culture

### ISSUE THREAD

**Issue by mikernet** [dotnet/docs#9201]
The section titled "Default ordinal comparisons" makes no sense - it states:

> The most common operations, String.CompareTo and String.Equals or String.Equality use an ordinal comparison, a case-sensitive comparison, and use the current culture. 

If it is using an ordinal comparison then by definition it can't be using the current culture. Ordinal comparisons are binary sort order comparisons that do not factor in culture, so which is it? The section continues on to state:

> The most important point about these default comparison methods is that because they use the current culture, the results depend on the locale and language settings of the machine where they run. These comparisons are unsuitable for comparisons where order should be consistent across machines or locations.

...which would need to be fixed as well.

---
#### Document Details

<span class="emoji-outer emoji-sizer"><span class="emoji-inner" style="background: url(chrome-extension://immhpnclomdloikkpcefncmfgjbkojmh/emoji-data/sheet_apple_32.png);background-position:95.94594594594594% 75.96944770857814%;background-size:5418.75% 5418.75%" data-codepoints="26a0-fe0f"></span></span> *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11ecfc18-477b-f792-4136-2feb46bbc5d3
* Version Independent ID: 82f53ae8-a9d4-dea9-5acd-6d9202a40882
* Content: [How to: Compare strings - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/how-to/compare-strings)
* Content Source: [docs/csharp/how-to/compare-strings.md](https://github.com/dotnet/docs/blob/master/docs/csharp/how-to/compare-strings.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by rpetrusha** [comment]
Sorry, Bill. I just got to this after being out yesterday.

I think that what the article is trying to say is that there’s inconsistency between the methods; CompareTo performs a culture-sensitive, case-sensitive comparison, while the equality methods are ordinal.

I’ll assign the issue to myself and address it this sprint (hopefully), since this is confusing and seems like an important issue to address. This is a high page-view topic.

--Ron

**Comment by rpetrusha** [comment]
Thanks for noticing this inconsistency, @mikernet. I think that what the text intended to say was that the default behaviors are inconsistent: CompareTo is case- and culture-sensitive; Equals and the Equality operator are ordinal. We'll modify the topic during this sprint to address this confusion.
