### ISSUE TITLE
Versioning recommendation for AssemblyVersion is not compatible with Windows Installer (MSI)

### ISSUE THREAD

**Issue by MarketKernel** [dotnet/docs#9202]
This recommendation:

✔️ CONSIDER only including a major version in the AssemblyVersion.

Is not compatible with Windows Installer (MSI). When reinstalling the program, MSI leaves the old libraries if AssemblyVersion has not been changed (AssemblyFileVersion is ignored by MSI).

Is there any solution of this problem?
https://guides.github.com/features/mastering-markdown/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffa1275e-9f51-c83e-7cbd-9dfc8abb6dea
* Version Independent ID: 899c196e-4aad-515f-2d04-525719244c69
* Content: [Versioning and .NET libraries](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/versioning)
* Content Source: [docs/standard/library-guidance/versioning.md](https://github.com/dotnet/docs/blob/master/docs/standard/library-guidance/versioning.md)
* Product: **dotnet**
* GitHub Login: @JamesNK
* Microsoft Alias: **mairaw**

**Comment by shueybubbles** [comment]
There's still a general problem with de-centralized assembly loaders like Powershell. If cmdlet  A relies on functionality from version 1.1.3 of some assembly, but cmdlet B runs first and loads version 1.1.0 the assembly, then cmdlet A may fail to run.  For a traditional EXE a binding redirect would work, but one can't edit powershell's config like that.

**Comment by jzabroski** [comment]
@MarketKernel I would suggest moving awai from MSI and towards Squirrel.Windows instead.  I believe this is what Microsoft Teams uses, based on observing the file layout of Teams.  Let me know if this solves your problem.  There are so many issues with MSIs, that I do not think MSIs should dictate best practices.

**Comment by jzabroski** [comment]
@shueybubbles It's not clear to me if you meant to reply to @MarketKernel, but there is general discussion in the PowerShell reposistory about fixing the psd1 module manifest format, among other issues.  With PowerShell Core, the transitive failure is somewhat fixable through AssemblyLoadContext.  The downside is that until .NET Core 3 arrives, you cannot unload those context assemblies.
