### ISSUE TITLE
Microsoft WCF Web Service Reference Provider Tool

### ISSUE THREAD

**Issue by nissimlevy** [dotnet/docs#9207]
So what are the next steps? Don't just leave me hanging like that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e89651a-5ad9-c3f9-146f-8d87b87d9e11
* Version Independent ID: 85c0e55f-abc0-3b2d-409a-06042b1f3ebb
* Content: [Microsoft WCF Web Service Reference Provider Tool](https://docs.microsoft.com/en-us/dotnet/core/additional-tools/wcf-web-service-reference-guide)
* Content Source: [docs/core/additional-tools/wcf-web-service-reference-guide.md](https://github.com/dotnet/docs/blob/master/docs/core/additional-tools/wcf-web-service-reference-guide.md)
* Product: **dotnet-core**
* GitHub Login: @mlacouture
* Microsoft Alias: **johalex**

**Comment by steepho** [comment]
Hi I have an example (the next steps) for everyone if they need to consume an ASMX Web Service using connect services.

First step.  Make sure your return types match what your ASMX is actually returning (for some reason using the Connected Services "Wizard" would create a partial class for DataTable return types for example. Go into the WebService1SoapClient class and make sure your return types are all correct. (I found types List<string> was wrong and types DataTable so far..)

So ..
`[System.ServiceModel.OperationContractAttribute(Action="http://services.fake.com/MethodThatReturnsListofString", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task**<List<string>>** MethodThatReturnsListofString();`

Make sure those are all correct for all methods.

Also when you change that intellisense will get mad at you and you must change the corresponding Task under the same class, ConfigureEndpoint method

`public System.Threading.Tasks.Task**<List<string>>** MethodThatReturnsListofString()
        {
            return base.Channel.MethodThatReturnsListofString();
        }` 

Now in your main class your are doing all your work, make an Async Task for each method you want to use from your WebService.

`        public async Task<List<string>> MethodThatReturnsListofStringAsync()
        {
            BasicHttpBinding binding = new BasicHttpBinding();
            binding.MaxReceivedMessageSize = 1000000; //change this to the max file size allowed to be transferred. I have it set to a meg.
            EndpointAddress address = new EndpointAddress("http://services.fake.com/WebService1.asmx");
            AIWebService.AIServiceSoapClient _client = new AIServiceSoapClient(binding, address);
            string _errors = await _client.MethodThatReturnsListofString();
            return _errors;
        }`

When you want to actually get that List of Strings in a method somewhere call these two lines, then use as you normally would.

`            Task<List<string>> _tempTask = MethodThatReturnsListofStringAsync();
            <List<string>> MyListOfStrings = _tempTask.Result;`

Voila! 

> Turn Coffee into Code!
