### ISSUE TITLE
Clarify semantics of null-conditional operator in contexts expecting a boolean value.

### ISSUE THREAD

**Issue by ericmutta** [dotnet/docs#9208]
For example, suppose you have an object `foo` with a boolean field called `IsBlah`. The following code in VB compiles...

```vb
If foo?.IsBlah Then DoSomething()
```

...but what exactly does it mean? I guess it is equivalent to this:

```vb
If foo IsNot Nothing AndAlso foo.IsBlah Then DoSomething()
```

...however none of this is spelled out in the documentation so it's not clear how this works. Is it like the code above or is the null-conditional operator returning a `Nullable(Of Boolean)` which is then handled in a special way by the `If` statement?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7427bc30-4d66-b234-4537-200d4419cc24
* Version Independent ID: 786cb51a-cd8d-95a7-a11c-c39245a01e9d
* Content: [Null-conditional Operators (Visual Basic)](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/operators/null-conditional-operators)
* Content Source: [docs/visual-basic/language-reference/operators/null-conditional-operators.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/language-reference/operators/null-conditional-operators.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by KathleenDollard** [comment]
I want to be careful that with how much information we put in topics other than the core where they primarily appear. 

This topic clarifies that `?.` returns a nullable (in your case a nullable of boolean). The If topic is clear on what happens when a nullable boolean is encountered (it is treated as False). 

The result you describe occurs, it is not in exactly that manner (particularly in IL). 

I'm not seeing a constructive change here, which I think you are. Could you hit the Edit button in the upper right  and offer the text that you think belongs here? You'll have to click through a couple of things, and make sure you get all the way to "PR" so it makes it back into the repo for us to see.

**Comment by ericmutta** [comment]
Hi @KathleenDollard  thanks for following up!

> The If topic is clear on what happens when a nullable boolean is encountered (it is treated as False).

I believe this is what I was getting at...because most people are highly unlikely to look up the documentation of the `if` statement (being such a basic construct) it is very easy to miss that "nullable boolean = false when Nothing" behaviour. For example I only discovered this behaviour when you mentioned it here!

> I'm not seeing a constructive change here, which I think you are. 

Since the second paragraph in those docs says **These operators help you write less code to handle null checks...** I think adding one more example of "writing less code to handle null checks" would be useful in helping users maximize the value of the null conditional operator. I would essentially say something to the tune of:

> The null-conditional operator can also be used to check the value of a boolean member on objects that are commonly null.

...then I would give an example like:

```vb
  Dim TargetCustomer = FindCustomerByID(123)

  If TargetCustomer IsNot Nothing AndAlso TargetCustomer.IsTaxExempt Then
   ApplyTaxExemption(TargetCustomer.Orders)
  End If
```

...and say it can be simplified to this:

```vb
  Dim TargetCustomer = FindCustomerByID(123)

  If TargetCustomer?.IsTaxExempt Then
   ApplyTaxExemption(TargetCustomer.Orders)
  End If
```

If you reckon the above is worth adding to the docs, let me know so I can attempt the Edit process you mentioned, otherwise it is OK to close this issue (it's no big deal, since as you point out someone can figure out the above by reading both the null-conditional operator docs and the `if` statement docs).

**Comment by BillWagner** [comment]
ping @KathleenDollard 

Do you want @ericmutta to make the changes suggested above?

**Comment by mairaw** [comment]
@KathleenDollard can you comment on this?

**Comment by KathleenDollard** [comment]
Yes. I am so sorry this dropped on my end. 

Yes, I think this is a good change @ericmutta are you able to add the example you suggest to the docs?

**Comment by ericmutta** [comment]
> @KathleenDollard Yes, I think this is a good change @ericmutta are you able to add the example you suggest to the docs?

Yes I can and will try sometime this week if not next week :+1:

**Comment by ericmutta** [comment]
I have created a PR here: https://github.com/dotnet/docs/pull/12077
