### ISSUE TITLE
Thank you very much from bottom of heart thank you very much

### ISSUE THREAD

**Issue by dipakvaghela99** [dotnet/docs#9209]
I have tried so many times and you give a very easy and convenient way for successful installation of Microsoft Indic tool for local Indian languages. (which are not supported after updating of windows 7 or 8 to Windows 10)

I think you understand the problem properly and give the best resolution.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea654e23-2ec5-637e-99c3-8870b895030c
* Version Independent ID: 9c054590-c5e3-199c-b852-e1a856b4aae7
* Content: [Install the .NET Framework 3.5 on Windows 10, Windows 8.1, and Windows 8](https://docs.microsoft.com/en-us/dotnet/framework/install/dotnet-35-windows-10)
* Content Source: [docs/framework/install/dotnet-35-windows-10.md](https://github.com/dotnet/docs/blob/master/docs/framework/install/dotnet-35-windows-10.md)
* Product: **dotnet-framework**
* GitHub Login: @rlander
* Microsoft Alias: **mairaw**

**Comment by Grand-Poobah** [comment]
microsoft employee?

**Comment by gewarren** [comment]
@dipakvaghela99 Thanks for the positive feedback, glad it helped you!
