### ISSUE TITLE
Property "Targetframwork" not defined

### ISSUE THREAD

**Issue by danielwertheim** [dotnet/docs#9210]
Following the recommendation above using `<TargetFrameworks>` to target multiple frameworks and then defining specific references for different frameworks, e.g.

```xml
<ItemGroup Condition=" '$(TargetFramework)' == 'net45' ">
    <Reference Include="System.Net.Http" />
    <Reference Include="System.Threading.Tasks" />
</ItemGroup>
```
gives an warning that "Property "Targetframwork" not defined". At least in VS2017 15.9.2

It works but gives warning which is annoying. So either document a solution that doesn't provide warnings or fix tooling so that it doesn't provide a warning.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49205137-dcec-a120-e5e7-1b9c79cdafbb
* Version Independent ID: 4352856b-5ccf-8e62-48b4-3151340cac56
* Content: [Target frameworks](https://docs.microsoft.com/en-us/dotnet/standard/frameworks)
* Content Source: [docs/standard/frameworks.md](https://github.com/dotnet/docs/blob/master/docs/standard/frameworks.md)
* Product: **dotnet**
* GitHub Login: @richlander
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Are you using SDK-style projects @danielwertheim or traditional .NET Framework projects?

**Comment by mairaw** [comment]
Closing due to the lack of response.

**Comment by Leon99** [comment]
@mairaw I'm observing this issue with SDK-style csproj in VS 16.4.

**Comment by mairaw** [comment]
Can one of you paste your csproj contents so I can try to more easily reproduce and follow up with the engineering team?

**Comment by Leon99** [comment]
@mairaw easy, here you go:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netcoreapp2.2;netcoreapp3.0</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'netcoreapp2.2' ">
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="2.2" />
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'netcoreapp3.0' ">
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="3.0.0" />
  </ItemGroup>
</Project>
```
