### ISSUE TITLE
can not download entire pdf of particualr document 

### ISSUE THREAD

**Issue by jaymin93** [dotnet/docs#9211]
for eg I  om on this link https://docs.microsoft.com/en-us/dotnet/csharp/deconstruct expecting download pdf to generate pdf for Deconstructing tuples and other types this topic , or with all higher level hierarchy c# concept's pdf but it gives me pdf of 2048 page  here is link by clicking on download pdf for this page https://opdhsblobprod02.blob.core.windows.net/contents/c6aea4f5457448ee818b7292ba695982/c2d7ce02056f95c379ef72c31bf1e7de?sv=2015-04-05&sr=b&sig=O26fGOUMcQD4ibli7zpg96ouoCEOjFTf2ffBEoaMin8%3D&st=2018-11-24T12%3A09%3A57Z&se=2018-11-25T12%3A19%3A57Z&sp=r

but I don't want this I want pdf of this page or parent topic pdf for few pages it woks like what I need but for many it does not so please fix the issue (if it is) or suggest way to do so in correct manner.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec91dfa8-265f-a220-fe14-14047375ee93
* Version Independent ID: b2afe72f-5b30-8938-7b64-9f45056df36a
* Content: [Deconstructing tuples and other types](https://docs.microsoft.com/en-us/dotnet/csharp/deconstruct)
* Content Source: [docs/csharp/deconstruct.md](https://github.com/dotnet/docs/blob/master/docs/csharp/deconstruct.md)
* Product: **dotnet-csharp**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by BillWagner** [comment]
Transferring to MicrosoftDocs/Feedback.

Closing as transferred to MicrosoftDocs/Feedback#1046
