### ISSUE TITLE
Does this paragraph need reviewing?

### ISSUE THREAD

**Issue by RaulBastian** [dotnet/docs#9212]
Does this paragraph need reviewing?

An encoding defines a set of rules about how to present messages on the wire. An encoder implements such an encoding and is responsible, on the sender side, for turning **a Message in-memory message** into a byte stream or byte buffer that can be sent across the network. On the receiver side, the encoder turns a sequence of bytes into an in-memory message.

Maybe:

An encoding defines a set of rules about how to present messages on the wire. An encoder implements such an encoding and is responsible, on the sender side, for turning **an in-memory Message** into a byte stream or byte buffer that can be sent across the network. On the receiver side, the encoder turns a sequence of bytes into an in-memory message.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 153e045b-c112-2680-df56-70270afbf1a9
* Version Independent ID: 4dc73bd5-260a-c40d-d972-b8ee23f6ec05
* Content: [Large Data and Streaming](https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/large-data-and-streaming)
* Content Source: [docs/framework/wcf/feature-details/large-data-and-streaming.md](https://github.com/dotnet/docs/blob/master/docs/framework/wcf/feature-details/large-data-and-streaming.md)
* Product: **dotnet-framework**
* GitHub Login: @Lxiamail
* Microsoft Alias: **wcfsrvt**

**Comment by Lxiamail** [comment]
@RaulBastian Your correction looks right, please submit an PR if you like to contribute.
