### ISSUE TITLE
What is the package manager for macOS

### ISSUE THREAD

**Issue by sadedil** [dotnet/docs#9218]
Hi,

The document says

> Starting with .NET Core 2.1, there is no need to uninstall the .NET Core SDK when upgrading it using a package manager. The package manager update or refresh commands will automatically remove the older version upon the successful installation of a newer version.

I'm not sure what the package manager is for macOS. I've downloaded .NET Core Sdk from https://www.microsoft.com/net/download and installed via double click the pkg file (for example `dotnet-sdk-{x}.{x}.{xxxx}-osx-gs-x64.pkg`). Should i install with Homebrew or something like this instead of downloading pkg?

**My question is:**
I only want to keep one for each major version. One version for 2.1 and one version for 2.2 and so on. How can i uninstall 2.1.105, 2.1.300, 2.1.301, 2.1.302?

**My current installations:**
```
dotnet --list-sdks
2.1.105 [/usr/local/share/dotnet/sdk]
2.1.300 [/usr/local/share/dotnet/sdk]
2.1.301 [/usr/local/share/dotnet/sdk]
2.1.302 [/usr/local/share/dotnet/sdk]
2.1.403 [/usr/local/share/dotnet/sdk]
2.2.100-preview3-009430 [/usr/local/share/dotnet/sdk]
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4ca18b0-5533-f5b9-2eb4-9853a4fa61ed
* Version Independent ID: a12b8b5c-a3af-d1c5-a27c-39e9d390dff2
* Content: [How to remove .NET runtime and SDK](https://docs.microsoft.com/en-us/dotnet/core/versions/remove-runtime-sdk-versions?tabs=macOS)
* Content Source: [docs/core/versions/remove-runtime-sdk-versions.md](https://github.com/dotnet/docs/blob/master/docs/core/versions/remove-runtime-sdk-versions.md)
* Product: **dotnet-core**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
I think the best answer for now is to use the `sudo rm -rf` command listed in the next table.  

@leecow would have more details on this.

**Comment by leecow** [comment]
Bill's suggestion is correct, the unwanted SDK directories need to be manually removed.

**Comment by mrward** [comment]
There is also this uninstall script which can be used to remove the .NET Core SDK on the Mac - https://github.com/dotnet/cli/blob/master/scripts/obtain/uninstall/dotnet-uninstall-pkgs.sh - which also removes the packages registered, among other things.

**Comment by sadedil** [comment]
Thanks for the comments. As my understanding i need to remove manually or with shell script (semi-manual).

What about the this part:
> Starting with .NET Core 2.1, there is no need to uninstall the .NET Core SDK when upgrading it using a package manager. The package manager update or refresh commands will automatically remove the older version upon the successful installation of a newer version.

Isn't this statement valid for Mac? Why i still have the old sdk versions?

**Comment by sadedil** [comment]
@BillWagner, thanks for the explanation.

**Comment by BillWagner** [comment]
re-opening so the message stays visible until PR #9418 is merged.
