### ISSUE TITLE
Sample split between several boxes

### ISSUE THREAD

**Issue by martingbrown** [dotnet/docs#9219]
When I view this page in Edge the two samples are presented in multiple boxes. Where as I think there should only be two boxes one for the XAML code and one for the C# code.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44be0b84-a485-c39c-dfe2-5b5ed901709f
* Version Independent ID: 8ff09ce0-5749-972b-9ef1-b4a85d64890a
* Content: [How to: Persist and Restore Application-Scope Properties Across Application Sessions](https://docs.microsoft.com/en-gb/dotnet/framework/wpf/app-development/persist-and-restore-application-scope-properties)
* Content Source: [docs/framework/wpf/app-development/persist-and-restore-application-scope-properties.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/app-development/persist-and-restore-application-scope-properties.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
Related to #2994
