### ISSUE TITLE
.NET Tutorial on https://dot.net/ has unnecessary threshold

### ISSUE THREAD

**Issue by KexyBiscuit** [dotnet/docs#9220]
`Keep learning` section in [.NET Tutorial](https://www.microsoft.com/net/learn/dotnet/hello-world-tutorial) leads the user to [List collections](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/intro-to-csharp/arrays-and-collections), which [requires the user to finish the previous lessons](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/intro-to-csharp/#list-collection).

**Comment by KexyBiscuit** [comment]
Any update on this?

**Comment by mairaw** [comment]
Thanks for your feedback @KexyBiscuit and I'm sorry we haven't triaged this earlier.

@BillWagner @rowanmiller can you comment on this? Not sure whether we'd want to update the marketing site, docs or both.

**Comment by imba-tjd** [comment]
Perhaps replace the link in <https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/next> with <https://docs.microsoft.com/dotnet/csharp/tutorials/intro-to-csharp/>

**Comment by BillWagner** [comment]
@KexyBiscuit @rowanmiller I think that link should point to the [numbers](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/intro-to-csharp/numbers-in-csharp-local) tutorial that runs locally. Visitors should have downloaded the SDK, so are ready to work locally. This is the first introductory lesson that has local instructions.

**Comment by rowanmiller** [comment]
I agree, and we already have some instructions at the start of the numbers page to point folks to the dot.net tutorial if they haven't already setup their environment. 

I will update the link on the dot.net side. 

@BillWagner I think we should also remove this note from the `Work with collections` step
![image](https://user-images.githubusercontent.com/4741851/52734048-14eaef00-2f79-11e9-89d2-6547ecfbfc07.png)

**Comment by BillWagner** [comment]
Good point @rowanmiller PR coming...

**Comment by rowanmiller** [comment]
Change is live on the dot.net side - https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/next

**Comment by BillWagner** [comment]
PR ready for the docs side: #10455

**Comment by BillWagner** [comment]
PRs merged, so closing this.
