### ISSUE TITLE
Ref returns for container types

### ISSUE THREAD

**Issue by samir105** [dotnet/docs#9225]
Is it possible to make index operator of generic container types like list to return ref (So we could write listOfStruct[i].field=value)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6968c8f-19ab-f79f-021a-265108870371
* Version Independent ID: 6b4f1fec-b9d1-f501-1fcf-2c6f15209a29
* Content: [Ref return values and ref locals (C# Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/ref-returns)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/ref-returns.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/ref-returns.md)
* Product: **dotnet-csharp**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by BillWagner** [comment]
@samir105 Thanks for taking the time to suggest this. If it's added, we'll update the documentation.

As a product suggestion, it would belong in the [dotnet/corefx](https://github.com/dotnet/corefx) repository. 

I'll close this, but consider opening an issue in the product repository.
