### ISSUE TITLE
Reading ETW events

### ISSUE THREAD

**Issue by mehmetilker** [dotnet/docs#9236]
I cannot find any information about TraceEventSession and ETWTraceEventSource classes on docs.microsoft.com.
Does it mean there is no official MS support to read ETW events?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f631676-9b12-c857-6f83-105cf07d5de8
* Version Independent ID: a1a4d50f-cc93-804f-561d-36af60d1cfe7
* Content: [ETW Events in the .NET Framework](https://docs.microsoft.com/en-us/dotnet/framework/performance/etw-events)
* Content Source: [docs/framework/performance/etw-events.md](https://github.com/dotnet/docs/blob/master/docs/framework/performance/etw-events.md)
* Product: **dotnet-framework**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by MagicAndre1981** [comment]
The documentation can be found here:

https://github.com/Microsoft/perfview/blob/master/documentation/TraceEvent/TraceEventProgrammersGuide.md

**Comment by mehmetilker** [comment]
@MagicAndre1981 Thanks for the link.
I am aware of perfview but same problem there. It is not officially supported.
logman and ETWTraceEventSource do not produce same result and I am looking for more detail info about them. And report the problem if it is related to https://www.nuget.org/packages/Microsoft.Diagnostics.Tracing.TraceEvent/
issue: https://github.com/Microsoft/perfview/issues/782
