### ISSUE TITLE
Document behaviour of 'unspecified' options in <proxy> Element

### ISSUE THREAD

**Issue by ChrisMaddock** [dotnet/docs#9238]
Most values here are stated as defaulting to 'unspecified' - however there is no information on the behaviour when using the default. (When the defaults are either true or false, it's easier to guess!)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09aeb831-81e3-0216-4ef7-b4cb40105290
* Version Independent ID: 32c08202-f73f-5bff-9e68-451349f9eb74
* Content: [&lt;proxy&gt; Element (Network Settings)](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/network/proxy-element-network-settings)
* Content Source: [docs/framework/configure-apps/file-schema/network/proxy-element-network-settings.md](https://github.com/dotnet/docs/blob/master/docs/framework/configure-apps/file-schema/network/proxy-element-network-settings.md)
* Product: **dotnet-framework**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

**Comment by kenlyon** [comment]
Agreed! Some of them are easier to test than others. I think `bypassonlocal` is true by default.

Also, it's odd to see `unspecified` as one of the options in the syntax. Wouldn't you just omit the property if you do not want to specify a value?

**Comment by kenlyon** [comment]
I was wrong. I found that if I omit `bypassonlocal`, the default behaviour is `false`.

**Comment by graphik55** [comment]
Maybe as a notice:

It looks like that "autoDetect" is "true" by default.
I think this should be changed to "false" to prevent WPAD attacks. 

I had the situation that a program used my WPAD without any proxy settings.
