### ISSUE TITLE
E una cosa pericolosa che si avvi e a che cosa serve?

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#9243]
@MarcoTeck commented on [Sat Nov 24 2018](https://github.com/dotnet/docs.it-it/issues/54)

Io non ho capito se è pericoloso il fatto che si avvi e a che cosa serve?

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: 64b60fe3-9661-0a43-d4bd-eedd9d4b82d1
* Version Independent ID: 35804ba6-f52d-104d-5b9f-5b11b5cbfdf6
* Content: [Uso di Strumentazione gestione Windows (WMI) per la diagnostica](https://docs.microsoft.com/it-it/dotnet/framework/wcf/diagnostics/wmi/#security)
* Content Source: [docs/framework/wcf/diagnostics/wmi/index.md](https://github.com/dotnet/docs.it-it/blob/live/docs/framework/wcf/diagnostics/wmi/index.md)
* Product: **dotnet-framework**
* GitHub Login: @Lxiamail
* Microsoft Alias: **wcfsrvt**

**Comment by CeciAc** [comment]
Hi team, 
I'm moving this here since the article may need some clarification:
Rough translation:

> Io non ho capito se è pericoloso il fatto che si avvi e a che cosa serve?

**Comment by rpetrusha** [comment]
Rough translation: "I did not understand if it's dangerous that it starts and what's the use?"

The Security section of the article discusses security considerations. Use cases are discussed in the parent article, [Administration and Diagnostics](https://docs.microsoft.com/dotnet/framework/wcf/diagnostics/index). I'll close this issue as Not Repro.
