### ISSUE TITLE
This articles does not follow the guide line described in Unit Test Best practices

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#9244]
@joonhwan commented on [Sun Nov 25 2018](https://github.com/dotnet/docs.ko-kr/issues/84)

Prefer helper methods to setup and teardown : see (https://docs.microsoft.com/ko-kr/dotnet/core/testing/unit-testing-best-practices#prefer-helper-methods-to-setup-and-teardown)

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: e39c2f1b-f41a-bdf9-2646-09379941453d
* Version Independent ID: 422811cb-6287-03af-ba8d-1daebee9744d
* Content: [dotnet test 및 xUnit을 사용하여 .NET Core에서 C# 코드 유닛 테스트](https://docs.microsoft.com/ko-kr/dotnet/core/testing/unit-testing-with-dotnet-test)
* Content Source: [docs/core/testing/unit-testing-with-dotnet-test.md](https://github.com/dotnet/docs.ko-kr/blob/live/docs/core/testing/unit-testing-with-dotnet-test.md)
* Product: **dotnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **wiwagn**

**Comment by jonaramos** [comment]
This is an example of the PrimeService following the "Unit Test Best practices" @joonhwan pointed out.

`using Xunit;
using Prime.Services;

namespace Prime.UnitTests.Services
{
    public class PrimeService_IsPrimeShould
    {
        [Fact]
        public void ReturnFalseGivenValueOf1()
        {
            // Arrange
            var primeService = CreateDefaultPrimeService();
            // Act
            var result = primeService.IsPrime(1);
            // Assert
            Assert.False(result, "1 should not be prime");
        }

        [Theory]
        [InlineData(-1)]
        [InlineData(0)]
        [InlineData(1)]
        public void ReturnFalseGivenValuesLessThan2(int value)
        {
            // Arrange
            var primeService = CreateDefaultPrimeService();
            // Act
            var result = primeService.IsPrime(value);
            // Assert
            Assert.False(result, $"{value} should not be prime");
        }

        [Theory]
        [InlineData(2)]
        [InlineData(3)]
        [InlineData(5)]
        [InlineData(7)]
        public void ReturnTrueGivenPrimesLessThan10(int value)
        {
            // Arrange
            var primeService = CreateDefaultPrimeService();
            // Act
            var result = primeService.IsPrime(value);
            // Assert
            Assert.True(result, $"{value} should be prime");
        }

        [Theory] 
        [InlineData(4)] 
        [InlineData(6)] 
        [InlineData(8)] 
        [InlineData(9)] 
        public void ReturnFalseGivenNonPrimesLessThan10(int value) 
        { 
            // Arrange
            var primeService = CreateDefaultPrimeService();
            // Act
            var result = primeService.IsPrime(value); 
            // Assert
            Assert.False(result, $"{value} should not be prime"); 
        } 

        private PrimeService CreateDefaultPrimeService()
        {
            return new PrimeService();
        }
    }
}
`

**Comment by Rick-Anderson** [comment]
@Thraka  recommend closing. This sample doesn't use `setup and teardown` methods.
