### ISSUE TITLE
Update Prerequisites topics for .NET Core 2.2

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#9257]
- [ ] Windows: https://docs.microsoft.com/en-us/dotnet/core/windows-prerequisites
- [x] macOS: https://docs.microsoft.com/en-us/dotnet/core/macos-prerequisites
- [x] Linux: https://docs.microsoft.com/en-us/dotnet/core/linux-prerequisites

**Comment by Thraka** [comment]
Following up with author of https://github.com/dotnet/core/blob/master/release-notes/2.2/2.2-supported-os.md to confirm there are no changes to prereqs for 2.2

**Comment by mairaw** [comment]
I just checked the Windows version and is not fully up-to-date. I'll create a PR shortly with some more changes to address this. I'll check the others later.

**Comment by mairaw** [comment]
@Andrew-MSFT @KathleenDollard @richlander I don't seem to be able to select the Target Framework version from the Build menu on VS 15.9.3 anymore. By design?

![image](https://user-images.githubusercontent.com/12971179/49482645-db616f00-f7e4-11e8-80c1-ddfadc749858.png)

I'm updating the screenshots we have at https://docs.microsoft.com/en-us/dotnet/core/windows-prerequisites#prerequisites-with-visual-studio-2017.

**Comment by Andrew-MSFT** [comment]
@davkean and @cartermp.  Not by design, mine looks like that but if I click the dropdown I can see the frameworks.  Is yours clickable?

**Comment by cartermp** [comment]
Mine doesn't look like that with File | New Project. Is this for an existing project?

**Comment by Andrew-MSFT** [comment]
In my case, yes it was an existing project

**Comment by mairaw** [comment]
Yes, existing project for me as well, but not clickable in my case.

**Comment by mairaw** [comment]
A new project works fine 😕 
![image](https://user-images.githubusercontent.com/12971179/49486826-cee51280-f7f4-11e8-865b-0f8c0887bb68.png)

And 15.9 comes with 2.1 SDK by defaut, correct?

**Comment by mairaw** [comment]
Never mind. It seems there was something funky going on with my machine and that particular project. The drop-down now shows fine for that one as well. 

So if I can just get confirmation that 2.1 SDK comes with the 15.9, I'll finish the updates I'm working on.

Thanks!

**Comment by cartermp** [comment]
The 2.1 SDK does come with 15.9, yes.

**Comment by mairaw** [comment]
Thanks @cartermp.
