### ISSUE TITLE
Add migration doc from .NET Core 2.1 to 2.2

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#9259]
Need to define whether this is needed.

This is what we had for 2.1: https://docs.microsoft.com/en-us/dotnet/core/migration/20-21

@KathleenDollard @Andrew-MSFT @richlander can you comment on this one?

**Comment by Andrew-MSFT** [comment]
@glennc @danroth27 what do you guys thing?  Are there enough changes between 2.1/2.2 we should have a doc?

**Comment by danroth27** [comment]
I think we should always have a doc for how to move from one version to the next. Even if the migration is simple, that just means the doc should be easy to write 😃 .

**Comment by mairaw** [comment]
Fair enough. 😄 

Other than the obvious TargetFramework(s) change, what else do we need to account for with this release?
