### ISSUE TITLE
Alternative security measures?

### ISSUE THREAD

**Issue by oddbear** [dotnet/docs#9263]
Is it possible to elaborate more on what 'without putting alternative security measures in place' means, or link to some other documentation for this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0505d926-b70e-94df-d4ef-1d70737d0353
* Version Independent ID: 1bf0791b-8627-9113-a0b3-e52987bd4d59
* Content: [How to: Run Partially Trusted Code in a Sandbox](https://docs.microsoft.com/en-us/dotnet/framework/misc/how-to-run-partially-trusted-code-in-a-sandbox)
* Content Source: [docs/framework/misc/how-to-run-partially-trusted-code-in-a-sandbox.md](https://github.com/dotnet/docs/blob/master/docs/framework/misc/how-to-run-partially-trusted-code-in-a-sandbox.md)
* Product: **dotnet-framework**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
The following topic that is linked from the see also section covers the security measures:
https://docs.microsoft.com/en-us/dotnet/standard/security/secure-coding-guidelines#securing-resource-access
