### ISSUE TITLE
An ASP.NET Web API service tutorial with ML.NET

### ISSUE THREAD

**Issue by tauheedul** [dotnet/docs#9264]
Please add an ML.NET Tutorial where the ML.NET logic is behind an ASP.NET Web API service so it can be utilised by any Web-enabled application over http.

The example can include a client application (desktop or web) triggering a web api service and returning a result to the client.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e855e630-1a30-d138-4ac6-bfeefebf9aae
* Version Independent ID: afc0a7d1-d3c2-acf2-d4ea-d2565e22b237
* Content: [ML.NET tutorials](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/index?view=azuremgmtredis-4.3.0-preview)
* Content Source: [docs/machine-learning/tutorials/index.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/index.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by JRAlexander** [comment]
Thanks, @tauheedul! This has been added to the backlog.

**Comment by tauheedul** [comment]
Thank you @JRAlexander

**Comment by susilj** [comment]
https://github.com/susilj/SentimentAnalysis

**Comment by junwin** [comment]
https://github.com/junwin/MLNetRegression

**Comment by tauheedul** [comment]
Thank you @junwin @susilj
