### ISSUE TITLE
Complexity and Confusion 

### ISSUE THREAD

**Issue by TroyTurley** [dotnet/docs#9267]
I agree with those who complain about the unnecessary complexity. The Help-&gt;About in Visual Studio 2017 tells me I have version 4.7.02556 but the Powershell method tells me 4.7.1 and clrver tells me 4.0.30319, but I think there's a difference between the framework and the runtime... correct? Is there an article that describes this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2115da38-e95e-46fc-1e2d-da88ef92c6cf
* Version Independent ID: a3790e8a-0654-851b-c991-ab7382025406
* Content: [How to: Determine which .NET Framework versions are installed](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed#ps_a)
* Content Source: [docs/framework/migration-guide/how-to-determine-which-versions-are-installed.md](https://github.com/dotnet/docs/blob/master/docs/framework/migration-guide/how-to-determine-which-versions-are-installed.md)
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by yeg-am-astronomer** [comment]
Couldn't agree more it's almost as if we've regressed to the horrors of dll hell and bsod!! Where's Bill Gates getting the blue screen of the death in front of millions live?  That inspired a hell of a lot of tidying up!!
