### ISSUE TITLE
Link to "Roadmap for the .NET Framework" doesn't work

### ISSUE THREAD

**Issue by bychkov** [dotnet/docs#9268]
Link to "Roadmap for the .NET Framework" doesn't work

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6372c771-955d-d043-7774-fcd7ff20b05c
* Version Independent ID: 15347b19-b2bf-640b-9d3f-982b970f9936
* Content: [Framework Design Guidelines](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/)
* Content Source: [docs/standard/design-guidelines/index.md](https://github.com/dotnet/docs/blob/master/docs/standard/design-guidelines/index.md)
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by Thraka** [comment]
@bychkov Thank you for reporting this. I noticed a PR is open that will remove this link. Thanks.
