### ISSUE TITLE
Add a overview page for .Net Core diagnostics

### ISSUE THREAD

**Issue by noahfalk** [dotnet/docs#9276]
I'm not actually the customer asking for this, but I'll attempt to paraphrase what I have heard as best I can

**Help us make content visible**

- Tell us what search terms you used and how you searched docs.
Customer searches on bing/google for terms such as: 
One of: ".Net Core", "C#", "asp.net core" +
One of: "diagnostics", "debugging", "logging", "profiling", "tracing", "crash", "dump", "monitor", "fix", "exception", "stack trace"

- Tell us what docs you found that didn't address your concern.
Searching under many of these terms will produce docs that are overly niche or outdated or only relevant to full framework rather than broad summary information that is useful to someone just getting started. For example a search for ".net core diagnostics" on google returns:
Logging using DiagnosticSource in ASP.NET Core  [niche]
GitHub - aspnet/Diagnostics: Diagnostics middleware for …   [niche]
.NET Framework Compatibility Diagnostics | .NET Blog [full framework]
Diagnostics in ASP.NET MVC 6 (ASP.NET Core 1.0) [outdated and niche]

**Describe the new topic**

- Explain why this topic is needed.

Customers are telling us they don't know what diagnostic tools .Net Core makes available to them. This is either because the they are new to .Net and we've never done a great job at this, or they are used to .Net but .Net Core and/or Linux means that their old tooling knowledge may no longer apply

- Suggest a location in the Table of Contents.

I'd suggest putting it under Docs/.NET/.NET Core Guide/Diagnostics

- Write an abstract. In one **short** paragraph, describe what this topic will cover.

This page will describe the tools and APIs that are available to a .Net Core developer to help them to diagnose and fix issues with their applications. 

- Create an outline for the new topic. We'll help review the outline and approve it before anyone writes a topic.

Intro
- Logging
- Debugging
- Profiling
- Tracing, Metrics, and Monitors
- Dump Debugging
- APIs for creating custom tools

For a little more detail I started sketching out what this could look like here - its very rough right now: https://github.com/noahfalk/docs/commit/89713d16b3ddf216f615fb860fc71ceb4979350a

**Comment by noahfalk** [comment]
cc @vancem @dotnet/dotnet-diag

**Comment by vancem** [comment]
Adding some specific sub items if you do these items check the box but also put in the URL to the 
Adding some specific items that we come across so we can check them off.  When they are checked off we should edit this items to put the URL of the new docs here.   

 - [ ] ACTION (Steve): "How to debug async" guidance.  We need official documentation about how to go about diagnosing various issues today with the tools available today.  

-  [ ] ACTION (Steve): "How to go async" guidance.  When customers come with a highly synchronous codebase and need CSS engineers to help them through the conversion process, they need information.  Where to start, what kind of work needs to be done, what are best practices, etc.  This kind of information exists, but spread out (e.g. the pfxteam blog, external blogs, etc.), and not in an official docs form. There's value in creating something official, even if it's pulling existing material from msdn blogs.

@stephentoub

**Comment by mairaw** [comment]
@noahfalk @vancem is this something you or your team could come up with a draft and we would help polish it?

**Comment by vancem** [comment]
Yes, that is the plan.

**Comment by mairaw** [comment]
Also, for the second bullet about how to go async, @BillWagner is driving a whole project about async best practices, etc. that you can see here:
https://github.com/dotnet/docs/projects/42
