### ISSUE TITLE
What are advantages of this approach over ‎Azure Logic App?

### ISSUE THREAD

**Issue by neil-rubens** [dotnet/docs#9287]
What are advantages of this approach over ‎Azure Logic App?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96ac9a09-0689-b95c-66d8-4b709cd3feaa
* Version Independent ID: 68a934b9-2ffd-c78d-eeb1-a1c11f8d71f6
* Content: [Orchestration patterns - Serverless apps](https://docs.microsoft.com/en-us/dotnet/standard/serverless-architecture/orchestration-patterns)
* Content Source: [docs/standard/serverless-architecture/orchestration-patterns.md](https://github.com/dotnet/docs/blob/master/docs/standard/serverless-architecture/orchestration-patterns.md)
* Product: **dotnet**
* GitHub Login: @cecilphillip
* Microsoft Alias: **cephilli**

**Comment by hugobarona** [comment]
@neil-rubens, i would say the advantage is the fact that you have more control over the workflows that you implement. So, in a scenario you want basic workflows, and if Azure Logic App provides you the requires features to implement, i would say go with Logic App. If you need something more custom, and also have more control over the way the steps are performs, logging, monitoring, etc., then go with Durable Functions.
