### ISSUE TITLE
Missing class definition

### ISSUE THREAD

**Issue by johnechiappetta** [dotnet/docs#9291]
The sample code under "Auto-property initializers" seems to be missing the declaration of class Student.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36fef60d-04e9-dc86-2e3f-134c10ea37bb
* Version Independent ID: 09b5aa7a-1b43-8bf9-9786-f10f457488dd
* Content: [What's New in C# 6 - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-6#auto-property-initializers)
* Content Source: [docs/csharp/whats-new/csharp-6.md](https://github.com/dotnet/docs/blob/master/docs/csharp/whats-new/csharp-6.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by CalvinAllen** [comment]
@BillWagner I would like to resolve this issue, but what should these examples look like?  

I.e., should the very first code example be a complete class file with all properties defined and set via constructor parameters?  The other two examples, Grades and YearInSchool, making modifications to the original class, and then having the fully modified class available at the end as the "new way"?

**Comment by BillWagner** [comment]
Thanks for asking @CalvinAllen 

Fixing this will take 2 PRs: Our samples are in the [dotnet/samples](https://github.com/dotnet/samples) repository. 

There is working sample code for the "What's new in C# 6" article in this folder: https://github.com/dotnet/samples/tree/master/snippets/csharp/new-in-6  The new or updated samples should be part of that project.

Instructions on including samples are in our [Contributor Guide - Code section](https://docs.microsoft.com/en-us/contribute/dotnet-style-guide#code). Let me know if you have any questions.

**Comment by CalvinAllen** [comment]
Thanks, Bill, Ill take a look and get started on shortly.

**Comment by CalvinAllen** [comment]
@BillWagner Is it possible to have nested tags?  In the old code, I want to flag the entire class for inclusion, but there are already tags defined within it for the properties and constructor - or, should I create a new class (in the same file, same properties/etc) but without the extra tags?

**Comment by BillWagner** [comment]
@CalvinAllen Yes, nested tags are supported.  That is the preferred way to accomplish what you want.

**Comment by CalvinAllen** [comment]
@BillWagner Great, thanks!
