### ISSUE TITLE
Field description is not clear

### ISSUE THREAD

**Issue by wschin** [dotnet/docs#9293]
I don't think after reading through this page, user will be able to adjust those parameters for their application. To actually playing with those parameters, users need to first find a suitable data set and figure out how to create a pipeline with the correct trainer. Maybe add some examples like scikit-learn (they basically have at least one runnable example for each component exposed to users) could help?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa672bcd-5d84-52b5-bd24-b35e9db51355
* Version Independent ID: 5df92e70-d059-03dd-b024-138f0a35e367
* Content: [AveragedLinearArguments Class (Microsoft.ML.Trainers.Online)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.trainers.online.averagedlineararguments?view=ml-dotnet)
* Content Source: [dotnet/xml/Microsoft.ML.Trainers.Online/AveragedLinearArguments.xml](https://github.com/dotnet/ml-api-docs/blob/live/dotnet/xml/Microsoft.ML.Trainers.Online/AveragedLinearArguments.xml)
* Product: **dotnet-ml-api**
* GitHub Login: @sfilipi
* Microsoft Alias: **johalex**

**Comment by JRAlexander** [comment]
Hi @wschin, great feedback! I will pass to the product team, as these pages are generated from the code comments. Have you seen the [tutorials](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/) in the ML.NET Guide?

**Comment by mairaw** [comment]
It seems this API no longer exists. Closing. FYI @natke
