### ISSUE TITLE
.NET microservices - Architecture e-book, MOBI-version

### ISSUE THREAD

**Issue by kjartanm** [dotnet/docs#9302]
Font color is set to dark gray (or transparency?), probably to soften the black-on-white impression. But unfortunately that means it can't be read with dark mode setting on Kindle, since the font setting is not overridden and you get dark gray on black -- which is unreadable, of course.

Best Regards
Kjartan Rekdal Müller

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2913c197-6b53-a39d-8de7-c9fc7d3de767
* Version Independent ID: ff8fd370-f807-f4d7-262d-ac5788d1bedd
* Content: [Designing a microservice domain model](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/microservice-domain-model#feedback)
* Content Source: [docs/architecture/microservices/microservice-ddd-cqrs-patterns/microservice-domain-model.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/microservice-ddd-cqrs-patterns/microservice-domain-model.md)
* Product: **dotnet**
* Technology: **dotnet-ebooks**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by mairaw** [comment]
Thanks for your feedback @kjartanm. Since this comment is regarding the site experience and not the content itself, I've moved it to https://github.com/MicrosoftDocs/feedback/issues/911.

**Comment by CESARDELATORRE** [comment]
Since it is related to the .MOBI version of the ebook for Kindle, I'm tracking that down. We'll review the images with a dark theme and fix that for the next release of the .MOBI file.
Thanks! 👍

**Comment by mairaw** [comment]
Gotcha @CESARDELATORRE!

**Comment by mairaw** [comment]
Any updates here @CESARDELATORRE @nishanil?

**Comment by mvelosop** [comment]
Closing this issue as all images have now been changed to actual white background.
