### ISSUE TITLE
add "dotnet project" command

### ISSUE THREAD

**Issue by samdevx1029** [dotnet/docs#9304]
Similar to "dotnet sln" where projects can be added or removed, how about being able to add/remove files (especially the class files) to a specific project?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 910cd365-d63a-00dc-417c-db017f83bf6f
* Version Independent ID: 5e495ddd-140e-de5c-a793-d4a9f88be51e
* Content: [dotnet build command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-build?tabs=netcore2x)
* Content Source: [docs/core/tools/dotnet-build.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-build.md)
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Thanks for your feedback @samdevx1029. @KathleenDollard @livarcocc can you comment on this product request? Should this be moved to dotnet/cli repo?

**Comment by livarcocc** [comment]
With SDK style projects, you don't need to specify the files explicitly on your project. We have globing enabled for that. So, I don't see this being something we will focus on.

**Comment by mairaw** [comment]
That's what I thought. So I'll close this. Thanks @livarcocc for your input.
