### ISSUE TITLE
Examples per task

### ISSUE THREAD

**Issue by wschin** [dotnet/docs#9308]
After reading this page, a user probably feels very exciting about what ML.NET can do. Can we have some links to some examples to help the user starting immediately? The current organization is good as a top-down doc but I'd like to have more connections between "down" sides to reduce to gap of using ML.NET.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd15175c-5b7d-4310-ecf5-32ffc7bc588b
* Version Independent ID: 38adc676-934e-0ff9-c868-527f075c96df
* Content: [Machine learning tasks](https://docs.microsoft.com/en-us/dotnet/machine-learning/resources/tasks)
* Content Source: [docs/machine-learning/resources/tasks.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/resources/tasks.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by JRAlexander** [comment]
Great idea! I've added it to the backlog and the  [tracking project](https://github.com/dotnet/docs/projects/64). Thanks!

**Comment by JRAlexander** [comment]
Closing as I believe this has been resolved with the current api documentation.
