### ISSUE TITLE
Can win-x64 be used for 64 bit Windows?

### ISSUE THREAD

**Issue by PingPongSet** [dotnet/docs#9312]
Why is win-x64 introduced? Can win-x64 be used for 64 bit Windows?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 009616d0-6c93-a2de-82fe-4f7168817f18
* Version Independent ID: 4c2c5549-0151-516d-91d0-9b017c74e787
* Content: [.NET Core Runtime IDentifier (RID) catalog](https://docs.microsoft.com/en-us/dotnet/core/rid-catalog)
* Content Source: [docs/core/rid-catalog.md](https://github.com/dotnet/docs/blob/master/docs/core/rid-catalog.md)
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment]
@PingPongSet Hi!

Yes. The article explains it this way:

>.NET Core 2.0 SDK introduces the concept of portable RIDs. They are new values added to the RID graph that aren't tied to a specific version or OS distribution. They're particularly useful when dealing with multiple Linux distros.

So `win-x64` would target any of the supported Windows 64-bit OS. Prior to this being introduced, you had to specify if you were targeting windows 7, 8, or 10.

I'm going to close this, thanks!
