### ISSUE TITLE
Folder creation: not clear

### ISSUE THREAD

**Issue by ericjlynch** [dotnet/docs#9314]
"In the terminal, create a golden folder and open the folder." Not helpful. Remember who your audience is: developers who are familiar with .Net on Windows but just getting started on Mac. How do you create a folder from terminal on a Mac? Is it the same as on a Windows box? Mac terminal certainly doesn't look like a Windows command prompt. Please be more detailed than this for those of us who are developing on a Mac for the first time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3343b35c-90c1-2e11-498d-ee1d4eb409f6
* Version Independent ID: f2eda261-d4c3-c90a-1294-dfe11e55c341
* Content: [Getting started with .NET Core on macOS](https://docs.microsoft.com/en-us/dotnet/core/tutorials/using-on-macos)
* Content Source: [docs/core/tutorials/using-on-macos.md](https://github.com/dotnet/docs/blob/master/docs/core/tutorials/using-on-macos.md)
* Product: **dotnet-core**
* GitHub Login: @bleroy
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Thanks for your feedback @ericjlynch. I think the title is a bit misleading in the sense that this is more of a tutorial rather than a Get started topic.
This feedback led to some interesting discussions with my team since we don't typically cover how to create a folder on a specific OS.

We'll see if we can make some quick updates to make those steps easier for someone trying to learn the technology on a Mac.

**Comment by mairaw** [comment]
Moving this to the backlog until I can really work on this one.

**Comment by SurlyMae** [comment]
@mairaw You're right, this one is not really macOS-specific. 
[the Windows/Linux/macOS starter](https://docs.microsoft.com/en-us/dotnet/core/tutorials/using-with-xplat-cli) is more approachable, but still lacks the basic command line instructions that @ericjlynch is looking for. 
If y'all are looking to keep **Getting started with .NET Core on macOS**, renaming it to reflect that it's more of a tutorial makes sense, but I would still change the wording of 'create a golden folder' to 'create a folder named golden.' Seems small, but adds clarification to folks who are new and may think, "Is a golden folder some magical .NET core thing I don't know about yet?"
Then, in **Getting started with...Windows/Linux/macOS**, I'd add some brief command-line snippets to show how to create folders and change directories, and I might even link to those code snippets from the **Getting started with .NET Core on macOS** tutorial in the places where users are being asked to perform similar steps.

**Comment by mairaw** [comment]
I've opened https://github.com/dotnet/docs/pull/14325 to take care of this and no longer need to create the folder ahead of time. Please provide feedback if you'd like.
