### ISSUE TITLE
Suggestion on live code examples

### ISSUE THREAD

**Issue by karenpayneoregon** [dotnet/docs#9316]
This is a suggestion, not an issue.

I frequent the MSDN forums everyday assisting those looking for assistance and noticed that all code examples which permit someone to execute the code from the page are only in C#, none that I saw (and I only hit a handful of pages) for VB.NET. Now a smart VB.NET developer would try an example, figure out if that is what they need and then either convert by sight or use a converter but there are many who refer to themselves as "noobies" what simply get frustrated when they see nothing for VB.NET. I'm sure there are more pressing issues for the document team (and you guys are doing a great job) then having both C# and VB.NET but thought it prudent to make that suggestion just the same as I'm sure there are a percentage of VB.NET developers who will someday (not yet) move to C# yet that does no good to them right now when they are focused on doing their daily programming task. Thanks for listening!!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50b5f5c7-99f8-e112-a3f4-691548e8fc06
* Version Independent ID: e4b0d61c-a09b-3bf0-1696-1d4472272237
* Content: [Composite Formatting](https://docs.microsoft.com/en-us/dotnet/standard/base-types/composite-formatting)
* Content Source: [docs/standard/base-types/composite-formatting.md](https://github.com/dotnet/docs/blob/master/docs/standard/base-types/composite-formatting.md)
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by mairaw** [comment]
Thank you @karenpayneoregon for your feedback. Adding @LadyNaggaga to comment on this request for try.net for VB developers.

**Comment by LadyNaggaga** [comment]
@karenpayneoregon  Thank you for the suggestion. Currently Try .NET only supports C#. However, the goal of Try .NET is to support more languages in the future. As we (Try .NET) begins to accept OSS contribution we might see VB support come through OSS contributions sooner.
