### ISSUE TITLE
Document how to install and use private .NET Core installs

### ISSUE THREAD

**Issue by richlander** [dotnet/docs#9317]
This is the idea you install the product as a zip and then use it. It's "private" in the sense that it is not globally installed.

**Comment by mairaw** [comment]
Who has that information @richlander? For which versions would this apply?

**Comment by Thraka** [comment]
I saw this being done in building the docker container. Let's figure the priority on this scenario. I'll send an email to @richlander to get his eyes on it.

@richlander Do you have any data on how many requests are there for this scenario?

**Comment by richlander** [comment]
This scenario isn't specifically related to Docker containers. For example, [this pattern](https://github.com/dotnet/dotnet-docker/blob/master/3.0/sdk/stretch/amd64/Dockerfile#L22) isn't what I mean.

It is about copying and decompressing a .NET Core .zip/tar.gz to your machine and using it w/the most limited disruption to your machine while still getting a decent dev experience by setting various environment variables.
