### ISSUE TITLE
One more advantage of FDD

### ISSUE THREAD

**Issue by MathiasRonnblom** [dotnet/docs#9322]
I would think that it would be a major advantage of FDD to be able to use "in-place upgrades" on the machine. For example if I target netcoreapp2.1 with FDD, I would get the benefit of bug fixes when future .Net Core Runtimes 2.1.x are installed on the machine.
https://docs.microsoft.com/en-us/dotnet/core/versions/selection#framework-dependent-apps-roll-forward

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06a17d5d-5f6e-d6bc-324b-af411a42ccb8
* Version Independent ID: f58588d7-70f6-aa32-5c6d-ac3e7d72d87c
* Content: [.NET Core Application Deployment](https://docs.microsoft.com/en-us/dotnet/core/deploying/index)
* Content Source: [docs/core/deploying/index.md](https://github.com/dotnet/docs/blob/master/docs/core/deploying/index.md)
* Product: **dotnet-core**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by mairaw** [comment]
Hi @MathiasRonnblom,

We do state the following as an advantage:
Unless overridden, FDDs will use the latest serviced runtime installed on the target system. This allows your application to use the latest patched version of the .NET Core runtime.

So with that, I'll be closing this issue, but please let us know if we missed anything.
