### ISSUE TITLE
Format Errors in Documentation

### ISSUE THREAD

**Issue by Cobi911** [dotnet/docs#9323]
Somethings wrong in the "Specifying Parameter Data Types" section. Please review and update documentation. Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0aa86042-a6a5-cf97-5abf-5f4e9375a240
* Version Independent ID: e7ca3196-3c42-7d72-bc37-9c05e97c9bfa
* Content: [Configuring Parameters and Parameter Data Types](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/configuring-parameters-and-parameter-data-types?view=netframework-4.7.2)
* Content Source: [docs/framework/data/adonet/configuring-parameters-and-parameter-data-types.md](https://github.com/dotnet/docs/blob/master/docs/framework/data/adonet/configuring-parameters-and-parameter-data-types.md)
* Product: **dotnet-framework**
* GitHub Login: @douglaslMS
* Microsoft Alias: **douglasl**

**Comment by mairaw** [comment]
Thanks for letting us know of this issue. We'll try to address it shortly!
