### ISSUE TITLE
The "Try pattern" link is broken

### ISSUE THREAD

**Issue by akeeton** [dotnet/docs#9327]
The "Try pattern" link is https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1021-avoid-out-parameters?view=vs-2017#try-pattern-methods.md when it should be https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1021-avoid-out-parameters?view=vs-2017#try-pattern-methods

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f6c8480-77a7-7505-5224-0efe15b9b755
* Version Independent ID: 993250d1-108c-ab1a-886e-ca1bfa9104c7
* Content: [out parameter modifier (C# Reference)](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/out-parameter-modifier)
* Content Source: [docs/csharp/language-reference/keywords/out-parameter-modifier.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/out-parameter-modifier.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
Thanks @akeeton. Would you like to submit a pull request to fix this?

We explain the process here: https://docs.microsoft.com/en-us/contribute/#quick-edits-to-existing-documents
