### ISSUE TITLE
Comments are not syntax highlighted

### ISSUE THREAD

**Issue by svick** [dotnet/docs#933]
It seems that on docs.ms, comments in code blocks are not syntax highlighted. I noticed this happens for F# on [let Bindings](https://docs.microsoft.com/en-us/dotnet/articles/fsharp/language-reference/functions/let-bindings#syntax), but it happens for C# too (e.g. on [Developing Libraries with Cross Platform Tools](https://docs.microsoft.com/en-us/dotnet/articles/core/tutorials/libraries#how-to-multitarget)).

The issue seems to be with CSS theme, this markdown:

``````
```fsharp
// Binding a value:
let identifier-or-pattern [: type] =expressionbody-expression
// Binding a function value:
let identifier parameter-list [: return-type ] =expressionbody-expression
```
``````

Results in this HTML (after JS):

``` html
<pre><code class="lang-fsharp"><span class="hljs-comment">// Binding a value:</span>
<span class="hljs-keyword">let</span> identifier-<span class="hljs-keyword">or</span>-pattern [: <span class="hljs-class"><span class="hljs-keyword">type</span>] </span>=expressionbody-expression
<span class="hljs-comment">// Binding a function value:</span>
<span class="hljs-keyword">let</span> identifier parameter-list [: <span class="hljs-keyword">return</span>-<span class="hljs-class"><span class="hljs-keyword">type</span> ] </span>=expressionbody-expression
</code></pre>
```

Notice that comments have the `hljs-comment` CSS class.

But shows as:

![](http://imgur.com/ozXOF6w.png)

Notice that comments have indistinct black font color.

**Comment by cartermp** [comment]
We've got a bug for this out already, but this is good info to link to for further examples.  Thanks.

**Comment by BillWagner** [comment]
I'm closing this after checking the links referenced above. Those, and a sampling of others all seem to be fixed at this point.
