### ISSUE TITLE
Difference between SortList and SortedDictionary is not explained

### ISSUE THREAD

**Issue by ptoye** [dotnet/docs#9335]
In this document, there is no difference between SortedList and SortedDictionary. I can only assume that there is some sort of a difference, and would love to know what it is (as question for StackOverflow). As this document is meant to help the user decide what form of list is needed, some guidance would be useful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e84850a4-05a8-5bab-ea8c-80df1ed0133f
* Version Independent ID: da3b31b2-54bf-14c2-56d3-872d4c1c109c
* Content: [Selecting a Collection Class](https://docs.microsoft.com/en-us/dotnet/standard/collections/selecting-a-collection-class)
* Content Source: [docs/standard/collections/selecting-a-collection-class.md](https://github.com/dotnet/docs/blob/master/docs/standard/collections/selecting-a-collection-class.md)
* Product: **dotnet**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Thank you for your feedback @ptoye. We're targeting an update of this topic for a future sprint.

**Comment by rpetrusha** [comment]
To respond to your question, @ptoye, we don't recommend the use of the non-generic [SortedList](https://docs.microsoft.com/dotnet/api/system.collections.sortedlist) class. The difference between the generic SortedList and SortedDictionary classes is discussed in the [SortedList\<TKey,TValue>](https://docs.microsoft.com/dotnet/api/system.collections.generic.sortedlist-2#remarks) documentation.

**Comment by ptoye** [comment]
Thanks @rpetrusha. I assumed that the page in question covered both the generic and the non-generic list types so didn't look further. I use generic classes in my project.

Also thanks @mairaw - maybe a pointer to the document referenced by @rpetrusha would be enough.

**Comment by ptoye** [comment]
Fine, But I was maybe a bit terse in my initial comment. Please replace SortedList and SortedDictionary by SortedList <TKey, TValue> and SortedDictionary <TKey, TValue> and re-open! I'd sort of assumed that you'd understand. Sorry.

**Comment by ptoye** [comment]
Thanks @rpetrusha. No problem.
