### ISSUE TITLE
SqlData

### ISSUE THREAD

**Issue by mikewiegand** [dotnet/docs#9336]
I get System.PlatformNotSupportedException: System.Data.SqlClient is not supported on this platform.\r\n   at System.Data.SqlClient.SqlConnection..ctor(String connectionString)

C# .Net Core Library called by a C# Function. How does one get data out of SQL without EF? What version of SqlClient do I need?????

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b4a4f96-84b9-5b6c-945b-daeab67b1ffa
* Version Independent ID: e256e48e-8b93-8b0b-e6ef-6d567dbd66ba
* Content: [Retrieving Data Using a DataReader](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/retrieving-data-using-a-datareader)
* Content Source: [docs/framework/data/adonet/retrieving-data-using-a-datareader.md](https://github.com/dotnet/docs/blob/master/docs/framework/data/adonet/retrieving-data-using-a-datareader.md)
* Product: **dotnet-framework**
* GitHub Login: @douglaslMS
* Microsoft Alias: **douglasl**

**Comment by mairaw** [comment]
Hi @mikewiegand! Can you give us more information about the project? Which version of .NET Core are you targeting? Are you referencing the System.Data.SqlClient package in your project? Which OS are you targeting?

**Comment by mikewiegand** [comment]
Hi
Pls close I was using the wrong version. A preview version. I reverted to a stable version and all is well. Thank u

**Comment by mairaw** [comment]
Great to hear!
