### ISSUE TITLE
System.Environment.FailFast should be the last resort

### ISSUE THREAD

**Issue by berkarslan-cs** [dotnet/docs#9339]
"CONSIDER terminating the process by calling System.Environment.FailFast (.NET Framework 2.0 feature) instead of throwing an exception if your code encounters a situation where it is unsafe for further execution.". This is too risky because other threads might be in a point that they might not execute their "finally" clauses in try..catch blocks which might cause some inconsistencies when the application gets started later. More graceful shutdown methodologies should be used imo..

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 674c6f94-0ed4-4482-18f1-f389fd4a84e6
* Version Independent ID: 270599c2-e00c-f707-21e6-318b1952496c
* Content: [Exception Throwing](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/exception-throwing)
* Content Source: [docs/standard/design-guidelines/exception-throwing.md](https://github.com/dotnet/docs/blob/master/docs/standard/design-guidelines/exception-throwing.md)
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by mairaw** [comment]
We can't modify that content since it's copyrighted. But adding @KrzysztofCwalina and @terrajobst to comment on the current guidance being used for the .NET team.

**Comment by KrzysztofCwalina** [comment]
Adding @bartonjs 

@berkarslan-cs, do you believe continuing when it's "unsafe" is better than not running finalizers? If yes, why? To me "unsafe" (in this context) means that if the program continues it will corrupt state (at best) or even result in a security issue.

**Comment by berkarslan-cs** [comment]
@KrzysztofCwalina  That sentence (actually the word "unsafe") can be interpreted differently than you just stated (like I did). Maybe the documentation can be edited in a way that the reader gets the idea of your last sentence? I interpreted it like "the application should not continue to run maybe because of a missing configuration or lacking authorization and that's fine but why would I kill it?"

**Comment by KrzysztofCwalina** [comment]
Ah, I see how it could be interpreted as such. We will try to clarify it when we update the guidelines/book.
Thanks for the feedback.
