### ISSUE TITLE
Build system not aware of preprocessor symbols representing the target frameworks

### ISSUE THREAD

**Issue by victor-david** [dotnet/docs#9343]
"The build system is aware of preprocessor symbols representing the target frameworks..."

This doesn't seem to be the case. I created the following  sample console app in Visual Studio 2017 15.9.2 and switched the framework version to everything from 3.5 to 4.61. None of them activated their corresponding conditional block.

    class Program
    {
        static void Main(string[] args)
        {
#if NET35
            bad code
#endif

#if NET40
            bad code
#endif

#if NET45
            bad code
#endif

#if NET451
            bad code
#endif

#if NET452
            bad code
#endif

#if NET46
            bad code
#endif

#if NET461
            bad code
#endif

        }
    }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49205137-dcec-a120-e5e7-1b9c79cdafbb
* Version Independent ID: 4352856b-5ccf-8e62-48b4-3151340cac56
* Content: [Target frameworks](https://docs.microsoft.com/en-us/dotnet/standard/frameworks#supported-target-framework-versions)
* Content Source: [docs/standard/frameworks.md](https://github.com/dotnet/docs/blob/master/docs/standard/frameworks.md)
* Product: **dotnet**
* GitHub Login: @richlander
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Thanks @victor-david for your feedback. I need to add some information to that topic and #if preprocessor directive topics that this behavior only applies to SDK-style projects (.NET Core projects).

**Comment by victor-david** [comment]
I thought that might be the case, but wasn't sure. Thanks for the clarification. @mairaw
