### ISSUE TITLE
"updated example but incorrect description"

### ISSUE THREAD

**Issue by lojk200775** [dotnet/docs#9349]
it is stated in the example section "Because the use of async and await in an application entry point is not supported, we cannot apply the async attribute to the Main method" but the example clearly shows an async task main.

The use of async/await is now supported (in DotNetCore at least) and the example shows a correct usage so this statement should be revised.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61f81774-3755-817c-edb0-8f3b36ddcc92
* Version Independent ID: 8ed3997b-3dd6-fcfd-67ad-6426e2292eb6
* Content: [await (C# Reference)](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/await)
* Content Source: [docs/csharp/language-reference/keywords/await.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/await.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by pkulikov** [comment]
@lojk200775 it's a good catch! Thanks for reporting it.
