### ISSUE TITLE
Operating Instructions Incorrect

### ISSUE THREAD

**Issue by 5U8cVs** [dotnet/docs#9350]
I have Visual Studio installed from MSDN (formerly My Visual Studio).  Instructions on the various (10000s) web pages tell me to type developer command line or dev to find my way to the latest InstallUtil for the utility that installs daemons (formerly Windows NT Services).  I am supposed to type dev in the text box on the Start menu.  But that does not work.  And I still did not find my way to InstallUtil which happens to be in %windir%\Microsoft.NET\Framework\v<something>.  Incorrect operating instructions are worse than the usual no operating instructions at all.  Just "explore" and "discover" and you will survive.  Great philosophy for a trillion dollar USA software corporation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a1428fb-1282-c537-8714-29cf2ccb0446
* Version Independent ID: d329fbf9-0b17-e4e4-733f-9b9c96eb46bd
* Content: [Developer Command Prompt for Visual Studio](https://docs.microsoft.com/en-us/dotnet/framework/tools/developer-command-prompt-for-vs)
* Content Source: [docs/framework/tools/developer-command-prompt-for-vs.md](https://github.com/dotnet/docs/blob/master/docs/framework/tools/developer-command-prompt-for-vs.md)
* Product: **dotnet-framework**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Hi @5U8cVs! We'll need more information from you to try to help you.

That topic covers the instructions for the latest versions of Visual Studio.

Can you let us know which version of Visual Studio you have installed and which version of Windows you're running on?

**Comment by mairaw** [comment]
Closing due to the lack of response.
