### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by DAud-IcI** [dotnet/docs#9351]
The note says "readonly field can be initialized EITHER at the declaration OR in a constructor" (my emphasis). Until now I thought this means you can't do both, but Roslyn keeps insisting that I should make my variables readonly which are only set in the constructor even if they are already initialized in the declaration. The code compiles and I see no issues so technically this is ok, but I wonder if this is by spec of an implementation quirk.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26899b81-d6f9-534a-83ee-283dd8aae545
* Version Independent ID: 3061125d-7de4-97ef-ccb0-ee792d6f2ae1
* Content: [readonly keyword (C# Reference)](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/readonly)
* Content Source: [docs/csharp/language-reference/keywords/readonly.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/readonly.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this up @DAud-IcI 

Can you provide a code sample of for this? I'd like to make sure I fully understand your question.

**Comment by DAud-IcI** [comment]
Hi Bill,

In the below example we have the `_fileName` field which I made readonly because I got "IDE0044 Make field readonly" message from Visual Studio. Both my default assumptions and the note I've mentioned from the Docs page suggests that this should not be valid. (the either-or wording I've quoted above) `_fileName` has already been assigned to during declaration, but I can overwrite it in the constructor still.

```C#
using System;
using System.Linq;

namespace Example
{
    public class Logger
    {
        private readonly string _fileName = "log.txt";

        public void Log(string message)
        {
            Console.WriteLine($"Simulated logging to {_fileName}: {message}");
        }

        public Logger(string FileName = null)
        {
            if (!string.IsNullOrWhiteSpace(FileName))
                _fileName = FileName;
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            var logger = new Logger(args.FirstOrDefault());
            logger.Log("Hello");
        }
    }
}
```

**Comment by BillWagner** [comment]
Thanks for the clarification. That makes sense. I just opened PR #9422 to address this issue.
