### ISSUE TITLE
Downloads blocked within installer

### ISSUE THREAD

**Issue by JacobHelton57** [dotnet/docs#9352]
When I attempt to install this framework, I am receiving an error message that files can't be found. I believe this is due to our web filter blocking the installer's attempts to grab files from the web. Is there anything in specific we should be whitelisting to allow these installations?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea654e23-2ec5-637e-99c3-8870b895030c
* Version Independent ID: 9c054590-c5e3-199c-b852-e1a856b4aae7
* Content: [Install the .NET Framework 3.5 on Windows 10, Windows 8.1, and Windows 8](https://docs.microsoft.com/en-us/dotnet/framework/install/dotnet-35-windows-10)
* Content Source: [docs/framework/install/dotnet-35-windows-10.md](https://github.com/dotnet/docs/blob/master/docs/framework/install/dotnet-35-windows-10.md)
* Product: **dotnet-framework**
* GitHub Login: @rlander
* Microsoft Alias: **mairaw**

**Comment by jamshedd** [comment]
Adding @rakeshsinghranchi for setup

**Comment by quickware** [comment]
Microsoft, stop ignoring your frustrated customers. Attend this bug!

**Comment by jamshedd** [comment]
@quickware @JacobHelton57 Can you tell me the specific build/version of Windows on which you're trying to enable the .NET 3.5 FOD? 
FYI - @rakeshsinghranchi has left the team, adding @NikolaMilosavljevic instead.
