### ISSUE TITLE
Add Note for when GeneratePackageOnBuild Is True

### ISSUE THREAD

**Issue by MarcelMichau** [dotnet/docs#9354]
Hello!

I ran into the issue where dotnet pack does not build the project when GeneratePackageOnBuild is set to true as per this issue: https://github.com/NuGet/Home/issues/5045#issuecomment-299967452.

Might be a worthwhile note to include in the docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7e805a3-f2ec-b05a-d5c8-29f7a8c16a5f
* Version Independent ID: 4257ec12-df6f-ec52-aad3-012e5fce8133
* Content: [dotnet pack command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-pack?tabs=netcore2x)
* Content Source: [docs/core/tools/dotnet-pack.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-pack.md)
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Thanks for your feedback @MarcelMichau. @KathleenDollard @livarcocc can you comment on this request?

**Comment by mairaw** [comment]
@KathleenDollard @livarcocc friendly ping on this one
