### ISSUE TITLE
= operators in c++ can be overloaded

### ISSUE THREAD

**Issue by linklight2** [dotnet/docs#9366]
In order to assign an object of a user-defined class type something other than its implicit type (which is automatically overloaded), c++ supports assignment operator overloading. For instance, I could create a class to store big numbers and have it accept a string as the right-hand argument. Ex:

class bigNum
{
    public:

        bigNum();
        bigNum(string const& str);
        
        void operator =(string const& str);
}

bigNum();
{
    "Do something"
}

bigNum(string const& str)
{
    bigNum = str;
}

void bigNum::operator =(string const& str)
{
    "Do something"
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71ec2ecc-c995-a549-65aa-564e995b2a89
* Version Independent ID: 64f44af4-ed87-fe94-6e3c-7e38057cdb14
* Content: [Overloadable operators (C# Programming Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/statements-expressions-operators/overloadable-operators)
* Content Source: [docs/csharp/programming-guide/statements-expressions-operators/overloadable-operators.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/statements-expressions-operators/overloadable-operators.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing the question @linklight2 

In C#, you achieve that result by creating implicit conversion operators.  For your example above, you'd create an `implicit operator bigNum (string s)`.  That provides the conversion from `string` to `bigNum`. Once converted, the resultant `bigNum` can be assigned to another `bigNum`.

This is covered in the page on [implicit conversion operators](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/implicit) and in the article on the [assignment operator](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/assignment-operator#operator-overloadability)

I'm closing this as already addressed.
