### ISSUE TITLE
Await keyword C# reference confusingly states that use in Main is disallowed immediately after an example of async Main

### ISSUE THREAD

**Issue by jimcullenaus** [dotnet/docs#9369]
**Issue description**

[The "await" keyword C# reference page](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/await) states:

> Because the use of `async` and `await` in an application entry point is not supported, we cannot apply the `async` attribute to the `Main` method, nor can we await the `GetPageLengthsAsync` method call. 

This paragraph is placed immediately after an example in which the `Main` method has the `async` attribute, and inside that method there is an `await GetPageLengthsAsync()` call.

One of these, either the example or the paragraph, are necessarily wrong, since they are in contradiction with one another.

**Comment by pkulikov** [comment]
@jimcullenaus thanks of reporting it. This was fixed yesterday by #9353 and expected to be live in next day or two.

**Comment by BillWagner** [comment]
As noted by @pkulikov this is fixed and will go live soon.

Closing as fixed.
