### ISSUE TITLE
Name simplification

### ISSUE THREAD

**Issue by alexv-r2r** [dotnet/docs#9372]
In VisualStudio, typing the line from the second code snippet:
Console.WriteLine(header.Trim( new Char[] { ' ', '*', '.' } )); 
will lead to a lightbulb warning "Name can be simplified" to "new char[]" instead, without capitalization.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd91d4c1-d713-b8f1-958f-3547a5150428
* Version Independent ID: 0a6a2496-ca04-fc7e-777f-8d2ef7bef1a6
* Content: [Trimming and Removing Characters from Strings in .NET](https://docs.microsoft.com/en-us/dotnet/standard/base-types/trimming)
* Content Source: [docs/standard/base-types/trimming.md](https://github.com/dotnet/docs/blob/master/docs/standard/base-types/trimming.md)
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by mairaw** [comment]
Thanks for your feedback @alexv-r2r. This is more of a coding style preference than an actual issue. Given that we also have code for VB and C++ using the Framework types instead of the C# type, we feel like we can keep this example as-is. Both Char[] and char[] are correct.
