### ISSUE TITLE
what is default --verbosity <LEVEL>?

### ISSUE THREAD

**Issue by michael-freidgeim-webjet** [dotnet/docs#9373]
It is not clear, what is default --verbosity &lt;LEVEL&gt;. Please specify.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 211afdc7-c796-202d-239d-823f2a499dff
* Version Independent ID: 9439897e-dcb3-bc2e-5cae-35c1ca2e0681
* Content: [dotnet publish command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-publish?tabs=netcore21)
* Content Source: [docs/core/tools/dotnet-publish.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-publish.md)
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Thanks for your feedback @michael-freidgeim-webjet. @KathleenDollard @livarcocc @dsplaisted can you confirm the default verbosity level for dotnet publish and the other commands?

**Comment by michael-freidgeim-webjet** [comment]
Thanks. Will you update the document?

**Comment by mairaw** [comment]
I will @michael-freidgeim-webjet.

**Comment by mairaw** [comment]
Moving this item to the backlog but added to the 3.0 release project. I've added this info to a few topics already but need to check for each command (the default seems to be different in every case). I should hopefully get this done soon.

**Comment by mairaw** [comment]
The idea here was to review all commands to make sure they include the default verbosity level. It seems not all are done yet: https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-store.md

**Comment by pushkin-** [comment]
can defaults of other commands (like `build`) be clarified? Oh though I guess [this](https://learn.microsoft.com/en-us/dotnet/api/microsoft.build.framework.loggerverbosity?view=msbuild-18-netcore#fields) states that Normal is the default when not set.. though this contradicts other issues in this repo that indicate that Minimal is the default
