### ISSUE TITLE
InstallDir incorrect default

### ISSUE THREAD

**Issue by AlexKeySmith** [dotnet/docs#9377]
The default is documented as %LocalAppData%.dotnet. but it instead appears to be %LocalAppData%/Microsoft/dotnet/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2e484a9-5e0c-eb3e-1413-7b507c4fa07d
* Version Independent ID: 5bc7caa5-f1c2-d7d5-fe02-80c65cca9672
* Content: [dotnet-install scripts](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script)
* Content Source: [docs/core/tools/dotnet-install-script.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-install-script.md)
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Thanks for your feedback @AlexKeySmith. @johnbeisner can you confirm?

**Comment by johnbeisner** [comment]
@mairaw 
"LocalAppData\Microsoft\dotnet" is correct.


https://github.com/dotnet/cli/blob/c1b484ad4c4d245914ea16c0b7f952c405536aa3/scripts/obtain/dotnet-install.ps1#L29-L31

**Comment by mairaw** [comment]
Thank you @johnbeisner. I've opened PR #9425 to fix this.

**Comment by AlexKeySmith** [comment]
Thanks for the speedy resolution guys. 👍
