### ISSUE TITLE
Expression-bodied method sometimes evaluates "the last expression" which is only part of a full expression

### ISSUE THREAD

**Issue by eliasx** [dotnet/docs#9383]
It looks like the expression-bodied methods sometimes evaluates part of a full expression

The question is how is "the last expression" determined by the compiler, if "the last expression" is part of "unfinished expression"?

Here is an example to demonstrate different behavior for a similar expression which is a string concatenation expression that has two operands

```
static void Main(string[] args)
{   
    // should print
    // 1->first
    // 2->second
    Console.WriteLine(GetKeyValueString(1, "first"));
    Console.WriteLine(GetKeyValueStrAlt(2, "second"));
            
}

static string GetKeyValueString(int key, object val) => $"{key}->" + val==null? "null" : val.ToString();
static string GetKeyValueStrAlt(int key, object val) => $"{key}->" + (val==null? "null" : val.ToString()); 

```

The above code prints the following 
first
2->second

It looks like int the first case, the compiler is taking only "the last expression" without realizing that it was part of "unfinished expression" where as in the second case, the parentheses somehow helped the compiler to find the "last expression" which is the full expression that is the string concatenation.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 874ea00d-6ec4-55f4-f0e3-e818d21454c7
* Version Independent ID: 98072328-af31-5bc6-9ba4-1353328d5f10
* Content: [Expression-bodied members (C# Programming Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/statements-expressions-operators/expression-bodied-members)
* Content Source: [docs/csharp/programming-guide/statements-expressions-operators/expression-bodied-members.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/statements-expressions-operators/expression-bodied-members.md)
* Product: **dotnet-csharp**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by pkulikov** [comment]
@eliasx it looks you're puzzled by this method:
```csharp
static string GetKeyValueString(int key, object val) => $"{key}->" + val == null ? "null" : val.ToString();
```

It works as expected. Let's check. The method expression uses three operators:
- addition `+`
- equality comparison `==`
- conditional operator `?:`

According to the [operator overview](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/), out of those three, the addition operator has the highest precedence, followed by comparison, with the conditional operator having the lowest precedence.

That means that the expression:
```csharp
 $"{key}->" + val == null ? "null" : val.ToString();
```

is equivalent to the following code:
```csharp
string temp =  $"{key}->" + val;
bool check = temp == null;
string result = check ? "null" : val.ToString();

**Comment by eliasx** [comment]
Thank you Petr, I was puzzled for sure :)  my expectation was the conditional operation will get evaluated before the addition, at least in my actual code as below

This was the actual code that I was working, and I tried to avoid my context but this looks a good puzzle
though

```
class Node {

	public int Data { get;set; }
	public Node Next { get;set; }
	public Node(int data) => Data = data;
	
	public override string ToString() => $"{this.Data}->" + Next==null? "null" : "";
       // public override string ToString() => $"{this.Data}->" + (Next==null? "null" : "");
	
}

```
Thank you again

**Comment by mairaw** [comment]
Thank you @eliasx for your comment. It seems you're less puzzled now with the help from @pkulikov. But if not, please let us know.
