### ISSUE TITLE
"Unit testing F# libraries in .NET Core using dotnet test and xUnit" doesn't work

### ISSUE THREAD

**Issue by glippert** [dotnet/docs#9385]
I can't get these step-by-step instructions to work. (error FS0039: The value, namespace, type or module 'MyMath' is not defined.) It would be *really* helpful for the code example blocks to show the *name of the file*, not just the language (e.g. "F#"). So this is an F# guide but it instructs one to edit "in the MathService class"? Um, "class"? And what file would that be?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17b7cd05-55aa-833e-d6ca-583b3fdb0ef0
* Version Independent ID: cc6cd7ba-8114-9390-531e-d5340947e842
* Content: [Unit testing F# libraries in .NET Core using dotnet test and xUnit](https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-fsharp-with-dotnet-test)
* Content Source: [docs/core/testing/unit-testing-fsharp-with-dotnet-test.md](https://github.com/dotnet/docs/blob/master/docs/core/testing/unit-testing-fsharp-with-dotnet-test.md)
* Product: **dotnet-core**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
Thanks for your feedback @glippert. We'll try to improve the instructions on a future sprint.

**Comment by tienle488** [comment]
Why isn't there a quick helpful answer?  :-)  Here's what I tried and worked.  Hope it helps the next person:
![unit-testing-fsharp-with-nunit Two tests pass now](https://user-images.githubusercontent.com/23621965/105560039-9a2fc000-5cc7-11eb-9842-5d7730dd7986.PNG)
