### ISSUE TITLE
Asp.Net Core tutorials link not working

### ISSUE THREAD

**Issue by CarlBrindle87** [dotnet/docs#9386]
The link gives a 404

https://docs.microsoft.com/en-us/aspnet/core/tutorials/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3caf351-18c6-5211-f2a2-bbdef5918629
* Version Independent ID: f13ef5fe-c17a-ecd1-2a2b-55b3b101da07
* Content: [Samples and tutorials](https://docs.microsoft.com/en-us/dotnet/samples-and-tutorials/)
* Content Source: [docs/samples-and-tutorials/index.md](https://github.com/dotnet/docs/blob/master/docs/samples-and-tutorials/index.md)
* Product: **dotnet**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
@scottaddie @Rick-Anderson can you look at this? It seems this path should work given you also have links such as https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api. 

If you used to have an index.md file and you removed, you should have added a redirection file.
You can take a look at PR #9360 for an example of how we're thinking of handling such cases.

**Comment by scottaddie** [comment]
The index file was indeed removed, but a redirect wasn't added. I'll fix it.

**Comment by mairaw** [comment]
Thank you @scottaddie!
