### ISSUE TITLE
Not much help for complex objects

### ISSUE THREAD

**Issue by Kberg81** [dotnet/docs#9387]
If you are working lists composed of custom classes, this code doesn't help much.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7550db03-fb38-f27b-59a3-ef202349e2f1
* Version Independent ID: 088ccbb9-47bf-da50-c637-07d142e9834f
* Content: [How to: Find the Set Difference Between Two Lists (LINQ) (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/linq/how-to-find-the-set-difference-between-two-lists-linq)
* Content Source: [docs/csharp/programming-guide/concepts/linq/how-to-find-the-set-difference-between-two-lists-linq.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/linq/how-to-find-the-set-difference-between-two-lists-linq.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
Thanks for your feedback @Kberg81. We do cover that scenario in the API reference:
https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.except

But it's a good suggestion to enhance this topic to show custom classes too.
