### ISSUE TITLE
Unclear Statement(s) in Concurrent collections

### ISSUE THREAD

**Issue by MxMaster** [dotnet/docs#9402]
At the beginning of this article, this statement appears: "use the concurrent collection classes whenever the collection will be writing to multiple threads concurrently". What do you exactly mean by "the collection will be writing to multiple threads"?
Multiple Threads can read and/or write from/to a Collection. The collection never does any reading or writing on its own. The correct statement could be: "the collection will be written to by multiple threads"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2a02e95-a17b-bfb0-c4ea-03f5f2d28907
* Version Independent ID: 647b6ea3-cde8-ba16-c9f7-c543c01517d9
* Content: [Thread-Safe Collections](https://docs.microsoft.com/en-us/dotnet/standard/collections/thread-safe/index)
* Content Source: [docs/standard/collections/thread-safe/index.md](https://github.com/dotnet/docs/blob/master/docs/standard/collections/thread-safe/index.md)
* Product: **dotnet**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by MxMaster** [comment]
BTW, I AM fun at parties... Don't you dare think otherwise!

**Comment by mairaw** [comment]
Thanks for your feedback @MxMaster. We don't judge here 😉  

Would you like to submit a PR? Here are the instructions:
https://docs.microsoft.com/en-us/contribute/#quick-edits-to-existing-documents

Our only suggestion would be to say "whenever multiple threads will write to the collection concurrently".
