### ISSUE TITLE
"Type matching" instead of "pattern matching"

### ISSUE THREAD

**Issue by volkan-yazilim** [dotnet/docs#9405]
IMHO, the term "type matching" is more illustrative instead of "pattern matching". Of course, after learned the subject -thanks to your docs and efforts- it suits to the content, but before it does not ring a bell.
I just wanted you to know.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1766cac-6e34-c70b-0933-9d9def2344c4
* Version Independent ID: 38869398-bce4-0321-112d-4b44d558d7b1
* Content: [How to: safely cast by using pattern matching and the is and as operators](https://docs.microsoft.com/en-us/dotnet/csharp/how-to/safely-cast-using-pattern-matching-is-and-as-operators)
* Content Source: [docs/csharp/how-to/safely-cast-using-pattern-matching-is-and-as-operators.md](https://github.com/dotnet/docs/blob/master/docs/csharp/how-to/safely-cast-using-pattern-matching-is-and-as-operators.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
Thanks for your feedback @volkan-yazilim. Since this is also part of the spec and the spec won't be changed, I'm closing this issue.

**Comment by BillWagner** [comment]
To elaborate, the "type pattern" is one pattern of many that will be supported. Others are in the early proposal stages. Others are noted in the [pattern matching spec](https://github.com/dotnet/csharplang/blob/master/proposals/patterns.md) on the dotnet/csharplang repo.
