### ISSUE TITLE
This page needs to be shown previously to ease understand the concepts, IMHO

### ISSUE THREAD

**Issue by volkan-yazilim** [dotnet/docs#9409]
this page has explained every question in my mind emerging while reading previous pages and trying to understand new concepts. Because I connect theoretical concepts with physical image or tools to realize in my mind.
I would like you to know that. Thanks for your effort.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afc9e424-8275-99f9-842f-93346eb9c986
* Version Independent ID: 12060f59-583e-e920-0564-2b16fe45c3e5
* Content: [Explore code with the Roslyn syntax visualizer in Visual Studio](https://docs.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/syntax-visualizer?tabs=csharp#syntax-visualizer)
* Content Source: [docs/csharp/roslyn-sdk/syntax-visualizer.md](https://github.com/dotnet/docs/blob/master/docs/csharp/roslyn-sdk/syntax-visualizer.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
Thanks for letting us know @volkan-yazilim! We appreciate the feedback.
