### ISSUE TITLE
UWP Support

### ISSUE THREAD

**Issue by rolfik** [dotnet/docs#9410]
Is this valid also for Universal Windows Applications (UWP) on Windows 10?
How to call web REST services using WebBinding?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 073c9840-8baf-f74b-2424-7d5a31195402
* Version Independent ID: 6eacf32e-efa3-0894-916f-549898f61375
* Content: [Accessing WCF Services with a Windows Store Client App](https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/accessing-wcf-services-with-a-windows-store-client-app)
* Content Source: [docs/framework/wcf/feature-details/accessing-wcf-services-with-a-windows-store-client-app.md](https://github.com/dotnet/docs/blob/master/docs/framework/wcf/feature-details/accessing-wcf-services-with-a-windows-store-client-app.md)
* Product: **dotnet-framework**
* GitHub Login: @Lxiamail
* Microsoft Alias: **wcfsrvt**

**Comment by tdykstra** [comment]
Apologies for delayed response.

> Is this valid also for Universal Windows Applications (UWP) on Windows 10?

Are you still looking for an answer to this question or did you find the answer already?

> How to call web REST services using WebBinding?

Please clarify how this question is related to this article -- the article is about calling WCF services and doesn't mention WebBinding.

**Comment by rolfik** [comment]
There is only limitted subset of WCF bindings in UWP applications (for Windows 10).
WebBinding for calling REST web services is missing or am I wrong?
Actually I had to add another SOAP 1.1 binding to existing REST WCF service just to call it from UWP.

**Comment by tdykstra** [comment]
@HongGit Can you help with this question?
