### ISSUE TITLE
Why do these specify an empty string instead of null?

### ISSUE THREAD

**Issue by StingyJack** [dotnet/docs#9411]
Just curious

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f6762d9-17f9-b4f2-e0ff-a919a0d861c0
* Version Independent ID: bc653d72-afa1-aa4c-e130-74bd181b53bd
* Content: [Caller Information (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/caller-information)
* Content Source: [docs/csharp/programming-guide/concepts/caller-information.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/caller-information.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
Thanks @StingyJack. The example is just setting an initial value, that in this case is an empty string.

For that reason, I'm closing the issue.
