### ISSUE TITLE
Uninstalling may be not enough

### ISSUE THREAD

**Issue by zawor** [dotnet/docs#9412]
Had a lot of runtimes and sdks accumulated over time on my dev machine. At some point i decided to do the cleanup and uninstalled quite a few from under appwiz.cpl (or add/remove programs). Unfortunately after running `dotnet --list-sdks` or `dotnet --list-runtimes` i still saw those which were uninstalled... Interestingly enough i discovered that installers have left a lot of empty dirs under `C:\Program Files\dotnet\sdk`, `C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All` and `C:\Program Files\dotnet\shared\Microsoft.NETCore.App`. Removing those made `--list-sdks` and `--list-runtimes` to no longer list uninstalled runtimes/sdks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4ca18b0-5533-f5b9-2eb4-9853a4fa61ed
* Version Independent ID: a12b8b5c-a3af-d1c5-a27c-39e9d390dff2
* Content: [How to remove .NET runtime and SDK](https://docs.microsoft.com/en-us/dotnet/core/versions/remove-runtime-sdk-versions?tabs=Windows)
* Content Source: [docs/core/versions/remove-runtime-sdk-versions.md](https://github.com/dotnet/docs/blob/master/docs/core/versions/remove-runtime-sdk-versions.md)
* Product: **dotnet-core**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
Thanks for your feedback @zawor. @danroth @KathleenDollard can you take a look at this since it's a product behavior and not a content issue?

**Comment by KathleenDollard** [comment]
@livarcocc @johnbeisner 

Are we aware of cases where Add/Remove programs is not completing successfully, or are we otherwise aware of this problem? 

@zawor We'd like to track this with you. Could you post this as an issue at GitHub.com/dotnet/sdk

**Comment by zawor** [comment]
sure thing!

**Comment by KathleenDollard** [comment]
yes

**Comment by BillWagner** [comment]
closing per @KathleenDollard

**Comment by mingtong** [comment]
Unfortunately, I cannot uninstall dotnet-sdk-1.0.0-preview-xxx-version.
Even I install 2.2.1, then I run dotnet --info, still showed 1.0.
My OS is CentOS 7 x64.

**Comment by zawor** [comment]
@mingtong have a look here ([dotnet/cli#9222](https://github.com/dotnet/cli/issues/9222#issuecomment-420617509)) as it may be related

**Comment by mingtong** [comment]
> @mingtong have a look here ([dotnet/cli#9222](https://github.com/dotnet/cli/issues/9222#issuecomment-420617509)) as it may be related

I solved by manually deleted the installation files in the path, thank you.
