### ISSUE TITLE
.Net Core 3.0 Needs ASP.Net Web Forms

### ISSUE THREAD

**Issue by JosephRufft** [dotnet/docs#9415]
Windows forms have been added to .Net Core, but we require Web Forms to use it!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b76cb0d-df6d-88c4-557d-ad327a566eef
* Version Independent ID: 95083e1c-ef53-e813-08e2-1aa31b431f00
* Content: [Choose between .NET Core and .NET Framework for server apps](https://docs.microsoft.com/en-us/dotnet/standard/choosing-core-framework-server)
* Content Source: [docs/standard/choosing-core-framework-server.md](https://github.com/dotnet/docs/blob/master/docs/standard/choosing-core-framework-server.md)
* Product: **dotnet**
* GitHub Login: @cartermp
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
I'm not sure we understand your request. .NET Core 3 is adding WinForms and WPF support. We're not adding Web Forms to .NET Core 3.

So for that reason, I'm closing this. But if you have more details about what you're trying to do, please let us know.

**Comment by CatalinAdlerDF** [comment]
@mairaw Just as WinForms/WPF now runs on top of .NET Core, I'd be desirable to be able to run WebForms on top of .NET Core.

Tons of apps out there that would benefit from migration to Core.

**Comment by JosephRufft** [comment]
The issue is ASP.Net Web Forms needs to be added to .Net Core!
