### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by volkan-yazilim** [dotnet/docs#9420]
"your can use" -> "you can use"
in sentence "By adding what is called a binding redirect your can use the new library version without having to recompile your app. "

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3e468f2-2cc4-a461-4e67-47e7aeff555d
* Version Independent ID: 5e2ade07-13fa-ddfc-377a-f6aa52738b4e
* Content: [C# Versioning - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/versioning#override)
* Content Source: [docs/csharp/versioning.md](https://github.com/dotnet/docs/blob/master/docs/csharp/versioning.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
Thank you @volkan-yazilim. Would you like to submit a PR to fix this?
You can find instructions here at https://docs.microsoft.com/en-us/contribute/#quick-edits-to-existing-documents.
