### ISSUE TITLE
Template not working

### ISSUE THREAD

**Issue by RanchMobile** [dotnet/docs#9426]
I'm getting the following error:
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='System.Windows.FrameworkElement', AncestorLevel='1''. BindingExpression:Path=Parent; DataItem=null; target element is 'TextBlock' (Name=''); target property is 'Parent' (type 'DependencyObject')

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 463966c3-3bf3-d3da-418f-4756956a99c0
* Version Independent ID: 21abf0b8-13d4-f81f-fc81-09505902fd19
* Content: [ComboBox Styles and Templates](https://docs.microsoft.com/en-us/dotnet/framework/wpf/controls/combobox-styles-and-templates)
* Content Source: [docs/framework/wpf/controls/combobox-styles-and-templates.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/controls/combobox-styles-and-templates.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks for your feedback @RanchMobile. Is this error from the code from the article?

**Comment by RanchMobile** [comment]
> Thanks for your feedback @RanchMobile. Is this error from the code from the article?

This occurs when I right click and create a copy template with a generic control without any modification using Blend 2017.

**Comment by mairaw** [comment]
Ok, thanks for getting back to us. If that's the case, I'd suggest you to file a product bug at https://developercommunity.visualstudio.com/spaces/61/index.html instead. Feel free to get back to us if you ever hear back from the dev team and if there are any content updates you feel we should make.
