### ISSUE TITLE
Compiler Error

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#9427]
@Ediceu commented on [Wed Dec 05 2018](https://github.com/dotnet/docs.pt-br/issues/99)

Olá, teria como tropicalizar os códigos podendo ser mostrados em idiomas especificos ex:
retorno em Português(PT-BR),

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 8b2cb61f-1605-70ba-c5fb-cc4a9d9f2c8d
* Version Independent ID: 6eaec3e9-0ed9-f3ec-7516-032d57246715
* Content: [Erro do Compilador CS0103](https://docs.microsoft.com/pt-br/dotnet/csharp/language-reference/compiler-messages/cs0103)
* Content Source: [docs/csharp/language-reference/compiler-messages/cs0103.md](https://github.com/dotnet/docs.pt-br/blob/live/docs/csharp/language-reference/compiler-messages/cs0103.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by CeciAc** [comment]
Hi team, 
the user is requesting to have the comments inside the codes translated to the specific locale but is outside of our scope.
best

**Comment by mairaw** [comment]
That is not a source issue but a localization issue. I'll answer in the original issue.
