### ISSUE TITLE
Still lacks the fundamental and essential building blocks of using exceptions correctly

### ISSUE THREAD

**Issue by sam-wheat** [dotnet/docs#9432]
I am sorry to be critical but I don't think this document offers the kind of specific advice a new developer might be looking for when embarking on a new project or trying to diagnose issues in an existing one.

> A well-designed app handles exceptions and errors to prevent app crashes.

I will start with line one and say that an objective of exception handling is not to prevent app crashes (although it is a welcome side effect).  To the contrary, a much more worthy objective of exception handling is to shut the app down in the most expedient way when an exception occurs.  

The objective of preventing app crashes is actually achieved not by HANDLING exceptions but by systematically preventing them through rigorous validation and actually THROWING exceptions at critical areas.  Another way of saying the same thing is that putting `catch` blocks everywhere in your code buys you nothing - it just moves your errors farther downstream.  Conversely, throwing exceptions early and often at low levels in the application has the effect of hardening the code and fully expressing the business logic.

One of the most misguided beliefs among developers is that their application must somehow press on and continue to function regardless of what error occurs.  This is analogous to driving your car on the interstate at full speed on a flat tire for fear of being late to work.  The goal of making an application impervious to exceptions by using `try/catch` blocks almost immediately leads to ambiguous business logic, false assumptions, and tepid error checking.  This further leads to data corruption, intermittent errors, and errors that are difficult or impossible to trace.

> Use try/catch/finally blocks around code that can potentially generate an exception.
> For conditions that are likely to occur but might trigger an exception, 

These statements are meaningless and offer no guidance.  ANY line of code might trigger an exception.  The question the developer has to ask is "Should I handle an exception here?"  The answer is very often a resounding "NO!"

> Handle common conditions without throwing exceptions
> The method to choose depends on how often you expect the event to occur.

I don't believe these statements to be in any way correct or even related to if or how an exception should be handled.

More relevant questions to ask are:

* Is the error the result of user input?  
* Can we display an error message and let the user try again?
* Should upstream business logic have prevented this circumstance from occurring?
* Does downstream business logic expect my code to check and handle this condition?
* Can I reliably determine the cause of the error and create a code path to handle it that is within the boundaries of my business logic?
* Can I safely and reliably conclude the error is caused by code/events/circumstances beyond my control and will have no residual impact if I swallow or handle the error?

> Design classes so that exceptions can be avoided

Well.........yes, of course.  But don't we do that already?  What does useful information does this section offer?

> Another way to avoid exceptions is to return null for extremely common error cases instead of throwing an exception.
> Throw exceptions instead of returning an error code

The above two lines are contradictory and offer no insight into how or when exception handling should occur.  Again, the number of times an event is expected to occur is most likely irrelevant as to whether exception handling should occur.  Consider the following methods:

This public method is called from a public API controller.  The user can put any number they like in a query string and make a call.  In this case the code should never throw an exception if a customer is not found:

	public Customer GetCustomerByID(int id)
	{
		Customer customer = db.GetCustomer(id);
		return customer; // don't care if it's null
	}

This private method is called from deep within an order processor.  The difference between this method and the preceding one is that before being saved to disk and processed the order should have been completely validated.  A null customer here means that upstream code is not doing it's job. This code should definitely throw:

	private Customer GetCustomerByID(int id)
	{
		Customer customer = db.GetCustomer(id);
		
		if(customer == null)
			throw new Exception($"Bad customer ID: {id}");
		
		return customer; 
	}

> Callers should be able to assume that there are no side effects when an exception is thrown from a method

I don't believe this is true.  An unhandled exception is an unknown and something for which no code path exists.  When an unhandled exception occurs callers should make no assumptions and allow the exception to flow up to the global exception handler. Processing should stop.  

In the example below if an exception occurs during the withdrawal it is potentially unhandled:

	private static void TransferFunds(Account from, Account to, decimal amount)
	{
		string withdrawalTrxID = from.Withdrawal(amount);
		try
		{
			to.Deposit(amount);
		}
		catch
		{
			from.RollbackTransaction(withdrawalTrxID);
			throw;
		}
	}

In general this document fails to convey these essential exception handling best practices:

1.) Don't catch exceptions you don't handle.  Logging an exception is not handling it.  Let exceptions flow up to the global handler.  This concept is often difficult to grasp because it means you use fewer rather than more `try/catch` blocks.  

2.) Don't be afraid to throw exceptions if calling code is not conforming to business rules or is in an invalid state.  Throw early and often!

3.) Catching exceptions does not necessarily make your code better.  Preventing exceptions makes your code better.  Throwing exceptions when state is invalid or business logic is violated has the effect of hardening your code and causing your business logic to become fully expressed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1ea31f6-516f-100d-046e-1a0445d92824
* Version Independent ID: a713e8c9-8210-761d-9ae7-238793825ff3
* Content: [Best Practices for Exceptions](https://docs.microsoft.com/en-us/dotnet/standard/exceptions/best-practices-for-exceptions)
* Content Source: [docs/standard/exceptions/best-practices-for-exceptions.md](https://github.com/dotnet/docs/blob/master/docs/standard/exceptions/best-practices-for-exceptions.md)
* Product: **dotnet**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by BillWagner** [comment]
@sam-wheat Thanks for expressing your concerns. You've put a lot of thought into this issue, and many of the ideas have merit.  

#9430 was merged last night, which made some improvements but did not address many of these concerns.

Do you want to submit a PR based on your analysis above?

**Comment by sam-wheat** [comment]
@BillWagner Thank you Bill.  What is required for submitting a PR?

**Comment by BillWagner** [comment]
@sam-wheat That's fantastic.

Most of the information you need is in the .NET Section of the [Contributor guide](https://docs.microsoft.com/Contribute/dotnet-contribute). 

I'll recommend starting with an outline, open a PR using the text '[WIP]' (for "work in progress") at the beginning of the title. I'll watch for it.  Then, just @- mention me when you have questions, or are ready for a review.

Thanks again.

**Comment by sam-wheat** [comment]
@BillWagner 
I think I botched the process but here is a [PR](https://github.com/dotnet/docs/pull/9531)
