### ISSUE TITLE
What is about 42 and "The meaning of life"?

### ISSUE THREAD

**Issue by volkan-yazilim** [dotnet/docs#9435]
Captain was here.
?v=aboZctrHfK8

Thank you for comprehensive document about tuples.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bf15268-9d34-cf10-97b9-0b94022c3305
* Version Independent ID: 17728168-48fa-0f5f-0c19-31ae4ce6fdb9
* Content: [Tuple types - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/tuples#assignment-and-tuples)
* Content Source: [docs/csharp/tuples.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tuples.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by rpetrusha** [comment]
Thank you for the positive feedback, @volkan-yazilim. We're please that you found the article useful and comprehensive.
