### ISSUE TITLE
Connections should be reused between different publish calls.

### ISSUE THREAD

**Issue by wmeints** [dotnet/docs#9439]
I see you are not reusing connections when publishing events. The RabbitMQ documentation states that connections should be long-lived objects. Creating a connection has a lot of overhead attached to it. See also https://www.rabbitmq.com/dotnet-api-guide.html#connection-and-channel-lifspan

Also, make sure you enable automatic connection failure recovery. It will save you some major headaches. Details about it are listed in the documentation: https://www.rabbitmq.com/dotnet-api-guide.html#recovery

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f590167-a388-94ac-e39b-463978a761b0
* Version Independent ID: cf81b170-d5eb-ca3d-ef50-fff0bea82673
* Content: [Implementing an event bus with RabbitMQ for the development or test environment](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/multi-container-microservice-net-applications/rabbitmq-event-bus-development-test-environment)
* Content Source: [docs/standard/microservices-architecture/multi-container-microservice-net-applications/rabbitmq-event-bus-development-test-environment.md](https://github.com/dotnet/docs/blob/master/docs/standard/microservices-architecture/multi-container-microservice-net-applications/rabbitmq-event-bus-development-test-environment.md)
* Product: **dotnet**
* GitHub Login: @CESARDELATORRE
* Microsoft Alias: **wiwagn**

**Comment by mvelosop** [comment]
Hi @wmeints, thanks for the heads up!

I think perhaps it should be emphasized more that the code shown is just a simplified version, to make it easier to grasp the whole concept. There are two links to the actual code, both right before and right after the code fragment. The actual code considers what you mention and also includes adding the retries policy with Polly, but I think the actual code adds too much "noise" to the core concept.

You can check that in the connection is a singleton in the actual code:
https://github.com/dotnet-architecture/eShopOnContainers/blob/fe0e41d0a6375664913b21bbb8a6f5abe43bc49d/src/Services/Ordering/Ordering.API/Startup.cs#L155

Comments?

**Comment by wmeints** [comment]
Hi Miguel,

Sorry for the late reply. I'm in the middle of writing the last two
chapters of my book. So that takes most of my time.

It certainly looks a lot better in the github repo.
And I totally understand that you can't add every aspect of the code in the
description on the website. But as you mentioned, it should be clear that
it is for demonstration purposes.
Is the actual code linked to from the article? I couldn't find it back when
I submitted the comment.

Kind regards,

Willem Meints

**Comment by mvelosop** [comment]
Hi Willem,

Yep, the actual code is linked from the article, will emphasize that it's a simplified version what's included in the article!

Cheers.
