### ISSUE TITLE
SEO updates - .NET Core folder

### ISSUE THREAD

**Issue by wadepickett** [dotnet/docs#9440]
Assign yourself to a folder by putting your github id next to it for the 12-6-2018 SEO effort.  One person per folder.

Folders:

--additional tools: adegeo

--build: adegeo

--deploying: rpetrusha

--docker: adegeo

--migration: mairaw

--porting: corob-msft

--testing: adegeo

-- tools: mairaw

--tutorials: @BillWagner 

--versions: adegeo

--whats-new: rpetrusha

**Comment by rpetrusha** [comment]
media can be removed -- it's an images folder.

**Comment by mairaw** [comment]
Removed @rpetrusha

**Comment by wadepickett** [comment]
removed mikeblome from --additional and --build per his request.

**Comment by wadepickett** [comment]
@mairaw, "--tools" was ommited by mistake.  Thanks for adding it back in.

**Comment by corob-msft** [comment]
Do I need to join a group or request some permissions in order to edit my name into the items at the top?

**Comment by mairaw** [comment]
Yes, let me add you.

**Comment by Thraka** [comment]
No one has taken `testing` want me to grab that? @wadepickett I saw you did one item from there, did you do any others or can I take it over?

**Comment by mairaw** [comment]
Just see if changes wouldn't conflict with the global changes I'm making with #9464 since that involves all folders. If all you'd do was add the .NET Core brand and ms.custom, my PR already covers that.

**Comment by Thraka** [comment]
Confirming all of my assigned folders have been completed. If everyone wants to confirm, we can probably close this.

**Comment by mikeblome** [comment]
@Thraka my tasks are complete

**Comment by corob-msft** [comment]
@Thraka I have nothing to add.
