### ISSUE TITLE
C# Guide: Getting started with the cross-platform command line tools

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#945]
The getting-started-with-visual-studio topic (http://github.com/dotnet/docs/blob/master/docs/csharp/getting-started/with-cross-platform-tools.md) should contain:

o installation information for the dotnet cli
o Create and run your first C# program.

Some of these concepts are covered in the getting started section for .NET core. Where applicable, this topic should reference that content rather than replicating it. It may be wise to make appropriate edits to that topic, or make a very samll topic with slightly different samples.

**Comment by BillWagner** [comment]
@tompratt-AQ I just assigned this one to you. Let me know if you have a Mac to work with. If not, we'll move the issue.

**Comment by GuardRex** [comment]
@BillWagner I'm going to take these off my issues list headed here into the final week. It's a little easier for me to see when filtering GH issues what's left if these aren't assigned to me.

**Comment by BillWagner** [comment]
Closing as this won't follow the updated organization of the new C# Guide.
