### ISSUE TITLE
C# Guide: Getting Started with C# Interactive

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#946]
The getting-started-with-csharp-interactive topic (http://github.com/dotnet/docs/blob/master/docs/csharp/getting-started/with-csharp-interactive.md) should contain:

o how to install C# interactive on windows, in Visual Studio, and on Mac
o basic definition of a REPL
o A tour of the major features of C# Interactive, with examples.

**Comment by GuardRex** [comment]
When *interactive/index.md* is created, activate link in *docs/csharp/whats-new/index.md* to the new topic.

**Comment by BillWagner** [comment]
Closing as this won't match the new organization of the C# Guide.
