### ISSUE TITLE
Missing from the TOC

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#9468]
By design @BillWagner? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92991e4f-6d00-9e10-9a0d-1058ba06457f
* Version Independent ID: e26cd6f8-ba2c-b8df-919f-4f1ecfd80864
* Content: [Local functions vs. lambda expressions](https://docs.microsoft.com/en-us/dotnet/csharp/local-functions-vs-lambdas)
* Content Source: [docs/csharp/local-functions-vs-lambdas.md](https://github.com/dotnet/docs/blob/master/docs/csharp/local-functions-vs-lambdas.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
Another one: https://docs.microsoft.com/en-us/dotnet/csharp/implicitly-typed-lambda-expressions

**Comment by BillWagner** [comment]
In both cases, yes, this is by design.

They are both "sidebars" to an existing article. If I find the right home for them, I'll make them move visible.

**Comment by Thraka** [comment]
SO WEIRD! I just came across this and there you go, you both found this.

Here is an idea. What if we put this in its own folder with its own TOC that pointed BACK to the parent article? It's a different design but at least gives the users a sense of direction versus having a blank TOC and thinking something is wrong? I donno.... 😄
