### ISSUE TITLE
ColumnAttribute and TextLoader.Column and TextLoader.Arguments has header property

### ISSUE THREAD

**Issue by PeterPann23** [dotnet/docs#9470]
To me, this seems to all address the same problem on several different steps of designing the data, perhaps make ordinal an integer and not a string and define the data kind all on-top of the class and have the text loader override it when needed if needed. Most likely one would create a model class as in MVC that consumes a given "view" on the world.  Perhaps my MVC experience has made me bias but this in my opinion overly complicated as is. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a27e9feb-8c29-a1ed-975f-5ce97f815147
* Version Independent ID: 30dc10c1-423c-617c-2c3d-2354f7bba073
* Content: [ColumnNameAttribute Class (Microsoft.ML.Runtime.Api)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.runtime.api.columnnameattribute?view=ml-dotnet)
* Content Source: [dotnet/xml/Microsoft.ML.Runtime.Api/ColumnNameAttribute.xml](https://github.com/dotnet/ml-api-docs/blob/live/dotnet/xml/Microsoft.ML.Runtime.Api/ColumnNameAttribute.xml)
* Product: **dotnet-ml-api**
* GitHub Login: @sfilipi
* Microsoft Alias: **johalex**

**Comment by mairaw** [comment]
@JRAlexander can you please triage this? Also, can we move the ML.NET API feedback to the machinelearning repo instead? We've moved the .NET API reference out of dotnet/docs as well.

**Comment by JRAlexander** [comment]
@mairaw, This appears to be a product question as opposed to a content one. I'll create an issue in the product repo and reference this. Let's take your moving request offline as I don't understand. Thanks!

**Comment by JRAlexander** [comment]
@PeterPann23 Thank you for the feedback. I've opened an issue in the dotnet/machinelearning repo as this is product feedback.
