### ISSUE TITLE
Example Issue

### ISSUE THREAD

**Issue by Wetwer** [dotnet/docs#9472]
In this article
Example
Example
Example
Example
Example
Example

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 870ea49c-ad84-f940-8d27-17c8b25beb97
* Version Independent ID: 285ef531-525a-8703-0f16-73a3c9e497b0
* Content: [Try...Catch...Finally Statement (Visual Basic)](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/statements/try-catch-finally-statement#example-4)
* Content Source: [docs/visual-basic/language-reference/statements/try-catch-finally-statement.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/language-reference/statements/try-catch-finally-statement.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by rpetrusha** [comment]
Thanks for pointing out the abundance of Example headings. We've opened #9485 to address the issue by creating a single Examples section.
