### ISSUE TITLE
"What's new in .NET Core 2.2" doesn't show up in table of contents sidebar

### ISSUE THREAD

**Issue by jonstodle** [dotnet/docs#9473]
The table of contents sidebar does not contain "What's new in .NET Core 2.2" in the "What's new in .NET Core" section of ".NET Core Guide". At the moment, only the articles for 2.0, 2.1 and 3.0 are visible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5dcb324-3ec5-e6a0-3a3c-76e139ae00e0
* Version Independent ID: a0077d6b-212f-03e9-a5f6-4cbc4c10d99e
* Content: [What's new in .NET Core 2.2](https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-2-2)
* Content Source: [docs/core/whats-new/dotnet-core-2-2.md](https://github.com/dotnet/docs/blob/master/docs/core/whats-new/dotnet-core-2-2.md)
* Product: **dotnet-core**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by rpetrusha** [comment]
Thanks for pointing this out, @jonstodle. This issue is addressed in #9431, which we've just merged. The change should be reflected on docs.microsoft.com in the next day or two. Since the PR has merged, I'll close this issue.
