### ISSUE TITLE
Great Info

### ISSUE THREAD

**Issue by thegongben** [dotnet/docs#9474]
This is great information. It's just that for a beginner there is too much information! I am very glad the dot Net has gone open source.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92857acd-4048-85cd-39e8-765664c19133
* Version Independent ID: 7965ba49-47d6-53e5-184e-96ef903b1c9b
* Content: [Interoperability with POX applications](https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/interoperability-with-pox-applications)
* Content Source: [docs/framework/wcf/feature-details/interoperability-with-pox-applications.md](https://github.com/dotnet/docs/blob/master/docs/framework/wcf/feature-details/interoperability-with-pox-applications.md)
* Product: **dotnet-framework**
* GitHub Login: @Lxiamail
* Microsoft Alias: **wcfsrvt**

**Comment by rpetrusha** [comment]
Thank you for the positive feedback, @thegongben!
