### ISSUE TITLE
Obsolete

### ISSUE THREAD

**Issue by jasonxz** [dotnet/docs#9476]
Is there an up-to-date version of this since literally everything on this page is marked "Obsolete"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4185570-21cc-dcdb-62fd-d05bceb62f81
* Version Independent ID: 4f0fe52a-a771-d044-593d-2bb65df15e0d
* Content: [Data transforms in ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/resources/transforms)
* Content Source: [docs/machine-learning/resources/transforms.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/resources/transforms.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by JRAlexander** [comment]
@jasonxz - working on this update right now (PR https://github.com/dotnet/docs/pull/9371) - should be live in the few days updated for 0.8.
