### ISSUE TITLE
Clarifying using await in Main

### ISSUE THREAD

**Issue by haydenhancock** [dotnet/docs#9496]
"Normally, you would prefer to await the completion of the task, as in the ProcessRepositories method, but that isn't allowed in the Main method." This isn't accurate if you are using C# 7, right? I was able to change my LangVersion property to 7.1 and the signature of the Main method to return a Task to get this to work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bfcc1a8-ddda-810c-17b0-56a506045d67
* Version Independent ID: 5415878b-e60b-5433-7b4b-efc8259908f0
* Content: [Create a REST client using .NET Core](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/console-webapiclient)
* Content Source: [docs/csharp/tutorials/console-webapiclient.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/console-webapiclient.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
Thanks @haydenhancock. We need to update some topics in regards to this new C# feature,

**Comment by BillWagner** [comment]
Adding the "up for grabs" label for community members to consider this.
