### ISSUE TITLE
C# Tutorial: Creating Portable Libraries

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#950]
This issue tracks the creation of this topic: https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/creating-portable-libraries.md

This tutorial should provide an end to end scenario that creates a library that can be used across multiple platform targets. It should walk the user through creating the library, updating the targets, creating a NuGet package, and how to distribute that package on different target environments.

The tutorial should demonstrate features of a cross-platform team where some are working on Windows, using Visual Studio, and some are on MacOS, using VS Code.

**Comment by mairaw** [comment]
PCL is deprecated now with .NET Standard.
