### ISSUE TITLE
Failed to run the container - The specified framework 'Microsoft.NETCore.App', version '1.1.2' was not found.

### ISSUE THREAD

**Issue by Golash** [dotnet/docs#9508]
After running the docker run command I'm getting the following error:

C:\code\Containers\Hello&gt;docker run --rm dotnetapp-dev Hello from Docker
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '1.1.2' was not found.
  - Check application dependencies and target a framework version installed at:
      /usr/share/dotnet/
  - Installing .NET Core prerequisites might help resolve this problem:
      https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
  - The .NET Core framework and SDK can be installed from:
      https://aka.ms/dotnet-download
  - The following versions are installed:
      2.1.6 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Running on Windows 10

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72ef1481-3b6f-30bf-330d-45400c0a349c
* Version Independent ID: 03a156f7-b178-4d54-503d-26d229f89dcd
* Content: [Containerize an app with Docker - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/docker/docker-basics-dotnet-core)
* Content Source: [docs/core/docker/docker-basics-dotnet-core.md](https://github.com/dotnet/docs/blob/master/docs/core/docker/docker-basics-dotnet-core.md)
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **adegeo**

**Comment by Golash** [comment]
It seems like the "dotnet new console" command generated an Hello.csproj file with <TargetFramework>netcoreapp1.1</TargetFramework> but the based image is microsoft/dotnet:2.1-sdk - once changing the  TargetFramework to netcoreapp2.1 the container running successfully.

**Comment by mairaw** [comment]
Thanks for your feedback @Golash. We'll have to investigate this issue and report back.

**Comment by Thraka** [comment]
@Golash It seems you have solved the problem. I was going to say it seemed like you had a container version-local version mismatch.

I'm curious why you generated a 1.1 app with just the basic command? Perhaps you have a global json config somewhere pointing to a different runtime.

Anyway, glad you're working now.

Bye!
