### ISSUE TITLE
Insufficient explanation on ICorDebugController.IsRunning

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/docs#9512]
It is not clear what this means. Can IsRunning be relied upon to determine the state of the debuggee process, i.e. whether it's in the Stopped or Running state? Or it can be false when the debuggee is in the Running state but no threads are "running"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c79327d6-7935-386a-3dae-ee80147ad1e7
* Version Independent ID: f4b25452-32d4-0f1f-8bde-c9551567c278
* Content: [ICorDebugController::IsRunning Method](https://docs.microsoft.com/en-us/dotnet/framework/unmanaged-api/debugging/icordebugcontroller-isrunning-method?view=dynamics-usd-3)
* Content Source: [docs/framework/unmanaged-api/debugging/icordebugcontroller-isrunning-method.md](https://github.com/dotnet/docs/blob/master/docs/framework/unmanaged-api/debugging/icordebugcontroller-isrunning-method.md)
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by mairaw** [comment]
@noahfalk can you help with this feedback?

**Comment by KirillOsenkov** [comment]
Also when a managed callback is processing, what is the state? 
How do I determine if the debuggee will resume after the current managed callback is done?

**Comment by noahfalk** [comment]
Sorry I've been on vacation and just getting back now. Logically the controller is always in one of two states, running or stopped. Stopped means that the debugger has suspended all managed code execution, running means the debugger is not doing that (which is to say, the code still might not be running, but it isn't the debugger that is preventing that from occurring). Starting from a running state, as soon as a debug event occurs the debugger transitions to the stopped state, and dispatches the callback to you. Once you have both returned from the callback and called ICorDebugProcess::Continue the process returns to the running state once more.

> Also when a managed callback is processing, what is the state?

Stopped

> How do I determine if the debuggee will resume after the current managed callback is done?

You can assume that it always resumes running, but you don't know how long it will run before it stops for the next debug event. For example imagine a debuggee that has two threads, both of which are simultaneously executing a breakpoint instruction on two separate cores. The debugger will enter the stop state and deliver a breakpoint callback for thread 1. After continuing from that event logically the debugger re-enters the running state, but then without executing any additional assembly instructions in the debuggee it immediately transitions back to the stopped state to deliver the breakpoint callback from thread 2. There is a logical running state between each event, but there is no guarantee the debuggee stays in that state long enough for the debugger to observe a side-effect other than having generated another debug event.


I should also clarify what it means to resume. From the debugger's perspective that only means that the debugger hasn't explicitly blocked all managed threads from running using some OS synchronization primitive. The debugger running state does not account for:

- Explicitly suspending individual threads with the debugger's Suspend API
- Explicitly suspending threads using OS native APIs such as SuspendThread
- Threads that are blocked on other synchronization primitives
- Threads that aren't marked runnable in the OS scheduler for any other reason
- Threads that are marked runnable in the OS scheduler, but aren't currently assigned to one of the cores.
