### ISSUE TITLE
"See also" change

### ISSUE THREAD

**Issue by danielgestwa** [dotnet/docs#9513]
Add link to lambda expressions in "See also" part.
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/statements-expressions-operators/lambda-expressions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9eba9bb-8296-b41c-f8f3-4cebe488722e
* Version Independent ID: 95b1655b-a782-02b1-ca0c-14f1b95bf5a5
* Content: [delegate (C# Reference)](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/delegate)
* Content Source: [docs/csharp/language-reference/keywords/delegate.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/delegate.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
That's a good idea @danielgestwa. Would you like to contribute with a pull request?

You can find the instructions on how to do that at https://docs.microsoft.com/en-us/contribute/#quick-edits-to-existing-documents.
