### ISSUE TITLE
461814 is double in the list above

### ISSUE THREAD

**Issue by iwangoll** [dotnet/docs#9514]
461814 .NET Framework 4.7.2 installed on Windows 10 Fall Creators Update and earlier OS versions
461814 .NET Framework 4.7.2 installed on Windows 10 October 2018 Update

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2115da38-e95e-46fc-1e2d-da88ef92c6cf
* Version Independent ID: a3790e8a-0654-851b-c991-ab7382025406
* Content: [How to: Determine which .NET Framework versions are installed](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed#net_d)
* Content Source: [docs/framework/migration-guide/how-to-determine-which-versions-are-installed.md](https://github.com/dotnet/docs/blob/master/docs/framework/migration-guide/how-to-determine-which-versions-are-installed.md)
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by mairaw** [comment]
Thank you for letting us know. We'll take care of this shortly.

**Comment by rpetrusha** [comment]
Thanks for pointing this out, @iwangoll. The information is actually correct. It made a great deal of sense when we first published it, but now, with the passage of a few months, I was no less convinced than you that it is erroneous. I'll open a pull request shortly that tries to make the release key values for .NET Framework 4.7.2 clearer.

**Comment by rpetrusha** [comment]
This was addressed in #9557,
