### ISSUE TITLE
Link to page not found

### ISSUE THREAD

**Issue by LuigiBruno** [dotnet/docs#9519]
The link to the list of the supported operating systems for .NET Core 1.1 in the ".NET Core supported operating systems" section results in a page not found.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff5c1c2a-7d86-703c-038e-062f5dcfc5b0
* Version Independent ID: cab4f67f-f338-8990-6454-853a0f01627e
* Content: [Prerequisites for .NET Core on Windows](https://docs.microsoft.com/en-us/dotnet/core/windows-prerequisites?tabs=netcore2x)
* Content Source: [docs/core/windows-prerequisites.md](https://github.com/dotnet/docs/blob/master/docs/core/windows-prerequisites.md)
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by PQMISSCMP** [comment]
r
