### ISSUE TITLE
Performance recommendations for .NET Core applications

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#9532]
Increased performance is a major part of the .NET Core story for developers.

We need to expand on that story in the .NET Core section of our docs. This should answer the following questions:

- What performance benefits are gained simply by migrating from .NET Framework to .NET Core?
- What techniques could produce further benefits?
- Of those, which (likely) have the best payback for common scenarios?
- How should customers measure the impact of adopting new .NET Core based performance techniques?

**Comment by BillWagner** [comment]
I shared this with internal folks, and here are thoughts for what content should be created. 

Performance guidance and raising visibility on the changes made are two pretty different topics. In some cases, they coincide like ValueTask<T>, Pipelines and IAsyncEnumerable<T>. These things should be in different sections not try to put them in the same doc.

> What performance benefits are gained simply by migrating from .NET Framework to .NET Core?

This comes down to fundamental improvements in core technology, places that we’ve removed overhead, made fundamental operations go faster, etc., the kinds of things I talked about in https://blogs.msdn.microsoft.com/dotnet/2017/06/07/performance-improvements-in-net-core/ and https://blogs.msdn.microsoft.com/dotnet/2018/04/18/performance-improvements-in-net-core-2-1/, and that Mukul highlighted for Bing in https://blogs.msdn.microsoft.com/dotnet/2018/08/20/bing-com-runs-on-net-core-2-1/.  That’s all about coreclr/corefx, but I agree with Wade that ASP.NET is a key factor there as well, and there are many significant improvements at the ASP.NET layer.

> What techniques could produce further benefits?

This comes down to mainly:

- Understanding ways to rearchitect an app to take advantage of the new platform.  This would be more at the ASP.NET layer, taking advantage of the recommended patterns for structuring one’s app to best adapt to the patterns ASP.NET optimizes for.
- Taking advantage of new features / overloads / etc. exposed in the new platform.  This is things like Span<T>, all of the UTF8-related work in .NET Core, additional overloads on things like ThreadPool to let you optimize further, etc.

> How should customers measure the impact of adopting new .NET Core based performance techniques?
Measure, measure, measure.  And ensure the right things are being measured.  What are the key metrics that drive success in the app, create benchmarks for those, and tune to those.

**Comment by brianrob** [comment]
Adding to the comment above - we should definitely have guidance on how to measure.  In the end, this is likely to be one of the most important pieces of performance guidance that we can provide.  I'm happy to work with you to get this done.
