### ISSUE TITLE
Main Procedure arguments

### ISSUE THREAD

**Issue by FerdaTanyeri** [dotnet/docs#9539]
With your example the arguments passed to the program can be trapped, but the program name itself cannot be determined. Example:

myProgram 1111 2222

The arguments "1111" and "2222" can be determined but not the program name "myProgram".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ed7d2c1-d322-86a6-d9be-1a5fce08e8b7
* Version Independent ID: cd994df4-a52a-4d81-edc5-972cf574e166
* Content: [Main Procedure in Visual Basic](https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/program-structure/main-procedure)
* Content Source: [docs/visual-basic/programming-guide/program-structure/main-procedure.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/programming-guide/program-structure/main-procedure.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by Thraka** [comment]
@FerdaTanyeri Hi!

You can use `System.Diagnostics.Process.GetCurrentProcess().ProcessName` to get the name of the program.

I'm closing this issue as it doesn't seem to be related to a problem with the article.

Thanks!
