### ISSUE TITLE
convertToStructTuple

### ISSUE THREAD

**Issue by decafbad** [dotnet/docs#9546]
I think "convert to and from struct tuple" examples should be other way around.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89bef555-3de1-5d81-c02b-2ac8c049423b
* Version Independent ID: eb13ad9e-2c95-979b-6d6e-13d29653c6ba
* Content: [Tour of F#](https://docs.microsoft.com/en-us/dotnet/fsharp/tour)
* Content Source: [docs/fsharp/tour.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/tour.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by cartermp** [comment]
@decafbad Can you clarify what you mean by "other way around"? Are the functions declared incorrectly, or do you feel their order could be improved?

**Comment by decafbad** [comment]
My bad. I saw them as values, not functions.  Still feels ambiguous.

**Comment by cartermp** [comment]
Closing as this has been answered
