### ISSUE TITLE
[discussion] Simplify article: How to validate email with regex

### ISSUE THREAD

**Issue by Thraka** [dotnet/docs#9547]
To do:

1. Simplify the regex, so that it's easier to read and parse.
2. Indicate that a regex for email is highly complicated and may never cover every possibility.
3. For security purposes and further validation, send a test email to the email address.

### Original issue content

>Related to the discussion on #5305 @pkulikov @weshaggard @dasMulli @BillWagner @mairaw @rpetrusha 

Hello! I wanted to just run the idea of deleting this article by you all. As we can see from the many issues opened on it, a lot of people want to have the regex tweaked to fit their specific needs. 

Reading through quite a few articles on this subject, it seems that the general consensus is to **not** use regex to validate every email type, but instead to just use a simple structural validator (contains @ and .) and to use a verification email to truly validate the email.

**Options**

1. Delete the article
2. Simplify the article
3. ??

#### Problems related to matching
- https://codereview.stackexchange.com/questions/77072/regex-to-match-email-address
- https://softwareengineering.stackexchange.com/questions/78353/how-far-should-one-take-e-mail-address-validation/78363#78363
- https://www.regular-expressions.info/email.html

#### Thoughts on why you shouldn't
- https://davidcel.is/posts/stop-validating-email-addresses-with-regex/
- https://hackernoon.com/the-100-correct-way-to-validate-email-addresses-7c4818f24643

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 202e3f9f-a12a-53de-9069-fd469e3dbebc
* Version Independent ID: fd3699bb-4881-b6b4-1275-43eed3d5f626
* Content: [How to: Verify that Strings Are in Valid Email Format](https://docs.microsoft.com/en-us/dotnet/standard/base-types/how-to-verify-that-strings-are-in-valid-email-format)
* Content Source: [docs/standard/base-types/how-to-verify-that-strings-are-in-valid-email-format.md](https://github.com/dotnet/docs/blob/master/docs/standard/base-types/how-to-verify-that-strings-are-in-valid-email-format.md)
* Service: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by BillWagner** [comment]
I'd agree with deleting it. The question is where to redirect traffic.

@scottaddie Is there an article that already exists on the ASP.NET site that talks about creating accounts and validating the destination email addresses?

**Comment by scottaddie** [comment]
@BillWagner The closest thing we have to that is https://docs.microsoft.com/aspnet/core/security/authentication/accconfirm.

**Comment by rpetrusha** [comment]
The basic regex actually does conform to an RFC. It's unfortunately the case, though, that when I wrote it, I neglected to document which RFC, and I've long ago forgotten.

My feeling is that we should keep the regex, but note its limitations -- that it doesn't validate every email address (and that a regex to validate all possible email addresses doesn't exist), and provide a few examples from customer requests for fixes to illustrate email addresses that won't validate.

**Comment by dasMulli** [comment]
I believe the previous discussion was more leaning towards finding a better example / use case for regex based validation. But so far, I don't think anyone has found a good one so far 😅.

**Comment by Thraka** [comment]
I feel like (based on the feedback and the searches coming in to the page) people  are visiting the page because they want to validate an email and want a solution. Therefor, they don't read the page really and probably just skim straight down to the code. 

Comparing it to the other example regex pages, none of them have any negative votes. This is the only one. And based on the feedback, it's because the email validation doesn't fit their need. It's not the "perfect" email validation they require. It can never be perfect.

Perhaps a first step would be to simplify the article and regex, note that it's not perfect and they must customize it to their needs, point to some other articles about regex email checking, and circle back on this in 3-4 months after we see if this change is effective? 

If it's not, then we can look at deleting it?

**Comment by rpetrusha** [comment]
The more we simplify the article and the regex, the less perfect it becomes. The only major simplification that I can think of is to remove support for punycode,, and I'm not really sure that it helps all that much, since the punycode portion of the validation is handled in a separate method.

I think that negative votes is likely to be the nature of the beast here. All of the how to regexes are intended to provide a solution; none are intended as tutorials. The basic problem is that the other regexes match an easily identifiable pattern, but this one can't and doesn't. Despite that, the topic still has a large number of page views and a relatively high CSAT.

Noting that the regex is not perfect is good, and that a regex cannot successfully validate all email addresses (or actually, if one could, it would be nearly incomprehensible and unmaintainable). Noting that it can be customized further, or welcoming contributors who want to customize it, is also good. But I'd tone the customization text down a bit, since customizing this regex is non-trivial, and we can't really expect that someone wants to customize their regex.

**Comment by mairaw** [comment]
There some interesting things to consider as well:
- The top keyword searches for the topics listed as related articles have nothing to do with how to validate email so I don't think they're fair comparisons.
- SkyRay shows 100% CSAT for this topic for the past month. How far are we looking back to consider deleting this one?
- If you look for C# valid email for example, this topic is the only article from docs that shows up on the first couple of pages

What if we just tweaked the title a bit to not indicate that our solution is complete?

**Comment by Thraka** [comment]
This was opened just due to when an issue gets opened on this article, it becomes extremely hard to address. The regex is so complex that it requires a lot of parsing, testing, and re-familiarizing oneself with regex.

For CSAT I always use 3 months. Of course, Dec is a hard month to include because of the nature of the holidays. I think I'm going to settle on this solution previously mentioned:

>Perhaps a first step would be to simplify the article and regex, note that it's not perfect and they must customize it to their needs, point to some other articles about regex email checking, and circle back on this in 3-4 months after we see if this change is effective?

**Comment by Thraka** [comment]
I don't think we came to a consensus on this. I'm going to close it for now and if something happens (such as a lot of issues being created) I'll reopen this.

**Comment by ea234** [comment]
https://github.com/ea234/FkEMailValidator
- No RegEx
- The Fasted (see TestClass)
- In German ... use Google-Translate

**Comment by ea234** [comment]
... the fastest (Sorry for the mistake. Maybe I should use Google-Translate too)

**Comment by mairaw** [comment]
Reopening this since we were discussing this again before the holidays.

**Comment by Thraka** [comment]
I think before the holiday's we left this at:

1. Simplify the regex, so that it's easier to read and parse.
2. Indicate that a regex for email is highly complicated and may never cover every possibility.
3. For security purposes and further validation, send a test email to the email address.

**Comment by Peled-Zohar** [comment]
I totally agree. Using a regular expression to validate the format of an email address means one of two things: Either your validation is incorrect, or your regular expression is so big and messy you'll have to spend a couple of hours just to understand what it is suppose to do. [There's an easier way](https://zoharpeled.wordpress.com/2019/11/26/validate-mail-address-format-the-easy-way/).

**Comment by Thraka** [comment]
@Peled-Zohar Thanks. I think that using the `MailAddress` class is a great idea of an alternative. I think a simple regex and then a wrapper around this class would simplify this article and make it easy to understand and use.

**Comment by Peled-Zohar** [comment]
@Thraka  Since the MailAddress constructor validates the format for you, there really is no need for a regular expression at all - unless you have a performance-sensitive use case where a simple regex can save you from a lot of exception catching.

**Comment by Thraka** [comment]
The article is about how to use RegEx to validate an email. So it's either delete it or simplify it. 😄 However, RegEx email validation **is** something commonly searched for. So someone may find it useful. I think pointing out (1) simpler things to do, such as `MailAddress` and (2) having a simple regex, would improve the value of the article.

**Comment by rpetrusha** [comment]
`MailAddress` is not a good alternative, @Thraka; see [#6620](https://github.com/dotnet/docs/issues/6620). Is this guidance still accurate, @davidsh?

**Comment by Thraka** [comment]
Hi @rpetrusha !! 😄 The wrapper code for using `MailAddress` (to handle the exception and return true/false) could implement that logic to search for a space character.

**Comment by Peled-Zohar** [comment]
@rpetrusha Thanks, I wasn't aware of that issue. still, I think it might be a better alternative than using a long, cumbersome, unreadable and unmaintainable regular expression, especially combined with @Thraka's idea of adding the logic to handle the space char.
