### ISSUE TITLE
Microsoft.ML.Legacy.Transforms.ColumnDropper xref not working

### ISSUE THREAD

**Issue by nschonni** [dotnet/docs#9552]
Noticed this on a [build as well](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C12%5C11%5Ca3bda507-3390-de91-8f7f-26f90f4e5fc8%5CPullRequest%5C201812112041471469-9550%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=gKLRgObJpwTf%2BsouB2cThO5SesZU%2Bd%2FGS%2B%2BVglmy37E%3D&st=2018-12-11T20%3A41%3A37Z&se=2019-01-11T20%3A46%3A37Z&sp=r) but the page is also rendering it as a raw `&lt;xref:Microsoft.ML.Legacy.Transforms.ColumnDropper&gt;`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4185570-21cc-dcdb-62fd-d05bceb62f81
* Version Independent ID: 4f0fe52a-a771-d044-593d-2bb65df15e0d
* Content: [Data transforms in ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/resources/transforms#feedback)
* Content Source: [docs/machine-learning/resources/transforms.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/resources/transforms.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by JRAlexander** [comment]
Thanks @nschonni! This has been fixed in https://github.com/dotnet/docs/pull/9371.
