### ISSUE TITLE
Restore configuration elements lost in migration

### ISSUE THREAD

**Issue by rpetrusha** [dotnet/docs#9554]
## Restore configuration elements lost in migration

In an old migration from DxStudio to CAPS, our previous authoring system, a number of configuration elements were dropped from the documentation. 

The following is the list of 82 instances of "the  configuration element", which, since two spaces separate "the" and "configuration", implies that the intervening text has been dropped:

[config-element-dropout.txt](https://github.com/dotnet/docs/files/2669570/config-element-dropout.txt)

**Comment by msschl** [comment]
I fixed all issues.

PR dotnet/dotnet-api-docs#1516
