### ISSUE TITLE
XML documentation generated from docs should not contain docs-relative URLs

### ISSUE THREAD

**Issue by Powerhelmsman** [dotnet/docs#9555]
This issue was created by @svick from https://github.com/MicrosoftDocs/feedback/issues/659

Describe the bug
When looking at the XML documentation for an API that seems to have been generated from .Net API reference, such as netstandard.xml, I can see docs-relative URLs such as `~/docs/standard/base-types/regular-expression-options.md`, while I think it should point to the live URL for the article: https://docs.microsoft.com/dotnet/standard/base-types/regular-expression-options.
Specifically, netstandard.xml (from version 2.0.3 of the NETStandard.Library package) contains (reformatted):
&lt;member name="F:System.Text.RegularExpressions.RegexOptions.Singleline"&gt;
  &lt;summary&gt;
    Specifies single-line mode. Changes the meaning of the dot (.) so it matches every
    character (instead of every character except \n). For more information, see the
    &quot;Single-line Mode&quot; section in the
    &lt;see cref="~/docs/standard/base-types/regular-expression-options.md"&gt;
      Regular Expression Options&lt;/see&gt; topic.&lt;/summary&gt;
  &lt;returns&gt;&lt;/returns&gt;
&lt;/member&gt;
Notice how the &lt;see cref&gt; contains a URL that does not make sense outside of the docs repo.
This content seems to come from this line in dotnet/dotnet-api-docs.
Expected behavior
XML documentation contains links to live versions of linked articles.
Note that while there doesn't seem to be spec-approved way provide HTTP links in XML documentation, ReSharper/Rider seems to accept &lt;a href&gt;, and there is a proposal to adopt &lt;see href&gt;: dotnet/csharplang#1764, which is also used by Sandcastle.
Screenshots
This is how the XML documentation is currently presented in Rider, where the link is not very useful:

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf9b6611-d08f-2fe9-216b-e0658d7f1553
* Version Independent ID: 3d3be892-b9b5-ca0b-1193-9fa49716decb
* Content: [Regular Expression Options](https://docs.microsoft.com/en-us/dotnet/standard/base-types/regular-expression-options)
* Content Source: [docs/standard/base-types/regular-expression-options.md](https://github.com/dotnet/docs/blob/master/docs/standard/base-types/regular-expression-options.md)
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by mairaw** [comment]
I've checked what's being produced by our latest IntelliSense builds and the link is no longer there (this has been the behavior of how we render links on IntelliSense):
    <member name="F:System.Text.RegularExpressions.RegexOptions.Singleline">
      <summary>Specifies single-line mode. Changes the meaning of the dot (.) so it matches every character (instead of every character except \n). For more information, see the "Single-line Mode" section in the Regular Expression Options topic.</summary>
    </member>

We'd now need to update the .NET Standard package with the latest version of our IntelliSense files.
@ahsonkhan @safern can you guys help with this?
