### ISSUE TITLE
Code example

### ISSUE THREAD

**Issue by najeeb-np** [dotnet/docs#9561]
Where can I get this 'DKSample' used in the example to work out with a real example?
( xmlns:c="clr-namespace:SDKSample")

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87567591-0d1a-a791-a609-fa7a3986d43c
* Version Independent ID: 29542eb2-683e-0217-71aa-14671a6f193a
* Content: [Data Binding Overview](https://docs.microsoft.com/en-us/dotnet/framework/wpf/data/data-binding-overview)
* Content Source: [docs/framework/wpf/data/data-binding-overview.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/data/data-binding-overview.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by Thraka** [comment]
@najeeb-kazmi Sorry for the late reply. This is linked to near the top of the article. The link points to https://github.com/microsoft/WPF-Samples/tree/master/Sample%20Applications/DataBindingDemo
