### ISSUE TITLE
mutable fields in Structs are not described

### ISSUE THREAD

**Issue by Szer** [dotnet/docs#9563]
Documentation lacks examples of
`val mutable` fields and way of their mutation without implicit copying of structure.

```fsharp
[<Struct>]
type Foo = 
  val mutable bar: string
  member self.ChangeBar bar = self.bar <- bar
  new (bar) = {bar = bar}

let foo = Foo "1"
foo.ChangeBar "2" //make implicit copy of Foo, changes the copy, discards the copy, foo remains unchanged
printfn "%s" foo.bar //prints 1

let mutable foo' = Foo "1"
foo'.ChangeBar "2" //changes foo'
printfn "%s" foo'.bar //prints 2
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a067d5a-bb13-9991-c808-c7c49a00ca47
* Version Independent ID: 201272a0-3350-93f3-8965-4a745671c7e7
* Content: [Structures (F#)](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/structures)
* Content Source: [docs/fsharp/language-reference/structures.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/language-reference/structures.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by cartermp** [comment]
Mutable fields in structs are described here: https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/members/explicit-fields-the-val-keyword

However, gotchas around implicit copies (such as your example) are not documented. Would you be willing to submit a PR to the structures file that explains this? I can put it on my backlog but there's no guarantee it'll be done soon.

**Comment by Szer** [comment]
@cartermp 
PR for docs
https://github.com/dotnet/docs/pull/9695
PR for snippets
https://github.com/dotnet/samples/pull/531

**Comment by cartermp** [comment]
Thanks a bunch @Szer
