### ISSUE TITLE
Turn off Fusion Logging

### ISSUE THREAD

**Issue by JosephRufft** [dotnet/docs#9565]
I have looked at this and I still have no idea how to turn of fusion logging.  Can you help me?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56e11373-7bdd-6c40-519b-0e2e28739acb
* Version Independent ID: 418d1a82-2131-88d4-f087-8cf57ca69434
* Content: [Fuslogvw.exe (Assembly Binding Log Viewer)](https://docs.microsoft.com/en-us/dotnet/framework/tools/fuslogvw-exe-assembly-binding-log-viewer)
* Content Source: [docs/framework/tools/fuslogvw-exe-assembly-binding-log-viewer.md](https://github.com/dotnet/docs/blob/master/docs/framework/tools/fuslogvw-exe-assembly-binding-log-viewer.md)
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by mikkelbu** [comment]
The page states
```
...
You can use the Log Settings dialog to perform the following actions.

To disable logging
Select the Log disabled option button.
...
```

**Comment by chucklu** [comment]
@mikkelbu  It did not work, I already choose log disabled option. However, it still keeps write log.
![image](https://user-images.githubusercontent.com/3004057/64758453-3770d500-d567-11e9-8c69-cc8bfa61ec7b.png)

**Comment by tdykstra** [comment]
@wtgodbe do you know who can help with this?

**Comment by wtgodbe** [comment]
I'm not sure, I haven't been able to determine who owns this tool...

**Comment by tdykstra** [comment]
@mairaw Any other ideas who we can ask about this tool?
