### ISSUE TITLE
Possibly ambiguous usage of `break` in C# `switch` statement

### ISSUE THREAD

**Issue by ryanwebjackson** [dotnet/docs#9566]
I know this might be a "gotcha", but within the context of a switch statement inside of a loop, to a human, it can be confusing what "break" is referring to.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4b4ba4c-b602-9335-97d1-3b8ac23e6cb3
* Version Independent ID: c53ac7c0-56f8-06cb-0f06-fdfc389358bd
* Content: [break statement - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/break)
* Content Source: [docs/csharp/language-reference/keywords/break.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/break.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@ryanwebjackson You are correct.

Is there more information that you need for this than what is available in the 2nd sample? That `break` breaks out of the inner loop, but not the outer loop.

**Comment by ryanwebjackson** [comment]
I was referring to a _switch_ statement inside of a loop, so an example of that would be perfect. Two loops can make it easier to tell what's going on, because you need curly brackets for both (if they're more than one line of code). I don't have access to the code I was looking at when I opened this, but because there can be both breaks (switch and loop) in the same code block -- it can be confusing.

**Comment by BillWagner** [comment]
The right fix is to make the following changes:

- [ ] Move the `switch` example before the nested loop example.
- [ ] Add text introducing the last (nested loop) example stating that 'break` exits the current branch or loop statement. Reinforce it by stating that this means only one level.
- [ ] add a final example with a lop and an embedded switch statement.

**Comment by davidlfox** [comment]
@BillWagner When adding a new snippet to the dotnet/samples repository, should this issue be referenced in commit message, then a PR submitted to samples, _then_ a PR submitted to dotnet/docs repository for this issue?

**Comment by mairaw** [comment]
Either in the commit message or in the PR description is enough. You can then create the docs PR right after, just call out that is dependent on the samples PR you created and we'll make sure to review after the samples PR is merged.
