### ISSUE TITLE
Paveover

### ISSUE THREAD

**Issue by Mandated** [dotnet/docs#9567]
What is the meaning of &lt;paveover&gt;?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5910cd5b-4251-9302-7ff9-65d2de94886d
* Version Independent ID: 130e32f0-e5d7-df10-1df9-596416f1e16e
* Content: [Inside a C# Program](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/inside-a-program/index)
* Content Source: [docs/csharp/programming-guide/inside-a-program/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/inside-a-program/index.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
That's an error in our documentation @Mandated. We should probably just change that link to go to https://docs.microsoft.com/en-us/dotnet/samples-and-tutorials/ now.
