### ISSUE TITLE
This API is now obsolete.

### ISSUE THREAD

**Issue by grahamehorner** [dotnet/docs#9585]
IMHO when the API is marked as obsolete, it would be good to reference what replaces this feature; or an example of how to achieve some this similar; allowing existing developers that improve code base and new developers that have examples/reading materials that reference older APIs to update code and learn at the same time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f33892c7-968e-fefd-b0d9-7040f5ef3211
* Version Independent ID: 71eb5a54-c34c-781a-7c4f-9f1871a71efd
* Content: [ColumnCopier Class (Microsoft.ML.Legacy.Transforms)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.legacy.transforms.columncopier?view=ml-dotnet)
* Content Source: [dotnet/xml/Microsoft.ML.Legacy.Transforms/ColumnCopier.xml](https://github.com/dotnet/ml-api-docs/blob/live/dotnet/xml/Microsoft.ML.Legacy.Transforms/ColumnCopier.xml)
* Product: **dotnet-ml-api**
* GitHub Login: @sfilipi
* Microsoft Alias: **johalex**

**Comment by mairaw** [comment]
@natke who can take a look at this feedback?
