### ISSUE TITLE
.NET Core 2.2 on Ubuntu 18.04

### ISSUE THREAD

**Issue by evermeire** [dotnet/docs#9587]
$ sudo apt-get install dotnet-sdk-2.2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package dotnet-sdk-2.2
E: Couldn't find any package by glob 'dotnet-sdk-2.2'
E: Couldn't find any package by regex 'dotnet-sdk-2.2'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff5c1c2a-7d86-703c-038e-062f5dcfc5b0
* Version Independent ID: cab4f67f-f338-8990-6454-853a0f01627e
* Content: [Prerequisites for .NET Core on Windows](https://docs.microsoft.com/en-us/dotnet/core/windows-prerequisites?tabs=netcore2x)
* Content Source: [docs/core/windows-prerequisites.md](https://github.com/dotnet/docs/blob/master/docs/core/windows-prerequisites.md)
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
@leecow @vivmishra can you take a look at this issue? Where should we move this too?

**Comment by leecow** [comment]
Just tested fine with a clean 18.04 Docker image. 

@evermeire - The repo registration information will be hiding in /etc/apt/sources.list.d. If you performed the repo registration steps detailed at https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-04/sdk-current then you should find a microsoft-prod.list file that has a single line: `deb [arch=amd64] https://packages.microsoft.com/ubuntu/18.04/prod bionic main`.

**Comment by evermeire** [comment]
In the /etc/apt/sources.list.d I had the following two files:
- microsoft-prod.list.distUpgrade 
- microsoft-prod.list.save

The both contain the line:
deb [arch=amd64] https://packages.microsoft.com/ubuntu/18.04/prod bionic main

I created a third file with the following:
sudo cp microsoft-prod.list.save microsoft-prod.list

Still the same issue when attempting to install 2.2.

I had a co-worker who is running Ubuntu 18.04 after upgrading from Ubuntu 16.10 and he has no problems installing.  I have another co-worker who installed 18.04 clean a few months ago and has the same issue I have.

**Comment by radu99999** [comment]
My machine runs Ubuntu 18.04 and I cannot  install .net core SDK 2.2. It is only 2.1 which is available. I followed https://dotnet.microsoft.com/download/linux-package-manager/rhel/sdk-2.2.101 and I've selected Ubuntu 18.04.

**Comment by mairaw** [comment]
@leecow @richlander should I move this issue to https://github.com/dotnet/core/?

**Comment by Thraka** [comment]
This is issue is stale. I'm going to close it unless there is still a problem.
