### ISSUE TITLE
do not use CAS

### ISSUE THREAD

**Issue by madamakis** [dotnet/docs#9589]
Is there something wrong with CAS. A 2017 Microsoft article is all about using CAS. I'm confused.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f89dddf-e9b5-b7c6-9ecc-a67b94f4412a
* Version Independent ID: d44fe46d-fce9-c72e-d035-a0c9c7f09353
* Content: [Secure coding guidelines for .NET](https://docs.microsoft.com/en-us/dotnet/standard/security/secure-coding-guidelines)
* Content Source: [docs/standard/security/secure-coding-guidelines.md](https://github.com/dotnet/docs/blob/master/docs/standard/security/secure-coding-guidelines.md)
* Product: **dotnet**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
@madamakis if you're talking about topics such as https://docs.microsoft.com/en-us/dotnet/framework/misc/code-access-security, they have been updated recently to have that big red warning about the dangers of using CAS. So the guidance about not using CAS for enforcement of varying levels of trust is correct in this topic. For this reason, I'm closing this issue. But please let me know if there's something I missed.
