### ISSUE TITLE
Calling a Dynamic Language Library

### ISSUE THREAD

**Issue by regal60740** [dotnet/docs#9595]
First thing I had to do was to set the DynamicIronPythonSample project to the start up project. Next, I had to change the file path to @"\IronPython 2.7\Lib". The last step I had to perform was to copy the IronPython 2.7 folder from programs folder to programs (x86) folder because the error I received in the console showed me the program was looking in that folder and could not find the file. Once I made these changes, it worked fine. You may want to add these details to your Walkthrough. Otherwise people will be running the wrong project.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f63fb701-91e9-5723-add6-33d2288431a3
* Version Independent ID: e9d33444-b5f7-96d4-9c33-dd29913349d5
* Content: [Walkthrough: Creating and Using Dynamic Objects (C# and Visual Basic)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/types/walkthrough-creating-and-using-dynamic-objects)
* Content Source: [docs/csharp/programming-guide/types/walkthrough-creating-and-using-dynamic-objects.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/types/walkthrough-creating-and-using-dynamic-objects.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for taking such careful notes on the changes you needed to make to complete this walkthrough.

I've added this to our backlog to address when we update this document.

**Comment by lnjuanj** [comment]
Would it be possible to rather migrate the walkthrough to another one? Ironpython was discontinued some time ago, so it's not compelling to get and install the library...
