### ISSUE TITLE
Is there a similar version of this for adding .dll? or nuget package?

### ISSUE THREAD

**Issue by hoksource** [dotnet/docs#9601]
I like to distribute a project without the source code, for simplicity. Is there a dotnet add reference my.dll
or dotnet add package my.nupkg?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76ab77c3-eba6-e947-8ffa-0fcda722f34b
* Version Independent ID: 48bbcb58-cfd1-b3d3-7a2a-319716541362
* Content: [dotnet-add reference command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-add-reference)
* Content Source: [docs/core/tools/dotnet-add-reference.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-add-reference.md)
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Sorry I've missed your question earlier @hoksource. 

There's the dotnet add package where you can specify the package source:
https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-add-package

I hope this helps.

**Comment by hoksource** [comment]
Turns out you need azure devops artifact feeds or some other package hosting to do this. thank you for the prompt response.

**Comment by hoksource** [comment]
any updates on this? is there a way to link a 3rd party dll to a .net core or .net framework project?
