### ISSUE TITLE
How to use RDLC in .Net core 2.0 .

### ISSUE THREAD

**Issue by pappukr** [dotnet/docs#9607]
How to use RDLC in .Net core 2.0 to export report.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d49bc05d-7c8e-5f89-aac5-d133225da4d5
* Version Independent ID: 2f831fc9-dfe6-15db-4ec6-00f59c2dacc2
* Content: [.NET Core Guide](https://docs.microsoft.com/en-us/dotnet/core/#support)
* Content Source: [docs/core/index.md](https://github.com/dotnet/docs/blob/master/docs/core/index.md)
* Product: **dotnet-core**
* GitHub Login: @richlander
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
I don’t think RDLC is supported on .NET Core but you can follow the discussion about this at https://github.com/aspnet/AspNetCore/issues/1528. Since this is more of a product question, I’ll be closing this issue.
