### ISSUE TITLE
Using the Inherited Control on a Form

### ISSUE THREAD

**Issue by regal60740** [dotnet/docs#9608]
Everything worked fine until I got to this step. The trouble began when I got to this particular step: In the Toolbox, expand the ctlClockLib Components node. Well, when I did step 2: Add a new Windows Application project to the solution, and name it Test., I did a search in VS 2017 for Windows Application and at the top of the list was WPF App so I added this project. When I tried to expand the ctlClockLib Components node, it was not listed. I only found it in the toolbox for the ctlClockLib project. When I did steps 6 through 11, they were not added to the WPF designer, they were added to ctlAlarmClock designer. I had a feeling this was wrong, but that was the only way ctlClockLib Components node was available to me. When I tried to get rid of the WPF project by removing it, I was getting errors trying to build the remaining project. How frustrating. I could not even get sample code for the original project to go back and add a different Windows Application. So I've spent a lot of time on this and now its broken. I wish you would tell us which Windows Application to use so we can repeat your outcome.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b349e6ca-f245-701b-af46-4fa5ffd9930e
* Version Independent ID: cf286845-9573-a739-4e4b-cfd25fa179b1
* Content: [Walkthrough: Authoring a Composite Control with Visual C#](https://docs.microsoft.com/en-us/dotnet/framework/winforms/controls/walkthrough-authoring-a-composite-control-with-visual-csharp)
* Content Source: [docs/framework/winforms/controls/walkthrough-authoring-a-composite-control-with-visual-csharp.md](https://github.com/dotnet/docs/blob/master/docs/framework/winforms/controls/walkthrough-authoring-a-composite-control-with-visual-csharp.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by regal60740** [comment]
I finally got it working. I used a Windows Form Application and fixed some code problems and it now works.

**Comment by tdykstra** [comment]
@regal60740 Thanks for letting us know you resolved the problem.  I'll leave this issue open as a reminder that we should change the instruction text from "Windows Application" to "Windows Forms Application".
