### ISSUE TITLE
What about the client side? 

### ISSUE THREAD

**Issue by mattias-m-andersson** [dotnet/docs#9610]
How is authentication used from HttpClient?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbf15d8f-56c9-61ea-9801-2d4049400f4a
* Version Independent ID: 390671d2-7d1b-48c8-bad4-b967559706af
* Content: [Understanding HTTP Authentication](https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/understanding-http-authentication)
* Content Source: [docs/framework/wcf/feature-details/understanding-http-authentication.md](https://github.com/dotnet/docs/blob/master/docs/framework/wcf/feature-details/understanding-http-authentication.md)
* Product: **dotnet-framework**
* GitHub Login: @Lxiamail
* Microsoft Alias: **wcfsrvt**

**Comment by Thraka** [comment]
Please look up how to do that on a developer forum such as stackoverflow. I'm closing this issue as your question is too broad for this article. Thanks!
