### ISSUE TITLE
What does it mean?

### ISSUE THREAD

**Issue by jasonxz** [dotnet/docs#9613]
It would be really nice if there were an explanation of how one might interpret the results of this method.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 853fc221-061c-6388-afd2-7d8b7a9b31d8
* Version Independent ID: 757fd3a3-1621-19ee-abd5-994968986b35
* Content: [LinearPredictor.GetFeatureWeights(VBuffer&lt;Single&gt;) Method (Microsoft.ML.Runtime.Learners)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.runtime.learners.linearpredictor.getfeatureweights?view=ml-dotnet)
* Content Source: [dotnet/xml/Microsoft.ML.Runtime.Learners/LinearPredictor.xml](https://github.com/dotnet/ml-api-docs/blob/live/dotnet/xml/Microsoft.ML.Runtime.Learners/LinearPredictor.xml)
* Product: **dotnet-ml-api**
* GitHub Login: @sfilipi
* Microsoft Alias: **johalex**

**Comment by mairaw** [comment]
This page no longer exists. Closing.
