### ISSUE TITLE
System.Linq.Enumerable+WhereSelectEnumerableIterator instead of IEnumerable<>

### ISSUE THREAD

**Issue by nlivaic** [dotnet/docs#9625]
**Issue description**

In example "Compound from clauses", code section labeled as "// Rest the mouse pointer on scoreQuery in the following line to " - the type is different then it is claimed in the article. For me, it shows:

> System.Linq.Enumerable+WhereSelectEnumerableIterator`2[<>f__AnonymousType2`2[MyProject.Student,System.Int32],<>f__AnonymousType3`2[System.String,System.Int32]]

**Target framework**

- .NET Core

**Code editor**

- Visual Studio Code

<details>
<summary><strong>dotnet --info output</strong></summary>

```console
dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.500
 Commit:    b68b931422

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.500\

Host (useful for support):
  Version: 2.1.6
  Commit:  3f4f8eebd8

.NET Core SDKs installed:
  2.1.500 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```
</details>

edit by @mairaw: added topic info

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 937bf577-34fe-4fed-57d0-8d91672945d8
* Version Independent ID: 23268adb-ff34-08cc-baa9-0ea1bfdf05ce
* Content: [from clause - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/from-clause)
* Content Source: [docs/csharp/language-reference/keywords/from-clause.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/from-clause.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for writing this @nlivaic The answer is a bit complicated. The `WhereSelectEnumerableIterator` does expose the same functionality as an `IEnumerable`. For practical purposes, thinking of the output from most LINQ queries in terms of an `IEnumerable` is the correct abstraction. In practice, different LINQ operators create different types. 

I need to figure out how to update this to be both correct and useful.
