### ISSUE TITLE
Typical Microsoft Rubbish

### ISSUE THREAD

**Issue by sackbut** [dotnet/docs#9628]
What the Walk Through says and what VS17 show on the screen bear no relation to each other. It may not matter - but beginners need 1:1 correspondence until they are more familiar with what is happening.

Have abandoned the MS walkthroughs. Will find some other tuition on the internet

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0dc39f7-b153-a46c-3b88-07c8ed2c71bc
* Version Independent ID: 78a14535-9703-e2af-4451-783a7c4c10be
* Content: [Create a WPF application in Visual Studio](https://docs.microsoft.com/en-us/dotnet/framework/wpf/getting-started/walkthrough-my-first-wpf-desktop-application)
* Content Source: [docs/framework/wpf/getting-started/walkthrough-my-first-wpf-desktop-application.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/getting-started/walkthrough-my-first-wpf-desktop-application.md)
* Product: **dotnet-framework**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by asloppyone** [comment]
well, You may have mistaken UWP as WPF ,thus making it impossible to draw any correspondence.

**Comment by sackbut** [comment]
I have no idea what you are talking about. I'm a beginner, Am I supposed to know what UWP and WPF mean ? Too many TLAs !
KT

**Comment by branstoncrumble** [comment]
I had the same problem until I started using VS2019 instead. I didn't know what UWP and WPF mean until I googled it. I have googled many terms whilst learning .NET. Google is your friend (sorry Microsoft)

**Comment by Potapy4** [comment]
@mairaw I think we can close it

**Comment by mairaw** [comment]
Thanks @Potapy4. We state on the prereqs that we're using VS 2019 in the article. Maybe we could enhance this by saying you need VS 2019 actually since the UI changed so much to create a new project. But after the first steps, the tutorial should work for both VS 2017 and 2019. I'll need to think on what to do here.
