### ISSUE TITLE
C# Guide: Basic Types

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#963]
This issue tracks the Basic Types content: https://github.com/dotnet/core-docs/csharp/basic-types.md

This should discuss how you work with the core built-in types in C#: numerics, strings, and System.Object.

There is existing content in MSDN, but it is in several places in the C# Programming Guide: https://msdn.microsoft.com/en-us/library/67ef8sbd.aspx

**Comment by IEvangelist** [comment]
Per @BillWagner - we believe this is already resolved... thanks to @pkulikov
