### ISSUE TITLE
c# expression body constructor with multiple assignment expressions

### ISSUE THREAD

**Issue by JohnMarsing** [dotnet/docs#9630]
For constructors, how would you do make multiple assignment expressions like for example a logger.

in the constructor example above you have this

private string locationName;

but what if you have this as well?

private readonly ILogger log;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 874ea00d-6ec4-55f4-f0e3-e818d21454c7
* Version Independent ID: 98072328-af31-5bc6-9ba4-1353328d5f10
* Content: [Expression-bodied members - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/statements-expressions-operators/expression-bodied-members#constructors)
* Content Source: [docs/csharp/programming-guide/statements-expressions-operators/expression-bodied-members.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/statements-expressions-operators/expression-bodied-members.md)
* Product: **dotnet-csharp**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by imba-tjd** [comment]
You can use a normal approach, that is `{ }`
```c#
class A
{
    private string locationName;
    private readonly ILogger log;

    public Location(string name, ILogger log)
    {
        locationName = name;
        this.log = log;
    }
}
```

**Comment by BillWagner** [comment]
You can also use tuples + expression bodied members, as follows:

```c#
class A
{
    private string locationName;
    private readonly ILogger log;

    public Location(string name, ILogger log) => 
      (locationName, this.log) = (name, log);
}
```

There is an example in the [tuples article](https://docs.microsoft.com/dotnet/csharp/tuples#deconstruction).

Closing this as an answered question.
