### ISSUE TITLE
Anomaly detection sample (timeseries?)

### ISSUE THREAD

**Issue by meraydin** [dotnet/docs#9633]
It would be great if you provide a sample regarding the following scenario: Suppose we have a text file containing information regarding when a user logged on to his/her machine. The file has the following columns:
* EventTime (datetime)
* UserId (string)
* MachineName (string)
* IpAddress (string)

SCENARIO:

"John" logs on to his machine regularly at 08:00am-08:30, from his personal laptop (John-PC), and from 127.0.0.1. However, one day log says, "John logged on to his machine from 10.1.2.3, at 03:00am." As a security analyst, one can say this is an anomaly (time is way too early and 10.1.2.3 is not his regular IP address) and investigate further. Or at least inform John for a possible security issue.

I'd like to see a sample about how to detect such an anomaly. Or at least the methods / algorithms to be used to detect such incidents. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd15175c-5b7d-4310-ecf5-32ffc7bc588b
* Version Independent ID: 38adc676-934e-0ff9-c868-527f075c96df
* Content: [Machine learning tasks - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/resources/tasks)
* Content Source: [docs/machine-learning/resources/tasks.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/resources/tasks.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by JRAlexander** [comment]
An anomaly detection sample is coming soon [here](https://github.com/dotnet/machinelearning-samples) with a tutorial or how-to to follow after that in docs. Thanks!

**Comment by JRAlexander** [comment]
Closing as I believe this is now resolved. Please reopen if needed.  Thanks!

**Comment by woanware** [comment]
I wouldn't say that this issue should be closed. The OP asked for a multi data outlier detection sample e.g. three items (timestamp, username, IP/hostname). All of the current samples use a single data item such as credit card outlier (Amount), power usage (Power Amount)

**Comment by meraydin** [comment]
I aggree 200%

**Comment by meraydin** [comment]
Why is someone not responding to this request? if this [ML.NET] is not capable of detecting that scenario, tell it.

**Comment by ygoe** [comment]
According to what I've found on the web today, ML.NET does not support anomaly detection over multiple values/dimensions. It can only handle single stupid numbers, nothing too realistic. I have 4096 float values in each set and need to determine whether a new set of 4096 values matches what's been there before (during the training period).

**Comment by meraydin** [comment]
Thanks Yves - though I am not surprised to hear this :(

Time to look for something more mature...


Murat Eraydın
Genel Müdür

Sent via the Samsung Galaxy S20



-------- Orijinal mesaj --------
Kimden: Yves Goergen <notifications@github.com>
Tarih: 16.09.2020 18:55 (GMT+03:00)
Alıcı: dotnet/docs <docs@noreply.github.com>
Cc: Murat Eraydın <murat.eraydin@karmasis.com>, Author <author@noreply.github.com>
Konu: Re: [dotnet/docs] Anomaly detection sample (timeseries?) (#9633)


According to what I've found on the web today, ML.NET does not support anomaly detection over multiple values/dimensions. It can only handle single stupid numbers, nothing too realistic. I have 4096 float values in each set and need to determine whether a new set of 4096 values matches what's been there before (during the training period).
