### ISSUE TITLE
we always need simple examples

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#9634]
@SKSON commented on [Sun Dec 16 2018](https://github.com/dotnet/docs.ko-kr/issues/86)

there are only partial explanation, or too complicated full example..?
we need simple example, which we can understand easy.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 925c8fe9-ba0b-bd2c-cea0-9d851ece8825
* Version Independent ID: 41cafff5-6418-2e54-3a0d-ee29fb1fca1f
* Content: [ML.NET을 사용하여 아이리스 꽃 클러스터(클러스터링)](https://docs.microsoft.com/ko-kr/dotnet/machine-learning/tutorials/iris-clustering)
* Content Source: [docs/machine-learning/tutorials/iris-clustering.md](https://github.com/dotnet/docs.ko-kr/blob/live/docs/machine-learning/tutorials/iris-clustering.md)
* Product: **dotnet-ml**
* GitHub Login: @pkulikov
* Microsoft Alias: **johalex**

**Comment by CeciAc** [comment]
Hi team, 
I'm moving this here since the reported issue is on the source documentation

Kind regards,
Microsoft DOCS International Team

**Comment by JRAlexander** [comment]
Thank you for the feedback. I hope the added examples help! Closing as I believe this is now resolved.
