### ISSUE TITLE
Command failed - docker exec aspnetcore_sample ipconfig

### ISSUE THREAD

**Issue by zoehart** [dotnet/docs#9635]
I could not get this sample to work. I cloned the sample app and ran it locally. And I was able to build it and run it in Docker for Windows. docker ps shows that it's running, but the command to determine the container's IP address fails. When I run 'docker exec aspnetcore_sample ipconfig' I get 'OCI runtime exec failed: exec failed: container_linux.go:348: starting container process caused "exec: \"ipconfig\": executable file not found in $PATH": unknown'. I ran 'docker container inspect container aspnetcore_sample', the output of which includes an IP address, but when I browse to that IP address in my browser I get no response. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9731aae1-505b-abb1-0d4b-d6a83ec735e1
* Version Independent ID: 760790d5-0e81-ea6c-19ea-f226d08ddf1f
* Content: [Docker images overview - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/docker/building-net-docker-images)
* Content Source: [docs/core/docker/building-net-docker-images.md](https://github.com/dotnet/docs/blob/master/docs/core/docker/building-net-docker-images.md)
* Product: **dotnet-core**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by jamieomaguire** [comment]
zoehart, if you are using a Linux container (even on a Windows machine with Docker for Windows) then I don't think you need to/can run the ipconfig command. That tutorial step is part of running the app in a Windows container. Apologies if I'm mistaken!

**Comment by zoehart** [comment]
Yes, I think that the root of my problem was that I _thought_ Docker for Windows had created a Windows container, not a Linux container. When I installed Docker for Windows, I checked an option that said something like "Use Windows containers instead of Linux containers". Based on that, I thought/assumed that my containers would be Windows containers. I ended up going into settings and changing it over to use Windows containers and all worked well after that. Maybe the install option I checked isn't working... or didn't mean what I thought it meant?

**Comment by tdykstra** [comment]
@zoehart It looks like the question you raised was answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.

**Comment by sudhir7795** [comment]
Hi @zoehart ,
I am also getting the same error:
OCI runtime exec failed: exec failed: container_linux.go:348: starting container process caused "exec: "ipconfig": executable file not found in $PATH": unknown

**Could you please help me how you would have fixed this issue?**

Thanks
Sudhir
