### ISSUE TITLE
File.FileOptions.Asynchronous purpose ?

### ISSUE THREAD

**Issue by DickBaker** [dotnet/docs#9636]
The File.Create etc docs show some method signatures requiring FileOptions although the examples here make no such demands. So what is optional/mandatory significance of this flag setting, and what disaster would befall if it was not specified when you then invoke those async stream method calls ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90c1b292-9f8a-d512-e780-24cb865a2da2
* Version Independent ID: 731858ee-ae76-9477-2ddf-40277bf1bd71
* Content: [Asynchronous File I/O](https://docs.microsoft.com/en-us/dotnet/standard/io/asynchronous-file-i-o)
* Content Source: [docs/standard/io/asynchronous-file-i-o.md](https://github.com/dotnet/docs/blob/master/docs/standard/io/asynchronous-file-i-o.md)
* Product: **dotnet**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
The example is using the overload that accepts only a string parameter:
https://docs.microsoft.com/en-us/dotnet/api/system.io.file.create?view=netframework-4.7.2#System_IO_File_Create_System_String_

The remarks of that overload explain what's the behavior for that particular API.

I hope that helps clarify things.

**Comment by imba-tjd** [comment]
@You may want to read this: https://stackoverflow.com/questions/13299705/fileoptions-asynchronous-causes-filestream-beginread-to-block

**Comment by DickBaker** [comment]
Thanks for that link. I will need to read thoroughly and probably review the source code too (now it is all OSS)

 

Dick
