### ISSUE TITLE
Reverse Package Search is outdated

### ISSUE THREAD

**Issue by MisinformedDNA** [dotnet/docs#9639]
The document links users to [Reverse Package Search](https://packagesearch.azurewebsites.net/), but this tool isn't really useful anymore. It still thinks .NET Core's moniker is 'netcore50', so we can't see packages that were made for released/latest versions of .NET Core.

This link should be removed until the external app is updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 577db847-e424-a9dc-ee2d-f2c6ddb54600
* Version Independent ID: 5fa219d8-0c9c-c758-c1ee-17cefd75ca24
* Content: [Port code from .NET Framework to .NET Core - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/porting/)
* Content Source: [docs/core/porting/index.md](https://github.com/dotnet/docs/blob/master/docs/core/porting/index.md)
* Product: **dotnet-core**
* GitHub Login: @cartermp
* Microsoft Alias: **mairaw**

**Comment by rjvdboon** [comment]
Rather than removing the link it would be great if the site itself would be improved. But there is apparently nowhere to file an issue, as I can't find any owner or github repo for the site...

**Comment by sujayvsarma** [comment]
The owner is @glennc (CC: @MadsTorgersen for visibility)

**Comment by cartermp** [comment]
Closing this out since it's not referenced in the article anymore
