### ISSUE TITLE
C# Guide: Classes

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#964]
This issue tracks the topic for http://github.com/dotnet/core-docs/csharp/classes.md

Much of the content can be taken from here: https://msdn.microsoft.com/en-us/library/ms173109.aspx

**Comment by pkulikov** [comment]
@BillWagner the first link looks to be broken, while the second link redirects to the https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/index

Can this issue be closed then?

**Comment by BillWagner** [comment]
@pkulikov 

> Or existing doc content should be revised as there are two topics on classes now:
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/classes
https://docs.microsoft.com/en-us/dotnet/csharp/classes

Yes, combining these two topics into the first is the correct fix.
