### ISSUE TITLE
Could you provide full code in a console application?

### ISSUE THREAD

**Issue by LiveLikeLastDay** [dotnet/docs#9643]
I'm a little bit lost.

Also is there a problem with the code "public Comparison&lt;T&gt; comparator;"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1dcd91a4-603a-feb9-cff2-94f1985417fc
* Version Independent ID: a86cde90-1eba-e1d5-2b42-2a3cd37f5499
* Content: [System.Delegate and the `delegate` keyword](https://docs.microsoft.com/en-us/dotnet/csharp/delegate-class)
* Content Source: [docs/csharp/delegate-class.md](https://github.com/dotnet/docs/blob/master/docs/csharp/delegate-class.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by asloppyone** [comment]
// From the .NET Core library

// Define the delegate type:
public delegate int Comparison<in T>(T left, T right);
The code is extracted from the library where sort() is implemented, so sort() must have been declared as a method taking a delegate as an argument.
