### ISSUE TITLE
ASP.NET Core Images starting from 2.1 included in microsoft/dotnet

### ISSUE THREAD

**Issue by MNF** [dotnet/docs#9645]
Please update, that Latest ASP.NET Core Images  for 2.1 and newer are now available on microsoft/dotnet. https://hub.docker.com/r/microsoft/aspnetcore/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b69a4b5-2003-e7a5-97a3-59e3737ea1ef
* Version Independent ID: 0df5f0d7-a2b4-e9b3-9f34-d66cedf418a3
* Content: [Development workflow for Docker apps](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/docker-application-development-process/docker-app-development-workflow#step-2-create-a-dockerfile-related-to-an-existing-net-base-image)
* Content Source: [docs/standard/microservices-architecture/docker-application-development-process/docker-app-development-workflow.md](https://github.com/dotnet/docs/blob/master/docs/standard/microservices-architecture/docker-application-development-process/docker-app-development-workflow.md)
* Product: **dotnet**
* GitHub Login: @CESARDELATORRE
* Microsoft Alias: **wiwagn**

**Comment by CESARDELATORRE** [comment]
Adding @mvelosop

**Comment by mvelosop** [comment]
Hi @MNF, @CESARDELATORRE, this has been already addressed, it's in the process to be merged into master with PR #7943, so I´m closing this issue now. will reopen if needed.
