### ISSUE TITLE
it is better to keep one consistent address

### ISSUE THREAD

**Issue by laohur** [dotnet/docs#9654]
The previous service address is "http://localhost:8000/GettingStarted/CalculatorService", so it is better to keep current service address in client fixed. And chang the .NET version  to v4.0 to run sucessfullly in first time.

"      &lt;endpoint address="http://localhost:8000/GettingStarted/CalculatorService"
"
"    &lt;supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.0,Profile=Client" /&gt;
"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05c2edb7-168e-ea7c-3f5a-3fdc226c68a3
* Version Independent ID: b8b5bd7f-14cd-ecd5-ecc3-a73bfcc28a99
* Content: [How to: Configure a Basic Windows Communication Foundation Client](https://docs.microsoft.com/en-us/dotnet/framework/wcf/how-to-configure-a-basic-wcf-client)
* Content Source: [docs/framework/wcf/how-to-configure-a-basic-wcf-client.md](https://github.com/dotnet/docs/blob/master/docs/framework/wcf/how-to-configure-a-basic-wcf-client.md)
* Product: **dotnet-framework**
* GitHub Login: @Lxiamail
* Microsoft Alias: **wcfsrvt**

**Comment by Thraka** [comment]
I'm not sure I understand what you're suggesting. Can you provide more information?
