### ISSUE TITLE
It's confusing about 'transformer.'

### ISSUE THREAD

**Issue by sheng-jie** [dotnet/docs#9655]
Transformer : A transformer is a component that takes data, does some work on it, and returns new transformed data.
Estimator：This is an object that learns from data. The result of the learning is a transformer.
-----

I think it should be better to change the 'transformer' in Estimator to 'model'.

[AB#1530397](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1530397)

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: edace175-268c-7428-dad5-95cd974422c3
* Version Independent ID: 707aed84-b636-088a-bf57-1cc5e4f69631
* Content: [Basic concepts for model training in ML.NET](https://docs.microsoft.com/zh-cn/dotnet/machine-learning/basic-concepts-model-training-in-mldotnet)
* Content Source: [docs/machine-learning/basic-concepts-model-training-in-mldotnet.MD](https://github.com/dotnet/docs/blob/master/docs/machine-learning/basic-concepts-model-training-in-mldotnet.MD)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by wschin** [comment]
Since a model can be a series of transformers, we'd like to keep our current naming convention. :)
