### ISSUE TITLE
Provide reasons why to chose the enum value

### ISSUE THREAD

**Issue by PeterPann23** [dotnet/docs#9658]
I think that for the majority of all users they will find it helpful if these enums are documented a bit better. When would one chose one over the other, also not all trainers work well on negative values, pointing that out would help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87174b51-7fce-54b7-c116-88eedf4ffc03
* Version Independent ID: 64d5b4c9-1be0-b6e1-81d2-e99fa34dfecb
* Content: [NormalizingEstimator.NormalizerMode Enum (Microsoft.ML.Transforms.Normalizers)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.transforms.normalizers.normalizingestimator.normalizermode?view=ml-dotnet)
* Content Source: [dotnet/xml/Microsoft.ML.Transforms.Normalizers/NormalizingEstimator+NormalizerMode.xml](https://github.com/dotnet/ml-api-docs/blob/live/dotnet/xml/Microsoft.ML.Transforms.Normalizers/NormalizingEstimator+NormalizerMode.xml)
* Product: **dotnet-ml-api**
* GitHub Login: @sfilipi
* Microsoft Alias: **johalex**

**Comment by mairaw** [comment]
@natke can you look at this issue for the ML.NET API docs? It seems the API doesn't exist anymore.
