### ISSUE TITLE
wrong input at city var

### ISSUE THREAD

**Issue by ibm5155** [dotnet/docs#9660]
Person p = new Person("John", "Quincy", "Adams", "Boston", "MA");
       var (fName, _, city, _) = p;// city = "Adams"
should be
       Person p = new Person("John", "Quincy", "Adams", "Boston", "MA");
       var (fName, _, _, city, _) = p;// city = "Boston

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8047b417-55af-c6df-9333-f1e1c428e594
* Version Independent ID: 8bcc16bb-c2d8-0b6d-af20-6958964efe9e
* Content: [Discards - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/discards)
* Content Source: [docs/csharp/discards.md](https://github.com/dotnet/docs/blob/master/docs/csharp/discards.md)
* Product: **dotnet-csharp**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by mairaw** [comment]
Thanks for your feedback @ibm5155 but the code is correct.

It uses the `Deconstruct` method with 4 parameters:

```csharp
public void Deconstruct(out string fname, out string lname, 
                           out string city, out string state)
```

So your change wouldn't even compile without adding a Deconstruct that looks like this:

```csharp
    public void Deconstruct(out string fname, out string mname, out string lname,
                            out string city, out string state)
    {
        fname = FirstName;
        mname = MiddleName;
        lname = LastName;
        city = City;
        state = State;
    }
```

I hope this helps!
