### ISSUE TITLE
Getting Error

### ISSUE THREAD

**Issue by regal60740** [dotnet/docs#9661]
base.Initialize(component); gives me this error: 	The name 'component' does not exist in the current context	MarqueeControlLibrary	C:\Users\Joe\source\repos\MarqueeControlTest\MarqueeControlLibrary\Design\MarqueeControlRootDesigner.cs	21	Active

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d6f328c-9e30-729a-663b-f58af880914e
* Version Independent ID: 5618d4bc-f5af-43d0-5ba4-5af39d0ec76e
* Content: [Walkthrough: Creating a Windows Forms Control That Takes Advantage of Visual Studio Design-Time Features](https://docs.microsoft.com/en-us/dotnet/framework/winforms/controls/creating-a-wf-control-design-time-features)
* Content Source: [docs/framework/winforms/controls/creating-a-wf-control-design-time-features.md](https://github.com/dotnet/docs/blob/master/docs/framework/winforms/controls/creating-a-wf-control-design-time-features.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by tdykstra** [comment]
@regal60740 Are you still looking for an answer to this question?

**Comment by regal60740** [comment]
No, I retired.
