### ISSUE TITLE
No docs for C# compiler error CS1648

### ISSUE THREAD

**Issue by ricobbe** [dotnet/docs#9665]
Unable to find documentation for C# compiler error CS1648: "Members of readonly field 'Container.st' cannot be modified (except in a constructor or a variable initializer)"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc586192-534e-0108-d265-c4f2f6947c57
* Version Independent ID: 4d39f536-5d78-335b-3525-d4b581c28fdc
* Content: [C# Compiler Errors](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/)
* Content Source: [docs/csharp/language-reference/compiler-messages/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-messages/index.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mikkelbu** [comment]
It can be found here https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs1648. It is probably due to this issue #1491 that the content is not found with the other errors.

**Comment by BillWagner** [comment]
Thanks for pointing this out @ricobbe 

As @mikkelbu points out, our articles on errors and warnings are currently in two different directories due to a couple migration processes.  

#1491 details the work to reconcile these two locations.

Closing as no further action is needed.
