### ISSUE TITLE
WCF basicHttpBinfing configuration description is missing default value for transferMode

### ISSUE THREAD

**Issue by salixzs** [dotnet/docs#9669]
Basically all attributes for WCF basicHttpBindings have mentioned their default values. 
transferMode attribute is missing one. I suspect it is "Buffered", but it could be good to officially confirm it :-)
Thanks for great docs!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0f13fe3-fc19-5741-40fc-a650ca68fb1a
* Version Independent ID: c17fd530-ad39-c8ae-78ac-6126307563db
* Content: [&lt;basicHttpBinding&gt;](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/wcf/basichttpbinding)
* Content Source: [docs/framework/configure-apps/file-schema/wcf/basichttpbinding.md](https://github.com/dotnet/docs/blob/master/docs/framework/configure-apps/file-schema/wcf/basichttpbinding.md)
* Product: **dotnet-framework**
* GitHub Login: @Lxiamail
* Microsoft Alias: **wcfsrvt**

**Comment by tdykstra** [comment]
@salixzs Per [the enum documentation](https://docs.microsoft.com/en-us/dotnet/api/system.servicemodel.transfermode), you are correct that the default is Buffered, I'll leave this issue open until we get a chance to add the default value here.
