### ISSUE TITLE
Unit testing best practices and AAA comments

### ISSUE THREAD

**Issue by jpreese** [dotnet/docs#9677]
I noticed on the Unit testing best practices document, AAA comments were added to each test via PR https://github.com/dotnet/samples/pull/379

My concern with this is that I believe it promotes the use of physically commenting each section with their Arrange, Act, and Assert sections. I personally disagree with this approach, and favor just breaking each section up via a newline as originally written. 

Obviously this is just a matter of opinion, so if we decide to leave it, I'd like to open a PR to make the comments a little more consistent. Some have a trailing space after the beginning comment syntax (//) and some do not.

Thoughts?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51947dc8-9ae8-21fa-13db-a7ffb3f9bc0e
* Version Independent ID: be661bf5-6f6e-cd18-344b-253edf5751ae
* Content: [Best practices for writing unit tests - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-best-practices)
* Content Source: [docs/core/testing/unit-testing-best-practices.md](https://github.com/dotnet/docs/blob/master/docs/core/testing/unit-testing-best-practices.md)
* Product: **dotnet-core**
* GitHub Login: @jpreese
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@jpreese Thanks for writing this up.  I've been thinking a bit over the holiday break about the best resolution.  I whole-heartedly agree with not having "arrange, act, assert" sections labeled in production code. And, our tutorials should teach the processes for production code.

However, the tutorials aren't production code, but instead are learning resources. The labels can be helpful for developers working to learn the idioms.

I propose leaving the "AAA" comments on the examples in the [Arranging your tests](https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-best-practices#arranging-your-tests) section, but not in the other sections.

What do you think?

**Comment by jpreese** [comment]
I agree with this approach. I'll whip up a PR sometime today.

Thanks for the feedback!

**Comment by jpreese** [comment]
https://github.com/dotnet/samples/pull/549
