### ISSUE TITLE
The LINQ to XML link links to “previous version” documentation

### ISSUE THREAD

**Issue by binki** [dotnet/docs#9678]
When I follow the link to [LINQ to XML](https://msdn.microsoft.com/library/f0fe21e9-ee43-4a55-b91a-0800e5782c13) in this document, I enter the “previous version” style documentation with this header:

&gt;  We're no longer updating this content regularly. Check the [Microsoft Product Lifecycle](https://support.microsoft.com/en-us/lifecycle/selectindex) for information about how this product, service, technology, or API is supported.

I shouldn’t be linked to previous versions documentation which has this warning when browsing the current version of the documentation.

It looks like the target page links to the C# and VB.net versions of the LINQ to XML guides. There should be a “current version” version of that landing page and it should be linked from this page instead of the “previous version” one.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e4e006a-3b84-bc10-377b-aa5d1ca02e04
* Version Independent ID: 4f022102-f171-5ff2-cc3d-a6247f83643f
* Content: [XML Processing Options](https://docs.microsoft.com/en-us/dotnet/standard/data/xml/xml-processing-options)
* Content Source: [docs/standard/data/xml/xml-processing-options.md](https://github.com/dotnet/docs/blob/master/docs/standard/data/xml/xml-processing-options.md)
* Product: **dotnet**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Thanks for your feedback @binki. This issue touches on a lot of migration efforts that are going on at the moment.
The most relevant related issue would be the following: https://github.com/dotnet/docs/issues/4728. Once we add that new set of docs, then the links would be revised with that effort.

**Comment by mairaw** [comment]
This was fixed by PR #10683, which added a link to the C# guide and one to the VB guide. Once we finish the work for #4728, we'll get the links updated to go to the new single target.
