### ISSUE TITLE
No longer necessary to get ip address of windows container to browse it

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#9681]
@matteopessina commented on [Wed Dec 19 2018](https://github.com/dotnet/docs.it-it/issues/56)

It seems that is no longer necessary to get the ip address of the windows container to browse the aspnetcore app, as stated in the following link
https://github.com/dotnet/dotnet-docker/blob/master/samples/aspnetapp/aspnetcore-docker-windows.md

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: 9731aae1-505b-abb1-0d4b-d6a83ec735e1
* Version Independent ID: 760790d5-0e81-ea6c-19ea-f226d08ddf1f
* Content: [Panoramica delle immagini Docker - .NET Core](https://docs.microsoft.com/it-it/dotnet/core/docker/building-net-docker-images?view=aspnetcore-2.2)
* Content Source: [docs/core/docker/building-net-docker-images.md](https://github.com/dotnet/docs.it-it/blob/live/docs/core/docker/building-net-docker-images.md)
* Product: **dotnet-core**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by CeciAc** [comment]
Hi team, 
Please check the contributor comments on this issue

Kind regards,
Microsoft DOCS International Team

**Comment by BillWagner** [comment]
thanks @CeciAc 
The behavior for this has changed, and we should update it.
