### ISSUE TITLE
VB forgotten

### ISSUE THREAD

**Issue by mccalljd** [dotnet/docs#9686]
Halfway through this walkthrough, the corresponding VB code was left out.  It was annoying but a good way to learn. 

Also, when the background image was downloaded, there was no instruction on where it should be saved, or how to actually access it.  The code would always hit an exception on loading the image.

In addition, when many of the empty code shells were run, Symantec Endpoint Protection would delete the .exe file, reporting a "Heuristic Virus," from their "SAPE technolgy," whatever that means.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0dc39f7-b153-a46c-3b88-07c8ed2c71bc
* Version Independent ID: 78a14535-9703-e2af-4451-783a7c4c10be
* Content: [Create a WPF application in Visual Studio](https://docs.microsoft.com/en-us/dotnet/framework/wpf/getting-started/walkthrough-my-first-wpf-desktop-application#add-controls)
* Content Source: [docs/framework/wpf/getting-started/walkthrough-my-first-wpf-desktop-application.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/getting-started/walkthrough-my-first-wpf-desktop-application.md)
* Product: **dotnet-framework**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment]
@mccalljd Sorry for the late reply. I checked the document and I see the VB snippets appearing. Something must have gotten fixed. Also, step 12 has you import the image to the project. However, I wonder if that image needs to be marked as copy-to-output or something? Anyway, I'm going to close this issue as it looks like the vb code appears correctly.

Thanks.
