### ISSUE TITLE
Possible error in example from using x?.y

### ISSUE THREAD

**Issue by jons** [dotnet/docs#9688]
I followed this example for a left join, but an expression in my code that is of the form `subpet?.Name` produces the compiler error "An expression tree lambda may not contain a null propagating operator."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d433265d-15f4-bd2e-a3d1-8148a3968783
* Version Independent ID: 75d2c893-1d07-f836-62f1-e767edfcebac
* Content: [Perform left outer joins (LINQ in C#)](https://docs.microsoft.com/en-us/dotnet/csharp/linq/perform-left-outer-joins)
* Content Source: [docs/csharp/linq/perform-left-outer-joins.md](https://github.com/dotnet/docs/blob/master/docs/csharp/linq/perform-left-outer-joins.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mikkelbu** [comment]
I just tried the example and it worked here. Could the problem be that you are using something , see https://stackoverflow.com/a/44681421 for more info.

**Comment by BillWagner** [comment]
Thanks for writing this @jons 

Some language features are not supported in IQueryable implementations. That may be the difference between the two samples.

I've added this to make sure we address it when we update LINQ content.
