### ISSUE TITLE
documentation incomplete?

### ISSUE THREAD

**Issue by mccalljd** [dotnet/docs#9689]
I am really frustrated.  None of the examples I have found on line (and I have been reading them all day) tell me how to get this Class into my code.  Visual Studio lists FolderBrowserDialog as undefined.  If I try to import System.Windows.Forms it is tagged as "imports statement unnecessary."   It would be nice if the documentation would include how these classes are intended to be implemented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a3f934e-bc23-d7bf-b954-09110edb5be7
* Version Independent ID: ae882ead-efb5-8936-19d5-23f30183aed0
* Content: [How to: Choose Folders with the Windows Forms FolderBrowserDialog Component](https://docs.microsoft.com/en-us/dotnet/framework/winforms/controls/how-to-choose-folders-with-the-windows-forms-folderbrowserdialog-component)
* Content Source: [docs/framework/winforms/controls/how-to-choose-folders-with-the-windows-forms-folderbrowserdialog-component.md](https://github.com/dotnet/docs/blob/master/docs/framework/winforms/controls/how-to-choose-folders-with-the-windows-forms-folderbrowserdialog-component.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by githubsnk** [comment]
Hello,
what i have to do for insert a control that verify that the path exist like C:/Programs,  and is not like  a fake directory C:/Programs/wrongdirectory ... ?
