### ISSUE TITLE
Missing NameOf in Visual Basic Language Reference

### ISSUE THREAD

**Issue by Berrysoft** [dotnet/docs#9690]
The NameOf keyword is missing in the keyword page, and according to [#366](https://github.com/dotnet/vblang/issues/366), the keyword is missing in the language reference.

The Visual Basic What's New topic should also be updated to link to this topic for detailed information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb2d0d24-a228-ab33-1c62-3b0a701ff318
* Version Independent ID: 9ef3c275-ce7b-808b-8acd-3d394296d897
* Content: [Keywords (Visual Basic)](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/keywords/)
* Content Source: [docs/visual-basic/language-reference/keywords/index.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/language-reference/keywords/index.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by mairaw** [comment]
@KathleenDollard since you commented on the spec issue too, can you triage this one here too?

**Comment by mairaw** [comment]
@KathleenDollard should we add docs for this?

**Comment by KathleenDollard** [comment]
yes, it should be a keyword.
