### ISSUE TITLE
Possibly missing step to instruct sending the PigLatin module to FSI

### ISSUE THREAD

**Issue by gabehollombe-aws** [dotnet/docs#9694]
"Next, in the FSI window, call the function with the PigLatin module that you defined earlier:"

Following along, I tried using `PigLatin.toPigLatin "banana";;` in the FSI window after moving `toPigLatin` into a `PigLatin` module in `ClassLibraryDemo.fs` but it didn't seem to work until I selected the entire module and did another `Alt+Enter` to get the contents sent to FSI.  

Did I miss a step in the instructions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c543c271-0800-4ff9-4dfb-5154efb85732
* Version Independent ID: f1a4752f-a001-5e5e-2604-358db6f5adbc
* Content: [Get Started with F# in Visual Studio Code](https://docs.microsoft.com/en-us/dotnet/fsharp/get-started/get-started-vscode)
* Content Source: [docs/fsharp/get-started/get-started-vscode.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/get-started/get-started-vscode.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by sjetha** [comment]
Just ran into this same issue myself. There's definitely something missing.

**Comment by StasBalia** [comment]
Same thing, only if i select module PigLatin from start to end and press Alt+Enter, then i can use PigLatin.toPigLatin in FSI.
