### ISSUE TITLE
VB tutorials - LINQ 

### ISSUE THREAD

**Issue by obelink** [dotnet/docs#97]
We need VB.NET LINQ in the tutorials list. This is a big topic so there could be a lot of samples here. Good starting point: https://code.msdn.microsoft.com/101-LINQ-Samples-3fb9811b

Tutorials should include one or more code examples, each example should also show expected output and should include an explanation of the code where it isn't obvious. Examples shouldn't be dependent on a specific IDE or target platform.

**Comment by obelink** [comment]
I will start with these samples.

**Comment by mairaw** [comment]
@stevehoag is there anything else to be done here? I know you've recently worked on some LINQ content.

**Comment by stevehoag** [comment]
This is from before the LINQ topics for VB were moved over from MSDN, so I'm guessing this is no longer a priority.
