### ISSUE TITLE
No Reference Documentation for Console Apps

### ISSUE THREAD

**Issue by piBoss** [dotnet/docs#9700]
I've searched online and in my offline documentation and can't find a topic on Console Applications, other then this one paragraph page of nothing.
For example, I simply desire to execute a command as though I opened a Command windows; "ipconfig /all" and can't find a single document on this, or any other Console application technologies.  

Thank you for any help!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1193ecc1-15d4-1a5c-2919-97e2e5583d2b
* Version Independent ID: 59dafd69-acba-5e10-c62a-0e361b1965e2
* Content: [Building Console Applications in the .NET Framework](https://docs.microsoft.com/en-us/dotnet/standard/building-console-apps)
* Content Source: [docs/standard/building-console-apps.md](https://github.com/dotnet/docs/blob/master/docs/standard/building-console-apps.md)
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by rpetrusha** [comment]
Thanks for your feedback, @piBoss. Most of the documentation on controlling the console is contained in the [System.Console](https://docs.microsoft.com/dotnet/api/system.console) API reference documentation. To execute a command such as **ipconfig** within a console application, call the [Process.Start(ProcessStartInfo)](https://docs.microsoft.com/dotnet/api/system.diagnostics.process.start#System_Diagnostics_Process_Start_System_Diagnostics_ProcessStartInfo_) method. 

I hope that this helps. In the meantime, I'll close this issue.
