### ISSUE TITLE
Following up on the Windows Installer page

### ISSUE THREAD

**Issue by casterle** [dotnet/docs#9703]
The recommendation to use InstallShield is not available to VS Community Edition users - Pro and up only even for the light version. So MS has no traditional-installer solution for VS CE users?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fdf77b0f-5062-0a1a-c172-821d24a378a4
* Version Independent ID: f67b80a0-9126-40c8-a8c7-c6a5c6efdff5
* Content: [Deploying a WPF Application (WPF)](https://docs.microsoft.com/en-us/dotnet/framework/wpf/app-development/deploying-a-wpf-application-wpf)
* Content Source: [docs/framework/wpf/app-development/deploying-a-wpf-application-wpf.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/app-development/deploying-a-wpf-application-wpf.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
I believe all the options available are listed at https://docs.microsoft.com/en-us/visualstudio/deployment/deploying-applications-services-and-components?view=vs-2017#create-an-installer-package-windows-client

/cc @gewarren @Mikejo5000
