### ISSUE TITLE
C# Guide: Using C# Interactive from the MacOS or Linux terminal

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#971]
This issue tracks the topic for https://github.com/dotnet/docs/blob/master/docs/csharp/interactive/with-bash.md

This topic should teach the reader how to use C# interactive using the command line in either MacOS or Linux. It should discuss installing and launching the C# interactive shell. It is a sub-task for issue #968

**Comment by AndreasHassing** [comment]
Should this guide explain how to use the [Mono REPL](http://www.mono-project.com/docs/tools+libraries/tools/repl/)? I'm guessing not, but until https://github.com/dotnet/roslyn/issues/17666 is closed, what is the alternative?

**Comment by mairaw** [comment]
Mono REPL would be a stop gap but we're going to wait until we have the final solution in place,

**Comment by BillWagner** [comment]
Closing this as it doesn't fit the updated C# Guide.
