### ISSUE TITLE
Object expressions explanation should mention its limitations

### ISSUE THREAD

**Issue by abelbraaksma** [dotnet/docs#9712]
As in the title, I'm thinking of:

* Cannot be used with sealed types
* Cannot be used with value types
* Cannot be used with types that do not have a constructor
* Cannot be used with discriminated unions
* Cannot be used with record types
* Cannot be used with structs

Also:

* Can only be used to override existing members in the base class
* Members can be defined using either `member` or `override`
* Members cannot be inlined
* The `as X` syntax used with class definitions cannot be used (notably contrary to what is written in Wikibooks: https://en.wikibooks.org/wiki/F_Sharp_Programming/Interfaces#Implementing_Interfaces_with_Object_Expressions)
* `val`, `let` and `static let` are not permitted (also different from what Wikibooks shows)

I'm sure these things aren't exhaustive, but it's a start.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db76e619-9fa5-bed5-8115-f8e95759623d
* Version Independent ID: f82139b7-e0b1-4dd8-f436-921f992af2f7
* Content: [Object Expressions - F#](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/object-expressions)
* Content Source: [docs/fsharp/language-reference/object-expressions.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/language-reference/object-expressions.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by akeeton** [comment]
Is this comment in the Remarks code example correct?

    // This object expression implements multiple interfaces.
