### ISSUE TITLE
Visual Studio does not prompt to fix binding errors when double click

### ISSUE THREAD

**Issue by THammond9** [dotnet/docs#9717]
The last section seems to be incorrect. When I double click the output warning or click the warning and press enter nothing happens. Either this documentation is incorrect or there is a bug in visual studio.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62b2e725-23a6-e54d-7afb-28448cf7a869
* Version Independent ID: 385f6d74-fe5c-7cc2-d0be-1cf0c0216f5d
* Content: [Enable or disable autogenerated binding redirects](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/how-to-enable-and-disable-automatic-binding-redirection)
* Content Source: [docs/framework/configure-apps/how-to-enable-and-disable-automatic-binding-redirection.md](https://github.com/dotnet/docs/blob/master/docs/framework/configure-apps/how-to-enable-and-disable-automatic-binding-redirection.md)
* Product: **dotnet-framework**
* GitHub Login: @mcleblanc
* Microsoft Alias: **markl**

**Comment by fruex** [comment]
I can reproduce this problem VS 15.9.4.

**Comment by BobbyCannon** [comment]
Same with 15.9.7

**Comment by fruex** [comment]
> Same with 15.9.7

Did you change something with Platform? After some checks I realized that it worked on AnyCPU not in x86.

**Comment by mairaw** [comment]
@terrajobst any clue on who could look into this issue with the binding redirects dialog for web apps?

**Comment by terrajobst** [comment]
@fruex @BobbyCannon 

What kind of project it is and what is it targeting? (e.g. WinForms on .NET FX 4.5, ASP.NET Web Forms on 4.6 etc)?

**Comment by terrajobst** [comment]
The right contact would be @Andrew-MSFT's team

**Comment by fruex** [comment]
> @fruex @BobbyCannon
> 
> What kind of project it is and what is it targeting? (e.g. WinForms on .NET FX 4.5, ASP.NET Web Forms on 4.6 etc)?

Console on .NET 4.7.2.

I used this functionality when I was working with the Nuget Format Reference but when I went back it to the previous configuration with package.config, which during the installation of the packages corrects AsseblyInformation itself.

**Comment by Andrew-MSFT** [comment]
@AngelosP can you help here?

**Comment by AngelosP** [comment]
@cartermp This problem is related to binding redirects and surfaces on consoles targeting 4.7.2 so I'm throwing it over to you :)
