### ISSUE TITLE
C# Guide: Using the .NET Compiler Platform

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#972]
This issue tracks the topic for this page: https://github.com/dotnet/docs/csharp/roslyn/

This topic is a placeholder for an entire section of documents.  The .NET Compiler Platform SDK enables a rich range of scenarios to analyze and correct coding errors. 

This issue is really a meta issue for several tasks that will be required to cover these APIs completely:
- [x] Create Compiler SDK TOC
- [x] Create Getting Started content
- [ ] Create samples and tutorials
- [ ] Create conceptual content
- [x] Link to API reference (on the Roslyn Repository)
- [ ] Link to samples on roslyn-analyzers repository.

A good first step would be to create the issues and tasks for those sections.

**Comment by GuardRex** [comment]
When *roslyn/index.md* is created, activate two links in *docs/csharp/whats-new/index.md* to the new topic.

**Comment by BillWagner** [comment]
closing due to scheduling priorities.

**Comment by BillWagner** [comment]
Reopening per this twitter conversation: https://twitter.com/RickStrahl/status/1091088235982278656

Note that this will be scheduled based on all upcoming C# priorities.

**Comment by BillWagner** [comment]
closing because this way of tracking epics has not proven useful.
