### ISSUE TITLE
Which versions will this repair?

### ISSUE THREAD

**Issue by GLComputing** [dotnet/docs#9722]
The other pages in this guide talk about 4.7.2 but the official download (1.3) only goes up to 4.6.

Which version is this link and which Frameworks does it repair?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 567666ce-6b1c-ea9b-aa9e-eae9da4f9485
* Version Independent ID: f2e94c72-459b-c8f1-7eec-73e7d4197f4d
* Content: [Repair the .NET Framework](https://docs.microsoft.com/en-us/dotnet/framework/install/repair)
* Content Source: [docs/framework/install/repair.md](https://github.com/dotnet/docs/blob/master/docs/framework/install/repair.md)
* Product: **dotnet-framework**
* GitHub Login: @rlander
* Microsoft Alias: **mairaw**

**Comment by captivemother** [comment]
windows 10 microsoft egde 10
