### ISSUE TITLE
What happened to TestHost?

### ISSUE THREAD

**Issue by weitzhandler** [dotnet/docs#9724]
Can't find it on NuGet, is it retired?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 245ea389-75e9-1321-3be4-dc8d8e47a925
* Version Independent ID: 5aac1345-20a9-d6b5-b4d8-203f5d80bfa0
* Content: [Testing ASP.NET Core services and web apps](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/multi-container-microservice-net-applications/test-aspnet-core-services-web-apps)
* Content Source: [docs/standard/microservices-architecture/multi-container-microservice-net-applications/test-aspnet-core-services-web-apps.md](https://github.com/dotnet/docs/blob/master/docs/standard/microservices-architecture/multi-container-microservice-net-applications/test-aspnet-core-services-web-apps.md)
* Product: **dotnet**
* GitHub Login: @CESARDELATORRE
* Microsoft Alias: **wiwagn**

**Comment by jnsn** [comment]
@weitzhandler As far as I can tell, it's still available: https://www.nuget.org/packages/Microsoft.AspNetCore.TestHost
