### ISSUE TITLE
FDE needs documentation

### ISSUE THREAD

**Issue by DylanFPS** [dotnet/docs#9728]
The Framework-Dependent Executables need documentation on how to deploy them as the other deployment options have.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06a17d5d-5f6e-d6bc-324b-af411a42ccb8
* Version Independent ID: f58588d7-70f6-aa32-5c6d-ac3e7d72d87c
* Content: [.NET Core Application Deployment - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/deploying/#framework-dependent-executables-fde)
* Content Source: [docs/core/deploying/index.md](https://github.com/dotnet/docs/blob/master/docs/core/deploying/index.md)
* Product: **dotnet-core**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by danstur** [comment]
At least a very short description of how we're supposed to create FDEs in this issue would be quite lovely as a starter before we get a complete documentation.

As far as I can see Microsoft went through the effort to implement the new feature and advertise it, but then didn't think to mention how to use it absolutely *anywhere*. 

The commandline tool also doesn't mention it anywhere in its help either.

**Comment by mairaw** [comment]
Thanks for your feedback @DylanFPS. We'll update the docs to include that hopefully this sprint.
