### ISSUE TITLE
command line dotnet new mvc

### ISSUE THREAD

**Issue by leobarbastefano** [dotnet/docs#9729]
I have "netcoreapp2.2" and "AspNetCore version 2.2.0" and when I run "dotnet new mvc" it is not installing bootstrap and bower. Is there any extra command to do that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b952f8a-18e1-4843-0741-6ca877fb303a
* Version Independent ID: d80dfb96-bc86-a960-abec-255dd907d04d
* Content: [dotnet new command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-new?tabs=netcore21)
* Content Source: [docs/core/tools/dotnet-new.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-new.md)
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
@Rick-Anderson @scottaddie can you help with this feedback?

**Comment by Rick-Anderson** [comment]
[Bower has been deprecated](https://blogs.msdn.microsoft.com/webdev/2018/04/18/what-happened-to-bower/)
bootstrap is there. look for wwwroot\lib\bootstrap\

what does `dotnet --version` show?

**Comment by scottaddie** [comment]
As Rick mentions above, Bower is deprecated. As such, there's no package manager being used to "install" client-side assets such as Bootstrap. The files are simply included by the project template in the *wwwroot\lib* folder.

Replacement solutions for Bower include npm or [LibMan](https://docs.microsoft.com/aspnet/core/client-side/libman/).

**Comment by MaisamRazai** [comment]
I can't see the AccountController when I create MVC application with this command:
 dotnet new mvc --auth SingleOrg

**Comment by Rick-Anderson** [comment]
You need to scaffold Identity now. See https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-2.2&tabs=visual-studio
