### ISSUE TITLE
Test Your Solution

### ISSUE THREAD

**Issue by bugaevski** [dotnet/docs#9733]
Did anybody from Microsoft try to use the suggested code for Default.aspx?
It does not even compile..
The subject of that article - is extremely important. BUT - it is absolutely useless. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8056ac34-1796-8082-572a-bb75f2af6395
* Version Independent ID: f382bce9-6e5b-cb9f-7e01-e2f55786b042
* Content: [How To: Build Claims-Aware ASP.NET Web Forms Application Using WIF](https://docs.microsoft.com/en-us/dotnet/framework/security/how-to-build-claims-aware-aspnet-web-forms-app-using-wif)
* Content Source: [docs/framework/security/how-to-build-claims-aware-aspnet-web-forms-app-using-wif.md](https://github.com/dotnet/docs/blob/master/docs/framework/security/how-to-build-claims-aware-aspnet-web-forms-app-using-wif.md)
* Product: **dotnet-framework**
* GitHub Login: @BrucePerlerMS
* Microsoft Alias: **dotnetcontent**

**Comment by nzhong168** [comment]
Same here. I found the samples have less quality than before.

**Comment by mairaw** [comment]
That content is being archived with PR #14801. It's not maintained any longer. So I'm closing this issue.
