### ISSUE TITLE
What's new in C# 7.3 - incorrect statement in document

### ISSUE THREAD

**Issue by johnkellyoxford** [dotnet/docs#9737]
[Enter feedback here]

-
![image](https://user-images.githubusercontent.com/32420055/50422088-98704580-083e-11e9-8b02-fe6c90d620e0.png)
That code does not compile in a safe context, it clearly has the unsafe keyword in it
--
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c0320fd-c7ac-200e-7e50-6b3ddcaa6a52
* Version Independent ID: 6ea1af7f-2251-f05f-4834-5a00e57fc5fb
* Content: [What's new in C# 7.3](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-7-3)
* Content Source: [docs/csharp/whats-new/csharp-7-3.md](https://github.com/dotnet/docs/blob/master/docs/csharp/whats-new/csharp-7-3.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@johnkellyoxford Thanks for pointing this out.

The examples you want are on the reference page for the [`is` operator](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/is#pattern-matching-with-is)

This page should be updated with a link to that content. I've added the "up for grabs" label to this issue, and added it to our community contribution project.
