### ISSUE TITLE
Roll CoreFX PInvoke guidance into docs

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/docs#9750]
The CoreFX repo has a document with a fair bit of useful guidance about effective use of PInvoke. Some or all of this could be rolled into the MSDN docs here, as it is not CoreFX specific.

Document is [interop-pinvokes](https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/interop-pinvokes.md
) also a section in general [interop](https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/interop-guidelines.md#definition) document.

The relevant docs topics all seem [here](https://github.com/dotnet/docs/blob/master/docs/framework/interop)

@AaronRobinsonMSFT 

https://github.com/dotnet/corefx/pull/34249

**Comment by AaronRobinsonMSFT** [comment]
@jkoritzinsky is this something we could fold into some of the samples we want to create for P/Invokes?
