### ISSUE TITLE
Instance Constructor as Static member?

### ISSUE THREAD

**Issue by Mandated** [dotnet/docs#9752]
In Function Member Invocation it lists Instance Constructor as a Static Member.  Just wanted to check and see if that is right.
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/expressions#function-member-invocation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e783650c-e063-e268-316e-564362cb1e37
* Version Independent ID: aa9f4996-cab4-0bed-6452-213342453785
* Content: [Expressions](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/expressions#function-member-invocation)
* Content Source: [spec/expressions.md](https://github.com/dotnet/csharplang/blob/master/spec/expressions.md)
* Product: **dotnet-csharp**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for spotting this and pointing out the issue @Mandated 

I've submitted a PR with the fix:  dotnet/csharplang#2111

**Comment by BillWagner** [comment]
Moving to dotnet/csharplang.   See dotnet/csharplang#2209

Closing here.
