### ISSUE TITLE
Bad link

### ISSUE THREAD

**Issue by maryob77062** [dotnet/docs#9753]
Troubleshooting Data Types. https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/programming-guide/language-features/data-types/troubleshooting-data-types
Produces 404 error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1297ceea-f38a-44c7-f275-2c1e6def3fe7
* Version Independent ID: ce852873-7679-2645-de77-77459e42af94
* Content: [Boolean Data Type (Visual Basic)](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference//data-types/boolean-data-type)
* Content Source: [docs/visual-basic/language-reference/data-types/boolean-data-type.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/language-reference/data-types/boolean-data-type.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by maryob77062** [comment]
I was on the page Boolean Data Type (Visual Basic) https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference//data-types/boolean-data-type <https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/data-types/boolean-data-type>  I clicked on the link  <https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/programming-guide/language-features/data-types/troubleshooting-data-types> Troubleshooting Data Types. This link needs to be fixed. Yes I found the appropriate page but the link still needs to be fixed.

**Comment by KathleenDollard** [comment]
@maryob77062 

Sorry, I wasn't clear. I need help from the docs team on this. I really appreciate you reporting it. 

Let me add some cc's
cc: @rpetrusha, @BillWagner, @mairaw

**Comment by mairaw** [comment]
Do you remember how did you land on that page @maryob77062?
The page you were visiting somehow has a double // after language-reference, which makes the relative URLs break.

https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference//data-types/boolean-data-type

If you visit the “right” page, that doesn’t happen:
https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/data-types/boolean-data-type

If we can find whether there’s a page we own that is wrongfully adding the extra /, then we can fix this.

**Comment by maryob77062** [comment]
I cannot remember. Many times I come to Microsoft docs from Google.

**Comment by mairaw** [comment]
Interesting. Google indeed has that extra / in the path. I'll check with our engineering team if there's a way for us to fix this. Not sure if the site map we're sending them is wrong.
I just tried searching for https://www.google.com/search?q=Boolean+Data+Type+(Visual+Basic).

**Comment by presleyy** [comment]
@mairaw are you still able to see the extra / when searching for https://www.google.com/search?q=Boolean+Data+Type+(Visual+Basic)? I just tried it, the search results have the correct URL (https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/data-types/boolean-data-type) without any extra /

**Comment by mairaw** [comment]
Yes @presleyy 

![image](https://user-images.githubusercontent.com/12971179/51167209-d1f30a00-185a-11e9-9661-eb8d1d554917.png)

**Comment by mairaw** [comment]
That is weird @presleyy! Thanks for looking into this.

**Comment by presleyy** [comment]
I reproduced the problem once I set Google search setting to "United States". We checked the sitemaps, the https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/data-types/boolean-data-type is correct. Actually, it seems Google indexed two different URLs for that content, one is the correct, another is the one with the extra "/". I removed the incorrect one from Google search console, and re-indexed the correct URL. Now the https://www.google.com/search?q=Boolean+Data+Type+(Visual+Basic) is working well at my end. @mairaw would you help double check it in your environment? Once proved that's the solution, I'm going to fix such for the rest (I found there are dozen of URLs have such extra "/" indexed).

**Comment by presleyy** [comment]
This page has been re-indexed in Google. The issue has been resolved.

**Comment by mairaw** [comment]
Thanks for letting us know @presleyy. I can verify the fix.
