### ISSUE TITLE
Extra double spaces

### ISSUE THREAD

**Issue by NextTurn** [dotnet/docs#9755]
Why are there extra double spaces at the end of each line in some files?

**Comment by mairaw** [comment]
The script used to migrate the content from MSDN to docs did that.
It creates a new line. We’re removing those when updating the articles.

**Comment by mairaw** [comment]
Given this doesn't really cause any issues and we're slowly removing them as we go, I'll be closing this one.

See an example here of a PR that did remove those:
https://github.com/dotnet/docs/pull/9629/files

And we have issues like the following to change sections that rely on that extra double space in the end:
https://github.com/dotnet/docs/issues/6923
