### ISSUE TITLE
Question related to is pattern expression

### ISSUE THREAD

**Issue by RupendraDhillon** [dotnet/docs#9756]
The description of the is pattern expression says the following: "The is pattern expression extends the familiar is operator to query an object beyond its type."

Could you show an example where the is operator is used to query an object other than it's type ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc229b53-a548-4ef8-86b9-58670a81344a
* Version Independent ID: aeb15230-e1cc-df50-7edb-fb50164e13be
* Content: [What's New in C# 7.0 - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-7)
* Content Source: [docs/csharp/whats-new/csharp-7.md](https://github.com/dotnet/docs/blob/master/docs/csharp/whats-new/csharp-7.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
@johnkellyoxford Thanks for pointing this out.

The examples you want are on the reference page for the [`is` operator](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/is#pattern-matching-with-is)

This page should be updated with a link to that content. I've added the "up for grabs" label to this issue, and added it to our community contribution project.
