### ISSUE TITLE
XmlDocument naming

### ISSUE THREAD

**Issue by zackbiernat** [dotnet/docs#9762]
The name of the XmlDocument in Step 3 is different in the subsequent steps.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d033ccb-b2fa-384d-2bf6-c51a951d8ee4
* Version Independent ID: b56ee08f-c576-9491-4e20-a40d0a82b818
* Content: [How to: Verify the Digital Signatures of XML Documents](https://docs.microsoft.com/en-us/dotnet/standard/security/how-to-verify-the-digital-signatures-of-xml-documents)
* Content Source: [docs/standard/security/how-to-verify-the-digital-signatures-of-xml-documents.md](https://github.com/dotnet/docs/blob/master/docs/standard/security/how-to-verify-the-digital-signatures-of-xml-documents.md)
* Product: **dotnet**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by rpetrusha** [comment]
Thanks for pointing out the incorrect variable name, @zackbiernat. We've corrected it in dotnet/samples#566.
