### ISSUE TITLE
double is missing.

### ISSUE THREAD

**Issue by volkan-yazilim** [dotnet/docs#9766]
There is not 'double' in the list. It is necessary to explain why. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86308a57-1418-cf16-94f7-d840d56f6dda
* Version Independent ID: cdb096f4-7498-2db7-ad2d-cd7c794b0bee
* Content: [Implicit numeric conversions table - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/implicit-numeric-conversions-table)
* Content Source: [docs/csharp/language-reference/keywords/implicit-numeric-conversions-table.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/implicit-numeric-conversions-table.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by imba-tjd** [comment]
`double` can not **implicit** convert to other types.

**Comment by imba-tjd** [comment]
Personally I would -1 because explicit conversion is just below this one.

**Comment by volkan-yazilim** [comment]
#9793
