### ISSUE TITLE
would be great to undersand how can the client be setup without a Web Reference (which might not be added for one or another reason)

### ISSUE THREAD

**Issue by andreireiand** [dotnet/docs#9768]
Example: I'm working on a solution that comes pre-packed with a product, and that allows customization up to a certain degree ... however adding Web Service references doesn't work. I can add DLL references fine though. 
Best practices on this would be appreciated. thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c27c6cc-63c8-5c3d-f344-228f8ad86c90
* Version Independent ID: d560cf6a-e9bd-95e5-ce15-a08a5778181a
* Content: [How to: Create a Windows Communication Foundation Client](https://docs.microsoft.com/en-us/dotnet/framework/wcf/how-to-create-a-wcf-client)
* Content Source: [docs/framework/wcf/how-to-create-a-wcf-client.md](https://github.com/dotnet/docs/blob/master/docs/framework/wcf/how-to-create-a-wcf-client.md)
* Product: **dotnet-framework**
* GitHub Login: @Lxiamail
* Microsoft Alias: **wcfsrvt**

**Comment by Thraka** [comment]
I think this is a duplicate of #9772

**Comment by Thraka** [comment]
Marking this as a duplicate. I think this request is in the same scenario of the linked issue. @Lxiamail may have more information or can point you somewhere, but I think your question is best answered in a support forum.
