### ISSUE TITLE
if WCF(using app.config) is not allowed on the client side, can one use simpler concepts (such as HttpClient objects) to consume such services?

### ISSUE THREAD

**Issue by andreireiand** [dotnet/docs#9769]
And is there an example of that?

thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c27c6cc-63c8-5c3d-f344-228f8ad86c90
* Version Independent ID: d560cf6a-e9bd-95e5-ce15-a08a5778181a
* Content: [How to: Create a Windows Communication Foundation Client](https://docs.microsoft.com/en-us/dotnet/framework/wcf/how-to-create-a-wcf-client)
* Content Source: [docs/framework/wcf/how-to-create-a-wcf-client.md](https://github.com/dotnet/docs/blob/master/docs/framework/wcf/how-to-create-a-wcf-client.md)
* Product: **dotnet-framework**
* GitHub Login: @Lxiamail
* Microsoft Alias: **wcfsrvt**

**Comment by Thraka** [comment]
I found this searching stackoverflow: https://stackoverflow.com/questions/19675194/is-possible-to-access-wcf-service-without-adding-service-reference
