### ISSUE TITLE
CONTRIBUTING.md is written for contribution toward English repo only

### ISSUE THREAD

**Issue by JasonCard** [dotnet/docs#9770]
**Issue description**

[CONTRIBUTING.md](https://github.com/dotnet/docs/blob/master/CONTRIBUTING.md) is written for contribution toward English repo only, so when it was localized, it caused confusion for contributor toward localized repo. 
Here is the GitHub Issue raised for reference: [https://github.com/dotnet/docs.ja-jp/issues/275](https://github.com/dotnet/docs.ja-jp/issues/275)  

The sentence that caused confusion is, "**Step 4:** Submit a Pull Request (PR) from your branch to `dotnet/docs/master`." and "Your PR should *always* target the master branch. You should *never* open a PR that targets the live branch."  

For contribution toward localized languages such as Japanese, PR should target the `live` branch where the `Edit` button is set to take them. GitHub repos for localized languages do not use `master` branch and only use `live` branch, so contribution is setup to open PR in `live` branch.

Can you please help to add this exception to the contributor guide?

**Comment by BillWagner** [comment]
@JasonCard 

Should the PRs on localized repos target the live branch, or should those repos be reconfigured to edit on the master branch?  It's a one-line [config change](https://github.com/dotnet/docs/blob/master/.openpublishing.publish.config.json#L6)

Which is the preferred fix?

**Comment by JasonCard** [comment]
Hi @BillWagner 

PRs on localized repos should target the live branch as they are setup now.
Setup for loc repos are different from en-us repo because for most loc repos, we only use live branch to automatically publish localized handback files live. We want to avoid the extra step from having to merge from master to live for loc.  
So could we update CONTRIBUTING.md to clarify this difference?
