### ISSUE TITLE
running this example without the app.config (which proves troublesome to include into some apps) will be helpful

### ISSUE THREAD

**Issue by andreireiand** [dotnet/docs#9771]
Some apps just don't have appetite for app.config file ... I know there are ways to programmatically add app.config content straight into code - it would be great to understand how that can be done. thanks 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c27c6cc-63c8-5c3d-f344-228f8ad86c90
* Version Independent ID: d560cf6a-e9bd-95e5-ce15-a08a5778181a
* Content: [How to: Create a Windows Communication Foundation Client](https://docs.microsoft.com/en-us/dotnet/framework/wcf/how-to-create-a-wcf-client)
* Content Source: [docs/framework/wcf/how-to-create-a-wcf-client.md](https://github.com/dotnet/docs/blob/master/docs/framework/wcf/how-to-create-a-wcf-client.md)
* Product: **dotnet-framework**
* GitHub Login: @Lxiamail
* Microsoft Alias: **wcfsrvt**

**Comment by Thraka** [comment]
Thank you for the suggestion.

In this case I think it would complicate this example to add a bunch of stuff about configuring it without app.config. This article is being rewritten and does talk about some manual config.
