### ISSUE TITLE
how can we actually avoid using the app.config file?

### ISSUE THREAD

**Issue by andreireiand** [dotnet/docs#9772]
We've got:

Edit App.config in GettingStartedLib to reflect the changes made in code:

    Change line 14 to &lt;service name="GettingStartedLib.CalculatorService"&gt;
    Change line 17 to &lt;add baseAddress = "http://localhost:8000/GettingStarted/CalculatorService" /&gt;
    Change line 22 to &lt;endpoint address="" binding="wsHttpBinding" contract="GettingStartedLib.ICalculator"&gt;

is there a way to incorporate these into code?

thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c8cbb16-05b1-a5f2-9031-1d7beb52efea
* Version Independent ID: 98092a9f-c19a-cca9-75d6-75b9c3d4cc0b
* Content: [How to: Host and Run a Basic Windows Communication Foundation Service](https://docs.microsoft.com/en-us/dotnet/framework/wcf/how-to-host-and-run-a-basic-wcf-service)
* Content Source: [docs/framework/wcf/how-to-host-and-run-a-basic-wcf-service.md](https://github.com/dotnet/docs/blob/master/docs/framework/wcf/how-to-host-and-run-a-basic-wcf-service.md)
* Product: **dotnet-framework**
* GitHub Login: @Lxiamail
* Microsoft Alias: **wcfsrvt**

**Comment by Thraka** [comment]
This tutorial is not covering how to do this by hand. Please search for an answer in a support forum or a place like stackoverflow.

Thanks!
