### ISSUE TITLE
Signed or unsigned?

### ISSUE THREAD

**Issue by IainMcCracken** [dotnet/docs#9774]
This article claims to be about unsigned assemblies, but uses the words signed and unsigned interchangeably. First example code is referred to as friend_signed_A.cs in the text, but has a comment at the top saying friend_unsigned_A.cs. Step 3 mentions friend_signed_A.cs in the text but the example compiles friend_unsigned_A.cs. And so on. I was able to figure out that all instances should say unsigned for this article, but I was confused for a while.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2fa1e135-a734-9fcd-aa57-a1983ce5e9f8
* Version Independent ID: dbf9cf66-ebe7-ffac-f2ef-7b84b0cfd101
* Content: [How to: Create Unsigned Friend Assemblies (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/assemblies-gac/how-to-create-unsigned-friend-assemblies)
* Content Source: [docs/csharp/programming-guide/concepts/assemblies-gac/how-to-create-unsigned-friend-assemblies.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/concepts/assemblies-gac/how-to-create-unsigned-friend-assemblies.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Pangar** [comment]
I was just looking at that as well.  I think it was a simple mistake.  You can submit on github to make a change.

**Comment by Pangar** [comment]
I submitted the change on github to change all that say signed to unsigned.

**Comment by BillWagner** [comment]
This was fixed in #10010

Closing.
