### ISSUE TITLE
Contents of byte array[] being converted into twos compliment

### ISSUE THREAD

**Issue by saadsaeed01** [dotnet/docs#9778]
I have a byte array.
byte[] myArray={0x10,0x14,0x01}
Now if I print the contents of byte array e.g.
Console.WriteLine(myArray[0]);
I am getting this:
16(Which is two compliment of 0x10).
What I am doing wrong here

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbaecbd7-3fd4-ceca-9d12-48b3f4bf3677
* Version Independent ID: 01405e94-c064-9c7a-ed63-b0b440b9d2e5
* Content: [byte - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/byte)
* Content Source: [docs/csharp/language-reference/keywords/byte.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/byte.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mikedn** [comment]
> 16(Which is two compliment of 0x10).

What do you mean? 0x10 is the hexadecimal representation of 16, it has nothing to do with two's complement.

**Comment by BillWagner** [comment]
Closing as `0x10` is `16`. Previous comments add clarification.
