### ISSUE TITLE
xsl-xml_html_css

### ISSUE THREAD

**Issue by manuela1994** [dotnet/docs#9783]
i want add a tag of link for my path.css to xsl code but it still invalide 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56eb39a3-d417-0ca8-1bd4-a866a0866f98
* Version Independent ID: 0afa841d-721e-016f-2510-e5115072d20e
* Content: [XML documentation parse error: Start tag '&lt;tag&gt;' doesn't have a matching end tag](https://docs.microsoft.com/en-us/dotnet/visual-basic/misc/bc42316)
* Content Source: [docs/visual-basic/misc/bc42316.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/misc/bc42316.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by mairaw** [comment]
Hi @manuela1994, can you show the code you're using that is causing this error?

**Comment by mairaw** [comment]
Closing due to the lack of response.
