### ISSUE TITLE
dotnet test from the solution directory

### ISSUE THREAD

**Issue by guardrex** [dotnet/docs#9785]
The current topic (for xUnit, perhaps NUnit and MSTest as well) remark that the `dotnet test` command must be executed from the test project's folder, which **was true** prior to the release of 15.9.

> From the PrimeService.Tests folder, ...

https://youtu.be/9Bhp8tw9wEw?t=818

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e39c2f1b-f41a-bdf9-2646-09379941453d
* Version Independent ID: 422811cb-6287-03af-ba8d-1daebee9744d
* Content: [Unit testing C# code in .NET Core using dotnet test and xUnit - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-with-dotnet-test?view=aspnetcore-2.2)
* Content Source: [docs/core/testing/unit-testing-with-dotnet-test.md](https://github.com/dotnet/docs/blob/master/docs/core/testing/unit-testing-with-dotnet-test.md)
* Product: **dotnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **wiwagn**

**Comment by Thraka** [comment]
Good catch!

**Comment by guardrex** [comment]
Props @RehanSaeed! 🎸
