### ISSUE TITLE
A problem regarding balancing group definitions

### ISSUE THREAD

**Issue by Alex0x1** [dotnet/docs#9789]
The balancing group definition uses name2 as a stack. The beginning character of each nested construct is placed in the group and in its Group.Captures collection. When the closing character is matched, its corresponding opening character is removed from the group, and the Captures collection is decreased by one. After the opening and closing characters of all nested constructs have been matched, name1 is empty.

Did the person who wrote this page mistaken name1 for name2? Cause name2 should be the one empty I think.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d124987-d837-b655-261e-e0871effcb7d
* Version Independent ID: 492a3233-0049-0678-1a4e-aed850e14bf4
* Content: [Grouping Constructs in Regular Expressions](https://docs.microsoft.com/en-us/dotnet/standard/base-types/grouping-constructs-in-regular-expressions#balancing_group_definition)
* Content Source: [docs/standard/base-types/grouping-constructs-in-regular-expressions.md](https://github.com/dotnet/docs/blob/master/docs/standard/base-types/grouping-constructs-in-regular-expressions.md)
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by mairaw** [comment]
Thanks for your feedback @Alex0x1. We'll have to investigate this issue. We've assigned it to a future sprint.
