### ISSUE TITLE
ProduceReferenceAssembly

### ISSUE THREAD

**Issue by paulomorgado** [dotnet/docs#9790]
This article should mention that the `/refout` switch can be set with the MSBuild property `ProduceReferenceAssembly` - see https://docs.microsoft.com/en-us/visualstudio/msbuild/common-msbuild-project-properties

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19cfe451-fe25-39c9-cf32-f5a434008a01
* Version Independent ID: 03a35576-ad5f-1c32-c158-cd710b47df9c
* Content: [-refout (C# Compiler Options)](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/refout-compiler-option)
* Content Source: [docs/csharp/language-reference/compiler-options/refout-compiler-option.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/refout-compiler-option.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by jwwicks** [comment]
@BillWagner I'll take on this update

**Comment by BillWagner** [comment]
Thanks @jwwicks.

It's yours.
