### ISSUE TITLE
Control Not Shown in Toolbox

### ISSUE THREAD

**Issue by regal60740** [dotnet/docs#9791]
When I get to this step: "Find the new tab called DebugControlLibrary Components and click to select it." The tab and control are not shown.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c87c96e6-c511-60c5-84a8-93762499c5d7
* Version Independent ID: 24faa21d-a6b8-5626-1979-542c08b5a8f4
* Content: [Walkthrough: Debugging Custom Windows Forms Controls at Design Time](https://docs.microsoft.com/en-us/dotnet/framework/winforms/controls/walkthrough-debugging-custom-windows-forms-controls-at-design-time)
* Content Source: [docs/framework/winforms/controls/walkthrough-debugging-custom-windows-forms-controls-at-design-time.md](https://github.com/dotnet/docs/blob/master/docs/framework/winforms/controls/walkthrough-debugging-custom-windows-forms-controls-at-design-time.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by regal60740** [comment]
Also, I'm not seeing instructions for a reference to DebugControlLibrary project.

**Comment by regal60740** [comment]
I was able to add the control by right clicking on the toolbox and browsing to the assembly for the control.

**Comment by regal60740** [comment]
When I get to this step: "Open Form1 in the Forms Designer and select the DebugControl control.", I can't get to the DebugControl. Visual Studio hits the break point in the debugging instance and won't let me get to the other instance. It just keeps pulling me back to the debugging instance.

**Comment by beanmf** [comment]
The instruction "Find the new tab called DebugControlLibrary Component" is unclear.  Visual Studio has innumerable tabs.  Please include where to look for this.

**Comment by ardalis** [comment]
@tdykstra This isn't related to ASP.NET Core - can you remove the guide - ASP.NET Core web apps label?

**Comment by regal60740** [comment]
I retired last summer. I will no longer be working on this. Thanks.
