### ISSUE TITLE
vh,k

### ISSUE THREAD

**Issue by VaraneFC** [dotnet/docs#9797]
hv,v

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94ed0851-104b-e65b-21bb-e59541e2b113
* Version Independent ID: 9c6481ef-659e-a7d3-e8a8-05dcc5f48a7c
* Content: [Implicit conversion from '&lt;typename1&gt;' to '&lt;typename2&gt;' in copying the value of 'ByRef' parameter '&lt;parametername&gt;' back to the matching argument.](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/error-messages/implicit-conversion-from-typename1-to-typename2-in-copying#to-correct-this-error)
* Content Source: [docs/visual-basic/language-reference/error-messages/implicit-conversion-from-typename1-to-typename2-in-copying.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/language-reference/error-messages/implicit-conversion-from-typename1-to-typename2-in-copying.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by mairaw** [comment]
Closing due to the lack of actual feedback.
