### ISSUE TITLE
code does not compile

### ISSUE THREAD

**Issue by Powerhelmsman** [dotnet/docs#9801]
This issue was submitted by @bugaevski from https://github.com/MicrosoftDocs/feedback/issues/991. 
Please contact the user for more details. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8056ac34-1796-8082-572a-bb75f2af6395
* Version Independent ID: f382bce9-6e5b-cb9f-7e01-e2f55786b042
* Content: [How To: Build Claims-Aware ASP.NET Web Forms Application Using WIF](https://docs.microsoft.com/en-us/dotnet/framework/security/how-to-build-claims-aware-aspnet-web-forms-app-using-wif)
* Content Source: [docs/framework/security/how-to-build-claims-aware-aspnet-web-forms-app-using-wif.md](https://github.com/dotnet/docs/blob/master/docs/framework/security/how-to-build-claims-aware-aspnet-web-forms-app-using-wif.md)
* Product: **dotnet-framework**
* GitHub Login: @BrucePerlerMS
* Microsoft Alias: **dotnetcontent**

**Comment by nzhong168** [comment]
Just add following block into the Default.aspx.cs, it does the mappings. It then works.
 public partial class _Default
    { 
        protected global::System.Web.UI.WebControls.Label signedIn;
        protected global::System.Web.UI.WebControls.Label claimType;
        protected global::System.Web.UI.WebControls.Label claimValue;
        protected global::System.Web.UI.WebControls.Label claimValueType;
        protected global::System.Web.UI.WebControls.Label claimSubjectName;
        protected global::System.Web.UI.WebControls.Label claimIssuer;
    }

Norman Zhong

**Comment by mairaw** [comment]
The WIF content hasn't been maintained for a long time and has now been archived as-is. Apologies for the inconvenience.
