### ISSUE TITLE
when type.property==0 are poor examples

### ISSUE THREAD

**Issue by DickBaker** [dotnet/docs#9804]
in ComputeArea_Version4 [and others] there are various tests is some property of the matched type equals zero, and in this case the constant zero is returned. I dislike such examples becasuse
1. the when condition code is likely more expensive than the simple expression specific to particular shape
 (if that property is zero the the expression result will also be zero)
2. having such conditions complicates the code readability to no useful benefit
3. the "0" literal constants should have the suffix to indicate double literal
 (whilst possible the jit optimisation will do that downstream, imho an explicit indicator is preferable)

so I suggest the content writers invent better examples that have some demonstrable payback
 (my code-smell hackles went on immediate overload and I suspect many other devs would be equally repulsed!)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1f2a2fe-8279-e6b3-93e8-33398167655f
* Version Independent ID: 35191215-988f-3700-1f85-4751711f692e
* Content: [Pattern Matching - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/pattern-matching)
* Content Source: [docs/csharp/pattern-matching.md](https://github.com/dotnet/docs/blob/master/docs/csharp/pattern-matching.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
I agree. I'm working on #8205 to re-work this article. I'll close this as a duplicate.

#8205 should be completed this month.
