### ISSUE TITLE
Horrible grammar

### ISSUE THREAD

**Issue by frankhaugen** [dotnet/docs#9805]
The grammar in this article needs serious improvements 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e80fe2fd-cbdb-699e-0dbb-a0a310bd372c
* Version Independent ID: 266d08ae-344a-683b-11e2-143b704e21a8
* Content: [Open-source .NET library guidance](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/)
* Content Source: [docs/standard/library-guidance/index.md](https://github.com/dotnet/docs/blob/master/docs/standard/library-guidance/index.md)
* Product: **dotnet**
* GitHub Login: @JamesNK
* Microsoft Alias: **mairaw**

**Comment by rpetrusha** [comment]
Thanks for your feedback, @frankhaugen. Would you like to submit a pull request to improve the article? See the [Contributor's guide](https://github.com/dotnet/docs/blob/master/CONTRIBUTING.md) for more information.

**Comment by mairaw** [comment]
Closing due to the lack of response. We'd need more info on which parts of the article if you find horrible as well.
