### ISSUE TITLE
file or filename? Show file included docs in intellisense?

### ISSUE THREAD

**Issue by deap82** [dotnet/docs#9808]
In the example for using a separate xml file, the attribute `file` is used, but in the text after `filename` is used. It should be `file`.

Is there any way to get docs included this way to show up as "intellisense" in VS 2017, as it does when the comments are directly in the code file? For example when hovering a member at the point of use. It does not work for me when the doc is in a referenced xml file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39152ded-70ce-012d-ffc3-a8b1a78f3308
* Version Independent ID: 809078f6-169a-0ffe-5f33-d5a359aeefc5
* Content: [Documenting your code with XML comments](https://docs.microsoft.com/en-us/dotnet/csharp/codedoc)
* Content Source: [docs/csharp/codedoc.md](https://github.com/dotnet/docs/blob/master/docs/csharp/codedoc.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
You are correct @deap82 I've added this to our community contributor project, if you'd like to submit a PR for the fix. If not, we'll address along with other priorities.

**Comment by deap82** [comment]
@BillWagner I'm guessing your talking only about the docs error? What about my other question? :-)
