### ISSUE TITLE
Document PackageLicenseExpression

### ISSUE THREAD

**Issue by piksel** [dotnet/docs#9812]
The properties for outputting the new &lt;license type="..."&gt; nuget properties is missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb4428fc-215c-78e1-5ff0-fe73f7a08260
* Version Independent ID: 6741b1de-38a4-fbb1-d79d-acc47d549a2d
* Content: [Additions to the csproj format for .NET Core - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/csproj)
* Content Source: [docs/core/tools/csproj.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/csproj.md)
* Product: **dotnet-core**
* GitHub Login: @blackdwarf
* Microsoft Alias: **mairaw**

**Comment by manigandham** [comment]
The latest information is here: https://github.com/NuGet/Home/wiki/Packaging-License-within-the-nupkg#project-properties

**Comment by VaclavK** [comment]
IMHO I do not think the doco for PackageLicenseExpression is clear in the document following the link above from @manigandham

**Comment by Mizux** [comment]
Will be fixed by #9675
