### ISSUE TITLE
How to register an async call upon cancellation?

### ISSUE THREAD

**Issue by weitzhandler** [dotnet/docs#9815]
Hi,

I need to to be able to wait for users cancellation, and then call another 'clean-up' method, that is also asynchronous.

In the WebClient example [above](https://docs.microsoft.com/en-us/dotnet/standard/threading/cancellation-in-managed-threads#listening-by-registering-a-callback), a call to an async method is called without `async`/`await`.

What is the right way to register an async cancellation delegate?

I need to achieve the following (I highlighted my requirement with `/**/` comments.

```c#
using System;
using System.Net;
using System.Threading;

class Example
{
    static void Main()
    {
        CancellationTokenSource cts = new CancellationTokenSource();

        StartWebRequest(cts.Token);

        /**************************************************/
        // This is what I want to achieve, request cancellation,
        // and await cancellation completion
        await cts.CancelAsync();
        /**************************************************/
    }

    static void StartWebRequest(CancellationToken token)
    {
        WebClient wc = new WebClient();
        wc.DownloadStringCompleted += (s, e) => Console.WriteLine("Request completed.");

        // Cancellation on the token will 
        // call CancelAsync on the WebClient.

        /********************/
        // where RegisterAsync accepts a Func<Task> to be invoke upon cancellation
        // and execute its `Task` result asynchronously.
        token.RegisterAsync(() => await wc.CancelAsync());
        /*******************/

        Console.WriteLine("Starting request.");
        wc.DownloadStringAsync(new Uri("http://www.contoso.com"));
    }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51f5ff8f-7d37-af59-4b51-41de21d67b95
* Version Independent ID: ef30d618-f141-3943-b93b-ce697ca8991b
* Content: [Cancellation in Managed Threads](https://docs.microsoft.com/en-us/dotnet/standard/threading/cancellation-in-managed-threads#listening-by-registering-a-callback)
* Content Source: [docs/standard/threading/cancellation-in-managed-threads.md](https://github.com/dotnet/docs/blob/master/docs/standard/threading/cancellation-in-managed-threads.md)
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by Thraka** [comment]
I believe this article was written without async/await in mind. If you search for things related to async/await and WebClient you might find a more to-the-point answer. For example, https://stackoverflow.com/questions/13240915/converting-a-webclient-method-to-async-await shows a little. 

The last two answers in this post https://stackoverflow.com/questions/16195694/how-cancel-downloading-async show a few different ways, once shows how to do it a cancel without async/await.

I hope this gets you going. I'm going to close this issue as it's not specific about something in the article and you're wondering about async/await, something the article doesn't talk about 😄 

Cheers!

**Comment by weitzhandler** [comment]
@Thraka My question wasn't about web client at all. I was merely using your example.
My general request is that you implement documentation that demonstrates asynchronous cancellation of an ongoing asynchronous task (not-related to web-client).

**Comment by Thraka** [comment]
Ok sorry about misunderstanding.

This article doesn't use the async/await pattern, so it wouldn't be the appropriate place to document this. 

I think your question would be better asked in a forum like stackoverflow. I don't think this scenario is something we're going to cover unless a lot of people ask for it. That said, why doesn't `token.Register(wc.CancelAsync);` work?

**Comment by weitzhandler** [comment]
@Thraka thanks for your kind reply.

`CancelAsync` is a `Task`, whereas `token.Register` accepts a synchronous `Action`.

**Comment by Thraka** [comment]
I coded this up and `CancelAsync` isn't a task, it's just a normal method. The name threw me at first too, but the documentation for it says `Cancels a pending asynchronous operation.` which I think means it cancels the `DownloadStringAsync` method. The signature fits with `token.Register` and the code compiles fine for me.

Are you seeing something different?

**Comment by weitzhandler** [comment]
@Thraka I know, I'm dealing with an async method that returns `Task`, and I'm looking for a means to have the cancellation method asynchronous as well.

**Comment by Thraka** [comment]
I just dont think I understand why you want to do this. The cancel is already running in a different thread from your main one, so why do you need to have a 3rd thread just for canceling?

Anyway, if you learn more about how the `Task` type works, you can create any task you want from any code and have it run. Use `Task.Factory.StartNew`.

I think you should ask this question in a forum/stackoverflow where you can discuss and get answers from multiple people. 😄
