### ISSUE TITLE
Program Language Selection

### ISSUE THREAD

**Issue by francisco-chavez** [dotnet/docs#9819]
What's the point of having that Language Selection drop-down at the top if it's going to be giving us both C# and VB code samples. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0dc39f7-b153-a46c-3b88-07c8ed2c71bc
* Version Independent ID: 78a14535-9703-e2af-4451-783a7c4c10be
* Content: [Create a WPF application in Visual Studio](https://docs.microsoft.com/en-us/dotnet/framework/wpf/getting-started/walkthrough-my-first-wpf-desktop-application)
* Content Source: [docs/framework/wpf/getting-started/walkthrough-my-first-wpf-desktop-application.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/getting-started/walkthrough-my-first-wpf-desktop-application.md)
* Product: **dotnet-framework**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by imba-tjd** [comment]
It can not distinguish C# XAML from VB XAML, but it's valid for normal c# and vb codes.
