### ISSUE TITLE
I have no idea what this doc is saying.

### ISSUE THREAD

**Issue by LJ9999** [dotnet/docs#9821]
Why does my application require an Association Set? I'm writing EF applications just fine and they are replete with Association and Navigation properties, all without knowledge of an Association Set. Why is that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e9eca91-e9dd-cba3-1705-7ae86074531f
* Version Independent ID: f50056a8-3889-be68-e103-bfb9f3eca3cc
* Content: [association set](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/association-set)
* Content Source: [docs/framework/data/adonet/association-set.md](https://github.com/dotnet/docs/blob/master/docs/framework/data/adonet/association-set.md)
* Product: **dotnet-framework**
* GitHub Login: @douglaslMS
* Microsoft Alias: **douglasl**

**Comment by mairaw** [comment]
@divega can you help with this question? Is there any doc if you think would be useful to link that explains this concept better?
