### ISSUE TITLE
So what does navigation do for me?

### ISSUE THREAD

**Issue by LJ9999** [dotnet/docs#9822]
You described the setup. But what on earth would I use this for? I can't read your mind. Don't assume people know what you know when writing these docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c68a641-b25c-5d34-ace8-01efccc90cfe
* Version Independent ID: 4c80c392-2eeb-e456-5b3c-a3d6443c2a06
* Content: [navigation property](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/navigation-property)
* Content Source: [docs/framework/data/adonet/navigation-property.md](https://github.com/dotnet/docs/blob/master/docs/framework/data/adonet/navigation-property.md)
* Product: **dotnet-framework**
* GitHub Login: @douglaslMS
* Microsoft Alias: **douglasl**

**Comment by mairaw** [comment]
Thanks for your feedback @LJ9999. I've created PR #10107 to add a link to the following topic that explains navigation properties among other things: https://docs.microsoft.com/en-us/ef/ef6/fundamentals/relationships
