### ISSUE TITLE
Bug in Announcement sample?

### ISSUE THREAD

**Issue by candritzky** [dotnet/docs#9826]
I think it should read
    serviceHost.Description.Behaviors.Add(discoveryBehavior);
instead of
    serviceHost.Description.Behaviors.Add(new ServiceDiscoveryBehavior());

Otherwise it will ignore the UdpAnnouncementEndpoint which is later added to the discoveryBehavior instance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0d5e1a9-837b-dfc6-3be6-6bbfedffc521
* Version Independent ID: 44c731ab-1b79-4522-39e8-deba3a03e216
* Content: [WCF Discovery Overview](https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/wcf-discovery-overview)
* Content Source: [docs/framework/wcf/feature-details/wcf-discovery-overview.md](https://github.com/dotnet/docs/blob/master/docs/framework/wcf/feature-details/wcf-discovery-overview.md)
* Product: **dotnet-framework**
* GitHub Login: @Lxiamail
* Microsoft Alias: **wcfsrvt**

**Comment by Thraka** [comment]
You're right! Thank you for filing this bug. I'll add it to the backlog and add flag the community to fix it. If you would like, you too could quickly fix it by editing the article. See the [contributors guide](https://review.docs.microsoft.com/en-us/help/contribute/?branch=master) for more information about making a quick edit.
