### ISSUE TITLE
Scope of pattern matched variable inside if statements 

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/docs#9834]
> If expr is true and is is used with an if statement, varname is assigned and has local scope within the if statement only.

Is this still true? While reviewing code I noticed that the scope of the assigned variable goes beyond the if statement:
```c#
        internal async Task<bool> TryServeCachedResponseAsync(ResponseCachingContext context, IResponseCacheEntry cacheEntry)
        {
            if (!(cacheEntry is CachedResponse cachedResponse))
            {
                return false;
            }

            context.CachedResponse = cachedResponse;
            ...
        }
```
The above code compiles and seems to work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3126aaa9-8f5f-04f3-2d75-96477b6273cd
* Version Independent ID: 3f4b3eac-11eb-2dd6-4f27-b24537367288
* Content: [is - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/is#feedback)
* Content Source: [docs/csharp/language-reference/keywords/is.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/is.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Good catch @JunTaoLuo Your code is correct: `cachedResponse` is **definitely assigned if false** after the `if` block. That means it is definitely assigned in this example (because of the `return` inside the `if`.

Scope extends beyond the `if`, in this example.
