### ISSUE TITLE
Please rename the regular method

### ISSUE THREAD

**Issue by GrantMeStrength** [dotnet/docs#9835]
Using the name "Double" is confusing e.g. static double Double(double input) has three "doubles" in a row. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9eba9bb-8296-b41c-f8f3-4cebe488722e
* Version Independent ID: 95b1655b-a782-02b1-ca0c-14f1b95bf5a5
* Content: [delegate - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/delegate)
* Content Source: [docs/csharp/language-reference/keywords/delegate.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/delegate.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by NextTurn** [comment]
Fixed in dotnet/samples#584

**Comment by BillWagner** [comment]
closing because it was fixed as noted above.
