### ISSUE TITLE
Dokyoomintashun? I'm not playin' no mo'. Get Down To O'Shack Hennessy's Office...

### ISSUE THREAD

**Issue by dhmorrison** [dotnet/docs#9840]
**The project was restored using Microsoft.NETCore.App version blah, but with current settings, version blah would be used instead**

Really?? I am saddened that this is the best guidance you can provide.  Why do you struggle so to provide useful troubleshooting information?  

_The cream RISES to the top._

https://youtu.be/rWrlAmT4jyA

Oh yeah, Nothing Means NOTHING. Bad documentation means NOTHING.  ...Zero.

**There is nobody who does troubleshooting better than the following.** Here is the kind of info we in the development community need when we get such bizarre compilation errors: https://stackoverflow.com/questions/51642172/the-project-was-restored-using-microsoft-netcore-app-version-2-1-0-but-with-cur

We really don't need ```Self-contained deployment roll forward.``` Nope.  What's the point of this information?  Come on man.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a901ae9f-cc78-b5de-a031-b4671c7a85ac
* Version Independent ID: 89276cf0-167d-c108-f9d6-f5bfe1317851
* Content: [Runtime roll forward for .NET Core self-contained app deployments. - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/deploying/runtime-patch-selection)
* Content Source: [docs/core/deploying/runtime-patch-selection.md](https://github.com/dotnet/docs/blob/master/docs/core/deploying/runtime-patch-selection.md)
* Product: **dotnet-core**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment]
It seems this error comes from the roll forward behavior targeting one version and then the dependencies are now version-desynced.

Yes? I think we should improve this article to really call it out. People are finding in search because of the error message listed in the article.

**Comment by Zhentar** [comment]
We aren't finding it in search - the error message tells us to go to http://aka.ms/dotnet-runtime-patch-selection for more information, which sends us here
