### ISSUE TITLE
Duplicated sentence

### ISSUE THREAD

**Issue by kims07231992** [dotnet/docs#9844]
This paragraph used twice.

The API Gateway products usually act like a reverse proxy for ingress communication, where you can also filter the APIs from the internal microservices plus apply authorization to the published APIs in this single tier.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5a3c5f2-59c1-d0f1-15f5-446f81d36d2b
* Version Independent ID: f1beb409-3b01-3cf0-f81e-8d4d2397ae6d
* Content: [The API gateway pattern versus the direct client-to-microservice communication](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/architect-microservice-container-applications/direct-client-to-microservice-communication-versus-the-api-gateway-pattern)
* Content Source: [docs/standard/microservices-architecture/architect-microservice-container-applications/direct-client-to-microservice-communication-versus-the-API-Gateway-pattern.md](https://github.com/dotnet/docs/blob/master/docs/standard/microservices-architecture/architect-microservice-container-applications/direct-client-to-microservice-communication-versus-the-API-Gateway-pattern.md)
* Product: **dotnet**
* GitHub Login: @CESARDELATORRE
* Microsoft Alias: **wiwagn**

**Comment by kims07231992** [comment]
Sorry, it's not duplicated but the author wrote a quite similar sentence twice.

 These products act like a reverse proxy for ingress communication, where you can also filter the APIs from the internal microservices and apply authorization to the published APIs in this single tier. 

The API Gateway products usually act like a reverse proxy for ingress communication, where you can also filter the APIs from the internal microservices plus apply authorization to the published APIs in this single tier.

**Comment by nishanil** [comment]
hey! @kims07231992 Great catch! Thank you for letting us know.
@mairaw I've updated the .NET 2.2 PR https://github.com/dotnet/docs/pull/9873 to include this fix.

**Comment by mvelosop** [comment]
Closing this issue as the PR fixing it has already been merged.
