### ISSUE TITLE
"A constant or type declaration is implicitly a static member."

### ISSUE THREAD

**Issue by volkan-yazilim** [dotnet/docs#9849]
Kindly asking for more detailed explanation or a sample.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d97db038-978f-fff3-4e68-110619dc86f2
* Version Independent ID: 3c933595-0ec1-2632-55c9-934af6e72f5d
* Content: [static modifier - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/static#example-1)
* Content Source: [docs/csharp/language-reference/keywords/static.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/static.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by jj-itventure** [comment]
Where was the clarity of this point in the documentation specifically?
