### ISSUE TITLE
It would be great if every code in docs get runned like here.

### ISSUE THREAD

**Issue by volkan-yazilim** [dotnet/docs#9856]
It is nice to play with code without worry.
If it is possible, of course.
Thanks for your efforts.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 039d1d42-5786-1d6b-92b3-cb8fbea5a78c
* Version Independent ID: f62b2fcf-1b18-77a1-dae5-b821e681b110
* Content: [while - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/while)
* Content Source: [docs/csharp/language-reference/keywords/while.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/while.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
Thanks for your feedback @volkan-yazilim and we're glad to hear that you like the interactive content. We're planning to expand that feature into more topics.
