### ISSUE TITLE
Should Include a "Grouping Constructs" Topic.

### ISSUE THREAD

**Issue by JediSQL** [dotnet/docs#9861]
The match operators (-match and -notmatch) (https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_comparison_operators?view=powershell-6) make use of "Grouping Constructs" (https://docs.microsoft.com/en-us/dotnet/standard/base-types/regular-expression-language-quick-reference#grouping-constructs) add elements to the $Matches array. This page should describe grouping constructs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16d4698e-4220-c422-a554-8a481803d240
* Version Independent ID: f0e3b82a-8d81-ad9e-97fc-efb92f7d0d38
* Content: [Regular Expression Language - Quick Reference](https://docs.microsoft.com/en-us/dotnet/standard/base-types/regular-expression-language-quick-reference#grouping-constructs)
* Content Source: [docs/standard/base-types/regular-expression-language-quick-reference.md](https://github.com/dotnet/docs/blob/master/docs/standard/base-types/regular-expression-language-quick-reference.md)
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by JediSQL** [comment]
oops, wrong RegEx topic. please ignore.

**Comment by rpetrusha** [comment]
There is a Grouping Constructs topic at <https://docs.microsoft.com/en-us/dotnet/standard/base-types/grouping-constructs-in-regular-expressions>? Were you expecting something different, @JediSQL.

In the meantime, closing this issue as Not Repro.
