### ISSUE TITLE
VB.NET code lacking

### ISSUE THREAD

**Issue by chould58** [dotnet/docs#9862]
Great example.
But I'm disappointed about VB.NET code lacking for this example.
I notice there is a lot of docs in your database, where you show example with C# code only .
With this fact, are you in the act to tell us you will be relinquishing VB.NET development ?

A worried Basic developer from 70's,

Christian

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58339b81-2a36-2bb4-2fab-8d01596d5a70
* Version Independent ID: 75bc38d0-eba9-ea58-4cc5-ba38d90c613e
* Content: [Walkthrough: Display Data from a SQL Server Database in a DataGrid Control](https://docs.microsoft.com/en-us/dotnet/framework/wpf/controls/walkthrough-display-data-from-a-sql-server-database-in-a-datagrid-control)
* Content Source: [docs/framework/wpf/controls/walkthrough-display-data-from-a-sql-server-database-in-a-datagrid-control.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/controls/walkthrough-display-data-from-a-sql-server-database-in-a-datagrid-control.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by Thraka** [comment]
Hello! This article does have VB.NET examples. There is a language switcher on the top-right of the page where you can change from C# to VB.

![image](https://user-images.githubusercontent.com/2672110/61476312-99370900-a941-11e9-8bd8-75c50ee2a610.png)

I'm going to close this issue. Cheers!
