### ISSUE TITLE
Business usecase is missing

### ISSUE THREAD

**Issue by suhastjs** [dotnet/docs#9863]
All most all pages explain how to use it. Can we include one business case on when to use this feature? it will be helpful in deeper understanding. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f86ebf5-b5c0-324a-43df-c17015729d01
* Version Independent ID: 8ce4ad4a-3dbd-42dc-bae3-230900097299
* Content: [What's new in C# 7.2](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-7-2#safe-efficient-code-enhancements)
* Content Source: [docs/csharp/whats-new/csharp-7-2.md](https://github.com/dotnet/docs/blob/master/docs/csharp/whats-new/csharp-7-2.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
That's a good point @suhastjs 

Many of the business cases and scenarios are surfaced throughout the docs. These articles are overviews of the new features, and should point people to those tutorials.

**Comment by BillWagner** [comment]
The `dotnet try` tutorials referred to in #12975 address this.

Closing.
