### ISSUE TITLE
Wrong ID for ContentionStop event

### ISSUE THREAD

**Issue by chrisnas** [dotnet/docs#9864]
Change the ContentionStop event ID from 81 to 91
look at https://github.com/dotnet/coreclr/blob/master/src/vm/ClrEtwAll.man#L2874

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1857c71e-e89a-e7c7-9633-4c1b6e731983
* Version Independent ID: 654e5569-24d2-4656-e65f-140d1dd38b6e
* Content: [Contention ETW Events](https://docs.microsoft.com/en-us/dotnet/framework/performance/contention-etw-events)
* Content Source: [docs/framework/performance/contention-etw-events.md](https://github.com/dotnet/docs/blob/master/docs/framework/performance/contention-etw-events.md)
* Product: **dotnet-framework**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Thanks for your feedback @chrisnas. I've opened PR #10103 to fix this.

You can also directly fix issues like that if you're interested, as explained in https://docs.microsoft.com/en-us/contribute/#quick-edits-to-existing-documents.
