### ISSUE TITLE
Does Architecture parameter support "arm"?

### ISSUE THREAD

**Issue by RickyLin** [dotnet/docs#9868]
The document said architecture parameter supports `auto`, `x64` and `x86`, I wonder if it supports `arm`? I want to install .net core runtime via powershell on Windows 10 IoT and Raspberry Pi 2.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2e484a9-5e0c-eb3e-1413-7b507c4fa07d
* Version Independent ID: 5bc7caa5-f1c2-d7d5-fe02-80c65cca9672
* Content: [dotnet-install scripts - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script#see-also)
* Content Source: [docs/core/tools/dotnet-install-script.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-install-script.md)
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
@johnbeisner can you confirm?

This is same list of supported values as listed at https://github.com/dotnet/cli/blob/master/scripts/obtain/dotnet-install.ps1#L35.

However, the switch at https://github.com/dotnet/cli/blob/master/scripts/obtain/dotnet-install.ps1#L161 seems to indicate the list should actually be
auto, amd64, x86, arm, and arm64.

**Comment by johnbeisner** [comment]
@mairaw 
You are correct - the help should be updated: https://github.com/dotnet/cli/pull/10619
