### ISSUE TITLE
Unavailable additional resources

### ISSUE THREAD

**Issue by sylvain-guillet** [dotnet/docs#9870]
Links provided to VaughnVernon web site are unavailable.
Howewer you can use these links from ddd community :
http://dddcommunity.org/wp-content/uploads/files/pdf_articles/Vernon_2011_1.pdf
http://dddcommunity.org/wp-content/uploads/files/pdf_articles/Vernon_2011_2.pdf
http://dddcommunity.org/wp-content/uploads/files/pdf_articles/Vernon_2011_3.pdf

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2913c197-6b53-a39d-8de7-c9fc7d3de767
* Version Independent ID: 43ee54f5-6812-2661-08d6-2314a86e301a
* Content: [Designing a microservice domain model](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/microservice-ddd-cqrs-patterns/microservice-domain-model)
* Content Source: [docs/standard/microservices-architecture/microservice-ddd-cqrs-patterns/microservice-domain-model.md](https://github.com/dotnet/docs/blob/master/docs/standard/microservices-architecture/microservice-ddd-cqrs-patterns/microservice-domain-model.md)
* Product: **dotnet**
* GitHub Login: @CESARDELATORRE
* Microsoft Alias: **wiwagn**

**Comment by Thraka** [comment]
Thank you for notifying us. I'll assign this to the author.

@CESARDELATORRE  ping.

**Comment by mairaw** [comment]
@mvelosop can you take a look at this feedback?

**Comment by mvelosop** [comment]
Hi @mairaw,

I just emailed Vaughn Vernon to check if this is temporal or he prefers to update the links to some other site.

Anyway, I think we'll wait for a few days for an answer or will use the suggested links otherwise.

**Comment by CESARDELATORRE** [comment]
The above links pointing to http://dddcommunity.org are good. They are the same articles and probably, http://dddcommunity.org is safe long term place to point to. 👍 
We'll update it as soon as possible.

**Comment by mvelosop** [comment]
Done!
