### ISSUE TITLE
Add framework-dependent executable deployment (FDE) instructions 

### ISSUE THREAD

**Issue by 4Matt** [dotnet/docs#9879]
Please add framework-dependent executable (FDE)-specific instructions to this 'Deploy apps with CLI tools' page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ee36626-0fc2-20d8-81c5-a3cd212244b2
* Version Independent ID: 044ba93c-9ad9-80c7-dc5c-27a80c9bd921
* Content: [Deploy .NET Core apps with command-line interface (CLI) tools - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/deploying/deploy-with-cli)
* Content Source: [docs/core/deploying/deploy-with-cli.md](https://github.com/dotnet/docs/blob/master/docs/core/deploying/deploy-with-cli.md)
* Product: **dotnet-core**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by MadMathMike** [comment]
If there are any actions I can take to give this issue more visibility, let me know. I would really like to use this new feature (framework-dependent executable), but I have no idea how. I'll admit I _may_ be missing something obvious, but some explicit instructions would be very welcome.

**Comment by mairaw** [comment]
Thanks for your feedback @4Matt and @MadMathMike. I'm closing this as a duplicate of the following issue that we have triaged yesterday: https://github.com/dotnet/docs/issues/9728

**Comment by danstur** [comment]
@MadMathMike I had the same problem and created [this](https://stackoverflow.com/questions/54075591/how-to-create-framework-dependent-executables-with-net-core-2-2) StackOverflow post and answered my own question after figuring it out.

Should be a good start for getting FDEs to work.

**Comment by MadMathMike** [comment]
That post was exactly what I needed! Thanks, @danstur! And thanks, @mairaw, for pointing me to the other issue. I'm glad it's being work on. :-)
