### ISSUE TITLE
A better approach might be to use the read-to-use class ObjectPool coming in Microsoft.Extensions

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet/docs#9880]
ObjectPool class, part of “Microsoft.Extensions”:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.objectpool.objectpool-1?view=aspnetcore-2.2 

Or also another new class is System.Buffers.ArrayPool<T>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e05147c-bb78-2dbf-c6a6-b296f4407871
* Version Independent ID: 88893e2c-575f-9c30-1aa3-d1158efac25c
* Content: [How to: Create an Object Pool by Using a ConcurrentBag](https://docs.microsoft.com/en-us/dotnet/standard/collections/thread-safe/how-to-create-an-object-pool)
* Content Source: [docs/standard/collections/thread-safe/how-to-create-an-object-pool.md](https://github.com/dotnet/docs/blob/master/docs/standard/collections/thread-safe/how-to-create-an-object-pool.md)
* Product: **dotnet**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
@BillWagner would this belong in the [Async, await, tasks, and parallel programming in .NET](https://github.com/dotnet/docs/projects/42) project?

**Comment by BillWagner** [comment]
@mairaw Yes. I added it to that project.

**Comment by bewarusman** [comment]
I personally use this code in production. But there is no limit. Can we limit the number of class instances per pool?

**Comment by CESARDELATORRE** [comment]
Btw, I wrote this Blog Post using ObjectPool with ML.NET Prediction Engine:

Could be interesting as a good case for Object Pooling:
https://devblogs.microsoft.com/cesardelatorre/how-to-optimize-and-run-ml-net-models-on-scalable-asp-net-core-webapis-or-web-apps/
