### ISSUE TITLE
Or also another new class is System.Buffers.ArrayPool<T>

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet/docs#9881]
A better approach might be to use the read-to-use class System.Buffers.ArrayPool&lt;T&gt; 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e05147c-bb78-2dbf-c6a6-b296f4407871
* Version Independent ID: 88893e2c-575f-9c30-1aa3-d1158efac25c
* Content: [How to: Create an Object Pool by Using a ConcurrentBag](https://docs.microsoft.com/en-us/dotnet/standard/collections/thread-safe/how-to-create-an-object-pool)
* Content Source: [docs/standard/collections/thread-safe/how-to-create-an-object-pool.md](https://github.com/dotnet/docs/blob/master/docs/standard/collections/thread-safe/how-to-create-an-object-pool.md)
* Product: **dotnet**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Edited issue #9880 to include the second case, Closing this as duplicate.
