### ISSUE TITLE
Suggested improvements

### ISSUE THREAD

**Issue by Neutrino-Sunset** [dotnet/docs#9884]
The section '.NET Standard' explicitly states that target framework 'netstandard' implicitly references NETStandard.Library, but the section '.NET Core Application' doesn't state that target framework 'netcoreapp' implicitly references anything at all, I would have thought that would have been one of the key points that this document was supposed to clarify.

Also I believe there are differences in how framework dependent applications and self contained applications are able to use metapackages related to the functioning of the Dotnet Core Store, a warning about those differences and a link to a detailed description of them would be very useful indeed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b8166ec-177f-67e5-7e98-2190ea82e0b0
* Version Independent ID: d6573a5f-4eb4-21c1-4d4f-50ef0f4723ae
* Content: [Packages, metapackages and frameworks - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/packages)
* Content Source: [docs/core/packages.md](https://github.com/dotnet/docs/blob/master/docs/core/packages.md)
* Product: **dotnet-core**
* GitHub Login: @richlander
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment]
Valid point. This is kind of mentioned at the start, but it's good to reiterate here. Thank you for the issue.
