### ISSUE TITLE
"Often, the set accessor consists of a single statement that returns a value, "

### ISSUE THREAD

**Issue by volkan-yazilim** [dotnet/docs#9885]
Please, check this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a05cb6c-7bdd-0777-7228-49aab2cb2894
* Version Independent ID: 6039d03d-7247-cfca-7d89-2af7c301a026
* Content: [set keyword - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/set)
* Content Source: [docs/csharp/language-reference/keywords/set.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/set.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by rpetrusha** [comment]
I've opened PR #9895 to change "returns" to "assigns", @volkan-yazilim
