### ISSUE TITLE
Update CLI ref for 3.0/3.1

### ISSUE THREAD

**Issue by Thraka** [dotnet/docs#9893]
CLI reference hasn't been updated for 3.0. This should be updated.

This issue applies to all dotnet command articles.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ba6c9b5-64cb-1dc6-21d0-ad8f0a1185fe
* Version Independent ID: 0f6c658c-b477-2d2c-2a9a-d74f6ae38d3f
* Content: [dotnet command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet?tabs=netcore21#environment-variables)
* Content Source: [docs/core/tools/dotnet.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment]
Per request, moving to @mairaw since she is doing the 2.2 CLI ref

**Comment by jbe2277** [comment]
Please, update the reference to include .NET Core 3.1 as well.
