### ISSUE TITLE
Make default values more obvious

### ISSUE THREAD

**Issue by Const-me** [dotnet/docs#9894]
The article has a title "Default Marshaling for Strings".

In the content, it lists options, but fails to say which one is the default, for all cases except COM interfaces. What's the default for Platform Invoke? What's the default for structures? Does the default depend on OS? No answers...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25d350b8-a514-6c13-a091-0952a8fc0610
* Version Independent ID: 3ee9bbfd-2060-d97f-c2f1-12867899034a
* Content: [Default Marshaling for Strings](https://docs.microsoft.com/en-us/dotnet/framework/interop/default-marshaling-for-strings#cpcondefaultmarshalingforstringsanchor5)
* Content Source: [docs/framework/interop/default-marshaling-for-strings.md](https://github.com/dotnet/docs/blob/master/docs/framework/interop/default-marshaling-for-strings.md)
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by NextTurn** [comment]
@rpetrusha 

What about *Customizing string marshaling* (like [Customizing parameter marshaling](https://docs.microsoft.com/dotnet/standard/native-interop/customize-parameter-marshalling))? These articles not just focus on the default behaviors.

**Comment by Const-me** [comment]
@NextTurn Thanks, at least title is more relevant now.

But I would really like to have the default marshalling documented somewhere. Don’t care in which article, but the exact behavior is quite important.

From experiments, I know the defaults are different based on everything: OS and platform (tested on windows .NET 4.7+ and ARM Linux .NET core 2.0+), and also the location (dll/so imported functions, IUnknown interfaces, structures, unmanaged function pointers).

These experiments are time consuming and not particularly reliable. E.g. impossible to distinguish BSTR from LPCWSTR, they point to the same data the only difference is memory management.

While it’s possible to always specify the format manually, for larger API surface, it makes the C# part of the interop harder to read and support.

**Comment by NextTurn** [comment]
Well... This article is in .NET Framework Guide so it only applies to .NET Framework on Windows :(

**Comment by Const-me** [comment]
@NextTurn The defaults are different in every case, and undocumented, even on Windows.

**Comment by NextTurn** [comment]
Do you want to take a look @jkoritzinsky ?

**Comment by jkoritzinsky** [comment]
@Const-me the other two tables on the referenced page do annotate which type is the default, but because of sizing/formatting, the `(default)` notation is just below the `UnmanagedType.LPStr` in the same cell instead of next to it.
