### ISSUE TITLE
Different views on the effect of the Thread.Start call on a thread state

### ISSUE THREAD

**Issue by pkulikov** [dotnet/docs#9896]
The dotnet/dotnet-api-docs#1527 updated the [ThreadState enum](https://docs.microsoft.com/en-us/dotnet/api/system.threading.threadstate?view=netframework-4.7.2) reference such that the conceptual [Managed Thread States](https://docs.microsoft.com/en-us/dotnet/standard/threading/managed-thread-states) article now duplicates the API reference page and can be removed.

Almost duplicates, though.

There is one difference between the articles that should be resolved. This is the description of the behavior of the `Thread.Start` method.

The [conceptual docs](https://docs.microsoft.com/en-us/dotnet/standard/threading/managed-thread-states) say:
> The thread remains in the `Unstarted` state until it is moved into the started state by the operating system. Calling `Start` lets the operating system know that the thread can be started; it does not change the state of the thread.

And the table (at right: the *resulting* thread state of the action mentioned at left):
![image](https://user-images.githubusercontent.com/15279990/50859977-0e26f600-1395-11e9-97b8-3d4f403b1298.png)

The [API reference](https://docs.microsoft.com/en-us/dotnet/api/system.threading.threadstate?view=netframework-4.7.2#remarks) describes the result of the `Thread.Start` call differently:
![image](https://user-images.githubusercontent.com/15279990/50860122-665df800-1395-11e9-89e7-a92d1f8974b8.png)

The [API doc on `Thread.Start`](https://docs.microsoft.com/en-us/dotnet/api/system.threading.thread.start?view=netframework-4.7.2#System_Threading_Thread_Start) claims that `Thread.Start`
>Causes the operating system to change the state of the current instance to `Running`.

To my understanding, the conceptual article does not match the API docs. What docs describe the effect of the `Thread.Start` call correctly? If the API reference is correct, then this issue will be fixed with the removal of the conceptual docs article.

/cc: @rpetrusha

**Comment by pkulikov** [comment]
> the thread is in the `Unstarted` state until the OS schedules and starts it, at which point it transitions to the `Running` state

@rpetrusha to my understanding, that part is common for both variants.

What confuses me is *when* does `Thread.Start` return and what is the state of the thread then?

The API docs say that `Thread.Start` returns only after the thread started running (I guess that also means, it's in the `Running` state).

As for the conceptual docs, I've interpreted them as the `Thread.Start` call might return with the thread state still being `Unstarted` (based on this sentence with my emphasis: "**Calling `Start`** lets the operating system know that the thread can be started; it **does not change the state of the thread.**"). I'm afraid I might have misunderstood the conceptual docs.

**Comment by kouvel** [comment]
At the moment `Thread.Start` will wait for the actual thread to start and initialize. This is to detect OOM during initialization, which would be reported through the call to `Start` with an exception. Once the thread reaches a certain point, the `Unstarted` bit is removed from the thread state and `Thread.Start` waits for that change before returning. It is done like that so that `Thread.Start` does not return without exception when the OS did not have resources to start the thread, as in that case the user would have no way of knowing that the thread did not start.

**Comment by pkulikov** [comment]
@kouvel thanks a lot for the clarification.
@rpetrusha I think the API documentation is correct in its current wording, no changes required. The conceptual article can be just removed. I'll do that in the PR that will close this issue, then.

**Comment by rpetrusha** [comment]
Thanks, @kouvel. That sounds good, @pkulikov .
