### ISSUE TITLE
Any plans to support POS.Net with .net core?

### ISSUE THREAD

**Issue by productinfo** [dotnet/docs#9897]
What is the future of POS for .Net with .net core?

**Comment by mairaw** [comment]
@terrajobst @karelz are you guys familiar with POS.NET?

It seems that UWP has some POS support: https://docs.microsoft.com/en-us/uwp/api/Windows.Devices.PointOfService

**Comment by karelz** [comment]
Not familiar with POS.NET. No plans AFAIK cc @danmosemsft 
@productinfo what kind of support would you expect? What would be the value?

**Comment by productinfo** [comment]
Thank you for the link @mairaw
@mairaw @karelz @danmosemsft it seems future improvements of POS for .Net would be part of UWP windows device framework, not part of net core/iOT core.
But, is there a way to connect external hardware from net core application on linux/raspberry, which already works with windows using POS for .Net.

**Comment by karelz** [comment]
Isn't POS Windows specific? If yes, I would not expect that to light up on Linux.
We are investing into GPIO for Linux - would that help you?

**Comment by productinfo** [comment]
thanks for the info..
