### ISSUE TITLE
BigInteger example does not compile

### ISSUE THREAD

**Issue by 9ParsonsB** [dotnet/docs#9899]
the BigInterger example does not run via the ".NET Editor" with the Output:

(8,19): error CS0103: The name 'BigInteger' does not exist in the current context

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ae38fce-fc98-9420-6b0b-ceee4e885f2d
* Version Independent ID: f23035e0-f271-b48c-f9a9-8582be80b4ad
* Content: [Standard Numeric Format Strings](https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-numeric-format-strings#PFormatString)
* Content Source: [docs/standard/base-types/standard-numeric-format-strings.md](https://github.com/dotnet/docs/blob/master/docs/standard/base-types/standard-numeric-format-strings.md)
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by LadyNaggaga** [comment]
try.net does support BigInteger but, I believe the docs samples are pointing to scripting workspaces. Is that still the case @BillWagner ?

**Comment by BillWagner** [comment]
Adding @dend 

I think most of the docs samples still use the scripting workspace. Den can confirm / clarify.

**Comment by dendeli-msft** [comment]
That is correct - currently we are using the scripting workspace across the board. There is an effort that we are currently assessing to move to a model where we can provide more flexibility in code execution - it's something we need to collaborate with @LadyNaggaga's team on.

**Comment by bdcoder2** [comment]
With regard to the G format specifier for VB - If you copy and paste the code, the following compiler errors will be displayed:

error BC30037: Character is not valid.
error BC30037: Character is not valid.
