### ISSUE TITLE
Could you provide more command line samples?

### ISSUE THREAD

**Issue by juniormayhe** [dotnet/docs#9905]
It would be nice to have practical examples of how to read a specific appSettings.json, or appSettings.Debug.json, appSettings.Release.json... Also would be nice to know if we can pass command line arguments that could be read by tests at runtime

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61ca4064-7481-a263-60fc-c70127f2ad16
* Version Independent ID: 2878af44-8208-7bd8-46d4-3acda3e82ce0
* Content: [dotnet test command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-test?tabs=netcore21)
* Content Source: [docs/core/tools/dotnet-test.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-test.md)
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment]
Is appSettings.json a ASP.NET Core concept or a .NET Core concept?

**Comment by Rick-Anderson** [comment]
ASP.NET Core I think. See https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/index?view=aspnetcore-2.2#json-configuration-provider

**Comment by Thraka** [comment]
@juniormayhe Please let me know if this helps?

Also, regarding the command line arguments, does the `RunSettings arguments` section of the article have what you need? In general you pass on arguments to your app by putting ` -- ` at the end of whole core CLI command.

I'm going to close this issue for now. Thanks!
