### ISSUE TITLE
"WeightColumn" in Trainers

### ISSUE THREAD

**Issue by HarshitShukla** [dotnet/docs#9906]
I am working on the regression trainers for my Model. 
I have to tell my model to take priority on a few numerical columns and then take the rest numerical column to predict some value. I tried searching for an example of weight. I haven't found any example of weight. Can you please send some example or how to solve the above problem using ML.Net. 

If 'weight column' has some different purpose can you please explain it.
You can use my email 'harshit.shukla@medibuddy.in' If you require or convey any Information.

**Comment by mairaw** [comment]
@JRAlexander @luisquintanilla - FYI on an issue I just tagged with the ML.NET guide

**Comment by luisquintanilla** [comment]
Hi @HarshitShukla 

In your trainers, you can use the exampleWeightColumnName to provide custom weights for training at the instance or observation level. ML.NET does not support applying weights to the individual columns for training. However, you may want to consider using a CustomMapping transform at the beginning of your pipeline to achieve the same effect. 

Here is the documentation to the CustomMapping transform along with some samples.

https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.custommappingcatalog.custommapping?view=ml-dotnet#Microsoft_ML_CustomMappingCatalog_CustomMapping__2_Microsoft_ML_TransformsCatalog_System_Action___0___1__System_String_Microsoft_ML_Data_SchemaDefinition_Microsoft_ML_Data_SchemaDefinition_

Closing this issue.

**Comment by luisquintanilla** [comment]
Referencing issue on dotnet/machinelearning#884 for additional information
