### ISSUE TITLE
Links to reference material needed.

### ISSUE THREAD

**Issue by Gammerz26** [dotnet/docs#9907]
All the expressions in the list need links to the relevant reference material. As this is only an overview with the briefest of details, programmers may need to look into more detail for new concepts (e.g. delegates, lambda expressions, the 'await' command).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58d7bc71-c69e-55a3-2f4c-f3139b4b0e82
* Version Independent ID: a7fc6aa5-1ee2-d01b-b34f-090c83599df7
* Content: [C# Expressions - A tour of the C# language](https://docs.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/expressions)
* Content Source: [docs/csharp/tour-of-csharp/expressions.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tour-of-csharp/expressions.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for opening this issue @Gammerz26 

This is an artifact of migrating content to docs from multiple sources. We'll add those links in our next refresh of the content.
