### ISSUE TITLE
Reinstall Packages Using dotnet CLI

### ISSUE THREAD

**Issue by wgv-srsedate** [dotnet/docs#9909]
With packages targeting .NET Framework, we could run "Update-Package -Reinstall" to reinstall all packages for all projects in a solution.  This does not run against projects targeting .NET Standard or .NET Core.  How can we use the "dotnet" CLI to reinstall packages using their current versions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff30b638-44e3-077c-3cad-b61d1314c303
* Version Independent ID: 784413e1-77f5-f2e6-a8f4-56a73fe2d3bf
* Content: [dotnet add package command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-add-package)
* Content Source: [docs/core/tools/dotnet-add-package.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-add-package.md)
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
@KathleenDollard @livarcocc do you have any issue tracking reinstalling packages via the CLI?

**Comment by KathleenDollard** [comment]
@livarcocc is this us adding a switch, or NuGet adding a feature?

**Comment by livarcocc** [comment]
This is a NuGet feature ask. However, I am interested in knowing what is the scenario for needing such a feature.

Also, you could achieve the same by running `dotnet nuget locals all --clear` followed by a `dotnet restore` on the solution. That would wipe all the contents of the NuGet cache though, not just the solution's packages.

**Comment by JosephRT** [comment]
@livarcocc I've had two scenarios where that command is useful.  The first is where we're upgrading versions of .NET and we want to set the `targetFramework` to the new version.  `Get-Project -All | Update-Package -Reinstall` is useful for updating all of your solution's projects in one fell swoop.

The other is when myself and my team members have occasionally encountered what I've started calling the "Package Yellow Triangle of Death", where VS seems to think that a Nuget package is missing even though as far as we can tell it exists exactly where it's looking for it.  That same command is useful for fixing that particular issue.  There may be a better way, but frankly it's a pretty low effort fix for a problem that doesn't crop up too terribly often, so we're pretty OK with it.

**Comment by mairaw** [comment]
@livarcocc should I move this issue elsewhere?

**Comment by livarcocc** [comment]
I think at this point we should close this issue. If this is something that folks feel strongly about, I would suggest filling a new issue at nuget/home.

**Comment by mairaw** [comment]
Thanks @livarcocc for the feedback. Closing the doc issue then.
