### ISSUE TITLE
2 Links are dead

### ISSUE THREAD

**Issue by fridoo** [dotnet/docs#9912]
2 links in the 'See Also' section are dead:

*FTP Client Technology Sample
*FTP Explorer Technology Sample

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: b9294af6-b587-a35a-09b5-1605f626574e
* Version Independent ID: 5b00d11d-89c8-aee7-167b-592e28203b5a
* Content: [FTP](https://docs.microsoft.com/de-de/dotnet/framework/network-programming/ftp)
* Content Source: [docs/framework/network-programming/ftp.md](https://github.com/dotnet/docs.de-de/blob/live/docs/framework/network-programming/ftp.md)
* Product: **dotnet-framework**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

**Comment by mairaw** [comment]
Thanks @fridoo for your feedback. I'll remove the broken links in the English docs and then the localized version will be updated subsequently.
