### ISSUE TITLE
Naming conventions aren't always being followed in examples

### ISSUE THREAD

**Issue by Tourbill0n** [dotnet/docs#9915]
For example, "public int salary;" should be "public int Salary;" and constructor parameters should be in camel hump notation: 
"public Manager(int initialdata)" should be "public Manager(int initialData)"

Please keep in mind that people who visit these pages are likely newbies so even though this page isn't about naming conventions, it could cause confusion for those of us that are in the process of learning.  This has otherwise been excellent content for learning.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 374a58d4-1905-c664-04b6-fd68e617f8c9
* Version Independent ID: 36d0bf3a-29bf-5162-c700-142b03f9a16c
* Content: [Using Constructors - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/using-constructors)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/using-constructors.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/using-constructors.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
You make a good point @Tourbill0n 

I've added this to our backlog, given it the "up for grabs" label, and added it to our community contribution project. If no one picks it up, we'll address it when we update these pages.
