### ISSUE TITLE
Document the signature and behavior of the `Quote` CE member

### ISSUE THREAD

**Issue by baronfel** [dotnet/docs#9919]
There's some confusion on the F# Org slack about the purpose/usage of this member, and this document would be a great place to polish that up.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 247c440d-b855-0df1-f2db-076cd3393a0b
* Version Independent ID: 1cbccd4d-1721-e14f-7546-8fa868c965b1
* Content: [Computation Expressions - F#](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/computation-expressions#creating-a-new-type-of-computation-expression)
* Content Source: [docs/fsharp/language-reference/computation-expressions.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/language-reference/computation-expressions.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by cartermp** [comment]
In the [34th Restaurant & Bar](https://www.radissonblu.com/en/plazahotel-oslo/bars) near midnight in Oslo last year, @dsyme is on record saying, "Yeah, I put that baby in there" when @tpetricek added it to an insane CE we were creating for fun.

I cannot say I understand its purpose, as it literally doesn't matter what you say the body of it is. For example:

```fsharp
type System.Int32 with
    member __.Return x = x
    member __.Quote x = failwith "I dunno lol"

let x =
    12 {
        return 13
    }
```

Gives:

```
val x : Quotations.Expr<int> =
  Call (None, Int32.Return, [ValueWithName (12, builder@), Value (13)])
```

So I'm not sure what to document.

**Comment by dsyme** [comment]
Yes, the method is defined simply by its presence.  It is used in the implementation of `query { ... }`, e.g.

```
        /// <summary>
        /// A method used to support the F# query syntax.  Indicates that the query should be passed as a quotation to the Run method.
        /// </summary>
        member Quote  : Quotations.Expr<'T> -> Quotations.Expr<'T>
```

We could have cut this other ways, e.g. by using a `ReflectedDefinition` attribute on the parameter to `Run`, but, well, this is how we did it.
