### ISSUE TITLE
No info on nuget packages or workspace samples

### ISSUE THREAD

**Issue by willemodendaal** [dotnet/docs#9926]
I need to get started with Workspaces, but there are no code samples to demonstrate how these are used. There is also no info on which Nuget packages to install.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4bd716a-906d-983b-141c-4a4e2e2a79ec
* Version Independent ID: debed50c-98ce-ec0e-bcf6-0170a4e60fcc
* Content: [The .NET Compiler Platform SDK (Roslyn APIs)](https://docs.microsoft.com/en-gb/dotnet/csharp/roslyn-sdk/#feedback)
* Content Source: [docs/csharp/roslyn-sdk/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/roslyn-sdk/index.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for adding this feedback @willemodendaal This is an area where we need to invest more.

I've added it to our backlog.
