### ISSUE TITLE
How to run dotnet watch run with iis?

### ISSUE THREAD

**Issue by vovikdrg** [dotnet/docs#9927]
1. How to run dotnet watch with iis?
2. How to run dotnet with iis and targeting .net framework

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cc2e9c2-f333-f6a1-064e-790d950b684c
* Version Independent ID: 25a4c9b9-2808-e296-df03-5837000dcbad
* Content: [Get started with C# and Visual Studio Code - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/tutorials/with-visual-studio-code)
* Content Source: [docs/core/tutorials/with-visual-studio-code.md](https://github.com/dotnet/docs/blob/master/docs/core/tutorials/with-visual-studio-code.md)
* Product: **dotnet-core**
* GitHub Login: @kendrahavens
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
We don't cover the dotnet-watch tool in this repo @vovikdrg.

You can find a topic on docs about it at https://docs.microsoft.com/en-us/aspnet/core/tutorials/dotnet-watch.

And the product repo is located here if you have product questions: https://github.com/aspnet/AspNetCore/tree/master/src/Tools/dotnet-watch
