### ISSUE TITLE
Dynamically construct expressions

### ISSUE THREAD

**Issue by tsahi** [dotnet/docs#9929]
The examples on this page are relatively simple, and assume a certain knowledge on the values used to construct the filter. But what if you have to add `GradeLevel.FifthYear`? You'll have to change your code. To have a truly dynamic filter, you'll have to construct an expression using the static methods on `System.Linq.Expressions.Expression`, based on arbitrary input, and feed it to the `.Where()` method. Admittedly, this is much more difficult. Perhaps it's worth adding a page on that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cc236de-12ec-cb38-153f-377a4d1c3006
* Version Independent ID: f1701369-b459-35d3-51a2-c63f96cb3dda
* Content: [Dynamically specify predicate filters at runtime (LINQ in C#)](https://docs.microsoft.com/en-us/dotnet/csharp/linq/dynamically-specify-predicate-filters-at-runtime)
* Content Source: [docs/csharp/linq/dynamically-specify-predicate-filters-at-runtime.md](https://github.com/dotnet/docs/blob/master/docs/csharp/linq/dynamically-specify-predicate-filters-at-runtime.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment]
Thanks for pointing this out @tsahi This is an advanced scenario that we'll consider going forward.

**Comment by tsahi** [comment]
I actually created a set of helper methods that take a list of filters, where each filter has a property name, property type name and property value as string, and construct expressions based on that. But it's proprietary so I can't post it online.

**Comment by Unders0n** [comment]
can someone post such a code with expression builder please?

**Comment by zspitz** [comment]
@tsahi Using expressions requires the collection to be an `IQueryable`/`IQueryable<T>`, unless you're proposing to construct an expression tree, compile it to a delegate, and pass the delegate into `Enumerable.Where`.

Also, there's already a [page for dynamically constructing expression trees](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/expression-trees/how-to-use-expression-trees-to-build-dynamic-queries); Once [this PR](https://github.com/dotnet/docs/pull/22710#issuecomment-776044767) goes through, it'll look much better. (ping @Unders0n).

@dotnet/docs

Assuming that this page should be limited to techniques that can be used directly with `IEnumerable`/`IEnumerable<T>`, there should still be some reference to creating and dynamically manipulating expression trees.

Also, the code samples on this page have far too much noise in them. (Something is wrong if the first instruction in how to use `Contains` in a LINQ query is, "Open a new console application and name it `PredicateFilters`.).

`switch`-ing on an enum value to get different queries whose only distinction is the comparison on that enum value really doesn't make sense; it's far simpler to use the enum value within the query directly.

**Comment by tsahi** [comment]
@zspitz that's exactly what I mean. Once you construct an expression tree using the methods of `System.Linq.Expressions.Expression`, the only difference between feeding it to `Queryable.Where` and `Enumerable.Where` is that in the later case you need to call `.Compile()` on the expression.

I suppose I didn't see that page you linked to when I opened this bug.
