### ISSUE TITLE
Inheriting IDisposable is OK

### ISSUE THREAD

**Issue by Jesse-Hufstetler** [dotnet/docs#9931]
I don't believe [this section of this page](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-dispose#implementing-the-dispose-pattern-for-a-derived-class) should start by saying 
> A class derived from a class that implements the IDisposable interface shouldn't implement IDisposable, because the base class implementation of IDisposable.Dispose is inherited by its derived classes.

That makes it sound like if you inherit from an `IDisposable` you're doing something wrong. Instead, it seems that it should say 

> A class derived from a class that implements the IDisposable interface shouldn't **be marked as implementing** IDisposable, because the base class implementation of IDisposable.Dispose **already inherits it**.

(i.e., don't be redundant). Or perhaps, 

> A class derived from a class that implements the IDisposable interface shouldn't **carelessly** implement IDisposable, because the base class implementation of IDisposable.Dispose is inherited by its derived classes **and would be overwritten**.

(i.e., don't be careless).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 572ef6c6-5066-4a14-76a0-c3fb4b62e604
* Version Independent ID: 9c754da1-c234-fb12-580b-0fcf9ffe2c20
* Content: [Implementing a Dispose method](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-dispose)
* Content Source: [docs/standard/garbage-collection/implementing-dispose.md](https://github.com/dotnet/docs/blob/master/docs/standard/garbage-collection/implementing-dispose.md)
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by marchewek** [comment]
Imo the original text is perfectly fine. @Jesse-Hufstetler - one cannot "inherit from an IDisposable". It's possible to "inherit a class" or "implement an interface". One could argue if "shouldn't" in that sentence shouldn't be replaced with "doesn't have to", though for the sake of less redundancy I agree with "shouldn't". For me any class shouldn't list any of base class' interfaces.
