### ISSUE TITLE
Should explain how to install NUnit3.DotNetNew.Template

### ISSUE THREAD

**Issue by sebwills** [dotnet/docs#9942]
In my dotnet SDK 2.1 installation (installed by VSCode on macos), the NUnit3 template was not automatically installed. I had to run `dotnet new -i NUnit3.DotNetNew.Template` before `dotnet new unit`

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0063ceb-57ea-f30c-efed-b2a36314ccaa
* Version Independent ID: bd9a321e-2ef2-491d-cd37-2d9c66f90cc9
* Content: [Unit testing C# with NUnit and .NET Core - .NET Core](https://docs.microsoft.com/en-gb/dotnet/core/testing/unit-testing-with-nunit)
* Content Source: [docs/core/testing/unit-testing-with-nunit.md](https://github.com/dotnet/docs/blob/master/docs/core/testing/unit-testing-with-nunit.md)
* Product: **dotnet-core**
* GitHub Login: @rprouse
* Microsoft Alias: **mairaw**

**Comment by ChrisMaddock** [comment]
Hey @sebwills. I think NUnit templates were added to the .NET SDK in June 2018 in SDK 2.1.400. Could you take a look at which version you have installed?

cc @kendrahavens - who knows much more than I do about this!

**Comment by mikkelbu** [comment]
The hint to install the template was removed as part of #7204, see e.g. the diff here
https://github.com/dotnet/docs/pull/7318/files#diff-99cce5dbaee58bb65a75f26df1fb31c6L41

**Comment by sebwills** [comment]
Yeah, sorry, I was on 2.1.200. Now upgraded.
