### ISSUE TITLE
A great reference

### ISSUE THREAD

**Issue by stanuku** [dotnet/docs#9943]
Nice work, hope to see an update for v2.2 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ea0ea53-3bb6-a0ea-9674-384c68a77c2e
* Version Independent ID: 58e80b9e-a005-7f7b-98d6-bc8fe31998c0
* Content: [Seedwork (reusable base classes and interfaces for your domain model)](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/microservice-ddd-cqrs-patterns/seedwork-domain-model-base-classes-interfaces)
* Content Source: [docs/standard/microservices-architecture/microservice-ddd-cqrs-patterns/seedwork-domain-model-base-classes-interfaces.md](https://github.com/dotnet/docs/blob/master/docs/standard/microservices-architecture/microservice-ddd-cqrs-patterns/seedwork-domain-model-base-classes-interfaces.md)
* Product: **dotnet**
* GitHub Login: @CESARDELATORRE
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment]
Thanks for your feedback @stanuku. We have some open pull requests at the moment to start updating the book for 2.2. /cc @nishanil

**Comment by mvelosop** [comment]
Hi @mairaw, @stanuku,

The guide was updated to 2.2 a few weeks ago.

The code in this particular article is not using any special feature from EF 2.2, so the coment fro EF Core 1.1 is still valid, so it doesn't need to be updated.

Best,

**Comment by mairaw** [comment]
Given @mvelosop's response, I'm closing this but let us know if we're missing anything @stanuku!
