### ISSUE TITLE
Duplicate link

### ISSUE THREAD

**Issue by XamlBrewer** [dotnet/docs#9944]
Hi, 
The MissingValueIndicatorTransform appears twice in the Missing Values table.
Kind regards,
Diederik

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4185570-21cc-dcdb-62fd-d05bceb62f81
* Version Independent ID: 4f0fe52a-a771-d044-593d-2bb65df15e0d
* Content: [Machine learning data transforms - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/resources/transforms)
* Content Source: [docs/machine-learning/resources/transforms.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/resources/transforms.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by mairaw** [comment]
Thanks for your feedback @XamlBrewer. Would you like to submit a fix for this?
You can see how to do this at 
https://docs.microsoft.com/en-us/contribute/#quick-edits-to-existing-documents

**Comment by XamlBrewer** [comment]
Thanks for that link. PR done: #9950.
