### ISSUE TITLE
Example fails to run, imbalanced stack exception

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#9945]
@lgilson commented on [Fri Jan 11 2019](https://github.com/dotnet/docs.de-de/issues/121)

The first example on this page fails with a imbalanced stack exception at 

int res = LibWrap.TestStructInStruct(ref personAll); 

on the CS side. I'm using VS2017, x86 Release mode for all projects involved (as the x64 mode does not even load the dll). I guess it could be any of the C++ compiler settings. Is it possible to get a working ready-to-run sln for this?

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: d9466a98-6498-3816-8385-3fa97ce746e3
* Version Independent ID: b7eba3f0-803c-8895-56f6-633de8ec857d
* Content: [Marshallen von Klassen, Strukturen und Unions](https://docs.microsoft.com/de-de/dotnet/framework/interop/marshaling-classes-structures-and-unions)
* Content Source: [docs/framework/interop/marshaling-classes-structures-and-unions.md](https://github.com/dotnet/docs.de-de/blob/live/docs/framework/interop/marshaling-classes-structures-and-unions.md)
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

---

@lgilson commented on [Fri Jan 11 2019](https://github.com/dotnet/docs.de-de/issues/121#issuecomment-453481021)

Adding "CallingConvention = CallingConvention.Cdecl" into the [DllImport("..\\LIB\\PinvokeLib.dll")] lines solved the problem.

**Comment by rpetrusha** [comment]
@lgilson, thanks for the feedback. I can't reproduce this, though. Given the unmanaged DLL PInvokeLib.dll, the existing code runs successfully without specifying the CallingConvention field. It fails (and throws a BadImageFormatException) only if the platform of the source and the unmanaged library are different.

What platform are you trying to run the sample on?

**Comment by NextTurn** [comment]
@rpetrusha 

I can reproduce this on Windows. You will need to enable MDA.

https://docs.microsoft.com/en-us/dotnet/framework/debug-trace-profile/pinvokestackimbalance-mda

**Comment by lgilson** [comment]
I checked and seem to have MDA on. It runs as-is with MDA off.

Isn't MDA clean code required for stable operation?

> What platform are you trying to run the sample on?

Windows 10 64Bit, VS 2017, whatever the current update is. Setting the solution (composed of a C++ and a CS project) from "Any cpu" to x64 does not change the CS project because "prefer 32bit" is checked by default in the CS project. It does however change the C++ project leading to mismatched dlls. Unchecking "prefer 32bit" solves the 32 vs 64 bit problem.

**Comment by NextTurn** [comment]
I agree that `CallingConvention = CallingConvention.Cdecl` should be added in every `DllImport` attribute for custom libraries.
