### ISSUE TITLE
Color design absents in blocks with code

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#9947]
@PeskovV commented on [Fri Jan 11 2019](https://github.com/dotnet/docs.ru-ru/issues/163)

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 3b792311-e336-3237-65b9-a8cebc835448
* Version Independent ID: 48df4b5a-6b9d-1dd2-eaa4-80ab7f8223cf
* Content: [Пошаговое руководство. Создание кнопки с помощью XAML](https://docs.microsoft.com/ru-ru/dotnet/framework/wpf/controls/walkthrough-create-a-button-by-using-xaml)
* Content Source: [docs/framework/wpf/controls/walkthrough-create-a-button-by-using-xaml.md](https://github.com/dotnet/docs.ru-ru/blob/live/docs/framework/wpf/controls/walkthrough-create-a-button-by-using-xaml.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
hi team, 
I'm moving this here since the user is reporting missing data in the code

best

**Comment by rpetrusha** [comment]
I've addressed this by adding the `xaml` language identifiers to code blocks where they're missing, but inadvertently merged directly to live without opening a PR. Therefore, I'm closing this issue.

Спасибо, @PeskovV.
