### ISSUE TITLE
Example not working correctly - solution below

### ISSUE THREAD

**Issue by mihalicsb** [dotnet/docs#9948]
In this line: memoryGraphics.CopyFromScreen(this.Location.X, this.Location.Y, 0, 0, s);  the Form's location coordinates are wrong, and the created bitmap is a picture from the screen ( every opened window can be seen on it).
A working solution to this problem:
        private void CaptureScreen()
        {
            memoryImage = new Bitmap(this.Width, this.Height);
            this.DrawToBitmap(memoryImage, new Rectangle(0, 0, this.Width, this.Height));
        }

But even better if you put your Controls (Buttons, TextBoxes, etc.) into a panel and print it out (in this case I created a Panel named to panel1.:
private void CaptureScreen()
        {
            memoryImage = new Bitmap(panel1.Width, panel1.Height);
            this.DrawToBitmap(memoryImage, new Rectangle(0, 0, panel1.Width, panel1.Height));
        }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 746149df-9434-2623-921a-99bcc4efcc3d
* Version Independent ID: aea85d18-b6f1-2957-3022-9e1c579c0faa
* Content: [How to: Print a Windows Form](https://docs.microsoft.com/en-us/dotnet/framework/winforms/advanced/how-to-print-a-windows-form)
* Content Source: [docs/framework/winforms/advanced/how-to-print-a-windows-form.md](https://github.com/dotnet/docs/blob/master/docs/framework/winforms/advanced/how-to-print-a-windows-form.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mihalicsb** [comment]
Sorry: change this.DrawToBitmap(memoryImage, new Rectangle(0, 0, panel1.Width, panel1.Height)); 
 to
panel1.DrawToBitmap(memoryImage, new Rectangle(0, 0, panel1.Width, panel1.Height));

**Comment by cloudn9** [comment]
@mihalicsb Hello, I've just tested the official code from the article, and I got only the form printed, without any other windows. It seems working as it should.

p.s. attached the scanned doc
[img-200319214010.pdf](https://github.com/dotnet/docs/files/4356821/img-200319214010.pdf)
