### ISSUE TITLE
What nuget packages are part of .net core 2.2 runtime?

### ISSUE THREAD

**Issue by xavierjohn** [dotnet/docs#9951]
**Issue description**

When developing a class library that targets .net standard 2.0, I would like to know what nuget packages are part of the .net core 2.2 runtime so that I can prefer those packages and reduce my footprint. 
In other words, if my library is smart about the nuget packages it uses, the app using my library has to ship less assemblies when the target machine has .net core runtime 2.2 installed.

**Target framework**

Check the .NET target framework(s) being used, and include the version number(s).

- [ x ] .NET Core
- [ ] .NET Framework
- [ x ] .NET Standard

If using the .NET Core SDK, include `dotnet --info` output. If using .NET Framework without the .NET Core SDK, include info from Visual Studio's **Help** > **About Microsoft Visual Studio** dialog.

<details>
<summary><strong>dotnet --info output</strong> or <strong>About VS info</strong></summary>

```console
<replace>
```
</details>

**Comment by mairaw** [comment]
@terrajobst @JamesNK @richlander any ideas on how to solve this for library developers? Do we have such a list?
