### ISSUE TITLE
Inconsistent formatting of command line flags

### ISSUE THREAD

**Issue by ChrisMaddock** [dotnet/docs#9958]
**Issue description**

The [Sn.exe](https://docs.microsoft.com/en-us/dotnet/framework/tools/sn-exe-strong-name-tool) docs have inconsistent formatting of the command line flags.

![image](https://user-images.githubusercontent.com/4837132/51072467-29298c80-1659-11e9-9cae-a180d891c855.png)

Looking around, this seems inconsistent through all the [.NET Framework Tools](https://docs.microsoft.com/en-us/dotnet/framework/tools/) docs. If the team can add what _should_ be the standard, I thought this might make a good 'first-contribution' issue. 🙂

**Comment by mairaw** [comment]
Thanks for bringing this issue to our attention @ChrisMaddock.

There are two things we're standardizing on:
- Using - instead of / for options when the command supports it
- fencing the command names with backticks to prevent them from being translated in our localized versions

**Comment by lennartb-** [comment]
@mairaw I'd like to do this, but have a question to your second point. Can you clarify what's the preferred MD formatting on parameters? Should these be backticked too?

So for example

`**-v** *assembly*`

or

    `-v` `assembly`

or something else entirely? *Most* pages under [.NET Framework Tools](https://docs.microsoft.com/en-us/dotnet/framework/tools/) seem to have the first option, but it's a mix between all styles in between the different pages.
