### ISSUE TITLE
Links broken

### ISSUE THREAD

**Issue by alexhiggins732** [dotnet/docs#9961]
This link to the github sample in this article (and several other docs) are all broken. Can they be updated so they don't point to 404?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b1fb0dd-648b-26e9-7e4e-48824ab94160
* Version Independent ID: 689b6488-dadc-fd39-c432-ebf095a0299a
* Content: [Determine the feature importance of models with Permutation Feature Importance in ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/determine-global-feature-importance-in-model)
* Content Source: [docs/machine-learning/how-to-guides/determine-global-feature-importance-in-model.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/how-to-guides/determine-global-feature-importance-in-model.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by alexhiggins732** [comment]
Additional, broken link on this page: https://blogs.msdn.microsoft.com/dotnet/2018/12/04/announcing-ml-net-0-8-machine-learning-for-net/

**Comment by JRAlexander** [comment]
Thanks, @alexhiggins732! I've added this to the backlog and submitted a PR here: https://github.com/dotnet/docs/pull/9980

**Comment by JRAlexander** [comment]
@alexhiggins732, the links should all be corrected now. @CESARDELATORRE, can you take a look at the blog post mentioned?

**Comment by mairaw** [comment]
@JRAlexander I can help with the blog post update. What should be the new link to replace https://github.com/dotnet/machinelearning/blob/master/docs/samples/Microsoft.ML.Samples/Dynamic/PermutationFeatureImportance.cs?

**Comment by rauhs** [comment]
Link on this page still broken!
