### ISSUE TITLE
Understanding multi-column vectors

### ISSUE THREAD

**Issue by fedoranimus** [dotnet/docs#9962]
Is there a difference between using a single vector to represent multiple columns opposed to having each column be separately defined?

For example, as the documentation shows:
`new TextLoader.Column("FeatureVector", DataKind.R4, 0, 9),`

Would this be different to something like:
```
new TextLoaderColumn("FeatureColumn0", DataKind.R4, 0),
...
new TextLoader.Column("FeatureColumn9", DataKind.R4, 9),
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c38e868c-b14c-c2f0-f9b5-18ed478180a1
* Version Independent ID: 0b75761e-cdc9-1591-e8e4-551581e7a41d
* Content: [Load data with many columns from a CSV file for machine learning processing - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/load-data-from-mult-column-csv-ml-net)
* Content Source: [docs/machine-learning/how-to-guides/load-data-from-mult-column-csv-ml-net.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/how-to-guides/load-data-from-mult-column-csv-ml-net.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by JRAlexander** [comment]
@asthana86,  @CESARDELATORRE, @sfilipi - Any thoughts?

**Comment by fedoranimus** [comment]
If it makes more sense, I can open an issue on the actual machine learning repo, or ask a question on StackOverflow.

I feel the documentation should express this information ultimately, however.

**Comment by sfilipi** [comment]
Hi @fedoranimus, thanks for the question. In a typical pipeline, where you have the data transformation anda trainer at the end of it,  If the data type is all the same, and especially if it is all floats(System.Single), and you want to use all of them as Features, you either should load them all together as a vector, or you'd have to concatenate them into one before supplying them to a trainer (algorithm). 

If you want to do different things with your columns, like normalize some of them, but not others, or convert them to different formats, you can load them separately, perform the operations, than you'd still have to concatenate them in a single float vector, before passing them to the algorithm.

**Comment by JRAlexander** [comment]
Thanks, @sfilipi!!  Closing, as I believe this is resolved.
