### ISSUE TITLE
Migrating from Power Pack code

### ISSUE THREAD

**Issue by philtsmith570** [dotnet/docs#9964]
Since Power Packs are no longer supported ans are considered as is, Does MS have any input on migrating code using these functions?  Any alternatives? Methodology?

Bests,
-phil s

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41f021e2-2a1d-362a-96ac-e6c011a22905
* Version Independent ID: 379d2a59-2d89-4fda-9b3f-3b3de71b2757
* Content: [Deploying applications that reference Power Packs controls (Visual Studio)](https://docs.microsoft.com/en-us/dotnet/visual-basic/developing-apps/windows-forms/deploying-applications-that-reference-power-packs-controls-visual-studio)
* Content Source: [docs/visual-basic/developing-apps/windows-forms/deploying-applications-that-reference-power-packs-controls-visual-studio.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/developing-apps/windows-forms/deploying-applications-that-reference-power-packs-controls-visual-studio.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by mairaw** [comment]
@KathleenDollard can you comment on this issue? I'm wondering if we should retire this whole section on Power Packs controls and redirect them to the previous-versions content that is archived and no longer maintained - https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2010/cc488277(v=vs.100)?

**Comment by KathleenDollard** [comment]
I am sorry, but I am not aware of any guidance we have on this. 

Maira, I don't think these have been updated in nearly ten years, so yes, we should retire the section.

**Comment by mairaw** [comment]
I'll help with that then @KathleenDollard
