### ISSUE TITLE
Not supported in .Net Standard 2.0

### ISSUE THREAD

**Issue by MrM40** [dotnet/docs#9967]
When you try to compile:
error BC37234: Like operator is not supported in current project type.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bec570c0-3c04-a8d1-9f13-1696f93080a3
* Version Independent ID: ce60c1cc-649a-5bef-28b2-ac34108d9483
* Content: [Like Operator (Visual Basic)](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/operators/like-operator?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(vb.Like)%3Bk(DevLang-VB)%26rd%3Dtrue)
* Content Source: [docs/visual-basic/language-reference/operators/like-operator.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/language-reference/operators/like-operator.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by mairaw** [comment]
Hi @MrM40, thanks for your feedback. We'll need more information about your project and how you're building it to be able to better assist you. I'm wondering if this could be related to the following issue: https://github.com/dotnet/sdk/issues/1622

**Comment by MrM40** [comment]
It's a VB.Net Standard 2.0 project.
You cannot use the Like operator. It seems it has not been implemented (yet) in VB.Net Standard.
This is more a remark on the documentation page.
But if you thinking of implementing it, that would be great! :-)
Let me know if you need more info.

**Comment by KathleenDollard** [comment]
Is this a .NET Core project? Or a .NET Framework project targeting .NET Standard?

**Comment by KathleenDollard** [comment]
Is this a project you converted or a new project. 

The VB runtime has limited support in .NET Core. We are fixing this in .NET Core 3.0

**Comment by MrM40** [comment]
It's neither a NET Framework or .Net Core project, but a NET Standard 2.0 project (library). I don't know how I can say it more clearly ;-)
I guess Fixing it in Core 3.0 will not fix it in Net Standard, right?

To confirm the issue:
1: create a new Standard 2.0 project
2: Insert this code:
`Public Class Class1
    Sub test()
        If "String1" Like "String2" Then Debug.Print("The same")
    End Sub
End Class`
3: Compile:
4: You get the error: "Like operator is not supported in current project type."

it took my less the 20 seconds.

It's totally fine with me the like operator is not implemented.

I just put a remark on the documentation page in the "Content feedback" section, as it say nowhere which thas it's not implemented!
It's not really a bug report. But a comment to the documentation page.

But if you implemented it would be great :-)

**Comment by mairaw** [comment]
This still doesn't work with the preview version of .NET Core 3.0.

@KathleenDollard do we need to add a note to this topic about the lack of support in .NET Core/.NET Standard at the moment? Are you tracking the implementation somewhere else?
