### ISSUE TITLE
Replace `~/docs` links with `../` relative links

### ISSUE THREAD

**Issue by NextTurn** [dotnet/docs#9968]
There are a number of links starting with `~/` in the `dotnet/docs` repo that point to files in the repo itself. These can be replaced with relative links starting with `../`.

As described in [styleguide/template.md#internal-links](https://github.com/dotnet/docs/blob/master/styleguide/template.md#internal-links)

> In most cases, we use the relative links and discourage the use of ~/ in links because relative links resolve in the source on GitHub.

Related to #8364

**Comment by mairaw** [comment]
Thanks @NextTurn for filing this issue. I've added this issue to our backlog and our community project.

We prefer the relative links because they work on GH preview too but the ~ works fine for the content.

**Comment by nemrism** [comment]
I think I've covered all the `~/docs/` links with those PRs.
Do you think it should be useful to replace other kind of `~/` links?

**Comment by NextTurn** [comment]
Thanks a lot for your contributions @nemrism.

This issue could be better described as "Replace `~/docs` links". It is fine to close it when your PRs are merged.

**Comment by mairaw** [comment]
I changed the title then to cover that. Let's close this issue once all PRs are merged. Thank you so much @nemrism!

**Comment by nemrism** [comment]
There are still some `~/docs` links into `includes` root folder.
As it is supposed to be included files, I don't know if they need to be changed.

cc @rpetrusha @mairaw @NextTurn

**Comment by NextTurn** [comment]
@nemrism No, we don't need to replace those `~/` links in *includes* directory.

**Comment by mairaw** [comment]
Correct. Inside the includes folder, it's fine to keep them because they can be used in any article, so we don't know the path.
