### ISSUE TITLE
Example 1 throws error

### ISSUE THREAD

**Issue by WalrusPenguins** [dotnet/docs#9969]
Cat does not have a constructor which takes string name

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0efd6a6a-b52a-f6a2-d98b-f245b55115ff
* Version Independent ID: 95025282-20a0-ded8-c6d2-3b8ffff600c4
* Content: [Object and Collection Initializers - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/object-and-collection-initializers)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/object-and-collection-initializers.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/object-and-collection-initializers.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by NextTurn** [comment]
Fixed in dotnet/samples#550

**Comment by mairaw** [comment]
Thanks for your feedback @WalrusPenguins. As @NextTurn mentioned, this has been fixed.
