### ISSUE TITLE
Mention required version to consume symbol packages

### ISSUE THREAD

**Issue by cremor** [dotnet/docs#9970]
According to the [official announcement](https://blog.nuget.org/20181116/Improved-debugging-experience-with-the-NuGet-org-symbol-server-and-snupkg.html) you need Visual Studio 2017 15.9 to consume .snupkg files from the NuGet symbol server. I think this should be mentioned on the page. Although it doesn't change the current recommendation (which is to embed the symbol file in the main NuGet package), it is an additional requirement for all consumers that want to debug the library. Any library author that wants to provide symbols for older versions of Visual Studio can't use .snupkg files.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc2b4abb-c382-17ef-f1f3-1413ee27aaa0
* Version Independent ID: 4d4bb4d2-a8f4-f142-7154-40ce7fc7ae32
* Content: [NuGet and .NET libraries](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/nuget#symbol-packages)
* Content Source: [docs/standard/library-guidance/nuget.md](https://github.com/dotnet/docs/blob/master/docs/standard/library-guidance/nuget.md)
* Product: **dotnet**
* GitHub Login: @JamesNK
* Microsoft Alias: **mairaw**

**Comment by JamesNK** [comment]
Sure, it would be worth adding a note that Visual Studio 2017 15.9 or above is required to use the new symbol package format.
