### ISSUE TITLE
Cross threading

### ISSUE THREAD

**Issue by AteCoder** [dotnet/docs#9973]
Is this code safe for cross threading implementation? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68c0b0cc-a295-daca-b3d8-802b1cf871f0
* Version Independent ID: ab826459-c149-5925-1360-3fa8bb3de7c9
* Content: [How to: Implement the INotifyPropertyChanged Interface](https://docs.microsoft.com/en-us/dotnet/framework/winforms/how-to-implement-the-inotifypropertychanged-interface)
* Content Source: [docs/framework/winforms/how-to-implement-the-inotifypropertychanged-interface.md](https://github.com/dotnet/docs/blob/master/docs/framework/winforms/how-to-implement-the-inotifypropertychanged-interface.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by ghendric** [comment]
I have a form that has controls that I've bound to a bindinglist using this methodology. I ran across a problem where if you change a value of a field on the form and then click a button to save the change, the change isn't being captured by the propertychanged event unless I tab off of the control. Is there a way to capture the change that is being made in the field on the form without tabbing off it to another field?

**Comment by AteCoder** [comment]
setting the binding data source update mode to On Property Change might do the trick.  I believe the default is On Validation, which occurs when the control loses focus. 

https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.binding.datasourceupdatemode?view=netframework-4.7.2
