### ISSUE TITLE
Make each headline independent

### ISSUE THREAD

**Issue by Smedjebacka** [dotnet/docs#9976]
Make each headlined section independent, i.e. put the `dotnet publish` info also in the "Self-contained deployment with third-party dependencies" section, not only in the "... without third-party..." section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ee36626-0fc2-20d8-81c5-a3cd212244b2
* Version Independent ID: 044ba93c-9ad9-80c7-dc5c-27a80c9bd921
* Content: [Deploy .NET Core apps with command-line interface (CLI) tools - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/deploying/deploy-with-cli)
* Content Source: [docs/core/deploying/deploy-with-cli.md](https://github.com/dotnet/docs/blob/master/docs/core/deploying/deploy-with-cli.md)
* Product: **dotnet-core**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by Thraka** [comment]
@Smedjebacka I'm working rewriting this article and adding info about framework-dependent executables, and adding command line examples. I'm going to cross link this issue with my PR.
