### ISSUE TITLE
Link to Formatting Characters Would be Helpful

### ISSUE THREAD

**Issue by PatrickRyder** [dotnet/docs#9978]
In the above example, the speed of light is formatted using ":N3". A link to all the possible format specifiers that can be used would be great.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0665571-35b7-0841-5719-b69456b35cfb
* Version Independent ID: 0410420b-3b12-6d96-40cf-56f22ac19a1d
* Content: [$ - string interpolation - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/interpolated)
* Content Source: [docs/csharp/language-reference/tokens/interpolated.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/tokens/interpolated.md)
* Product: **dotnet-csharp**
* GitHub Login: @pkulikov
* Microsoft Alias: **ronpet**

**Comment by pkulikov** [comment]
@PatrickRyder #9981 adds the link to the table, which lists format specifiers for numeric types.

Given that, the table in the [Structure of an interpolated string](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/interpolated#structure-of-an-interpolated-string) section contains the link to the [Format String Component](https://docs.microsoft.com/en-us/dotnet/standard/base-types/composite-formatting#format-string-component) section, which provides an overview of format strings for various .NET types, including numerics as well.
