### ISSUE TITLE
Windows default directory path for DOTNET_PACKAGES is wrong

### ISSUE THREAD

**Issue by david1995** [dotnet/docs#9979]
I think the default Windows path for DOTNET_PACKAGES is wrong. As far as I know it should be ``%userprofile%\.nuget\packages``.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ba6c9b5-64cb-1dc6-21d0-ad8f0a1185fe
* Version Independent ID: 0f6c658c-b477-2d2c-2a9a-d74f6ae38d3f
* Content: [dotnet command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet?tabs=netcore21)
* Content Source: [docs/core/tools/dotnet.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet.md)
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment]
You're correct. Thanks for discovering and reporting this. @mairaw Do you want to do this as part of your 2.2 CLI update?

**Comment by mairaw** [comment]
Sure @Thraka!

**Comment by emrgcl** [comment]
Documentation needs this update. Still pointing to wrong path.
