### ISSUE TITLE
Dead link "ref directory"

### ISSUE THREAD

**Issue by ascott18** [dotnet/docs#9984]
&gt; The official specification is a set of .cs files that define the APIs that are part of the standard. The ref directory in the dotnet/standard repository defines the .NET Standard APIs.

The link to "ref directory" is a 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9eb8b774-c6f0-8235-6964-15219baf2ea7
* Version Independent ID: 6819a4a7-7527-d8c7-e132-767f7344e00e
* Content: [.NET Standard](https://docs.microsoft.com/en-us/dotnet/standard/net-standard)
* Content Source: [docs/standard/net-standard.md](https://github.com/dotnet/docs/blob/master/docs/standard/net-standard.md)
* Product: **dotnet**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by ascott18** [comment]
https://github.com/dotnet/standard/tree/master/netstandard/ref is the exact link that is 404ing

**Comment by mairaw** [comment]
Thaks for your feedback @ascott18. I've opened https://github.com/dotnet/docs/pull/9985 to fix this.
