### ISSUE TITLE
[core/rid-catalog] Suggestion to add an example of where RIDs are used in project.json

### ISSUE THREAD

**Issue by mairaw** [dotnet/docs#999]
Customer feedback posted at https://docs.microsoft.com/en-us/dotnet/articles/core/rid-catalog

This is great but can you use an example of where to define them ? i.e.

"runtimes": {
  "win10-x64": { },
    "osx.10.11-x64": { }
  }, in project.json file?

**Comment by stevehoag** [comment]
@mairaw Is this up for grabs or is it assigned to you? Seems like it should be one or the other.

**Comment by mairaw** [comment]
it's assigned to me since I won the topic, but if anyone wants to jump in, they can. Makes sense?

**Comment by rpetrusha** [comment]
@mairaw Rather than providing a standalone example, one option is to link to the section on self-contained deployment in the [deployment](https://docs.microsoft.com/en-us/dotnet/articles/core/deploying/index) topic, which has a complete example that builds an app for Windows 10 and OS X.

**Comment by stevehoag** [comment]
For me, seeing that an issue is assigned would lead me to believe it's no longer up for grabs, but maybe that's just me :-)

**Comment by Satindersatty** [comment]
This is the full example for Window 7 & OSX
https://github.com/Satindersatty/dotNetCore/blob/gh-pages/project.json_Window7Runtime
https://github.com/Satindersatty/dotNetCore/blob/gh-pages/Project.json_OSX

**Comment by mairaw** [comment]
@livarcocc is this still applicable with csproj?

**Comment by livarcocc** [comment]
Yes. In csproj you can have RuntimeIdentifier (for a single one) or RuntimeIdentifiers (when you have multiples):


https://github.com/dotnet/cli/blob/master/TestAssets/TestProjects/MSBuildTestApp/MSBuildTestApp.csproj#L7

**Comment by BillWagner** [comment]
@mairaw I think this can be closed based on these:

https://docs.microsoft.com/en-us/dotnet/core/packages
https://docs.microsoft.com/en-us/dotnet/core/rid-catalog

If you agree, go ahead and close it.
