### ISSUE TITLE
Visual Studio on Mac

### ISSUE THREAD

**Issue by wuidakaiser** [dotnet/docs#9998]
Hello,
I used Visual Basic on Windows and want now to move to Mac. I installed Visual Studio for Mac, can take over from Windows some  console apps but not Form-based projects. When I try building a new Windows based project I'm missing a toolbox with all the gages I found under Windows. What do I need to do to be able to create a Form-based program under Visual Basic?
Thanks in advance!
Wuidakaiser

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 581f6cbb-c666-87ee-ab0c-f131baca403c
* Version Independent ID: 9205f603-e1d4-e0eb-1273-f176fcbf520f
* Content: [About .NET Core](https://docs.microsoft.com/en-us/dotnet/core/about#feedback)
* Content Source: [docs/core/about.md](https://github.com/dotnet/docs/blob/master/docs/core/about.md)
* Product: **dotnet-core**
* GitHub Login: @richlander
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Hi @wuidakaiser! Are you talking about Windows Forms projects? If so, you can't develop that on Visual Studio for Mac.
See this topic for more information:
https://docs.microsoft.com/en-us/visualstudio/productinfo/vs2017-compatibility-mac#feature-summary

> Visual Studio for Mac does not support Windows client projects like Windows Forms, WPF, or UWP.

For that reason, I'm closing this issue. But if for some reason, I misunderstood your question, please let us know.

**Comment by wuidakaiser** [comment]
Hello,
Reading the Info from the  link you gave me I learned that I have to use Xamarin/Xcode in order to create a UI for my app. Thus I have to learn how to use a new tool and a new language (C#). A good task for the new year!
Thanks and have a good time!
Ernst
